#ifndef DETAIL_XTE_HEADER_PREPROC_COMPILER
#	define DETAIL_XTE_HEADER_PREPROC_COMPILER
#
#	define XTE_COMPILER_ACC 0
#	define XTE_COMPILER_ACC_MAJOR 0
#	define XTE_COMPILER_ACC_MINOR 0
#	define XTE_COMPILER_ACC_PATCH 0
#	define XTE_COMPILER_ACC_TWEAK 0
#	define XTE_COMPILER_ACK 0
#	define XTE_COMPILER_ACK_MAJOR 0
#	define XTE_COMPILER_ACK_MINOR 0
#	define XTE_COMPILER_ACK_PATCH 0
#	define XTE_COMPILER_ACK_TWEAK 0
#	define XTE_COMPILER_ADSP 0
#	define XTE_COMPILER_ADSP_MAJOR 0
#	define XTE_COMPILER_ADSP_MINOR 0
#	define XTE_COMPILER_ADSP_PATCH 0
#	define XTE_COMPILER_ADSP_TWEAK 0
#	define XTE_COMPILER_AHCC 0
#	define XTE_COMPILER_AHCC_MAJOR 0
#	define XTE_COMPILER_AHCC_MINOR 0
#	define XTE_COMPILER_AHCC_PATCH 0
#	define XTE_COMPILER_AHCC_TWEAK 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MAJOR 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MINOR 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_PATCH 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_TWEAK 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MAJOR 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MINOR 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C_PATCH 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C_TWEAK 0
#	define XTE_COMPILER_AOCC 0
#	define XTE_COMPILER_AOCC_MAJOR 0
#	define XTE_COMPILER_AOCC_MINOR 0
#	define XTE_COMPILER_AOCC_PATCH 0
#	define XTE_COMPILER_AOCC_TWEAK 0
#	define XTE_COMPILER_APPLE_CLANG 0
#	define XTE_COMPILER_APPLE_CLANG_MAJOR 0
#	define XTE_COMPILER_APPLE_CLANG_MINOR 0
#	define XTE_COMPILER_APPLE_CLANG_PATCH 0
#	define XTE_COMPILER_APPLE_CLANG_TWEAK 0
#	define XTE_COMPILER_ARMCC 0
#	define XTE_COMPILER_ARMCC_MAJOR 0
#	define XTE_COMPILER_ARMCC_MINOR 0
#	define XTE_COMPILER_ARMCC_PATCH 0
#	define XTE_COMPILER_ARMCC_TWEAK 0
#	define XTE_COMPILER_AZTEC_C 0
#	define XTE_COMPILER_AZTEC_C_MAJOR 0
#	define XTE_COMPILER_AZTEC_C_MINOR 0
#	define XTE_COMPILER_AZTEC_C_PATCH 0
#	define XTE_COMPILER_AZTEC_C_TWEAK 0
#	define XTE_COMPILER_BORLAND 0
#	define XTE_COMPILER_BORLAND_MAJOR 0
#	define XTE_COMPILER_BORLAND_MINOR 0
#	define XTE_COMPILER_BORLAND_PATCH 0
#	define XTE_COMPILER_BORLAND_TWEAK 0
#	define XTE_COMPILER_BRUCE 0
#	define XTE_COMPILER_BRUCE_MAJOR 0
#	define XTE_COMPILER_BRUCE_MINOR 0
#	define XTE_COMPILER_BRUCE_PATCH 0
#	define XTE_COMPILER_BRUCE_TWEAK 0
#	define XTE_COMPILER_C2 0
#	define XTE_COMPILER_C2_MAJOR 0
#	define XTE_COMPILER_C2_MINOR 0
#	define XTE_COMPILER_C2_PATCH 0
#	define XTE_COMPILER_C2_TWEAK 0
#	define XTE_COMPILER_CASTXML 0
#	define XTE_COMPILER_CASTXML_MAJOR 0
#	define XTE_COMPILER_CASTXML_MINOR 0
#	define XTE_COMPILER_CASTXML_PATCH 0
#	define XTE_COMPILER_CASTXML_TWEAK 0
#	define XTE_COMPILER_CC65 0
#	define XTE_COMPILER_CC65_MAJOR 0
#	define XTE_COMPILER_CC65_MINOR 0
#	define XTE_COMPILER_CC65_PATCH 0
#	define XTE_COMPILER_CC65_TWEAK 0
#	define XTE_COMPILER_CILLY 0
#	define XTE_COMPILER_CILLY_MAJOR 0
#	define XTE_COMPILER_CILLY_MINOR 0
#	define XTE_COMPILER_CILLY_PATCH 0
#	define XTE_COMPILER_CILLY_TWEAK 0
#	define XTE_COMPILER_CIRCLE 0
#	define XTE_COMPILER_CIRCLE_MAJOR 0
#	define XTE_COMPILER_CIRCLE_MINOR 0
#	define XTE_COMPILER_CIRCLE_PATCH 0
#	define XTE_COMPILER_CIRCLE_TWEAK 0
#	define XTE_COMPILER_CLANG 0
#	define XTE_COMPILER_CLANG_MAJOR 0
#	define XTE_COMPILER_CLANG_MINOR 0
#	define XTE_COMPILER_CLANG_PATCH 0
#	define XTE_COMPILER_CLANG_TWEAK 0
#	define XTE_COMPILER_COMEAU 0
#	define XTE_COMPILER_COMEAU_MAJOR 0
#	define XTE_COMPILER_COMEAU_MINOR 0
#	define XTE_COMPILER_COMEAU_PATCH 0
#	define XTE_COMPILER_COMEAU_TWEAK 0
#	define XTE_COMPILER_COMPAQ 0
#	define XTE_COMPILER_COMPAQ_MAJOR 0
#	define XTE_COMPILER_COMPAQ_MINOR 0
#	define XTE_COMPILER_COMPAQ_PATCH 0
#	define XTE_COMPILER_COMPAQ_TWEAK 0
#	define XTE_COMPILER_COMPCERT 0
#	define XTE_COMPILER_COMPCERT_MAJOR 0
#	define XTE_COMPILER_COMPCERT_MINOR 0
#	define XTE_COMPILER_COMPCERT_PATCH 0
#	define XTE_COMPILER_COMPCERT_TWEAK 0
#	define XTE_COMPILER_CONVEX_C 0
#	define XTE_COMPILER_CONVEX_C_MAJOR 0
#	define XTE_COMPILER_CONVEX_C_MINOR 0
#	define XTE_COMPILER_CONVEX_C_PATCH 0
#	define XTE_COMPILER_CONVEX_C_TWEAK 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER_MAJOR 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER_MINOR 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER_PATCH 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER_TWEAK 0
#	define XTE_COMPILER_CRAY 0
#	define XTE_COMPILER_CRAY_MAJOR 0
#	define XTE_COMPILER_CRAY_MINOR 0
#	define XTE_COMPILER_CRAY_PATCH 0
#	define XTE_COMPILER_CRAY_TWEAK 0
#	define XTE_COMPILER_DIGITAL_MARS 0
#	define XTE_COMPILER_DIGITAL_MARS_MAJOR 0
#	define XTE_COMPILER_DIGITAL_MARS_MINOR 0
#	define XTE_COMPILER_DIGITAL_MARS_PATCH 0
#	define XTE_COMPILER_DIGITAL_MARS_TWEAK 0
#	define XTE_COMPILER_DICE_C 0
#	define XTE_COMPILER_DICE_C_MAJOR 0
#	define XTE_COMPILER_DICE_C_MINOR 0
#	define XTE_COMPILER_DICE_C_PATCH 0
#	define XTE_COMPILER_DICE_C_TWEAK 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MAJOR 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MINOR 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_PATCH 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_TWEAK 0
#	define XTE_COMPILER_DJGPP 0
#	define XTE_COMPILER_DJGPP_MAJOR 0
#	define XTE_COMPILER_DJGPP_MINOR 0
#	define XTE_COMPILER_DJGPP_PATCH 0
#	define XTE_COMPILER_DJGPP_TWEAK 0
#	define XTE_COMPILER_EDG 0
#	define XTE_COMPILER_EDG_MAJOR 0
#	define XTE_COMPILER_EDG_MINOR 0
#	define XTE_COMPILER_EDG_PATCH 0
#	define XTE_COMPILER_EDG_TWEAK 0
#	define XTE_COMPILER_EKOPATH 0
#	define XTE_COMPILER_EKOPATH_MAJOR 0
#	define XTE_COMPILER_EKOPATH_MINOR 0
#	define XTE_COMPILER_EKOPATH_PATCH 0
#	define XTE_COMPILER_EKOPATH_TWEAK 0
#	define XTE_COMPILER_ELLCC 0
#	define XTE_COMPILER_ELLCC_MAJOR 0
#	define XTE_COMPILER_ELLCC_MINOR 0
#	define XTE_COMPILER_ELLCC_PATCH 0
#	define XTE_COMPILER_ELLCC_TWEAK 0
#	define XTE_COMPILER_EMBARCADERO 0
#	define XTE_COMPILER_EMBARCADERO_MAJOR 0
#	define XTE_COMPILER_EMBARCADERO_MINOR 0
#	define XTE_COMPILER_EMBARCADERO_PATCH 0
#	define XTE_COMPILER_EMBARCADERO_TWEAK 0
#	define XTE_COMPILER_FLANG 0
#	define XTE_COMPILER_FLANG_MAJOR 0
#	define XTE_COMPILER_FLANG_MINOR 0
#	define XTE_COMPILER_FLANG_PATCH 0
#	define XTE_COMPILER_FLANG_TWEAK 0
#	define XTE_COMPILER_FUJITSU_CPP 0
#	define XTE_COMPILER_FUJITSU_CPP_MAJOR 0
#	define XTE_COMPILER_FUJITSU_CPP_MINOR 0
#	define XTE_COMPILER_FUJITSU_CPP_PATCH 0
#	define XTE_COMPILER_FUJITSU_CPP_TWEAK 0
#	define XTE_COMPILER_GCC 0
#	define XTE_COMPILER_GCC_MAJOR 0
#	define XTE_COMPILER_GCC_MINOR 0
#	define XTE_COMPILER_GCC_PATCH 0
#	define XTE_COMPILER_GCC_TWEAK 0
#	define XTE_COMPILER_GCCXML 0
#	define XTE_COMPILER_GCCXML_MAJOR 0
#	define XTE_COMPILER_GCCXML_MINOR 0
#	define XTE_COMPILER_GCCXML_PATCH 0
#	define XTE_COMPILER_GCCXML_TWEAK 0
#	define XTE_COMPILER_GREEN_HILLS 0
#	define XTE_COMPILER_GREEN_HILLS_MAJOR 0
#	define XTE_COMPILER_GREEN_HILLS_MINOR 0
#	define XTE_COMPILER_GREEN_HILLS_PATCH 0
#	define XTE_COMPILER_GREEN_HILLS_TWEAK 0
#	define XTE_COMPILER_HEXAGON 0
#	define XTE_COMPILER_HEXAGON_MAJOR 0
#	define XTE_COMPILER_HEXAGON_MINOR 0
#	define XTE_COMPILER_HEXAGON_PATCH 0
#	define XTE_COMPILER_HEXAGON_TWEAK 0
#	define XTE_COMPILER_HIPCC 0
#	define XTE_COMPILER_HIPCC_MAJOR 0
#	define XTE_COMPILER_HIPCC_MINOR 0
#	define XTE_COMPILER_HIPCC_PATCH 0
#	define XTE_COMPILER_HIPCC_TWEAK 0
#	define XTE_COMPILER_HPUX 0
#	define XTE_COMPILER_HPUX_MAJOR 0
#	define XTE_COMPILER_HPUX_MINOR 0
#	define XTE_COMPILER_HPUX_PATCH 0
#	define XTE_COMPILER_HPUX_TWEAK 0
#	define XTE_COMPILER_HSC 0
#	define XTE_COMPILER_HSC_MAJOR 0
#	define XTE_COMPILER_HSC_MINOR 0
#	define XTE_COMPILER_HSC_PATCH 0
#	define XTE_COMPILER_HSC_TWEAK 0
#	define XTE_COMPILER_IAR 0
#	define XTE_COMPILER_IAR_MAJOR 0
#	define XTE_COMPILER_IAR_MINOR 0
#	define XTE_COMPILER_IAR_PATCH 0
#	define XTE_COMPILER_IAR_TWEAK 0
#	define XTE_COMPILER_IBM_OPEN_XL 0
#	define XTE_COMPILER_IBM_OPEN_XL_MAJOR 0
#	define XTE_COMPILER_IBM_OPEN_XL_MINOR 0
#	define XTE_COMPILER_IBM_OPEN_XL_PATCH 0
#	define XTE_COMPILER_IBM_OPEN_XL_TWEAK 0
#	define XTE_COMPILER_IBM_XL 0
#	define XTE_COMPILER_IBM_XL_MAJOR 0
#	define XTE_COMPILER_IBM_XL_MINOR 0
#	define XTE_COMPILER_IBM_XL_PATCH 0
#	define XTE_COMPILER_IBM_XL_TWEAK 0
#	define XTE_COMPILER_IBM_XL_CLANG 0
#	define XTE_COMPILER_IBM_XL_CLANG_MAJOR 0
#	define XTE_COMPILER_IBM_XL_CLANG_MINOR 0
#	define XTE_COMPILER_IBM_XL_CLANG_PATCH 0
#	define XTE_COMPILER_IBM_XL_CLANG_TWEAK 0
#	define XTE_COMPILER_IBM_Z_OS_XL 0
#	define XTE_COMPILER_IBM_Z_OS_XL_MAJOR 0
#	define XTE_COMPILER_IBM_Z_OS_XL_MINOR 0
#	define XTE_COMPILER_IBM_Z_OS_XL_PATCH 0
#	define XTE_COMPILER_IBM_Z_OS_XL_TWEAK 0
#	define XTE_COMPILER_ICC 0
#	define XTE_COMPILER_ICC_MAJOR 0
#	define XTE_COMPILER_ICC_MINOR 0
#	define XTE_COMPILER_ICC_PATCH 0
#	define XTE_COMPILER_ICC_TWEAK 0
#	define XTE_COMPILER_ICX 0
#	define XTE_COMPILER_ICX_MAJOR 0
#	define XTE_COMPILER_ICX_MINOR 0
#	define XTE_COMPILER_ICX_PATCH 0
#	define XTE_COMPILER_ICX_TWEAK 0
#	define XTE_COMPILER_IMAGECRAFT_C 0
#	define XTE_COMPILER_IMAGECRAFT_C_MAJOR 0
#	define XTE_COMPILER_IMAGECRAFT_C_MINOR 0
#	define XTE_COMPILER_IMAGECRAFT_C_PATCH 0
#	define XTE_COMPILER_IMAGECRAFT_C_TWEAK 0
#	define XTE_COMPILER_KCC 0
#	define XTE_COMPILER_KCC_MAJOR 0
#	define XTE_COMPILER_KCC_MINOR 0
#	define XTE_COMPILER_KCC_PATCH 0
#	define XTE_COMPILER_KCC_TWEAK 0
#	define XTE_COMPILER_KEIL_C166 0
#	define XTE_COMPILER_KEIL_C166_MAJOR 0
#	define XTE_COMPILER_KEIL_C166_MINOR 0
#	define XTE_COMPILER_KEIL_C166_PATCH 0
#	define XTE_COMPILER_KEIL_C166_TWEAK 0
#	define XTE_COMPILER_KEIL_C51 0
#	define XTE_COMPILER_KEIL_C51_MAJOR 0
#	define XTE_COMPILER_KEIL_C51_MINOR 0
#	define XTE_COMPILER_KEIL_C51_PATCH 0
#	define XTE_COMPILER_KEIL_C51_TWEAK 0
#	define XTE_COMPILER_KEIL_CARM 0
#	define XTE_COMPILER_KEIL_CARM_MAJOR 0
#	define XTE_COMPILER_KEIL_CARM_MINOR 0
#	define XTE_COMPILER_KEIL_CARM_PATCH 0
#	define XTE_COMPILER_KEIL_CARM_TWEAK 0
#	define XTE_COMPILER_KICKC 0
#	define XTE_COMPILER_KICKC_MAJOR 0
#	define XTE_COMPILER_KICKC_MINOR 0
#	define XTE_COMPILER_KICKC_PATCH 0
#	define XTE_COMPILER_KICKC_TWEAK 0
#	define XTE_COMPILER_LATTICE_C 0
#	define XTE_COMPILER_LATTICE_C_MAJOR 0
#	define XTE_COMPILER_LATTICE_C_MINOR 0
#	define XTE_COMPILER_LATTICE_C_PATCH 0
#	define XTE_COMPILER_LATTICE_C_TWEAK 0
#	define XTE_COMPILER_LCC 0
#	define XTE_COMPILER_LCC_MAJOR 0
#	define XTE_COMPILER_LCC_MINOR 0
#	define XTE_COMPILER_LCC_PATCH 0
#	define XTE_COMPILER_LCC_TWEAK 0
#	define XTE_COMPILER_LIGHTSPEED_C 0
#	define XTE_COMPILER_LIGHTSPEED_C_MAJOR 0
#	define XTE_COMPILER_LIGHTSPEED_C_MINOR 0
#	define XTE_COMPILER_LIGHTSPEED_C_PATCH 0
#	define XTE_COMPILER_LIGHTSPEED_C_TWEAK 0
#	define XTE_COMPILER_LLVM 0
#	define XTE_COMPILER_LLVM_MAJOR 0
#	define XTE_COMPILER_LLVM_MINOR 0
#	define XTE_COMPILER_LLVM_PATCH 0
#	define XTE_COMPILER_LLVM_TWEAK 0
#	define XTE_COMPILER_MCST_LLC 0
#	define XTE_COMPILER_MCST_LLC_MAJOR 0
#	define XTE_COMPILER_MCST_LLC_MINOR 0
#	define XTE_COMPILER_MCST_LLC_PATCH 0
#	define XTE_COMPILER_MCST_LLC_TWEAK 0
#	define XTE_COMPILER_METAWARE_HIGH 0
#	define XTE_COMPILER_METAWARE_HIGH_MAJOR 0
#	define XTE_COMPILER_METAWARE_HIGH_MINOR 0
#	define XTE_COMPILER_METAWARE_HIGH_PATCH 0
#	define XTE_COMPILER_METAWARE_HIGH_TWEAK 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR_TWEAK 0
#	define XTE_COMPILER_MICROTEC 0
#	define XTE_COMPILER_MICROTEC_MAJOR 0
#	define XTE_COMPILER_MICROTEC_MINOR 0
#	define XTE_COMPILER_MICROTEC_PATCH 0
#	define XTE_COMPILER_MICROTEC_TWEAK 0
#	define XTE_COMPILER_MICROWAY_NDP_C 0
#	define XTE_COMPILER_MICROWAY_NDP_C_MAJOR 0
#	define XTE_COMPILER_MICROWAY_NDP_C_MINOR 0
#	define XTE_COMPILER_MICROWAY_NDP_C_PATCH 0
#	define XTE_COMPILER_MICROWAY_NDP_C_TWEAK 0
#	define XTE_COMPILER_MINGW32 0
#	define XTE_COMPILER_MINGW32_MAJOR 0
#	define XTE_COMPILER_MINGW32_MINOR 0
#	define XTE_COMPILER_MINGW32_PATCH 0
#	define XTE_COMPILER_MINGW32_TWEAK 0
#	define XTE_COMPILER_MINGW_W64 0
#	define XTE_COMPILER_MINGW_W64_MAJOR 0
#	define XTE_COMPILER_MINGW_W64_MINOR 0
#	define XTE_COMPILER_MINGW_W64_PATCH 0
#	define XTE_COMPILER_MINGW_W64_TWEAK 0
#	define XTE_COMPILER_MIPSPRO 0
#	define XTE_COMPILER_MIPSPRO_MAJOR 0
#	define XTE_COMPILER_MIPSPRO_MINOR 0
#	define XTE_COMPILER_MIPSPRO_PATCH 0
#	define XTE_COMPILER_MIPSPRO_TWEAK 0
#	define XTE_COMPILER_MIRACLE_C 0
#	define XTE_COMPILER_MIRACLE_C_MAJOR 0
#	define XTE_COMPILER_MIRACLE_C_MINOR 0
#	define XTE_COMPILER_MIRACLE_C_PATCH 0
#	define XTE_COMPILER_MIRACLE_C_TWEAK 0
#	define XTE_COMPILER_MPW 0
#	define XTE_COMPILER_MPW_MAJOR 0
#	define XTE_COMPILER_MPW_MINOR 0
#	define XTE_COMPILER_MPW_PATCH 0
#	define XTE_COMPILER_MPW_TWEAK 0
#	define XTE_COMPILER_MSVC 0
#	define XTE_COMPILER_MSVC_MAJOR 0
#	define XTE_COMPILER_MSVC_MINOR 0
#	define XTE_COMPILER_MSVC_PATCH 0
#	define XTE_COMPILER_MSVC_TWEAK 0
#	define XTE_COMPILER_NCC 0
#	define XTE_COMPILER_NCC_MAJOR 0
#	define XTE_COMPILER_NCC_MINOR 0
#	define XTE_COMPILER_NCC_PATCH 0
#	define XTE_COMPILER_NCC_TWEAK 0
#	define XTE_COMPILER_NORCROFT_C 0
#	define XTE_COMPILER_NORCROFT_C_MAJOR 0
#	define XTE_COMPILER_NORCROFT_C_MINOR 0
#	define XTE_COMPILER_NORCROFT_C_PATCH 0
#	define XTE_COMPILER_NORCROFT_C_TWEAK 0
#	define XTE_COMPILER_NVIDIA_HPC 0
#	define XTE_COMPILER_NVIDIA_HPC_MAJOR 0
#	define XTE_COMPILER_NVIDIA_HPC_MINOR 0
#	define XTE_COMPILER_NVIDIA_HPC_PATCH 0
#	define XTE_COMPILER_NVIDIA_HPC_TWEAK 0
#	define XTE_COMPILER_NVCC 0
#	define XTE_COMPILER_NVCC_MAJOR 0
#	define XTE_COMPILER_NVCC_MINOR 0
#	define XTE_COMPILER_NVCC_PATCH 0
#	define XTE_COMPILER_NVCC_TWEAK 0
#	define XTE_COMPILER_NWCC 0
#	define XTE_COMPILER_NWCC_MAJOR 0
#	define XTE_COMPILER_NWCC_MINOR 0
#	define XTE_COMPILER_NWCC_PATCH 0
#	define XTE_COMPILER_NWCC_TWEAK 0
#	define XTE_COMPILER_OCC 0
#	define XTE_COMPILER_OCC_MAJOR 0
#	define XTE_COMPILER_OCC_MINOR 0
#	define XTE_COMPILER_OCC_PATCH 0
#	define XTE_COMPILER_OCC_TWEAK 0
#	define XTE_COMPILER_OPEN64 0
#	define XTE_COMPILER_OPEN64_MAJOR 0
#	define XTE_COMPILER_OPEN64_MINOR 0
#	define XTE_COMPILER_OPEN64_PATCH 0
#	define XTE_COMPILER_OPEN64_TWEAK 0
#	define XTE_COMPILER_OPENACC 0
#	define XTE_COMPILER_OPENACC_MAJOR 0
#	define XTE_COMPILER_OPENACC_MINOR 0
#	define XTE_COMPILER_OPENACC_PATCH 0
#	define XTE_COMPILER_OPENACC_TWEAK 0
#	define XTE_COMPILER_OPENSERVER 0
#	define XTE_COMPILER_OPENSERVER_MAJOR 0
#	define XTE_COMPILER_OPENSERVER_MINOR 0
#	define XTE_COMPILER_OPENSERVER_PATCH 0
#	define XTE_COMPILER_OPENSERVER_TWEAK 0
#	define XTE_COMPILER_ORACLE_PRO_C 0
#	define XTE_COMPILER_ORACLE_PRO_C_MAJOR 0
#	define XTE_COMPILER_ORACLE_PRO_C_MINOR 0
#	define XTE_COMPILER_ORACLE_PRO_C_PATCH 0
#	define XTE_COMPILER_ORACLE_PRO_C_TWEAK 0
#	define XTE_COMPILER_ORACLE_SUN 0
#	define XTE_COMPILER_ORACLE_SUN_MAJOR 0
#	define XTE_COMPILER_ORACLE_SUN_MINOR 0
#	define XTE_COMPILER_ORACLE_SUN_PATCH 0
#	define XTE_COMPILER_ORACLE_SUN_TWEAK 0
#	define XTE_COMPILER_ORANGE_C 0
#	define XTE_COMPILER_ORANGE_C_MAJOR 0
#	define XTE_COMPILER_ORANGE_C_MINOR 0
#	define XTE_COMPILER_ORANGE_C_PATCH 0
#	define XTE_COMPILER_ORANGE_C_TWEAK 0
#	define XTE_COMPILER_PACIFIC_C 0
#	define XTE_COMPILER_PACIFIC_C_MAJOR 0
#	define XTE_COMPILER_PACIFIC_C_MINOR 0
#	define XTE_COMPILER_PACIFIC_C_PATCH 0
#	define XTE_COMPILER_PACIFIC_C_TWEAK 0
#	define XTE_COMPILER_PALM 0
#	define XTE_COMPILER_PALM_MAJOR 0
#	define XTE_COMPILER_PALM_MINOR 0
#	define XTE_COMPILER_PALM_PATCH 0
#	define XTE_COMPILER_PALM_TWEAK 0
#	define XTE_COMPILER_PCC 0
#	define XTE_COMPILER_PCC_MAJOR 0
#	define XTE_COMPILER_PCC_MINOR 0
#	define XTE_COMPILER_PCC_PATCH 0
#	define XTE_COMPILER_PCC_TWEAK 0
#	define XTE_COMPILER_PELLES_C 0
#	define XTE_COMPILER_PELLES_C_MAJOR 0
#	define XTE_COMPILER_PELLES_C_MINOR 0
#	define XTE_COMPILER_PELLES_C_PATCH 0
#	define XTE_COMPILER_PELLES_C_TWEAK 0
#	define XTE_COMPILER_PGI 0
#	define XTE_COMPILER_PGI_MAJOR 0
#	define XTE_COMPILER_PGI_MINOR 0
#	define XTE_COMPILER_PGI_PATCH 0
#	define XTE_COMPILER_PGI_TWEAK 0
#	define XTE_COMPILER_PUREC 0
#	define XTE_COMPILER_PUREC_MAJOR 0
#	define XTE_COMPILER_PUREC_MINOR 0
#	define XTE_COMPILER_PUREC_PATCH 0
#	define XTE_COMPILER_PUREC_TWEAK 0
#	define XTE_COMPILER_PW32 0
#	define XTE_COMPILER_PW32_MAJOR 0
#	define XTE_COMPILER_PW32_MINOR 0
#	define XTE_COMPILER_PW32_PATCH 0
#	define XTE_COMPILER_PW32_TWEAK 0
#	define XTE_COMPILER_QUICKC 0
#	define XTE_COMPILER_QUICKC_MAJOR 0
#	define XTE_COMPILER_QUICKC_MINOR 0
#	define XTE_COMPILER_QUICKC_PATCH 0
#	define XTE_COMPILER_QUICKC_TWEAK 0
#	define XTE_COMPILER_RENESAS 0
#	define XTE_COMPILER_RENESAS_MAJOR 0
#	define XTE_COMPILER_RENESAS_MINOR 0
#	define XTE_COMPILER_RENESAS_PATCH 0
#	define XTE_COMPILER_RENESAS_TWEAK 0
#	define XTE_COMPILER_SDCC 0
#	define XTE_COMPILER_SDCC_MAJOR 0
#	define XTE_COMPILER_SDCC_MINOR 0
#	define XTE_COMPILER_SDCC_PATCH 0
#	define XTE_COMPILER_SDCC_TWEAK 0
#	define XTE_COMPILER_SHARC 0
#	define XTE_COMPILER_SHARC_MAJOR 0
#	define XTE_COMPILER_SHARC_MINOR 0
#	define XTE_COMPILER_SHARC_PATCH 0
#	define XTE_COMPILER_SHARC_TWEAK 0
#	define XTE_COMPILER_SNC 0
#	define XTE_COMPILER_SNC_MAJOR 0
#	define XTE_COMPILER_SNC_MINOR 0
#	define XTE_COMPILER_SNC_PATCH 0
#	define XTE_COMPILER_SNC_TWEAK 0
#	define XTE_COMPILER_SOZOBON 0
#	define XTE_COMPILER_SOZOBON_MAJOR 0
#	define XTE_COMPILER_SOZOBON_MINOR 0
#	define XTE_COMPILER_SOZOBON_PATCH 0
#	define XTE_COMPILER_SOZOBON_TWEAK 0
#	define XTE_COMPILER_STRATUS_VOS_C 0
#	define XTE_COMPILER_STRATUS_VOS_C_MAJOR 0
#	define XTE_COMPILER_STRATUS_VOS_C_MINOR 0
#	define XTE_COMPILER_STRATUS_VOS_C_PATCH 0
#	define XTE_COMPILER_STRATUS_VOS_C_TWEAK 0
#	define XTE_COMPILER_SYMANTEC_CPP 0
#	define XTE_COMPILER_SYMANTEC_CPP_MAJOR 0
#	define XTE_COMPILER_SYMANTEC_CPP_MINOR 0
#	define XTE_COMPILER_SYMANTEC_CPP_PATCH 0
#	define XTE_COMPILER_SYMANTEC_CPP_TWEAK 0
#	define XTE_COMPILER_TASKING 0
#	define XTE_COMPILER_TASKING_MAJOR 0
#	define XTE_COMPILER_TASKING_MINOR 0
#	define XTE_COMPILER_TASKING_PATCH 0
#	define XTE_COMPILER_TASKING_TWEAK 0
#	define XTE_COMPILER_TCC 0
#	define XTE_COMPILER_TCC_MAJOR 0
#	define XTE_COMPILER_TCC_MINOR 0
#	define XTE_COMPILER_TCC_PATCH 0
#	define XTE_COMPILER_TCC_TWEAK 0
#	define XTE_COMPILER_TENDRA 0
#	define XTE_COMPILER_TENDRA_MAJOR 0
#	define XTE_COMPILER_TENDRA_MINOR 0
#	define XTE_COMPILER_TENDRA_PATCH 0
#	define XTE_COMPILER_TENDRA_TWEAK 0
#	define XTE_COMPILER_TI 0
#	define XTE_COMPILER_TI_MAJOR 0
#	define XTE_COMPILER_TI_MINOR 0
#	define XTE_COMPILER_TI_PATCH 0
#	define XTE_COMPILER_TI_TWEAK 0
#	define XTE_COMPILER_TI_CGT 0
#	define XTE_COMPILER_TI_CGT_MAJOR 0
#	define XTE_COMPILER_TI_CGT_MINOR 0
#	define XTE_COMPILER_TI_CGT_PATCH 0
#	define XTE_COMPILER_TI_CGT_TWEAK 0
#	define XTE_COMPILER_TI_CL430 0
#	define XTE_COMPILER_TI_CL430_MAJOR 0
#	define XTE_COMPILER_TI_CL430_MINOR 0
#	define XTE_COMPILER_TI_CL430_PATCH 0
#	define XTE_COMPILER_TI_CL430_TWEAK 0
#	define XTE_COMPILER_TOPSPEED_C 0
#	define XTE_COMPILER_TOPSPEED_C_MAJOR 0
#	define XTE_COMPILER_TOPSPEED_C_MINOR 0
#	define XTE_COMPILER_TOPSPEED_C_PATCH 0
#	define XTE_COMPILER_TOPSPEED_C_TWEAK 0
#	define XTE_COMPILER_TURBO 0
#	define XTE_COMPILER_TURBO_MAJOR 0
#	define XTE_COMPILER_TURBO_MINOR 0
#	define XTE_COMPILER_TURBO_PATCH 0
#	define XTE_COMPILER_TURBO_TWEAK 0
#	define XTE_COMPILER_ULTIMATE 0
#	define XTE_COMPILER_ULTIMATE_MAJOR 0
#	define XTE_COMPILER_ULTIMATE_MINOR 0
#	define XTE_COMPILER_ULTIMATE_PATCH 0
#	define XTE_COMPILER_ULTIMATE_TWEAK 0
#	define XTE_COMPILER_USL_C 0
#	define XTE_COMPILER_USL_C_MAJOR 0
#	define XTE_COMPILER_USL_C_MINOR 0
#	define XTE_COMPILER_USL_C_PATCH 0
#	define XTE_COMPILER_USL_C_TWEAK 0
#	define XTE_COMPILER_VBCC 0
#	define XTE_COMPILER_VBCC_MAJOR 0
#	define XTE_COMPILER_VBCC_MINOR 0
#	define XTE_COMPILER_VBCC_PATCH 0
#	define XTE_COMPILER_VBCC_TWEAK 0
#	define XTE_COMPILER_VCM 0
#	define XTE_COMPILER_VCM_MAJOR 0
#	define XTE_COMPILER_VCM_MINOR 0
#	define XTE_COMPILER_VCM_PATCH 0
#	define XTE_COMPILER_VCM_TWEAK 0
#	define XTE_COMPILER_WATCOM 0
#	define XTE_COMPILER_WATCOM_MAJOR 0
#	define XTE_COMPILER_WATCOM_MINOR 0
#	define XTE_COMPILER_WATCOM_PATCH 0
#	define XTE_COMPILER_WATCOM_TWEAK 0
#	define XTE_COMPILER_WIND_RIVER_DIAB 0
#	define XTE_COMPILER_WIND_RIVER_DIAB_MAJOR 0
#	define XTE_COMPILER_WIND_RIVER_DIAB_MINOR 0
#	define XTE_COMPILER_WIND_RIVER_DIAB_PATCH 0
#	define XTE_COMPILER_WIND_RIVER_DIAB_TWEAK 0
#	define XTE_COMPILER_XC8 0
#	define XTE_COMPILER_XC8_MAJOR 0
#	define XTE_COMPILER_XC8_MINOR 0
#	define XTE_COMPILER_XC8_PATCH 0
#	define XTE_COMPILER_XC8_TWEAK 0
#	define XTE_COMPILER_XC16 0
#	define XTE_COMPILER_XC16_MAJOR 0
#	define XTE_COMPILER_XC16_MINOR 0
#	define XTE_COMPILER_XC16_PATCH 0
#	define XTE_COMPILER_XC16_TWEAK 0
#	define XTE_COMPILER_XC32 0
#	define XTE_COMPILER_XC32_MAJOR 0
#	define XTE_COMPILER_XC32_MINOR 0
#	define XTE_COMPILER_XC32_PATCH 0
#	define XTE_COMPILER_XC32_TWEAK 0
#	define XTE_COMPILER_XC_DSC 0
#	define XTE_COMPILER_XC_DSC_MAJOR 0
#	define XTE_COMPILER_XC_DSC_MINOR 0
#	define XTE_COMPILER_XC_DSC_PATCH 0
#	define XTE_COMPILER_XC_DSC_TWEAK 0
#	define XTE_COMPILER_ZORTECH 0
#	define XTE_COMPILER_ZORTECH_MAJOR 0
#	define XTE_COMPILER_ZORTECH_MINOR 0
#	define XTE_COMPILER_ZORTECH_PATCH 0
#	define XTE_COMPILER_ZORTECH_TWEAK 0
#	define XTE_COMPILER_Z88DK 0
#	define XTE_COMPILER_Z88DK_MAJOR 0
#	define XTE_COMPILER_Z88DK_MINOR 0
#	define XTE_COMPILER_Z88DK_PATCH 0
#	define XTE_COMPILER_Z88DK_TWEAK 0
#
#	define XTE_COMPILER(NAME, OP, MAJOR, ...) \
		DETAIL_XTE_COMPILER(OP, \
			XTE_COMPILER_##NAME##_MAJOR, XTE_COMPILER_##NAME##_MINOR, XTE_COMPILER_##NAME##_PATCH, XTE_COMPILER_##NAME##_TWEAK \
			MAJOR, __VA_ARGS__ __VA_OPT__(,) 0, 0, 0 \
		)
#
#	ifdef _ACC_
#		undef XTE_COMPILER_ACC
#		define XTE_COMPILER_ACC 1
#	endif
#
#	if defined(_ACK) || defined(__ACK__)
#		undef XTE_COMPILER_ACK
#		define XTE_COMPILER_ACK 1
#	endif
#
#	if defined(__ADSP21XX__) || defined(__ADSP218X__)
#		undef XTE_COMPILER_ADSP
#		define XTE_COMPILER_ADSP 1
#		ifdef __VISUALDSPVERSION__
#			undef XTE_COMPILER_ADSP_MAJOR
#			undef XTE_COMPILER_ADSP_MINOR
#			undef XTE_COMPILER_ADSP_PATCH
#			define XTE_COMPILER_ADSP_MAJOR ((__VISUALDSPVERSION__) / 0x1000000)
#			define XTE_COMPILER_ADSP_MINOR ((__VISUALDSPVERSION__) / 0x10000 % 0x100)
#			define XTE_COMPILER_ADSP_PATCH ((__VISUALDSPVERSION__) / 0x100 % 0x100)
#		endif
#	endif
#
#	ifdef __AHCC__
#		undef XTE_COMPILER_AHCC
#		define XTE_COMPILER_AHCC 1
#	endif
#
#	ifdef __CHC__
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MAJOR
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MINOR
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE_PATCH
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE_TWEAK
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE 1
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MAJOR ((__VERSION__) / 1000)
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MINOR ((__VERSION__) % 1000)
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_PATCH (__REVISION__)
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_TWEAK ((__BUILD__) % 0x1000)
#	endif
#
#	ifdef __CMB__
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C_MAJOR
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C_MINOR
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C_PATCH
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C_TWEAK
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C 1
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MAJOR ((__VERSION__) / 1000)
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MINOR ((__VERSION__) % 1000)
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C_PATCH (__REVISION__)
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C_TWEAK ((__BUILD__) % 0x1000)
#	endif
#
#	ifdef __aocc__
#		undef XTE_COMPILER_AOCC
#		define XTE_COMPILER_AOCC 1
#		ifdef __aocc_major__
#			undef XTE_COMPILER_AOCC_MAJOR
#			undef XTE_COMPILER_AOCC_MAJOR
#			define XTE_COMPILER_AOCC_MAJOR (__aocc_major__)
#			define XTE_COMPILER_AOCC_MAJOR (__aocc_minor__)
#			define XTE_COMPILER_AOCC_MAJOR (__aocc_patchlevel__)
#		endif
#	endif
#
#	ifdef __apple_build_version__
#		undef XTE_COMPILER_APPLE_CLANG
#		undef XTE_COMPILER_APPLE_CLANG_MAJOR
#		undef XTE_COMPILER_APPLE_CLANG_MINOR
#		undef XTE_COMPILER_APPLE_CLANG_PATCH
#		undef XTE_COMPILER_APPLE_CLANG_TWEAK
#		define XTE_COMPILER_APPLE_CLANG 1
#		define XTE_COMPILER_APPLE_CLANG_MAJOR ((__apple_build_version__) / 10000000)
#		define XTE_COMPILER_APPLE_CLANG_MINOR ((__apple_build_version__) / 100000 % 10)
#		define XTE_COMPILER_APPLE_CLANG_PATCH ((__apple_build_version__) / 10000 % 10)
#		define XTE_COMPILER_APPLE_CLANG_TWEAK ((__apple_build_version__) % 10000)
#	endif
#
#	ifdef __CC_ARM
#		undef XTE_COMPILER_ARMCC
#		undef XTE_COMPILER_ARMCC_MAJOR
#		undef XTE_COMPILER_ARMCC_MINOR
#		undef XTE_COMPILER_ARMCC_PATCH
#		undef XTE_COMPILER_ARMCC_TWEAK
#		define XTE_COMPILER_ARMCC 1
#		ifdef __ARMCOMPILER_VERSION
#			define XTE_COMPILER_ARMCC_MAJOR ((__ARMCOMPILER_VERSION) / 100000)
#			define XTE_COMPILER_ARMCC_MINOR ((__ARMCOMPILER_VERSION) / 10000 % 10)
#			define XTE_COMPILER_ARMCC_PATCH ((__ARMCOMPILER_VERSION) / 1000 % 10)
#			define XTE_COMPILER_ARMCC_TWEAK ((__ARMCOMPILER_VERSION) % 1000)
#		else
#			define XTE_COMPILER_ARMCC_MAJOR ((__ARMCC_VERSION) / 1000000)
#			define XTE_COMPILER_ARMCC_MINOR ((__ARMCC_VERSION) / 10000 % 100)
#			define XTE_COMPILER_ARMCC_PATCH 0
#			define XTE_COMPILER_ARMCC_TWEAK ((__ARMCC_VERSION) % 10000)
#		endif
#	endif
#
#	if defined(__AZTEC_C__) || defined(AZTEC_C)
#		undef XTE_COMPILER_AZTEC_C
#		undef XTE_COMPILER_AZTEC_C_MAJOR
#		undef XTE_COMPILER_AZTEC_C_MINOR
#		define XTE_COMPILER_AZTEC_C 1
#		define XTE_COMPILER_AZTEC_C_MAJOR ((__VERSION) / 100)
#		define XTE_COMPILER_AZTEC_C_MINOR ((__VERSION) % 100)
#	endif
#
#	if defined(__BORLANDC__) && !defined(__CODEGEARC_VERSION__)
#		undef XTE_COMPILER_BORLAND
#		undef XTE_COMPILER_BORLAND_MAJOR
#		undef XTE_COMPILER_BORLAND_MINOR
#		undef XTE_COMPILER_BORLAND_PATCH
#		define XTE_COMPILER_BORLAND 1
#		if (__BORLANDC__) == 0x400
#			define XTE_COMPILER_BORLAND_MAJOR 3
#			define XTE_COMPILER_BORLAND_MINOR 0
#			define XTE_COMPILER_BORLAND_PATCH 0
#		elif (__BORLANDC__) == 0x410
#			define XTE_COMPILER_BORLAND_MAJOR 3
#			define XTE_COMPILER_BORLAND_MINOR 1
#			define XTE_COMPILER_BORLAND_PATCH 0
#		elif (__BORLANDC__) == 0x452
#			define XTE_COMPILER_BORLAND_MAJOR 4
#			define XTE_COMPILER_BORLAND_MINOR 0
#			define XTE_COMPILER_BORLAND_PATCH 0
#		elif (__BORLANDC__) == 0x520
#			define XTE_COMPILER_BORLAND_MAJOR 5
#			define XTE_COMPILER_BORLAND_MINOR 2
#			define XTE_COMPILER_BORLAND_PATCH 0
#		elif (__BORLANDC__) == 0x550
#			define XTE_COMPILER_BORLAND_MAJOR 5
#			define XTE_COMPILER_BORLAND_MINOR 5
#			define XTE_COMPILER_BORLAND_PATCH 0
#		elif (__BORLANDC__) == 0x652
#			define XTE_COMPILER_BORLAND_MAJOR 5
#			define XTE_COMPILER_BORLAND_MINOR 6
#			define XTE_COMPILER_BORLAND_PATCH 4
#		else
#			define XTE_COMPILER_BORLAND_MAJOR ((__BORLANDC__) / 0x100)
#			define XTE_COMPILER_BORLAND_MINOR ((__BORLANDC__) % 0x100)
#			define XTE_COMPILER_BORLAND_PATCH 0
#		endif
#	endif
#
#	ifdef __BCC__
#		undef XTE_COMPILER_BRUCE
#		define XTE_COMPILER_BRUCE 1
#	endif
#
#	ifdef __c2__
#		undef XTE_COMPILER_C2
#		define XTE_COMPILER_C2 1
#	endif
#
#	ifdef __castxml__
#		undef XTE_COMPILER_CASTXML
#		undef XTE_COMPILER_CASTXML_MAJOR
#		undef XTE_COMPILER_CASTXML_MINOR
#		undef XTE_COMPILER_CASTXML_PATCH
#		define XTE_COMPILER_CASTXML 1
#		define XTE_COMPILER_CASTXML_MAJOR (__castxml_major__)
#		define XTE_COMPILER_CASTXML_MINOR (__castxml_minor__)
#		define XTE_COMPILER_CASTXML_PATCH (__castxml_patch__)
#	endif
#
#	ifdef __CC65__
#		undef XTE_COMPILER_CC65
#		undef XTE_COMPILER_CC65_MAJOR
#		undef XTE_COMPILER_CC65_MINOR
#		undef XTE_COMPILER_CC65_PATCH
#		define XTE_COMPILER_CC65 1
#		define XTE_COMPILER_CC65_MAJOR ((__CC65__) / 0x100)
#		define XTE_COMPILER_CC65_MINOR ((__CC65__) / 0x10 % 0x10)
#		define XTE_COMPILER_CC65_PATCH ((__CC65__) % 0x10)
#	endif
#
#	if defined(CIL) && defined(_GNUCC)
#		undef XTE_COMPILER_CILLY
#		define XTE_COMPILER_CILLY 1
#		ifdef __CILLY__
#			undef XTE_COMPILER_CILLY_MAJOR
#			undef XTE_COMPILER_CILLY_MINOR
#			undef XTE_COMPILER_CILLY_PATCH
#			define XTE_COMPILER_CILLY_MAJOR ((__CILLY__) / 0x10000)
#			define XTE_COMPILER_CILLY_MINOR ((__CILLY__) / 0x100 % 0x100)
#			define XTE_COMPILER_CILLY_PATCH ((__CILLY__) % 0x100)
#		endif
#	endif
#
#	ifdef __circle_lang__
#		undef XTE_COMPILER_CIRCLE
#		undef XTE_COMPILER_CIRCLE_MAJOR
#		undef XTE_COMPILER_CIRCLE_MINOR
#		undef XTE_COMPILER_CIRCLE_PATCH
#		define XTE_COMPILER_CIRCLE 1
#		define XTE_COMPILER_CIRCLE_MAJOR (__circle_major__)
#		define XTE_COMPILER_CIRCLE_MINOR (__circle_minor__)
#		define XTE_COMPILER_CIRCLE_PATCH (__circle_build__)
#	endif
#
#	if defined(__clang__)
#		undef XTE_COMPILER_CLANG
#		undef XTE_COMPILER_CLANG_MAJOR
#		undef XTE_COMPILER_CLANG_MINOR
#		undef XTE_COMPILER_CLANG_PATCH
#		define XTE_COMPILER_CLANG 1
#		define XTE_COMPILER_CLANG_MAJOR (__clang_major__)
#		define XTE_COMPILER_CLANG_MINOR (__clang_minor__)
#		define XTE_COMPILER_CLANG_PATCH (__clang_patchlevel__)
#	endif
#
#	ifdef __COMO__
#		undef XTE_COMPILER_COMEAU
#		undef XTE_COMPILER_COMEAU_MAJOR
#		undef XTE_COMPILER_COMEAU_MINOR
#		undef XTE_COMPILER_COMEAU_PATCH
#		define XTE_COMPILER_COMEAU 1
#		if __COMO_VERSION__ >= 0x1000
#			define XTE_COMPILER_COMEAU_MAJOR ((__COMO_VERSION__) / 1000)
#			define XTE_COMPILER_COMEAU_MINOR ((__COMO_VERSION__) / 100 % 10)
#			define XTE_COMPILER_COMEAU_PATCH ((__COMO_VERSION__) % 100)
#		else
#			define XTE_COMPILER_COMEAU_MAJOR ((__COMO_VERSION__) / 100)
#			define XTE_COMPILER_COMEAU_MINOR ((__COMO_VERSION__) % 100)
#			define XTE_COMPILER_COMEAU_PATCH 0
#		endif
#	endif
#
#	if defined(__DECC) || defined(__DECCXX)
#		undef XTE_COMPILER_COMPAQ
#		undef XTE_COMPILER_COMPAQ_MAJOR
#		undef XTE_COMPILER_COMPAQ_MINOR
#		undef XTE_COMPILER_COMPAQ_PATCH
#		define XTE_COMPILER_COMPAQ 1
#		ifdef __DECCXX
#			define XTE_COMPILER_COMPAQ_MAJOR ((__DECCXX_VER) / 10000000)
#			define XTE_COMPILER_COMPAQ_MINOR ((__DECCXX_VER) / 100000 % 100)
#			define XTE_COMPILER_COMPAQ_PATCH ((__DECCXX_VER) % 10000)
#		else
#			define XTE_COMPILER_COMPAQ_MAJOR ((__DECC_VER) / 10000000)
#			define XTE_COMPILER_COMPAQ_MINOR ((__DECC_VER) / 100000 % 100)
#			define XTE_COMPILER_COMPAQ_PATCH ((__DECC_VER) % 10000)
#		endif
#	endif
#
#	ifdef __COMPCERT__
#		undef XTE_COMPILER_COMPCERT
#		define XTE_COMPILER_COMPCERT 1
#	endif
#
#	ifdef __convexc__
#		undef XTE_COMPILER_CONVEX_C
#		define XTE_COMPILER_CONVEX_C 1
#	endif
#
#	ifdef __COVERITY__
#		undef XTE_COMPILER_COVERITY_STATIC_ANALYZER
#		define XTE_COMPILER_COVERITY_STATIC_ANALYZER 1
#	endif
#
#	if defined(__cray__) || defined(_CRAYC)
#		undef XTE_COMPILER_CRAY
#		undef XTE_COMPILER_CRAY_MAJOR
#		undef XTE_COMPILER_CRAY_MINOR
#		undef XTE_COMPILER_CRAY_PATCH
#		define XTE_COMPILER_CRAY 1
#		ifdef __cray__
#			define XTE_COMPILER_CRAY_MAJOR (__cray_major__)
#			define XTE_COMPILER_CRAY_MINOR (__cray_minor__)
#			define XTE_COMPILER_CRAY_PATCH (__cray_patchlevel__)
#		else
#			define XTE_COMPILER_CRAY_MAJOR (_RELEASE)
#			define XTE_COMPILER_CRAY_MINOR (_RELEASE_MINOR)
#			ifdef _RELEASE_PATCHLEVEL
#				define XTE_COMPILER_CRAY_PATCH (_RELEASE_PATCHLEVEL)
#			else
#				define XTE_COMPILER_CRAY_PATCH 0
#			endif
#		endif
#	endif
#
#	ifdef __DMC__
#		undef XTE_COMPILER_DIGITAL_MARS
#		undef XTE_COMPILER_DIGITAL_MARS_MAJOR
#		undef XTE_COMPILER_DIGITAL_MARS_MINOR
#		undef XTE_COMPILER_DIGITAL_MARS_PATCH
#		define XTE_COMPILER_DIGITAL_MARS 1
#		define XTE_COMPILER_DIGITAL_MARS_MAJOR ((__DMC__) / 0x100)
#		define XTE_COMPILER_DIGITAL_MARS_MINOR ((__DMC__) / 0x10 % 0x10)
#		define XTE_COMPILER_DIGITAL_MARS_PATCH ((__DMC__) % 0x10)
#	endif
#
#	ifdef _DICE
#		undef XTE_COMPILER_DICE_C
#		define XTE_COMPILER_DICE_C 1
#	endif
#
#	ifdef __SYSC__
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MAJOR
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MINOR
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP_PATCH
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP 1
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MAJOR ((__SYSC_VER__) / 10000)
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MINOR ((__SYSC_VER__) / 100 % 100)
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_PATCH ((__SYSC_VER__) % 100)
#	endif
#
#	if defined(__DJGPP__) || defined(__DJGPP) || defined(DJGPP)
#		undef XTE_COMPILER_DJGPP
#		undef XTE_COMPILER_DJGPP_MAJOR
#		undef XTE_COMPILER_DJGPP_MINOR
#		define XTE_COMPILER_DJGPP 1
#		define XTE_COMPILER_DJGPP_MAJOR (__DJGPP__)
#		define XTE_COMPILER_DJGPP_MINOR (__DJGPP_MINOR__)
#	endif
#
#	ifdef __EDG__
#		undef XTE_COMPILER_EDG
#		undef XTE_COMPILER_EDG_MAJOR
#		undef XTE_COMPILER_EDG_MINOR
#		define XTE_COMPILER_EDG 1
#		define XTE_COMPILER_EDG_MAJOR ((__EDG_VERSION__) / 100)
#		define XTE_COMPILER_EDG_MINOR ((__EDG_VERSION__) % 100)
#	endif
#
#	if defined(__PATHSCALE__) || defined(__PATHCC__)
#		undef XTE_COMPILER_EKOPATH
#		undef XTE_COMPILER_EKOPATH_MAJOR
#		undef XTE_COMPILER_EKOPATH_MINOR
#		undef XTE_COMPILER_EKOPATH_PATCH
#		define XTE_COMPILER_EKOPATH 1
#		define XTE_COMPILER_EKOPATH_MAJOR (__PATHCC__)
#		define XTE_COMPILER_EKOPATH_MINOR (__PATHCC_MINOR__)
#		define XTE_COMPILER_EKOPATH_PATCH (__PATHCC_PATCHLEVEL__)
#	endif
#
#	ifdef __ELLCC__
#		undef XTE_COMPILER_ELLCC
#		define XTE_COMPILER_ELLCC 1
#	endif
#
#	if defined(__BORLANDC__) && defined(__CODEGEARC_VERSION__)
#		undef XTE_COMPILER_EMBARCADERO
#		undef XTE_COMPILER_EMBARCADERO_MAJOR
#		undef XTE_COMPILER_EMBARCADERO_MINOR
#		undef XTE_COMPILER_EMBARCADERO_PATCH
#		define XTE_COMPILER_EMBARCADERO 1
#		define XTE_COMPILER_EMBARCADERO_MAJOR ((__CODEGEARC_VERSION__) / 0x1000000)
#		define XTE_COMPILER_EMBARCADERO_MINOR ((__CODEGEARC_VERSION__) / 0x10000 % 0x100)
#		define XTE_COMPILER_EMBARCADERO_PATCH ((__CODEGEARC_VERSION__) % 0x10000)
#	endif
#
#	if defined(__FLANG) || defined(__flang__)
#		undef XTE_COMPILER_FLANG
#		undef XTE_COMPILER_FLANG_MAJOR
#		undef XTE_COMPILER_FLANG_MINOR
#		undef XTE_COMPILER_FLANG_PATCH
#		define XTE_COMPILER_FLANG 1
#		ifdef __flang__
#			define XTE_COMPILER_FLANG_MAJOR (__flang_major__)
#			define XTE_COMPILER_FLANG_MINOR (__flang_minor__)
#			define XTE_COMPILER_FLANG_PATCH (__flang_patchlevel__)
#		else
#			define XTE_COMPILER_FLANG_MAJOR (__FLANG_MAJOR__)
#			define XTE_COMPILER_FLANG_MINOR (__FLANG_MINOR__)
#			define XTE_COMPILER_FLANG_PATCH (__FLANG_PATCHLEVEL__)
#		endif
#	endif
#
#	if defined(__CLANG_FUJITSU) || defined(__FCC__) || defined(__FCC_VERSION) || defined(__FCC_version__) || defined(__FUJITSU) || defined(__fcc__) || defined(__fcc_version)
#		undef XTE_COMPILER_FUJITSU_CPP
#		define XTE_COMPILER_FUJITSU_CPP 1
#		ifdef __FCC_major__
#			undef XTE_COMPILER_FUJITSU_CPP_MAJOR
#			undef XTE_COMPILER_FUJITSU_CPP_MINOR
#			undef XTE_COMPILER_FUJITSU_CPP_PATCH
#			define XTE_COMPILER_FUJITSU_CPP_MAJOR (__FCC_major__)
#			define XTE_COMPILER_FUJITSU_CPP_MINOR (__FCC_minor__)
#			define XTE_COMPILER_FUJITSU_CPP_PATCH (__FCC_patchlevel__)
#		endif
#	endif
#
#	if defined(__GNUC__) || defined(__GNUC) || defined(__gnuc)
#		undef XTE_COMPILER_GCC
#		undef XTE_COMPILER_GCC_MAJOR
#		undef XTE_COMPILER_GCC_MINOR
#		undef XTE_COMPILER_GCC_PATCH
#		define XTE_COMPILER_GCC 1
#		define XTE_COMPILER_GCC_MAJOR (__GNUC__)
#		define XTE_COMPILER_GCC_MINOR (__GNUC_MINOR__)
#		define XTE_COMPILER_GCC_PATCH (__GNUC_PATCHLEVEL__)
#	endif
#
#	ifdef __GCCXML__
#		undef XTE_COMPILER_GCCXML
#		define XTE_COMPILER_GCCXML 1
#	endif
#
#	if defined(__ghs) || defined(__ghs__)
#		undef XTE_COMPILER_GREEN_HILLS
#		undef XTE_COMPILER_GREEN_HILLS_MAJOR
#		undef XTE_COMPILER_GREEN_HILLS_MINOR
#		undef XTE_COMPILER_GREEN_HILLS_PATCH
#		define XTE_COMPILER_GREEN_HILLS 1
#		ifdef __GHS_VERSION_NUMBER__
#			define XTE_COMPILER_GREEN_HILLS_MAJOR ((__GHS_VERSION_NUMBER__) / 100)
#			define XTE_COMPILER_GREEN_HILLS_MINOR ((__GHS_VERSION_NUMBER__) / 10 % 10)
#			define XTE_COMPILER_GREEN_HILLS_PATCH ((__GHS_VERSION_NUMBER__) % 10)
#		else
#			define XTE_COMPILER_GREEN_HILLS_MAJOR ((__GHS_VERSION_NUMBER) / 100)
#			define XTE_COMPILER_GREEN_HILLS_MINOR ((__GHS_VERSION_NUMBER) / 10 % 10)
#			define XTE_COMPILER_GREEN_HILLS_PATCH ((__GHS_VERSION_NUMBER) % 10)
#		endif
#	endif
#
#	ifdef __hexagon__
#		undef XTE_COMPILER_HEXAGON
#		undef XTE_COMPILER_HEXAGON_MAJOR
#		define XTE_COMPILER_HEXAGON 1
#		ifdef __HEXAGON_V73__
#			define XTE_COMPILER_HEXAGON_MAJOR 73
#		elif defined(__HEXAGON_V71__)
#			define XTE_COMPILER_HEXAGON_MAJOR 71
#		elif defined(__HEXAGON_V70__)
#			define XTE_COMPILER_HEXAGON_MAJOR 70
#		elif defined(__HEXAGON_V69__)
#			define XTE_COMPILER_HEXAGON_MAJOR 69
#		elif defined(__HEXAGON_V68__)
#			define XTE_COMPILER_HEXAGON_MAJOR 68
#		elif defined(__HEXAGON_V67__)
#			define XTE_COMPILER_HEXAGON_MAJOR 67
#		elif defined(__HEXAGON_V66__)
#			define XTE_COMPILER_HEXAGON_MAJOR 66
#		elif defined(__HEXAGON_V65__)
#			define XTE_COMPILER_HEXAGON_MAJOR 65
#		else
#			define XTE_COMPILER_HEXAGON_MAJOR 0
#		endif
#	endif
#
#	if defined(__HCC__) || defined(__HIP__) || defined(__HIPCC__) || defined(__HIPCC_PLATFORM_HCC)
#		undef XTE_COMPILER_HIPCC
#		define XTE_COMPILER_HIPCC 1
#	endif
#
#	if defined(__HP_cc) || defined(__HP_aCC)
#		undef XTE_COMPILER_HPUX
#		undef XTE_COMPILER_HPUX_MAJOR
#		undef XTE_COMPILER_HPUX_MINOR
#		undef XTE_COMPILER_HPUX_PATCH
#		define XTE_COMPILER_HPUX 1
#		ifdef __HP_aCC
#			define XTE_COMPILER_HPUX_MAJOR ((__HP_aCC) / 10000)
#			define XTE_COMPILER_HPUX_MINOR ((__HP_aCC) / 10000 % 100)
#			define XTE_COMPILER_HPUX_PATCH ((__HP_aCC) % 100)
#		else
#			define XTE_COMPILER_HPUX_MAJOR ((__HP_cc) / 10000)
#			define XTE_COMPILER_HPUX_MINOR ((__HP_cc) / 10000 % 100)
#			define XTE_COMPILER_HPUX_PATCH ((__HP_cc) % 100)
#		endif
#	endif
#
#	ifdef __HSC__
#		undef XTE_COMPILER_HSC
#		define XTE_COMPILER_HSC 1
#	endif
#
#	if defined(__IAR_SYSTEMS_ICC__) || defined(__IAR_SYSTEMS_ICC)
#		undef XTE_COMPILER_IAR
#		undef XTE_COMPILER_IAR_MAJOR
#		undef XTE_COMPILER_IAR_MINOR
#		undef XTE_COMPILER_IAR_PATCH
#		define XTE_COMPILER_IAR 1
#		ifdef __SUBVERSION__
#			define XTE_COMPILER_IAR_MAJOR ((__VER__) / 100)
#			define XTE_COMPILER_IAR_MINOR ((__VER__) % 100)
#			define XTE_COMPILER_IAR_PATCH (__SUBVERSION__)
#		else
#			define XTE_COMPILER_IAR_MAJOR ((__VER__) / 1000000)
#			define XTE_COMPILER_IAR_MINOR ((__VER__) / 1000 % 1000)
#			define XTE_COMPILER_IAR_PATCH ((__VER__) % 1000)
#		endif
#	endif
#
#	ifdef __open_xl__
#		undef XTE_COMPILER_IBM_OPEN_XL
#		undef XTE_COMPILER_IBM_OPEN_XL_MAJOR
#		undef XTE_COMPILER_IBM_OPEN_XL_MINOR
#		undef XTE_COMPILER_IBM_OPEN_XL_PATCH
#		undef XTE_COMPILER_IBM_OPEN_XL_TWEAK
#		define XTE_COMPILER_IBM_OPEN_XL 1
#		define XTE_COMPILER_IBM_OPEN_XL_MAJOR (__open_xl_version__)
#		define XTE_COMPILER_IBM_OPEN_XL_MINOR (__open_xl_release__)
#		define XTE_COMPILER_IBM_OPEN_XL_PATCH (__open_xl_modification__)
#		define XTE_COMPILER_IBM_OPEN_XL_TWEAK (__open_xl_ptf_fix_level__)
#	endif
#
#	if defined(__IBMC__) || defined(__IBMCPP__)
#		undef XTE_COMPILER_IBM_XL
#		undef XTE_COMPILER_IBM_XL_MAJOR
#		undef XTE_COMPILER_IBM_XL_MINOR
#		undef XTE_COMPILER_IBM_XL_PATCH
#		undef XTE_COMPILER_IBM_XL_TWEAK
#		define XTE_COMPILER_IBM_XL 1
#		define XTE_COMPILER_IBM_XL_MAJOR ((__xlC__) / 0x100)
#		define XTE_COMPILER_IBM_XL_MINOR ((__xlC__) % 0x100)
#		define XTE_COMPILER_IBM_XL_PATCH ((__xlC_ver__) / 0x100)
#		define XTE_COMPILER_IBM_XL_TWEAK ((__xlC_ver__) % 0x100)
#	endif
#
#	if defined(__ibmxl__)
#		undef XTE_COMPILER_IBM_XL_CLANG
#		undef XTE_COMPILER_IBM_XL_CLANG_MAJOR
#		undef XTE_COMPILER_IBM_XL_CLANG_MINOR
#		undef XTE_COMPILER_IBM_XL_CLANG_PATCH
#		undef XTE_COMPILER_IBM_XL_CLANG_TWEAK
#		define XTE_COMPILER_IBM_XL_CLANG 1
#		define XTE_COMPILER_IBM_XL_CLANG_MAJOR (__ibmxl_version__)
#		define XTE_COMPILER_IBM_XL_CLANG_MINOR (__ibmxl_release__)
#		define XTE_COMPILER_IBM_XL_CLANG_PATCH (__ibmxl_modification__)
#		define XTE_COMPILER_IBM_XL_CLANG_TWEAK (__ibmxl_ptf_fix_level__)
#	endif
#
#	if defined(__COMPILER_VER__) && (defined(__IBMC__) || defined(__IBMCPP__))
#		undef XTE_COMPILER_IBM_Z_OS_XL
#		undef XTE_COMPILER_IBM_Z_OS_XL_MAJOR
#		undef XTE_COMPILER_IBM_Z_OS_XL_MINOR
#		undef XTE_COMPILER_IBM_Z_OS_XL_PATCH
#		undef XTE_COMPILER_IBM_Z_OS_XL_TWEAK
#		define XTE_COMPILER_IBM_Z_OS_XL 1
#		define XTE_COMPILER_IBM_Z_OS_XL_MAJOR ((__COMPILER_VER__) / 0x1000000 % 0x10)
#		define XTE_COMPILER_IBM_Z_OS_XL_MINOR ((__COMPILER_VER__) / 0x10000 % 0x100)
#		define XTE_COMPILER_IBM_Z_OS_XL_PATCH ((__COMPILER_VER__) / 0x100 % 0x100)
#		define XTE_COMPILER_IBM_Z_OS_XL_TWEAK ((__COMPILER_VER__) % 0x100)
#	endif
#
#	if defined(__ECC) || defined(__ECC__) || defined(__ICC) || defined(__ICL) || defined(__INTEL_COMPILER)
#		undef XTE_COMPILER_ICC
#		define XTE_COMPILER_ICC 1
#		ifdef __INTEL_COMPILER
#			undef XTE_COMPILER_ICC_MAJOR
#			undef XTE_COMPILER_ICC_MINOR
#			undef XTE_COMPILER_ICC_PATCH
#			if (__INTEL_COMPILER) == 9999
#				define XTE_COMPILER_ICC_MAJOR 12
#				define XTE_COMPILER_ICC_MINOR 1
#				define XTE_COMPILER_ICC_PATCH 0
#			else
#				define XTE_COMPILER_ICC_MAJOR ((__INTEL_COMPILER) / 100)
#				define XTE_COMPILER_ICC_MINOR ((__INTEL_COMPILER) % 100)
#				define XTE_COMPILER_ICC_PATCH (__INTEL_COMPILER_UPDATE)
#			endif
#		endif
#	endif
#
#	if defined(__INTEL_CLANG_COMPILER) || defined(__INTEL_LLVM_COMPILER)
#		undef XTE_COMPILER_ICX
#		undef XTE_COMPILER_ICX_MAJOR
#		undef XTE_COMPILER_ICX_MINOR
#		undef XTE_COMPILER_ICX_PATCH
#		define XTE_COMPILER_ICX 1
#		ifdef __INTEL_LLVM_COMPILER
#			if (__INTEL_LLVM_COMPILER) >= 1000000
#				define XTE_COMPILER_ICX_MAJOR ((__INTEL_LLVM_COMPILER) / 10000)
#				define XTE_COMPILER_ICX_MINOR ((__INTEL_LLVM_COMPILER) / 100 % 100)
#				define XTE_COMPILER_ICX_PATCH ((__INTEL_LLVM_COMPILER) % 100)
#			else
#				define XTE_COMPILER_ICX_MAJOR ((__INTEL_LLVM_COMPILER) / 100)
#				define XTE_COMPILER_ICX_MINOR ((__INTEL_LLVM_COMPILER) / 10 % 10)
#				define XTE_COMPILER_ICX_PATCH ((__INTEL_LLVM_COMPILER) % 10)
#			endif
#		elif (__INTEL_CLANG_COMPILER) >= 1000000
#			define XTE_COMPILER_ICX_MAJOR ((__INTEL_CLANG_COMPILER) / 10000)
#			define XTE_COMPILER_ICX_MINOR ((__INTEL_CLANG_COMPILER) / 100 % 100)
#			define XTE_COMPILER_ICX_PATCH ((__INTEL_CLANG_COMPILER) % 100)
#		else
#			define XTE_COMPILER_ICX_MAJOR ((__INTEL_CLANG_COMPILER) / 100)
#			define XTE_COMPILER_ICX_MINOR ((__INTEL_CLANG_COMPILER) / 10 % 10)
#			define XTE_COMPILER_ICX_PATCH ((__INTEL_CLANG_COMPILER) % 10)
#		endif
#	endif
#
#	ifdef __IMAGECRAFT__
#		undef XTE_COMPILER_IMAGECRAFT_C
#		define XTE_COMPILER_IMAGECRAFT_C 1
#	endif
#
#	if defined(__COMPILER_KCC__) || defined(__KCC_)
#		undef XTE_COMPILER_KCC
#		undef XTE_COMPILER_KCC_MAJOR
#		undef XTE_COMPILER_KCC_MINOR
#		undef XTE_COMPILER_KCC_PATCH
#		define XTE_COMPILER_KCC 1
#		define XTE_COMPILER_KCC_MAJOR ((__KCC_VERSION) / 0x1000)
#		define XTE_COMPILER_KCC_MINOR ((__KCC_VERSION) / 0x100 % 0x10)
#		define XTE_COMPILER_KCC_PATCH ((__KCC_VERSION) % 0x100)
#	endif
#
#	ifdef __C166__
#		undef XTE_COMPILER_KEIL_C166
#		undef XTE_COMPILER_KEIL_C166_MAJOR
#		undef XTE_COMPILER_KEIL_C166_MINOR
#		define XTE_COMPILER_KEIL_C166 1
#		define XTE_COMPILER_KEIL_C166_MAJOR ((__C166__) / 100)
#		define XTE_COMPILER_KEIL_C166_MINOR ((__C166__) % 100)
#	endif
#
#	ifdef __C51__
#		undef XTE_COMPILER_KEIL_C51
#		undef XTE_COMPILER_KEIL_C51_MAJOR
#		undef XTE_COMPILER_KEIL_C51_MINOR
#		define XTE_COMPILER_KEIL_C51 1
#		define XTE_COMPILER_KEIL_C51_MAJOR ((__C51__) / 100)
#		define XTE_COMPILER_KEIL_C51_MINOR ((__C51__) % 100)
#	endif
#
#	if defined(__CA__) || defined(__KEIL__)
#		undef XTE_COMPILER_KEIL_CARM
#		undef XTE_COMPILER_KEIL_CARM_MAJOR
#		undef XTE_COMPILER_KEIL_CARM_MINOR
#		define XTE_COMPILER_KEIL_CARM 1
#		define XTE_COMPILER_KEIL_CARM_MAJOR ((__CA__) / 100)
#		define XTE_COMPILER_KEIL_CARM_MINOR ((__CA__) % 100)
#	endif
#
#	ifdef __KICKC__
#		undef XTE_COMPILER_KICKC
#		define XTE_COMPILER_KICKC 1
#	endif
#
#	if defined(__SASC__) || defined(__SASC) || defined(SASC)
#		undef XTE_COMPILER_LATTICE_C
#		undef XTE_COMPILER_LATTICE_C_MAJOR
#		undef XTE_COMPILER_LATTICE_C_MINOR
#		define XTE_COMPILER_LATTICE_C 1
#		ifdef __SASC__
#			define XTE_COMPILER_LATTICE_C_MAJOR ((__SASC__) / 100)
#			define XTE_COMPILER_LATTICE_C_MINOR ((__SASC__) % 100)
#		else
#			define XTE_COMPILER_LATTICE_C_MAJOR (__VERSION__)
#			define XTE_COMPILER_LATTICE_C_MINOR (__REVISION__)
#		endif
#	endif
#
#	ifdef __LCC__
#		undef XTE_COMPILER_LCC
#		undef XTE_COMPILER_LCC_MAJOR
#		define XTE_COMPILER_LCC 1
#		define XTE_COMPILER_LCC_MAJOR (__LCC__)
#		ifdef __LCC_MINOR__
#			undef XTE_COMPILER_LCC_MINOR
#			define XTE_COMPILER_LCC_MINOR (__LCC_MINOR__)
#		endif
#	endif
#
#	if defined(THINKC3) || defined(THINKC4)
#		undef XTE_COMPILER_LIGHTSPEED_C
#		undef XTE_COMPILER_LIGHTSPEED_C_MAJOR
#		define XTE_COMPILER_LIGHTSPEED_C 1
#		ifdef THINKC4
#			define XTE_COMPILER_LIGHTSPEED_C_MAJOR 4
#		else
#			define XTE_COMPILER_LIGHTSPEED_C_MAJOR 3
#		endif
#	endif
#
#	ifdef __llvm__
#		undef XTE_COMPILER_LLVM
#		define XTE_COMPILER_LLVM 1
#	endif
#
#	if defined(__LLC__) && defined(__MCST__)
#		undef XTE_COMPILER_MCST_LLC
#		undef XTE_COMPILER_MCST_LLC_MAJOR
#		undef XTE_COMPILER_MCST_LLC_MINOR
#		define XTE_COMPILER_MCST_LLC 1
#		define XTE_COMPILER_MCST_LLC_MAJOR (__LLC__)
#		define XTE_COMPILER_MCST_LLC_MINOR (__LLC_MINOR__)
#	endif
#
#	ifdef __HIGHC__
#		undef XTE_COMPILER_METAWARE_HIGH
#		define XTE_COMPILER_METAWARE_HIGH 1
#	endif
#
#	if defined(__CWCC__) || defined(__MWBROWSER__) || defined(__MWERKS__)
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH
#		define XTE_COMPILER_METROWERKS_CODEWARRIOR 1
#		ifdef __CWCC__
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR ((__CWCC__) / 0x1000)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR ((__CWCC__) % 0x1000 / 0x100)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH ((__CWCC__) % 0x100)
#		else
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR ((__MWERKS__) / 0x1000)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR ((__MWERKS__) % 0x1000 / 0x100)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH ((__MWERKS__) % 0x100)
#		endif
#	endif
#
#	ifdef _MRI
#		undef XTE_COMPILER_MICROTEC
#		define XTE_COMPILER_MICROTEC 1
#	endif
#
#	if defined(__NDPC__) || defined(__NDPX__)
#		undef XTE_COMPILER_MICROWAY_NDP_C
#		define XTE_COMPILER_MICROWAY_NDP_C 1
#	endif
#
#	ifdef __MINGW32__
#		include <windows.h>
#		undef XTE_COMPILER_MINGW32
#		undef XTE_COMPILER_MINGW32_MAJOR
#		undef XTE_COMPILER_MINGW32_MINOR
#		define XTE_COMPILER_MINGW32 1
#		define XTE_COMPILER_MINGW32_MAJOR (__MINGW32_MAJOR_VERSION)
#		define XTE_COMPILER_MINGW32_MINOR (__MINGW32_MINOR_VERSION)
#	endif
#
#	ifdef __MINGW64__
#		include <windows.h>
#		undef XTE_COMPILER_MINGW_W64
#		undef XTE_COMPILER_MINGW_W64_MAJOR
#		undef XTE_COMPILER_MINGW_W64_MINOR
#		define XTE_COMPILER_MINGW_W64 1
#		define XTE_COMPILER_MINGW_W64_MAJOR (__MINGW64_VERSION_MAJOR)
#		define XTE_COMPILER_MINGW_W64_MINOR (__MINGW64_VERSION_MINOR)
#	endif
#
#	if defined(__sgi) || defined(sgi)
#		undef XTE_COMPILER_MIPSPRO
#		undef XTE_COMPILER_MIPSPRO_MAJOR
#		undef XTE_COMPILER_MIPSPRO_MINOR
#		undef XTE_COMPILER_MIPSPRO_PATCH
#		define XTE_COMPILER_MIPSPRO 1
#		ifdef _SGI_COMPILER_VERSION
#			define XTE_COMPILER_MIPSPRO_MAJOR ((_SGI_COMPILER_VERSION) / 100)
#			define XTE_COMPILER_MIPSPRO_MINOR ((_SGI_COMPILER_VERSION) % 100 / 10)
#			define XTE_COMPILER_MIPSPRO_PATCH ((_SGI_COMPILER_VERSION) % 10)
#		elif defined(_COMPILER_VERSION)
#			define XTE_COMPILER_MIPSPRO_MAJOR ((_COMPILER_VERSION) / 100)
#			define XTE_COMPILER_MIPSPRO_MINOR ((_COMPILER_VERSION) % 100 / 10)
#			define XTE_COMPILER_MIPSPRO_PATCH ((_COMPILER_VERSION) % 10)
#		else
#			define XTE_COMPILER_MIPSPRO_MAJOR 0
#			define XTE_COMPILER_MIPSPRO_MINOR 0
#			define XTE_COMPILER_MIPSPRO_PATCH 0
#		endif
#	endif
#
#	ifdef MIRACLE
#		undef XTE_COMPILER_MIRACLE_C
#		define XTE_COMPILER_MIRACLE_C 1
#	endif
#
#	if defined(__MRC__) || defined(MPW_C) || defined(MPW_CPLUS)
#		undef XTE_COMPILER_MPW
#		undef XTE_COMPILER_MPW_MAJOR
#		undef XTE_COMPILER_MPW_MINOR
#		define XTE_COMPILER_MPW 1
#		define XTE_COMPILER_MPW_MAJOR ((__MRC__) / 0x100)
#		define XTE_COMPILER_MPW_MINOR ((__MRC__) % 0x100)
#	endif
#
#	ifdef _MSC_VER
#		undef XTE_COMPILER_MSVC
#		undef XTE_COMPILER_MSVC_MAJOR
#		undef XTE_COMPILER_MSVC_MINOR
#		undef XTE_COMPILER_MSVC_PATCH
#		define XTE_COMPILER_MSVC 1
#		ifdef _MSC_FULL_VER
#			define XTE_COMPILER_MSVC_MAJOR ((_MSC_FULL_VER) / 10000000)
#			define XTE_COMPILER_MSVC_MINOR ((_MSC_FULL_VER) % 10000000 / 100000)
#			define XTE_COMPILER_MSVC_PATCH ((_MSC_FULL_VER) % 100000)
#			ifdef _MSC_BUILD
#				undef XTE_COMPILER_MSVC_TWEAK
#				define XTE_COMPILER_MSVC_TWEAK (_MSC_BUILD)
#			endif
#		else
#			define XTE_COMPILER_MSVC_MAJOR ((_MSC_VER) / 100)
#			define XTE_COMPILER_MSVC_MINOR ((_MSC_VER) % 100)
#			define XTE_COMPILER_MSVC_PATCH 0
#		endif
#	endif
#
#	ifdef __NCC__
#		undef XTE_COMPILER_NCC
#		undef XTE_COMPILER_NCC_MAJOR
#		undef XTE_COMPILER_NCC_MINOR
#		define XTE_COMPILER_NCC 1
#		define XTE_COMPILER_NCC_MAJOR (__NCC_MAJOR__)
#		define XTE_COMPILER_NCC_MINOR (__NCC_MINOR__)
#	endif
#
#	ifdef __CC_NORCROFT
#		undef XTE_COMPILER_NORCROFT_C
#		define XTE_COMPILER_NORCROFT_C 1
#	endif
#
#	ifdef __NVCOMPILER
#		undef XTE_COMPILER_NVIDIA_HPC
#		undef XTE_COMPILER_NVIDIA_HPC_MAJOR
#		undef XTE_COMPILER_NVIDIA_HPC_MINOR
#		undef XTE_COMPILER_NVIDIA_HPC_PATCH
#		define XTE_COMPILER_NVIDIA_HPC 1
#		define XTE_COMPILER_NVIDIA_HPC_MAJOR (__NVCOMPILER_MAJOR__)
#		define XTE_COMPILER_NVIDIA_HPC_MINOR (__NVCOMPILER_MINOR__)
#		define XTE_COMPILER_NVIDIA_HPC_PATCH (__NVCOMPILER_PATCHLEVEL__)
#	endif
#
#	if defined(__CUDACC__) || defined(__NVCC__) || defined(HIPCC_PLATFORM_NVCC)
#		undef XTE_COMPILER_NVCC
#		undef XTE_COMPILER_NVCC_MAJOR
#		undef XTE_COMPILER_NVCC_MINOR
#		undef XTE_COMPILER_NVCC_PATCH
#		define XTE_COMPILER_NVCC 1
#		define XTE_COMPILER_NVCC_MAJOR (__CUDACC_VER_MAJOR__)
#		define XTE_COMPILER_NVCC_MINOR (__CUDACC_VER_MINOR__)
#		define XTE_COMPILER_NVCC_PATCH (__CUDACC_VER_BUILD__)
#	endif
#
#	ifdef __NWCC__
#		undef XTE_COMPILER_NWCC
#		define XTE_COMPILER_NWCC 1
#	endif
#
#	ifdef __OCC__
#		undef XTE_COMPILER_OCC
#		define XTE_COMPILER_OCC 1
#	endif
#
#	if defined(__OPEN64__) || defined(__OPENCC__)
#		undef XTE_COMPILER_OPEN64
#		undef XTE_COMPILER_OPEN64_MAJOR
#		undef XTE_COMPILER_OPEN64_MINOR
#		define XTE_COMPILER_OPEN64 1
#		define XTE_COMPILER_OPEN64_MAJOR (__OPENCC__)
#		define XTE_COMPILER_OPEN64_MINOR (__OPENCC_MINOR__)
#	endif
#
#	ifdef _OPENACC
#		undef XTE_COMPILER_OPENACC
#		define XTE_COMPILER_OPENACC 1
#	endif
#
#	ifdef _SCO_DS
#		undef XTE_COMPILER_OPENSERVER
#		define XTE_COMPILER_OPENSERVER 1
#	endif
#
#	ifdef ORA_PROC
#		undef XTE_COMPILER_ORACLE_PRO_C
#		define XTE_COMPILER_ORACLE_PRO_C 1
#	endif
#
#	if defined(__SUNPRO_C) || defined(__SUNPRO_CC)
#		undef XTE_COMPILER_ORACLE_SUN
#		undef XTE_COMPILER_ORACLE_SUN_MAJOR
#		undef XTE_COMPILER_ORACLE_SUN_MINOR
#		undef XTE_COMPILER_ORACLE_SUN_PATCH
#		define XTE_COMPILER_ORACLE_SUN 1
#		ifdef __SUNPRO_CC
#			if (__SUNPRO_CC) >= 0x5100
#				define XTE_COMPILER_ORACLE_SUN_MAJOR ((__SUNPRO_CC) / 0x1000)
#				define XTE_COMPILER_ORACLE_SUN_MINOR ((__SUNPRO_CC) / 0x10 % 0x100)
#				define XTE_COMPILER_ORACLE_SUN_PATCH ((__SUNPRO_CC) % 0x10)
#			else
#				define XTE_COMPILER_ORACLE_SUN_MAJOR ((__SUNPRO_CC) / 0x100)
#				define XTE_COMPILER_ORACLE_SUN_MINOR ((__SUNPRO_CC) / 0x10 % 0x10)
#				define XTE_COMPILER_ORACLE_SUN_PATCH ((__SUNPRO_CC) % 0x10)
#			endif
#		elif (__SUNPRO_C) >= 0x5100
#			define XTE_COMPILER_ORACLE_SUN_MAJOR ((__SUNPRO_C) / 0x1000)
#			define XTE_COMPILER_ORACLE_SUN_MINOR ((__SUNPRO_C) / 0x10 % 0x100)
#			define XTE_COMPILER_ORACLE_SUN_PATCH ((__SUNPRO_C) % 0x10)
#		else
#			define XTE_COMPILER_ORACLE_SUN_MAJOR ((__SUNPRO_C) / 0x100)
#			define XTE_COMPILER_ORACLE_SUN_MINOR ((__SUNPRO_C) / 0x10 % 0x10)
#			define XTE_COMPILER_ORACLE_SUN_PATCH ((__SUNPRO_C) % 0x10)
#		endif
#	endif
#
#	ifdef __ORANGEC__
#		undef XTE_COMPILER_ORANGE_C
#		undef XTE_COMPILER_ORANGE_C_MAJOR
#		undef XTE_COMPILER_ORANGE_C_MINOR
#		undef XTE_COMPILER_ORANGE_C_PATCH
#		define XTE_COMPILER_ORANGE_C 1
#		define XTE_COMPILER_ORANGE_C_MAJOR (__ORANGEC_MAJOR__)
#		define XTE_COMPILER_ORANGE_C_MINOR (__ORANGEC_MINOR__)
#		define XTE_COMPILER_ORANGE_C_PATCH (__ORANGEC_PATCHLEVEL__)
#	endif
#
#	ifdef __PACIFIC__
#		undef XTE_COMPILER_PACIFIC_C
#		define XTE_COMPILER_PACIFIC_C 1
#	endif
#
#	ifdef _PACC_VER
#		undef XTE_COMPILER_PALM
#		undef XTE_COMPILER_PALM_MAJOR
#		undef XTE_COMPILER_PALM_MINOR
#		undef XTE_COMPILER_PALM_PATCH
#		undef XTE_COMPILER_PALM_TWEAK
#		define XTE_COMPILER_PALM 1
#		define XTE_COMPILER_PALM_MAJOR ((_PACC_VER) / 0x10000000)
#		define XTE_COMPILER_PALM_MINOR ((_PACC_VER) / 0x100000 % 0x100)
#		define XTE_COMPILER_PALM_PATCH ((_PACC_VER) / 0x1000 % 0x100)
#		define XTE_COMPILER_PALM_TWEAK ((_PACC_VER) % 0x1000)
#	endif
#
#	ifdef __PCC__
#		undef XTE_COMPILER_PCC
#		undef XTE_COMPILER_PCC_MAJOR
#		undef XTE_COMPILER_PCC_MINOR
#		undef XTE_COMPILER_PCC_PATCH
#		define XTE_COMPILER_PCC 1
#		define XTE_COMPILER_PCC_MAJOR (__PCC__)
#		define XTE_COMPILER_PCC_MINOR (__PCC_MINOR__)
#		define XTE_COMPILER_PCC_PATCH (__PCC_MINORMINOR__)
#	endif
#
#	ifdef __POCC__
#		undef XTE_COMPILER_PELLES_C
#		undef XTE_COMPILER_PELLES_C_MAJOR
#		undef XTE_COMPILER_PELLES_C_MINOR
#		define XTE_COMPILER_PELLES_C 1
#		define XTE_COMPILER_PELLES_C_MAJOR ((__POCC__) / 100)
#		define XTE_COMPILER_PELLES_C_MINOR ((__POCC__) % 100)
#	endif
#
#	ifdef __PGI
#		undef XTE_COMPILER_PGI
#		undef XTE_COMPILER_PGI_MAJOR
#		undef XTE_COMPILER_PGI_MINOR
#		undef XTE_COMPILER_PGI_PATCH
#		define XTE_COMPILER_PGI 1
#		define XTE_COMPILER_PGI_MAJOR (__PGIC__)
#		define XTE_COMPILER_PGI_MINOR (__PGIC_MINOR__)
#		define XTE_COMPILER_PGI_PATCH (__PGIC_PATCHLEVEL__)
#	endif
#
#	ifdef __PUREC__
#		undef XTE_COMPILER_PUREC
#		define XTE_COMPILER_PUREC 1
#	endif
#
#	ifdef __PW32__
#		undef XTE_COMPILER_PW32
#		define XTE_COMPILER_PW32 1
#	endif
#
#	ifdef _QC
#		undef XTE_COMPILER_QUICKC
#		define XTE_COMPILER_QUICKC 1
#	endif
#
#	if defined(__HITACHI__) || defined(__RENESAS__)
#		undef XTE_COMPILER_RENESAS
#		undef XTE_COMPILER_RENESAS_MAJOR
#		undef XTE_COMPILER_RENESAS_MINOR
#		undef XTE_COMPILER_RENESAS_PATCH
#		define XTE_COMPILER_RENESAS 1
#		if (__RENESAS_VERSION__) >= 0x10000
#			define XTE_COMPILER_RENESAS_MAJOR ((__RENESAS_VERSION__) / 0x1000000)
#			define XTE_COMPILER_RENESAS_MINOR ((__RENESAS_VERSION__) / 0x10000 % 0x100)
#			define XTE_COMPILER_RENESAS_PATCH ((__RENESAS_VERSION__) / 0x100 % 0x100)
#		else
#			define XTE_COMPILER_RENESAS_MAJOR ((__RENESAS_VERSION__) / 0x100)
#			define XTE_COMPILER_RENESAS_MINOR ((__RENESAS_VERSION__) % 0x100)
#			define XTE_COMPILER_RENESAS_PATCH 0
#		endif
#	endif
#
#	if defined(__SDCC) || defined(SDCC)
#		undef XTE_COMPILER_SDCC
#		undef XTE_COMPILER_SDCC_MAJOR
#		undef XTE_COMPILER_SDCC_MINOR
#		undef XTE_COMPILER_SDCC_PATCH
#		define XTE_COMPILER_SDCC 1
#		ifdef __SDCC
#			define XTE_COMPILER_SDCC_MAJOR (__SDCC_VERSION_MAJOR)
#			define XTE_COMPILER_SDCC_MINOR (__SDCC_VERSION_MINOR)
#			define XTE_COMPILER_SDCC_MINOR (__SDCC_VERSION_PATCH)
#		else
#			define XTE_COMPILER_SDCC_MAJOR ((SDCC) / 100)
#			define XTE_COMPILER_SDCC_MINOR ((SDCC) / 10 % 10)
#			define XTE_COMPILER_SDCC_PATCH ((SDCC) % 10)
#		endif
#	endif
#
#	if defined(__ADSP21000__) || defined(_ADI_COMPILER)
#		undef XTE_COMPILER_SHARC
#		undef XTE_COMPILER_VISUALDSP_MAJOR
#		undef XTE_COMPILER_VISUALDSP_MINOR
#		undef XTE_COMPILER_VISUALDSP_PATCH
#		define XTE_COMPILER_SHARC 1
#		define XTE_COMPILER_VISUALDSP_MAJOR ((__VERSIONNUM__) / 0x1000000)
#		define XTE_COMPILER_VISUALDSP_MINOR ((__VERSIONNUM__) / 0x10000 % 0x100)
#		define XTE_COMPILER_VISUALDSP_PATCH ((__VERSIONNUM__) / 0x100 % 0x100)
#	endif
#
#	ifdef __SNC__
#		undef XTE_COMPILER_SNC
#		define XTE_COMPILER_SNC 1
#	endif
#
#	ifdef __SOZOBON__
#		undef XTE_COMPILER_SOZOBON
#		define XTE_COMPILER_SOZOBON 1
#	endif
#
#	ifdef __VOSC__
#		undef XTE_COMPILER_STRATUS_VOS_C
#		undef XTE_COMPILER_STRATUS_VOS_C_MAJOR
#		define XTE_COMPILER_STRATUS_VOS_C 1
#		define XTE_COMPILER_STRATUS_VOS_C_MAJOR (__VOSC__)
#	endif
#
#	ifdef __SC__
#		undef XTE_COMPILER_SYMANTEC_CPP
#		undef XTE_COMPILER_SYMANTEC_CPP_MAJOR
#		undef XTE_COMPILER_SYMANTEC_CPP_MINOR
#		define XTE_COMPILER_SYMANTEC_CPP 1
#		define XTE_COMPILER_SYMANTEC_CPP_MAJOR ((__SC__) / 0x100)
#		define XTE_COMPILER_SYMANTEC_CPP_MINOR ((__SC__) % 0x100)
#	endif
#
#	ifdef __TASKING__
#		undef XTE_COMPILER_TASKING
#		undef XTE_COMPILER_TASKING_MAJOR
#		undef XTE_COMPILER_TASKING_MINOR
#		define XTE_COMPILER_TASKING 1
#		define XTE_COMPILER_TASKING_MAJOR ((__VERSION__) / 1000)
#		define XTE_COMPILER_TASKING_MINOR ((__VERSION__) % 1000)
#	endif
#
#	ifdef __TINYC__
#		undef XTE_COMPILER_TCC
#		define XTE_COMPILER_TCC 1
#	endif
#
#	ifdef __TenDRA__
#		undef XTE_COMPILER_TENDRA
#		define XTE_COMPILER_TENDRA 1
#	endif
#
#	ifdef __ti__
#		undef XTE_COMPILER_TI
#		undef XTE_COMPILER_TI_MAJOR
#		undef XTE_COMPILER_TI_MINOR
#		undef XTE_COMPILER_TI_PATCH
#		define XTE_COMPILER_TI 1
#		define XTE_COMPILER_TI_MAJOR (__ti_major__)
#		define XTE_COMPILER_TI_MINOR (__ti_minor__)
#		define XTE_COMPILER_TI_PATCH (__ti_patchlevel__)
#	endif
#
#	ifdef _TMS320C6X
#		undef XTE_COMPILER_TI_CGT
#		undef XTE_COMPILER_TI_CGT_MAJOR
#		undef XTE_COMPILER_TI_CGT_MINOR
#		undef XTE_COMPILER_TI_CGT_PATCH
#		define XTE_COMPILER_TI_CGT 1
#		define XTE_COMPILER_TI_CGT_MAJOR ((__TI_COMPILER_VERSION__) / 1000000)
#		define XTE_COMPILER_TI_CGT_MINOR ((__TI_COMPILER_VERSION__) / 1000 % 1000)
#		define XTE_COMPILER_TI_CGT_PATCH ((__TI_COMPILER_VERSION__) % 1000)
#	endif
#
#	ifdef __MSP430__
#		undef XTE_COMPILER_TI_CL430
#		undef XTE_COMPILER_TI_CL430_MAJOR
#		undef XTE_COMPILER_TI_CL430_MINOR
#		undef XTE_COMPILER_TI_CL430_PATCH
#		define XTE_COMPILER_TI_CL430 1
#		define XTE_COMPILER_TI_CL430_MAJOR ((__TI_COMPILER_VERSION__) / 1000000)
#		define XTE_COMPILER_TI_CL430_MINOR ((__TI_COMPILER_VERSION__) / 1000 % 1000)
#		define XTE_COMPILER_TI_CL430_PATCH ((__TI_COMPILER_VERSION__) % 1000)
#	endif
#
#	ifdef __TSC__
#		undef XTE_COMPILER_TOPSPEED_C
#		define XTE_COMPILER_TOPSPEED_C 1
#	endif
#
#	ifdef __TURBOC__
#		undef XTE_COMPILER_TURBO
#		undef XTE_COMPILER_TURBO_MAJOR
#		undef XTE_COMPILER_TURBO_MINOR
#		define XTE_COMPILER_TURBO 1
#		define XTE_COMPILER_TURBO_MAJOR ((__TURBOC__) / 0x100)
#		define XTE_COMPILER_TURBO_MINOR ((__TURBOC__) % 0x100)
#	endif
#
#	ifdef _UCC
#		undef XTE_COMPILER_ULTIMATE
#		undef XTE_COMPILER_ULTIMATE_MAJOR
#		undef XTE_COMPILER_ULTIMATE_MINOR
#		define XTE_COMPILER_ULTIMATE 1
#		define XTE_COMPILER_ULTIMATE_MAJOR (_MAJOR_REV)
#		define XTE_COMPILER_ULTIMATE_MINOR (_MINOR_REV)
#	endif
#
#	ifdef __USLC__
#		undef XTE_COMPILER_USL_C
#		undef XTE_COMPILER_USL_C_MAJOR
#		undef XTE_COMPILER_USL_C_MINOR
#		define XTE_COMPILER_USL_C 1
#		define XTE_COMPILER_USL_C_MAJOR ((__SCO_VERSION__) / 100000000)
#		define XTE_COMPILER_USL_C_MINOR ((__SCO_VERSION__) / 1000000 % 100)
#	endif
#
#	ifdef __VBCC__
#		undef XTE_COMPILER_VBCC
#		define XTE_COMPILER_VBCC 1
#	endif
#
#	ifdef __VCM__
#		undef XTE_COMPILER_VCM
#		define XTE_COMPILER_VCM 1
#	endif
#
#	ifdef __WATCOMC__
#		undef XTE_COMPILER_WATCOM
#		undef XTE_COMPILER_WATCOM_MAJOR
#		undef XTE_COMPILER_WATCOM_MINOR
#		define XTE_COMPILER_WATCOM 1
#		define XTE_COMPILER_WATCOM_MAJOR ((__WATCOMC__) / 100)
#		define XTE_COMPILER_WATCOM_MINOR ((__WATCOMC__) % 100)
#	endif
#
#	ifdef __XC8
#		undef XTE_COMPILER_XC8
#		define XTE_COMPILER_XC8 1
#		ifdef __XC8_VERSION
#			undef XTE_COMPILER_XC8_MAJOR
#			undef XTE_COMPILER_XC8_MINOR
#			undef XTE_COMPILER_XC8_MAJOR
#			define XTE_COMPILER_XC8_MAJOR ((__XC8_VERSION) / 1000)
#			define XTE_COMPILER_XC8_MINOR ((__XC8_VERSION) / 10 % 100)
#			define XTE_COMPILER_XC8_MAJOR ((__XC8_VERSION) % 10)
#		endif
#	endif
#
#	if defined(C30) || defined(XC16) || defined(__C30) || defined(__C30__) || defined(__XC16) || defined(__XC16__) || defined(dsPICC30) || defined(__dsPICC30__) || defined(__dsPICC30) || defined(dsPIC30)
#		undef XTE_COMPILER_XC16
#		define XTE_COMPILER_XC16 1
#		ifdef __XC16_VERSION
#			undef XTE_COMPILER_XC16_MAJOR
#			undef XTE_COMPILER_XC16_MINOR
#			define XTE_COMPILER_XC16_MAJOR ((__XC16_VERSION) / 1000)
#			define XTE_COMPILER_XC16_MINOR ((__XC16_VERSION) / 10 % 100)
#		endif
#	endif
#
#	ifdef __XC32
#		undef XTE_COMPILER_XC32
#		undef XTE_COMPILER_XC32_MAJOR
#		undef XTE_COMPILER_XC32_MINOR
#		define XTE_COMPILER_XC32 1
#		define XTE_COMPILER_XC32_MAJOR ((__XC32_VERSION) / 1000)
#		define XTE_COMPILER_XC32_MINOR ((__XC32_VERSION) / 10 % 100)
#	endif
#
#	if defined(__DCC__) || defined(_DIAB_TOOL)
#		undef XTE_COMPILER_WIND_RIVER_DIAB
#		undef XTE_COMPILER_WIND_RIVER_DIAB_MAJOR
#		undef XTE_COMPILER_WIND_RIVER_DIAB_MINOR
#		undef XTE_COMPILER_WIND_RIVER_DIAB_PATCH
#		undef XTE_COMPILER_WIND_RIVER_DIAB_TWEAK
#		define XTE_COMPILER_WIND_RIVER_DIAB 1
#		ifdef __VERSION_MAJOR_NUMBER__
#			define XTE_COMPILER_WIND_RIVER_DIAB_MAJOR (__VERSION_MAJOR_NUMBER__)
#			define XTE_COMPILER_WIND_RIVER_DIAB_MINOR (__VERSION_MINOR_NUMBER__)
#			define XTE_COMPILER_WIND_RIVER_DIAB_PATCH (__VERSION_ARCH_FEATURE_NUMBER__)
#			define XTE_COMPILER_WIND_RIVER_DIAB_TWEAK (__VERSION_BUG_FIX_NUMBER__)
#		else
#			define XTE_COMPILER_WIND_RIVER_DIAB_MAJOR ((__VERSION_NUMBER__) / 1000)
#			define XTE_COMPILER_WIND_RIVER_DIAB_MINOR ((__VERSION_NUMBER__) / 100 % 10)
#			define XTE_COMPILER_WIND_RIVER_DIAB_PATCH ((__VERSION_NUMBER__) % 100)
#			define XTE_COMPILER_WIND_RIVER_DIAB_TWEAK 0
#		endif
#	endif
#
#	ifdef __ZTC__
#		undef XTE_COMPILER_ZORTECH
#		undef XTE_COMPILER_ZORTECH_MAJOR
#		undef XTE_COMPILER_ZORTECH_MINOR
#		undef XTE_COMPILER_ZORTECH_PATCH
#		define XTE_COMPILER_ZORTECH 1
#		define XTE_COMPILER_ZORTECH_MAJOR ((__ZTC__) / 0x100)
#		define XTE_COMPILER_ZORTECH_MINOR ((__ZTC__) / 0x10 % 0x10)
#		define XTE_COMPILER_ZORTECH_PATCH ((__ZTC__) % 0x10)
#	endif
#
#	if defined(__SCCZ80) || defined(SCCZ80)
#		undef XTE_COMPILER_Z88DK
#		define XTE_COMPILER_Z88DK 1
#	endif
#
#	define DETAIL_XTE_COMPILER(OP, LHS_MAJOR, LHS_MINOR, LHS_PATCH, LHS_TWEAK, RHS_MAJOR, RHS_MINOR, RHS_PATCH, RHS_TWEAK, ...) \
		(((((0 OP 0) && !(0 OP 1) && !(1 OP 0)) \
			|| (!(0 OP 0) && (0 OP 1) && (1 OP 0))) \
		&& (((LHS_MAJOR) OP (RHS_MAJOR)) \
			&& ((LHS_MINOR) OP (RHS_MINOR)) \
			&& ((LHS_PATCH) OP (RHS_PATCH)) \
			&& ((LHS_TWEAK) OP (RHS_TWEAK)))) \
		|| ((LHS_MAJOR) OP (RHS_MAJOR)) \
			|| (((LHS_MAJOR) == (RHS_MAJOR)) && ((LHS_MINOR) OP (RHS_MINOR))) \
			|| (((LHS_MINOR) == (RHS_MINOR)) && ((LHS_PATCH) OP (RHS_PATCH))) \
			|| (((LHS_PATCH) == (RHS_PATCH)) && ((LHS_TWEAK) OP (RHS_TWEAK))))
#endif

// https://github.com/cpredef/predef/blob/master/Compilers.md
// https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#nvcc-identification-macro
