#ifndef DETAIL_XTE_HEADER_PREPROC_COMPILER
#	define DETAIL_XTE_HEADER_PREPROC_COMPILER
#
#	define XTE_COMPILER_ACK 0
#	define XTE_COMPILER_ACK_MAJOR 0
#	define XTE_COMPILER_ACK_MINOR 0
#	define XTE_COMPILER_ACK_PATCH 0
#	define XTE_COMPILER_ADSP 0
#	define XTE_COMPILER_ADSP_MAJOR 0
#	define XTE_COMPILER_ADSP_MINOR 0
#	define XTE_COMPILER_ADSP_PATCH 0
#	define XTE_COMPILER_AHCC 0
#	define XTE_COMPILER_AHCC_MAJOR 0
#	define XTE_COMPILER_AHCC_MINOR 0
#	define XTE_COMPILER_AHCC_PATCH 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MAJOR 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MINOR 0
#	define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_PATCH 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MAJOR 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MINOR 0
#	define XTE_COMPILER_ALTIUM_MICROBLAZE_C_PATCH 0
#	define XTE_COMPILER_AOCC 0
#	define XTE_COMPILER_AOCC_MAJOR 0
#	define XTE_COMPILER_AOCC_MINOR 0
#	define XTE_COMPILER_AOCC_PATCH 0
#	define XTE_COMPILER_ARMCC 0
#	define XTE_COMPILER_ARMCC_MAJOR 0
#	define XTE_COMPILER_ARMCC_MINOR 0
#	define XTE_COMPILER_ARMCC_PATCH 0
#	define XTE_COMPILER_AZTEC_C 0
#	define XTE_COMPILER_AZTEC_C_MAJOR 0
#	define XTE_COMPILER_AZTEC_C_MINOR 0
#	define XTE_COMPILER_AZTEC_C_PATCH 0
#	define XTE_COMPILER_BCC 0
#	define XTE_COMPILER_BCC_MAJOR 0
#	define XTE_COMPILER_BCC_MINOR 0
#	define XTE_COMPILER_BCC_PATCH 0
#	define XTE_COMPILER_BORLAND 0
#	define XTE_COMPILER_BORLAND_MAJOR 0
#	define XTE_COMPILER_BORLAND_MINOR 0
#	define XTE_COMPILER_BORLAND_PATCH 0
#	define XTE_COMPILER_C2 0
#	define XTE_COMPILER_C2_MAJOR 0
#	define XTE_COMPILER_C2_MINOR 0
#	define XTE_COMPILER_C2_PATCH 0
#	define XTE_COMPILER_CASTXML 0
#	define XTE_COMPILER_CASTXML_MAJOR 0
#	define XTE_COMPILER_CASTXML_MINOR 0
#	define XTE_COMPILER_CASTXML_PATCH 0
#	define XTE_COMPILER_CC65 0
#	define XTE_COMPILER_CC65_MAJOR 0
#	define XTE_COMPILER_CC65_MINOR 0
#	define XTE_COMPILER_CC65_PATCH 0
#	define XTE_COMPILER_CILLY 0
#	define XTE_COMPILER_CILLY_MAJOR 0
#	define XTE_COMPILER_CILLY_MINOR 0
#	define XTE_COMPILER_CILLY_PATCH 0
#	define XTE_COMPILER_CIRCLE 0
#	define XTE_COMPILER_CIRCLE_MAJOR 0
#	define XTE_COMPILER_CIRCLE_MINOR 0
#	define XTE_COMPILER_CIRCLE_PATCH 0
#	define XTE_COMPILER_CLANG 0
#	define XTE_COMPILER_CLANG_MAJOR 0
#	define XTE_COMPILER_CLANG_MINOR 0
#	define XTE_COMPILER_CLANG_PATCH 0
#	define XTE_COMPILER_COMEAU 0
#	define XTE_COMPILER_COMEAU_MAJOR 0
#	define XTE_COMPILER_COMEAU_MINOR 0
#	define XTE_COMPILER_COMEAU_PATCH 0
#	define XTE_COMPILER_COMPAQ_C 0
#	define XTE_COMPILER_COMPAQ_C_MAJOR 0
#	define XTE_COMPILER_COMPAQ_C_MINOR 0
#	define XTE_COMPILER_COMPAQ_C_PATCH 0
#	define XTE_COMPILER_COMPAQ_CPP 0
#	define XTE_COMPILER_COMPAQ_CPP_MAJOR 0
#	define XTE_COMPILER_COMPAQ_CPP_MINOR 0
#	define XTE_COMPILER_COMPAQ_CPP_PATCH 0
#	define XTE_COMPILER_COMPCERT 0
#	define XTE_COMPILER_COMPCERT_MAJOR 0
#	define XTE_COMPILER_COMPCERT_MINOR 0
#	define XTE_COMPILER_COMPCERT_PATCH 0
#	define XTE_COMPILER_CONVEX_C 0
#	define XTE_COMPILER_CONVEX_C_MAJOR 0
#	define XTE_COMPILER_CONVEX_C_MINOR 0
#	define XTE_COMPILER_CONVEX_C_PATCH 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER_MAJOR 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER_MINOR 0
#	define XTE_COMPILER_COVERITY_STATIC_ANALYZER_PATCH 0
#	define XTE_COMPILER_CRAY_C 0
#	define XTE_COMPILER_CRAY_C_MAJOR 0
#	define XTE_COMPILER_CRAY_C_MINOR 0
#	define XTE_COMPILER_CRAY_C_PATCH 0
#	define XTE_COMPILER_CRAY_F90 0
#	define XTE_COMPILER_CRAY_F90_MAJOR 0
#	define XTE_COMPILER_CRAY_F90_MINOR 0
#	define XTE_COMPILER_CRAY_F90_PATCH 0
#	define XTE_COMPILER_DIGITAL_MARS 0
#	define XTE_COMPILER_DIGITAL_MARS_MAJOR 0
#	define XTE_COMPILER_DIGITAL_MARS_MINOR 0
#	define XTE_COMPILER_DIGITAL_MARS_PATCH 0
#	define XTE_COMPILER_DICE_C 0
#	define XTE_COMPILER_DICE_C_MAJOR 0
#	define XTE_COMPILER_DICE_C_MINOR 0
#	define XTE_COMPILER_DICE_C_PATCH 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MAJOR 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MINOR 0
#	define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_PATCH 0
#	define XTE_COMPILER_DJGPP 0
#	define XTE_COMPILER_DJGPP_MAJOR 0
#	define XTE_COMPILER_DJGPP_MINOR 0
#	define XTE_COMPILER_DJGPP_PATCH 0
#	define XTE_COMPILER_EDG 0
#	define XTE_COMPILER_EDG_MAJOR 0
#	define XTE_COMPILER_EDG_MINOR 0
#	define XTE_COMPILER_EDG_PATCH 0
#	define XTE_COMPILER_EKOPATH 0
#	define XTE_COMPILER_EKOPATH_MAJOR 0
#	define XTE_COMPILER_EKOPATH_MINOR 0
#	define XTE_COMPILER_EKOPATH_PATCH 0
#	define XTE_COMPILER_ELLCC 0
#	define XTE_COMPILER_ELLCC_MAJOR 0
#	define XTE_COMPILER_ELLCC_MINOR 0
#	define XTE_COMPILER_ELLCC_PATCH 0
#	define XTE_COMPILER_F2C 0
#	define XTE_COMPILER_F2C_MAJOR 0
#	define XTE_COMPILER_F2C_MINOR 0
#	define XTE_COMPILER_F2C_PATCH 0
#	define XTE_COMPILER_FLANG 0
#	define XTE_COMPILER_FLANG_MAJOR 0
#	define XTE_COMPILER_FLANG_MINOR 0
#	define XTE_COMPILER_FLANG_PATCH 0
#	define XTE_COMPILER_FUJITSU_CPP 0
#	define XTE_COMPILER_FUJITSU_CPP_MAJOR 0
#	define XTE_COMPILER_FUJITSU_CPP_MINOR 0
#	define XTE_COMPILER_FUJITSU_CPP_PATCH 0
#	define XTE_COMPILER_GCC 0
#	define XTE_COMPILER_GCC_MAJOR 0
#	define XTE_COMPILER_GCC_MINOR 0
#	define XTE_COMPILER_GCC_PATCH 0
#	define XTE_COMPILER_GCCXML 0
#	define XTE_COMPILER_GCCXML_MAJOR 0
#	define XTE_COMPILER_GCCXML_MINOR 0
#	define XTE_COMPILER_GCCXML_PATCH 0
#	define XTE_COMPILER_GNU_F95 0
#	define XTE_COMPILER_GNU_F95_MAJOR 0
#	define XTE_COMPILER_GNU_F95_MINOR 0
#	define XTE_COMPILER_GNU_F95_PATCH 0
#	define XTE_COMPILER_GREEN_HILLS 0
#	define XTE_COMPILER_GREEN_HILLS_MAJOR 0
#	define XTE_COMPILER_GREEN_HILLS_MINOR 0
#	define XTE_COMPILER_GREEN_HILLS_PATCH 0
#	define XTE_COMPILER_HEXAGON 0
#	define XTE_COMPILER_HEXAGON_MAJOR 0
#	define XTE_COMPILER_HEXAGON_MINOR 0
#	define XTE_COMPILER_HEXAGON_PATCH 0
#	define XTE_COMPILER_HIPCC 0
#	define XTE_COMPILER_HIPCC_MAJOR 0
#	define XTE_COMPILER_HIPCC_MINOR 0
#	define XTE_COMPILER_HIPCC_PATCH 0
#	define XTE_COMPILER_HPUX_C 0
#	define XTE_COMPILER_HPUX_C_MAJOR 0
#	define XTE_COMPILER_HPUX_C_MINOR 0
#	define XTE_COMPILER_HPUX_C_PATCH 0
#	define XTE_COMPILER_HPUX_CPP 0
#	define XTE_COMPILER_HPUX_CPP_MAJOR 0
#	define XTE_COMPILER_HPUX_CPP_MINOR 0
#	define XTE_COMPILER_HPUX_CPP_PATCH 0
#	define XTE_COMPILER_HSC 0
#	define XTE_COMPILER_HSC_MAJOR 0
#	define XTE_COMPILER_HSC_MINOR 0
#	define XTE_COMPILER_HSC_PATCH 0
#	define XTE_COMPILER_IAR 0
#	define XTE_COMPILER_IAR_MAJOR 0
#	define XTE_COMPILER_IAR_MINOR 0
#	define XTE_COMPILER_IAR_PATCH 0
#	define XTE_COMPILER_ICC 0
#	define XTE_COMPILER_ICC_MAJOR 0
#	define XTE_COMPILER_ICC_MINOR 0
#	define XTE_COMPILER_ICC_PATCH 0
#	define XTE_COMPILER_ICX 0
#	define XTE_COMPILER_ICX_MAJOR 0
#	define XTE_COMPILER_ICX_MINOR 0
#	define XTE_COMPILER_ICX_PATCH 0
#	define XTE_COMPILER_IMAGECRAFT_C 0
#	define XTE_COMPILER_IMAGECRAFT_C_MAJOR 0
#	define XTE_COMPILER_IMAGECRAFT_C_MINOR 0
#	define XTE_COMPILER_IMAGECRAFT_C_PATCH 0
#	define XTE_COMPILER_KCC 0
#	define XTE_COMPILER_KCC_MAJOR 0
#	define XTE_COMPILER_KCC_MINOR 0
#	define XTE_COMPILER_KCC_PATCH 0
#	define XTE_COMPILER_KEIL_C166 0
#	define XTE_COMPILER_KEIL_C166_MAJOR 0
#	define XTE_COMPILER_KEIL_C166_MINOR 0
#	define XTE_COMPILER_KEIL_C166_PATCH 0
#	define XTE_COMPILER_KEIL_C51 0
#	define XTE_COMPILER_KEIL_C51_MAJOR 0
#	define XTE_COMPILER_KEIL_C51_MINOR 0
#	define XTE_COMPILER_KEIL_C51_PATCH 0
#	define XTE_COMPILER_KEIL_CARM 0
#	define XTE_COMPILER_KEIL_CARM_MAJOR 0
#	define XTE_COMPILER_KEIL_CARM_MINOR 0
#	define XTE_COMPILER_KEIL_CARM_PATCH 0
#	define XTE_COMPILER_KICKC 0
#	define XTE_COMPILER_KICKC_MAJOR 0
#	define XTE_COMPILER_KICKC_MINOR 0
#	define XTE_COMPILER_KICKC_PATCH 0
#	define XTE_COMPILER_LATTICE_C 0
#	define XTE_COMPILER_LATTICE_C_MAJOR 0
#	define XTE_COMPILER_LATTICE_C_MINOR 0
#	define XTE_COMPILER_LATTICE_C_PATCH 0
#	define XTE_COMPILER_LCC 0
#	define XTE_COMPILER_LCC_MAJOR 0
#	define XTE_COMPILER_LCC_MINOR 0
#	define XTE_COMPILER_LCC_PATCH 0
#	define XTE_COMPILER_LIGHTSPEED_C 0
#	define XTE_COMPILER_LIGHTSPEED_C_MAJOR 0
#	define XTE_COMPILER_LIGHTSPEED_C_MINOR 0
#	define XTE_COMPILER_LIGHTSPEED_C_PATCH 0
#	define XTE_COMPILER_LLVM 0
#	define XTE_COMPILER_LLVM_MAJOR 0
#	define XTE_COMPILER_LLVM_MINOR 0
#	define XTE_COMPILER_LLVM_PATCH 0
#	define XTE_COMPILER_MCST_LLC 0
#	define XTE_COMPILER_MCST_LLC_MAJOR 0
#	define XTE_COMPILER_MCST_LLC_MINOR 0
#	define XTE_COMPILER_MCST_LLC_PATCH 0
#	define XTE_COMPILER_METAWARE_HIGH 0
#	define XTE_COMPILER_METAWARE_HIGH_MAJOR 0
#	define XTE_COMPILER_METAWARE_HIGH_MINOR 0
#	define XTE_COMPILER_METAWARE_HIGH_PATCH 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR 0
#	define XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH 0
#	define XTE_COMPILER_MICROTEC 0
#	define XTE_COMPILER_MICROTEC_MAJOR 0
#	define XTE_COMPILER_MICROTEC_MINOR 0
#	define XTE_COMPILER_MICROTEC_PATCH 0
#	define XTE_COMPILER_MICROWAY_NDP_C 0
#	define XTE_COMPILER_MICROWAY_NDP_C_MAJOR 0
#	define XTE_COMPILER_MICROWAY_NDP_C_MINOR 0
#	define XTE_COMPILER_MICROWAY_NDP_C_PATCH 0
#	define XTE_COMPILER_MINGW32 0
#	define XTE_COMPILER_MINGW32_MAJOR 0
#	define XTE_COMPILER_MINGW32_MINOR 0
#	define XTE_COMPILER_MINGW32_PATCH 0
#	define XTE_COMPILER_MINGW_W64 0
#	define XTE_COMPILER_MINGW_W64_MAJOR 0
#	define XTE_COMPILER_MINGW_W64_MINOR 0
#	define XTE_COMPILER_MINGW_W64_PATCH 0
#	define XTE_COMPILER_MIPSPRO 0
#	define XTE_COMPILER_MIPSPRO_MAJOR 0
#	define XTE_COMPILER_MIPSPRO_MINOR 0
#	define XTE_COMPILER_MIPSPRO_PATCH 0
#	define XTE_COMPILER_MIRACLE_C 0
#	define XTE_COMPILER_MIRACLE_C_MAJOR 0
#	define XTE_COMPILER_MIRACLE_C_MINOR 0
#	define XTE_COMPILER_MIRACLE_C_PATCH 0
#	define XTE_COMPILER_MPW 0
#	define XTE_COMPILER_MPW_MAJOR 0
#	define XTE_COMPILER_MPW_MINOR 0
#	define XTE_COMPILER_MPW_PATCH 0
#	define XTE_COMPILER_MSVC 0
#	define XTE_COMPILER_MSVC_MAJOR 0
#	define XTE_COMPILER_MSVC_MINOR 0
#	define XTE_COMPILER_MSVC_PATCH 0
#	define XTE_COMPILER_NCC 0
#	define XTE_COMPILER_NCC_MAJOR 0
#	define XTE_COMPILER_NCC_MINOR 0
#	define XTE_COMPILER_NCC_PATCH 0
#	define XTE_COMPILER_NORCROFT_C 0
#	define XTE_COMPILER_NORCROFT_C_MAJOR 0
#	define XTE_COMPILER_NORCROFT_C_MINOR 0
#	define XTE_COMPILER_NORCROFT_C_PATCH 0
#	define XTE_COMPILER_NVIDIA_HPC 0
#	define XTE_COMPILER_NVIDIA_HPC_MAJOR 0
#	define XTE_COMPILER_NVIDIA_HPC_MINOR 0
#	define XTE_COMPILER_NVIDIA_HPC_PATCH 0
#	define XTE_COMPILER_NVCC 0
#	define XTE_COMPILER_NVCC_MAJOR 0
#	define XTE_COMPILER_NVCC_MINOR 0
#	define XTE_COMPILER_NVCC_PATCH 0
#	define XTE_COMPILER_NWCC 0
#	define XTE_COMPILER_NWCC_MAJOR 0
#	define XTE_COMPILER_NWCC_MINOR 0
#	define XTE_COMPILER_NWCC_PATCH 0
#	define XTE_COMPILER_OCC 0
#	define XTE_COMPILER_OCC_MAJOR 0
#	define XTE_COMPILER_OCC_MINOR 0
#	define XTE_COMPILER_OCC_PATCH 0
#	define XTE_COMPILER_OPEN64 0
#	define XTE_COMPILER_OPEN64_MAJOR 0
#	define XTE_COMPILER_OPEN64_MINOR 0
#	define XTE_COMPILER_OPEN64_PATCH 0
#	define XTE_COMPILER_OPENACC 0
#	define XTE_COMPILER_OPENACC_MAJOR 0
#	define XTE_COMPILER_OPENACC_MINOR 0
#	define XTE_COMPILER_OPENACC_PATCH 0
#	define XTE_COMPILER_OPENSERVER 0
#	define XTE_COMPILER_OPENSERVER_MAJOR 0
#	define XTE_COMPILER_OPENSERVER_MINOR 0
#	define XTE_COMPILER_OPENSERVER_PATCH 0
#	define XTE_COMPILER_ORANGE_C 0
#	define XTE_COMPILER_ORANGE_C_MAJOR 0
#	define XTE_COMPILER_ORANGE_C_MINOR 0
#	define XTE_COMPILER_ORANGE_C_PATCH 0
#	define XTE_COMPILER_PACIFIC_C 0
#	define XTE_COMPILER_PACIFIC_C_MAJOR 0
#	define XTE_COMPILER_PACIFIC_C_MINOR 0
#	define XTE_COMPILER_PACIFIC_C_PATCH 0
#	define XTE_COMPILER_PALM 0
#	define XTE_COMPILER_PALM_MAJOR 0
#	define XTE_COMPILER_PALM_MINOR 0
#	define XTE_COMPILER_PALM_PATCH 0
#	define XTE_COMPILER_PCC 0
#	define XTE_COMPILER_PCC_MAJOR 0
#	define XTE_COMPILER_PCC_MINOR 0
#	define XTE_COMPILER_PCC_PATCH 0
#	define XTE_COMPILER_PELLES_C 0
#	define XTE_COMPILER_PELLES_C_MAJOR 0
#	define XTE_COMPILER_PELLES_C_MINOR 0
#	define XTE_COMPILER_PELLES_C_PATCH 0
#	define XTE_COMPILER_PGI 0
#	define XTE_COMPILER_PGI_MAJOR 0
#	define XTE_COMPILER_PGI_MINOR 0
#	define XTE_COMPILER_PGI_PATCH 0
#	define XTE_COMPILER_PUREC 0
#	define XTE_COMPILER_PUREC_MAJOR 0
#	define XTE_COMPILER_PUREC_MINOR 0
#	define XTE_COMPILER_PUREC_PATCH 0
#	define XTE_COMPILER_PRO_C 0
#	define XTE_COMPILER_PRO_C_MAJOR 0
#	define XTE_COMPILER_PRO_C_MINOR 0
#	define XTE_COMPILER_PRO_C_PATCH 0
#	define XTE_COMPILER_PW32 0
#	define XTE_COMPILER_PW32_MAJOR 0
#	define XTE_COMPILER_PW32_MINOR 0
#	define XTE_COMPILER_PW32_PATCH 0
#	define XTE_COMPILER_QUICKC 0
#	define XTE_COMPILER_QUICKC_MAJOR 0
#	define XTE_COMPILER_QUICKC_MINOR 0
#	define XTE_COMPILER_QUICKC_PATCH 0
#	define XTE_COMPILER_RENESAS 0
#	define XTE_COMPILER_RENESAS_MAJOR 0
#	define XTE_COMPILER_RENESAS_MINOR 0
#	define XTE_COMPILER_RENESAS_PATCH 0
#	define XTE_COMPILER_SDCC 0
#	define XTE_COMPILER_SDCC_MAJOR 0
#	define XTE_COMPILER_SDCC_MINOR 0
#	define XTE_COMPILER_SDCC_PATCH 0
#	define XTE_COMPILER_SHARC 0
#	define XTE_COMPILER_SHARC_MAJOR 0
#	define XTE_COMPILER_SHARC_MINOR 0
#	define XTE_COMPILER_SHARC_PATCH 0
#	define XTE_COMPILER_SNC 0
#	define XTE_COMPILER_SNC_MAJOR 0
#	define XTE_COMPILER_SNC_MINOR 0
#	define XTE_COMPILER_SNC_PATCH 0
#	define XTE_COMPILER_SOZOBON 0
#	define XTE_COMPILER_SOZOBON_MAJOR 0
#	define XTE_COMPILER_SOZOBON_MINOR 0
#	define XTE_COMPILER_SOZOBON_PATCH 0
#	define XTE_COMPILER_STRATUS_VOS_C 0
#	define XTE_COMPILER_STRATUS_VOS_C_MAJOR 0
#	define XTE_COMPILER_STRATUS_VOS_C_MINOR 0
#	define XTE_COMPILER_STRATUS_VOS_C_PATCH 0
#	define XTE_COMPILER_SUNPRO_C 0
#	define XTE_COMPILER_SUNPRO_C_MAJOR 0
#	define XTE_COMPILER_SUNPRO_C_MINOR 0
#	define XTE_COMPILER_SUNPRO_C_PATCH 0
#	define XTE_COMPILER_SUNPRO_CPP 0
#	define XTE_COMPILER_SUNPRO_CPP_MAJOR 0
#	define XTE_COMPILER_SUNPRO_CPP_MINOR 0
#	define XTE_COMPILER_SUNPRO_CPP_PATCH 0
#	define XTE_COMPILER_SYMANTEC_CPP 0
#	define XTE_COMPILER_SYMANTEC_CPP_MAJOR 0
#	define XTE_COMPILER_SYMANTEC_CPP_MINOR 0
#	define XTE_COMPILER_SYMANTEC_CPP_PATCH 0
#	define XTE_COMPILER_TCC 0
#	define XTE_COMPILER_TCC_MAJOR 0
#	define XTE_COMPILER_TCC_MINOR 0
#	define XTE_COMPILER_TCC_PATCH 0
#	define XTE_COMPILER_TENDRA 0
#	define XTE_COMPILER_TENDRA_MAJOR 0
#	define XTE_COMPILER_TENDRA_MINOR 0
#	define XTE_COMPILER_TENDRA_PATCH 0
#	define XTE_COMPILER_TI_CGT 0
#	define XTE_COMPILER_TI_CGT_MAJOR 0
#	define XTE_COMPILER_TI_CGT_MINOR 0
#	define XTE_COMPILER_TI_CGT_PATCH 0
#	define XTE_COMPILER_TI_CL430 0
#	define XTE_COMPILER_TI_CL430_MAJOR 0
#	define XTE_COMPILER_TI_CL430_MINOR 0
#	define XTE_COMPILER_TI_CL430_PATCH 0
#	define XTE_COMPILER_TOPSPEED_C 0
#	define XTE_COMPILER_TOPSPEED_C_MAJOR 0
#	define XTE_COMPILER_TOPSPEED_C_MINOR 0
#	define XTE_COMPILER_TOPSPEED_C_PATCH 0
#	define XTE_COMPILER_TURBO 0
#	define XTE_COMPILER_TURBO_MAJOR 0
#	define XTE_COMPILER_TURBO_MINOR 0
#	define XTE_COMPILER_TURBO_PATCH 0
#	define XTE_COMPILER_ULTIMATE 0
#	define XTE_COMPILER_ULTIMATE_MAJOR 0
#	define XTE_COMPILER_ULTIMATE_MINOR 0
#	define XTE_COMPILER_ULTIMATE_PATCH 0
#	define XTE_COMPILER_USL_C 0
#	define XTE_COMPILER_USL_C_MAJOR 0
#	define XTE_COMPILER_USL_C_MINOR 0
#	define XTE_COMPILER_USL_C_PATCH 0
#	define XTE_COMPILER_VBCC 0
#	define XTE_COMPILER_VBCC_MAJOR 0
#	define XTE_COMPILER_VBCC_MINOR 0
#	define XTE_COMPILER_VBCC_PATCH 0
#	define XTE_COMPILER_VCM 0
#	define XTE_COMPILER_VCM_MAJOR 0
#	define XTE_COMPILER_VCM_MINOR 0
#	define XTE_COMPILER_VCM_PATCH 0
#	define XTE_COMPILER_WATCOM 0
#	define XTE_COMPILER_WATCOM_MAJOR 0
#	define XTE_COMPILER_WATCOM_MINOR 0
#	define XTE_COMPILER_WATCOM_PATCH 0
#	define XTE_COMPILER_WIND_RIVER_DIAB 0
#	define XTE_COMPILER_WIND_RIVER_DIAB_MAJOR 0
#	define XTE_COMPILER_WIND_RIVER_DIAB_MINOR 0
#	define XTE_COMPILER_WIND_RIVER_DIAB_PATCH 0
#	define XTE_COMPILER_XC8 0
#	define XTE_COMPILER_XC8_MAJOR 0
#	define XTE_COMPILER_XC8_MINOR 0
#	define XTE_COMPILER_XC8_PATCH 0
#	define XTE_COMPILER_XC16 0
#	define XTE_COMPILER_XC16_MAJOR 0
#	define XTE_COMPILER_XC16_MINOR 0
#	define XTE_COMPILER_XC16_PATCH 0
#	define XTE_COMPILER_XC32 0
#	define XTE_COMPILER_XC32_MAJOR 0
#	define XTE_COMPILER_XC32_MINOR 0
#	define XTE_COMPILER_XC32_PATCH 0
#	define XTE_COMPILER_XC_DSC 0
#	define XTE_COMPILER_XC_DSC_MAJOR 0
#	define XTE_COMPILER_XC_DSC_MINOR 0
#	define XTE_COMPILER_XC_DSC_PATCH 0
#	define XTE_COMPILER_XL 0
#	define XTE_COMPILER_XL_MAJOR 0
#	define XTE_COMPILER_XL_MINOR 0
#	define XTE_COMPILER_XL_PATCH 0
#	define XTE_COMPILER_ZORTECH_CPP 0
#	define XTE_COMPILER_ZORTECH_CPP_MAJOR 0
#	define XTE_COMPILER_ZORTECH_CPP_MINOR 0
#	define XTE_COMPILER_ZORTECH_CPP_PATCH 0
#	define XTE_COMPILER_Z88DK 0
#	define XTE_COMPILER_Z88DK_MAJOR 0
#	define XTE_COMPILER_Z88DK_MINOR 0
#	define XTE_COMPILER_Z88DK_PATCH 0
#
#	define XTE_COMPILER(_type, _operator, _major, ...) \
		DETAIL_XTE_COMPILER( \
			_operator, \
			XTE_COMPILER__MAJOR##_type, XTE_COMPILER__MINOR##_type, XTE_COMPILER__PATCH##_type, \
			_major, __VA_ARGS__ __VA_OPT__(,) 0, 0 \
		)
#
#	if defined(_ACK) || defined(__ACK__)
#		undef XTE_COMPILER_ACK
#		define XTE_COMPILER_ACK 1
#	endif
#
#	if defined(__ADSP21XX__) || defined(__ADSP218X__)
#		undef XTE_COMPILER_ADSP
#		define XTE_COMPILER_ADSP 1
#
#		ifdef __VISUALDSPVERSION__
#			undef XTE_COMPILER_ADSP_MAJOR
#			define XTE_COMPILER_ADSP_MAJOR (__VISUALDSPVERSION__ >> 24)
#
#			undef XTE_COMPILER_ADSP_MINOR
#			define XTE_COMPILER_ADSP_MINOR ((__VISUALDSPVERSION__ >> 16) & 0xFF)
#
#			undef XTE_COMPILER_ADSP_PATCH
#			define XTE_COMPILER_ADSP_PATCH ((__VISUALDSPVERSION__ >> 8) & 0xFF)
#		endif
#	endif
#
#	ifdef __AHCC__
#		undef XTE_COMPILER_AHCC
#		define XTE_COMPILER_AHCC 1
#	endif
#
#	ifdef __CHC__
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE 1
#
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MAJOR
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MAJOR (__VERSION___ / 1000)
#
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MINOR
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_MINOR (__VERSION___ % 1000)
#
#		undef XTE_COMPILER_ALTIUM_C_TO_HARDWARE_PATCH
#		define XTE_COMPILER_ALTIUM_C_TO_HARDWARE_PATCH __REVISION__
#	endif
#
#	ifdef __CMB__
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C 1
#
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C_MAJOR
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MAJOR (__VERSION___ / 1000)
#
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C_MINOR
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C_MINOR (__VERSION___ % 1000)
#
#		undef XTE_COMPILER_ALTIUM_MICROBLAZE_C_PATCH
#		define XTE_COMPILER_ALTIUM_MICROBLAZE_C_PATCH __REVISION__
#	endif
#
#	ifdef __aocc__
#		undef XTE_COMPILER_AOCC
#		define XTE_COMPILER_AOCC 1
#
#		ifdef __aocc_major__
#			undef XTE_COMPILER_AOCC_MAJOR
#			define XTE_COMPILER_AOCC_MAJOR __aocc_major__
#
#			undef XTE_COMPILER_AOCC_MAJOR
#			define XTE_COMPILER_AOCC_MAJOR __aocc_minor__
#
#			undef XTE_COMPILER_AOCC_MAJOR
#			define XTE_COMPILER_AOCC_MAJOR __aocc_patchlevel__
#		endif
#	endif
#
#	ifdef __CC_ARM
#		undef XTE_COMPILER_ARMCC
#		define XTE_COMPILER_ARMCC 1
#
#		undef XTE_COMPILER_ARMCC_MAJOR
#		undef XTE_COMPILER_ARMCC_MINOR
#		undef XTE_COMPILER_ARMCC_PATCH
#		ifdef __ARMCOMPILER_VERSION
#			define XTE_COMPILER_ARMCC_MAJOR (__ARMCOMPILER_VERSION / 100000)
#			define XTE_COMPILER_ARMCC_MINOR (__ARMCOMPILER_VERSION % 100000 / 10000)
#			define XTE_COMPILER_ARMCC_PATCH (__ARMCOMPILER_VERSION % 10000 / 1000)
#		else
#			define XTE_COMPILER_ARMCC_MAJOR (__ARMCC_VERSION / 100000)
#			define XTE_COMPILER_ARMCC_MINOR (__ARMCC_VERSION % 100000 / 10000)
#			define XTE_COMPILER_ARMCC_PATCH (__ARMCC_VERSION % 10000 / 1000)
#		endif
#	endif
#
#	ifdef AZTEC_C
#		undef XTE_COMPILER_AZTEC_C
#		define XTE_COMPILER_AZTEC_C 1
#
#		undef XTE_COMPILER_AZTEC_C_MAJOR
#		define XTE_COMPILER_AZTEC_C_MAJOR (__VERSION / 100)
#
#		undef XTE_COMPILER_AZTEC_C_MINOR
#		define XTE_COMPILER_AZTEC_C_MINOR (__VERSION % 100)
#	endif
#
#	ifdef __BCC__
#		undef XTE_COMPILER_BCC
#		define XTE_COMPILER_BCC 1
#	endif
#
#	if defined(__BORLANDC__) || defined(__CODEGEARC__)
#		undef XTE_COMPILER_BORLAND
#		define XTE_COMPILER_BORLAND 1
#	endif
#
#	ifdef __c2__
#		undef XTE_COMPILER_C2
#		define XTE_COMPILER_C2 1
#	endif
#
#	ifdef __castxml__
#		undef XTE_COMPILER_CASTXML
#		define XTE_COMPILER_CASTXML 1
#
#		undef XTE_COMPILER_CASTXML_MAJOR
#		define XTE_COMPILER_CASTXML_MAJOR __castxml_major__
#
#		undef XTE_COMPILER_CASTXML_MINOR
#		define XTE_COMPILER_CASTXML_MINOR __castxml_minor__
#
#		undef XTE_COMPILER_CASTXML_PATCH
#		define XTE_COMPILER_CASTXML_PATCH __castxml_patch__
#	endif
#
#	ifdef __CC65__
#		undef XTE_COMPILER_CC65
#		define XTE_COMPILER_CC65 1
#
#		undef XTE_COMPILER_CC65_MAJOR
#		define XTE_COMPILER_CC65_MAJOR (__CC65__ / 0x100)
#
#		undef XTE_COMPILER_CC65_MINOR
#		define XTE_COMPILER_CC65_MINOR (__CC65__ % 0x100)
#	endif
#
#	if defined(CIL) && defined(_GNUCC)
#		undef XTE_COMPILER_CILLY
#		define XTE_COMPILER_CILLY 1
#
#		ifdef __CILLY__
#			undef XTE_COMPILER_CILLY_MAJOR
#			define XTE_COMPILER_CILLY_MAJOR (__CILLY__ / 0x10000)
#
#			undef XTE_COMPILER_CILLY_MINOR
#			define XTE_COMPILER_CILLY_MINOR (__CILLY__ % 0x10000 / 0x100)
#
#			undef XTE_COMPILER_CILLY_PATCH
#			define XTE_COMPILER_CILLY_PATCH (__CILLY__ % 0x100)
#		endif
#	endif
#
#	if defined(__circle__) || defined(__circle_lang__) || defined(__circle_build__)
#		undef XTE_COMPILER_CIRCLE
#		define XTE_COMPILER_CIRCLE 1
#
#		undef XTE_COMPILER_CIRCLE_MAJOR
#		define XTE_COMPILER_CIRCLE_MAJOR (__circle__ / 10000)
#
#		undef XTE_COMPILER_CIRCLE_MINOR
#		define XTE_COMPILER_CIRCLE_MINOR (__circle__ % 10000 / 100)
#
#		undef XTE_COMPILER_CIRCLE_PATCH
#		define XTE_COMPILER_CIRCLE_PATCH (__circle__ % 100)
#	endif
#
#	if defined(__clang__)
#		undef XTE_COMPILER_CLANG
#		define XTE_COMPILER_CLANG 1
#
#		undef XTE_COMPILER_CLANG_MAJOR
#		define XTE_COMPILER_CLANG_MAJOR __clang_major___
#
#		undef XTE_COMPILER_CLANG_MINOR
#		define XTE_COMPILER_CLANG_MINOR __clang_minor___
#
#		undef XTE_COMPILER_CLANG_PATCH
#		define XTE_COMPILER_CLANG_PATCH __clang_patchlevel__
#	endif
#
#	ifdef __COMO__
#		undef XTE_COMPILER_COMEAU
#		define XTE_COMPILER_COMEAU 1
#
#		undef XTE_COMPILER_COMEAU_MAJOR
#		define XTE_COMPILER_COMEAU_MAJOR (__COMO_VERSION___ / 0x100)
#
#		undef XTE_COMPILER_COMEAU_MINOR
#		define XTE_COMPILER_COMEAU_MINOR (__COMO_VERSION___ % 0x100 / 0x10)
#
#		undef XTE_COMPILER_COMEAU_PATCH
#		define XTE_COMPILER_COMEAU_PATCH (__COMO_VERSION__ % 0x10)
#	endif
#
#	ifdef __DECC
#		undef XTE_COMPILER_COMPAQ_C
#		define XTE_COMPILER_COMPAQ_C 1
#
#		undef XTE_COMPILER_COMPAQ_C_MAJOR
#		define XTE_COMPILER_COMPAQ_C_MAJOR (__DECC_VER / 10000000)
#
#		undef XTE_COMPILER_COMPAQ_C_MINOR
#		define XTE_COMPILER_COMPAQ_C_MINOR (__DECC_VER % 10000000 / 100000)
#
#		undef XTE_COMPILER_COMPAQ_C_PATCH
#		define XTE_COMPILER_COMPAQ_C_PATCH (__DECC_VER % 10000)
#	endif
#
#	ifdef __DECCXX
#		undef XTE_COMPILER_COMPAQ_CPP
#		define XTE_COMPILER_COMPAQ_CPP 1
#
#		undef XTE_COMPILER_COMPAQ_CPP_MAJOR
#		define XTE_COMPILER_COMPAQ_CPP_MAJOR (__DECCXX_VER / 10000000)
#
#		undef XTE_COMPILER_COMPAQ_CPP_MINOR
#		define XTE_COMPILER_COMPAQ_CPP_MINOR (__DECCXX_VER % 10000000 / 100000)
#
#		undef XTE_COMPILER_COMPAQ_CPP_PATCH
#		define XTE_COMPILER_COMPAQ_CPP_PATCH (__DECCXX_VER % 10000)
#	endif
#
#	ifdef __COMPCERT__
#		undef XTE_COMPILER_COMPCERT
#		define XTE_COMPILER_COMPCERT 1
#	endif
#
#	ifdef __convexc__
#		undef XTE_COMPILER_CONVEX_C
#		define XTE_COMPILER_CONVEX_C 1
#	endif
#
#	ifdef __COVERITY__
#		undef XTE_COMPILER_COVERITY_STATIC_ANALYZER
#		define XTE_COMPILER_COVERITY_STATIC_ANALYZER 1
#	endif
#
#	ifdef _CRAYC
#		undef XTE_COMPILER_CRAY_C
#		define XTE_COMPILER_CRAY_C 1
#
#		undef XTE_COMPILER_CRAY_C_MAJOR
#		define XTE_COMPILER_CRAY_C_MAJOR _RELEASE
#
#		undef XTE_COMPILER_CRAY_C_MINOR
#		define XTE_COMPILER_CRAY_C_MINOR _RELEASE_MINOR
#	endif
#
#	ifdef _CRAYFTN
#		undef XTE_COMPILER_CRAY_F90
#		define XTE_COMPILER_CRAY_F90 1
#
#		undef XTE_COMPILER_CRAY_F90_MAJOR
#		define XTE_COMPILER_CRAY_F90_MAJOR _RELEASE_MAJOR
#
#		undef XTE_COMPILER_CRAY_F90_MINOR
#		define XTE_COMPILER_CRAY_F90_MINOR _RELEASE_MINOR
#
#		undef XTE_COMPILER_CRAY_F90_PATCH
#		define XTE_COMPILER_CRAY_F90_PATCH _RELEASE_PATCHLEVEL
#	endif
#
#	ifdef __DMC__
#		undef XTE_COMPILER_DIGITAL_MARS
#		define XTE_COMPILER_DIGITAL_MARS 1
#
#		undef XTE_COMPILER_DIGITAL_MARS_MAJOR
#		define XTE_COMPILER_DIGITAL_MARS_MAJOR (__DMC__ / 0x100)
#
#		undef XTE_COMPILER_DIGITAL_MARS_MINOR
#		define XTE_COMPILER_DIGITAL_MARS_MINOR (__DMC__ % 0x100 / 0x10)
#
#		undef XTE_COMPILER_DIGITAL_MARS_PATCH
#		define XTE_COMPILER_DIGITAL_MARS_PATCH (__DMC__ % 0x10)
#	endif
#
#	ifdef _DICE
#		undef XTE_COMPILER_DICE_C
#		define XTE_COMPILER_DICE_C 1
#	endif
#
#	ifdef __SYSC__
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP 1
#
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MAJOR
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MAJOR (__SYSC_VER__ / 10000)
#
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MINOR
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_MINOR (__SYSC_VER__ % 10000 / 100)
#
#		undef XTE_COMPILER_DIGNUS_SYSTEMS_CPP_PATCH
#		define XTE_COMPILER_DIGNUS_SYSTEMS_CPP_PATCH (__SYSC_VER__ % 100)
#	endif
#
#	if defined(DJGPP) || defined(__DJGPP) || defined(__DJGPP__)
#		undef XTE_COMPILER_DJGPP
#		define XTE_COMPILER_DJGPP 1
#
#		undef XTE_COMPILER_DJGPP_MAJOR
#		define XTE_COMPILER_DJGPP_MAJOR __DJGPP__
#
#		undef XTE_COMPILER_DJGPP_MINOR
#		define XTE_COMPILER_DJGPP_MINOR __DJGPP_MINOR__
#	endif
#
#	ifdef __EDG__
#		undef XTE_COMPILER_EDG
#		define XTE_COMPILER_EDG 1
#
#		undef XTE_COMPILER_EDG_MAJOR
#		define XTE_COMPILER_EDG_MAJOR (__EDG_VERSION___ / 100)
#
#		undef XTE_COMPILER_EDG_MINOR
#		define XTE_COMPILER_EDG_MINOR (__EDG_VERSION___ % 100)
#	endif
#
#	if defined(__PATHSCALE__) || defined(__PATHCC__)
#		undef XTE_COMPILER_EKOPATH
#		define XTE_COMPILER_EKOPATH 1
#
#		undef XTE_COMPILER_EKOPATH_MAJOR
#		define XTE_COMPILER_EKOPATH_MAJOR __PATHCC__
#
#		undef XTE_COMPILER_EKOPATH_MINOR
#		define XTE_COMPILER_EKOPATH_MINOR __PATHCC_MINOR__
#
#		undef XTE_COMPILER_EKOPATH_PATCH
#		define XTE_COMPILER_EKOPATH_PATCH __PATHCC_PATCHLEVEL__
#	endif
#
#	ifdef __ELLCC__
#		undef XTE_COMPILER_ELLCC
#		define XTE_COMPILER_ELLCC 1
#	endif
#
#	if defined(F2C) || defined(F2CFortran) || defined(f2cFortran)
#		undef XTE_COMPILER_F2C
#		define XTE_COMPILER_F2C 1
#	endif
#
#	if defined(__FLANG) || defined(__flang__)
#		undef XTE_COMPILER_FLANG
#		define XTE_COMPILER_FLANG 1
#
#		undef XTE_COMPILER_FLANG_MAJOR
#		undef XTE_COMPILER_FLANG_MINOR
#		undef XTE_COMPILER_FLANG_PATCH
#		ifdef __flang__
#			define XTE_COMPILER_FLANG_MAJOR __flang_major__
#			define XTE_COMPILER_FLANG_MINOR __flang_minor__
#			define XTE_COMPILER_FLANG_PATCH __flang_patchlevel__
#		else
#			define XTE_COMPILER_FLANG_MAJOR __FLANG_MAJOR__
#			define XTE_COMPILER_FLANG_MINOR __FLANG_MINOR__
#			define XTE_COMPILER_FLANG_PATCH __FLANG_PATCHLEVEL__
#		endif
#	endif
#
#	if defined(__CLANG_FUJITSU) \
		|| defined(__FCC__) \
		|| defined(__FCC_VERSION) \
		|| defined(__FCC_version__) \
		|| defined(__FUJITSU) \
		|| defined(__fcc__) \
		|| defined(__fcc_version)
#		undef XTE_COMPILER_FUJITSU_CPP
#		define XTE_COMPILER_FUJITSU_CPP 1
#
#		ifdef __FCC_major__
#			undef XTE_COMPILER_FUJITSU_CPP_MAJOR
#			define XTE_COMPILER_FUJITSU_CPP_MAJOR __FCC_major__
#
#			undef XTE_COMPILER_FUJITSU_CPP_MINOR
#			define XTE_COMPILER_FUJITSU_CPP_MINOR __FCC_minor__
#
#			undef XTE_COMPILER_FUJITSU_CPP_PATCH
#			define XTE_COMPILER_FUJITSU_CPP_PATCH __FCC_patchlevel__
#		endif
#	endif
#
#	if defined(__GNUC) || defined(__GNUC__) || defined(__gnuc)
#		undef XTE_COMPILER_GCC
#		define XTE_COMPILER_GCC 1
#
#		undef XTE_COMPILER_GCC_MAJOR
#		define XTE_COMPILER_GCC_MAJOR __GNUC__
#
#		undef XTE_COMPILER_GCC_MINOR
#		define XTE_COMPILER_GCC_MINOR __GNUC_MINOR__
#
#		undef XTE_COMPILER_GCC_PATCH
#		define XTE_COMPILER_GCC_PATCH __GNUC_PATCHLEVEL__
#	endif
#
#	ifdef __GCCXML__
#		undef XTE_COMPILER_GCCXML
#		define XTE_COMPILER_GCCXML 1
#	endif
#
#	ifdef __GFORTRAN__
#		undef XTE_COMPILER_GNU_F95
#		define XTE_COMPILER_GNU_F95 1
#
#		undef XTE_COMPILER_GNU_F95_MAJOR
#		define XTE_COMPILER_GNU_F95_MAJOR __GNUC__
#
#		undef XTE_COMPILER_GNU_F95_MINOR
#		define XTE_COMPILER_GNU_F95_MINOR __GNUC_MINOR__
#
#		undef XTE_COMPILER_GNU_F95_PATCH
#		define XTE_COMPILER_GNU_F95_PATCH __GNUC_PATCHLEVEL__
#	endif
#
#	if defined(__ghs) || defined(__ghs__)
#		undef XTE_COMPILER_GREEN_HILLS
#		define XTE_COMPILER_GREEN_HILLS 1
#
#		ifdef __ghs
#			undef XTE_COMPILER_GREEN_HILLS_MAJOR
#			define XTE_COMPILER_GREEN_HILLS_MAJOR (__ghs / 100)
#
#			undef XTE_COMPILER_GREEN_HILLS_MINOR
#			define XTE_COMPILER_GREEN_HILLS_MINOR (__ghs % 100 / 10)
#
#			undef XTE_COMPILER_GREEN_HILLS_PATCH
#			define XTE_COMPILER_GREEN_HILLS_PATCH (__ghs % 10)
#		elifdef __GHS_VERSION_NUMBER__
#			undef XTE_COMPILER_GREEN_HILLS_MAJOR
#			define XTE_COMPILER_GREEN_HILLS_MAJOR (__GHS_VERSION_NUMBER__ / 100)
#
#			undef XTE_COMPILER_GREEN_HILLS_MINOR
#			define XTE_COMPILER_GREEN_HILLS_MINOR (__GHS_VERSION_NUMBER__ % 100 / 10)
#
#			undef XTE_COMPILER_GREEN_HILLS_PATCH
#			define XTE_COMPILER_GREEN_HILLS_PATCH (__GHS_VERSION_NUMBER__ % 10)
#		elifdef __GHS_VERSION_NUMBER
#			undef XTE_COMPILER_GREEN_HILLS_MAJOR
#			define XTE_COMPILER_GREEN_HILLS_MAJOR (__GHS_VERSION_NUMBER / 100)
#
#			undef XTE_COMPILER_GREEN_HILLS_MINOR
#			define XTE_COMPILER_GREEN_HILLS_MINOR (__GHS_VERSION_NUMBER % 100 / 10)
#
#			undef XTE_COMPILER_GREEN_HILLS_PATCH
#			define XTE_COMPILER_GREEN_HILLS_PATCH (__GHS_VERSION_NUMBER % 10)
#		endif
#	endif
#
#	ifdef __hexagon__
#		undef XTE_COMPILER_HEXAGON
#		define XTE_COMPILER_HEXAGON 1
#
#		undef XTE_COMPILER_HEXAGON_MAJOR
#		ifdef __HEXAGON_V73__
#			define XTE_COMPILER_HEXAGON_MAJOR 73
#		elifdef __HEXAGON_V71__
#			define XTE_COMPILER_HEXAGON_MAJOR 71
#		elifdef __HEXAGON_V70__
#			define XTE_COMPILER_HEXAGON_MAJOR 70
#		elifdef __HEXAGON_V69__
#			define XTE_COMPILER_HEXAGON_MAJOR 69
#		elifdef __HEXAGON_V68__
#			define XTE_COMPILER_HEXAGON_MAJOR 68
#		elifdef __HEXAGON_V67__
#			define XTE_COMPILER_HEXAGON_MAJOR 67
#		elifdef __HEXAGON_V66__
#			define XTE_COMPILER_HEXAGON_MAJOR 66
#		elifdef __HEXAGON_V65__
#			define XTE_COMPILER_HEXAGON_MAJOR 65
#		else
#			define XTE_COMPILER_HEXAGON_MAJOR 0
#		endif
#	endif
#
#	if defined(__HCC__) \
		|| defined(__HIPCC_PLATFORM_HCC) \
		|| defined(__HIP__) \
		|| defined(__HIPCC__)
#		undef XTE_COMPILER_HIPCC
#		define XTE_COMPILER_HIPCC 1
#	endif
#
#	ifdef __HP_cc
#		undef XTE_COMPILER_HPUX_C
#		define XTE_COMPILER_HPUX_C 1
#	endif
#
#	if defined(_ACC_) || defined(__HP_aCC)
#		undef XTE_COMPILER_HPUX_CPP
#		define XTE_COMPILER_HPUX_CPP 1
#
#		ifdef __HP_aCC
#			undef XTE_COMPILER_HPUX_CPP_MAJOR
#			define XTE_COMPILER_HPUX_CPP_MAJOR (__HP_aCC / 10000)
#
#			undef XTE_COMPILER_HPUX_CPP_MINOR
#			define XTE_COMPILER_HPUX_CPP_MINOR (__HP_aCC % 10000 / 100)
#
#			undef XTE_COMPILER_HPUX_CPP_PATCH
#			define XTE_COMPILER_HPUX_CPP_PATCH (__HP_aCC % 100)
#		endif
#	endif
#
#	ifdef __HSC__
#		undef XTE_COMPILER_HSC
#		define XTE_COMPILER_HSC 1
#	endif
#
#	if defined(__IAR_SYSTEMS_ICC) || defined(__IAR_SYSTEMS_ICC__)
#		undef XTE_COMPILER_IAR
#		define XTE_COMPILER_IAR 1
#
#		undef XTE_COMPILER_IAR_MAJOR
#		undef XTE_COMPILER_IAR_MINOR
#		undef XTE_COMPILER_IAR_PATCH
#		ifdef __SUBVERSION__
#			define XTE_COMPILER_IAR_MAJOR (__VER__ / 100)
#			define XTE_COMPILER_IAR_MINOR (__VER__ % 100)
#			define XTE_COMPILER_IAR_PATCH __SUBVERSION__
#		else
#			define XTE_COMPILER_IAR_MAJOR (__VER__ / 1000000)
#			define XTE_COMPILER_IAR_MINOR (__VER__ % 1000000 / 1000)
#			define XTE_COMPILER_IAR_PATCH (__VER__ % 1000)
#		endif
#	endif
#
#	if defined(__ECC) \
		|| defined(__ECC__) \
		|| defined(__ICC) \
		|| defined(__ICL) \
		|| defined(__INTEL_COMPILER)
#		undef XTE_COMPILER_ICC
#		define XTE_COMPILER_ICC 1
#
#		ifdef __INTEL_COMPILER
#			undef XTE_COMPILER_ICC_MAJOR
#			undef XTE_COMPILER_ICC_MINOR
#			undef XTE_COMPILER_ICC_PATCH
#			if __INTEL_COMPILER == 9999
#				define XTE_COMPILER_ICC_MAJOR 12
#				define XTE_COMPILER_ICC_MINOR 1
#			else
#				define XTE_COMPILER_ICC_MAJOR (__INTEL_COMPILER / 100)
#				define XTE_COMPILER_ICC_MINOR (__INTEL_COMPILER % 100 / 10)
#				ifdef __INTEL_COMPILER_UPDATE
#					define XTE_COMPILER_ICC_PATCH __INTEL_COMPILER_UPDATE
#				else
#					define XTE_COMPILER_ICC_PATCH (__INTEL_COMPILER % 10)
#				endif
#			endif
#		endif
#	endif
#
#	if defined(__INTEL_CLANG_COMPILER) || defined(__INTEL_LLVM_COMPILER)
#		undef XTE_COMPILER_ICX
#		define XTE_COMPILER_ICX 1
#
#		undef XTE_COMPILER_ICX_MAJOR
#		define XTE_COMPILER_ICX_MAJOR (__INTEL_CLANG_COMPILER / 100)
#
#		undef XTE_COMPILER_ICX_MINOR
#		define XTE_COMPILER_ICX_MINOR (__INTEL_CLANG_COMPILER % 100 / 10)
#
#		undef XTE_COMPILER_ICX_PATCH
#		define XTE_COMPILER_ICX_PATCH (__INTEL_CLANG_COMPILER % 10)
#	endif
#
#	ifdef __IMAGECRAFT__
#		undef XTE_COMPILER_IMAGECRAFT_C
#		define XTE_COMPILER_IMAGECRAFT_C 1
#	endif
#
#	if defined(__COMPILER_KCC__) || defined(__KCC_)
#		undef XTE_COMPILER_KCC
#		define XTE_COMPILER_KCC 1
#
#		undef XTE_COMPILER_KCC_MAJOR
#		define XTE_COMPILER_KCC_MAJOR (__KCC_VERSION / 0x1000)
#
#		undef XTE_COMPILER_KCC_MINOR
#		define XTE_COMPILER_KCC_MINOR (__KCC_VERSION % 0x1000 / 0x100)
#
#		undef XTE_COMPILER_KCC_PATCH
#		define XTE_COMPILER_KCC_PATCH (__KCC_VERSION % 0x100)
#	endif
#
#	ifdef __C166__
#		undef XTE_COMPILER_KEIL_C166
#		define XTE_COMPILER_KEIL_C166 1
#
#		undef XTE_COMPILER_KEIL_C166_MAJOR
#		define XTE_COMPILER_KEIL_C166_MAJOR (__C166__ / 100)
#
#		undef XTE_COMPILER_KEIL_C166_MINOR
#		define XTE_COMPILER_KEIL_C166_MINOR (__C166__ % 100)
#	endif
#
#	ifdef __C51__
#		undef XTE_COMPILER_KEIL_C51
#		define XTE_COMPILER_KEIL_C51 1
#
#		undef XTE_COMPILER_KEIL_C51_MAJOR
#		define XTE_COMPILER_KEIL_C51_MAJOR (__C51__ / 100)
#
#		undef XTE_COMPILER_KEIL_C51_MINOR
#		define XTE_COMPILER_KEIL_C51_MINOR (__C51__ % 100)
#	endif
#
#	if defined(__CA__) || defined(__KEIL__)
#		undef XTE_COMPILER_KEIL_CARM
#		define XTE_COMPILER_KEIL_CARM 1
#
#		undef XTE_COMPILER_KEIL_CARM_MAJOR
#		define XTE_COMPILER_KEIL_CARM_MAJOR (__CA__ / 100)
#
#		undef XTE_COMPILER_KEIL_CARM_MINOR
#		define XTE_COMPILER_KEIL_CARM_MINOR (__CA__ % 100)
#	endif
#
#	ifdef __KICKC__
#		undef XTE_COMPILER_KICKC
#		define XTE_COMPILER_KICKC 1
#	endif
#
#	if defined(SASC) || defined(__SASC) || defined(__SASC__)
#		undef XTE_COMPILER_LATTICE_C
#		define XTE_COMPILER_LATTICE_C 1
#
#		undef XTE_COMPILER_LATTICE_C_MAJOR
#		define XTE_COMPILER_LATTICE_C_MAJOR (__SASC__ / 100)
#
#		undef XTE_COMPILER_LATTICE_C_MINOR
#		define XTE_COMPILER_LATTICE_C_MINOR (__SASC__ % 100)
#	endif
#
#	ifdef __LCC__
#		undef XTE_COMPILER_LCC
#		define XTE_COMPILER_LCC 1
#
#		undef XTE_COMPILER_LCC_MAJOR
#		define XTE_COMPILER_LCC_MAJOR __LCC__
#
#		undef XTE_COMPILER_LCC_MINOR
#		define XTE_COMPILER_LCC_MINOR __LCC_MINOR__
#	endif
#
#	if defined(THINKC3) || defined(THINKC4)
#		undef XTE_COMPILER_LIGHTSPEED_C
#		define XTE_COMPILER_LIGHTSPEED_C 1
#	endif
#
#	ifdef __llvm__
#		undef XTE_COMPILER_LLVM
#		define XTE_COMPILER_LLVM 1
#	endif
#
#	if defined(__LLC__) || defined(__MCST__)
#		undef XTE_COMPILER_MCST_LLC
#		define XTE_COMPILER_MCST_LLC 1
#
#		undef XTE_COMPILER_MCST_LLC_MAJOR
#		define XTE_COMPILER_MCST_LLC_MAJOR __LLC__
#
#		undef XTE_COMPILER_MCST_LLC_MINOR
#		define XTE_COMPILER_MCST_LLC_MINOR __LLC_MINOR__
#	endif
#
#	ifdef __HIGHC__
#		undef XTE_COMPILER_METAWARE_HIGH
#		define XTE_COMPILER_METAWARE_HIGH 1
#	endif
#
#	if defined(__CWCC__) || defined(__MWBROWSER__) || defined(__MWERKS__)
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR
#		define XTE_COMPILER_METROWERKS_CODEWARRIOR 1
#
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR
#		undef XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH
#		ifdef __CWCC__
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR (__CWCC__ / 0x1000)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR (__CWCC__ % 0x1000 / 0x100)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH (__CWCC__ % 0x100)
#		else
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MAJOR (__MWERKS__ / 0x1000)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_MINOR (__MWERKS__ % 0x1000 / 0x100)
#			define XTE_COMPILER_METROWERKS_CODEWARRIOR_PATCH (__MWERKS__ % 0x100)
#		endif
#	endif
#
#	ifdef _MRI
#		undef XTE_COMPILER_MICROTEC
#		define XTE_COMPILER_MICROTEC 1
#	endif
#
#	if defined(__NDPC__) || defined(__NDPX__)
#		undef XTE_COMPILER_MICROWAY_NDP_C
#		define XTE_COMPILER_MICROWAY_NDP_C 1
#	endif
#
#	ifdef __MINGW32__
#		include <windows.h>
#
#		undef XTE_COMPILER_MINGW32
#		define XTE_COMPILER_MINGW32 1
#
#		undef XTE_COMPILER_MINGW32_MAJOR
#		define XTE_COMPILER_MINGW32_MAJOR __MINGW32_MAJOR_VERSION
#
#		undef XTE_COMPILER_MINGW32_MINOR
#		define XTE_COMPILER_MINGW32_MINOR __MINGW32_MINOR_VERSION
#	endif
#
#	ifdef __MINGW64__
#		include <windows.h>
#
#		undef XTE_COMPILER_MINGW_W64
#		define XTE_COMPILER_MINGW_W64 1
#
#		undef XTE_COMPILER_MINGW_W64_MAJOR
#		define XTE_COMPILER_MINGW_W64_MAJOR __MINGW64_VERSION_MAJOR
#
#		undef XTE_COMPILER_MINGW_W64_MINOR
#		define XTE_COMPILER_MINGW_W64_MINOR __MINGW64_VERSION_MINOR
#	endif
#
#	if defined(mipsFortran) || defined(sgi) || defined(__sgi)
#		undef XTE_COMPILER_MIPSPRO
#		define XTE_COMPILER_MIPSPRO 1
#
#		ifdef _SGI_COMPILER_VERSION
#			undef XTE_COMPILER_MIPSPRO_MAJOR
#			define XTE_COMPILER_MIPSPRO_MAJOR (_SGI_COMPILER_VERSION / 100)
#
#			undef XTE_COMPILER_MIPSPRO_MINOR
#			define XTE_COMPILER_MIPSPRO_MINOR (_SGI_COMPILER_VERSION % 100 / 10)
#
#			undef XTE_COMPILER_MIPSPRO_PATCH
#			define XTE_COMPILER_MIPSPRO_PATCH (_SGI_COMPILER_VERSION % 10)
#		elifdef _COMPILER_VERSION
#			undef XTE_COMPILER_MIPSPRO_MAJOR
#			define XTE_COMPILER_MIPSPRO_MAJOR (_COMPILER_VERSION / 100)
#
#			undef XTE_COMPILER_MIPSPRO_MINOR
#			define XTE_COMPILER_MIPSPRO_MINOR (_COMPILER_VERSION % 100 / 10)
#
#			undef XTE_COMPILER_MIPSPRO_PATCH
#			define XTE_COMPILER_MIPSPRO_PATCH (_COMPILER_VERSION % 10)
#		endif
#	endif
#
#	ifdef MIRACLE
#		undef XTE_COMPILER_MIRACLE_C
#		define XTE_COMPILER_MIRACLE_C 1
#	endif
#
#	if defined(MPW_C) || defined(MPW_CPLUS) || defined(__MRC__)
#		undef XTE_COMPILER_MPW
#		define XTE_COMPILER_MPW 1
#
#		undef XTE_COMPILER_MPW_MAJOR
#		define XTE_COMPILER_MPW_MAJOR (__MRC__ / 0x100)
#
#		undef XTE_COMPILER_MPW_MINOR
#		define XTE_COMPILER_MPW_MINOR (__MRC__ % 0x100)
#	endif
#
#	ifdef _MSC_VER
#		undef XTE_COMPILER_MSVC
#		define XTE_COMPILER_MSVC 1
#
#		undef XTE_COMPILER_MSVC_MAJOR
#		undef XTE_COMPILER_MSVC_MINOR
#		undef XTE_COMPILER_MSVC_PATCH
#		ifdef _MSC_FULL_VER
#			define XTE_COMPILER_MSVC_MAJOR (_MSC_FULL_VER / 10000000)
#			define XTE_COMPILER_MSVC_MINOR (_MSC_FULL_VER % 10000000 / 100000)
#			define XTE_COMPILER_MSVC_PATCH (_MSC_FULL_VER % 100000)
#		else
#			define XTE_COMPILER_MSVC_MAJOR (_MSC_VER / 100)
#			define XTE_COMPILER_MSVC_MINOR (_MSC_VER % 100)
#			define XTE_COMPILER_MSVC_PATCH 0
#		endif
#	endif
#
#	ifdef __NCC__
#		undef XTE_COMPILER_NCC
#		define XTE_COMPILER_NCC 1
#
#		undef XTE_COMPILER_NCC_MAJOR
#		define XTE_COMPILER_NCC_MAJOR __NCC_MAJOR__
#
#		undef XTE_COMPILER_NCC_MINOR
#		define XTE_COMPILER_NCC_MINOR __NCC_MINOR__
#	endif
#
#	ifdef __CC_NORCROFT
#		undef XTE_COMPILER_NORCROFT_C
#		define XTE_COMPILER_NORCROFT_C 1
#	endif
#
#	ifdef __NVCOMPILER
#		undef XTE_COMPILER_NVIDIA_HPC
#		define XTE_COMPILER_NVIDIA_HPC 1
#
#		undef XTE_COMPILER_NVIDIA_HPC_MAJOR
#		define XTE_COMPILER_NVIDIA_HPC_MAJOR __NVCOMPILER_MAJOR__
#
#		undef XTE_COMPILER_NVIDIA_HPC_MINOR
#		define XTE_COMPILER_NVIDIA_HPC_MINOR __NVCOMPILER_MINOR__
#
#		undef XTE_COMPILER_NVIDIA_HPC_PATCH
#		define XTE_COMPILER_NVIDIA_HPC_PATCH __NVCOMPILER_PATCHLEVEL__
#	endif
#
#	if defined(HIPCC_PLATFORM_NVCC) || defined(__CUDACC__) || defined(__NVCC__)
#		undef XTE_COMPILER_NVCC
#		define XTE_COMPILER_NVCC 1
#
#		undef XTE_COMPILER_NVCC_MAJOR
#		define XTE_COMPILER_NVCC_MAJOR __CUDACC_VER_MAJOR__
#
#		undef XTE_COMPILER_NVCC_MINOR
#		define XTE_COMPILER_NVCC_MINOR __CUDACC_VER_MINOR__
#
#		undef XTE_COMPILER_NVCC_PATCH
#		define XTE_COMPILER_NVCC_PATCH __CUDACC_VER_BUILD__
#	endif
#
#	ifdef __NWCC__
#		undef XTE_COMPILER_NWCC
#		define XTE_COMPILER_NWCC 1
#	endif
#
#	ifdef __OCC__
#		undef XTE_COMPILER_OCC
#		define XTE_COMPILER_OCC 1
#	endif
#
#	if defined(__OPEN64__) || defined(__OPENCC__)
#		undef XTE_COMPILER_OPEN64
#		define XTE_COMPILER_OPEN64 1
#
#		undef XTE_COMPILER_OPEN64_MAJOR
#		define XTE_COMPILER_OPEN64_MAJOR __OPENCC__
#
#		undef XTE_COMPILER_OPEN64_MINOR
#		define XTE_COMPILER_OPEN64_MINOR __OPENCC_MINOR__
#
#		undef XTE_COMPILER_OPEN64_PATCH
#		define XTE_COMPILER_OPEN64_PATCH __OPENCC_PATCHLEVEL__
#	endif
#
#	ifdef _OPENACC
#		undef XTE_COMPILER_OPENACC
#		define XTE_COMPILER_OPENACC 1
#	endif
#
#	ifdef _SCO_DS
#		undef XTE_COMPILER_OPENSERVER
#		define XTE_COMPILER_OPENSERVER 1
#	endif
#
#	ifdef __ORANGEC__
#		undef XTE_COMPILER_ORANGE_C
#		define XTE_COMPILER_ORANGE_C 1
#
#		undef XTE_COMPILER_ORANGE_C_MAJOR
#		define XTE_COMPILER_ORANGE_C_MAJOR __ORANGEC_MAJOR__
#
#		undef XTE_COMPILER_ORANGE_C_MINOR
#		define XTE_COMPILER_ORANGE_C_MINOR __ORANGEC_MINOR__
#
#		undef XTE_COMPILER_ORANGE_C_PATCH
#		define XTE_COMPILER_ORANGE_C_PATCH __ORANGEC_PATCHLEVEL__
#	endif
#
#	ifdef __PACIFIC__
#		undef XTE_COMPILER_PACIFIC_C
#		define XTE_COMPILER_PACIFIC_C 1
#	endif
#
#	ifdef _PACC_VER
#		undef XTE_COMPILER_PALM
#		define XTE_COMPILER_PALM 1
#
#		undef XTE_COMPILER_PALM_MAJOR
#		define XTE_COMPILER_PALM_MAJOR (_PACC_VER / 0x10000000)
#
#		undef XTE_COMPILER_PALM_MINOR
#		define XTE_COMPILER_PALM_MINOR (_PACC_VER % 0x10000000 / 0x100000)
#
#		undef XTE_COMPILER_PALM_PATCH
#		define XTE_COMPILER_PALM_PATCH (_PACC_VER % 0x100000 / 0x1000)
#	endif
#
#	ifdef __PCC__
#		undef XTE_COMPILER_PCC
#		define XTE_COMPILER_PCC 1
#
#		undef XTE_COMPILER_PCC_MAJOR
#		define XTE_COMPILER_PCC_MAJOR __PCC__
#
#		undef XTE_COMPILER_PCC_MINOR
#		define XTE_COMPILER_PCC_MINOR __PCC_MINOR__
#
#		undef XTE_COMPILER_PCC_PATCH
#		define XTE_COMPILER_PCC_PATCH __PCC_MINORMINOR__
#	endif
#
#	ifdef __POCC__
#		undef XTE_COMPILER_PELLES_C
#		define XTE_COMPILER_PELLES_C 1
#
#		undef XTE_COMPILER_PELLES_C_MAJOR
#		define XTE_COMPILER_PELLES_C_MAJOR (__POCC__ / 100)
#
#		undef XTE_COMPILER_PELLES_C_MINOR
#		define XTE_COMPILER_PELLES_C_MINOR (__POCC__ % 100)
#	endif
#
#	ifdef __PGI
#		undef XTE_COMPILER_PGI
#		define XTE_COMPILER_PGI 1
#
#		undef XTE_COMPILER_PGI_MAJOR
#		define XTE_COMPILER_PGI_MAJOR __PGIC__
#
#		undef XTE_COMPILER_PGI_MINOR
#		define XTE_COMPILER_PGI_MINOR __PGIC_MINOR__
#
#		undef XTE_COMPILER_PGI_PATCH
#		define XTE_COMPILER_PGI_PATCH __PGIC_PATCHLEVEL__
#	endif
#
#	ifdef __PUREC__
#		undef XTE_COMPILER_PUREC
#		define XTE_COMPILER_PUREC 1
#	endif
#
#	ifdef ORA_PROC
#		undef XTE_COMPILER_PRO_C
#		define XTE_COMPILER_PRO_C 1
#	endif
#
#	ifdef __PW32__
#		undef XTE_COMPILER_PW32
#		define XTE_COMPILER_PW32 1
#	endif
#
#	ifdef _QC
#		undef XTE_COMPILER_QUICKC
#		define XTE_COMPILER_QUICKC 1
#	endif
#
#	if defined(__HITACHI__) || defined(__RENESAS__)
#		undef XTE_COMPILER_RENESAS
#		define XTE_COMPILER_RENESAS 1
#
#		undef XTE_COMPILER_RENESAS_MAJOR
#		define XTE_COMPILER_RENESAS_MAJOR (__RENESAS_VERSION___ / 0x1000000)
#
#		undef XTE_COMPILER_RENESAS_MINOR
#		define XTE_COMPILER_RENESAS_MINOR (__RENESAS_VERSION___ % 0x1000000 / 0x10000)
#
#		undef XTE_COMPILER_RENESAS_PATCH
#		define XTE_COMPILER_RENESAS_PATCH (__RENESAS_VERSION___ % 0x10000 / 0x100)
#	endif
#
#	if defined(SDCC) || defined(__SDCC)
#		undef XTE_COMPILER_SDCC
#		define XTE_COMPILER_SDCC 1
#
#		undef XTE_COMPILER_SDCC_MAJOR
#		undef XTE_COMPILER_SDCC_MINOR
#		undef XTE_COMPILER_SDCC_PATCH
#		ifdef SDCC
#			define XTE_COMPILER_SDCC_MAJOR (SDCC / 100)
#			define XTE_COMPILER_SDCC_MINOR (SDCC % 100 / 10)
#			define XTE_COMPILER_SDCC_PATCH (SDCC % 10)
#		elifdef __SDCC
#			define XTE_COMPILER_SDCC_MAJOR (__SDCC / 100)
#			define XTE_COMPILER_SDCC_MINOR (__SDCC % 100 / 10)
#			define XTE_COMPILER_SDCC_PATCH (__SDCC % 10)
#		else
#			define XTE_COMPILER_SDCC_MAJOR __SDCC_VERSION_MAJOR
#			define XTE_COMPILER_SDCC_MINOR __SDCC_VERSION_MINOR
#			define XTE_COMPILER_SDCC_MINOR __SDCC_VERSION_PATCH
#		endif
#	endif
#
#	if defined(_ADI_COMPILER) || defined(__ADSP21000__)
#		undef XTE_COMPILER_SHARC
#		define XTE_COMPILER_SHARC 1
#
#		undef XTE_COMPILER_VISUALDSP_MAJOR
#		define XTE_COMPILER_VISUALDSP_MAJOR (__VERSIONNUM__ >> 24)
#
#		undef XTE_COMPILER_VISUALDSP_MINOR
#		define XTE_COMPILER_VISUALDSP_MINOR ((__VERSIONNUM__ >> 16) & 0xFF)
#
#		undef XTE_COMPILER_VISUALDSP_PATCH
#		define XTE_COMPILER_VISUALDSP_PATCH ((__VERSIONNUM__ >> 8) & 0xFF)
#	endif
#
#	ifdef __SNC__
#		undef XTE_COMPILER_SNC
#		define XTE_COMPILER_SNC 1
#	endif
#
#	ifdef __SOZOBON__
#		undef XTE_COMPILER_SOZOBON
#		define XTE_COMPILER_SOZOBON 1
#	endif
#
#	ifdef __VOSC__
#		undef XTE_COMPILER_STRATUS_VOS_C
#		define XTE_COMPILER_STRATUS_VOS_C 1
#	endif
#
#	ifdef __SUNPRO_C
#		undef XTE_COMPILER_SUNPRO_C
#		define XTE_COMPILER_SUNPRO_C 1
#
#		undef XTE_COMPILER_SUNPRO_C_MAJOR
#		define XTE_COMPILER_SUNPRO_C_MAJOR (__SUNPRO_C / 0x1000)
#
#		undef XTE_COMPILER_SUNPRO_C_MINOR
#		define XTE_COMPILER_SUNPRO_C_MINOR (__SUNPRO_C % 0x1000 / 0x10)
#
#		undef XTE_COMPILER_SUNPRO_C_PATCH
#		define XTE_COMPILER_SUNPRO_C_PATCH (__SUNPRO_C % 0x10)
#	endif
#
#	ifdef __SUNPRO_CC
#		undef XTE_COMPILER_SUNPRO_CPP
#		define XTE_COMPILER_SUNPRO_CPP 1
#
#		undef XTE_COMPILER_SUNPRO_CPP_MAJOR
#		define XTE_COMPILER_SUNPRO_CPP_MAJOR (__SUNPRO_CC / 0x1000)
#
#		undef XTE_COMPILER_SUNPRO_CPP_MINOR
#		define XTE_COMPILER_SUNPRO_CPP_MINOR (__SUNPRO_CC % 0x1000 / 0x10)
#
#		undef XTE_COMPILER_SUNPRO_CPP_PATCH
#		define XTE_COMPILER_SUNPRO_CPP_PATCH (__SUNPRO_CC % 0x10)
#	endif
#
#	if defined(__SUNPRO_F77) || defined(sunFortran)
#		undef XTE_COMPILER_SUNPRO_F77
#		define XTE_COMPILER_SUNPRO_F77 1
#
#		ifdef __SUNPRO_F77
#			undef XTE_COMPILER_SUNPRO_F77_MAJOR
#			define XTE_COMPILER_SUNPRO_F77_MAJOR (__SUNPRO_F77 / 0xF)
#
#			undef XTE_COMPILER_SUNPRO_F77_MINOR
#			define XTE_COMPILER_SUNPRO_F77_MINOR (__SUNPRO_F77 % 0xF)
#		endif
#	endif
#
#	ifdef __SC__
#		undef XTE_COMPILER_SYMANTEC_CPP
#		define XTE_COMPILER_SYMANTEC_CPP 1
#
#		undef XTE_COMPILER_SYMANTEC_CPP_MAJOR
#		define XTE_COMPILER_SYMANTEC_CPP_MAJOR (__SC__ / 0x100)
#
#		undef XTE_COMPILER_SYMANTEC_CPP_MINOR
#		define XTE_COMPILER_SYMANTEC_CPP_MINOR (__SC__ % 0x100)
#	endif
#
#	ifdef __TINYC__
#		undef XTE_COMPILER_TCC
#		define XTE_COMPILER_TCC 1
#	endif
#
#	ifdef __TenDRA__
#		undef XTE_COMPILER_TENDRA
#		define XTE_COMPILER_TENDRA 1
#	endif
#
#	ifdef _TMS320C6X
#		undef XTE_COMPILER_TI_CGT
#		define XTE_COMPILER_TI_CGT 1
#
#		undef XTE_COMPILER_TI_CGT_MAJOR
#		define XTE_COMPILER_TI_CGT_MAJOR (__TI_COMPILER_VERSION___ / 1000000)
#
#		undef XTE_COMPILER_TI_CGT_MINOR
#		define XTE_COMPILER_TI_CGT_MINOR (__TI_COMPILER_VERSION___ % 1000000 / 1000)
#
#		undef XTE_COMPILER_TI_CGT_PATCH
#		define XTE_COMPILER_TI_CGT_PATCH (__TI_COMPILER_VERSION___ % 1000)
#	endif
#
#	ifdef __MSP430__
#		undef XTE_COMPILER_TI_CL430
#		define XTE_COMPILER_TI_CL430 1
#
#		undef XTE_COMPILER_TI_CL430_MAJOR
#		define XTE_COMPILER_TI_CL430_MAJOR (__TI_COMPILER_VERSION___ / 1000000)
#
#		undef XTE_COMPILER_TI_CL430_MINOR
#		define XTE_COMPILER_TI_CL430_MINOR (__TI_COMPILER_VERSION___ % 1000000 / 1000)
#
#		undef XTE_COMPILER_TI_CL430_PATCH
#		define XTE_COMPILER_TI_CL430_PATCH (__TI_COMPILER_VERSION___ % 1000)
#	endif
#
#	ifdef __TSC__
#		undef XTE_COMPILER_TOPSPEED_C
#		define XTE_COMPILER_TOPSPEED_C 1
#	endif
#
#	ifdef __TURBOC__
#		undef XTE_COMPILER_TURBO
#		define XTE_COMPILER_TURBO 1
#
#		undef XTE_COMPILER_TURBO_MAJOR
#		define XTE_COMPILER_TURBO_MAJOR (__TURBOC__ / 0x100)
#
#		undef XTE_COMPILER_TURBO_MINOR
#		define XTE_COMPILER_TURBO_MINOR (__TURBOC__ % 0x100)
#	endif
#
#	ifdef _UCC
#		undef XTE_COMPILER_ULTIMATE
#		define XTE_COMPILER_ULTIMATE 1
#
#		undef XTE_COMPILER_ULTIMATE_MAJOR
#		define XTE_COMPILER_ULTIMATE_MAJOR _MAJOR_REV
#
#		undef XTE_COMPILER_ULTIMATE_MINOR
#		define XTE_COMPILER_ULTIMATE_MINOR _MINOR_REV
#	endif
#
#	ifdef __USLC__
#		undef XTE_COMPILER_USL_C
#		define XTE_COMPILER_USL_C 1
#
#		undef XTE_COMPILER_USL_C_MAJOR
#		define XTE_COMPILER_USL_C_MAJOR (__SCO_VERSION___ / 100000000)
#
#		undef XTE_COMPILER_USL_C_MINOR
#		define XTE_COMPILER_USL_C_MINOR (__SCO_VERSION___ % 100000000 / 1000000)
#	endif
#
#	ifdef __VBCC__
#		undef XTE_COMPILER_VBCC
#		define XTE_COMPILER_VBCC 1
#	endif
#
#	ifdef __VCM__
#		undef XTE_COMPILER_VCM
#		define XTE_COMPILER_VCM 1
#	endif
#
#	ifdef __WATCOMC__
#		undef XTE_COMPILER_WATCOM
#		define XTE_COMPILER_WATCOM 1
#
#		undef XTE_COMPILER_WATCOM_MAJOR
#		define XTE_COMPILER_WATCOM_MAJOR (__WATCOMC__ / 100)
#
#		undef XTE_COMPILER_WATCOM_MINOR
#		define XTE_COMPILER_WATCOM_MINOR (__WATCOMC__ % 100)
#	endif
#
#	ifdef __XC8
#		undef XTE_COMPILER_XC8
#		define XTE_COMPILER_XC8 1
#
#		ifdef __XC8_VERSION
#			undef XTE_COMPILER_XC8_MAJOR
#			define XTE_COMPILER_XC8_MAJOR (__XC8_VERSION / 1000)
#
#			undef XTE_COMPILER_XC8_MINOR
#			define XTE_COMPILER_XC8_MINOR (__XC8_VERSION % 1000 / 10)
#
#			undef XTE_COMPILER_XC8_MAJOR
#			define XTE_COMPILER_XC8_MAJOR (__XC8_VERSION % 10)
#		endif
#	endif
#
#	if defined(C30) \
		|| defined(XC16) \
		|| defined(__C30) \
		|| defined(__C30__) \
		|| defined(__XC16) \
		|| defined(__XC16__) \
		|| defined(dsPICC30) \
		|| defined(__dsPICC30__) \
		|| defined(__dsPICC30) \
		|| defined(dsPIC30)
#		undef XTE_COMPILER_XC16
#		define XTE_COMPILER_XC16 1
#
#		ifdef __XC32_VERSION
#			undef XTE_COMPILER_XC32_MAJOR
#			define XTE_COMPILER_XC32_MAJOR (__XC32_VERSION / 1000)
#
#			undef XTE_COMPILER_XC32_MINOR
#			define XTE_COMPILER_XC32_MINOR (__XC32_VERSION % 1000 / 10)
#
#			undef XTE_COMPILER_XC32_MAJOR
#			define XTE_COMPILER_XC32_MAJOR (__XC32_VERSION % 10)
#		elifdef __C32_VERSION__
#			undef XTE_COMPILER_XC32_PATCH
#			define XTE_COMPILER_XC32_PATCH (__C32_VERSION__ / 1000)
#
#			undef XTE_COMPILER_XC32_MINOR
#			define XTE_COMPILER_XC32_MINOR (__C32_VERSION__ % 1000 / 10)
#
#			undef XTE_COMPILER_XC32_PATCH
#			define XTE_COMPILER_XC32_PATCH (__C32_VERSION__ % 10)
#		endif
#	endif
#
#	ifdef __XC32
#		undef XTE_COMPILER_XC32
#		define XTE_COMPILER_XC32 1
#
#		ifdef __XC32_VERSION
#			undef XTE_COMPILER_XC32_MAJOR
#			define XTE_COMPILER_XC32_MAJOR (__XC32_VERSION / 1000)
#
#			undef XTE_COMPILER_XC32_MINOR
#			define XTE_COMPILER_XC32_MINOR (__XC32_VERSION % 1000 / 10)
#
#			undef XTE_COMPILER_XC32_MAJOR
#			define XTE_COMPILER_XC32_MAJOR (__XC32_VERSION % 10)
#		elifdef __C32_VERSION__
#			undef XTE_COMPILER_XC32_PATCH
#			define XTE_COMPILER_XC32_PATCH (__C32_VERSION__ / 1000)
#
#			undef XTE_COMPILER_XC32_MINOR
#			define XTE_COMPILER_XC32_MINOR (__C32_VERSION__ % 1000 / 10)
#
#			undef XTE_COMPILER_XC32_PATCH
#			define XTE_COMPILER_XC32_PATCH (__C32_VERSION__ % 10)
#		endif
#	endif
#
#	ifdef __DCC__
#		undef XTE_COMPILER_WIND_RIVER_DIAB
#		define XTE_COMPILER_WIND_RIVER_DIAB 1
#
#		undef XTE_COMPILER_WIND_RIVER_DIAB_MAJOR
#		define XTE_COMPILER_WIND_RIVER_DIAB_MAJOR (__VERSION_NUMBER__ / 1000)
#
#		undef XTE_COMPILER_WIND_RIVER_DIAB_MINOR
#		define XTE_COMPILER_WIND_RIVER_DIAB_MINOR (__VERSION_NUMBER__ % 1000 / 100)
#
#		undef XTE_COMPILER_WIND_RIVER_DIAB_PATCH
#		define XTE_COMPILER_WIND_RIVER_DIAB_PATCH (__VERSION_NUMBER__ % 100)
#	endif
#
#	if defined(__IBMC__) \
		|| defined(__IBMCPP__) \
		|| defined(__ibmxl__) \
		|| defined(__open_xl__) \
		|| defined(__xlC__) \
		|| defined(__xlc__)
#		undef XTE_COMPILER_XL
#		define XTE_COMPILER_XL 1
#
#		undef XTE_COMPILER_XL_MAJOR
#		undef XTE_COMPILER_XL_MINOR
#		undef XTE_COMPILER_XL_PATCH
#		ifdef __COMPILER_VER__
#			define XTE_COMPILER_XL_MAJOR (__COMPILER_VER__ / 0x1000000)
#			define XTE_COMPILER_XL_MINOR (__COMPILER_VER__ % 0x1000000 / 0x1000)
#			define XTE_COMPILER_XL_PATCH (__COMPILER_VER__ % 0x1000)
#		elifdef __IBMCPP__
#			define XTE_COMPILER_XL_MAJOR (__IBMCPP__ / 100)
#			define XTE_COMPILER_XL_MINOR (__IBMCPP__ % 10 / 10)
#			define XTE_COMPILER_XL_PATCH (__IBMCPP__ % 10)
#		elifdef __xlC__
#			define XTE_COMPILER_XL_MAJOR (__xlC__ / 0x100)
#			define XTE_COMPILER_XL_MINOR (__xlC__ % 0x100)
#			define XTE_COMPILER_XL_PATCH 0
#		elifdef __xlc__
#			define XTE_COMPILER_XL_MAJOR (__xlc__ / 0x100)
#			define XTE_COMPILER_XL_MINOR (__xlc__ % 0x100)
#			define XTE_COMPILER_XL_PATCH 0
#		else
#			define XTE_COMPILER_XL_MAJOR __ibmxl_version__
#			define XTE_COMPILER_XL_MINOR __ibmxl_release__
#			define XTE_COMPILER_XL_PATCH __ibmxl_modification__
#		endif
#	endif
#
#	ifdef __ZTC__
#		undef XTE_COMPILER_ZORTECH_CPP
#		define XTE_COMPILER_ZORTECH_CPP 1
#
#		undef XTE_COMPILER_ZORTECH_CPP_MAJOR
#		define XTE_COMPILER_ZORTECH_CPP_MAJOR (__ZTC__ / 0x100)
#
#		undef XTE_COMPILER_ZORTECH_CPP_MINOR
#		define XTE_COMPILER_ZORTECH_CPP_MINOR (__ZTC__ % 0x100 / 0x10)
#
#		undef XTE_COMPILER_ZORTECH_CPP_PATCH
#		define XTE_COMPILER_ZORTECH_CPP_PATCH (__ZTC__ % 0x10)
#	endif
#
#	if defined(SCCZ80) || defined(__SCCZ80)
#		undef XTE_COMPILER_Z88DK
#		define XTE_COMPILER_Z88DK 1
#	endif
#
#	define DETAIL_XTE_COMPILER(_operator, _major0, _minor0, _patch0, _major1, _minor1, _patch1, ...) \
		(((((0 _operator 0) && !(0 _operator 1) && !(1 _operator 0)) \
			|| (!(0 _operator 0) && (0 _operator 1) && (1 _operator 0))) \
		&& (((_major0) _operator (_major1)) \
			&& ((_minor0) _operator (_minor1)) \
			&& ((_patch0) _operator (_patch1)))) \
		|| ((_major0) _operator (_major1)) \
			|| (((_major0) == (_major1)) && ((_minor0) _operator (_minor1))) \
			|| (((_minor0) == (_minor1)) && ((_patch0) _operator (_patch1))))
#endif

// https://github.com/cpredef/predef/blob/master/Compilers.md
// https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#nvcc-identification-macro
