#ifndef DETAIL_XTE_HEADER_PREPROC_DIAGNOSTIC
#	define DETAIL_XTE_HEADER_PREPROC_DIAGNOSTIC
#
#	include "../preproc/any.hpp"
#	include "../preproc/compiler.hpp"
#	include "../preproc/if.hpp"
#	include "../preproc/pragma.hpp"
#
#	define XTE_DIAGNOSTIC_INFO(MESSAGE)
#	define XTE_DIAGNOSTIC_INFO_GCC(MESSAGE)
#	define XTE_DIAGNOSTIC_INFO_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE)
#	define XTE_DIAGNOSTIC_WARN(MESSAGE)
#	define XTE_DIAGNOSTIC_WARN_GCC(MESSAGE)
#	define XTE_DIAGNOSTIC_WARN_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_WARN_MSVC(MESSAGE)
#	define XTE_DIAGNOSTIC_ERROR(MESSAGE)
#	define XTE_DIAGNOSTIC_ERROR_GCC(MESSAGE)
#	define XTE_DIAGNOSTIC_ERROR_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_ERROR_MSVC(MESSAGE)
#	define XTE_DIAGNOSTIC_PUSH(OP, ...)
#	define XTE_DIAGNOSTIC_PUSH_GCC(OP, ...)
#	define XTE_DIAGNOSTIC_PUSH_CLANG(OP, ...)
#	define XTE_DIAGNOSTIC_PUSH_MSVC(OP, ...)
#	define XTE_DIAGNOSTIC_POP()
#	define XTE_DIAGNOSTIC_POP_GCC()
#	define XTE_DIAGNOSTIC_POP_CLANG()
#	define XTE_DIAGNOSTIC_POP_MSVC()
#	define XTE_DIAGNOSTIC_ON_GCC(ID, ...)
#	define XTE_DIAGNOSTIC_ON_CLANG(ID, ...)
#	define XTE_DIAGNOSTIC_ON_MSVC(ID, ...)
#	define XTE_DIAGNOSTIC_STRICT_GCC(ID, ...)
#	define XTE_DIAGNOSTIC_STRICT_CLANG(ID, ...)
#	define XTE_DIAGNOSTIC_STRICT_MSVC(ID, ...)
#	define XTE_DIAGNOSTIC_OFF_GCC(ID, ...)
#	define XTE_DIAGNOSTIC_OFF_CLANG(ID, ...)
#	define XTE_DIAGNOSTIC_OFF_MSVC(ID, ...)
#
#	define XTE_DIAGNOSTIC_INFO_GCC_CLANG(MESSAGE) \
		XTE_DIAGNOSTIC_INFO_GCC(MESSAGE) \
		XTE_DIAGNOSTIC_INFO_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_WARN_GCC_CLANG(MESSAGE) \
		XTE_DIAGNOSTIC_WARN_GCC(MESSAGE) \
		XTE_DIAGNOSTIC_WARN_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_ERROR_GCC_CLANG(MESSAGE) \
		XTE_DIAGNOSTIC_ERROR_GCC(MESSAGE) \
		XTE_DIAGNOSTIC_ERROR_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_PUSH_GCC_CLANG(OP, ...) \
		XTE_DIAGNOSTIC_PUSH_GCC(OP, __VA_ARGS__) \
		XTE_DIAGNOSTIC_PUSH_CLANG(OP, __VA_ARGS__)
#	define XTE_DIAGNOSTIC_PUSH_GCC_MSVC(OP, ...) \
		XTE_DIAGNOSTIC_PUSH_GCC(OP, __VA_ARGS__) \
		XTE_DIAGNOSTIC_PUSH_MSVC(OP, __VA_ARGS__)
#	define XTE_DIAGNOSTIC_PUSH_CLANG_MSVC(OP, ...) \
		XTE_DIAGNOSTIC_PUSH_CLANG(OP, __VA_ARGS__) \
		XTE_DIAGNOSTIC_PUSH_MSVC(OP, __VA_ARGS__)
#	define XTE_DIAGNOSTIC_POP_GCC_CLANG() \
		XTE_DIAGNOSTIC_POP_GCC() \
		XTE_DIAGNOSTIC_POP_CLANG()
#	define XTE_DIAGNOSTIC_POP_GCC_MSVC() \
		XTE_DIAGNOSTIC_POP_GCC() \
		XTE_DIAGNOSTIC_POP_MSVC()
#	define XTE_DIAGNOSTIC_POP_CLANG_MSVC() \
		XTE_DIAGNOSTIC_POP_CLANG() \
		XTE_DIAGNOSTIC_POP_MSVC()
#	define XTE_DIAGNOSTIC_ON_GCC_CLANG(MESSAGE) \
		XTE_DIAGNOSTIC_ON_GCC(MESSAGE) \
		XTE_DIAGNOSTIC_ON_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_STRICT_GCC_CLANG(MESSAGE) \
		XTE_DIAGNOSTIC_STRICT_GCC(MESSAGE) \
		XTE_DIAGNOSTIC_STRICT_CLANG(MESSAGE)
#	define XTE_DIAGNOSTIC_OFF_GCC_CLANG(MESSAGE) \
		XTE_DIAGNOSTIC_OFF_GCC(MESSAGE) \
		XTE_DIAGNOSTIC_OFF_CLANG(MESSAGE)
#
#	if XTE_COMPILER_MSVC
#		undef XTE_DIAGNOSTIC_INFO
#		define XTE_DIAGNOSTIC_INFO(MESSAGE) XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_WARN
#		define XTE_DIAGNOSTIC_WARN(MESSAGE) XTE_DIAGNOSTIC_WARN_MSVC(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_ERROR
#		define XTE_DIAGNOSTIC_ERROR(MESSAGE) XTE_DIAGNOSTIC_ERROR_MSVC(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_PUSH
#		define XTE_DIAGNOSTIC_PUSH(OP, ...) XTE_DIAGNOSTIC_PUSH_MSVC(OP, __VA_ARGS__)
#
#		undef XTE_DIAGNOSTIC_POP
#		define XTE_DIAGNOSTIC_POP() XTE_DIAGNOSTIC_POP_MSVC()
#	elif XTE_COMPILER_CLANG
#		undef XTE_DIAGNOSTIC_INFO
#		define XTE_DIAGNOSTIC_INFO(MESSAGE) XTE_DIAGNOSTIC_INFO_CLANG(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_WARN
#		define XTE_DIAGNOSTIC_WARN(MESSAGE) XTE_DIAGNOSTIC_WARN_CLANG(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_ERROR
#		define XTE_DIAGNOSTIC_ERROR(MESSAGE) XTE_DIAGNOSTIC_ERROR_CLANG(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_PUSH
#		define XTE_DIAGNOSTIC_PUSH(OP, ...) XTE_DIAGNOSTIC_PUSH_CLANG(OP, __VA_ARGS__)
#
#		undef XTE_DIAGNOSTIC_POP
#		define XTE_DIAGNOSTIC_POP() XTE_DIAGNOSTIC_POP_CLANG()
#	elif XTE_COMPILER_GCC
#		undef XTE_DIAGNOSTIC_INFO
#		define XTE_DIAGNOSTIC_INFO(MESSAGE) XTE_DIAGNOSTIC_INFO_GCC(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_WARN
#		define XTE_DIAGNOSTIC_WARN(MESSAGE) XTE_DIAGNOSTIC_WARN_GCC(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_ERROR
#		define XTE_DIAGNOSTIC_ERROR(MESSAGE) XTE_DIAGNOSTIC_ERROR_GCC(MESSAGE)
#
#		undef XTE_DIAGNOSTIC_PUSH
#		define XTE_DIAGNOSTIC_PUSH(OP, ...) XTE_DIAGNOSTIC_PUSH_GCC(OP, __VA_ARGS__)
#
#		undef XTE_DIAGNOSTIC_POP
#		define XTE_DIAGNOSTIC_POP() XTE_DIAGNOSTIC_POP_GCC()
#	endif
#
#	if XTE_COMPILER_GCC
#		undef XTE_DIAGNOSTIC_INFO_GCC
#		define XTE_DIAGNOSTIC_INFO_GCC(MESSAGE) XTE_PRAGMA(message MESSAGE)
#
#		undef XTE_DIAGNOSTIC_WARN_GCC
#		define XTE_DIAGNOSTIC_WARN_GCC(MESSAGE) XTE_PRAGMA(GCC warning MESSAGE)
#
#		undef XTE_DIAGNOSTIC_ERROR_GCC
#		define XTE_DIAGNOSTIC_ERROR_GCC(MESSAGE) XTE_PRAGMA(GCC error MESSAGE)
#
#		undef XTE_DIAGNOSTIC_PUSH_GCC
#		define XTE_DIAGNOSTIC_PUSH_GCC(OP, ...) XTE_PRAGMA(GCC diagnostic push) \
			XTE_IF(XTE_ANY(OP))(XTE_DIAGNOSTIC_##OP##_GCC(__VA_ARGS__))()
#
#		undef XTE_DIAGNOSTIC_POP_GCC
#		define XTE_DIAGNOSTIC_POP_GCC() XTE_PRAGMA(GCC diagnostic pop)
#
#		undef XTE_DIAGNOSTIC_ON_GCC
#		define XTE_DIAGNOSTIC_ON_GCC(ID) XTE_PRAGMA(GCC diagnostic warning ID)
#
#		undef XTE_DIAGNOSTIC_STRICT_GCC
#		define XTE_DIAGNOSTIC_STRICT_GCC(ID) XTE_PRAGMA(GCC diagnostic error ID)
#
#		undef XTE_DIAGNOSTIC_OFF_GCC
#		define XTE_DIAGNOSTIC_OFF_GCC(ID) XTE_PRAGMA(GCC diagnostic ignored ID)
#
#		define DETAIL_XTE_DIAGNOSTIC_ON_GCC(ID) 
#	endif
#
#	if XTE_COMPILER_CLANG
#		undef XTE_DIAGNOSTIC_INFO_CLANG
#		define XTE_DIAGNOSTIC_INFO_CLANG(MESSAGE) XTE_PRAGMA(message MESSAGE)
#
#		undef XTE_DIAGNOSTIC_WARN_CLANG
#		define XTE_DIAGNOSTIC_WARN_CLANG(MESSAGE) XTE_PRAGMA(GCC warning MESSAGE)
#
#		undef XTE_DIAGNOSTIC_ERROR_CLANG
#		define XTE_DIAGNOSTIC_ERROR_CLANG(MESSAGE) XTE_PRAGMA(GCC error MESSAGE)
#
#		undef XTE_DIAGNOSTIC_PUSH_CLANG
#		define XTE_DIAGNOSTIC_PUSH_CLANG(OP, ...) XTE_PRAGMA(clang diagnostic push) \
			XTE_IF(XTE_ANY(OP))(XTE_DIAGNOSTIC_##OP##_CLANG(__VA_ARGS__))()
#
#		undef XTE_DIAGNOSTIC_POP_CLANG
#		define XTE_DIAGNOSTIC_POP_CLANG() XTE_PRAGMA(clang diagnostic pop)
#
#		undef XTE_DIAGNOSTIC_ON_CLANG
#		define XTE_DIAGNOSTIC_ON_CLANG(ID) XTE_PRAGMA(clang diagnostic warning ID)
#
#		undef XTE_DIAGNOSTIC_STRICT_CLANG
#		define XTE_DIAGNOSTIC_STRICT_CLANG(ID) XTE_PRAGMA(clang diagnostic error ID)
#
#		undef XTE_DIAGNOSTIC_OFF_CLANG
#		define XTE_DIAGNOSTIC_OFF_CLANG(ID) XTE_PRAGMA(clang diagnostic ignored ID)
#	endif
#
#	if XTE_COMPILER_MSVC
#		undef XTE_DIAGNOSTIC_INFO_MSVC
#		define XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE) XTE_PRAGMA(message(MESSAGE))
#
#		undef XTE_DIAGNOSTIC_WARN_MSVC
#		define XTE_DIAGNOSTIC_WARN_MSVC(MESSAGE) XTE_PRAGMA(message("\x1B[31m" MESSAGE "\x1B[0m"))
#
#		undef XTE_DIAGNOSTIC_ERROR_MSVC
#		define XTE_DIAGNOSTIC_ERROR_MSVC(MESSAGE) XTE_PRAGMA(message("\x1B[35m" MESSAGE "\x1B[0m"))
#
#		undef XTE_DIAGNOSTIC_PUSH_MSVC
#		define XTE_DIAGNOSTIC_PUSH_MSVC(OP, ...) XTE_PRAGMA(warning(push)) \
			XTE_IF(XTE_ANY(OP))(XTE_DIAGNOSTIC_##OP##_MSVC(__VA_ARGS__))()
#
#		undef XTE_DIAGNOSTIC_POP_MSVC
#		define XTE_DIAGNOSTIC_POP_MSVC() XTE_PRAGMA(warning(pop))
#
#		undef XTE_DIAGNOSTIC_ON_MSVC
#		define XTE_DIAGNOSTIC_ON_MSVC(ID) XTE_PRAGMA(warning(default: ID))
#
#		undef XTE_DIAGNOSTIC_STRICT_MSVC
#		define XTE_DIAGNOSTIC_STRICT_MSVC(ID) XTE_PRAGMA(warning(error: ID))
#
#		undef XTE_DIAGNOSTIC_OFF_MSVC
#		define XTE_DIAGNOSTIC_OFF_MSVC(ID) XTE_PRAGMA(warning(disable: ID))
#	endif
#endif

// https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4000-c5999
