#ifndef DETAIL_XTE_HEADER_PREPROC_PLATFORM
#	define DETAIL_XTE_HEADER_PREPROC_PLATFORM
#
#	define XTE_PLATFORM_AEGIS 0
#	define XTE_PLATFORM_AEGIS_MAJOR 0
#	define XTE_PLATFORM_AEGIS_MINOR 0
#	define XTE_PLATFORM_AEGIS_PATCH 0
#	define XTE_PLATFORM_AIX 0
#	define XTE_PLATFORM_AIX_MAJOR 0
#	define XTE_PLATFORM_AIX_MINOR 0
#	define XTE_PLATFORM_AIX_PATCH 0
#	define XTE_PLATFORM_AKAROS 0
#	define XTE_PLATFORM_AKAROS_MAJOR 0
#	define XTE_PLATFORM_AKAROS_MINOR 0
#	define XTE_PLATFORM_AKAROS_PATCH 0
#	define XTE_PLATFORM_AMIGAOS 0
#	define XTE_PLATFORM_AMIGAOS_MAJOR 0
#	define XTE_PLATFORM_AMIGAOS_MINOR 0
#	define XTE_PLATFORM_AMIGAOS_PATCH 0
#	define XTE_PLATFORM_AMIGAOS_POWERUP 0
#	define XTE_PLATFORM_AMIGAOS_POWERUP_MAJOR 0
#	define XTE_PLATFORM_AMIGAOS_POWERUP_MINOR 0
#	define XTE_PLATFORM_AMIGAOS_POWERUP_PATCH 0
#	define XTE_PLATFORM_AMIGAOS_WARPOS 0
#	define XTE_PLATFORM_AMIGAOS_WARPOS_MAJOR 0
#	define XTE_PLATFORM_AMIGAOS_WARPOS_MINOR 0
#	define XTE_PLATFORM_AMIGAOS_WARPOS_PATCH 0
#	define XTE_PLATFORM_AMIX 0
#	define XTE_PLATFORM_AMIX_MAJOR 0
#	define XTE_PLATFORM_AMIX_MINOR 0
#	define XTE_PLATFORM_AMIX_PATCH 0
#	define XTE_PLATFORM_ANDROID 0
#	define XTE_PLATFORM_ANDROID_MAJOR 0
#	define XTE_PLATFORM_ANDROID_MINOR 0
#	define XTE_PLATFORM_ANDROID_PATCH 0
#	define XTE_PLATFORM_APPLE_II 0
#	define XTE_PLATFORM_APPLE_II_MAJOR 0
#	define XTE_PLATFORM_APPLE_II_MINOR 0
#	define XTE_PLATFORM_APPLE_II_PATCH 0
#	define XTE_PLATFORM_APPLE_IIE 0
#	define XTE_PLATFORM_APPLE_IIE_MAJOR 0
#	define XTE_PLATFORM_APPLE_IIE_MINOR 0
#	define XTE_PLATFORM_APPLE_IIE_PATCH 0
#	define XTE_PLATFORM_AROS 0
#	define XTE_PLATFORM_AROS_MAJOR 0
#	define XTE_PLATFORM_AROS_MINOR 0
#	define XTE_PLATFORM_AROS_PATCH 0
#	define XTE_PLATFORM_ASMJS 0
#	define XTE_PLATFORM_ASMJS_MAJOR 0
#	define XTE_PLATFORM_ASMJS_MINOR 0
#	define XTE_PLATFORM_ASMJS_PATCH 0
#	define XTE_PLATFORM_ATARI 0
#	define XTE_PLATFORM_ATARI_MAJOR 0
#	define XTE_PLATFORM_ATARI_MINOR 0
#	define XTE_PLATFORM_ATARI_PATCH 0
#	define XTE_PLATFORM_ATARI_2600 0
#	define XTE_PLATFORM_ATARI_2600_MAJOR 0
#	define XTE_PLATFORM_ATARI_2600_MINOR 0
#	define XTE_PLATFORM_ATARI_2600_PATCH 0
#	define XTE_PLATFORM_ATARI_5200 0
#	define XTE_PLATFORM_ATARI_5200_MAJOR 0
#	define XTE_PLATFORM_ATARI_5200_MINOR 0
#	define XTE_PLATFORM_ATARI_5200_PATCH 0
#	define XTE_PLATFORM_ATARI_LYNX 0
#	define XTE_PLATFORM_ATARI_LYNX_MAJOR 0
#	define XTE_PLATFORM_ATARI_LYNX_MINOR 0
#	define XTE_PLATFORM_ATARI_LYNX_PATCH 0
#	define XTE_PLATFORM_ATARI_XL 0
#	define XTE_PLATFORM_ATARI_XL_MAJOR 0
#	define XTE_PLATFORM_ATARI_XL_MINOR 0
#	define XTE_PLATFORM_ATARI_XL_PATCH 0
#	define XTE_PLATFORM_BADA 0
#	define XTE_PLATFORM_BADA_MAJOR 0
#	define XTE_PLATFORM_BADA_MINOR 0
#	define XTE_PLATFORM_BADA_PATCH 0
#	define XTE_PLATFORM_BEOS 0
#	define XTE_PLATFORM_BEOS_MAJOR 0
#	define XTE_PLATFORM_BEOS_MINOR 0
#	define XTE_PLATFORM_BEOS_PATCH 0
#	define XTE_PLATFORM_BLUE_GENE 0
#	define XTE_PLATFORM_BLUE_GENE_MAJOR 0
#	define XTE_PLATFORM_BLUE_GENE_MINOR 0
#	define XTE_PLATFORM_BLUE_GENE_PATCH 0
#	define XTE_PLATFORM_BLUE_GENE_Q 0
#	define XTE_PLATFORM_BLUE_GENE_Q_MAJOR 0
#	define XTE_PLATFORM_BLUE_GENE_Q_MINOR 0
#	define XTE_PLATFORM_BLUE_GENE_Q_PATCH 0
#	define XTE_PLATFORM_BRIDGE_OS 0
#	define XTE_PLATFORM_BRIDGE_OS_MAJOR 0
#	define XTE_PLATFORM_BRIDGE_OS_MINOR 0
#	define XTE_PLATFORM_BRIDGE_OS_PATCH 0
#	define XTE_PLATFORM_BSD 0
#	define XTE_PLATFORM_BSD_MAJOR 0
#	define XTE_PLATFORM_BSD_MINOR 0
#	define XTE_PLATFORM_BSD_PATCH 0
#	define XTE_PLATFORM_BSD_OS 0
#	define XTE_PLATFORM_BSD_OS_MAJOR 0
#	define XTE_PLATFORM_BSD_OS_MINOR 0
#	define XTE_PLATFORM_BSD_OS_PATCH 0
#	define XTE_PLATFORM_BSDI 0
#	define XTE_PLATFORM_BSDI_MAJOR 0
#	define XTE_PLATFORM_BSDI_MINOR 0
#	define XTE_PLATFORM_BSDI_PATCH 0
#	define XTE_PLATFORM_CLOUDABI 0
#	define XTE_PLATFORM_CLOUDABI_MAJOR 0
#	define XTE_PLATFORM_CLOUDABI_MINOR 0
#	define XTE_PLATFORM_CLOUDABI_PATCH 0
#	define XTE_PLATFORM_CMB 0
#	define XTE_PLATFORM_CMB_MAJOR 0
#	define XTE_PLATFORM_CMB_MINOR 0
#	define XTE_PLATFORM_CMB_PATCH 0
#	define XTE_PLATFORM_CMB_500 0
#	define XTE_PLATFORM_CMB_500_MAJOR 0
#	define XTE_PLATFORM_CMB_500_MINOR 0
#	define XTE_PLATFORM_CMB_500_PATCH 0
#	define XTE_PLATFORM_CMB_600 0
#	define XTE_PLATFORM_CMB_600_MAJOR 0
#	define XTE_PLATFORM_CMB_600_MINOR 0
#	define XTE_PLATFORM_CMB_600_PATCH 0
#	define XTE_PLATFORM_COMMANDER_X16 0
#	define XTE_PLATFORM_COMMANDER_X16_MAJOR 0
#	define XTE_PLATFORM_COMMANDER_X16_MINOR 0
#	define XTE_PLATFORM_COMMANDER_X16_PATCH 0
#	define XTE_PLATFORM_COMMODORE_16 0
#	define XTE_PLATFORM_COMMODORE_16_MAJOR 0
#	define XTE_PLATFORM_COMMODORE_16_MINOR 0
#	define XTE_PLATFORM_COMMODORE_16_PATCH 0
#	define XTE_PLATFORM_COMMODORE_64 0
#	define XTE_PLATFORM_COMMODORE_64_MAJOR 0
#	define XTE_PLATFORM_COMMODORE_64_MINOR 0
#	define XTE_PLATFORM_COMMODORE_64_PATCH 0
#	define XTE_PLATFORM_COMMODORE_128 0
#	define XTE_PLATFORM_COMMODORE_128_MAJOR 0
#	define XTE_PLATFORM_COMMODORE_128_MINOR 0
#	define XTE_PLATFORM_COMMODORE_128_PATCH 0
#	define XTE_PLATFORM_COMMODORE_PLUS_4 0
#	define XTE_PLATFORM_COMMODORE_PLUS_4_MAJOR 0
#	define XTE_PLATFORM_COMMODORE_PLUS_4_MINOR 0
#	define XTE_PLATFORM_COMMODORE_PLUS_4_PATCH 0
#	define XTE_PLATFORM_COMMODORE_VIC20 0
#	define XTE_PLATFORM_COMMODORE_VIC20_MAJOR 0
#	define XTE_PLATFORM_COMMODORE_VIC20_MINOR 0
#	define XTE_PLATFORM_COMMODORE_VIC20_PATCH 0
#	define XTE_PLATFORM_CONVEXOS 0
#	define XTE_PLATFORM_CONVEXOS_MAJOR 0
#	define XTE_PLATFORM_CONVEXOS_MINOR 0
#	define XTE_PLATFORM_CONVEXOS_PATCH 0
#	define XTE_PLATFORM_CPM 0
#	define XTE_PLATFORM_CPM_MAJOR 0
#	define XTE_PLATFORM_CPM_MINOR 0
#	define XTE_PLATFORM_CPM_PATCH 0
#	define XTE_PLATFORM_CYGWIN 0
#	define XTE_PLATFORM_CYGWIN_MAJOR 0
#	define XTE_PLATFORM_CYGWIN_MINOR 0
#	define XTE_PLATFORM_CYGWIN_PATCH 0
#	define XTE_PLATFORM_DC_OSX 0
#	define XTE_PLATFORM_DC_OSX_MAJOR 0
#	define XTE_PLATFORM_DC_OSX_MINOR 0
#	define XTE_PLATFORM_DC_OSX_PATCH 0
#	define XTE_PLATFORM_DG_UX 0
#	define XTE_PLATFORM_DG_UX_MAJOR 0
#	define XTE_PLATFORM_DG_UX_MINOR 0
#	define XTE_PLATFORM_DG_UX_PATCH 0
#	define XTE_PLATFORM_DOMAIN_OS 0
#	define XTE_PLATFORM_DOMAIN_OS_MAJOR 0
#	define XTE_PLATFORM_DOMAIN_OS_MINOR 0
#	define XTE_PLATFORM_DOMAIN_OS_PATCH 0
#	define XTE_PLATFORM_DRAGONFLY_BSD 0
#	define XTE_PLATFORM_DRAGONFLY_BSD_MAJOR 0
#	define XTE_PLATFORM_DRAGONFLY_BSD_MINOR 0
#	define XTE_PLATFORM_DRAGONFLY_BSD_PATCH 0
#	define XTE_PLATFORM_DRIVERKIT 0
#	define XTE_PLATFORM_DRIVERKIT_MAJOR 0
#	define XTE_PLATFORM_DRIVERKIT_MINOR 0
#	define XTE_PLATFORM_DRIVERKIT_PATCH 0
#	define XTE_PLATFORM_DYNIX 0
#	define XTE_PLATFORM_DYNIX_MAJOR 0
#	define XTE_PLATFORM_DYNIX_MINOR 0
#	define XTE_PLATFORM_DYNIX_PATCH 0
#	define XTE_PLATFORM_ECOS 0
#	define XTE_PLATFORM_ECOS_MAJOR 0
#	define XTE_PLATFORM_ECOS_MINOR 0
#	define XTE_PLATFORM_ECOS_PATCH 0
#	define XTE_PLATFORM_EMSCRIPTEN 0
#	define XTE_PLATFORM_EMSCRIPTEN_MAJOR 0
#	define XTE_PLATFORM_EMSCRIPTEN_MINOR 0
#	define XTE_PLATFORM_EMSCRIPTEN_PATCH 0
#	define XTE_PLATFORM_EMX 0
#	define XTE_PLATFORM_EMX_MAJOR 0
#	define XTE_PLATFORM_EMX_MINOR 0
#	define XTE_PLATFORM_EMX_PATCH 0
#	define XTE_PLATFORM_EPOC32_MARM 0
#	define XTE_PLATFORM_EPOC32_MARM_MAJOR 0
#	define XTE_PLATFORM_EPOC32_MARM_MINOR 0
#	define XTE_PLATFORM_EPOC32_MARM_PATCH 0
#	define XTE_PLATFORM_EPOC32_WINS 0
#	define XTE_PLATFORM_EPOC32_WINS_MAJOR 0
#	define XTE_PLATFORM_EPOC32_WINS_MINOR 0
#	define XTE_PLATFORM_EPOC32_WINS_PATCH 0
#	define XTE_PLATFORM_FREEBSD 0
#	define XTE_PLATFORM_FREEBSD_MAJOR 0
#	define XTE_PLATFORM_FREEBSD_MINOR 0
#	define XTE_PLATFORM_FREEBSD_PATCH 0
#	define XTE_PLATFORM_FREERTOS 0
#	define XTE_PLATFORM_FREERTOS_MAJOR 0
#	define XTE_PLATFORM_FREERTOS_MINOR 0
#	define XTE_PLATFORM_FREERTOS_PATCH 0
#	define XTE_PLATFORM_FUCHSIA 0
#	define XTE_PLATFORM_FUCHSIA_MAJOR 0
#	define XTE_PLATFORM_FUCHSIA_MINOR 0
#	define XTE_PLATFORM_FUCHSIA_PATCH 0
#	define XTE_PLATFORM_GEOS 0
#	define XTE_PLATFORM_GEOS_MAJOR 0
#	define XTE_PLATFORM_GEOS_MINOR 0
#	define XTE_PLATFORM_GEOS_PATCH 0
#	define XTE_PLATFORM_GEOS_APPLE 0
#	define XTE_PLATFORM_GEOS_APPLE_MAJOR 0
#	define XTE_PLATFORM_GEOS_APPLE_MINOR 0
#	define XTE_PLATFORM_GEOS_APPLE_PATCH 0
#	define XTE_PLATFORM_GEOS_CMB 0
#	define XTE_PLATFORM_GEOS_CMB_MAJOR 0
#	define XTE_PLATFORM_GEOS_CMB_MINOR 0
#	define XTE_PLATFORM_GEOS_CMB_PATCH 0
#	define XTE_PLATFORM_GNU_HURD 0
#	define XTE_PLATFORM_GNU_HURD_MAJOR 0
#	define XTE_PLATFORM_GNU_HURD_MINOR 0
#	define XTE_PLATFORM_GNU_HURD_PATCH 0
#	define XTE_PLATFORM_GNU_KFREEBSD 0
#	define XTE_PLATFORM_GNU_KFREEBSD_MAJOR 0
#	define XTE_PLATFORM_GNU_KFREEBSD_MINOR 0
#	define XTE_PLATFORM_GNU_KFREEBSD_PATCH 0
#	define XTE_PLATFORM_GNU_LINUX 0
#	define XTE_PLATFORM_GNU_LINUX_MAJOR 0
#	define XTE_PLATFORM_GNU_LINUX_MINOR 0
#	define XTE_PLATFORM_GNU_LINUX_PATCH 0
#	define XTE_PLATFORM_GP32 0
#	define XTE_PLATFORM_GP32_MAJOR 0
#	define XTE_PLATFORM_GP32_MINOR 0
#	define XTE_PLATFORM_GP32_PATCH 0
#	define XTE_PLATFORM_HAIKU 0
#	define XTE_PLATFORM_HAIKU_MAJOR 0
#	define XTE_PLATFORM_HAIKU_MINOR 0
#	define XTE_PLATFORM_HAIKU_PATCH 0
#	define XTE_PLATFORM_HI_UX 0
#	define XTE_PLATFORM_HI_UX_MAJOR 0
#	define XTE_PLATFORM_HI_UX_MINOR 0
#	define XTE_PLATFORM_HI_UX_PATCH 0
#	define XTE_PLATFORM_HI_UX_MPP 0
#	define XTE_PLATFORM_HI_UX_MPP_MAJOR 0
#	define XTE_PLATFORM_HI_UX_MPP_MINOR 0
#	define XTE_PLATFORM_HI_UX_MPP_PATCH 0
#	define XTE_PLATFORM_HP_UX 0
#	define XTE_PLATFORM_HP_UX_MAJOR 0
#	define XTE_PLATFORM_HP_UX_MINOR 0
#	define XTE_PLATFORM_HP_UX_PATCH 0
#	define XTE_PLATFORM_ILLUMOS 0
#	define XTE_PLATFORM_ILLUMOS_MAJOR 0
#	define XTE_PLATFORM_ILLUMOS_MINOR 0
#	define XTE_PLATFORM_ILLUMOS_PATCH 0
#	define XTE_PLATFORM_INTEGRITY 0
#	define XTE_PLATFORM_INTEGRITY_MAJOR 0
#	define XTE_PLATFORM_INTEGRITY_MINOR 0
#	define XTE_PLATFORM_INTEGRITY_PATCH 0
#	define XTE_PLATFORM_INTERIX 0
#	define XTE_PLATFORM_INTERIX_MAJOR 0
#	define XTE_PLATFORM_INTERIX_MINOR 0
#	define XTE_PLATFORM_INTERIX_PATCH 0
#	define XTE_PLATFORM_IOS 0
#	define XTE_PLATFORM_IOS_MAJOR 0
#	define XTE_PLATFORM_IOS_MINOR 0
#	define XTE_PLATFORM_IOS_PATCH 0
#	define XTE_PLATFORM_IOS_SIMULATOR 0
#	define XTE_PLATFORM_IOS_SIMULATOR_MAJOR 0
#	define XTE_PLATFORM_IOS_SIMULATOR_MINOR 0
#	define XTE_PLATFORM_IOS_SIMULATOR_PATCH 0
#	define XTE_PLATFORM_IRIX 0
#	define XTE_PLATFORM_IRIX_MAJOR 0
#	define XTE_PLATFORM_IRIX_MINOR 0
#	define XTE_PLATFORM_IRIX_PATCH 0
#	define XTE_PLATFORM_KALLISTI 0
#	define XTE_PLATFORM_KALLISTI_MAJOR 0
#	define XTE_PLATFORM_KALLISTI_MINOR 0
#	define XTE_PLATFORM_KALLISTI_PATCH 0
#	define XTE_PLATFORM_LINUX 0
#	define XTE_PLATFORM_LINUX_MAJOR 0
#	define XTE_PLATFORM_LINUX_MINOR 0
#	define XTE_PLATFORM_LINUX_PATCH 0
#	define XTE_PLATFORM_LUNIX 0
#	define XTE_PLATFORM_LUNIX_MAJOR 0
#	define XTE_PLATFORM_LUNIX_MINOR 0
#	define XTE_PLATFORM_LUNIX_PATCH 0
#	define XTE_PLATFORM_LYNXOS 0
#	define XTE_PLATFORM_LYNXOS_MAJOR 0
#	define XTE_PLATFORM_LYNXOS_MINOR 0
#	define XTE_PLATFORM_LYNXOS_PATCH 0
#	define XTE_PLATFORM_MACCATALYST 0
#	define XTE_PLATFORM_MACCATALYST_MAJOR 0
#	define XTE_PLATFORM_MACCATALYST_MINOR 0
#	define XTE_PLATFORM_MACCATALYST_PATCH 0
#	define XTE_PLATFORM_MACINTOSH 0
#	define XTE_PLATFORM_MACINTOSH_MAJOR 0
#	define XTE_PLATFORM_MACINTOSH_MINOR 0
#	define XTE_PLATFORM_MACINTOSH_PATCH 0
#	define XTE_PLATFORM_MACINTOSH_DYLD 0
#	define XTE_PLATFORM_MACINTOSH_DYLD_MAJOR 0
#	define XTE_PLATFORM_MACINTOSH_DYLD_MINOR 0
#	define XTE_PLATFORM_MACINTOSH_DYLD_PATCH 0
#	define XTE_PLATFORM_MIDNIGHTBSD 0
#	define XTE_PLATFORM_MIDNIGHTBSD_MAJOR 0
#	define XTE_PLATFORM_MIDNIGHTBSD_MINOR 0
#	define XTE_PLATFORM_MIDNIGHTBSD_PATCH 0
#	define XTE_PLATFORM_MINGW32 0
#	define XTE_PLATFORM_MINGW32_MAJOR 0
#	define XTE_PLATFORM_MINGW32_MINOR 0
#	define XTE_PLATFORM_MINGW32_PATCH 0
#	define XTE_PLATFORM_MINGW64 0
#	define XTE_PLATFORM_MINGW64_MAJOR 0
#	define XTE_PLATFORM_MINGW64_MINOR 0
#	define XTE_PLATFORM_MINGW64_PATCH 0
#	define XTE_PLATFORM_MINIX 0
#	define XTE_PLATFORM_MINIX_MAJOR 0
#	define XTE_PLATFORM_MINIX_MINOR 0
#	define XTE_PLATFORM_MINIX_PATCH 0
#	define XTE_PLATFORM_MINT 0
#	define XTE_PLATFORM_MINT_MAJOR 0
#	define XTE_PLATFORM_MINT_MINOR 0
#	define XTE_PLATFORM_MINT_PATCH 0
#	define XTE_PLATFORM_MORPHOS 0
#	define XTE_PLATFORM_MORPHOS_MAJOR 0
#	define XTE_PLATFORM_MORPHOS_MINOR 0
#	define XTE_PLATFORM_MORPHOS_PATCH 0
#	define XTE_PLATFORM_MP_RAS 0
#	define XTE_PLATFORM_MP_RAS_MAJOR 0
#	define XTE_PLATFORM_MP_RAS_MINOR 0
#	define XTE_PLATFORM_MP_RAS_PATCH 0
#	define XTE_PLATFORM_MPE_IX 0
#	define XTE_PLATFORM_MPE_IX_MAJOR 0
#	define XTE_PLATFORM_MPE_IX_MINOR 0
#	define XTE_PLATFORM_MPE_IX_PATCH 0
#	define XTE_PLATFORM_MS_DOS 0
#	define XTE_PLATFORM_MS_DOS_MAJOR 0
#	define XTE_PLATFORM_MS_DOS_MINOR 0
#	define XTE_PLATFORM_MS_DOS_PATCH 0
#	define XTE_PLATFORM_NACL 0
#	define XTE_PLATFORM_NACL_MAJOR 0
#	define XTE_PLATFORM_NACL_MINOR 0
#	define XTE_PLATFORM_NACL_PATCH 0
#	define XTE_PLATFORM_NETBSD 0
#	define XTE_PLATFORM_NETBSD_MAJOR 0
#	define XTE_PLATFORM_NETBSD_MINOR 0
#	define XTE_PLATFORM_NETBSD_PATCH 0
#	define XTE_PLATFORM_NETWARE 0
#	define XTE_PLATFORM_NETWARE_MAJOR 0
#	define XTE_PLATFORM_NETWARE_MINOR 0
#	define XTE_PLATFORM_NETWARE_PATCH 0
#	define XTE_PLATFORM_NES 0
#	define XTE_PLATFORM_NES_MAJOR 0
#	define XTE_PLATFORM_NES_MINOR 0
#	define XTE_PLATFORM_NES_PATCH 0
#	define XTE_PLATFORM_NEXT 0
#	define XTE_PLATFORM_NEXT_MAJOR 0
#	define XTE_PLATFORM_NEXT_MINOR 0
#	define XTE_PLATFORM_NEXT_PATCH 0
#	define XTE_PLATFORM_NINTENDO_3DS 0
#	define XTE_PLATFORM_NINTENDO_3DS_MAJOR 0
#	define XTE_PLATFORM_NINTENDO_3DS_MINOR 0
#	define XTE_PLATFORM_NINTENDO_3DS_PATCH 0
#	define XTE_PLATFORM_NINTENDO_64 0
#	define XTE_PLATFORM_NINTENDO_64_MAJOR 0
#	define XTE_PLATFORM_NINTENDO_64_MINOR 0
#	define XTE_PLATFORM_NINTENDO_64_PATCH 0
#	define XTE_PLATFORM_NINTENDO_DS 0
#	define XTE_PLATFORM_NINTENDO_DS_MAJOR 0
#	define XTE_PLATFORM_NINTENDO_DS_MINOR 0
#	define XTE_PLATFORM_NINTENDO_DS_PATCH 0
#	define XTE_PLATFORM_NINTENDO_GAMECUBE 0
#	define XTE_PLATFORM_NINTENDO_GAMECUBE_MAJOR 0
#	define XTE_PLATFORM_NINTENDO_GAMECUBE_MINOR 0
#	define XTE_PLATFORM_NINTENDO_GAMECUBE_PATCH 0
#	define XTE_PLATFORM_NINTENDO_SWITCH 0
#	define XTE_PLATFORM_NINTENDO_SWITCH_MAJOR 0
#	define XTE_PLATFORM_NINTENDO_SWITCH_MINOR 0
#	define XTE_PLATFORM_NINTENDO_SWITCH_PATCH 0
#	define XTE_PLATFORM_NINTENDO_WII 0
#	define XTE_PLATFORM_NINTENDO_WII_MAJOR 0
#	define XTE_PLATFORM_NINTENDO_WII_MINOR 0
#	define XTE_PLATFORM_NINTENDO_WII_PATCH 0
#	define XTE_PLATFORM_NONSTOP 0
#	define XTE_PLATFORM_NONSTOP_MAJOR 0
#	define XTE_PLATFORM_NONSTOP_MINOR 0
#	define XTE_PLATFORM_NONSTOP_PATCH 0
#	define XTE_PLATFORM_NUCLEUS_RTOS 0
#	define XTE_PLATFORM_NUCLEUS_RTOS_MAJOR 0
#	define XTE_PLATFORM_NUCLEUS_RTOS_MINOR 0
#	define XTE_PLATFORM_NUCLEUS_RTOS_PATCH 0
#	define XTE_PLATFORM_NUTTX 0
#	define XTE_PLATFORM_NUTTX_MAJOR 0
#	define XTE_PLATFORM_NUTTX_MINOR 0
#	define XTE_PLATFORM_NUTTX_PATCH 0
#	define XTE_PLATFORM_OHIO_SCIENTIFIC_CHALLENGER_1P 0
#	define XTE_PLATFORM_OHIO_SCIENTIFIC_CHALLENGER_1P_MAJOR 0
#	define XTE_PLATFORM_OHIO_SCIENTIFIC_CHALLENGER_1P_MINOR 0
#	define XTE_PLATFORM_OHIO_SCIENTIFIC_CHALLENGER_1P_PATCH 0
#	define XTE_PLATFORM_OHOS 0
#	define XTE_PLATFORM_OHOS_MAJOR 0
#	define XTE_PLATFORM_OHOS_MINOR 0
#	define XTE_PLATFORM_OHOS_PATCH 0
#	define XTE_PLATFORM_OPENBSD 0
#	define XTE_PLATFORM_OPENBSD_MAJOR 0
#	define XTE_PLATFORM_OPENBSD_MINOR 0
#	define XTE_PLATFORM_OPENBSD_PATCH 0
#	define XTE_PLATFORM_OPENSERVER 0
#	define XTE_PLATFORM_OPENSERVER_MAJOR 0
#	define XTE_PLATFORM_OPENSERVER_MINOR 0
#	define XTE_PLATFORM_OPENSERVER_PATCH 0
#	define XTE_PLATFORM_ORIC_ATMOS 0
#	define XTE_PLATFORM_ORIC_ATMOS_MAJOR 0
#	define XTE_PLATFORM_ORIC_ATMOS_MINOR 0
#	define XTE_PLATFORM_ORIC_ATMOS_PATCH 0
#	define XTE_PLATFORM_OS_2 0
#	define XTE_PLATFORM_OS_2_MAJOR 0
#	define XTE_PLATFORM_OS_2_MINOR 0
#	define XTE_PLATFORM_OS_2_PATCH 0
#	define XTE_PLATFORM_OS_400 0
#	define XTE_PLATFORM_OS_400_MAJOR 0
#	define XTE_PLATFORM_OS_400_MINOR 0
#	define XTE_PLATFORM_OS_400_PATCH 0
#	define XTE_PLATFORM_OS_9 0
#	define XTE_PLATFORM_OS_9_MAJOR 0
#	define XTE_PLATFORM_OS_9_MINOR 0
#	define XTE_PLATFORM_OS_9_PATCH 0
#	define XTE_PLATFORM_OSE 0
#	define XTE_PLATFORM_OSE_MAJOR 0
#	define XTE_PLATFORM_OSE_MINOR 0
#	define XTE_PLATFORM_OSE_PATCH 0
#	define XTE_PLATFORM_PALM_OS 0
#	define XTE_PLATFORM_PALM_OS_MAJOR 0
#	define XTE_PLATFORM_PALM_OS_MINOR 0
#	define XTE_PLATFORM_PALM_OS_PATCH 0
#	define XTE_PLATFORM_PDOS 0
#	define XTE_PLATFORM_PDOS_MAJOR 0
#	define XTE_PLATFORM_PDOS_MINOR 0
#	define XTE_PLATFORM_PDOS_PATCH 0
#	define XTE_PLATFORM_PET 0
#	define XTE_PLATFORM_PET_MAJOR 0
#	define XTE_PLATFORM_PET_MINOR 0
#	define XTE_PLATFORM_PET_PATCH 0
#	define XTE_PLATFORM_PHOENIX 0
#	define XTE_PLATFORM_PHOENIX_MAJOR 0
#	define XTE_PLATFORM_PHOENIX_MINOR 0
#	define XTE_PLATFORM_PHOENIX_PATCH 0
#	define XTE_PLATFORM_PLAN_9 0
#	define XTE_PLATFORM_PLAN_9_MAJOR 0
#	define XTE_PLATFORM_PLAN_9_MINOR 0
#	define XTE_PLATFORM_PLAN_9_PATCH 0
#	define XTE_PLATFORM_PNACL 0
#	define XTE_PLATFORM_PNACL_MAJOR 0
#	define XTE_PLATFORM_PNACL_MINOR 0
#	define XTE_PLATFORM_PNACL_PATCH 0
#	define XTE_PLATFORM_PPCC 0
#	define XTE_PLATFORM_PPCC_MAJOR 0
#	define XTE_PLATFORM_PPCC_MINOR 0
#	define XTE_PLATFORM_PPCC_PATCH 0
#	define XTE_PLATFORM_PSOS 0
#	define XTE_PLATFORM_PSOS_MAJOR 0
#	define XTE_PLATFORM_PSOS_MINOR 0
#	define XTE_PLATFORM_PSOS_PATCH 0
#	define XTE_PLATFORM_QNX 0
#	define XTE_PLATFORM_QNX_MAJOR 0
#	define XTE_PLATFORM_QNX_MINOR 0
#	define XTE_PLATFORM_QNX_PATCH 0
#	define XTE_PLATFORM_RISCOS 0
#	define XTE_PLATFORM_RISCOS_MAJOR 0
#	define XTE_PLATFORM_RISCOS_MINOR 0
#	define XTE_PLATFORM_RISCOS_PATCH 0
#	define XTE_PLATFORM_RTEMS 0
#	define XTE_PLATFORM_RTEMS_MAJOR 0
#	define XTE_PLATFORM_RTEMS_MINOR 0
#	define XTE_PLATFORM_RTEMS_PATCH 0
#	define XTE_PLATFORM_RTTHREAD 0
#	define XTE_PLATFORM_RTTHREAD_MAJOR 0
#	define XTE_PLATFORM_RTTHREAD_MINOR 0
#	define XTE_PLATFORM_RTTHREAD_PATCH 0
#	define XTE_PLATFORM_SEGA_DREAMCAST 0
#	define XTE_PLATFORM_SEGA_DREAMCAST_MAJOR 0
#	define XTE_PLATFORM_SEGA_DREAMCAST_MINOR 0
#	define XTE_PLATFORM_SEGA_DREAMCAST_PATCH 0
#	define XTE_PLATFORM_SIM6502 0
#	define XTE_PLATFORM_SIM6502_MAJOR 0
#	define XTE_PLATFORM_SIM6502_MINOR 0
#	define XTE_PLATFORM_SIM6502_PATCH 0
#	define XTE_PLATFORM_SIM65C02 0
#	define XTE_PLATFORM_SIM65C02_MAJOR 0
#	define XTE_PLATFORM_SIM65C02_MINOR 0
#	define XTE_PLATFORM_SIM65C02_PATCH 0
#	define XTE_PLATFORM_SINIX 0
#	define XTE_PLATFORM_SINIX_MAJOR 0
#	define XTE_PLATFORM_SINIX_MINOR 0
#	define XTE_PLATFORM_SINIX_PATCH 0
#	define XTE_PLATFORM_SKYOS 0
#	define XTE_PLATFORM_SKYOS_MAJOR 0
#	define XTE_PLATFORM_SKYOS_MINOR 0
#	define XTE_PLATFORM_SKYOS_PATCH 0
#	define XTE_PLATFORM_SOLARIS 0
#	define XTE_PLATFORM_SOLARIS_MAJOR 0
#	define XTE_PLATFORM_SOLARIS_MINOR 0
#	define XTE_PLATFORM_SOLARIS_PATCH 0
#	define XTE_PLATFORM_SUNOS 0
#	define XTE_PLATFORM_SUNOS_MAJOR 0
#	define XTE_PLATFORM_SUNOS_MINOR 0
#	define XTE_PLATFORM_SUNOS_PATCH 0
#	define XTE_PLATFORM_SONY_PS 0
#	define XTE_PLATFORM_SONY_PS_MAJOR 0
#	define XTE_PLATFORM_SONY_PS_MINOR 0
#	define XTE_PLATFORM_SONY_PS_PATCH 0
#	define XTE_PLATFORM_SONY_PS2 0
#	define XTE_PLATFORM_SONY_PS2_MAJOR 0
#	define XTE_PLATFORM_SONY_PS2_MINOR 0
#	define XTE_PLATFORM_SONY_PS2_PATCH 0
#	define XTE_PLATFORM_SONY_PS3 0
#	define XTE_PLATFORM_SONY_PS3_MAJOR 0
#	define XTE_PLATFORM_SONY_PS3_MINOR 0
#	define XTE_PLATFORM_SONY_PS3_PATCH 0
#	define XTE_PLATFORM_SONY_PS4 0
#	define XTE_PLATFORM_SONY_PS4_MAJOR 0
#	define XTE_PLATFORM_SONY_PS4_MINOR 0
#	define XTE_PLATFORM_SONY_PS4_PATCH 0
#	define XTE_PLATFORM_SONY_PS5 0
#	define XTE_PLATFORM_SONY_PS5_MAJOR 0
#	define XTE_PLATFORM_SONY_PS5_MINOR 0
#	define XTE_PLATFORM_SONY_PS5_PATCH 0
#	define XTE_PLATFORM_SONY_PSP 0
#	define XTE_PLATFORM_SONY_PSP_MAJOR 0
#	define XTE_PLATFORM_SONY_PSP_MINOR 0
#	define XTE_PLATFORM_SONY_PSP_PATCH 0
#	define XTE_PLATFORM_SONY_VITA 0
#	define XTE_PLATFORM_SONY_VITA_MAJOR 0
#	define XTE_PLATFORM_SONY_VITA_MINOR 0
#	define XTE_PLATFORM_SONY_VITA_PATCH 0
#	define XTE_PLATFORM_SORTIX 0
#	define XTE_PLATFORM_SORTIX_MAJOR 0
#	define XTE_PLATFORM_SORTIX_MINOR 0
#	define XTE_PLATFORM_SORTIX_PATCH 0
#	define XTE_PLATFORM_SUPERVISION 0
#	define XTE_PLATFORM_SUPERVISION_MAJOR 0
#	define XTE_PLATFORM_SUPERVISION_MINOR 0
#	define XTE_PLATFORM_SUPERVISION_PATCH 0
#	define XTE_PLATFORM_SYGWIN 0
#	define XTE_PLATFORM_SYGWIN_MAJOR 0
#	define XTE_PLATFORM_SYGWIN_MINOR 0
#	define XTE_PLATFORM_SYGWIN_PATCH 0
#	define XTE_PLATFORM_SYLLABLE 0
#	define XTE_PLATFORM_SYLLABLE_MAJOR 0
#	define XTE_PLATFORM_SYLLABLE_MINOR 0
#	define XTE_PLATFORM_SYLLABLE_PATCH 0
#	define XTE_PLATFORM_SYM1 0
#	define XTE_PLATFORM_SYM1_MAJOR 0
#	define XTE_PLATFORM_SYM1_MINOR 0
#	define XTE_PLATFORM_SYM1_PATCH 0
#	define XTE_PLATFORM_SYMBIAN 0
#	define XTE_PLATFORM_SYMBIAN_MAJOR 0
#	define XTE_PLATFORM_SYMBIAN_MINOR 0
#	define XTE_PLATFORM_SYMBIAN_PATCH 0
#	define XTE_PLATFORM_SYSTEM_V 0
#	define XTE_PLATFORM_SYSTEM_V_MAJOR 0
#	define XTE_PLATFORM_SYSTEM_V_MINOR 0
#	define XTE_PLATFORM_SYSTEM_V_PATCH 0
#	define XTE_PLATFORM_SWLINUX 0
#	define XTE_PLATFORM_SWLINUX_MAJOR 0
#	define XTE_PLATFORM_SWLINUX_MINOR 0
#	define XTE_PLATFORM_SWLINUX_PATCH 0
#	define XTE_PLATFORM_TELESTRAT 0
#	define XTE_PLATFORM_TELESTRAT_MAJOR 0
#	define XTE_PLATFORM_TELESTRAT_MINOR 0
#	define XTE_PLATFORM_TELESTRAT_PATCH 0
#	define XTE_PLATFORM_THREADX 0
#	define XTE_PLATFORM_THREADX_MAJOR 0
#	define XTE_PLATFORM_THREADX_MINOR 0
#	define XTE_PLATFORM_THREADX_PATCH 0
#	define XTE_PLATFORM_TRU64 0
#	define XTE_PLATFORM_TRU64_MAJOR 0
#	define XTE_PLATFORM_TRU64_MINOR 0
#	define XTE_PLATFORM_TRU64_PATCH 0
#	define XTE_PLATFORM_TV_OS 0
#	define XTE_PLATFORM_TV_OS_MAJOR 0
#	define XTE_PLATFORM_TV_OS_MINOR 0
#	define XTE_PLATFORM_TV_OS_PATCH 0
#	define XTE_PLATFORM_UC_OS_II 0
#	define XTE_PLATFORM_UC_OS_II_MAJOR 0
#	define XTE_PLATFORM_UC_OS_II_MINOR 0
#	define XTE_PLATFORM_UC_OS_II_PATCH 0
#	define XTE_PLATFORM_UCLINUX 0
#	define XTE_PLATFORM_UCLINUX_MAJOR 0
#	define XTE_PLATFORM_UCLINUX_MINOR 0
#	define XTE_PLATFORM_UCLINUX_PATCH 0
#	define XTE_PLATFORM_ULTRIX 0
#	define XTE_PLATFORM_ULTRIX_MAJOR 0
#	define XTE_PLATFORM_ULTRIX_MINOR 0
#	define XTE_PLATFORM_ULTRIX_PATCH 0
#	define XTE_PLATFORM_UNICOS 0
#	define XTE_PLATFORM_UNICOS_MAJOR 0
#	define XTE_PLATFORM_UNICOS_MINOR 0
#	define XTE_PLATFORM_UNICOS_PATCH 0
#	define XTE_PLATFORM_UNICOS_MP 0
#	define XTE_PLATFORM_UNICOS_MP_MAJOR 0
#	define XTE_PLATFORM_UNICOS_MP_MINOR 0
#	define XTE_PLATFORM_UNICOS_MP_PATCH 0
#	define XTE_PLATFORM_UNIX 0
#	define XTE_PLATFORM_UNIX_MAJOR 0
#	define XTE_PLATFORM_UNIX_MINOR 0
#	define XTE_PLATFORM_UNIX_PATCH 0
#	define XTE_PLATFORM_UNIX_SV 0
#	define XTE_PLATFORM_UNIX_SV_MAJOR 0
#	define XTE_PLATFORM_UNIX_SV_MINOR 0
#	define XTE_PLATFORM_UNIX_SV_PATCH 0
#	define XTE_PLATFORM_UNIXWARE 0
#	define XTE_PLATFORM_UNIXWARE_MAJOR 0
#	define XTE_PLATFORM_UNIXWARE_MINOR 0
#	define XTE_PLATFORM_UNIXWARE_PATCH 0
#	define XTE_PLATFORM_UTS 0
#	define XTE_PLATFORM_UTS_MAJOR 0
#	define XTE_PLATFORM_UTS_MINOR 0
#	define XTE_PLATFORM_UTS_PATCH 0
#	define XTE_PLATFORM_UWIN 0
#	define XTE_PLATFORM_UWIN_MAJOR 0
#	define XTE_PLATFORM_UWIN_MINOR 0
#	define XTE_PLATFORM_UWIN_PATCH 0
#	define XTE_PLATFORM_VMS 0
#	define XTE_PLATFORM_VMS_MAJOR 0
#	define XTE_PLATFORM_VMS_MINOR 0
#	define XTE_PLATFORM_VMS_PATCH 0
#	define XTE_PLATFORM_VOS 0
#	define XTE_PLATFORM_VOS_MAJOR 0
#	define XTE_PLATFORM_VOS_MINOR 0
#	define XTE_PLATFORM_VOS_PATCH 0
#	define XTE_PLATFORM_VXWORKS 0
#	define XTE_PLATFORM_VXWORKS_MAJOR 0
#	define XTE_PLATFORM_VXWORKS_MINOR 0
#	define XTE_PLATFORM_VXWORKS_PATCH 0
#	define XTE_PLATFORM_VISION_OS 0
#	define XTE_PLATFORM_VISION_OS_MAJOR 0
#	define XTE_PLATFORM_VISION_OS_MINOR 0
#	define XTE_PLATFORM_VISION_OS_PATCH 0
#	define XTE_PLATFORM_WASI 0
#	define XTE_PLATFORM_WASI_MAJOR 0
#	define XTE_PLATFORM_WASI_MINOR 0
#	define XTE_PLATFORM_WASI_PATCH 0
#	define XTE_PLATFORM_WATCH_OS 0
#	define XTE_PLATFORM_WATCH_OS_MAJOR 0
#	define XTE_PLATFORM_WATCH_OS_MINOR 0
#	define XTE_PLATFORM_WATCH_OS_PATCH 0
#	define XTE_PLATFORM_WINDOWS 0
#	define XTE_PLATFORM_WINDOWS_MAJOR 0
#	define XTE_PLATFORM_WINDOWS_MINOR 0
#	define XTE_PLATFORM_WINDOWS_PATCH 0
#	define XTE_PLATFORM_WINDOWS_CE 0
#	define XTE_PLATFORM_WINDOWS_CE_MAJOR 0
#	define XTE_PLATFORM_WINDOWS_CE_MINOR 0
#	define XTE_PLATFORM_WINDOWS_CE_PATCH 0
#	define XTE_PLATFORM_WINDOWS_DESKTOP 0
#	define XTE_PLATFORM_WINDOWS_DESKTOP_MAJOR 0
#	define XTE_PLATFORM_WINDOWS_DESKTOP_MINOR 0
#	define XTE_PLATFORM_WINDOWS_DESKTOP_PATCH 0
#	define XTE_PLATFORM_WINDOWS_GDK 0
#	define XTE_PLATFORM_WINDOWS_GDK_MAJOR 0
#	define XTE_PLATFORM_WINDOWS_GDK_MINOR 0
#	define XTE_PLATFORM_WINDOWS_GDK_PATCH 0
#	define XTE_PLATFORM_WINDOWS_NT 0
#	define XTE_PLATFORM_WINDOWS_NT_MAJOR 0
#	define XTE_PLATFORM_WINDOWS_NT_MINOR 0
#	define XTE_PLATFORM_WINDOWS_NT_PATCH 0
#	define XTE_PLATFORM_WIND_U 0
#	define XTE_PLATFORM_WIND_U_MAJOR 0
#	define XTE_PLATFORM_WIND_U_MINOR 0
#	define XTE_PLATFORM_WIND_U_PATCH 0
#	define XTE_PLATFORM_XBOX 0
#	define XTE_PLATFORM_XBOX_MAJOR 0
#	define XTE_PLATFORM_XBOX_MINOR 0
#	define XTE_PLATFORM_XBOX_PATCH 0
#	define XTE_PLATFORM_XBOX_360 0
#	define XTE_PLATFORM_XBOX_360_MAJOR 0
#	define XTE_PLATFORM_XBOX_360_MINOR 0
#	define XTE_PLATFORM_XBOX_360_PATCH 0
#	define XTE_PLATFORM_XBOX_ONE 0
#	define XTE_PLATFORM_XBOX_ONE_MAJOR 0
#	define XTE_PLATFORM_XBOX_ONE_MINOR 0
#	define XTE_PLATFORM_XBOX_ONE_PATCH 0
#	define XTE_PLATFORM_XBOX_SERIES 0
#	define XTE_PLATFORM_XBOX_SERIES_MAJOR 0
#	define XTE_PLATFORM_XBOX_SERIES_MINOR 0
#	define XTE_PLATFORM_XBOX_SERIES_PATCH 0
#	define XTE_PLATFORM_XENIX 0
#	define XTE_PLATFORM_XENIX_MAJOR 0
#	define XTE_PLATFORM_XENIX_MINOR 0
#	define XTE_PLATFORM_XENIX_PATCH 0
#	define XTE_PLATFORM_Z 0
#	define XTE_PLATFORM_Z_MAJOR 0
#	define XTE_PLATFORM_Z_MINOR 0
#	define XTE_PLATFORM_Z_PATCH 0
#	define XTE_PLATFORM_ZEPHYR 0
#	define XTE_PLATFORM_ZEPHYR_MAJOR 0
#	define XTE_PLATFORM_ZEPHYR_MINOR 0
#	define XTE_PLATFORM_ZEPHYR_PATCH 0
#	define XTE_PLATFORM_ZETA 0
#	define XTE_PLATFORM_ZETA_MAJOR 0
#	define XTE_PLATFORM_ZETA_MINOR 0
#	define XTE_PLATFORM_ZETA_PATCH 0
#
#	define XTE_PLATFORM(_type, _operator, _major, ...) \
		DETAIL_XTE_PLATFORM( \
			_operator, \
			XTE_PLATFORM_##_type##_MAJOR, XTE_PLATFORM_##_type##_MINOR, XTE_PLATFORM_##_type##_PATCH, \
			_major, __VA_ARGS__ __VA_OPT__(,) 0, 0 \
		)
#
#	if __has_include(<TargetConditionals.h>)
#		include <TargetConditionals.h>
#	endif
#
#	ifdef aegis
#		undef XTE_PLATFORM_AEGIS
#		define XTE_PLATFORM_AEGIS 1
#	endif
#
#	if defined(_AIX) || defined(__TOS_AIX__)
#		undef XTE_PLATFORM_AIX
#		define XTE_PLATFORM_AIX 1
#
#		undef XTE_PLATFORM_AIX_MAJOR
#		undef XTE_PLATFORM_AIX_MINOR
#		ifdef _AIX43
#			define XTE_PLATFORM_AIX_MAJOR 4
#			define XTE_PLATFORM_AIX_MINOR 3
#		elifdef _AIX41
#			define XTE_PLATFORM_AIX_MAJOR 4
#			define XTE_PLATFORM_AIX_MINOR 1
#		elifdef _AIX32
#			define XTE_PLATFORM_AIX_MAJOR 3
#			define XTE_PLATFORM_AIX_MINOR 2
#		elifdef _AIX3
#			define XTE_PLATFORM_AIX_MAJOR 3
#			define XTE_PLATFORM_AIX_MINOR 0
#		else
#			define XTE_PLATFORM_AIX_MAJOR 0
#			define XTE_PLATFORM_AIX_MINOR 0
#		endif
#	endif
#
#	ifdef __ros__
#		undef XTE_PLATFORM_AKAROS
#		define XTE_PLATFORM_AKAROS 1
#	endif
#
#	if defined(AMIGA) \
		|| defined(AMIGA_AROS) \
		|| defined(AMIGA_M68K) \
		|| defined(AMIGA_MORPHOS) \
		|| defined(AMIGA_OS4) \
		|| defined(_AMIGA) \
		|| defined(__amigaos__)
#		undef XTE_PLATFORM_AMIGAOS
#		define XTE_PLATFORM_AMIGAOS 1
#
#		undef XTE_PLATFORM_AMIGAOS_MAJOR
#		if defined(AMIGA_OS4) || defined(__amigaos4__)
#			define XTE_PLATFORM_AMIGAOS_MAJOR 4
#		elifdef AMIGA_M68K
#			define XTE_PLATFORM_AMIGAOS_MAJOR 3
#		else
#			define XTE_PLATFORM_AMIGAOS_MAJOR 0
#		endif
#	endif
#
#	if defined(AMIGA_M68K) && defined(__VBCC__) && defined(__PPC__)
#		include <proto/powerpc.h>
#
#		ifndef _VBCCINLINE_POWERPC_H
#			undef XTE_PLATFORM_AMIGAOS_POWERUP
#			define XTE_PLATFORM_AMIGAOS_POWERUP 1
#		endif
#	endif
#
#	if defined(AMIGA_M68K) && defined(__VBCC__) && defined(__PPC__)
#		include <proto/powerpc.h>
#
#		ifdef _VBCCINLINE_POWERPC_H
#			undef XTE_PLATFORM_AMIGAOS_WARPOS
#			define XTE_PLATFORM_AMIGAOS_WARPOS 1
#		endif
#	endif
#
#	ifdef __AMIX__
#		undef XTE_PLATFORM_AMIX
#		define XTE_PLATFORM_AMIX 1
#	endif
#
#	ifdef __ANDROID__
#		include <android/api-level.h>
#
#		undef XTE_PLATFORM_ANDROID
#		define XTE_PLATFORM_ANDROID 1
#
#		undef XTE_PLATFORM_ANDROID_MAJOR
#		define XTE_PLATFORM_ANDROID_MAJOR __ANDROID_API__
#	endif
#
#	ifdef __APPLE2__
#		undef XTE_PLATFORM_APPLE_II
#		define XTE_PLATFORM_APPLE_II 1
#	endif
#
#	ifdef __APPLE2ENH__
#		undef XTE_PLATFORM_APPLE_IIE
#		define XTE_PLATFORM_APPLE_IIE 1
#	endif
#
#	ifdef __AROS__
#		undef XTE_PLATFORM_AROS
#		define XTE_PLATFORM_AROS 1
#	endif
#
#	ifdef __asmjs__
#		undef XTE_PLATFORM_ASMJS
#		define XTE_PLATFORM_ASMJS 1
#	endif
#
#	ifdef __ATARI__
#		undef XTE_PLATFORM_ATARI
#		define XTE_PLATfORM_ATARI 1
#	endif
#
#	ifdef __ATARI2600__
#		undef XTE_PLATFORM_ATARI_2600
#		define XTE_PLATfORM_ATARI_2600 1
#	endif
#
#	ifdef __ATARI5200__
#		undef XTE_PLATFORM_ATARI_5200
#		define XTE_PLATfORM_ATARI_5200 1
#	endif
#
#	ifdef __LYNX__
#		undef XTE_PLATFORM_ATARI_LYNX
#		define XTE_PLATfORM_ATARI_LYNX 1
#	endif
#
#	ifdef __ATARIXL__
#		undef XTE_PLATFORM_ATARI_XL
#		define XTE_PLATfORM_ATARI_XL 1
#	endif
#
#	ifdef __BADA__
#		undef XTE_PLATFORM_BADA
#		define XTE_PLATFORM_BADA 1
#	endif
#
#	if defined(_BEOS) || defined(__BEOS__) || defined(__BeOS)
#		undef XTE_PLATFORM_BEOS
#		define XTE_PLATFORM_BEOS 1
#	endif
#
#	if defined(__THW_BLUEGENE__) || defined(__bg__)
#		undef XTE_PLATFORM_BLUE_GENE
#		define XTE_PLATFORM_BLUE_GENE 1
#	endif
#
#	if defined(__TOS_BGQ__) || defined(__bgq__)
#		undef XTE_PLATFORM_BLUE_GENE_Q
#		define XTE_PLATFORM_BLUE_GENE_Q 1
#	endif
#
#	if defined(__BRIDGE_OS_VERSION_MIN_REQUIRED) \
		|| defined(__ENVIRONMENT_BRIDGE_OS_VERSION_MIN_REQUIRED__)
#		undef XTE_PLATFORM_BRIDGE_OS
#		define XTE_PLATFORM_BRIDGE_OS 1
#
#		undef XTE_PLATFORM_BRIDGE_OS_MAJOR
#		undef XTE_PLATFORM_BRIDGE_OS_MINOR
#		undef XTE_PLATFORM_BRIDGE_OS_PATCH
#		ifdef __BRIDGE_OS_VERSION_MIN_REQUIRED
#			define XTE_PLATFORM_BRIDGE_OS_MAJOR (__BRIDGE_OS_VERSION_MIN_REQUIRED / 10000)
#			define XTE_PLATFORM_BRIDGE_OS_MINOR (__BRIDGE_OS_VERSION_MIN_REQUIRED % 10000 / 100)
#			define XTE_PLATFORM_BRIDGE_OS_PATCH (__BRIDGE_OS_VERSION_MIN_REQUIRED % 100)
#		else
#			define XTE_PLATFORM_BRIDGE_OS_MAJOR (__ENVIRONMENT_BRIDGE_OS_VERSION_MIN_REQUIRED__ / 10000)
#			define XTE_PLATFORM_BRIDGE_OS_MINOR (__ENVIRONMENT_BRIDGE_OS_VERSION_MIN_REQUIRED__ % 10000 / 100)
#			define XTE_PLATFORM_BRIDGE_OS_PATCH (__ENVIRONMENT_BRIDGE_OS_VERSION_MIN_REQUIRED__ % 100)
#		endif
#	endif
#
#	if defined(BSD) \
		|| defined(_SYSTYPE_BSD) \
		|| defined(__DragonFly__) \
		|| defined(__FreeBSD__) \
		|| defined(__NetBSD__) \
		|| defined(__OpenBSD__) \
		|| defined(__bsdi__)
#		include <sys/param.h>
#
#		undef XTE_PLATFORM_BSD
#		define XTE_PLATFORM_BSD 1
#
#		undef XTE_PLATFORM_BSD_MAJOR
#		define XTE_PLATFORM_BSD_MAJOR (BSD / 100)
#
#		undef XTE_PLATFORM_BSD_MINOR
#		define XTE_PLATFORM_BSD_MINOR (BSD % 100)
#	endif
#
#	ifdef __bsdos__
#		undef XTE_PLATFORM_BSD_OS
#		define XTE_PLATFORM_BSD_OS 1
#	endif
#
#	if defined(__bsdi) || defined(__bsdi__) || defined(bsdi)
#		undef XTE_PLATFORM_BSDI
#		define XTE_PLATFORM_BSDI 1
#	endif
#
#	ifdef __CloudABI__
#		undef XTE_PLATFORM_CLOUDABI
#		define XTE_PLATFORM_CLOUDABI 1
#	endif
#
#	ifdef __CMB__
#		undef XTE_PLATFORM_CMB
#		define XTE_PLATFORM_CMB 1
#	endif
#
#	ifdef __CMB510__
#		undef XTE_PLATFORM_CMB_500
#		define XTE_PLATFORM_CMB_500 1
#	endif
#
#	ifdef __CMB610__
#		undef XTE_PLATFORM_CMB_600
#		define XTE_PLATFORM_CMB_600 1
#	endif
#
#	ifdef __CX16__
#		undef XTE_PLATFORM_COMMANDER_X16
#		define XTE_PLATFORM_COMMANDER_X16 1
#	endif
#
#	ifdef __C16__
#		undef XTE_PLATFORM_COMMODORE_16
#		define XTE_PLATFORM_COMMODORE_16 1
#	endif
#
#	ifdef __C64__
#		undef XTE_PLATFORM_COMMODORE_64
#		define XTE_PLATFORM_COMMODORE_64 1
#	endif
#
#	ifdef __C128__
#		undef XTE_PLATFORM_COMMODORE_128
#		define XTE_PLATFORM_COMMODORE_128 1
#	endif
#
#	ifdef __PLUS4__
#		undef XTE_PLATFORM_COMMODORE_PLUS_4
#		define XTE_PLATFORM_COMMODORE_PLUS_4 1
#	endif
#
#	ifdef __VIC20__
#		undef XTE_PLATFORM_COMMODORE_VIC20
#		define XTE_PLATFORM_COMMODORE_VIC20 1
#	endif
#
#	ifdef __convex__
#		undef XTE_PLATFORM_CONVEXOS
#		define XTE_PLATFORM_CONVEXOS 1
#	endif
#
#	if defined(CPM) || defined(__CPM)
#		undef XTE_PLATFORM_CPM
#		define XTE_PLATFORM_CPM 1
#	endif
#
#	ifdef __CYGWIN__
#		undef XTE_PLATFORM_CYGWIN
#		define XTE_PLATFORM_CYGWIN 1
#
#		undef XTE_PLATFORM_CYGWIN_MAJOR
#		define XTE_PLATFORM_CYGWIN_MAJOR CYGWIN_VERSION_API_MAJOR
#
#		undef XTE_PLATFORM_CYGWIN_MINOR
#		define XTE_PLATFORM_CYGWIN_MINOR CYGWIN_VERSION_API_MINOR
#	endif
#
#	ifdef pyr
#		undef XTE_PLATFORM_DC_OSX
#		define XTE_PLATFORM_DC_OSX 1
#	endif
#
#	if defined(DGUX) || defined(__DGUX__) || defined(__dgux__)
#		undef XTE_PLATFORM_DG_UX
#		define XTE_PLATFORM_DG_UX 1
#	endif
#
#	ifdef apollo
#		undef XTE_PLATFORM_DOMAIN_OS
#		define XTE_PLATFORM_DOMAIN_OS 1
#	endif
#
#	ifdef __DragonFly__
#		undef XTE_PLATFORM_DRAGONFLY_BSD
#		define XTE_PLATFORM_DRAGONFLY_BSD 1
#	endif
#
#	if defined(__DRIVERKIT_VERSION_MIN_REQUIRED) \
		|| defined(__ENVIRONMENT_DRIVERKIT_VERSION_MIN_REQUIRED__)
#		undef XTE_PLATFORM_DRIVERKIT
#		define XTE_PLATFORM_DRIVERKIT 1
#
#		undef XTE_PLATFORM_DRIVERKIT_MAJOR
#		undef XTE_PLATFORM_DRIVERKIT_MINOR
#		undef XTE_PLATFORM_DRIVERKIT_PATCH
#		ifdef __DRIVERKIT_VERSION_MIN_REQUIRED
#			define XTE_PLATFORM_DRIVERKIT_MAJOR (__DRIVERKIT_VERSION_MIN_REQUIRED / 10000)
#			define XTE_PLATFORM_DRIVERKIT_MINOR (__DRIVERKIT_VERSION_MIN_REQUIRED % 10000 / 100)
#			define XTE_PLATFORM_DRIVERKIT_PATCH (__DRIVERKIT_VERSION_MIN_REQUIRED % 100)
#		else
#			define XTE_PLATFORM_DRIVERKIT_MAJOR (__ENVIRONMENT_DRIVERKIT_VERSION_MIN_REQUIRED__ / 10000)
#			define XTE_PLATFORM_DRIVERKIT_MINOR (__ENVIRONMENT_DRIVERKIT_VERSION_MIN_REQUIRED__ % 10000 / 100)
#			define XTE_PLATFORM_DRIVERKIT_PATCH (__ENVIRONMENT_DRIVERKIT_VERSION_MIN_REQUIRED__ % 100)
#		endif
#	endif
#
#	if defined(_SEQUENT_) || defined(sequent)
#		undef XTE_PLATFORM_DYNIX
#		define XTE_PLATFORM_DYNIX 1
#	endif
#
#	ifdef __ECOS
#		undef XTE_PLATFORM_ECOS
#		define XTE_PLATFORM_ECOS 1
#	endif
#
#	ifdef __EMSCRIPTEN__
#		include <emscripten/version.h>
#
#		undef XTE_PLATFORM_EMSCRIPTEN
#		define XTE_PLATFORM_EMSCRIPTEN 1
#
#		ifdef __EMSCRIPTEN_major__
#			undef XTE_PLATFORM_EMSCRIPTEN_MAJOR
#			define XTE_PLATFORM_EMSCRIPTEN_MAJOR __EMSCRIPTEN_major__
#
#			undef XTE_PLATFORM_EMSCRIPTEN_MINOR
#			define XTE_PLATFORM_EMSCRIPTEN_MINOR __EMSCRIPTEN_minor__
#
#			undef XTE_PLATFORM_EMSCRIPTEN_PATCH
#			define XTE_PLATFORM_EMSCRIPTEN_PATCH __EMSCRIPTEN_tiny__
#		endif
#	endif
#
#	ifdef __EMX__
#		undef XTE_PLATFORM_EMX
#		define XTE_PLATFORM_EMX 1
#	endif
#
#	ifdef __EPOC32__
#		undef XTE_PLATFORM_EPOC32_MARM
#		define XTE_PLATFORM_EPOC32_MARM 1
#	endif
#
#	ifdef __WINS__
#		undef XTE_PLATFORM_EPOC32_WINS
#		define XTE_PLATFORM_EPOC32_WINS 1
#	endif
#
#	if defined(__FreeBSD__) || defined(__FreeBSD_kernel__)
#		include <sys/param.h>
#
#		undef XTE_PLATFORM_FREEBSD
#		define XTE_PLATFORM_FREEBSD 1
#
#		undef XTE_PLATFORM_FREEBSD_MAJOR
#		define XTE_PLATFORM_FREEBSD_MAJOR (__FreeBSD_version / 100000)
#
#		undef XTE_PLATFORM_FREEBSD_MINOR
#		define XTE_PLATFORM_FREEBSD_MINOR (__FreeBSD_version / 10000 % 10)
#
#		undef XTE_PLATFORM_FREEBSD_PATCH
#		define XTE_PLATFORM_FREEBSD_PATCH (__FreeBSD_version % 10000)
#	endif
#
#	ifdef __FREERTOS__
#		undef XTE_PLATFORM_FREERTOS
#		define XTE_PLATFORM_FREERTOS 1
#	endif
#
#	ifdef __Fuchsia__
#		undef XTE_PLATFORM_FUCHSIA
#		define XTE_PLATFORM_FUCHSIA 1
#
#		undef XTE_PLATFORM_FUCHSIA_MAJOR
#		define XTE_PLATFORM_FUCHSIA_MAJOR __Fuchsia_API_level__
#	endif
#
#	ifdef __GEOS__
#		undef XTE_PLATFORM_GEOS
#		define XTE_PLATFORM_GEOS 1
#	endif
#
#	ifdef __GEOS_APPLE__
#		undef XTE_PLATFORM_GEOS_APPLE
#		define XTE_PLATFORM_GEOS_APPLE 1
#	endif
#
#	ifdef __GEOS_CMB__
#		undef XTE_PLATFORM_GEOS_CMB
#		define XTE_PLATFORM_GEOS_CMB 1
#	endif
#
#	if defined(__GNU__) || defined(__gnu_hurd__)
#		undef XTE_PLATFORM_GNU_HURD
#		define XTE_PLATFORM_GNU_HURD 1
#	endif
#
#	if defined(__FreeBSD_kernel__) && defined(__GLIBC__)
#		undef XTE_PLATFORM_GNU_KFREEBSD
#		define XTE_PLATFORM_GNU_KFREEBSD 1
#	endif
#
#	ifdef __gnu_linux__
#		undef XTE_PLATFORM_GNU_LINUX
#		define XTE_PLATFORM_GNU_LINUX 1
#	endif
#
#	ifdef __GP32__
#		undef XTE_PLATFORM_GP32
#		define XTE_PLATFORM_GP32 1
#	endif
#
#	ifdef __HAIKU__
#		undef XTE_PLATFORM_HAIKU
#		define XTE_PLATFORM_HAIKU 1
#	endif
#
#	ifdef __hiuxmpp
#		undef XTE_PLATFORM_HI_UX_MPP
#		define XTE_PLATFORM_HI_UX_MPP 1
#	endif
#
#	if defined(__hpua) \
		|| defined(__hpux) \
		|| defined(__hpux__) \
		|| defined(_hpux) \
		|| defined(hpux)
#		undef XTE_PLATFORM_HP_UX
#		define XTE_PLATFORM_HP_UX 1
#	endif
#
#	ifdef __illumos__
#		undef XTE_PLATFORM_ILLUMOS
#		define XTE_PLATFORM_ILLUMOS 1
#	endif
#
#	ifdef __INTEGRITY
#		undef XTE_PLATFORM_INTEGRITY
#		define XTE_PLATFORM_INTEGRITY 1
#	endif
#
#	if (defined(__APPLE__) && (defined(TARGET_OS_IOS) || defined(TARGET_OS_IPHONE))) \
		|| defined(__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__) \
		|| defined(__IPHONE_OS_VERSION_MIN_REQUIRED)
#		undef XTE_PLATFORM_IOS
#		define XTE_PLATFORM_IOS 1
#
#		undef XTE_PLATFORM_IOS_MAJOR
#		undef XTE_PLATFORM_IOS_MINOR
#		undef XTE_PLATFORM_IOS_PATCH
#		ifdef __IPHONE_OS_VERSION_MIN_REQUIRED
#			define XTE_PLATFORM_IOS_MAJOR (__IPHONE_OS_VERSION_MIN_REQUIRED / 10000)
#			define XTE_PLATFORM_IOS_MINOR (__IPHONE_OS_VERSION_MIN_REQUIRED % 10000 / 100)
#			define XTE_PLATFORM_IOS_PATCH (__IPHONE_OS_VERSION_MIN_REQUIRED % 100)
#		else
#			define XTE_PLATFORM_IOS_MAJOR (__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__ / 10000)
#			define XTE_PLATFORM_IOS_MINOR (__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__ % 10000 / 100)
#			define XTE_PLATFORM_IOS_PATCH (__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__ % 100)
#		endif
#	endif
#
#	if (defined(__APPLE__) && defined(TARGET_OS_SIMULATOR)) || defined(TARGET_IPHONE_SIMULATOR)
#		undef XTE_PLATFORM_IOS_SIMULATOR
#		define XTE_PLATFORM_IOS_SIMULATOR 1
#	endif
#
#	ifdef __INTERIX
#		include <interix/interix.h>
#		include <interix/registry.h>
#
#		undef XTE_PLATFORM_INTERIX
#		define XTE_PLATFORM_INTERIX 1
#
#		undef XTE_PLATFORM_INTERIX_MAJOR
#		undef XTE_PLATFORM_INTERIX_MINOR
#		ifdef ROOT_KEY_SYSWOW
#			ifdef REGVAL_ENABLE_SU_TO_ROOT
#				include <net/if.h>
#
#				if IF_NAMESIZE != 127
#					define XTE_PLATFORM_INTERIX_MAJOR 6
#					define XTE_PLATFORM_INTERIX_MINOR 2
#				else
#					define XTE_PLATFORM_INTERIX_MAJOR 6
#					define XTE_PLATFORM_INTERIX_MINOR 0
#				endif
#			else
#				define XTE_PLATFORM_INTERIX_MAJOR 5
#				define XTE_PLATFORM_INTERIX_MINOR 2
#			endif
#		elifdef PTHREAD_CHUNK_SIZE
#			define XTE_PLATFORM_INTERIX_MAJOR 3
#			define XTE_PLATFORM_INTERIX_MINOR 5
#		else
#			define XTE_PLATFORM_INTERIX_MAJOR 3
#			define XTE_PLATFORM_INTERIX_MINOR 0
#		endif
#	endif
#
#	if defined(_SGI) || defined(__sgi) || defined(sgi)
#		undef XTE_PLATFORM_IRIX
#		define XTE_PLATFORM_IRIX 1
#	endif
#
#	ifdef __KOS__
#		undef XTE_PLATFORM_KALLISTI
#		define XTE_PLATFORM_KALLISTI 1
#	endif
#
#	if defined(__gnu_linux__) \
		|| defined(__linux) \
		|| defined(__linux__) \
		|| defined(linux)
#		undef XTE_PLATFORM_LINUX
#		define XTE_PLATFORM_LINUX 1
#	endif
#
#	ifdef __LUNIX__
#		undef XTE_PLATFORM_LUNIX
#		define XTE_PLATFORM_LUNIX 1
#	endif
#
#	ifdef __Lynx__
#		undef XTE_PLATFORM_LYNXOS
#		define XTE_PLATFORM_LYNXOS 1
#	endif
#
#	if defined(__APPLE__) && defined(TARGET_OS_MACCATALYST)
#		undef XTE_PLATFORM_MACCATALYST
#		define XTE_PLATFORM_MACCATALYST 1
#	endif
#
#	if defined(MAC) \
		|| defined(Macintosh) \
		|| (defined(__APPLE__) && (defined(TARGET_OS_EMBEDDED) || defined(TARGET_OS_OSX))) \
		|| defined(__DARWIN__) \
		|| defined(__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__) \
		|| defined(__MAC_OS_X_VERSION_MIN_REQUIRED) \
		|| defined(__MACH__) \
		|| defined(applec) \
		|| defined(macintosh)
#		undef XTE_PLATFORM_MACINTOSH
#		define XTE_PLATFORM_MACINTOSH 1
#
#		undef XTE_PLATFORM_MACINTOSH_MAJOR
#		undef XTE_PLATFORM_MACINTOSH_MINOR
#		undef XTE_PLATFORM_MACINTOSH_PATCH
#		ifdef __MAC_OS_X_VERSION_MIN_REQUIRED
#			define XTE_PLATFORM_MACINTOSH_MAJOR (__MAC_OS_X_VERSION_MIN_REQUIRED / 10000)
#			define XTE_PLATFORM_MACINTOSH_MINOR (__MAC_OS_X_VERSION_MIN_REQUIRED % 10000 / 100)
#			define XTE_PLATFORM_MACINTOSH_PATCH (__MAC_OS_X_VERSION_MIN_REQUIRED % 100)
#		elifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__
#			define XTE_PLATFORM_MACINTOSH_MAJOR (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ / 10000)
#			define XTE_PLATFORM_MACINTOSH_MINOR (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ % 10000 / 100)
#			define XTE_PLATFORM_MACINTOSH_PATCH (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ % 100)
#		elif defined(__APPLE__) && defined(__MACH__)
#			define XTE_PLATFORM_MACINTOSH_MAJOR 10
#			define XTE_PLATFORM_MACINTOSH_MINOR 0
#			define XTE_PLATFORM_MACINTOSH_PATCH 0
#		else
#			define XTE_PLATFORM_MACINTOSH_MAJOR 9
#			define XTE_PLATFORM_MACINTOSH_MINOR 0
#			define XTE_PLATFORM_MACINTOSH_PATCH 0
#		endif
#	endif
#
#	ifdef MACOSX_DYLD
#		undef XTE_PLATFORM_MACINTOSH_DYLD
#		define XTE_PLATFORM_MACINTOSH_DYLD 1
#	endif
#
#	if defined(__MidnightBSD__) || defined(__MidnightBSD_kernel__)
#		include <sys/param.h>
#
#		undef XTE_PLATFORM_MIDNIGHTBSD
#		define XTE_PLATFORM_MIDNIGHTBSD 1
#
#		undef XTE_PLATFORM_MIDNIGHTBSD_MAJOR
#		define XTE_PLATFORM_MIDNIGHTBSD_MAJOR (__MidnightBSD_version / 100000)
#
#		undef XTE_PLATFORM_MIDNIGHTBSD_MINOR
#		define XTE_PLATFORM_MIDNIGHTBSD_MINOR (__MidnightBSD_version / 1000 % 100)
#
#		undef XTE_PLATFORM_MIDNIGHTBSD_PATCH
#		define XTE_PLATFORM_MIDNIGHTBSD_PATCH (__MidnightBSD_version % 1000)
#	endif
#
#	ifdef __MINGW32__
#		undef XTE_PLATFORM_MINGW32
#		define XTE_PLATFORM_MINGW32 1
#
#		undef XTE_PLATFORM_MINGW32_MAJOR
#		define XTE_PLATFORM_MINGW32_MAJOR __MING32_VERSION_MAJOR
#
#		undef XTE_PLATFORM_MINGW32_MINOR
#		define XTE_PLATFORM_MINGW32_MINOR __MING32_VERSION_MINOR
#	endif
#
#	ifdef __MINGW64__
#		undef XTE_PLATFORM_MINGW64
#		define XTE_PLATFORM_MINGW64 1
#
#		undef XTE_PLATFORM_MINGW64_MAJOR
#		define XTE_PLATFORM_MINGW64_MAJOR __MING64_VERSION_MAJOR
#
#		undef XTE_PLATFORM_MINGW64_MINOR
#		define XTE_PLATFORM_MINGW64_MINOR __MING64_VERSION_MINOR
#	endif
#
#	if defined(_MINIX) || defined(__minix) || defined(__minix__)
#		undef XTE_PLATFORM_MINIX
#		define XTE_PLATFORM_MINIX 1
#	endif
#
#	ifdef __MINT__
#		undef XTE_PLATFORM_MINT
#		define XTE_PLATFORM_MINT 1
#	endif
#
#	ifdef __MORPHOS__
#		undef XTE_PLATFORM_MORPHOS
#		define XTE_PLATFORM_MORPHOS 1
#	endif
#
#	if defined(MPRAS) || defined(_MPRAS)
#		undef XTE_PLATFORM_MP_RAS
#		define XTE_PLATFORM_MP_RAS 1
#	endif
#
#	if defined(mpeix) || defined(__mpexl)
#		undef XTE_PLATFORM_MPE_IX
#		define XTE_PLATFORM_MPE_IX 1
#	endif
#
#	if defined(MSDOS) \
		|| defined(_MSDOS) \
		|| defined(__DOS__) \
		|| defined(__MSDOS) \
		|| defined(__MSDOS__)
#		undef XTE_PLATFORM_MS_DOS
#		define XTE_PLATFORM_MS_DOS 1
#	endif
#
#	ifdef __native_client__
#		undef XTE_PLATFORM_NACL
#		define XTE_PLATFORM_NACL 1
#	endif
#
#	ifdef __NetBSD__
#		include <sys/param.h>
#
#		undef XTE_PLATFORM_NETBSD
#		define XTE_PLATFORM_NETBSD 1
#
#		ifdef __NetBSD_Version
#			undef XTE_PLATFORM_NETBSD_MAJOR
#			define XTE_PLATFORM_NETBSD_MAJOR (__NetBSD_Version / 100000000)
#
#			undef XTE_PLATFORM_NETBSD_MINOR
#			define XTE_PLATFORM_NETBSD_MINOR (__NetBSD_Version / 1000000 % 100)
#
#			undef XTE_PLATFORM_NETBSD_PATCH
#			define XTE_PLATFORM_NETBSD_PATCH (__NetBSD_Version / 100 % 100)
#		elifdef __NetBSD_version
#			undef XTE_PLATFORM_NETBSD_MAJOR
#			define XTE_PLATFORM_NETBSD_MAJOR (__NetBSD_version / 100000000)
#
#			undef XTE_PLATFORM_NETBSD_MINOR
#			define XTE_PLATFORM_NETBSD_MINOR (__NetBSD_version / 1000000 % 100)
#
#			undef XTE_PLATFORM_NETBSD_PATCH
#			define XTE_PLATFORM_NETBSD_PATCH (__NetBSD_version / 100 % 100)
#		elifdef NetBSD1_0
#			undef XTE_PLATFORM_NETBSD_MAJOR
#			define XTE_PLATFORM_NETBSD_MAJOR 1
#		elifdef NetBSD0_9
#			undef XTE_PLATFORM_NETBSD_MINOR
#			define XTE_PLATFORM_NETBSD_MINOR 9
#		elifdef NetBSD0_8
#			undef XTE_PLATFORM_NETBSD_MINOR
#			define XTE_PLATFORM_NETBSD_MINOR 8
#		endif
#	endif
#
#	ifdef NLM
#		undef XTE_PLATFORM_NETWARE
#		define XTE_PLATFORM_NETWARE 1
#	endif
#
#	ifdef __NES__
#		undef XTE_PLATFORM_NES
#		define XTE_PLATFORM_NES 1
#	endif
#
#	ifdef NeXT
#		undef XTE_PLATFORM_NEXT
#		define XTE_PLATFORM_NEXT 1
#	endif
#
#	ifdef __3DS__
#		undef XTE_PLATFORM_NINTENDO_3DS
#		define XTE_PLATFORM_NINTENDO_3DS 1
#	endif
#
#	ifdef __N64__
#		undef XTE_PLATFORM_NINTENDO_64
#		define XTE_PLATFORM_NINTENDO_64 1
#	endif
#
#	ifdef __DS__
#		undef XTE_PLATFORM_NINTENDO_DS
#		define XTE_PLATFORM_NINTENDO_DS 1
#	endif
#
#	if (defined(_GC) && (defined(__PPC__) || defined(__ppc__))) \
		|| defined(__GAMECUBE__)
#		undef XTE_PLATFORM_NINTENDO_GAMECUBE
#		define XTE_PLATFORM_NINTENDO_GAMECUBE 1
#	endif
#
#	ifdef __NX__
#		undef XTE_PLATFORM_NINTENDO_SWITCH
#		define XTE_PLATFORM_NINTENDO_SWITCH 1
#	endif
#
#	ifdef __WII__
#		undef XTE_PLATFORM_NINTENDO_WII
#		define XTE_PLATFORM_NINTENDO_WII 1
#	endif
#
#	ifdef __TANDEM
#		undef XTE_PLATFORM_NONSTOP
#		define XTE_PLATFORM_NONSTOP 1
#	endif
#
#	ifdef __nucleus__
#		undef XTE_PLATFORM_NUCLEUS_RTOS
#		define XTE_PLATFORM_NUCLEUS_RTOS 1
#	endif
#
#	ifdef __NuttX__
#		undef XTE_PLATFORM_NUTTX
#		define XTE_PLATFORM_NUTTX 1
#	endif
#
#	ifdef __OSIC1P__
#		undef XTE_PLATFORM_OHIO_SCIENTIFIC_COMPUTER_1P
#		define XTE_PLATFORM_OHIO_SCIENTIFIC_COMPUTER_1P 1
#	endif
#
#	ifdef __OHOS__
#		undef XTE_PLATFORM_OHOS
#		define XTE_PLATFORM_OHOS 1
#	endif
#
#	ifdef __OpenBSD__
#		undef XTE_PLATFORM_OPENBSD
#		define XTE_PLATFORM_OPENBSD 1
#
#		undef XTE_PLATFORM_OPENBSD_MAJOR
#		undef XTE_PLATFORM_OPENBSD_MINOR
#		ifdef OpenBSD7_6
#			define XTE_PLATFORM_OPENBSD_MAJOR 7
#			define XTE_PLATFORM_OPENBSD_MINOR 6
#		elifdef OpenBSD7_5
#			define XTE_PLATFORM_OPENBSD_MAJOR 7
#			define XTE_PLATFORM_OPENBSD_MINOR 5
#		elifdef OpenBSD7_4
#			define XTE_PLATFORM_OPENBSD_MAJOR 7
#			define XTE_PLATFORM_OPENBSD_MINOR 4
#		elifdef OpenBSD7_3
#			define XTE_PLATFORM_OPENBSD_MAJOR 7
#			define XTE_PLATFORM_OPENBSD_MINOR 3
#		elifdef OpenBSD7_2
#			define XTE_PLATFORM_OPENBSD_MAJOR 7
#			define XTE_PLATFORM_OPENBSD_MINOR 2
#		elifdef OpenBSD7_1
#			define XTE_PLATFORM_OPENBSD_MAJOR 7
#			define XTE_PLATFORM_OPENBSD_MINOR 1
#		elifdef OpenBSD7_0
#			define XTE_PLATFORM_OPENBSD_MAJOR 7
#			define XTE_PLATFORM_OPENBSD_MINOR 0
#		elifdef OpenBSD6_9
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 9
#		elifdef OpenBSD6_8
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 8
#		elifdef OpenBSD6_7
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 7
#		elifdef OpenBSD6_6
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 6
#		elifdef OpenBSD6_5
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 5
#		elifdef OpenBSD6_4
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 4
#		elifdef OpenBSD6_3
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 3
#		elifdef OpenBSD6_2
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 2
#		elifdef OpenBSD6_1
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 1
#		elifdef OpenBSD6_0
#			define XTE_PLATFORM_OPENBSD_MAJOR 6
#			define XTE_PLATFORM_OPENBSD_MINOR 0
#		elifdef OpenBSD5_9
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 9
#		elifdef OpenBSD5_8
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 8
#		elifdef OpenBSD5_7
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 7
#		elifdef OpenBSD5_6
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 6
#		elifdef OpenBSD5_5
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 5
#		elifdef OpenBSD5_4
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 4
#		elifdef OpenBSD5_3
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 3
#		elifdef OpenBSD5_2
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 2
#		elifdef OpenBSD5_1
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 1
#		elifdef OpenBSD5_0
#			define XTE_PLATFORM_OPENBSD_MAJOR 5
#			define XTE_PLATFORM_OPENBSD_MINOR 0
#		elifdef OpenBSD4_9
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 9
#		elifdef OpenBSD4_8
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 8
#		elifdef OpenBSD4_7
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 7
#		elifdef OpenBSD4_6
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 6
#		elifdef OpenBSD4_5
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 5
#		elifdef OpenBSD4_4
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 4
#		elifdef OpenBSD4_3
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 3
#		elifdef OpenBSD4_2
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 2
#		elifdef OpenBSD4_1
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 1
#		elifdef OpenBSD4_0
#			define XTE_PLATFORM_OPENBSD_MAJOR 4
#			define XTE_PLATFORM_OPENBSD_MINOR 0
#		elifdef OpenBSD3_9
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 9
#		elifdef OpenBSD3_8
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 8
#		elifdef OpenBSD3_7
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 7
#		elifdef OpenBSD3_6
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 6
#		elifdef OpenBSD3_5
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 5
#		elifdef OpenBSD3_4
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 4
#		elifdef OpenBSD3_3
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 3
#		elifdef OpenBSD3_2
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 2
#		elifdef OpenBSD3_1
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 1
#		elifdef OpenBSD3_0
#			define XTE_PLATFORM_OPENBSD_MAJOR 3
#			define XTE_PLATFORM_OPENBSD_MINOR 0
#		elifdef OpenBSD2_9
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 9
#		elifdef OpenBSD2_8
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 8
#		elifdef OpenBSD2_7
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 7
#		elifdef OpenBSD2_6
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 6
#		elifdef OpenBSD2_5
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 5
#		elifdef OpenBSD2_4
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 4
#		elifdef OpenBSD2_3
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 3
#		elifdef OpenBSD2_2
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 2
#		elifdef OpenBSD2_1
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 1
#		elifdef OpenBSD2_0
#			define XTE_PLATFORM_OPENBSD_MAJOR 2
#			define XTE_PLATFORM_OPENBSD_MINOR 0
#		else
#			define XTE_PLATFORM_OPENBSD_MAJOR 1
#			define XTE_PLATFORM_OPENBSD_MINOR 0
#		endif
#	endif
#
#	if defined(M_I386) \
		|| defined(SCO_SV) \
		|| defined(_SCO_DS) \
		|| defined(_SCO_SV) \
		|| defined(sco_sv)
#		undef XTE_PLATFORM_OPENSERVER
#		define XTE_PLATFORM_OPENSERVER 1
#	endif
#
#	ifdef __ATMOS__
#		undef XTE_PLATFORM_ORIC_ATMOS
#		define XTE_PLATFORM_ORIC_ATMOS 1
#	endif
#
#	if defined(OS2) \
		|| defined(_OS2) \
		|| defined(__OS2__) \
		|| defined(__TOS_OS2__)
#		undef XTE_PLATFORM_OS_2
#		define XTE_PLATFORM_OS_2 1
#	endif
#
#	ifdef __OS400__
#		undef XTE_PLATFORM_OS_400
#		define XTE_PLATFORM_OS_400 1
#
#		undef XTE_PLATFORM_OS_400_MAJOR
#		define XTE_PLATFORM_OS_400_MAJOR (__OS400_TGTVRM__ / 100)
#
#		undef XTE_PLATFORM_OS_400_MINOR
#		define XTE_PLATFORM_OS_400_MINOR (__OS400_TGTVRM__ / 10 % 10)
#
#		undef XTE_PLATFORM_OS_400_PATCH
#		define XTE_PLATFORM_OS_400_PATCH (__OS400_TGTVRM__ % 10)
#	endif
#
#	if defined(_OSK) || defined(__OS9000)
#		undef XTE_PLATFORM_OS_9
#		define XTE_PLATFORM_OS_9 1
#	endif
#
#	ifdef __OSE__
#		undef XTE_PLATFORM_OSE
#		define XTE_PLATFORM_OSE 1
#	endif
#
#	ifdef __palmos__
#		undef XTE_PLATFORM_PALM_OS
#		define XTE_PLATFORM_PALM_OS 1
#	endif
#
#	ifdef __PDOS386__
#		undef XTE_PLATFORM_PDOS
#		define XTE_PLATFORM_PDOS 1
#	endif
#
#	ifdef __PET__
#		undef XTE_PLATFORM_PET
#		define XTE_PLATFORM_PET 1
#	endif
#
#	if defined(__phoenix) || defined(__phoenix__) || defined(phoenix)
#		undef XTE_PLATFORM_PHOENIX
#		define XTE_PLATFORM_PHOENIX 1
#	endif
#
#	ifdef EPLAN9
#		undef XTE_PLATFORM_PLAN_9
#		define XTE_PLATFORM_PLAN_9 1
#	endif
#
#	ifdef __pnacl__
#		undef XTE_PLATFORM_PNACL
#		define XTE_PLATFORM_PNACL 1
#	endif
#
#	ifdef __PPCC__
#		undef XTE_PLATFORM_PPCC
#		define XTE_PLATFORM_PPCC 1
#	endif
#
#	ifdef __PSOS__
#		undef XTE_PLATFORM_PSOS
#		define XTE_PLATFORM_PSOS 1
#	endif
#
#	if defined(__QNXNTO__) || defined(__QNX__)
#		include <sys/neutrino.h>
#
#		undef XTE_PLATFORM_QNX
#		define XTE_PLATFORM_QNX 1
#
#		ifdef __QNXNTO__
#			undef XTE_PLATFORM_QNX_MAJOR
#			define XTE_PLATFORM_QNX_MAJOR (_NTO_VERSION / 100)
#
#			undef XTE_PLATFORM_QNX_MINOR
#			define XTE_PLATFORM_QNX_MINOR (_NTO_VERSION / 10 % 10)
#
#			undef XTE_PLATFORM_QNX_PATCH
#			define XTE_PLATFORM_QNX_PATCH (_NTO_VERSION % 10)
#		elifdef __QNX__
#			undef XTE_PLATFORM_QNX_MAJOR
#			define XTE_PLATFORM_QNX_MAJOR 4
#		endif
#	endif
#
#	if defined(__acorn) || defined(__riscos) || defined(__riscos__)
#		undef XTE_PLATFORM_RISCOS
#		define XTE_PLATFORM_RISCOS 1
#	endif
#
#	ifdef __RTEMS__
#		undef XTE_PLATFORM_RTEMS
#		define XTE_PLATFORM_RTEMS 1
#	endif
#
#	ifdef __RTTHREAD__
#		undef XTE_PLATFORM_RTTHREAD
#		define XTE_PLATFORM_RTTHREAD 1
#	endif
#
#	if (defined(__GNUC__) && !defined(__SNC__) && defined(__SH4_SINGLE_ONLY__)) \
		|| defined(_arch_dreamcast)
#		undef XTE_PLATFORM_SEGA_DREAMCAST
#		define XTE_PLATFORM_SEGA_DREAMCAST 1
#	endif
#
#	ifdef __SIM6502__
#		undef XTE_PLATFORM_SIM6502
#		define XTE_PLATFORM_SIM6502 1
#	endif
#
#	ifdef __SIM65C02__
#		undef XTE_PLATFORM_SIM65C02
#		define XTE_PLATFORM_SIM65C02 1
#	endif
#
#	if defined(__SINIX__) || defined(__sinix) || defined(__sinix__)
#		undef XTE_PLATFORM_SINIX
#		define XTE_PLATFORM_SINIX 1
#	endif
#
#	if defined(_SINUX_) || defined(sinux)
#		undef XTE_PLATFORM_SINUX
#		define XTE_PLATFORM_SINUX 1
#	endif
#
#	ifdef SKYOS
#		undef XTE_PLATFORM_SKYOS
#		define XTE_PLATFORM_SKYOS 1
#	endif
#
#	if defined(__SVR4) || defined(__svr4__)
#		undef XTE_PLATFORM_SOLARIS
#		define XTE_PLATFORM_SOLARIS 1
#	endif
#
#	if defined(sun) || defined(__sun)
#		undef XTE_PLATFORM_SUNOS
#		define XTE_PLATFORM_SUNOS 1
#	endif
#
#	ifdef __SCE__
#		undef XTE_PLATFORM_SONY_PS
#		define XTE_PLATFORM_SONY_PS 1
#	endif
#
#	if defined(PS2) || defined(__PS2__) || defined(__PLAYSTATION2__)
#		undef XTE_PLATFORM_SONY_PS2
#		define XTE_PLATFORM_SONY_PS2 1
#	endif
#
#	ifdef __CELLOS_LV2__
#		undef XTE_PLATFORM_SONY_PS3
#		define XTE_PLATFORM_SONY_PS3 1
#	endif
#
#	ifdef __ORBIS__
#		undef XTE_PLATFORM_SONY_PS4
#		define XTE_PLATFORM_SONY_PS4 1
#	endif
#
#	ifdef __PROSPERO__
#		undef XTE_PLATFORM_SONY_PS5
#		define XTE_PLATFORM_SONY_PS5 1
#	endif
#
#	if defined(__psp__) || defined(__PSP__)
#		undef XTE_PLATFORM_SONY_PSP
#		define XTE_PLATFORM_SONY_PSP 1
#	endif
#
#	if defined(__psp2__) || defined(__vita__)
#		undef XTE_PLATFORM_SONY_VITA
#		define XTE_PLATFORM_SONY_VITA 1
#	endif
#
#	ifdef __sortix__
#		undef XTE_PLATFORM_SORTIX
#		define XTE_PLATFORM_SORTIX 1
#	endif
#
#	ifdef __SUPERVISION__
#		undef XTE_PLATFORM_SUPERVISION
#		define XTE_PLATFORM_SUPERVISION 1
#	endif
#
#	ifdef __SYGWIN__
#		undef XTE_PLATFORM_SYGWIN
#		define XTE_PLATFORM_SYGWIN 1
#	endif
#
#	ifdef __SYLLABLE__
#		undef XTE_PLATFORM_SYLLABLE
#		define XTE_PLATFORM_SYLLABLE 1
#	endif
#
#	ifdef __SYM1__
#		undef XTE_PLATFORM_SYM1
#		define XTE_PLATFORM_SYM1 1
#	endif
#
#	ifdef __SYMBIAN32__
#		undef XTE_PLATFORM_SYMBIAN
#		define XTE_PLATFORM_SYMBIAN 1
#	endif
#
#	if defined(_SYSTYPE_SVR4) \
		|| defined(__SVR4) \
		|| defined(__svr4__) \
		|| defined(__sysv__)
#		undef XTE_PLATFORM_SYSTEM_V
#		define XTE_PLATFORM_SYSTEM_V 1
#	endif
#
#	ifdef __WINBOND_SWLINUX__
#		undef XTE_PLATFORM_SWLINUX
#		define XTE_PLATFORM_SWLINUX 1
#	endif
#
#	ifdef __TELESTRAT__
#		undef XTE_PLATFORM_TELESTRAT
#		define XTE_PLATFORM_TELESTRAT 1
#	endif
#
#	ifdef __THREADX__
#		undef XTE_PLATFORM_THREADX
#		define XTE_PLATFORM_THREADX 1
#	endif
#
#	if defined(_tru64) \
		|| defined(__OSF__) \
		|| defined(__TRU64__) \
		|| defined(__osf) \
		|| defined(__osf__) \
		|| defined(__tru64)
#		undef XTE_PLATFORM_TRU64
#		define XTE_PLATFORM_TRU64 1
#	endif
#
#	if (defined(__APPLE__) && defined(TARGET_OS_TV)) \
		|| defined(__ENVIRONMENT_TV_OS_VERSION_MIN_REQUIRED__) \
		|| defined(__TV_OS_VERSION_MIN_REQUIRED)
#		undef XTE_PLATFORM_TV_OS
#		define XTE_PLATFORM_TV_OS 1
#
#		undef XTE_PLATFORM_TV_OS_MAJOR
#		undef XTE_PLATFORM_TV_OS_MINOR
#		undef XTE_PLATFORM_TV_OS_PATCH
#		ifdef __TV_OS_VERSION_MIN_REQUIRED
#			define XTE_PLATFORM_TV_OS_MAJOR (__TV_OS_VERSION_MIN_REQUIRED / 10000)
#			define XTE_PLATFORM_TV_OS_MINOR (__TV_OS_VERSION_MIN_REQUIRED % 10000 / 100)
#			define XTE_PLATFORM_TV_OS_PATCH (__TV_OS_VERSION_MIN_REQUIRED % 100)
#		else
#			define XTE_PLATFORM_TV_OS_MAJOR (__ENVIRONMENT_TV_OS_VERSION_MIN_REQUIRED__ / 10000)
#			define XTE_PLATFORM_TV_OS_MINOR (__ENVIRONMENT_TV_OS_VERSION_MIN_REQUIRED__ % 10000 / 100)
#			define XTE_PLATFORM_TV_OS_PATCH (__ENVIRONMENT_TV_OS_VERSION_MIN_REQUIRED__ % 100)
#		endif
#	endif
#
#	ifdef __UCOSII__
#		undef XTE_PLATFORM_UC_OS_II
#		define XTE_PLATFORM_UC_OS_II 1
#	endif
#
#	ifdef __uClinux__
#		undef XTE_PLATFORM_UCLINUX
#		define XTE_PLATFORM_UCLINUX 1
#	endif
#
#	if defined(_ULTRIX) \
		|| defined(__ultrix) \
		|| defined(__ultrix__) \
		|| defined(ultrix) \
		|| (defined(unix) && defined(vax))
#		undef XTE_PLATFORM_ULTRIX
#		define XTE_PLATFORM_ULTRIX 1
#	endif
#
#	ifdef _UNICOS
#		undef XTE_PLATFORM_UNICOS
#		define XTE_PLATFORM_UNICOS 1
#
#		undef XTE_PLATFORM_UNICOS_MAJOR
#		define XTE_PLATFORM_UNICOS_MAJOR _UNICOS
#	endif
#
#	if defined(_CRAY) || defined(_UNICOSMP) || defined(__crayx1)
#		undef XTE_PLATFORM_UNICOS_MP
#		define XTE_PLATFORM_UNICOS_MP 1
#	endif
#
#	if defined(_POSIX_SOURCE) \
		|| defined(_XOPEN_SOURCE) \
		|| defined(__unix) \
		|| defined(__unix__) \
		|| defined(unix)
#		undef XTE_PLATFORM_UNIX
#		define XTE_PLATFORM_UNIX 1
#	endif
#
#	ifdef __UNIX_SV__
#		undef XTE_PLATFORM_UNIX_SV
#		define XTE_PLATFORM_UNIX_SV 1
#	endif
#
#	if defined(_UNIXWARE7) || defined(sco)
#		undef XTE_PLATFORM_UNIXWARE
#		define XTE_PLATFORM_UNIXWARE 1
#
#		ifdef _UNIXWARE7
#			undef XTE_PLATFORM_UNIXWARE_MAJOR
#			define XTE_PLATFORM_UNIXWARE_MAJOR 7
#		endif
#	endif
#
#	ifdef UTS
#		undef XTE_PLATFORM_UTS
#		define XTE_PLATFORM_UTS 1
#	endif
#
#	ifdef _UWIN
#		undef XTE_PLATFORM_UWIN
#		define XTE_PLATFORM_UWIN 1
#	endif
#
#	if defined(VMS) \
		|| defined(__VMS) \
		|| defined(__VMS__) \
		|| defined(__vms) \
		|| defined(__vms__)
#		undef XTE_PLATFORM_VMS
#		define XTE_PLATFORM_VMS 1
#
#		undef XTE_PLATFORM_VMS_MAJOR
#		define XTE_PLATFORM_VMS_MAJOR (__VMS_VER / 10000000)
#
#		undef XTE_PLATFORM_VMS_MINOR
#		define XTE_PLATFORM_VMS_MINOR (__VMS_VER / 100000 % 100)
#
#		undef XTE_PLATFORM_VMS_PATCH
#		define XTE_PLATFORM_VMS_PATCH (__VMS_VER / 100 % 100)
#	endif
#
#	ifdef __VOS__
#		undef XTE_PLATFORM_VOS
#		define XTE_PLATFORM_VOS 1
#
#		undef XTE_PALTFORM_VERSION_MAJOR_VOS
#		define XTE_PLATFORM_VOS_MAJOR __VOS__
#	endif
#
#	if defined(__VXWORKS__) || defined(__vxworks)
#		include <version.h>
#
#		undef XTE_PLATFORM_VXWORKS
#		define XTE_PLATFORM_VXWORKS 1
#
#		undef XTE_PLATFORM_VXWORKS_MAJOR
#		define XTE_PLATFORM_VXWORKS_MAJOR _WRS_VXWORKS_MAJOR
#
#		undef XTE_PLATFORM_VXWORKS_MINOR
#		define XTE_PLATFORM_VXWORKS_MINOR _WRS_VXWORKS_MINOR
#
#		undef XTE_PLATFORM_VXWORKS_PATCH
#		define XTE_PLATFORM_VXWORKS_PATCH _WRS_VXWORKS_MAINT
#	endif
#
#	if defined(__ENVIRONMENT_VISION_OS_VERSION_MIN_REQUIRED__) \
		|| defined(__VISION_OS_VERSION_MIN_REQUIRED)
#		undef XTE_PLATFORM_VISION_OS
#		define XTE_PLATFORM_VISION_OS 1
#
#		undef XTE_PLATFORM_VISION_OS_MAJOR
#		undef XTE_PLATFORM_VISION_OS_MINOR
#		undef XTE_PLATFORM_VISION_OS_PATCH
#		ifdef __VISION_OS_VERSION_MIN_REQUIRED
#			define XTE_PLATFORM_VISION_OS_MAJOR (__VISION_OS_VERSION_MIN_REQUIRED / 10000)
#			define XTE_PLATFORM_VISION_OS_MINOR (__VISION_OS_VERSION_MIN_REQUIRED % 10000 / 100)
#			define XTE_PLATFORM_VISION_OS_PATCH (__VISION_OS_VERSION_MIN_REQUIRED % 100)
#		else
#			define XTE_PLATFORM_VISION_OS_MAJOR (__ENVIRONMENT_VISION_OS_VERSION_MIN_REQUIRED__ / 10000)
#			define XTE_PLATFORM_VISION_OS_MINOR (__ENVIRONMENT_VISION_OS_VERSION_MIN_REQUIRED__ % 10000 / 100)
#			define XTE_PLATFORM_VISION_OS_PATCH (__ENVIRONMENT_VISION_OS_VERSION_MIN_REQUIRED__ % 100)
#		endif
#	endif
#
#	ifdef __wasi__
#		undef XTE_PLATFORM_WASI
#		define XTE_PLATFORM_WASI 1
#	endif
#
#	if (defined(__APPLE__) && defined(TARGET_OS_WATCH)) \
		|| defined(__ENVIRONMENT_WATCH_OS_VERSION_MIN_REQUIRED__) \
		|| defined(__WATCH_OS_VERSION_MIN_REQUIRED)
#		undef XTE_PLATFORM_WATCH_OS
#		define XTE_PLATFORM_WATCH_OS 1
#
#		undef XTE_PLATFORM_WATCH_OS_MAJOR
#		undef XTE_PLATFORM_WATCH_OS_MINOR
#		undef XTE_PLATFORM_WATCH_OS_PATCH
#		ifdef __WATCH_OS_VERSION_MIN_REQUIRED
#			define XTE_PLATFORM_WATCH_OS_MAJOR (__WATCH_OS_VERSION_MIN_REQUIRED / 10000)
#			define XTE_PLATFORM_WATCH_OS_MINOR (__WATCH_OS_VERSION_MIN_REQUIRED % 10000 / 100)
#			define XTE_PLATFORM_WATCH_OS_PATCH (__WATCH_OS_VERSION_MIN_REQUIRED % 100)
#		else
#			define XTE_PLATFORM_WATCH_OS_MAJOR (__ENVIRONMENT_WATCH_OS_VERSION_MIN_REQUIRED__ / 10000)
#			define XTE_PLATFORM_WATCH_OS_MINOR (__ENVIRONMENT_WATCH_OS_VERSION_MIN_REQUIRED__ % 10000 / 100)
#			define XTE_PLATFORM_WATCH_OS_PATCH (__ENVIRONMENT_WATCH_OS_VERSION_MIN_REQUIRED__ % 100)
#		endif
#	endif
#
#	if defined(WIN16) \
		|| defined(WIN32) \
		|| defined(WIN64) \
		|| defined(_WIN16) \
		|| defined(_WIN32) \
		|| defined(_WIN64) \
		|| defined(__TOS_WIN__) \
		|| defined(__WIN16) \
		|| defined(__WIN16__) \
		|| defined(__WIN32) \
		|| defined(__WIN32__) \
		|| defined(__WIN64) \
		|| defined(__WIN64__) \
		|| defined(__WINDOWS__)
#		undef XTE_PLATFORM_WINDOWS
#		define XTE_PLATFORM_WINDOWS 1
#	endif
#
#	ifdef _WIN32_WCE
#		undef XTE_PLATFORM_WINDOWS_CE
#		define XTE_PLATFORM_WINDOWS_CE 1
#
#		undef XTE_PLATFORM_WINDOWS_CE_MAJOR
#		define XTE_PLATFORM_WINDOWS_CE_MAJOR (_WIN32_WCE / 100)
#
#		undef XTE_PLATFORM_WINDOWS_CE_MINOR
#		define XTE_PLATFORM_WINDOWS_CE_MINOR (_WIN32_WCE % 100)
#	endif
#
#	if defined(WINAPI_FAMILY) \
		&& defined(WINAPI_FAMILY_DESKTOP_APP) \
		&& (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)
#		undef XTE_PLATFORM_WINDOWS_DESKTOP
#		define XTE_PLATFORM_WINDOWS_DESKTOP 1
#	endif
#
#	ifdef _GAMING_DESKTOP
#		undef XTE_PLATFORM_WINDOWS_GDK
#		define XTE_PLATFORM_WINDOWS_GDK 1
#	endif
#
#	if defined(__WINNT__) || defined(__NT__)
#		undef XTE_PLATFORM_WINDOWS_NT
#		define XTE_PLATFORM_WINDOWS_NT 1
#	endif
#
#	if defined(WINAPI_FAMILY) \
		&& defined(WINAPI_FAMILY_PHONE_APP) \
		&& (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)
#		undef XTE_PLATFORM_WINDOWS_PHONE
#		define XTE_PLATFORM_WINDOWS_PHONE 1
#	endif
#
#	if defined(WINAPI_FAMILY) \
		&& defined(WINAPI_FAMILY_SERVER) \
		&& (WINAPI_FAMILY == WINAPI_FAMILY_SERVER)
#		undef XTE_PLATFORM_WINDOWS_SERVER
#		define XTE_PLATFORM_WINDOWS_SERVER 1
#	endif
#
#	if defined(WINAPI_FAMILY) \
		&& (defined(WINAPI_FAMILY_APP) || defined(WINAPI_FAMILY_PC_APP)) \
		&& ((WINAPI_FAMILY == WINAPI_FAMILY_APP) || (WINAPI_FAMILY == WINAPI_FAMILY_PC_APP))
#		undef XTE_PLATFORM_WINDOWS_STORE
#		define XTE_PLATFORM_WINDOWS_STORE 1
#	endif
#
#	if defined(WINAPI_FAMILY) \
		&& defined(WINAPI_FAMILY_SYSTEM) \
		&& (WINAPI_FAMILY == WINAPI_FAMILY_SYSTEM)
#		undef XTE_PLATFORM_WINDOWS_SYSTEM
#		define XTE_PLATFORM_WINDOWS_SYSTEM 1
#	endif
#
#	ifdef _WINDU_SOURCE
#		undef XTE_PLATFORM_WIND_U
#		define XTE_PLATFORM_WIND_U 1
#
#		undef XTE_PLATFORM_WIND_U_MAJOR
#		define XTE_PLATFORM_WIND_U_MAJOR (_WINDU_SOURCE / 0x10000)
#
#		undef XTE_PLATFORM_WIND_U_MINOR
#		define XTE_PLATFORM_WIND_U_MINOR (_WINDU_SOURCE / 0x100 % 0x100)
#
#		undef XTE_PLATFORM_WIND_U_PATCH
#		define XTE_PLATFORM_WIND_U_PATCH (_WINDU_SOURCE % 0x100)
#	endif
#
#	ifdef _XBOX_VER
#		undef XTE_PLATFORM_XBOX
#		define XTE_PLATFORM_XBOX 1
#	endif
#
#	if _XBOX_VER >= 200
#		undef XTE_PLATFORM_XBOX_360
#		define XTE_PLATFORM_XBOX_360 1
#	endif
#
#	if defined(_DURANGO) || defined(_GAMING_XBOX_XBOXONE) || defined(_XBOX_ONE)
#		undef XTE_PLATFORM_XBOX_ONE
#		define XTE_PLATFORM_XBOX_ONE 1
#	endif
#
#	ifdef _GAMING_XBOX_SCARLETT
#		undef XTE_PLATFORM_XBOX_SERIES
#		define XTE_PLATFORM_XBOX_SERIES 1
#	endif
#
#	if defined(M_XENIX) \
		|| defined(XENIX) \
		|| defined(_XENIX) \
		|| defined(__XENIX__)
#		undef XTE_PLATFORM_XENIX
#		define XTE_PLATFORM_XENIX 1
#	endif
#
#	if defined(__HOS_MVS__) || defined(__MVS__) || defined(__TOS_MVS__)
#		undef XTE_PLATFORM_Z
#		define XTE_PLATFORM_Z 1
#	endif
#
#	ifdef __ZEPHYR__
#		undef XTE_PLATFORM_ZEPHYR
#		define XTE_PLATFORM_ZEPHYR 1
#	endif
#
#	ifdef __ZETA__
#		undef XTE_PLATFORM_ZETA
#		define XTE_PLATFORM_ZETA 1
#	endif
#
#	define DETAIL_XTE_PLATFORM(_operator, _major0, _minor0, _patch0, _major1, _minor1, _patch1, ...) \
		(((((0 _operator 0) && !(0 _operator 1) && !(1 _operator 0)) \
			|| (!(0 _operator 0) && (0 _operator 1) && (1 _operator 0))) \
		&& (((_major0) _operator (_major1)) \
			&& ((_minor0) _operator (_minor1)) \
			&& ((_patch0) _operator (_patch1)))) \
		|| ((_major0) _operator (_major1)) \
			|| (((_major0) == (_major1)) && ((_minor0) _operator (_minor1))) \
			|| (((_minor0) == (_minor1)) && ((_patch0) _operator (_patch1))))
#endif

// https://github.com/cpredef/predef/blob/master/OperatingSystems.md
// https://cc65.github.io/doc/cc65.html#s6
// Thanks to Ian Pike (https://github.com/Rinzii) for some detection macros
