#ifndef DETAIL_XTE_HEADER_PREPROC_UNWRAP
#	define DETAIL_XTE_HEADER_PREPROC_UNWRAP
#
#	include "../preproc/cat.hpp"
#
#	define XTE_UNWRAP(...) XTE_CAT(DETAIL_XTE_UNWRAP, DETAIL_XTE_UNWRAP __VA_ARGS__)
#
#	define DETAIL_XTE_UNWRAP(...) DETAIL_XTE_UNWRAP __VA_ARGS__
#	define DETAIL_XTE_UNWRAPDETAIL_XTE_UNWRAP
#endif
