#ifndef DETAIL_XTE_HEADER_PREPROC_VERSION
#	define DETAIL_XTE_HEADER_PREPROC_VERSION
#
#	define XTE_VERSION_MAJOR 0
#	define XTE_VERSION_MINOR 207
#	define XTE_VERSION_PATCH 0
#
#	define XTE_VERSION(OP, MAJOR, ...) DETAIL_XTE_VERSION(OP, MAJOR, __VA_ARGS__ __VA_OPT__(,) 0, 0)
#
#	define DETAIL_XTE_VERSION(OP, MAJOR, MINOR, PATCH, ...) \
		(((((0 OP 0) && !(0 OP 1) && !(1 OP 0)) \
			|| (!(0 OP 0) && (0 OP 1) && (1 OP 0))) \
		&& (((XTE_VERSION_MAJOR) OP (MAJOR)) \
			&& ((XTE_VERSION_MINOR) OP (MINOR)) \
			&& ((XTE_VERSION_PATCH) OP (PATCH)))) \
		|| ((XTE_VERSION_MAJOR) OP (MAJOR)) \
			|| (((XTE_VERSION_MAJOR) == (MAJOR)) && ((XTE_VERSION_MINOR) OP (MINOR))) \
			|| (((XTE_VERSION_MINOR) == (MINOR)) && ((XTE_VERSION_PATCH) OP (PATCH))))
#endif
