#ifndef DETAIL_XTE_HEADER_PREPROC_WRAPPED
#	define DETAIL_XTE_HEADER_PREPROC_WRAPPED
#
#	include "../preproc/cat.hpp"
#	include "../preproc/eat.hpp"
#
#	define XTE_WRAPPED(...) XTE_CAT(DETAIL_XTE_WRAPPED_, DETAIL_XTE_WRAPPED __VA_ARGS__))
#
#	define DETAIL_XTE_WRAPPED(...) DETAIL_XTE_WRAPPED_
#	define DETAIL_XTE_WRAPPED_DETAIL_XTE_WRAPPED 0 XTE_EAT(
#	define DETAIL_XTE_WRAPPED_DETAIL_XTE_WRAPPED_ 1 XTE_EAT(
#endif
