#ifndef XIEITE_HEADER_MACROS_COMPILER_TYPE
#	define XIEITE_HEADER_MACROS_COMPILER_TYPE

#	define XIEITE_COMPILER_TYPE_ACC 0
#	define XIEITE_COMPILER_TYPE_ACK 0
#	define XIEITE_COMPILER_TYPE_ALTIUM_C_TO_HARDWARE 0
#	define XIEITE_COMPILER_TYPE_ALTIUM_MICROBLAZE_C 0
#	define XIEITE_COMPILER_TYPE_ARMCC 0
#	define XIEITE_COMPILER_TYPE_AZTEC_C 0
#	define XIEITE_COMPILER_TYPE_CC65 0
#	define XIEITE_COMPILER_TYPE_CIRCLE 0
#	define XIEITE_COMPILER_TYPE_CLANG 0
#	define XIEITE_COMPILER_TYPE_CODEWARRIOR 0
#	define XIEITE_COMPILER_TYPE_COMEAU_C_CPP 0
#	define XIEITE_COMPILER_TYPE_COMPAQ_C 0
#	define XIEITE_COMPILER_TYPE_COMPAQ_CPP 0
#	define XIEITE_COMPILER_TYPE_COMPCERT 0
#	define XIEITE_COMPILER_TYPE_CONVEX_C 0
#	define XIEITE_COMPILER_TYPE_COVERITY_C_CPP_STATIC_ANALYZER 0
#	define XIEITE_COMPILER_TYPE_CPPBUILDER 0
#	define XIEITE_COMPILER_TYPE_CRAY_C_CPP 0
#	define XIEITE_COMPILER_TYPE_DATALIGHT_C 0
#	define XIEITE_COMPILER_TYPE_DICE_C 0
#	define XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_CPP 0
#	define XIEITE_COMPILER_TYPE_DJGPP 0
#	define XIEITE_COMPILER_TYPE_ECCP 0
#	define XIEITE_COMPILER_TYPE_EKOPATH 0
#	define XIEITE_COMPILER_TYPE_ELLCC 0
#	define XIEITE_COMPILER_TYPE_EMSCRIPTEN 0
#	define XIEITE_COMPILER_TYPE_FUJITSU_CPP 0
#	define XIEITE_COMPILER_TYPE_GCC 0
#	define XIEITE_COMPILER_TYPE_GREEN_HILLS_C_CPP 0
#	define XIEITE_COMPILER_TYPE_HP_ACPP 0
#	define XIEITE_COMPILER_TYPE_HP_ANSI_C 0
#	define XIEITE_COMPILER_TYPE_IAR_C_CPP_COMPILER 0
#	define XIEITE_COMPILER_TYPE_ICC 0
#	define XIEITE_COMPILER_TYPE_ICX 0
#	define XIEITE_COMPILER_TYPE_IMAGECRAFT_C 0
#	define XIEITE_COMPILER_TYPE_KCC 0
#	define XIEITE_COMPILER_TYPE_KEIL_C166 0
#	define XIEITE_COMPILER_TYPE_KEIL_C51 0
#	define XIEITE_COMPILER_TYPE_KEIL_CARM 0
#	define XIEITE_COMPILER_TYPE_LATTICE_C 0
#	define XIEITE_COMPILER_TYPE_LCC 0
#	define XIEITE_COMPILER_TYPE_LIGHTSPEED_C 0
#	define XIEITE_COMPILER_TYPE_LLVM 0
#	define XIEITE_COMPILER_TYPE_METAWARE_HIGH_C_CPP 0
#	define XIEITE_COMPILER_TYPE_MICROTEC_C_CPP 0
#	define XIEITE_COMPILER_TYPE_MICROWAY_NDP_C 0
#	define XIEITE_COMPILER_TYPE_MINGW32 0
#	define XIEITE_COMPILER_TYPE_MINGW_W64 0
#	define XIEITE_COMPILER_TYPE_MIPSPRO 0
#	define XIEITE_COMPILER_TYPE_MIRACLE_C 0
#	define XIEITE_COMPILER_TYPE_MPW 0
#	define XIEITE_COMPILER_TYPE_MSVC 0
#	define XIEITE_COMPILER_TYPE_NORCROFT_C 0
#	define XIEITE_COMPILER_TYPE_NVIDIA_HPC 0
#	define XIEITE_COMPILER_TYPE_NWCC 0
#	define XIEITE_COMPILER_TYPE_OPEN64 0
#	define XIEITE_COMPILER_TYPE_OPENSERVER 0
#	define XIEITE_COMPILER_TYPE_PACIFIC_C 0
#	define XIEITE_COMPILER_TYPE_PALM_C_CPP 0
#	define XIEITE_COMPILER_TYPE_PELLES_C 0
#	define XIEITE_COMPILER_TYPE_PGI_C_CPP 0
#	define XIEITE_COMPILER_TYPE_PRO_C 0
#	define XIEITE_COMPILER_TYPE_RENESAS_C_CPP 0
#	define XIEITE_COMPILER_TYPE_SDCC 0
#	define XIEITE_COMPILER_TYPE_SNC_COMPILER 0
#	define XIEITE_COMPILER_TYPE_STRATUS_VOS_C 0
#	define XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS_C 0
#	define XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS_CPP 0
#	define XIEITE_COMPILER_TYPE_SYMANTEC_CPP 0
#	define XIEITE_COMPILER_TYPE_TCC 0
#	define XIEITE_COMPILER_TYPE_TENDRA 0
#	define XIEITE_COMPILER_TYPE_TI_CGT 0
#	define XIEITE_COMPILER_TYPE_TURBO_C_CPP 0
#	define XIEITE_COMPILER_TYPE_ULTIMATE_C_CPP 0
#	define XIEITE_COMPILER_TYPE_USL_C 0
#	define XIEITE_COMPILER_TYPE_VBCC 0
#	define XIEITE_COMPILER_TYPE_WATCOM_C_CPP 0
#	define XIEITE_COMPILER_TYPE_WIND_RIVER_DIAB_COMPILER 0
#	define XIEITE_COMPILER_TYPE_XL_C_CPP 0
#	define XIEITE_COMPILER_TYPE_ZORTECH_CPP 0

#	define XIEITE_COMPILER_VERSION_MAJOR_ACC 0
#	define XIEITE_COMPILER_VERSION_MINOR_ACC 0
#	define XIEITE_COMPILER_VERSION_PATCH_ACC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ACK 0
#	define XIEITE_COMPILER_VERSION_MINOR_ACK 0
#	define XIEITE_COMPILER_VERSION_PATCH_ACK 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ALTIUM_C_TO_HARDWARE 0
#	define XIEITE_COMPILER_VERSION_MINOR_ALTIUM_C_TO_HARDWARE 0
#	define XIEITE_COMPILER_VERSION_PATCH_ALTIUM_C_TO_HARDWARE 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ALTIUM_MICROBLAZE_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_ALTIUM_MICROBLAZE_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_ALTIUM_MICROBLAZE_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ARMCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_ARMCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_ARMCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_AZTEC_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_AZTEC_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_AZTEC_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_CC65 0
#	define XIEITE_COMPILER_VERSION_MINOR_CC65 0
#	define XIEITE_COMPILER_VERSION_PATCH_CC65 0
#	define XIEITE_COMPILER_VERSION_MAJOR_CIRCLE 0
#	define XIEITE_COMPILER_VERSION_MINOR_CIRCLE 0
#	define XIEITE_COMPILER_VERSION_PATCH_CIRCLE 0
#	define XIEITE_COMPILER_VERSION_MAJOR_CLANG 0
#	define XIEITE_COMPILER_VERSION_MINOR_CLANG 0
#	define XIEITE_COMPILER_VERSION_PATCH_CLANG 0
#	define XIEITE_COMPILER_VERSION_MAJOR_CODEWARRIOR 0
#	define XIEITE_COMPILER_VERSION_MINOR_CODEWARRIOR 0
#	define XIEITE_COMPILER_VERSION_PATCH_CODEWARRIOR 0
#	define XIEITE_COMPILER_VERSION_MAJOR_COMEAU_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_COMEAU_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_COMEAU_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_COMPAQ_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_COMPAQ_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_COMPAQ_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_COMPAQ_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_COMPAQ_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_COMPAQ_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_COMPCERT 0
#	define XIEITE_COMPILER_VERSION_MINOR_COMPCERT 0
#	define XIEITE_COMPILER_VERSION_PATCH_COMPCERT 0
#	define XIEITE_COMPILER_VERSION_MAJOR_CONVEX_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_CONVEX_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_CONVEX_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_COVERITY_C_CPP_STATIC_ANALYZER 0
#	define XIEITE_COMPILER_VERSION_MINOR_COVERITY_C_CPP_STATIC_ANALYZER 0
#	define XIEITE_COMPILER_VERSION_PATCH_COVERITY_C_CPP_STATIC_ANALYZER 0
#	define XIEITE_COMPILER_VERSION_MAJOR_CPPBUILDER 0
#	define XIEITE_COMPILER_VERSION_MINOR_CPPBUILDER 0
#	define XIEITE_COMPILER_VERSION_PATCH_CPPBUILDER 0
#	define XIEITE_COMPILER_VERSION_MAJOR_CRAY_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_CRAY_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_CRAY_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_DATALIGHT_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_DATALIGHT_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_DATALIGHT_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_DICE_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_DICE_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_DICE_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_DIGNUS_SYSTEMS_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_DIGNUS_SYSTEMS_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_DIGNUS_SYSTEMS_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_DJGPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_DJGPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_DJGPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ECCP 0
#	define XIEITE_COMPILER_VERSION_MINOR_ECCP 0
#	define XIEITE_COMPILER_VERSION_PATCH_ECCP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_EKOPATH 0
#	define XIEITE_COMPILER_VERSION_MINOR_EKOPATH 0
#	define XIEITE_COMPILER_VERSION_PATCH_EKOPATH 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ELLCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_ELLCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_ELLCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_EMSCRIPTEN 0
#	define XIEITE_COMPILER_VERSION_MINOR_EMSCRIPTEN 0
#	define XIEITE_COMPILER_VERSION_PATCH_EMSCRIPTEN 0
#	define XIEITE_COMPILER_VERSION_MAJOR_FUJITSU_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_FUJITSU_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_FUJITSU_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_GCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_GCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_GCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_GREEN_HILLS_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_GREEN_HILLS_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_GREEN_HILLS_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_HP_ACPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_HP_ACPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_HP_ACPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_HP_ANSI_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_HP_ANSI_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_HP_ANSI_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_IAR_C_CPP_COMPILER 0
#	define XIEITE_COMPILER_VERSION_MINOR_IAR_C_CPP_COMPILER 0
#	define XIEITE_COMPILER_VERSION_PATCH_IAR_C_CPP_COMPILER 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ICC 0
#	define XIEITE_COMPILER_VERSION_MINOR_ICC 0
#	define XIEITE_COMPILER_VERSION_PATCH_ICC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ICX 0
#	define XIEITE_COMPILER_VERSION_MINOR_ICX 0
#	define XIEITE_COMPILER_VERSION_PATCH_ICX 0
#	define XIEITE_COMPILER_VERSION_MAJOR_IMAGECRAFT_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_IMAGECRAFT_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_IMAGECRAFT_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_KCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_KCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_KCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_KEIL_C166 0
#	define XIEITE_COMPILER_VERSION_MINOR_KEIL_C166 0
#	define XIEITE_COMPILER_VERSION_PATCH_KEIL_C166 0
#	define XIEITE_COMPILER_VERSION_MAJOR_KEIL_C51 0
#	define XIEITE_COMPILER_VERSION_MINOR_KEIL_C51 0
#	define XIEITE_COMPILER_VERSION_PATCH_KEIL_C51 0
#	define XIEITE_COMPILER_VERSION_MAJOR_KEIL_CARM 0
#	define XIEITE_COMPILER_VERSION_MINOR_KEIL_CARM 0
#	define XIEITE_COMPILER_VERSION_PATCH_KEIL_CARM 0
#	define XIEITE_COMPILER_VERSION_MAJOR_LATTICE_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_LATTICE_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_LATTICE_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_LCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_LCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_LCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_LIGHTSPEED_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_LIGHTSPEED_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_LIGHTSPEED_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_LLVM 0
#	define XIEITE_COMPILER_VERSION_MINOR_LLVM 0
#	define XIEITE_COMPILER_VERSION_PATCH_LLVM 0
#	define XIEITE_COMPILER_VERSION_MAJOR_METAWARE_HIGH_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_METAWARE_HIGH_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_METAWARE_HIGH_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MICROTEC_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_MICROTEC_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_MICROTEC_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MICROWAY_NDP_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_MICROWAY_NDP_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_MICROWAY_NDP_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MINGW32 0
#	define XIEITE_COMPILER_VERSION_MINOR_MINGW32 0
#	define XIEITE_COMPILER_VERSION_PATCH_MINGW32 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MINGW_W64 0
#	define XIEITE_COMPILER_VERSION_MINOR_MINGW_W64 0
#	define XIEITE_COMPILER_VERSION_PATCH_MINGW_W64 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MIPSPRO 0
#	define XIEITE_COMPILER_VERSION_MINOR_MIPSPRO 0
#	define XIEITE_COMPILER_VERSION_PATCH_MIPSPRO 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MIRACLE_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_MIRACLE_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_MIRACLE_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MPW 0
#	define XIEITE_COMPILER_VERSION_MINOR_MPW 0
#	define XIEITE_COMPILER_VERSION_PATCH_MPW 0
#	define XIEITE_COMPILER_VERSION_MAJOR_MSVC 0
#	define XIEITE_COMPILER_VERSION_MINOR_MSVC 0
#	define XIEITE_COMPILER_VERSION_PATCH_MSVC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_NORCROFT_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_NORCROFT_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_NORCROFT_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_NVIDIA_HPC 0
#	define XIEITE_COMPILER_VERSION_MINOR_NVIDIA_HPC 0
#	define XIEITE_COMPILER_VERSION_PATCH_NVIDIA_HPC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_NWCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_NWCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_NWCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_OPEN64 0
#	define XIEITE_COMPILER_VERSION_MINOR_OPEN64 0
#	define XIEITE_COMPILER_VERSION_PATCH_OPEN64 0
#	define XIEITE_COMPILER_VERSION_MAJOR_OPENSERVER 0
#	define XIEITE_COMPILER_VERSION_MINOR_OPENSERVER 0
#	define XIEITE_COMPILER_VERSION_PATCH_OPENSERVER 0
#	define XIEITE_COMPILER_VERSION_MAJOR_PACIFIC_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_PACIFIC_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_PACIFIC_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_PALM_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_PALM_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_PALM_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_PELLES_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_PELLES_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_PELLES_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_PGI_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_PGI_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_PGI_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_PRO_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_PRO_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_PRO_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_RENESAS_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_RENESAS_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_RENESAS_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_SDCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_SDCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_SDCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_SNC_COMPILER 0
#	define XIEITE_COMPILER_VERSION_MINOR_SNC_COMPILER 0
#	define XIEITE_COMPILER_VERSION_PATCH_SNC_COMPILER 0
#	define XIEITE_COMPILER_VERSION_MAJOR_STRATUS_VOS_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_STRATUS_VOS_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_STRATUS_VOS_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_SUNPRO_COMPILERS_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_SUNPRO_COMPILERS_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_SUNPRO_COMPILERS_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_SUNPRO_COMPILERS_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_SUNPRO_COMPILERS_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_SUNPRO_COMPILERS_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_SYMANTEC_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_SYMANTEC_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_SYMANTEC_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_TCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_TCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_TCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_TENDRA 0
#	define XIEITE_COMPILER_VERSION_MINOR_TENDRA 0
#	define XIEITE_COMPILER_VERSION_PATCH_TENDRA 0
#	define XIEITE_COMPILER_VERSION_MAJOR_TI_CGT 0
#	define XIEITE_COMPILER_VERSION_MINOR_TI_CGT 0
#	define XIEITE_COMPILER_VERSION_PATCH_TI_CGT 0
#	define XIEITE_COMPILER_VERSION_MAJOR_TURBO_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_TURBO_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_TURBO_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ULTIMATE_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_ULTIMATE_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_ULTIMATE_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_USL_C 0
#	define XIEITE_COMPILER_VERSION_MINOR_USL_C 0
#	define XIEITE_COMPILER_VERSION_PATCH_USL_C 0
#	define XIEITE_COMPILER_VERSION_MAJOR_VBCC 0
#	define XIEITE_COMPILER_VERSION_MINOR_VBCC 0
#	define XIEITE_COMPILER_VERSION_PATCH_VBCC 0
#	define XIEITE_COMPILER_VERSION_MAJOR_WATCOM_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_WATCOM_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_WATCOM_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_WIND_RIVER_DIAB_COMPILER 0
#	define XIEITE_COMPILER_VERSION_MINOR_WIND_RIVER_DIAB_COMPILER 0
#	define XIEITE_COMPILER_VERSION_PATCH_WIND_RIVER_DIAB_COMPILER 0
#	define XIEITE_COMPILER_VERSION_MAJOR_XL_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_XL_C_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_XL_C_CPP 0
#	define XIEITE_COMPILER_VERSION_MAJOR_ZORTECH_CPP 0
#	define XIEITE_COMPILER_VERSION_MINOR_ZORTECH_CPP 0
#	define XIEITE_COMPILER_VERSION_PATCH_ZORTECH_CPP 0

#	define XIEITE_COMPILER_VERSION_LEAST(compiler, major, minor, patch) (XIEITE_COMPILER_TYPE_##compiler && ((XIEITE_COMPILER_VERSION_MAJOR_##compiler > (major)) || (XIEITE_COMPILER_VERSION_MAJOR_##compiler == (major)) && ((XIEITE_COMPILER_VERSION_MINOR_##compiler > (minor)) || (XIEITE_COMPILER_VERSION_MINOR_##compiler == (minor)) && (XIEITE_COMPILER_VERSION_PATCH_##compiler >= (patch)))))
#	define XIEITE_COMPILER_VERSION_MOST(compiler, major, minor, patch) (XIEITE_COMPILER_TYPE_##compiler && ((XIEITE_COMPILER_VERSION_MAJOR_##compiler < (major)) || (XIEITE_COMPILER_VERSION_MAJOR_##compiler == (major)) && ((XIEITE_COMPILER_VERSION_MINOR_##compiler < (minor)) || (XIEITE_COMPILER_VERSION_MINOR_##compiler == (minor)) && (XIEITE_COMPILER_VERSION_PATCH_##compiler <= (patch)))))

#	ifdef _ACC_
#		undef XIEITE_COMPILER_TYPE_ACC
#		define XIEITE_COMPILER_TYPE_ACC 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ACC
#		define XIEITE_COMPILER_VERSION_MAJOR_ACC (__HP_aCC / 10000)

#		undef XIEITE_COMPILER_VERSION_MINOR_ACC
#		define XIEITE_COMPILER_VERSION_MINOR_ACC (__HP_aCC % 10000 / 100)

#		undef XIEITE_COMPILER_VERSION_PATCH_ACC
#		define XIEITE_COMPILER_VERSION_PATCH_ACC (__HP_aCC % 100)
#	endif

#	ifdef __ACK__
#		undef XIEITE_COMPILER_TYPE_ACK
#		define XIEITE_COMPILER_TYPE_ACK 1
#	endif

#	ifdef __CHC__
#		undef XIEITE_COMPILER_TYPE_ALTIUM_C_TO_HARDWARE
#		define XIEITE_COMPILER_TYPE_ALTIUM_C_TO_HARDWARE 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ALTIUM_C_TO_HARDWARE
#		define XIEITE_COMPILER_VERSION_MAJOR_ALTIUM_C_TO_HARDWARE (__VERSION___ / 1000)

#		undef XIEITE_COMPILER_VERSION_MINOR_ALTIUM_C_TO_HARDWARE
#		define XIEITE_COMPILER_VERSION_MINOR_ALTIUM_C_TO_HARDWARE (__VERSION___ % 1000)

#		undef XIEITE_COMPILER_VERSION_PATCH_ALTIUM_C_TO_HARDWARE
#		define XIEITE_COMPILER_VERSION_PATCH_ALTIUM_C_TO_HARDWARE __REVISION__
#	endif

#	ifdef __CMB__
#		undef XIEITE_COMPILER_TYPE_ALTIUM_MICROBLAZE_C
#		define XIEITE_COMPILER_TYPE_ALTIUM_MICROBLAZE_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ALTIUM_MICROBLAZE_C
#		define XIEITE_COMPILER_VERSION_MAJOR_ALTIUM_MICROBLAZE_C (__VERSION___ / 1000)

#		undef XIEITE_COMPILER_VERSION_MINOR_ALTIUM_MICROBLAZE_C
#		define XIEITE_COMPILER_VERSION_MINOR_ALTIUM_MICROBLAZE_C (__VERSION___ % 1000)

#		undef XIEITE_COMPILER_VERSION_PATCH_ALTIUM_MICROBLAZE_C
#		define XIEITE_COMPILER_VERSION_PATCH_ALTIUM_MICROBLAZE_C __REVISION__
#	endif

#	ifdef __CC_ARM
#		undef XIEITE_COMPILER_TYPE_ARMCC
#		define XIEITE_COMPILER_TYPE_ARMCC 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ARMCC
#		define XIEITE_COMPILER_VERSION_MAJOR_ARMCC (__ARMCC_VERSION / 100000)

#		undef XIEITE_COMPILER_VERSION_MINOR_ARMCC
#		define XIEITE_COMPILER_VERSION_MINOR_ARMCC (__ARMCC_VERSION % 100000 / 10000)

#		undef XIEITE_COMPILER_VERSION_PATCH_ARMCC
#		define XIEITE_COMPILER_VERSION_PATCH_ARMCC (__ARMCC_VERSION % 10000 / 1000)
#	endif

#	ifdef AZTEC_C
#		undef XIEITE_COMPILER_TYPE_AZTEC_C
#		define XIEITE_COMPILER_TYPE_AZTEC_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_AZTEC_C
#		define XIEITE_COMPILER_VERSION_MAJOR_AZTEC_C (__VERSION / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_AZTEC_C
#		define XIEITE_COMPILER_VERSION_MINOR_AZTEC_C (__VERSION % 100)
#	endif

#	ifdef __CC65__
#		undef XIEITE_COMPILER_TYPE_CC65
#		define XIEITE_COMPILER_TYPE_CC65 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_CC65
#		define XIEITE_COMPILER_VERSION_MAJOR_CC65 (__CC65__ / 0x100)

#		undef XIEITE_COMPILER_VERSION_MINOR_CC65
#		define XIEITE_COMPILER_VERSION_MINOR_CC65 (__CC65__ % 0x100 / 0x10)

#		undef XIEITE_COMPILER_VERSION_PATCH_CC65
#		define XIEITE_COMPILER_VERSION_PATCH_CC65 (__CC65__ % 0x10)
#	endif

#	if defined(__circle__) || defined(__circle_lang__) || defined(__circle_build__)
#		undef XIEITE_COMPILER_TYPE_CIRCLE
#		define XIEITE_COMPILER_TYPE_CIRCLE 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_CIRCLE
#		define XIEITE_COMPILER_VERSION_MAJOR_CIRCLE (__circle__ / 10000)

#		undef XIEITE_COMPILER_VERSION_MINOR_CIRCLE
#		define XIEITE_COMPILER_VERSION_MINOR_CIRCLE (__circle__ % 10000 / 100)

#		undef XIEITE_COMPILER_VERSION_PATCH_CIRCLE
#		define XIEITE_COMPILER_VERSION_PATCH_CIRCLE (__circle__ % 100)
#	endif

#	ifdef __clang__
#		undef XIEITE_COMPILER_TYPE_CLANG
#		define XIEITE_COMPILER_TYPE_CLANG 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_CLANG
#		define XIEITE_COMPILER_VERSION_MAJOR_CLANG __clang_major__

#		undef XIEITE_COMPILER_VERSION_MINOR_CLANG
#		define XIEITE_COMPILER_VERSION_MINOR_CLANG __clang_minor__

#		undef XIEITE_COMPILER_VERSION_PATCH_CLANG
#		define XIEITE_COMPILER_VERSION_PATCH_CLANG __clang_patchlevel__
#	endif

#	if defined(__MWERKS__) || defined(__CWCC__)
#		undef XIEITE_COMPILER_TYPE_CODEWARRIOR
#		define XIEITE_COMPILER_TYPE_CODEWARRIOR 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_CODEWARRIOR
#		define XIEITE_COMPILER_VERSION_MAJOR_CODEWARRIOR (__MWERKS__ / 0x1000)

#		undef XIEITE_COMPILER_VERSION_MINOR_CODEWARRIOR
#		define XIEITE_COMPILER_VERSION_MINOR_CODEWARRIOR (__MWERKS__ % 0x1000 / 0x100)

#		undef XIEITE_COMPILER_VERSION_PATCH_CODEWARRIOR
#		define XIEITE_COMPILER_VERSION_PATCH_CODEWARRIOR (__MWERKS__ % 0x100)
#	endif

#	ifdef __COMO__
#		undef XIEITE_COMPILER_TYPE_COMEAU_C_CPP
#		define XIEITE_COMPILER_TYPE_COMEAU_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_COMEAU_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_COMEAU_C_CPP (__COMO_VERSION___ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_COMEAU_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_COMEAU_C_CPP (__COMO_VERSION___ % 100)
#	endif

#	ifdef __DECC
#		undef XIEITE_COMPILER_TYPE_COMPAQ_C
#		define XIEITE_COMPILER_TYPE_COMPAQ_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_COMPAQ_C
#		define XIEITE_COMPILER_VERSION_MAJOR_COMPAQ_C (__DECC_VER / 10000000)

#		undef XIEITE_COMPILER_VERSION_MINOR_COMPAQ_C
#		define XIEITE_COMPILER_VERSION_MINOR_COMPAQ_C (__DECC_VER % 10000000 / 100000)

#		undef XIEITE_COMPILER_VERSION_PATCH_COMPAQ_C
#		define XIEITE_COMPILER_VERSION_PATCH_COMPAQ_C (__DECC_VER % 10000)
#	endif

#	ifdef __DECCXX
#		undef XIEITE_COMPILER_TYPE_COMPAQ_CPP
#		define XIEITE_COMPILER_TYPE_COMPAQ_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_COMPAQ_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_COMPAQ_CPP (__DECCXX_VER / 10000000)

#		undef XIEITE_COMPILER_VERSION_MINOR_COMPAQ_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_COMPAQ_CPP (__DECCXX_VER % 10000000 / 100000)

#		undef XIEITE_COMPILER_VERSION_PATCH_COMPAQ_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_COMPAQ_CPP (__DECCXX_VER % 10000)
#	endif

#	ifdef __COMPCERT__
#		undef XIEITE_COMPILER_TYPE_COMPCERT
#		define XIEITE_COMPILER_TYPE_COMPCERT 1
#	endif

#	ifdef __convexc__
#		undef XIEITE_COMPILER_TYPE_CONVEX_C
#		define XIEITE_COMPILER_TYPE_CONVEX_C 1
#	endif

#	ifdef __COVERITY__
#		undef XIEITE_COMPILER_TYPE_COVERITY_C_CPP_STATIC_ANALYZER
#		define XIEITE_COMPILER_TYPE_COVERITY_C_CPP_STATIC_ANALYZER 1
#	endif

#	if defined(__BORLANDC__) || defined(__CODEGEARC__)
#		undef XIEITE_COMPILER_TYPE_CPPBUILDER
#		define XIEITE_COMPILER_TYPE_CPPBUILDER 1
#	endif

#	ifdef _CRAYC
#		undef XIEITE_COMPILER_TYPE_CRAY_C_CPP
#		define XIEITE_COMPILER_TYPE_CRAY_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_CRAY_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_CRAY_C_CPP _RELEASE

#		undef XIEITE_COMPILER_VERSION_MINOR_CRAY_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_CRAY_C_CPP _RELEASE_MINOR
#	endif

#	ifdef __DMC__
#		undef XIEITE_COMPILER_TYPE_DATALIGHT_C
#		define XIEITE_COMPILER_TYPE_DATALIGHT_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_DATALIGHT_C
#		define XIEITE_COMPILER_VERSION_MAJOR_DATALIGHT_C (__DMC__ / 0x100)

#		undef XIEITE_COMPILER_VERSION_MINOR_DATALIGHT_C
#		define XIEITE_COMPILER_VERSION_MINOR_DATALIGHT_C (__DMC__ % 0x100 / 0x10)

#		undef XIEITE_COMPILER_VERSION_PATCH_DATALIGHT_C
#		define XIEITE_COMPILER_VERSION_PATCH_DATALIGHT_C (__DMC__ % 0x10)
#	endif

#	ifdef _DICE
#		undef XIEITE_COMPILER_TYPE_DICE_C
#		define XIEITE_COMPILER_TYPE_DICE_C 1
#	endif

#	ifdef __SYSC__
#		undef XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_CPP
#		define XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_DIGNUS_SYSTEMS_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_DIGNUS_SYSTEMS_CPP (__SYSC_VER__ / 10000)

#		undef XIEITE_COMPILER_VERSION_MINOR_DIGNUS_SYSTEMS_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_DIGNUS_SYSTEMS_CPP (__SYSC_VER__ % 10000 / 100)

#		undef XIEITE_COMPILER_VERSION_PATCH_DIGNUS_SYSTEMS_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_DIGNUS_SYSTEMS_CPP (__SYSC_VER__ % 100)
#	endif

#	ifdef __DJGPP__
#		undef XIEITE_COMPILER_TYPE_DJGPP
#		define XIEITE_COMPILER_TYPE_DJGPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_DJGPP
#		define XIEITE_COMPILER_VERSION_MAJOR_DJGPP __DJGPP__

#		undef XIEITE_COMPILER_VERSION_MINOR_DJGPP
#		define XIEITE_COMPILER_VERSION_MINOR_DJGPP __DJGPP_MINOR__
#	endif

#	ifdef __EDG__
#		undef XIEITE_COMPILER_TYPE_ECCP
#		define XIEITE_COMPILER_TYPE_ECCP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ECCP
#		define XIEITE_COMPILER_VERSION_MAJOR_ECCP (__EDG_VERSION___ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_ECCP
#		define XIEITE_COMPILER_VERSION_MINOR_ECCP (__EDG_VERSION___ % 100)
#	endif

#	ifdef __PATHCC__
#		undef XIEITE_COMPILER_TYPE_EKOPATH
#		define XIEITE_COMPILER_TYPE_EKOPATH 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_EKOPATH
#		define XIEITE_COMPILER_VERSION_MAJOR_EKOPATH __PATHCC__

#		undef XIEITE_COMPILER_VERSION_MINOR_EKOPATH
#		define XIEITE_COMPILER_VERSION_MINOR_EKOPATH __PATHCC_MINOR__

#		undef XIEITE_COMPILER_VERSION_PATCH_EKOPATH
#		define XIEITE_COMPILER_VERSION_PATCH_EKOPATH __PATHCC_PATCHLEVEL__
#	endif

#	ifdef __ELLCC__
#		undef XIEITE_COMPILER_TYPE_ELLCC
#		define XIEITE_COMPILER_TYPE_ELLCC 1
#	endif

#	ifdef __EMSCRIPTEN__
#		undef XIEITE_COMPILER_TYPE_EMSCRIPTEN
#		define XIEITE_COMPILER_TYPE_EMSCRIPTEN 1
#	endif

#	ifdef __FCC_VERSION
#		undef XIEITE_COMPILER_TYPE_FUJITSU_CPP
#		define XIEITE_COMPILER_TYPE_FUJITSU_CPP 1
#	endif

#	ifdef __GNUC__
#		undef XIEITE_COMPILER_TYPE_GCC
#		define XIEITE_COMPILER_TYPE_GCC 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_GCC
#		define XIEITE_COMPILER_VERSION_MAJOR_GCC __GNUC__

#		undef XIEITE_COMPILER_VERSION_MINOR_GCC
#		define XIEITE_COMPILER_VERSION_MINOR_GCC __GNUC_MINOR__

#		undef XIEITE_COMPILER_VERSION_PATCH_GCC
#		define XIEITE_COMPILER_VERSION_PATCH_GCC __GNUC_PATCHLEVEL__
#	endif

#	ifdef __ghs__
#		undef XIEITE_COMPILER_TYPE_GREEN_HILLS_C_CPP
#		define XIEITE_COMPILER_TYPE_GREEN_HILLS_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_GREEN_HILLS_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_GREEN_HILLS_C_CPP (__GHS_VERSION_NUMBER__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_GREEN_HILLS_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_GREEN_HILLS_C_CPP (__GHS_VERSION_NUMBER__ % 100 / 10)

#		undef XIEITE_COMPILER_VERSION_PATCH_GREEN_HILLS_C_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_GREEN_HILLS_C_CPP (__GHS_VERSION_NUMBER__ % 10)
#	endif

#	ifdef __HP_aCC
#		undef XIEITE_COMPILER_TYPE_HP_ACPP
#		define XIEITE_COMPILER_TYPE_HP_ACPP 1
#	endif

#	ifdef __HP_cc
#		undef XIEITE_COMPILER_TYPE_HP_ANSI_C
#		define XIEITE_COMPILER_TYPE_HP_ANSI_C 1
#	endif

#	ifdef __IAR_SYSTEMS_ICC__
#		undef XIEITE_COMPILER_TYPE_IAR_C_CPP_COMPILER
#		define XIEITE_COMPILER_TYPE_IAR_C_CPP_COMPILER 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_IAR_C_CPP_COMPILER
#		define XIEITE_COMPILER_VERSION_MAJOR_IAR_C_CPP_COMPILER (__VER__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_IAR_C_CPP_COMPILER
#		define XIEITE_COMPILER_VERSION_MINOR_IAR_C_CPP_COMPILER (__VER__ % 100)
#	endif

#	if defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ECC) || defined(__ICL)
#		undef XIEITE_COMPILER_TYPE_ICC
#		define XIEITE_COMPILER_TYPE_ICC 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ICC
#		define XIEITE_COMPILER_VERSION_MAJOR_ICC (__INTEL_COMPILER / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_ICC
#		define XIEITE_COMPILER_VERSION_MINOR_ICC (__INTEL_COMPILER % 100 / 10)

#		undef XIEITE_COMPILER_VERSION_PATCH_ICC
#		define XIEITE_COMPILER_VERSION_PATCH_ICC (__INTEL_COMPILER % 10)
#	endif

#	if defined(__INTEL_CLANG_COMPILER)
#		undef XIEITE_COMPILER_TYPE_ICX
#		define XIEITE_COMPILER_TYPE_ICX 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ICX
#		define XIEITE_COMPILER_VERSION_MAJOR_ICX (__INTEL_CLANG_COMPILER / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_ICX
#		define XIEITE_COMPILER_VERSION_MINOR_ICX (__INTEL_CLANG_COMPILER % 100 / 10)

#		undef XIEITE_COMPILER_VERSION_PATCH_ICX
#		define XIEITE_COMPILER_VERSION_PATCH_ICX (__INTEL_CLANG_COMPILER % 10)
#	endif

#	ifdef __IMAGECRAFT__
#		undef XIEITE_COMPILER_TYPE_IMAGECRAFT_C
#		define XIEITE_COMPILER_TYPE_IMAGECRAFT_C 1
#	endif

#	ifdef __KCC
#		undef XIEITE_COMPILER_TYPE_KCC
#		define XIEITE_COMPILER_TYPE_KCC 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_KCC
#		define XIEITE_COMPILER_VERSION_MAJOR_KCC (__KCC_VERSION / 0x1000)

#		undef XIEITE_COMPILER_VERSION_MINOR_KCC
#		define XIEITE_COMPILER_VERSION_MINOR_KCC (__KCC_VERSION % 0x1000 / 0x100)

#		undef XIEITE_COMPILER_VERSION_PATCH_KCC
#		define XIEITE_COMPILER_VERSION_PATCH_KCC (__KCC_VERSION % 0x100)
#	endif

#	ifdef __C166__
#		undef XIEITE_COMPILER_TYPE_KEIL_C166
#		define XIEITE_COMPILER_TYPE_KEIL_C166 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_KEIL_C166
#		define XIEITE_COMPILER_VERSION_MAJOR_KEIL_C166 (__C166__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_KEIL_C166
#		define XIEITE_COMPILER_VERSION_MINOR_KEIL_C166 (__C166__ % 100)
#	endif

#	ifdef __C51__
#		undef XIEITE_COMPILER_TYPE_KEIL_C51
#		define XIEITE_COMPILER_TYPE_KEIL_C51 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_KEIL_C51
#		define XIEITE_COMPILER_VERSION_MAJOR_KEIL_C51 (__C51__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_KEIL_C51
#		define XIEITE_COMPILER_VERSION_MINOR_KEIL_C51 (__C51__ % 100)
#	endif

#	if defined(__CA__) || defined(__KEIL__)
#		undef XIEITE_COMPILER_TYPE_KEIL_CARM
#		define XIEITE_COMPILER_TYPE_KEIL_CARM 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_KEIL_CARM
#		define XIEITE_COMPILER_VERSION_MAJOR_KEIL_CARM (__CA__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_KEIL_CARM
#		define XIEITE_COMPILER_VERSION_MINOR_KEIL_CARM (__CA__ % 100)
#	endif

#	if defined(SASC) || defined(__SASC) || defined(__SASC__)
#		undef XIEITE_COMPILER_TYPE_LATTICE_C
#		define XIEITE_COMPILER_TYPE_LATTICE_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_LATTICE_C
#		define XIEITE_COMPILER_VERSION_MAJOR_LATTICE_C (__SASC__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_LATTICE_C
#		define XIEITE_COMPILER_VERSION_MINOR_LATTICE_C (__SASC__ % 100)
#	endif

#	ifdef __LCC__
#		undef XIEITE_COMPILER_TYPE_LCC
#		define XIEITE_COMPILER_TYPE_LCC 1
#	endif

#	if defined(THINKC3) || defined(THINKC4)
#		undef XIEITE_COMPILER_TYPE_LIGHTSPEED_C
#		define XIEITE_COMPILER_TYPE_LIGHTSPEED_C 1
#	endif

#	ifdef __llvm__
#		undef XIEITE_COMPILER_TYPE_LLVM
#		define XIEITE_COMPILER_TYPE_LLVM 1
#	endif

#	ifdef __HIGHC__
#		undef XIEITE_COMPILER_TYPE_METAWARE_HIGH_C_CPP
#		define XIEITE_COMPILER_TYPE_METAWARE_HIGH_C_CPP 1
#	endif

#	ifdef _MRI
#		undef XIEITE_COMPILER_TYPE_MICROTEC_C_CPP
#		define XIEITE_COMPILER_TYPE_MICROTEC_C_CPP 1
#	endif

#	if defined(__NDPC__) || defined(__NDPX__)
#		undef XIEITE_COMPILER_TYPE_MICROWAY_NDP_C
#		define XIEITE_COMPILER_TYPE_MICROWAY_NDP_C 1
#	endif

#	ifdef __MINGW32__
#		include <windows.h>

#		undef XIEITE_COMPILER_TYPE_MINGW32
#		define XIEITE_COMPILER_TYPE_MINGW32 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_MINGW32
#		define XIEITE_COMPILER_VERSION_MAJOR_MINGW32 __MINGW32_MAJOR_VERSION

#		undef XIEITE_COMPILER_VERSION_MINOR_MINGW32
#		define XIEITE_COMPILER_VERSION_MINOR_MINGW32 __MINGW32_MINOR_VERSION
#	endif

#	ifdef __MINGW64__
#		include <windows.h>

#		undef XIEITE_COMPILER_TYPE_MINGW_W64
#		define XIEITE_COMPILER_TYPE_MINGW_W64 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_MINGW_W64
#		define XIEITE_COMPILER_VERSION_MAJOR_MINGW_W64 __MINGW64_VERSION_MAJOR

#		undef XIEITE_COMPILER_VERSION_MINOR_MINGW_W64
#		define XIEITE_COMPILER_VERSION_MINOR_MINGW_W64 __MINGW64_VERSION_MINOR

#		undef XIEITE_COMPILER_VERSION_PATCH_MINGW_W64
#		define XIEITE_COMPILER_VERSION_PATCH_MINGW_W64
#	endif

#	if defined(__sgi) || defined(sgi)
#		undef XIEITE_COMPILER_TYPE_MIPSPRO
#		define XIEITE_COMPILER_TYPE_MIPSPRO 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_MIPSPRO
#		define XIEITE_COMPILER_VERSION_MAJOR_MIPSPRO (_SGI_COMPILER_VERSION / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_MIPSPRO
#		define XIEITE_COMPILER_VERSION_MINOR_MIPSPRO (_SGI_COMPILER_VERSION % 100 / 10)

#		undef XIEITE_COMPILER_VERSION_PATCH_MIPSPRO
#		define XIEITE_COMPILER_VERSION_PATCH_MIPSPRO (_SGI_COMPILER_VERSION % 10)
#	endif

#	ifdef MIRACLE
#		undef XIEITE_COMPILER_TYPE_MIRACLE_C
#		define XIEITE_COMPILER_TYPE_MIRACLE_C 1
#	endif

#	if defined(__MRC__) || defined(MPW_C) || defined(MPW_CPLUS)
#		undef XIEITE_COMPILER_TYPE_MPW
#		define XIEITE_COMPILER_TYPE_MPW 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_MPW
#		define XIEITE_COMPILER_VERSION_MAJOR_MPW (__MRC__ / 0x100)

#		undef XIEITE_COMPILER_VERSION_MINOR_MPW
#		define XIEITE_COMPILER_VERSION_MINOR_MPW (__MRC__ % 0x100)
#	endif

#	ifdef _MSC_VER
#		undef XIEITE_COMPILER_TYPE_MSVC
#		define XIEITE_COMPILER_TYPE_MSVC 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_MSVC
#		define XIEITE_COMPILER_VERSION_MAJOR_MSVC (_MSC_FULL_VER / 10000000)

#		undef XIEITE_COMPILER_VERSION_MINOR_MSVC
#		define XIEITE_COMPILER_VERSION_MINOR_MSVC (_MSC_FULL_VER % 10000000 / 100000)

#		undef XIEITE_COMPILER_VERSION_PATCH_MSVC
#		define XIEITE_COMPILER_VERSION_PATCH_MSVC (_MSC_FULL_VER % 100000)
#	endif

#	ifdef __CC_NORCROFT
#		undef XIEITE_COMPILER_TYPE_NORCROFT_C
#		define XIEITE_COMPILER_TYPE_NORCROFT_C 1
#	endif

#	ifdef __NVCOMPILER
#		undef XIEITE_COMPILER_TYPE_NVIDIA_HPC
#		define XIEITE_COMPILER_TYPE_NVIDIA_HPC 1
#	endif

#	ifdef __NWCC__
#		undef XIEITE_COMPILER_TYPE_NWCC
#		define XIEITE_COMPILER_TYPE_NWCC 1
#	endif

#	if defined(__OPEN64__) || defined(__OPENCC__)
#		undef XIEITE_COMPILER_TYPE_OPEN64
#		define XIEITE_COMPILER_TYPE_OPEN64 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_OPEN64
#		define XIEITE_COMPILER_VERSION_MAJOR_OPEN64 __OPENCC__

#		undef XIEITE_COMPILER_VERSION_MINOR_OPEN64
#		define XIEITE_COMPILER_VERSION_MINOR_OPEN64 __OPENCC_MINOR__

#		undef XIEITE_COMPILER_VERSION_PATCH_OPEN64
#		define XIEITE_COMPILER_VERSION_PATCH_OPEN64 __OPENCC_PATCHLEVEL__
#	endif

#	ifdef _SCO_DS
#		undef XIEITE_COMPILER_TYPE_OPENSERVER
#		define XIEITE_COMPILER_TYPE_OPENSERVER 1
#	endif

#	ifdef __PACIFIC__
#		undef XIEITE_COMPILER_TYPE_PACIFIC_C
#		define XIEITE_COMPILER_TYPE_PACIFIC_C 1
#	endif

#	ifdef _PACC_VER
#		undef XIEITE_COMPILER_TYPE_PALM_C_CPP
#		define XIEITE_COMPILER_TYPE_PALM_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_PALM_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_PALM_C_CPP (_PACC_VER / 0x10000000)

#		undef XIEITE_COMPILER_VERSION_MINOR_PALM_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_PALM_C_CPP (_PACC_VER % 0x10000000 / 0x100000)

#		undef XIEITE_COMPILER_VERSION_PATCH_PALM_C_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_PALM_C_CPP (_PACC_VER % 0x100000 / 0x1000)
#	endif

#	ifdef __POCC__
#		undef XIEITE_COMPILER_TYPE_PELLES_C
#		define XIEITE_COMPILER_TYPE_PELLES_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_PELLES_C
#		define XIEITE_COMPILER_VERSION_MAJOR_PELLES_C (__POCC__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_PELLES_C
#		define XIEITE_COMPILER_VERSION_MINOR_PELLES_C (__POCC__ % 100)
#	endif

#	ifdef __PGI
#		undef XIEITE_COMPILER_TYPE_PGI_C_CPP
#		define XIEITE_COMPILER_TYPE_PGI_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_PGI_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_PGI_C_CPP __PGIC__

#		undef XIEITE_COMPILER_VERSION_MINOR_PGI_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_PGI_C_CPP __PGIC_MINOR__

#		undef XIEITE_COMPILER_VERSION_PATCH_PGI_C_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_PGI_C_CPP __PGIC_PATCHLEVEL__
#	endif

#	ifdef ORA_PROC
#		undef XIEITE_COMPILER_TYPE_PRO_C
#		define XIEITE_COMPILER_TYPE_PRO_C 1
#	endif

#	if defined(__RENESAS__) || defined(__HITACHI__)
#		undef XIEITE_COMPILER_TYPE_RENESAS_C_CPP
#		define XIEITE_COMPILER_TYPE_RENESAS_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_RENESAS_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_RENESAS_C_CPP (__RENESAS_VERSION___ / 0x1000000)

#		undef XIEITE_COMPILER_VERSION_MINOR_RENESAS_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_RENESAS_C_CPP (__RENESAS_VERSION___ % 0x1000000 / 0x10000)

#		undef XIEITE_COMPILER_VERSION_PATCH_RENESAS_C_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_RENESAS_C_CPP (__RENESAS_VERSION___ % 0x10000 / 0x100)
#	endif

#	ifdef SDCC
#		undef XIEITE_COMPILER_TYPE_SDCC
#		define XIEITE_COMPILER_TYPE_SDCC 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_SDCC
#		define XIEITE_COMPILER_VERSION_MAJOR_SDCC (SDCC / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_SDCC
#		define XIEITE_COMPILER_VERSION_MINOR_SDCC (SDCC % 100 / 10)

#		undef XIEITE_COMPILER_VERSION_PATCH_SDCC
#		define XIEITE_COMPILER_VERSION_PATCH_SDCC (SDCC % 10)
#	endif

#	ifdef __SNC__
#		undef XIEITE_COMPILER_TYPE_SNC_COMPILER
#		define XIEITE_COMPILER_TYPE_SNC_COMPILER 1
#	endif

#	ifdef __VOSC__
#		undef XIEITE_COMPILER_TYPE_STRATUS_VOS_C
#		define XIEITE_COMPILER_TYPE_STRATUS_VOS_C 1
#	endif

#	if defined(__SUNPRO_C)
#		undef XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS_C
#		define XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_SUNPRO_COMPILERS_C
#		define XIEITE_COMPILER_VERSION_MAJOR_SUNPRO_COMPILERS_C (__SUNPRO_C / 0x1000)

#		undef XIEITE_COMPILER_VERSION_MINOR_SUNPRO_COMPILERS_C
#		define XIEITE_COMPILER_VERSION_MINOR_SUNPRO_COMPILERS_C (__SUNPRO_C % 0x1000 / 0x10)

#		undef XIEITE_COMPILER_VERSION_PATCH_SUNPRO_COMPILERS_C
#		define XIEITE_COMPILER_VERSION_PATCH_SUNPRO_COMPILERS_C (__SUNPRO_C % 0x10)
#	endif

#	if defined(__SUNPRO_CC)
#		undef XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS_CPP
#		define XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_SUNPRO_COMPILERS_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_SUNPRO_COMPILERS_CPP (__SUNPRO_CC / 0x1000)

#		undef XIEITE_COMPILER_VERSION_MINOR_SUNPRO_COMPILERS_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_SUNPRO_COMPILERS_CPP (__SUNPRO_CC % 0x1000 / 0x10)

#		undef XIEITE_COMPILER_VERSION_PATCH_SUNPRO_COMPILERS_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_SUNPRO_COMPILERS_CPP (__SUNPRO_CC % 0x10)
#	endif

#	ifdef __SC__
#		undef XIEITE_COMPILER_TYPE_SYMANTEC_CPP
#		define XIEITE_COMPILER_TYPE_SYMANTEC_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_SYMANTEC_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_SYMANTEC_CPP (__SC__ / 0x100)

#		undef XIEITE_COMPILER_VERSION_MINOR_SYMANTEC_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_SYMANTEC_CPP (__SC__ % 0x100)
#	endif

#	if __TINYC__
#		undef XIEITE_COMPILER_TYPE_TCC
#		define XIEITE_COMPILER_TYPE_TCC 1
#	endif

#	ifdef __TenDRA__
#		undef XIEITE_COMPILER_TYPE_TENDRA
#		define XIEITE_COMPILER_TYPE_TENDRA 1
#	endif

#	if defined(__TI_COMPILER_VERSION__) || defined(_TMS320C6X)
#		undef XIEITE_COMPILER_TYPE_TI_CGT
#		define XIEITE_COMPILER_TYPE_TI_CGT 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_TI_CGT
#		define XIEITE_COMPILER_VERSION_MAJOR_TI_CGT (__TI_COMPILER_VERSION___ / 1000000)

#		undef XIEITE_COMPILER_VERSION_MINOR_TI_CGT
#		define XIEITE_COMPILER_VERSION_MINOR_TI_CGT (__TI_COMPILER_VERSION___ % 1000000 / 1000)

#		undef XIEITE_COMPILER_VERSION_PATCH_TI_CGT
#		define XIEITE_COMPILER_VERSION_PATCH_TI_CGT (__TI_COMPILER_VERSION___ % 1000)
#	endif

#	ifdef __TURBOC__
#		undef XIEITE_COMPILER_TYPE_TURBO_C_CPP
#		define XIEITE_COMPILER_TYPE_TURBO_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_TURBO_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_TURBO_C_CPP (__TURBOC__ / 0x100)

#		undef XIEITE_COMPILER_VERSION_MINOR_TURBO_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_TURBO_C_CPP (__TURBOC__ % 0x100)
#	endif

#	ifdef _UCC
#		undef XIEITE_COMPILER_TYPE_ULTIMATE_C_CPP
#		define XIEITE_COMPILER_TYPE_ULTIMATE_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ULTIMATE_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_ULTIMATE_C_CPP _MAJOR_REV

#		undef XIEITE_COMPILER_VERSION_MINOR_ULTIMATE_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_ULTIMATE_C_CPP _MINOR_REV
#	endif

#	ifdef __USLC__
#		undef XIEITE_COMPILER_TYPE_USL_C
#		define XIEITE_COMPILER_TYPE_USL_C 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_USL_C
#		define XIEITE_COMPILER_VERSION_MAJOR_USL_C (__SCO_VERSION___ / 100000000)

#		undef XIEITE_COMPILER_VERSION_MINOR_USL_C
#		define XIEITE_COMPILER_VERSION_MINOR_USL_C (__SCO_VERSION___ % 100000000 / 1000000)
#	endif

#	ifdef __VBCC__
#		undef XIEITE_COMPILER_TYPE_VBCC
#		define XIEITE_COMPILER_TYPE_VBCC 1
#	endif

#	ifdef __WATCOMC__
#		undef XIEITE_COMPILER_TYPE_WATCOM_C_CPP
#		define XIEITE_COMPILER_TYPE_WATCOM_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_WATCOM_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_WATCOM_C_CPP (__WATCOMC__ / 100)

#		undef XIEITE_COMPILER_VERSION_MINOR_WATCOM_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_WATCOM_C_CPP (__WATCOMC__ % 100)
#	endif

#	ifdef __DCC__
#		undef XIEITE_COMPILER_TYPE_WIND_RIVER_DIAB_COMPILER
#		define XIEITE_COMPILER_TYPE_WIND_RIVER_DIAB_COMPILER 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_WIND_RIVER_DIAB_COMPILER
#		define XIEITE_COMPILER_VERSION_MAJOR_WIND_RIVER_DIAB_COMPILER (__VERSION_NUMBER__ / 1000)

#		undef XIEITE_COMPILER_VERSION_MINOR_WIND_RIVER_DIAB_COMPILER
#		define XIEITE_COMPILER_VERSION_MINOR_WIND_RIVER_DIAB_COMPILER (__VERSION_NUMBER__ % 1000 / 100)

#		undef XIEITE_COMPILER_VERSION_PATCH_WIND_RIVER_DIAB_COMPILER
#		define XIEITE_COMPILER_VERSION_PATCH_WIND_RIVER_DIAB_COMPILER (__VERSION_NUMBER__ % 100)
#	endif

#	if defined(__ibmxl__) || defined(__xlC__) || defined(__IBMC__) || defined(__IBMCPP__)
#		undef XIEITE_COMPILER_TYPE_XL_C_CPP
#		define XIEITE_COMPILER_TYPE_XL_C_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_XL_C_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_XL_C_CPP __ibmxl_version__

#		undef XIEITE_COMPILER_VERSION_MINOR_XL_C_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_XL_C_CPP __ibmxl_release__

#		undef XIEITE_COMPILER_VERSION_PATCH_XL_C_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_XL_C_CPP __ibmxl_modification__
#	endif

#	ifdef __ZTC__
#		undef XIEITE_COMPILER_TYPE_ZORTECH_CPP
#		define XIEITE_COMPILER_TYPE_ZORTECH_CPP 1

#		undef XIEITE_COMPILER_VERSION_MAJOR_ZORTECH_CPP
#		define XIEITE_COMPILER_VERSION_MAJOR_ZORTECH_CPP (__ZTC__ / 0x100)

#		undef XIEITE_COMPILER_VERSION_MINOR_ZORTECH_CPP
#		define XIEITE_COMPILER_VERSION_MINOR_ZORTECH_CPP (__ZTC__ % 0x100 / 0x10)

#		undef XIEITE_COMPILER_VERSION_PATCH_ZORTECH_CPP
#		define XIEITE_COMPILER_VERSION_PATCH_ZORTECH_CPP (__ZTC__ % 0x10)
#	endif

#endif

// https://sourceforge.net/p/predef/wiki/Compilers/

// TODO: Search GitHub for possible detection macros
