#ifndef XIEITE_HEADER_MACROS_COMPILER
#	define XIEITE_HEADER_MACROS_COMPILER

#	undef XIEITE_COMPILER_ACC
#	undef XIEITE_COMPILER_ACK
#	undef XIEITE_COMPILER_ACORN_C_CPP
#	undef XIEITE_COMPILER_ALAN_SNYDERS_PORTABLE_C_COMPILER
#	undef XIEITE_COMPILER_ALTIUM_C_TO_HARDWARE
#	undef XIEITE_COMPILER_ALTIUM_MICROBLAZE_C
#	undef XIEITE_COMPILER_AMD_OPTIMIZING_C_CPP_COMPILER
#	undef XIEITE_COMPILER_AOCC
#	undef XIEITE_COMPILER_ARM_COMPILER
#	undef XIEITE_COMPILER_ARMCC
#	undef XIEITE_COMPILER_ARMCLANG
#	undef XIEITE_COMPILER_AZTEC_C
#	undef XIEITE_COMPILER_AMSTERDAM_COMPILER_KIT
#	undef XIEITE_COMPILER_BD_SOFTWARE_C_COMPILER
#	undef XIEITE_COMPILER_BDS_C
#	undef XIEITE_COMPILER_BSD_C
#	undef XIEITE_COMPILER_CFRONT
#	undef XIEITE_COMPILER_CC65
#	undef XIEITE_COMPILER_CH
#	undef XIEITE_COMPILER_CINT
#	undef XIEITE_COMPILER_CIRCLE
#	undef XIEITE_COMPILER_CLANG
#	undef XIEITE_COMPILER_CODEWARRIOR
#	undef XIEITE_COMPILER_COMEAU_C_CPP
#	undef XIEITE_COMPILER_COMPAQ_C
#	undef XIEITE_COMPILER_COMPAQ_CPP
#	undef XIEITE_COMPILER_COMPCERT
#	undef XIEITE_COMPILER_CONVEX_C
#	undef XIEITE_COMPILER_COVERITY_C_CPP_STATIC_ANALYZER
#	undef XIEITE_COMPILER_CPPBUILDER
#	undef XIEITE_COMPILER_CRAY_C_CPP
#	undef XIEITE_COMPILER_DATALIGHT_C
#	undef XIEITE_COMPILER_DICE_C
#	undef XIEITE_COMPILER_DIGITAL_MARS_C_CPP
#	undef XIEITE_COMPILER_DIGITAL_MARS_CPP
#	undef XIEITE_COMPILER_DIGITAL_RESEARCH_C
#	undef XIEITE_COMPILER_DIGNUS_SYSTEMS_C
#	undef XIEITE_COMPILER_DIGNUS_SYSTEMS_CPP
#	undef XIEITE_COMPILER_DJGPP
#	undef XIEITE_COMPILER_DJS_GNU_PROGRAMMING_PLATFORM
#	undef XIEITE_COMPILER_DMCPP
#	undef XIEITE_COMPILER_DPCPP
#	undef XIEITE_COMPILER_ECCP
#	undef XIEITE_COMPILER_EDGCPFE
#	undef XIEITE_COMPILER_EDG_CPP_FRONT_END
#	undef XIEITE_COMPILER_EDISON_DESIGN_GROUP_CPP_FRONT_END
#	undef XIEITE_COMPILER_EDGE_C_CPP
#	undef XIEITE_COMPILER_EKOPATH
#	undef XIEITE_COMPILER_ELLCC
#	undef XIEITE_COMPILER_EMSCRIPTEN
#	undef XIEITE_COMPILER_FORTE_DEVELOPER
#	undef XIEITE_COMPILER_FPGAC
#	undef XIEITE_COMPILER_FUJITSU_CPP
#	undef XIEITE_COMPILER_GCC
#	undef XIEITE_COMPILER_GNU_COMPILER_COLLECTION
#	undef XIEITE_COMPILER_GREEN_HILLS_C_CPP
#	undef XIEITE_COMPILER_HP_ACPP
#	undef XIEITE_COMPILER_HP_ANSI_C
#	undef XIEITE_COMPILER_IAR_C_CPP_COMPILER
#	undef XIEITE_COMPILER_ICC
#	undef XIEITE_COMPILER_ICL
#	undef XIEITE_COMPILER_ICX
#	undef XIEITE_COMPILER_ICPC
#	undef XIEITE_COMPILER_ICPX
#	undef XIEITE_COMPILER_IMAGECRAFT_C
#	undef XIEITE_COMPILER_IMPULSE_C
#	undef XIEITE_COMPILER_INTEL_ONEAPI_DPCPP_CPP_COMPILER
#	undef XIEITE_COMPILER_INTEL_CPP_COMPILER_CLASSIC
#	undef XIEITE_COMPILER_INTERACTIVE_C
#	undef XIEITE_COMPILER_KAI_CPP
#	undef XIEITE_COMPILER_KCC
#	undef XIEITE_COMPILER_KEIL_C166
#	undef XIEITE_COMPILER_KEIL_C51
#	undef XIEITE_COMPILER_KEIL_CARM
#	undef XIEITE_COMPILER_LABWINDOWS
#	undef XIEITE_COMPILER_LATTICE_C
#	undef XIEITE_COMPILER_LCC
#	undef XIEITE_COMPILER_LIGHTSPEED_C
#	undef XIEITE_COMPILER_LITTLE_C_COMPILER
#	undef XIEITE_COMPILER_LLVM
#	undef XIEITE_COMPILER_LOCAL_C_COMPILER
#	undef XIEITE_COMPILER_MACINTOSH_PROGRAMMERS_WORKSHOP
#	undef XIEITE_COMPILER_MARK_WILLIAMS_C
#	undef XIEITE_COMPILER_MCC
#	undef XIEITE_COMPILER_MEGAMAX_C
#	undef XIEITE_COMPILER_METAWARE_HIGH_C_CPP
#	undef XIEITE_COMPILER_MICROSOFT_VISUAL_CPP
#	undef XIEITE_COMPILER_MICROTEC_C_CPP
#	undef XIEITE_COMPILER_MICROWAY_NPC_C
#	undef XIEITE_COMPILER_MIKROC_COMPILER
#	undef XIEITE_COMPILER_MINGW
#	undef XIEITE_COMPILER_MINGW32
#	undef XIEITE_COMPILER_MINGW_W64
#	undef XIEITE_COMPILER_MIPSPRO
#	undef XIEITE_COMPILER_MIRACLE_C
#	undef XIEITE_COMPILER_MPW
#	undef XIEITE_COMPILER_MSVC
#	undef XIEITE_COMPILER_NORCROFT_C
#	undef XIEITE_COMPILER_NVIDIA_HPC
#	undef XIEITE_COMPILER_NWCC
#	undef XIEITE_COMPILER_OPEN_WATCOM_C_CPP
#	undef XIEITE_COMPILER_OPEN_XL_C_CPP
#	undef XIEITE_COMPILER_OPEN64
#	undef XIEITE_COMPILER_OPENSERVER
#	undef XIEITE_COMPILER_ORACLE_DEVELOPER_STUDIO
#	undef XIEITE_COMPILER_ORACLE_SOLARIS_STUDIO
#	undef XIEITE_COMPILER_PACIFIC_C
#	undef XIEITE_COMPILER_PALM_C_CPP
#	undef XIEITE_COMPILER_PATHCC
#	undef XIEITE_COMPILER_PCC
#	undef XIEITE_COMPILER_PCCM
#	undef XIEITE_COMPILER_PELLES_C
#	undef XIEITE_COMPILER_PERSONAL_C_COMPILER
#	undef XIEITE_COMPILER_PGI_C_CPP
#	undef XIEITE_COMPILER_PICOC
#	undef XIEITE_COMPILER_PORTABLE_C_COMPILER
#	undef XIEITE_COMPILER_PORTLAND_GROUP_C_CPP
#	undef XIEITE_COMPILER_PRO_C
#	undef XIEITE_COMPILER_PRO_C_CPP
#	undef XIEITE_COMPILER_PRODEV_WORKSHOP
#	undef XIEITE_COMPILER_QUICKC
#	undef XIEITE_COMPILER_REALVIEW_COMPILATION_TOOLS
#	undef XIEITE_COMPILER_RENESAS_C_CPP
#	undef XIEITE_COMPILER_RITCHIE_C_COMPILER
#	undef XIEITE_COMPILER_SAS_C
#	undef XIEITE_COMPILER_SAS_C_CPP
#	undef XIEITE_COMPILER_SCORE_C
#	undef XIEITE_COMPILER_SCORE_CPP
#	undef XIEITE_COMPILER_SDCC
#	undef XIEITE_COMPILER_SEGGER_COMPILER
#	undef XIEITE_COMPILER_SMALL_C
#	undef XIEITE_COMPILER_SMALL_DEVICE_C_COMPILER
#	undef XIEITE_COMPILER_SNC_COMPILER
#	undef XIEITE_COMPILER_STANFORD_CPP_COMPILER
#	undef XIEITE_COMPILER_STRATUS_VOS_C
#	undef XIEITE_COMPILER_SUBC
#	undef XIEITE_COMPILER_SUN_STUDIO
#	undef XIEITE_COMPILER_SUN_WORKSHOP
#	undef XIEITE_COMPILER_SUNPRO_COMPILERS
#	undef XIEITE_COMPILER_SYMANTEC_CPP
#	undef XIEITE_COMPILER_SYMBOLICS_C
#	undef XIEITE_COMPILER_TANDEM_C
#	undef XIEITE_COMPILER_TANDEM_CPP
#	undef XIEITE_COMPILER_TASKING
#	undef XIEITE_COMPILER_TCC
#	undef XIEITE_COMPILER_TENDRA
#	undef XIEITE_COMPILER_THINK_C
#	undef XIEITE_COMPILER_TI_CGT
#	undef XIEITE_COMPILER_TINY_C_COMPILER
#	undef XIEITE_COMPILER_TINYCC
#	undef XIEITE_COMPILER_TURBO_C_CPP
#	undef XIEITE_COMPILER_ULTIMATE_C_CPP
#	undef XIEITE_COMPILER_UNIX_SYSTEM_LABORATORIES
#	undef XIEITE_COMPILER_USL_C
#	undef XIEITE_COMPILER_VBCC
#	undef XIEITE_COMPILER_VECTORC
#	undef XIEITE_COMPILER_WATCOM_C_CPP
#	undef XIEITE_COMPILER_WIND_RIVER_DIAB_COMPILER
#	undef XIEITE_COMPILER_XL_C_CPP
#	undef XIEITE_COMPILER_ZIG_C_CPP
#	undef XIEITE_COMPILER_ZORLAND_C
#	undef XIEITE_COMPILER_ZORTECH_C
#	undef XIEITE_COMPILER_ZORTECH_CPP

#	ifdef _ACC_
#		define XIEITE_COMPILER_ACC true
#	endif

#	ifdef __ACK__
#		define XIEITE_COMPILER_ACK true
#		define XIEITE_COMPILER_AMSTERDAM_COMPILER_KIT true
#	endif

#	if false
#		define XIEITE_COMPILER_ACORN_C_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_ALAN_SNYDERS_PORTABLE_C_COMPILER true
#	endif

#	ifdef __CHC__
#		define XIEITE_COMPILER_ALTIUM_C_TO_HARDWARE true
#	endif

#	ifdef __CMB__
#		define XIEITE_COMPILER_ALTIUM_MICROBLAZE_C true
#	endif

#	if false
#		define XIEITE_COMPILER_AMD_OPTIMIZING_C_CPP_COMPILER true
#		define XIEITE_COMPILER_AOCC true
#	endif

#	ifdef __CC_ARM
#		define XIEITE_COMPILER_ARM_COMPILER true
#		define XIEITE_COMPILER_ARMCC true
#		define XIEITE_COMPILER_ARMCLANG true
#	endif

#	ifdef AZTEC_C
#		define XIEITE_COMPILER_AZTEC_C true
#	endif

#	if false
#		define XIEITE_COMPILER_BD_SOFTWARE_C_COMPILER true
#		define XIEITE_COMPILER_BDS_C true
#	endif

#	if false
#		define XIEITE_COMPILER_BSD_C true
#	endif

#	if false
#		define XIEITE_COMPILER_CFRONT true
#	endif

#	ifdef __CC65__
#		define XIEITE_COMPILER_CC65 true
#	endif

#	if false
#		define XIEITE_COMPILER_CH true
#	endif

#	if false
#		define XIEITE_COMPILER_CINT true
#	endif

#	ifdef __circle_lang__
#		define XIEITE_COMPILER_CIRCLE true
#	endif

#	ifdef __clang__
#		define XIEITE_COMPILER_CLANG true
#	endif

#	if defined(__MWERKS__) || defined(__CWCC__)
#		define XIEITE_COMPILER_CODEWARRIOR true
#	endif

#	ifdef __COMO__
#		define XIEITE_COMPILER_COMEAU_C_CPP true
#	endif

#	ifdef __DECC
#		define XIEITE_COMPILER_COMPAQ_C true
#	endif

#	ifdef __DECCXX
#		define XIEITE_COMPILER_COMPAQ_CPP true
#	endif

#	ifdef __COMPCERT__
#		define XIEITE_COMPILER_COMPCERT true
#	endif

#	ifdef __convexc__
#		define XIEITE_COMPILER_CONVEX_C true
#	endif

#	ifdef __COVERITY__
#		define XIEITE_COMPILER_COVERITY_C_CPP_STATIC_ANALYZER true
#	endif

#	if defined(__BORLANDC__) || defined(__CODEGEARC__)
#		define XIEITE_COMPILER_CPPBUILDER true
#	endif

#	ifdef _CRAYC
#		define XIEITE_COMPILER_CRAY_C_CPP true
#	endif

#	ifdef __DMC__
#		define XIEITE_COMPILER_DATALIGHT_C true
#		define XIEITE_COMPILER_DIGITAL_MARS_C_CPP true
#		define XIEITE_COMPILER_ZORLAND_C true
#		define XIEITE_COMPILER_ZORTECH_C true
#	endif

#	ifdef _DICE
#		define XIEITE_COMPILER_DICE_C true
#	endif

#	if false
#		define XIEITE_COMPILER_DIGITAL_RESEARCH_C true
#	endif

#	if false
#		define XIEITE_COMPILER_DIGNUS_SYSTEMS_C true
#	endif

#	ifdef __SYSC__
#		define XIEITE_COMPILER_DIGNUS_SYSTEMS_CPP true
#	endif

#	ifdef __DJGPP__
#		define XIEITE_COMPILER_DJGPP true
#		define XIEITE_COMPILER_DJS_GNU_PROGRAMMING_PLATFORM true
#	endif

#	if false
#		define XIEITE_COMPILER_DPCPP true
#	endif

#	ifdef __EDG__
#		define XIEITE_COMPILER_ECCP true
#		define XIEITE_COMPILER_EDGCPFE true
#		define XIEITE_COMPILER_EDG_CPP_FRONT_END true
#		define XIEITE_COMPILER_EDISON_DESIGN_GROUP_CPP_FRONT_END true
#	endif

#	if false
#		define XIEITE_COMPILER_EDGE_C_CPP true
#	endif

#	ifdef __PATHCC__
#		define XIEITE_COMPILER_EKOPATH true
#		define XIEITE_COMPILER_PATHCC true
#	endif

#	ifdef __ELLCC__
#		define XIEITE_COMPILER_ELLCC true
#	endif

#	ifdef __EMSCRIPTEN__
#		define XIEITE_COMPILER_EMSCRIPTEN true
#	endif

#	if defined(__SUNPRO_C) || defined(__SUNPRO_CC)
#		define XIEITE_COMPILER_FORTE_DEVELOPER true
#		define XIEITE_COMPILER_SUNPRO_COMPILERS true
#		define XIEITE_COMPILER_SUN_STUDIO true
#		define XIEITE_COMPILER_SUN_WORKSHOP true
#		define XIEITE_COMPILER_ORACLE_DEVELOPER_STUDIO true
#		define XIEITE_COMPILER_ORACLE_SOLARIS_STUDIO true
#	endif

#	if false
#		define XIEITE_COMPILER_FPGAC true
#	endif

#	ifdef __FCC_VERSION
#		define XIEITE_COMPILER_FUJITSU_CPP true
#	endif

#	ifdef __GNUC__
#		define XIEITE_COMPILER_GCC true
#		define XIEITE_COMPILER_GNU_COMPILER_COLLECTION true
#	endif

#	ifdef __ghs__
#		define XIEITE_COMPILER_GREEN_HILLS_C_CPP true
#	endif

#	ifdef __HP_aCC
#		define XIEITE_COMPILER_HP_ACPP true
#	endif

#	ifdef __HP_cc
#		define XIEITE_COMPILER_HP_ANSI_C true
#	endif

#	ifdef __IAR_SYSTEMS_ICC__
#		define XIEITE_COMPILER_IAR_C_CPP_COMPILER true
#	endif

#	if defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ECC) || defined(__ICL)
#		define XIEITE_COMPILER_ICC true
#		define XIEITE_COMPILER_ICL true
#		define XIEITE_COMPILER_ICPC true
#		define XIEITE_COMPILER_INTEL_CPP_COMPILER_CLASSIC true
#	endif

#	if false
#		define XIEITE_COMPILER_ICX true
#		define XIEITE_COMPILER_ICPX true
#		define XIEITE_COMPILER_INTEL_ONEAPI_DPCPP_CPP_COMPILER true
#	endif

#	ifdef __IMAGECRAFT__
#		define XIEITE_COMPILER_IMAGECRAFT_C true
#	endif

#	if false
#		define XIEITE_COMPILER_IMPULSE_C true
#	endif

#	if false
#		define XIEITE_COMPILER_INTERACTIVE_C true
#	endif

#	ifdef __KCC
#		define XIEITE_COMPILER_KAI_CPP true
#		define XIEITE_COMPILER_KCC true
#	endif

#	ifdef __C166__
#		define XIEITE_COMPILER_KEIL_C166 true
#	endif

#	ifdef __C51__
#		define XIEITE_COMPILER_KEIL_C51 true
#	endif

#	if defined(__CA__) || defined(__KEIL__)
#		define XIEITE_COMPILER_KEIL_CARM true
#	endif

#	if false
#		define XIEITE_COMPILER_LABWINDOWS true
#	endif

#	if defined(SASC) || defined(__SASC) || defined(__SASC__)
#		define XIEITE_COMPILER_LATTICE_C true
#		define XIEITE_COMPILER_SAS_C true
#	endif

#	ifdef __LCC__
#		define XIEITE_COMPILER_LCC true
#		define XIEITE_COMPILER_LITTLE_C_COMPILER true
#		define XIEITE_COMPILER_LOCAL_C_COMPILER true
#	endif

#	if defined(THINKC3) || defined(THINKC4)
#		define XIEITE_COMPILER_LIGHTSPEED_C true
#		define XIEITE_COMPILER_THINK_C true
#	endif

#	ifdef __llvm__
#		define XIEITE_COMPILER_LLVM true
#	endif

#	if defined(__MRC__) || defined(MPW_C) || defined(MPW_CPLUS)
#		define XIEITE_COMPILER_MACINTOSH_PROGRAMMERS_WORKSHOP true
#		define XIEITE_COMPILER_MPW true
#	endif

#	if false
#		define XIEITE_COMPILER_MARK_WILLIAMS_C true
#	endif

#	if false
#		define XIEITE_COMPILER_MCC true
#	endif

#	if false
#		define XIEITE_COMPILER_MEGAMAX_C true
#	endif

#	ifdef __HIGHC__
#		define XIEITE_COMPILER_METAWARE_HIGH_C_CPP true
#	endif

#	ifdef _MSC_VER
#		define XIEITE_COMPILER_MICROSOFT_VISUAL_CPP true
#		define XIEITE_COMPILER_MSVC true
#	endif

#	ifdef _MRI
#		define XIEITE_COMPILER_MICROTEC_C_CPP true
#	endif

#	if defined(__NDPC__) || defined(__NDPX__)
#		define XIEITE_COMPILER_MICROWAY_NPC_C true
#	endif

#	if false
#		define XIEITE_COMPILER_MIKROC_COMPILER true
#	endif

#	ifdef __MINGW32__
#		define XIEITE_COMPILER_MINGW true
#		define XIEITE_COMPILER_MINGW32 true
#	endif

#	ifdef __MINGW64__
#		define XIEITE_COMPILER_MINGW_W64 true
#	endif

#	if defined(__sgi) || defined(sgi)
#		define XIEITE_COMPILER_MIPSPRO true
#		define XIEITE_COMPILER_OPEN64 true
#	endif

#	ifdef MIRACLE
#		define XIEITE_COMPILER_MIRACLE_C true
#	endif

#	ifdef __CC_NORCROFT
#		define XIEITE_COMPILER_NORCROFT_C true
#	endif

#	ifdef __NVCOMPILER
#		define XIEITE_COMPILER_NVIDIA_HPC true
#	endif

#	ifdef __NWCC__
#		define XIEITE_COMPILER_NWCC true
#	endif

#	ifdef __WATCOMC__
#		define XIEITE_COMPILER_OPEN_WATCOM_C_CPP true
#		define XIEITE_COMPILER_WATCOM_C_CPP true
#	endif

#	if defined(__ibmxl__) || defined(__xlC__) || defined(__IBMC__) || defined(__IBMCPP__)
#		define XIEITE_COMPILER_OPEN_XL_C_CPP true
#		define XIEITE_COMPILER_XL_C_CPP true
#	endif

#	ifdef _SCO_DS
#		define XIEITE_COMPILER_OPENSERVER true
#	endif

#	ifdef __PACIFIC__
#		define XIEITE_COMPILER_PACIFIC_C true
#	endif

#	ifdef _PACC_VER
#		define XIEITE_COMPILER_PALM_C_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_PCC true
#		define XIEITE_COMPILER_PCCM true
#		define XIEITE_COMPILER_PORTABLE_C_COMPILER true
#	endif

#	ifdef __POCC__
#		define XIEITE_COMPILER_PELLES_C true
#	endif

#	if false
#		define XIEITE_COMPILER_PERSONAL_C_COMPILER true
#	endif

#	ifdef __PGI
#		define XIEITE_COMPILER_PGI_C_CPP true
#		define XIEITE_COMPILER_PORTLAND_GROUP_C_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_PICOC true
#	endif

#	ifdef ORA_PROC
#		define XIEITE_COMPILER_PRO_C true
#	endif

#	if false
#		define XIEITE_COMPILER_PRO_C_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_PRODEV_WORKSHOP true
#	endif

#	if false
#		define XIEITE_COMPILER_QUICKC true
#	endif

#	if false
#		define XIEITE_COMPILER_REALVIEW_COMPILATION_TOOLS true
#	endif

#	if defined(__RENESAS__) || defined(__HITACHI__)
#		define XIEITE_COMPILER_RENESAS_C_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_RITCHIE_C_COMPILER true
#	endif

#	if false
#		define XIEITE_COMPILER_SAS_C_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_SCORE_C true
#	endif

#	if false
#		define XIEITE_COMPILER_SCORE_CPP true
#	endif

#	ifdef SDCC
#		define XIEITE_COMPILER_SDCC true
#		define XIEITE_COMPILER_SMALL_DEVICE_C_COMPILER true
#	endif

#	if false
#		define XIEITE_COMPILER_SEGGER_COMPILER true
#	endif

#	if false
#		define XIEITE_COMPILER_SMALL_C true
#	endif

#	ifdef __SNC__
#		define XIEITE_COMPILER_SNC_COMPILER true
#	endif

#	if false
#		define XIEITE_COMPILER_STANFORD_CPP_COMPILER true
#	endif

#	ifdef __VOSC__
#		define XIEITE_COMPILER_STRATUS_VOS_C true
#	endif

#	if false
#		define XIEITE_COMPILER_SUBC true
#	endif

#	ifdef __SC__
#		define XIEITE_COMPILER_DIGITAL_MARS_CPP true
#		define XIEITE_COMPILER_DMCPP true
#		define XIEITE_COMPILER_SYMANTEC_CPP true
#		define XIEITE_COMPILER_ZORTECH_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_SYMBOLICS_C true
#	endif

#	if false
#		define XIEITE_COMPILER_TANDEM_C true
#	endif

#	if false
#		define XIEITE_COMPILER_TANDEM_CPP true
#	endif

#	if false
#		define XIEITE_COMPILER_TASKING true
#	endif

#	if __TINYC__
#		define XIEITE_COMPILER_TCC true
#		define XIEITE_COMPILER_TINY_C_COMPILER true
#		define XIEITE_COMPILER_TINYCC true
#	endif

#	ifdef __TenDRA__
#		define XIEITE_COMPILER_TENDRA true
#	endif

#	if defined(__TI_COMPILER_VERSION__) || defined(_TMS320C6X)
#		define XIEITE_COMPILER_TI_CGT true
#	endif

#	ifdef __TURBOC__
#		define XIEITE_COMPILER_TURBO_C_CPP true
#	endif

#	ifdef _UCC
#		define XIEITE_COMPILER_ULTIMATE_C_CPP true
#	endif

#	ifdef __USLC__
#		define XIEITE_COMPILER_UNIX_SYSTEM_LABORATORIES true
#		define XIEITE_COMPILER_USL_C true
#	endif

#	ifdef __VBCC__
#		define XIEITE_COMPILER_VBCC true
#	endif

#	if false
#		define XIEITE_COMPILER_VECTORC true
#	endif

#	ifdef __DCC__
#		define XIEITE_COMPILER_WIND_RIVER_DIAB_COMPILER true
#	endif

#	if false
#		define XIEITE_COMPILER_ZIG_C_CPP true
#	endif

#endif
