#ifndef XIEITE_HEADER_MACROS_COMPILER_TYPE
#	define XIEITE_HEADER_MACROS_COMPILER_TYPE

#	define XIEITE_COMPILER_TYPE_ACC 0
#	define XIEITE_COMPILER_TYPE_ACK 0
#	define XIEITE_COMPILER_TYPE_ACORN_C_CPP 0
#	define XIEITE_COMPILER_TYPE_ALAN_SNYDERS_PORTABLE_C_COMPILER 0
#	define XIEITE_COMPILER_TYPE_ALTIUM_C_TO_HARDWARE 0
#	define XIEITE_COMPILER_TYPE_ALTIUM_MICROBLAZE_C 0
#	define XIEITE_COMPILER_TYPE_AOCC 0
#	define XIEITE_COMPILER_TYPE_ARMCC 0
#	define XIEITE_COMPILER_TYPE_AZTEC_C 0
#	define XIEITE_COMPILER_TYPE_BDS_C 0
#	define XIEITE_COMPILER_TYPE_BSD_C 0
#	define XIEITE_COMPILER_TYPE_CFRONT 0
#	define XIEITE_COMPILER_TYPE_CC65 0
#	define XIEITE_COMPILER_TYPE_CH 0
#	define XIEITE_COMPILER_TYPE_CINT 0
#	define XIEITE_COMPILER_TYPE_CIRCLE 0
#	define XIEITE_COMPILER_TYPE_CLANG 0
#	define XIEITE_COMPILER_TYPE_CODEWARRIOR 0
#	define XIEITE_COMPILER_TYPE_COMEAU_C_CPP 0
#	define XIEITE_COMPILER_TYPE_COMPAQ_C 0
#	define XIEITE_COMPILER_TYPE_COMPAQ_CPP 0
#	define XIEITE_COMPILER_TYPE_COMPCERT 0
#	define XIEITE_COMPILER_TYPE_CONVEX_C 0
#	define XIEITE_COMPILER_TYPE_COVERITY_C_CPP_STATIC_ANALYZER 0
#	define XIEITE_COMPILER_TYPE_CPPBUILDER 0
#	define XIEITE_COMPILER_TYPE_CRAY_C_CPP 0
#	define XIEITE_COMPILER_TYPE_DATALIGHT_C 0
#	define XIEITE_COMPILER_TYPE_DICE_C 0
#	define XIEITE_COMPILER_TYPE_DIGITAL_RESEARCH_C 0
#	define XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_C 0
#	define XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_CPP 0
#	define XIEITE_COMPILER_TYPE_DJGPP 0
#	define XIEITE_COMPILER_TYPE_DPCPP 0
#	define XIEITE_COMPILER_TYPE_ECCP 0
#	define XIEITE_COMPILER_TYPE_EDGE_C_CPP 0
#	define XIEITE_COMPILER_TYPE_EKOPATH 0
#	define XIEITE_COMPILER_TYPE_ELLCC 0
#	define XIEITE_COMPILER_TYPE_EMSCRIPTEN 0
#	define XIEITE_COMPILER_TYPE_FPGAC 0
#	define XIEITE_COMPILER_TYPE_FUJITSU_CPP 0
#	define XIEITE_COMPILER_TYPE_GCC 0
#	define XIEITE_COMPILER_TYPE_GREEN_HILLS_C_CPP 0
#	define XIEITE_COMPILER_TYPE_HP_ACPP 0
#	define XIEITE_COMPILER_TYPE_HP_ANSI_C 0
#	define XIEITE_COMPILER_TYPE_IAR_C_CPP_COMPILER 0
#	define XIEITE_COMPILER_TYPE_ICC 0
#	define XIEITE_COMPILER_TYPE_ICX 0
#	define XIEITE_COMPILER_TYPE_IMAGECRAFT_C 0
#	define XIEITE_COMPILER_TYPE_IMPULSE_C 0
#	define XIEITE_COMPILER_TYPE_INTERACTIVE_C 0
#	define XIEITE_COMPILER_TYPE_KAI_CPP 0
#	define XIEITE_COMPILER_TYPE_KCC 0
#	define XIEITE_COMPILER_TYPE_KEIL_C166 0
#	define XIEITE_COMPILER_TYPE_KEIL_C51 0
#	define XIEITE_COMPILER_TYPE_KEIL_CARM 0
#	define XIEITE_COMPILER_TYPE_LABWINDOWS 0
#	define XIEITE_COMPILER_TYPE_LATTICE_C 0
#	define XIEITE_COMPILER_TYPE_LCC 0
#	define XIEITE_COMPILER_TYPE_LIGHTSPEED_C 0
#	define XIEITE_COMPILER_TYPE_LLVM 0
#	define XIEITE_COMPILER_TYPE_MARK_WILLIAMS_C 0
#	define XIEITE_COMPILER_TYPE_MCC 0
#	define XIEITE_COMPILER_TYPE_MEGAMAX_C 0
#	define XIEITE_COMPILER_TYPE_METAWARE_HIGH_C_CPP 0
#	define XIEITE_COMPILER_TYPE_MICROTEC_C_CPP 0
#	define XIEITE_COMPILER_TYPE_MICROWAY_NPC_C 0
#	define XIEITE_COMPILER_TYPE_MIKROC_COMPILER 0
#	define XIEITE_COMPILER_TYPE_MINGW32 0
#	define XIEITE_COMPILER_TYPE_MINGW_W64 0
#	define XIEITE_COMPILER_TYPE_MIRACLE_C 0
#	define XIEITE_COMPILER_TYPE_MPW 0
#	define XIEITE_COMPILER_TYPE_MSVC 0
#	define XIEITE_COMPILER_TYPE_NORCROFT_C 0
#	define XIEITE_COMPILER_TYPE_NVIDIA_HPC 0
#	define XIEITE_COMPILER_TYPE_NWCC 0
#	define XIEITE_COMPILER_TYPE_OPEN64 0
#	define XIEITE_COMPILER_TYPE_OPENSERVER 0
#	define XIEITE_COMPILER_TYPE_PACIFIC_C 0
#	define XIEITE_COMPILER_TYPE_PALM_C_CPP 0
#	define XIEITE_COMPILER_TYPE_PCC 0
#	define XIEITE_COMPILER_TYPE_PELLES_C 0
#	define XIEITE_COMPILER_TYPE_PERSONAL_C_COMPILER 0
#	define XIEITE_COMPILER_TYPE_PGI_C_CPP 0
#	define XIEITE_COMPILER_TYPE_PICOC 0
#	define XIEITE_COMPILER_TYPE_PRO_C 0
#	define XIEITE_COMPILER_TYPE_PRO_C_CPP 0
#	define XIEITE_COMPILER_TYPE_PRODEV_WORKSHOP 0
#	define XIEITE_COMPILER_TYPE_QUICKC 0
#	define XIEITE_COMPILER_TYPE_REALVIEW_COMPILATION_TOOLS 0
#	define XIEITE_COMPILER_TYPE_RENESAS_C_CPP 0
#	define XIEITE_COMPILER_TYPE_RITCHIE_C_COMPILER 0
#	define XIEITE_COMPILER_TYPE_SAS_C_CPP 0
#	define XIEITE_COMPILER_TYPE_SCORE_C 0
#	define XIEITE_COMPILER_TYPE_SCORE_CPP 0
#	define XIEITE_COMPILER_TYPE_SDCC 0
#	define XIEITE_COMPILER_TYPE_SEGGER_COMPILER 0
#	define XIEITE_COMPILER_TYPE_SMALL_C 0
#	define XIEITE_COMPILER_TYPE_SNC_COMPILER 0
#	define XIEITE_COMPILER_TYPE_STANFORD_CPP_COMPILER 0
#	define XIEITE_COMPILER_TYPE_STRATUS_VOS_C 0
#	define XIEITE_COMPILER_TYPE_SUBC 0
#	define XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS 0
#	define XIEITE_COMPILER_TYPE_SYMANTEC_CPP
#	define XIEITE_COMPILER_TYPE_SYMBOLICS_C 0
#	define XIEITE_COMPILER_TYPE_TANDEM_C 0
#	define XIEITE_COMPILER_TYPE_TANDEM_CPP 0
#	define XIEITE_COMPILER_TYPE_TASKING 0
#	define XIEITE_COMPILER_TYPE_TCC 0
#	define XIEITE_COMPILER_TYPE_TENDRA 0
#	define XIEITE_COMPILER_TYPE_TI_CGT 0
#	define XIEITE_COMPILER_TYPE_TURBO_C_CPP 0
#	define XIEITE_COMPILER_TYPE_ULTIMATE_C_CPP 0
#	define XIEITE_COMPILER_TYPE_USL_C 0
#	define XIEITE_COMPILER_TYPE_VBCC 0
#	define XIEITE_COMPILER_TYPE_VECTORC 0
#	define XIEITE_COMPILER_TYPE_WATCOM_C_CPP 0
#	define XIEITE_COMPILER_TYPE_WIND_RIVER_DIAB_COMPILER 0
#	define XIEITE_COMPILER_TYPE_XL_C_CPP 0
#	define XIEITE_COMPILER_TYPE_ZERYNTH
#	define XIEITE_COMPILER_TYPE_ZIG_C_CPP 0
#	define XIEITE_COMPILER_TYPE_ZORTECH_CPP 0

#	ifdef _ACC_
#		undef XIEITE_COMPILER_TYPE_ACC
#		define XIEITE_COMPILER_TYPE_ACC 1
#	endif

#	ifdef __ACK__
#		undef XIEITE_COMPILER_TYPE_ACK
#		define XIEITE_COMPILER_TYPE_ACK 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_ACORN_C_CPP
#		define XIEITE_COMPILER_TYPE_ACORN_C_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_ALAN_SNYDERS_PORTABLE_C_COMPILER
#		define XIEITE_COMPILER_TYPE_ALAN_SNYDERS_PORTABLE_C_COMPILER 1
#	endif

#	ifdef __CHC__
#		undef XIEITE_COMPILER_TYPE_ALTIUM_C_TO_HARDWARE
#		define XIEITE_COMPILER_TYPE_ALTIUM_C_TO_HARDWARE 1
#	endif

#	ifdef __CMB__
#		undef XIEITE_COMPILER_TYPE_ALTIUM_MICROBLAZE_C
#		define XIEITE_COMPILER_TYPE_ALTIUM_MICROBLAZE_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_AOCC
#		define XIEITE_COMPILER_TYPE_AOCC 1
#	endif

#	ifdef __CC_ARM
#		undef XIEITE_COMPILER_TYPE_ARMCC
#		define XIEITE_COMPILER_TYPE_ARMCC 1
#	endif

#	ifdef AZTEC_C
#		undef XIEITE_COMPILER_TYPE_AZTEC_C
#		define XIEITE_COMPILER_TYPE_AZTEC_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_BDS_C
#		define XIEITE_COMPILER_TYPE_BDS_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_BSD_C
#		define XIEITE_COMPILER_TYPE_BSD_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_CFRONT
#		define XIEITE_COMPILER_TYPE_CFRONT 1
#	endif

#	ifdef __CC65__
#		undef XIEITE_COMPILER_TYPE_CC65
#		define XIEITE_COMPILER_TYPE_CC65 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_CH
#		define XIEITE_COMPILER_TYPE_CH 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_CINT
#		define XIEITE_COMPILER_TYPE_CINT 1
#	endif

#	ifdef __circle_lang__
#		undef XIEITE_COMPILER_TYPE_CIRCLE
#		define XIEITE_COMPILER_TYPE_CIRCLE 1
#	endif

#	ifdef __clang__
#		undef XIEITE_COMPILER_TYPE_CLANG
#		define XIEITE_COMPILER_TYPE_CLANG 1
#	endif

#	if defined(__MWERKS__) || defined(__CWCC__)
#		undef XIEITE_COMPILER_TYPE_CODEWARRIOR
#		define XIEITE_COMPILER_TYPE_CODEWARRIOR 1
#	endif

#	ifdef __COMO__
#		undef XIEITE_COMPILER_TYPE_COMEAU_C_CPP
#		define XIEITE_COMPILER_TYPE_COMEAU_C_CPP 1
#	endif

#	ifdef __DECC
#		undef XIEITE_COMPILER_TYPE_COMPAQ_C
#		define XIEITE_COMPILER_TYPE_COMPAQ_C 1
#	endif

#	ifdef __DECCXX
#		undef XIEITE_COMPILER_TYPE_COMPAQ_CPP
#		define XIEITE_COMPILER_TYPE_COMPAQ_CPP 1
#	endif

#	ifdef __COMPCERT__
#		undef XIEITE_COMPILER_TYPE_COMPCERT
#		define XIEITE_COMPILER_TYPE_COMPCERT 1
#	endif

#	ifdef __convexc__
#		undef XIEITE_COMPILER_TYPE_CONVEX_C
#		define XIEITE_COMPILER_TYPE_CONVEX_C 1
#	endif

#	ifdef __COVERITY__
#		undef XIEITE_COMPILER_TYPE_COVERITY_C_CPP_STATIC_ANALYZER
#		define XIEITE_COMPILER_TYPE_COVERITY_C_CPP_STATIC_ANALYZER 1
#	endif

#	if defined(__BORLANDC__) || defined(__CODEGEARC__)
#		undef XIEITE_COMPILER_TYPE_CPPBUILDER
#		define XIEITE_COMPILER_TYPE_CPPBUILDER 1
#	endif

#	ifdef _CRAYC
#		undef XIEITE_COMPILER_TYPE_CRAY_C_CPP
#		define XIEITE_COMPILER_TYPE_CRAY_C_CPP 1
#	endif

#	ifdef __DMC__
#		undef XIEITE_COMPILER_TYPE_DATALIGHT_C
#		define XIEITE_COMPILER_TYPE_DATALIGHT_C 1
#	endif

#	ifdef _DICE
#		undef XIEITE_COMPILER_TYPE_DICE_C
#		define XIEITE_COMPILER_TYPE_DICE_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_DIGITAL_RESEARCH_C
#		define XIEITE_COMPILER_TYPE_DIGITAL_RESEARCH_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_C
#		define XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_C 1
#	endif

#	ifdef __SYSC__
#		undef XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_CPP
#		define XIEITE_COMPILER_TYPE_DIGNUS_SYSTEMS_CPP 1
#	endif

#	ifdef __DJGPP__
#		undef XIEITE_COMPILER_TYPE_DJGPP
#		define XIEITE_COMPILER_TYPE_DJGPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_DPCPP
#		define XIEITE_COMPILER_TYPE_DPCPP 1
#	endif

#	ifdef __EDG__
#		undef XIEITE_COMPILER_TYPE_ECCP
#		define XIEITE_COMPILER_TYPE_ECCP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_EDGE_C_CPP
#		define XIEITE_COMPILER_TYPE_EDGE_C_CPP 1
#	endif

#	ifdef __PATHCC__
#		undef XIEITE_COMPILER_TYPE_EKOPATH
#		define XIEITE_COMPILER_TYPE_EKOPATH 1
#	endif

#	ifdef __ELLCC__
#		undef XIEITE_COMPILER_TYPE_ELLCC
#		define XIEITE_COMPILER_TYPE_ELLCC 1
#	endif

#	ifdef __EMSCRIPTEN__
#		undef XIEITE_COMPILER_TYPE_EMSCRIPTEN
#		define XIEITE_COMPILER_TYPE_EMSCRIPTEN 1
#	endif

#	if defined(__SUNPRO_C) || defined(__SUNPRO_CC)
#		undef XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS
#		define XIEITE_COMPILER_TYPE_SUNPRO_COMPILERS 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_FPGAC
#		define XIEITE_COMPILER_TYPE_FPGAC 1
#	endif

#	ifdef __FCC_VERSION
#		undef XIEITE_COMPILER_TYPE_FUJITSU_CPP
#		define XIEITE_COMPILER_TYPE_FUJITSU_CPP 1
#	endif

#	ifdef __GNUC__
#		undef XIEITE_COMPILER_TYPE_GCC
#		define XIEITE_COMPILER_TYPE_GCC 1
#	endif

#	ifdef __ghs__
#		undef XIEITE_COMPILER_TYPE_GREEN_HILLS_C_CPP
#		define XIEITE_COMPILER_TYPE_GREEN_HILLS_C_CPP 1
#	endif

#	ifdef __HP_aCC
#		undef XIEITE_COMPILER_TYPE_HP_ACPP
#		define XIEITE_COMPILER_TYPE_HP_ACPP 1
#	endif

#	ifdef __HP_cc
#		undef XIEITE_COMPILER_TYPE_HP_ANSI_C
#		define XIEITE_COMPILER_TYPE_HP_ANSI_C 1
#	endif

#	ifdef __IAR_SYSTEMS_ICC__
#		undef XIEITE_COMPILER_TYPE_IAR_C_CPP_COMPILER
#		define XIEITE_COMPILER_TYPE_IAR_C_CPP_COMPILER 1
#	endif

#	if defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ECC) || defined(__ICL)
#		undef XIEITE_COMPILER_TYPE_ICC
#		define XIEITE_COMPILER_TYPE_ICC 1
#	endif

#	if defined(__INTEL_CLANG_COMPILER)
#		undef XIEITE_COMPILER_TYPE_ICX
#		define XIEITE_COMPILER_TYPE_ICX 1
#	endif

#	ifdef __IMAGECRAFT__
#		undef XIEITE_COMPILER_TYPE_IMAGECRAFT_C
#		define XIEITE_COMPILER_TYPE_IMAGECRAFT_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_IMPULSE_C
#		define XIEITE_COMPILER_TYPE_IMPULSE_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_INTERACTIVE_C
#		define XIEITE_COMPILER_TYPE_INTERACTIVE_C 1
#	endif

#	ifdef __KCC
#		undef XIEITE_COMPILER_TYPE_KCC
#		define XIEITE_COMPILER_TYPE_KCC 1
#	endif

#	ifdef __C166__
#		undef XIEITE_COMPILER_TYPE_KEIL_C166
#		define XIEITE_COMPILER_TYPE_KEIL_C166 1
#	endif

#	ifdef __C51__
#		undef XIEITE_COMPILER_TYPE_KEIL_C51
#		define XIEITE_COMPILER_TYPE_KEIL_C51 1
#	endif

#	if defined(__CA__) || defined(__KEIL__)
#		undef XIEITE_COMPILER_TYPE_KEIL_CARM
#		define XIEITE_COMPILER_TYPE_KEIL_CARM 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_LABWINDOWS
#		define XIEITE_COMPILER_TYPE_LABWINDOWS 1
#	endif

#	if defined(SASC) || defined(__SASC) || defined(__SASC__)
#		undef XIEITE_COMPILER_TYPE_LATTICE_C
#		define XIEITE_COMPILER_TYPE_LATTICE_C 1
#	endif

#	ifdef __LCC__
#		undef XIEITE_COMPILER_TYPE_LCC
#		define XIEITE_COMPILER_TYPE_LCC 1
#	endif

#	if defined(THINKC3) || defined(THINKC4)
#		undef XIEITE_COMPILER_TYPE_LIGHTSPEED_C
#		define XIEITE_COMPILER_TYPE_LIGHTSPEED_C 1
#	endif

#	ifdef __llvm__
#		undef XIEITE_COMPILER_TYPE_LLVM
#		define XIEITE_COMPILER_TYPE_LLVM 1
#	endif

#	if defined(__MRC__) || defined(MPW_C) || defined(MPW_CPLUS)
#		undef XIEITE_COMPILER_TYPE_MPW
#		define XIEITE_COMPILER_TYPE_MPW 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_MARK_WILLIAMS_C
#		define XIEITE_COMPILER_TYPE_MARK_WILLIAMS_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_MCC
#		define XIEITE_COMPILER_TYPE_MCC 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_MEGAMAX_C
#		define XIEITE_COMPILER_TYPE_MEGAMAX_C 1
#	endif

#	ifdef __HIGHC__
#		undef XIEITE_COMPILER_TYPE_METAWARE_HIGH_C_CPP
#		define XIEITE_COMPILER_TYPE_METAWARE_HIGH_C_CPP 1
#	endif

#	ifdef _MSC_VER
#		undef XIEITE_COMPILER_TYPE_MSVC
#		define XIEITE_COMPILER_TYPE_MSVC 1
#	endif

#	ifdef _MRI
#		undef XIEITE_COMPILER_TYPE_MICROTEC_C_CPP
#		define XIEITE_COMPILER_TYPE_MICROTEC_C_CPP 1
#	endif

#	if defined(__NDPC__) || defined(__NDPX__)
#		undef XIEITE_COMPILER_TYPE_MICROWAY_NPC_C
#		define XIEITE_COMPILER_TYPE_MICROWAY_NPC_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_MIKROC_COMPILER
#		define XIEITE_COMPILER_TYPE_MIKROC_COMPILER 1
#	endif

#	ifdef __MINGW32__
#		undef XIEITE_COMPILER_TYPE_MINGW32
#		define XIEITE_COMPILER_TYPE_MINGW32 1
#	endif

#	ifdef __MINGW64__
#		undef XIEITE_COMPILER_TYPE_MINGW_W64
#		define XIEITE_COMPILER_TYPE_MINGW_W64 1
#	endif

#	if defined(__sgi) || defined(sgi)
#		undef XIEITE_COMPILER_TYPE_MIPSPRO
#		define XIEITE_COMPILER_TYPE_MIPSPRO 1
#	endif

#	ifdef MIRACLE
#		undef XIEITE_COMPILER_TYPE_MIRACLE_C
#		define XIEITE_COMPILER_TYPE_MIRACLE_C 1
#	endif

#	ifdef __CC_NORCROFT
#		undef XIEITE_COMPILER_TYPE_NORCROFT_C
#		define XIEITE_COMPILER_TYPE_NORCROFT_C 1
#	endif

#	ifdef __NVCOMPILER
#		undef XIEITE_COMPILER_TYPE_NVIDIA_HPC
#		define XIEITE_COMPILER_TYPE_NVIDIA_HPC 1
#	endif

#	ifdef __NWCC__
#		undef XIEITE_COMPILER_TYPE_NWCC
#		define XIEITE_COMPILER_TYPE_NWCC 1
#	endif

#	ifdef __WATCOMC__
#		undef XIEITE_COMPILER_TYPE_WATCOM_C_CPP
#		define XIEITE_COMPILER_TYPE_WATCOM_C_CPP 1
#	endif

#	if defined(__ibmxl__) || defined(__xlC__) || defined(__IBMC__) || defined(__IBMCPP__)
#		undef XIEITE_COMPILER_TYPE_XL_C_CPP
#		define XIEITE_COMPILER_TYPE_XL_C_CPP 1
#	endif

#	if defined(__OPEN64__) || defined(__OPENCC__)
#		undef XIEITE_COMPILER_TYPE_OPEN64
#		define XIEITE_COMPILER_TYPE_OPEN64
#	endif

#	ifdef _SCO_DS
#		undef XIEITE_COMPILER_TYPE_OPENSERVER
#		define XIEITE_COMPILER_TYPE_OPENSERVER 1
#	endif

#	ifdef __PACIFIC__
#		undef XIEITE_COMPILER_TYPE_PACIFIC_C
#		define XIEITE_COMPILER_TYPE_PACIFIC_C 1
#	endif

#	ifdef _PACC_VER
#		undef XIEITE_COMPILER_TYPE_PALM_C_CPP
#		define XIEITE_COMPILER_TYPE_PALM_C_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_PCC
#		define XIEITE_COMPILER_TYPE_PCC 1
#	endif

#	ifdef __POCC__
#		undef XIEITE_COMPILER_TYPE_PELLES_C
#		define XIEITE_COMPILER_TYPE_PELLES_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_PERSONAL_C_COMPILER
#		define XIEITE_COMPILER_TYPE_PERSONAL_C_COMPILER 1
#	endif

#	ifdef __PGI
#		undef XIEITE_COMPILER_TYPE_PGI_C_CPP
#		define XIEITE_COMPILER_TYPE_PGI_C_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_PICOC
#		define XIEITE_COMPILER_TYPE_PICOC 1
#	endif

#	ifdef ORA_PROC
#		undef XIEITE_COMPILER_TYPE_PRO_C
#		define XIEITE_COMPILER_TYPE_PRO_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_PRO_C_CPP
#		define XIEITE_COMPILER_TYPE_PRO_C_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_PRODEV_WORKSHOP
#		define XIEITE_COMPILER_TYPE_PRODEV_WORKSHOP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_QUICKC
#		define XIEITE_COMPILER_TYPE_QUICKC 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_REALVIEW_COMPILATION_TOOLS
#		define XIEITE_COMPILER_TYPE_REALVIEW_COMPILATION_TOOLS 1
#	endif

#	if defined(__RENESAS__) || defined(__HITACHI__)
#		undef XIEITE_COMPILER_TYPE_RENESAS_C_CPP
#		define XIEITE_COMPILER_TYPE_RENESAS_C_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_RITCHIE_C_COMPILER
#		define XIEITE_COMPILER_TYPE_RITCHIE_C_COMPILER 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_SAS_C_CPP
#		define XIEITE_COMPILER_TYPE_SAS_C_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_SCORE_C
#		define XIEITE_COMPILER_TYPE_SCORE_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_SCORE_CPP
#		define XIEITE_COMPILER_TYPE_SCORE_CPP 1
#	endif

#	ifdef SDCC
#		undef XIEITE_COMPILER_TYPE_SDCC
#		define XIEITE_COMPILER_TYPE_SDCC 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_SEGGER_COMPILER
#		define XIEITE_COMPILER_TYPE_SEGGER_COMPILER 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_SMALL_C
#		define XIEITE_COMPILER_TYPE_SMALL_C 1
#	endif

#	ifdef __SNC__
#		undef XIEITE_COMPILER_TYPE_SNC_COMPILER
#		define XIEITE_COMPILER_TYPE_SNC_COMPILER 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_STANFORD_CPP_COMPILER
#		define XIEITE_COMPILER_TYPE_STANFORD_CPP_COMPILER 1
#	endif

#	ifdef __VOSC__
#		undef XIEITE_COMPILER_TYPE_STRATUS_VOS_C
#		define XIEITE_COMPILER_TYPE_STRATUS_VOS_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_SUBC
#		define XIEITE_COMPILER_TYPE_SUBC 1
#	endif

#	ifdef __SC__
#		undef XIEITE_COMPILER_TYPE_SYMANTEC_CPP
#		define XIEITE_COMPILER_TYPE_SYMANTEC_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_SYMBOLICS_C
#		define XIEITE_COMPILER_TYPE_SYMBOLICS_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_TANDEM_C
#		define XIEITE_COMPILER_TYPE_TANDEM_C 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_TANDEM_CPP
#		define XIEITE_COMPILER_TYPE_TANDEM_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_TASKING
#		define XIEITE_COMPILER_TYPE_TASKING 1
#	endif

#	if __TINYC__
#		undef XIEITE_COMPILER_TYPE_TCC
#		define XIEITE_COMPILER_TYPE_TCC 1
#	endif

#	ifdef __TenDRA__
#		undef XIEITE_COMPILER_TYPE_TENDRA
#		define XIEITE_COMPILER_TYPE_TENDRA 1
#	endif

#	if defined(__TI_COMPILER_VERSION__) || defined(_TMS320C6X)
#		undef XIEITE_COMPILER_TYPE_TI_CGT
#		define XIEITE_COMPILER_TYPE_TI_CGT 1
#	endif

#	ifdef __TURBOC__
#		undef XIEITE_COMPILER_TYPE_TURBO_C_CPP
#		define XIEITE_COMPILER_TYPE_TURBO_C_CPP 1
#	endif

#	ifdef _UCC
#		undef XIEITE_COMPILER_TYPE_ULTIMATE_C_CPP
#		define XIEITE_COMPILER_TYPE_ULTIMATE_C_CPP 1
#	endif

#	ifdef __USLC__
#		undef XIEITE_COMPILER_TYPE_USL_C
#		define XIEITE_COMPILER_TYPE_USL_C 1
#	endif

#	ifdef __VBCC__
#		undef XIEITE_COMPILER_TYPE_VBCC
#		define XIEITE_COMPILER_TYPE_VBCC 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_VECTORC
#		define XIEITE_COMPILER_TYPE_VECTORC 1
#	endif

#	ifdef __DCC__
#		undef XIEITE_COMPILER_TYPE_WIND_RIVER_DIAB_COMPILER
#		define XIEITE_COMPILER_TYPE_WIND_RIVER_DIAB_COMPILER 1
#	endif

#	ifdef __ZTC__
#		undef XIEITE_COMPILER_TYPE_ZORTECH_CPP
#		define XIEITE_COMPILER_TYPE_ZORTECH_CPP 1
#	endif

#	if false
#		undef XIEITE_COMPILER_TYPE_ZIG_C_CPP
#		define XIEITE_COMPILER_TYPE_ZIG_C_CPP 1
#	endif

#endif

// https://sourceforge.net/p/predef/wiki/Compilers/
// https://en.wikipedia.org/wiki/List_of_compilers
