#pragma once

#define XIEITE_COMPILER_ACC false
#define XIEITE_COMPILER_ACK false
#define XIEITE_COMPILER_ACORN_C_CPP false
#define XIEITE_COMPILER_ALAN_SNYDERS_PORTABLE_C_COMPILER false
#define XIEITE_COMPILER_ALTIUM_C_TO_HARDWARE false
#define XIEITE_COMPILER_ALTIUM_MICROBLAZE_C false
#define XIEITE_COMPILER_AMD_OPTIMIZING_C_CPP_COMPILER false
#define XIEITE_COMPILER_AOCC false
#define XIEITE_COMPILER_ARM_COMPILER false
#define XIEITE_COMPILER_ARMCC false
#define XIEITE_COMPILER_ARMCLANG false
#define XIEITE_COMPILER_AZTEC_C false
#define XIEITE_COMPILER_AMSTERDAM_COMPILER_KIT false
#define XIEITE_COMPILER_BD_SOFTWARE_C_COMPILER false
#define XIEITE_COMPILER_BDS_C false
#define XIEITE_COMPILER_BSD_C false
#define XIEITE_COMPILER_CFRONT false
#define XIEITE_COMPILER_CC65
#define XIEITE_COMPILER_CH false
#define XIEITE_COMPILER_CINT false
#define XIEITE_COMPILER_CIRCLE false
#define XIEITE_COMPILER_CLANG false
#define XIEITE_COMPILER_CODEWARRIOR false
#define XIEITE_COMPILER_COMEAU_C_CPP false
#define XIEITE_COMPILER_COMPAQ_C false
#define XIEITE_COMPILER_COMPAQ_CPP false
#define XIEITE_COMPILER_COMPCERT false
#define XIEITE_COMPILER_CONVEX_C false
#define XIEITE_COMPILER_COVERITY_C_CPP_STATIC_ANALYZER false
#define XIEITE_COMPILER_CPPBUILDER false
#define XIEITE_COMPILER_CRAY_C_CPP false
#define XIEITE_COMPILER_DATALIGHT_C false
#define XIEITE_COMPILER_DICE_C false
#define XIEITE_COMPILER_DIGITAL_MARS_C_CPP false
#define XIEITE_COMPILER_DIGITAL_MARS_CPP false
#define XIEITE_COMPILER_DIGITAL_RESEARCH_C false
#define XIEITE_COMPILER_DIGNUS_SYSTEMS_C false
#define XIEITE_COMPILER_DIGNUS_SYSTEMS_CPP false
#define XIEITE_COMPILER_DJGPP false
#define XIEITE_COMPILER_DJS_GNU_PROGRAMMING_PLATFORM false
#define XIEITE_COMPILER_DMCPP false
#define XIEITE_COMPILER_DPCPP false
#define XIEITE_COMPILER_ECCP false
#define XIEITE_COMPILER_EDGCPFE false
#define XIEITE_COMPILER_EDG_CPP_FRONT_END false
#define XIEITE_COMPILER_EDISON_DESIGN_GROUP_CPP_FRONT_END false
#define XIEITE_COMPILER_EDGE_C_CPP false
#define XIEITE_COMPILER_EKOPATH false
#define XIEITE_COMPILER_FORTE_DEVELOPER false
#define XIEITE_COMPILER_FPGAC false
#define XIEITE_COMPILER_FUJITSU_CPP false
#define XIEITE_COMPILER_GCC false
#define XIEITE_COMPILER_GNU_COMPILER_COLLECTION false
#define XIEITE_COMPILER_GREEN_HILLS_C_CPP false
#define XIEITE_COMPILER_HP_ACPP false
#define XIEITE_COMPILER_HP_ANSI_C false
#define XIEITE_COMPILER_IAR_C_CPP_COMPILER false
#define XIEITE_COMPILER_ICC false
#define XIEITE_COMPILER_ICL false
#define XIEITE_COMPILER_ICX false
#define XIEITE_COMPILER_ICPC false
#define XIEITE_COMPILER_ICPX false
#define XIEITE_COMPILER_IMAGECRAFT_C false
#define XIEITE_COMPILER_IMPULSE_C false
#define XIEITE_COMPILER_INTEL_ONEAPI_DPCPP_CPP_COMPILER false
#define XIEITE_COMPILER_INTEL_CPP_COMPILER_CLASSIC false
#define XIEITE_COMPILER_INTERACTIVE_C false
#define XIEITE_COMPILER_KAI_CPP false
#define XIEITE_COMPILER_KCC false
#define XIEITE_COMPILER_KEIL_C166
#define XIEITE_COMPILER_KEIL_C51
#define XIEITE_COMPILER_KEIL_CARM false
#define XIEITE_COMPILER_LABWINDOWS false
#define XIEITE_COMPILER_LATTICE_C false
#define XIEITE_COMPILER_LCC false
#define XIEITE_COMPILER_LIGHTSPEED_C false
#define XIEITE_COMPILER_LITTLE_C_COMPILER false
#define XIEITE_COMPILER_LLVM false
#define XIEITE_COMPILER_LOCAL_C_COMPILER false
#define XIEITE_COMPILER_MACINTOSH_PROGRAMMERS_WORKSHOP false
#define XIEITE_COMPILER_MARK_WILLIAMS_C false
#define XIEITE_COMPILER_MCC false
#define XIEITE_COMPILER_MEGAMAX_C false
#define XIEITE_COMPILER_METAWARE_HIGH_C_CPP false
#define XIEITE_COMPILER_MICROSOFT_VISUAL_CPP false
#define XIEITE_COMPILER_MICROTEC_C_CPP false
#define XIEITE_COMPILER_MICROWAY_NPC_C false
#define XIEITE_COMPILER_MIKROC_COMPILER false
#define XIEITE_COMPILER_MINGW false
#define XIEITE_COMPILER_MINGW32
#define XIEITE_COMPILER_MINGW_W64
#define XIEITE_COMPILER_MIPSPRO false
#define XIEITE_COMPILER_MIRACLE_C false
#define XIEITE_COMPILER_MPW false
#define XIEITE_COMPILER_MSVC false
#define XIEITE_COMPILER_NORCROFT_C false
#define XIEITE_COMPILER_NWCC false
#define XIEITE_COMPILER_OPEN_WATCOM_C_CPP false
#define XIEITE_COMPILER_OPEN_XL_C_CPP false
#define XIEITE_COMPILER_OPEN64
#define XIEITE_COMPILER_OPENSERVER false
#define XIEITE_COMPILER_ORACLE_DEVELOPER_STUDIO false
#define XIEITE_COMPILER_ORACLE_SOLARIS_STUDIO false
#define XIEITE_COMPILER_PACIFIC_C false
#define XIEITE_COMPILER_PALM_C_CPP false
#define XIEITE_COMPILER_PATHCC false
#define XIEITE_COMPILER_PCC false
#define XIEITE_COMPILER_PCCM false
#define XIEITE_COMPILER_PELLES_C false
#define XIEITE_COMPILER_PERSONAL_C_COMPILER false
#define XIEITE_COMPILER_PGI_C_CPP
#define XIEITE_COMPILER_PICOC false
#define XIEITE_COMPILER_PORTABLE_C_COMPILER false
#define XIEITE_COMPILER_PORTLAND_GROUP_C_CPP
#define XIEITE_COMPILER_PRO_C false
#define XIEITE_COMPILER_PRO_C_CPP false
#define XIEITE_COMPILER_PRODEV_WORKSHOP false
#define XIEITE_COMPILER_QUICKC false
#define XIEITE_COMPILER_REALVIEW_COMPILATION_TOOLS false
#define XIEITE_COMPILER_RENESAS_C_CPP false
#define XIEITE_COMPILER_RITCHIE_C_COMPILER false
#define XIEITE_COMPILER_SAS_C false
#define XIEITE_COMPILER_SAS_C_CPP false
#define XIEITE_COMPILER_SCORE_C false
#define XIEITE_COMPILER_SCORE_CPP false
#define XIEITE_COMPILER_SDCC false
#define XIEITE_COMPILER_SEGGER_COMPILER false
#define XIEITE_COMPILER_SMALL_C false
#define XIEITE_COMPILER_SMALL_DEVICE_C_COMPILER false
#define XIEITE_COMPILER_SNC_COMPILER false
#define XIEITE_COMPILER_STANFORD_CPP_COMPILER false
#define XIEITE_COMPILER_STRATUS_VOS_C false
#define XIEITE_COMPILER_SUBC false
#define XIEITE_COMPILER_SUN_STUDIO false
#define XIEITE_COMPILER_SUN_WORKSHOP false
#define XIEITE_COMPILER_SUNPRO_COMPILERS false
#define XIEITE_COMPILER_SYMANTEC_CPP false
#define XIEITE_COMPILER_SYMBOLICS_C false
#define XIEITE_COMPILER_TANDEM_C false
#define XIEITE_COMPILER_TANDEM_CPP false
#define XIEITE_COMPILER_TASKING false
#define XIEITE_COMPILER_TCC false
#define XIEITE_COMPILER_TENDRA false
#define XIEITE_COMPILER_THINK_C false
#define XIEITE_COMPILER_TI_CGT false
#define XIEITE_COMPILER_TINY_C_COMPILER false
#define XIEITE_COMPILER_TINYCC false
#define XIEITE_COMPILER_TURBO_C_CPP false
#define XIEITE_COMPILER_ULTIMATE_C_CPP false
#define XIEITE_COMPILER_UNIX_SYSTEM_LABORATORIES false
#define XIEITE_COMPILER_USL_C false
#define XIEITE_COMPILER_VBCC false
#define XIEITE_COMPILER_VECTORC false
#define XIEITE_COMPILER_WATCOM_C_CPP false
#define XIEITE_COMPILER_WIND_RIVER_DIAB_COMPILER false
#define XIEITE_COMPILER_XL_C_CPP false
#define XIEITE_COMPILER_ZIG_C_CPP false
#define XIEITE_COMPILER_ZORLAND_C false
#define XIEITE_COMPILER_ZORTECH_C false
#define XIEITE_COMPILER_ZORTECH_CPP false

#ifdef _ACC_
#	undef XIEITE_COMPILER_ACC
#	define XIEITE_COMPILER_ACC true
#endif

#ifdef __ACK__
#	undef XIEITE_COMPILER_ACK
#	undef XIEITE_COMPILER_AMSTERDAM_COMPILER_KIT
#	define XIEITE_COMPILER_ACK true
#	define XIEITE_COMPILER_AMSTERDAM_COMPILER_KIT true
#endif

#if false
#	undef XIEITE_COMPILER_ACORN_C_CPP
#	define XIEITE_COMPILER_ACORN_C_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_ALAN_SNYDERS_PORTABLE_C_COMPILER
#	define XIEITE_COMPILER_ALAN_SNYDERS_PORTABLE_C_COMPILER true
#endif

#ifdef __CHC__
#	undef XIEITE_COMPILER_ALTIUM_C_TO_HARDWARE
#	define XIEITE_COMPILER_ALTIUM_C_TO_HARDWARE true
#endif

#ifdef __CMB__
#	undef XIEITE_COMPILER_ALTIUM_MICROBLAZE_C
#	define XIEITE_COMPILER_ALTIUM_MICROBLAZE_C true
#endif

#if false
#	undef XIEITE_COMPILER_AMD_OPTIMIZING_C_CPP_COMPILER
#	undef XIEITE_COMPILER_AOCC
#	define XIEITE_COMPILER_AMD_OPTIMIZING_C_CPP_COMPILER true
#	define XIEITE_COMPILER_AOCC true
#endif

#ifdef __CC_ARM
#	undef XIEITE_COMPILER_ARM_COMPILER
#	undef XIEITE_COMPILER_ARMCC
#	undef XIEITE_COMPILER_ARMCLANG
#	define XIEITE_COMPILER_ARM_COMPILER true
#	define XIEITE_COMPILER_ARMCC true
#	define XIEITE_COMPILER_ARMCLANG true
#endif

#ifdef AZTEC_C
#	undef XIEITE_COMPILER_AZTEC_C
#	define XIEITE_COMPILER_AZTEC_C true
#endif

#if false
#	undef XIEITE_COMPILER_BD_SOFTWARE_C_COMPILER
#	undef XIEITE_COMPILER_BDS_C
#	define XIEITE_COMPILER_BD_SOFTWARE_C_COMPILER true
#	define XIEITE_COMPILER_BDS_C true
#endif

#if false
#	undef XIEITE_COMPILER_BSD_C
#	define XIEITE_COMPILER_BSD_C true
#endif

#if false
#	undef XIEITE_COMPILER_CFRONT
#	define XIEITE_COMPILER_CFRONT true
#endif

#ifdef __CC65__
#	undef XIEITE_COMPILER_CC65
#	define XIEITE_COMPILER_CC65 true
#endif

#if false
#	undef XIEITE_COMPILER_CH
#	define XIEITE_COMPILER_CH true
#endif

#if false
#	undef XIEITE_COMPILER_CINT
#	define XIEITE_COMPILER_CINT true
#endif

#ifdef __circle_lang__
#	undef XIEITE_COMPILER_CIRCLE
#	define XIEITE_COMPILER_CIRCLE true
#endif

#ifdef __clang__
#	undef XIEITE_COMPILER_CLANG
#	define XIEITE_COMPILER_CLANG true
#endif

#if defined(__MWERKS__) || defined(__CWCC__)
#	undef XIEITE_COMPILER_CODEWARRIOR
#	define XIEITE_COMPILER_CODEWARRIOR true
#endif

#ifdef __COMO__
#	undef XIEITE_COMPILER_COMEAU_C_CPP
#	define XIEITE_COMPILER_COMEAU_C_CPP true
#endif

#ifdef __DECC
#	undef XIEITE_COMPILER_COMPAQ_C
#	define XIEITE_COMPILER_COMPAQ_C true
#endif

#ifdef __DECCXX
#	undef XIEITE_COMPILER_COMPAQ_CPP
#	define XIEITE_COMPILER_COMPAQ_CPP true
#endif

#ifdef __COMPCERT__
#	undef XIEITE_COMPILER_COMPCERT
#	define XIEITE_COMPILER_COMPCERT true
#endif

#ifdef __convexc__
#	undef XIEITE_COMPILER_CONVEX_C
#	define XIEITE_COMPILER_CONVEX_C true
#endif

#ifdef __COVERITY__
#	undef XIEITE_COMPILER_COVERITY_C_CPP_STATIC_ANALYZER
#	define XIEITE_COMPILER_COVERITY_C_CPP_STATIC_ANALYZER true
#endif

#if defined(__BORLANDC__) || defined(__CODEGEARC__)
#	undef XIEITE_COMPILER_CPPBUILDER
#	define XIEITE_COMPILER_CPPBUILDER true
#endif

#ifdef _CRAYC
#	undef XIEITE_COMPILER_CRAY_C_CPP
#	define XIEITE_COMPILER_CRAY_C_CPP true
#endif

#ifdef __DMC__
#	undef XIEITE_COMPILER_DATALIGHT_C
#	undef XIEITE_COMPILER_DIGITAL_MARS_C_CPP
#	undef XIEITE_COMPILER_ZORLAND_C
#	undef XIEITE_COMPILER_ZORTECH_C
#	define XIEITE_COMPILER_DATALIGHT_C true
#	define XIEITE_COMPILER_DIGITAL_MARS_C_CPP true
#	define XIEITE_COMPILER_ZORLAND_C true
#	define XIEITE_COMPILER_ZORTECH_C true
#endif

#ifdef _DICE
#	undef XIEITE_COMPILER_DICE_C
#	define XIEITE_COMPILER_DICE_C true
#endif

#if false
#	undef XIEITE_COMPILER_DIGITAL_RESEARCH_C
#	define XIEITE_COMPILER_DIGITAL_RESEARCH_C true
#endif

#if false
#	undef XIEITE_COMPILER_DIGNUS_SYSTEMS_C
#	define XIEITE_COMPILER_DIGNUS_SYSTEMS_C true
#endif

#ifdef __SYSC__
#	undef XIEITE_COMPILER_DIGNUS_SYSTEMS_CPP
#	define XIEITE_COMPILER_DIGNUS_SYSTEMS_CPP true
#endif

#ifdef __DJGPP__
#	undef XIEITE_COMPILER_DJGPP
#	undef XIEITE_COMPILER_DJS_GNU_PROGRAMMING_PLATFORM
#	define XIEITE_COMPILER_DJGPP true
#	define XIEITE_COMPILER_DJS_GNU_PROGRAMMING_PLATFORM true
#endif

#if false
#	undef XIEITE_COMPILER_DPCPP
#	define XIEITE_COMPILER_DPCPP true
#endif

#ifdef __EDG__
#	undef XIEITE_COMPILER_ECCP
#	undef XIEITE_COMPILER_EDGCPFE
#	undef XIEITE_COMPILER_EDG_CPP_FRONT_END
#	undef XIEITE_COMPILER_EDISON_DESIGN_GROUP_CPP_FRONT_END
#	define XIEITE_COMPILER_ECCP true
#	define XIEITE_COMPILER_EDGCPFE true
#	define XIEITE_COMPILER_EDG_CPP_FRONT_END true
#	define XIEITE_COMPILER_EDISON_DESIGN_GROUP_CPP_FRONT_END true
#endif

#if false
#	undef XIEITE_COMPILER_EDGE_C_CPP
#	define XIEITE_COMPILER_EDGE_C_CPP true
#endif

#ifdef __PATHCC__
#	undef XIEITE_COMPILER_EKOPATH
#	undef XIEITE_COMPILER_PATHCC
#	define XIEITE_COMPILER_EKOPATH true
#	define XIEITE_COMPILER_PATHCC true
#endif

#if defined(__SUNPRO_C) || defined(__SUNPRO_CC)
#	undef XIEITE_COMPILER_FORTE_DEVELOPER
#	undef XIEITE_COMPILER_SUNPRO_COMPILERS
#	undef XIEITE_COMPILER_SUN_STUDIO
#	undef XIEITE_COMPILER_SUN_WORKSHOP
#	undef XIEITE_COMPILER_ORACLE_DEVELOPER_STUDIO
#	undef XIEITE_COMPILER_ORACLE_SOLARIS_STUDIO
#	define XIEITE_COMPILER_FORTE_DEVELOPER true
#	define XIEITE_COMPILER_SUNPRO_COMPILERS true
#	define XIEITE_COMPILER_SUN_STUDIO true
#	define XIEITE_COMPILER_SUN_WORKSHOP true
#	define XIEITE_COMPILER_ORACLE_DEVELOPER_STUDIO true
#	define XIEITE_COMPILER_ORACLE_SOLARIS_STUDIO true
#endif

#if false
#	undef XIEITE_COMPILER_FPGAC
#	define XIEITE_COMPILER_FPGAC true
#endif

#ifdef __FCC_VERSION
#	undef XIEITE_COMPILER_FUJITSU_CPP
#	define XIEITE_COMPILER_FUJITSU_CPP true
#endif

#ifdef __GNUC__
#	undef XIEITE_COMPILER_GCC
#	undef XIEITE_COMPILER_GNU_COMPILER_COLLECTION
#	define XIEITE_COMPILER_GCC true
#	define XIEITE_COMPILER_GNU_COMPILER_COLLECTION true
#endif

#ifdef __ghs__
#	undef XIEITE_COMPILER_GREEN_HILLS_C_CPP
#	define XIEITE_COMPILER_GREEN_HILLS_C_CPP true
#endif

#ifdef __HP_aCC
#	undef XIEITE_COMPILER_HP_ACPP
#	define XIEITE_COMPILER_HP_ACPP true
#endif

#ifdef __HP_cc
#	undef XIEITE_COMPILER_HP_ANSI_C
#	define XIEITE_COMPILER_HP_ANSI_C true
#endif

#ifdef __IAR_SYSTEMS_ICC__
#	undef XIEITE_COMPILER_IAR_C_CPP_COMPILER
#	define XIEITE_COMPILER_IAR_C_CPP_COMPILER true
#endif

#if defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ECC) || defined(__ICL)
#	undef XIEITE_COMPILER_ICC
#	undef XIEITE_COMPILER_ICL
#	undef XIEITE_COMPILER_ICPC
#	undef XIEITE_COMPILER_INTEL_CPP_COMPILER_CLASSIC
#	define XIEITE_COMPILER_ICC true
#	define XIEITE_COMPILER_ICL true
#	define XIEITE_COMPILER_ICPC true
#	define XIEITE_COMPILER_INTEL_CPP_COMPILER_CLASSIC true
#endif

#if false
#	undef XIEITE_COMPILER_ICX
#	undef XIEITE_COMPILER_ICPX
#	undef XIEITE_COMPILER_INTEL_ONEAPI_DPCPP_CPP_COMPILER
#	define XIEITE_COMPILER_ICX true
#	define XIEITE_COMPILER_ICPX true
#	define XIEITE_COMPILER_INTEL_ONEAPI_DPCPP_CPP_COMPILER true
#endif

#ifdef __IMAGECRAFT__
#	undef XIEITE_COMPILER_IMAGECRAFT_C
#	define XIEITE_COMPILER_IMAGECRAFT_C true
#endif

#if false
#	undef XIEITE_COMPILER_IMPULSE_C
#	define XIEITE_COMPILER_IMPULSE_C true
#endif

#if false
#	undef XIEITE_COMPILER_INTERACTIVE_C
#	define XIEITE_COMPILER_INTERACTIVE_C true
#endif

#ifdef __KCC
#	undef XIEITE_COMPILER_KAI_CPP
#	undef XIEITE_COMPILER_KCC
#	define XIEITE_COMPILER_KAI_CPP true
#	define XIEITE_COMPILER_KCC true
#endif

#ifdef __C166__
#	undef XIEITE_COMPILER_KEIL_C166
#	define XIEITE_COMPILER_KEIL_C166 true
#endif

#ifdef __C51__
#	undef XIEITE_COMPILER_KEIL_C51
#	define XIEITE_COMPILER_KEIL_C51 true
#endif

#if defined(__CA__) || defined(__KEIL__)
#	undef XIEITE_COMPILER_KEIL_CARM
#	define XIEITE_COMPILER_KEIL_CARM true
#endif

#if false
#	undef XIEITE_COMPILER_LABWINDOWS
#	define XIEITE_COMPILER_LABWINDOWS true
#endif

#if defined(SASC) || defined(__SASC) || defined(__SASC__)
#	undef XIEITE_COMPILER_LATTICE_C
#	undef XIEITE_COMPILER_SAS_C
#	define XIEITE_COMPILER_LATTICE_C true
#	define XIEITE_COMPILER_SAS_C true
#endif

#ifdef __LCC__
#	undef XIEITE_COMPILER_LCC
#	undef XIEITE_COMPILER_LITTLE_C_COMPILER
#	undef XIEITE_COMPILER_LOCAL_C_COMPILER
#	define XIEITE_COMPILER_LCC true
#	define XIEITE_COMPILER_LITTLE_C_COMPILER true
#	define XIEITE_COMPILER_LOCAL_C_COMPILER true
#endif

#if defined(THINKC3) || defined(THINKC4)
#	undef XIEITE_COMPILER_LIGHTSPEED_C
#	undef XIEITE_COMPILER_THINK_C
#	define XIEITE_COMPILER_LIGHTSPEED_C true
#	define XIEITE_COMPILER_THINK_C true
#endif

#ifdef __llvm__
#	undef XIEITE_COMPILER_LLVM
#	define XIEITE_COMPILER_LLVM true
#endif

#if defined(__MRC__) || defined(MPW_C) || defined(MPW_CPLUS)
#	undef XIEITE_COMPILER_MACINTOSH_PROGRAMMERS_WORKSHOP
#	undef XIEITE_COMPILER_MPW
#	define XIEITE_COMPILER_MACINTOSH_PROGRAMMERS_WORKSHOP true
#	define XIEITE_COMPILER_MPW true
#endif

#if false
#	undef XIEITE_COMPILER_MARK_WILLIAMS_C
#	define XIEITE_COMPILER_MARK_WILLIAMS_C true
#endif

#if false
#	undef XIEITE_COMPILER_MCC
#	define XIEITE_COMPILER_MCC true
#endif

#if false
#	undef XIEITE_COMPILER_MEGAMAX_C
#	define XIEITE_COMPILER_MEGAMAX_C true
#endif

#ifdef __HIGHC__
#	undef XIEITE_COMPILER_METAWARE_HIGH_C_CPP
#	define XIEITE_COMPILER_METAWARE_HIGH_C_CPP true
#endif

#ifdef _MSC_VER
#	undef XIEITE_COMPILER_MICROSOFT_VISUAL_CPP
#	undef XIEITE_COMPILER_MSVC
#	define XIEITE_COMPILER_MICROSOFT_VISUAL_CPP true
#	define XIEITE_COMPILER_MSVC true
#endif

#ifdef _MRI
#	undef XIEITE_COMPILER_MICROTEC_C_CPP
#	define XIEITE_COMPILER_MICROTEC_C_CPP true
#endif

#if defined(__NDPC__) || defined(__NDPX__)
#	undef XIEITE_COMPILER_MICROWAY_NPC_C
#	define XIEITE_COMPILER_MICROWAY_NPC_C true
#endif

#if false
#	undef XIEITE_COMPILER_MIKROC_COMPILER
#	define XIEITE_COMPILER_MIKROC_COMPILER true
#endif

#ifdef __MINGW32__
#	undef XIEITE_COMPILER_MINGW
#	undef XIEITE_COMPILER_MINGW32
#	define XIEITE_COMPILER_MINGW true
#	define XIEITE_COMPILER_MINGW32 true
#endif

#ifdef __MINGW64__
#	undef XIEITE_COMPILER_MINGW_W64
#	define XIEITE_COMPILER_MINGW_W64 true
#endif

#if defined(__sgi) || defined(sgi)
#	undef XIEITE_COMPILER_MIPSPRO
#	undef XIEITE_COMPILER_OPEN64
#	define XIEITE_COMPILER_MIPSPRO true
#	define XIEITE_COMPILER_OPEN64 true
#endif

#ifdef MIRACLE
#	undef XIEITE_COMPILER_MIRACLE_C
#	define XIEITE_COMPILER_MIRACLE_C true
#endif

#ifdef __CC_NORCROFT
#	undef XIEITE_COMPILER_NORCROFT_C
#	define XIEITE_COMPILER_NORCROFT_C true
#endif

#ifdef __NWCC__
#	undef XIEITE_COMPILER_NWCC
#	define XIEITE_COMPILER_NWCC true
#endif

#ifdef __WATCOMC__
#	undef XIEITE_COMPILER_OPEN_WATCOM_C_CPP
#	undef XIEITE_COMPILER_WATCOM_C_CPP
#	define XIEITE_COMPILER_OPEN_WATCOM_C_CPP true
#	define XIEITE_COMPILER_WATCOM_C_CPP true
#endif

#if defined(__ibmxl__) || defined(__xlC__) || defined(__IBMC__) || defined(__IBMCPP__)
#	undef XIEITE_COMPILER_OPEN_XL_C_CPP
#	undef XIEITE_COMPILER_XL_C_CPP
#	define XIEITE_COMPILER_OPEN_XL_C_CPP true
#	define XIEITE_COMPILER_XL_C_CPP true
#endif

#ifdef _SCO_DS
#	undef XIEITE_COMPILER_OPENSERVER
#	define XIEITE_COMPILER_OPENSERVER true
#endif

#ifdef __PACIFIC__
#	undef XIEITE_COMPILER_PACIFIC_C
#	define XIEITE_COMPILER_PACIFIC_C true
#endif

#ifdef _PACC_VER
#	undef XIEITE_COMPILER_PALM_C_CPP
#	define XIEITE_COMPILER_PALM_C_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_PCC
#	undef XIEITE_COMPILER_PCCM
#	undef XIEITE_COMPILER_PORTABLE_C_COMPILER
#	define XIEITE_COMPILER_PCC true
#	define XIEITE_COMPILER_PCCM true
#	define XIEITE_COMPILER_PORTABLE_C_COMPILER true
#endif

#ifdef __POCC__
#	undef XIEITE_COMPILER_PELLES_C
#	define XIEITE_COMPILER_PELLES_C true
#endif

#if false
#	undef XIEITE_COMPILER_PERSONAL_C_COMPILER
#	define XIEITE_COMPILER_PERSONAL_C_COMPILER true
#endif

#ifdef __PGI
#	undef XIEITE_COMPILER_PGI_C_CPP
#	undef XIEITE_COMPILER_PORTLAND_GROUP_C_CPP
#	define XIEITE_COMPILER_PGI_C_CPP true
#	define XIEITE_COMPILER_PORTLAND_GROUP_C_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_PICOC
#	define XIEITE_COMPILER_PICOC true
#endif

#ifdef ORA_PROC
#	undef XIEITE_COMPILER_PRO_C
#	define XIEITE_COMPILER_PRO_C true
#endif

#if false
#	undef XIEITE_COMPILER_PRO_C_CPP
#	define XIEITE_COMPILER_PRO_C_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_PRODEV_WORKSHOP
#	define XIEITE_COMPILER_PRODEV_WORKSHOP true
#endif

#if false
#	undef XIEITE_COMPILER_QUICKC
#	define XIEITE_COMPILER_QUICKC true
#endif

#if false
#	undef XIEITE_COMPILER_REALVIEW_COMPILATION_TOOLS
#	define XIEITE_COMPILER_REALVIEW_COMPILATION_TOOLS true
#endif

#if defined(__RENESAS__) || defined(__HITACHI__)
#	undef XIEITE_COMPILER_RENESAS_C_CPP
#	define XIEITE_COMPILER_RENESAS_C_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_RITCHIE_C_COMPILER
#	define XIEITE_COMPILER_RITCHIE_C_COMPILER true
#endif

#if false
#	undef XIEITE_COMPILER_SAS_C_CPP
#	define XIEITE_COMPILER_SAS_C_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_SCORE_C
#	define XIEITE_COMPILER_SCORE_C true
#endif

#if false
#	undef XIEITE_COMPILER_SCORE_CPP
#	define XIEITE_COMPILER_SCORE_CPP true
#endif

#ifdef SDCC
#	undef XIEITE_COMPILER_SDCC
#	undef XIEITE_COMPILER_SMALL_DEVICE_C_COMPILER
#	define XIEITE_COMPILER_SDCC true
#	define XIEITE_COMPILER_SMALL_DEVICE_C_COMPILER true
#endif

#if false
#	undef XIEITE_COMPILER_SEGGER_COMPILER
#	define XIEITE_COMPILER_SEGGER_COMPILER true
#endif

#if false
#	undef XIEITE_COMPILER_SMALL_C
#	define XIEITE_COMPILER_SMALL_C true
#endif

#ifdef __SNC__
#	undef XIEITE_COMPILER_SNC_COMPILER
#	define XIEITE_COMPILER_SNC_COMPILER true
#endif

#if false
#	undef XIEITE_COMPILER_STANFORD_CPP_COMPILER
#	define XIEITE_COMPILER_STANFORD_CPP_COMPILER true
#endif

#ifdef __VOSC__
#	undef XIEITE_COMPILER_STRATUS_VOS_C
#	define XIEITE_COMPILER_STRATUS_VOS_C true
#endif

#if false
#	undef XIEITE_COMPILER_SUBC
#	define XIEITE_COMPILER_SUBC true
#endif

#ifdef __SC__
#	undef XIEITE_COMPILER_DIGITAL_MARS_CPP
#	undef XIEITE_COMPILER_DMCPP
#	undef XIEITE_COMPILER_SYMANTEC_CPP
#	undef XIEITE_COMPILER_ZORTECH_CPP
#	define XIEITE_COMPILER_DIGITAL_MARS_CPP true
#	define XIEITE_COMPILER_DMCPP true
#	define XIEITE_COMPILER_SYMANTEC_CPP true
#	define XIEITE_COMPILER_ZORTECH_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_SYMBOLICS_C
#	define XIEITE_COMPILER_SYMBOLICS_C true
#endif

#if false
#	undef XIEITE_COMPILER_TANDEM_C
#	define XIEITE_COMPILER_TANDEM_C true
#endif

#if false
#	undef XIEITE_COMPILER_TANDEM_CPP
#	define XIEITE_COMPILER_TANDEM_CPP true
#endif

#if false
#	undef XIEITE_COMPILER_TASKING
#	define XIEITE_COMPILER_TASKING true
#endif

#if __TINYC__
#	undef XIEITE_COMPILER_TCC
#	undef XIEITE_COMPILER_TINY_C_COMPILER
#	undef XIEITE_COMPILER_TINYCC
#	define XIEITE_COMPILER_TCC true
#	define XIEITE_COMPILER_TINY_C_COMPILER true
#	define XIEITE_COMPILER_TINYCC true
#endif

#ifdef __TenDRA__
#	undef XIEITE_COMPILER_TENDRA
#	define XIEITE_COMPILER_TENDRA true
#endif

#if defined(__TI_COMPILER_VERSION__) || defined(_TMS320C6X)
#	undef XIEITE_COMPILER_TI_CGT
#	define XIEITE_COMPILER_TI_CGT true
#endif

#ifdef __TURBOC__
#	undef XIEITE_COMPILER_TURBO_C_CPP
#	define XIEITE_COMPILER_TURBO_C_CPP true
#endif

#ifdef _UCC
#	undef XIEITE_COMPILER_ULTIMATE_C_CPP
#	define XIEITE_COMPILER_ULTIMATE_C_CPP true
#endif

#ifdef __USLC__
#	undef XIEITE_COMPILER_UNIX_SYSTEM_LABORATORIES
#	undef XIEITE_COMPILER_USL_C
#	define XIEITE_COMPILER_UNIX_SYSTEM_LABORATORIES true
#	define XIEITE_COMPILER_USL_C true
#endif

#ifdef __VBCC__
#	undef XIEITE_COMPILER_VBCC
#	define XIEITE_COMPILER_VBCC true
#endif

#if false
#	undef XIEITE_COMPILER_VECTORC
#	define XIEITE_COMPILER_VECTORC true
#endif

#ifdef __DCC__
#	undef XIEITE_COMPILER_WIND_RIVER_DIAB_COMPILER
#	define XIEITE_COMPILER_WIND_RIVER_DIAB_COMPILER true
#endif

#if false
#	undef XIEITE_COMPILER_ZIG_C_CPP
#	define XIEITE_COMPILER_ZIG_C_CPP true
#endif
