#ifndef XIEITE_HEADER_MACROS_CONCATENATE
#	define XIEITE_HEADER_MACROS_CONCATENATE

#	define XIEITE_CONCATENATE_DIRECT_FORWARD(first_, second_) first_##second_

#	define XIEITE_CONCATENATE_FIRECT_REVERSE(first_, second_) second_##first_

#	define XIEITE_CONCATENATE(first_, second_) XIEITE_CONCATENATE_DIRECT_FORWARD(first_, second_)

#	define XIEITE_CONCATENATE_FIRST(first_) XIEITE_CONCATENATE_DIRECT_FORWARD(first_,

#	define XIEITE_CONCATENATE_SECOND(second_) XIEITE_CONCATENATE_DIRECT_REVERSE(second_,

#endif
