#ifndef XIEITE_HEADER_MACROS_FEATURE
#	define XIEITE_HEADER_MACROS_FEATURE

#	include "../macros/language_standard.hpp"

#	if XIEITE_LANGUAGE_STANDARD_CPP_2011
#		include <cstdint>
#	else
#		include <stdint.h>
#	endif

#	define XIEITE_FEATURE_SIGNED_INTEGER_8 0
#	define XIEITE_FEATURE_UNSIGNED_INTEGER_8 0
#	define XIEITE_FEATURE_SIGNED_INTEGER_16 0
#	define XIEITE_FEATURE_UNSIGNED_INTEGER_16 0
#	define XIEITE_FEATURE_SIGNED_INTEGER_32 0
#	define XIEITE_FEATURE_UNSIGNED_INTEGER_32 0
#	define XIEITE_FEATURE_SIGNED_INTEGER_64 0
#	define XIEITE_FEATURE_UNSIGNED_INTEGER_64 0
#	define XIEITE_FEATURE_SIGNED_INTEGER_128 0
#	define XIEITE_FEATURE_UNSIGNED_INTEGER_128 0
#	define XIEITE_FEATURE_FLOATING_POINT_16 0
#	define XIEITE_FEATURE_FLOATING_POINT_32 0
#	define XIEITE_FEATURE_FLOATING_POINT_64 0
#	define XIEITE_FEATURE_FLOATING_POINT_128 0
#	define XIEITE_FEATURE_FLOATING_POINT_BRAIN 0

#	ifdef INT8_MAX
#		undef XIEITE_FEATURE_SIGNED_INTEGER_8
#		define XIEITE_FEATURE_SIGNED_INTEGER_8 1
#	endif

#	ifdef UINT8_MAX
#		undef XIEITE_FEATURE_UNSIGNED_INTEGER_8
#		define XIEITE_FEATURE_UNSIGNED_INTEGER_8 1
#	endif

#	ifdef INT16_MAX
#		undef XIEITE_FEATURE_SIGNED_INTEGER_16
#		define XIEITE_FEATURE_SIGNED_INTEGER_16 1
#	endif

#	ifdef UINT16_MAX
#		undef XIEITE_FEATURE_UNSIGNED_INTEGER_16
#		define XIEITE_FEATURE_UNSIGNED_INTEGER_16 1
#	endif

#	ifdef INT32_MAX
#		undef XIEITE_FEATURE_SIGNED_INTEGER_32
#		define XIEITE_FEATURE_SIGNED_INTEGER_32 1
#	endif

#	ifdef UINT32_MAX
#		undef XIEITE_FEATURE_UNSIGNED_INTEGER_32
#		define XIEITE_FEATURE_UNSIGNED_INTEGER_32 1
#	endif

#	ifdef INT64_MAX
#		undef XIEITE_FEATURE_SIGNED_INTEGER_64
#		define XIEITE_FEATURE_SIGNED_INTEGER_64 1
#	endif

#	ifdef UINT64_MAX
#		undef XIEITE_FEATURE_UNSIGNED_INTEGER_64
#		define XIEITE_FEATURE_UNSIGNED_INTEGER_64 1
#	endif

#	if defined(__SIZEOF_INT128__) || __has_include(<__msvc_int128.hpp>)
#		undef XIEITE_FEATURE_SIGNED_INTEGER_128
#		define XIEITE_FEATURE_SIGNED_INTEGER_128 1
#		undef XIEITE_FEATURE_UNSIGNED_INTEGER_128
#		define XIEITE_FEATURE_UNSIGNED_INTEGER_128 1
#	endif

#	ifdef __STDCPP_FLOAT16_T__
#		undef XIEITE_FEATURE_FLOATING_POINT_16
#		define XIEITE_FEATURE_FLOATING_POINT_16 1
#	endif

#	ifdef __STDCPP_FLOAT32_T__
#		undef XIEITE_FEATURE_FLOATING_POINT_32
#		define XIEITE_FEATURE_FLOATING_POINT_32 1
#	endif

#	ifdef __STDCPP_FLOAT64_T__
#		undef XIEITE_FEATURE_FLOATING_POINT_64
#		define XIEITE_FEATURE_FLOATING_POINT_64 1
#	endif

#	ifdef __STDCPP_FLOAT128_T__
#		undef XIEITE_FEATURE_FLOATING_POINT_128
#		define XIEITE_FEATURE_FLOATING_POINT_128 1
#	endif

#	ifdef __STDCPP_BFLOAT16_T__
#		undef XIEITE_FEATURE_FLOATING_POINT_BRAIN
#		define XIEITE_FEATURE_FLOATING_POINT_BRAIN 1
#	endif

#endif
