#ifndef XIEITE_HEADER_MACROS_FUNCTION_SIGNATURE
#	define XIEITE_HEADER_MACROS_FUNCTION_SIGNATURE

#	include "../macros/COMPILER_TYPE.hpp"

#	define XIEITE_FUNCTION_SIGNATURE __func__

#	if XIEITE_COMPILER_TYPE_GCC || XIEITE_COMPILER_TYPE_LLVM
#		undef XIEITE_FUNCTION_SIGNATURE
#		define XIEITE_FUNCTION_SIGNATURE __PRETTY_FUNCTION__
#	endif

#	if XIEITE_COMPILER_TYPE_MSVC
#		undef XIEITE_FUNCTION_SIGNATURE
#		define XIEITE_FUNCTION_SIGNATURE __FUNCSIG__
#	endif

// Thanks to eightfold for original code

#endif
