#ifndef XIEITE_HEADER_MACROS_LANGUAGE_STANDARD
#	define XIEITE_HEADER_MACROS_LANGUAGE_STANDARD

#	undef XIEITE_LANGUAGE_STANDARD_C_1978
#	undef XIEITE_LANGUAGE_STANDARD_C_1989
#	undef XIEITE_LANGUAGE_STANDARD_C_1990
#	undef XIEITE_LANGUAGE_STANDARD_C_1994
#	undef XIEITE_LANGUAGE_STANDARD_C_1999
#	undef XIEITE_LANGUAGE_STANDARD_C_2011
#	undef XIEITE_LANGUAGE_STANDARD_C_2018
#	undef XIEITE_LANGUAGE_STANDARD_C_2020
#	undef XIEITE_LANGUAGE_STANDARD_CPP_1998
#	undef XIEITE_LANGUAGE_STANDARD_CPP_2011
#	undef XIEITE_LANGUAGE_STANDARD_CPP_2014
#	undef XIEITE_LANGUAGE_STANDARD_CPP_2017
#	undef XIEITE_LANGUAGE_STANDARD_CPP_2020
#	undef XIEITE_LANGUAGE_STANDARD_CPP_2023
#	undef XIEITE_LANGUAGE_STANDARD_CPP_CLI
#	undef XIEITE_LANGUAGE_STANDARD_CPP_EMBEDDED

#	if true
#		define XIEITE_LANGUAGE_STANDARD_C_1978
#	endif

#	ifdef __STDC__
#		define XIEITE_LANGUAGE_STANDARD_C_1989 true
#		define XIEITE_LANGUAGE_STANDARD_C_1990 true
#	endif

#	ifdef __STDC_VERSION__
#		if __STDC_VERSION__ >= 199409
#			define XIEITE_LANGUAGE_STANDARD_C_1994 true
#		endif

#		if __STDC_VERSION__ >= 199901
#			define XIEITE_LANGUAGE_STANDARD_C_1999 true
#		endif

#		if __STDC_VERSION__ >= 201112
#			define XIEITE_LANGUAGE_STANDARD_C_2011 true
#		endif

#		if __STDC_VERSION__ >= 201710
#			define XIEITE_LANGUAGE_STANDARD_C_2018 true
#		endif

#		if __STDC_VERSION__ >= 202000
#			define XIEITE_LANGUAGE_STANDARD_C_2020 true
#		endif
#	endif

#	ifdef __cplusplus
#		if __cplusplus >= 199711
#			define XIEITE_LANGUAGE_STANDARD_CPP_1998 true
#		endif

#		if __cplusplus >= 201103
#			define XIEITE_LANGUAGE_STANDARD_CPP_2011 true
#		endif

#		if __cplusplus >= 201402
#			define XIEITE_LANGUAGE_STANDARD_CPP_2014 true
#		endif

#		if __cplusplus >= 201703
#			define XIEITE_LANGUAGE_STANDARD_CPP_2017 true
#		endif

#		if __cplusplus >= 202002
#			define XIEITE_LANGUAGE_STANDARD_CPP_2020 true
#		endif

#		if __cplusplus >= 202302
#			define XIEITE_LANGUAGE_STANDARD_CPP_2023 true
#		endif
#	endif

#	if defined(__cplusplus_cli) && (__cplusplus_cli >= 200406)
#		define XIEITE_LANGUAGE_STANDARD_CPP_CLI true
#	endif

#	ifdef __embedded_cplusplus
#		define XIEITE_LANGUAGE_STANDARD_CPP_EMBEDDED true
#	endif

#endif
