#ifndef XIEITE_HEADER_MACROS_PLATFORM
#	define XIEITE_HEADER_MACROS_PLATFORM

#	define XIEITE_PLATFORM_TYPE_AEGIS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_AEGIS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_AEGIS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_AEGIS 0
#	define XIEITE_PLATFORM_TYPE_AIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_AIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_AIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_AIX 0
#	define XIEITE_PLATFORM_TYPE_AMIGAOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_AMIGAOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_AMIGAOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_AMIGAOS 0
#	define XIEITE_PLATFORM_TYPE_ANDROID 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_ANDROID 0
#	define XIEITE_PLATFORM_VERSION_MINOR_ANDROID 0
#	define XIEITE_PLATFORM_VERSION_PATCH_ANDROID 0
#	define XIEITE_PLATFORM_TYPE_BEOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_BEOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_BEOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_BEOS 0
#	define XIEITE_PLATFORM_TYPE_BLUE_GENE 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_BLUE_GENE 0
#	define XIEITE_PLATFORM_VERSION_MINOR_BLUE_GENE 0
#	define XIEITE_PLATFORM_VERSION_PATCH_BLUE_GENE 0
#	define XIEITE_PLATFORM_TYPE_BSD 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_BSD 0
#	define XIEITE_PLATFORM_VERSION_MINOR_BSD 0
#	define XIEITE_PLATFORM_VERSION_PATCH_BSD 0
#	define XIEITE_PLATFORM_TYPE_BSD_OS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_BSD_OS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_BSD_OS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_BSD_OS 0
#	define XIEITE_PLATFORM_TYPE_CONVEXOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_CONVEXOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_CONVEXOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_CONVEXOS 0
#	define XIEITE_PLATFORM_TYPE_DC_OSX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_DC_OSX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_DC_OSX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_DC_OSX 0
#	define XIEITE_PLATFORM_TYPE_DG_UX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_DG_UX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_DG_UX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_DG_UX 0
#	define XIEITE_PLATFORM_TYPE_DOMAIN_OS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_DOMAIN_OS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_DOMAIN_OS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_DOMAIN_OS 0
#	define XIEITE_PLATFORM_TYPE_DRAGONFLY 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_DRAGONFLY 0
#	define XIEITE_PLATFORM_VERSION_MINOR_DRAGONFLY 0
#	define XIEITE_PLATFORM_VERSION_PATCH_DRAGONFLY 0
#	define XIEITE_PLATFORM_TYPE_DYNIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_DYNIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_DYNIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_DYNIX 0
#	define XIEITE_PLATFORM_TYPE_ECOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_ECOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_ECOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_ECOS 0
#	define XIEITE_PLATFORM_TYPE_EMX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_EMX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_EMX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_EMX 0
#	define XIEITE_PLATFORM_TYPE_FREEBSD 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_FREEBSD 0
#	define XIEITE_PLATFORM_VERSION_MINOR_FREEBSD 0
#	define XIEITE_PLATFORM_VERSION_PATCH_FREEBSD 0
#	define XIEITE_PLATFORM_TYPE_GNU_HURD 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_GNU_HURD 0
#	define XIEITE_PLATFORM_VERSION_MINOR_GNU_HURD 0
#	define XIEITE_PLATFORM_VERSION_PATCH_GNU_HURD 0
#	define XIEITE_PLATFORM_TYPE_GNU_KFREEBSD 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_GNU_KFREEBSD 0
#	define XIEITE_PLATFORM_VERSION_MINOR_GNU_KFREEBSD 0
#	define XIEITE_PLATFORM_VERSION_PATCH_GNU_KFREEBSD 0
#	define XIEITE_PLATFORM_TYPE_GNU_LINUX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_GNU_LINUX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_GNU_LINUX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_GNU_LINUX 0
#	define XIEITE_PLATFORM_TYPE_HI_UX_MPP 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_HI_UX_MPP 0
#	define XIEITE_PLATFORM_VERSION_MINOR_HI_UX_MPP 0
#	define XIEITE_PLATFORM_VERSION_PATCH_HI_UX_MPP 0
#	define XIEITE_PLATFORM_TYPE_INTEGRITY 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_INTEGRITY 0
#	define XIEITE_PLATFORM_VERSION_MINOR_INTEGRITY 0
#	define XIEITE_PLATFORM_VERSION_PATCH_INTEGRITY 0
#	define XIEITE_PLATFORM_TYPE_INTERIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_INTERIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_INTERIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_INTERIX 0
#	define XIEITE_PLATFORM_TYPE_IRIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_IRIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_IRIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_IRIX 0
#	define XIEITE_PLATFORM_TYPE_LINUX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_LINUX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_LINUX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_LINUX 0
#	define XIEITE_PLATFORM_TYPE_LYNXOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_LYNXOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_LYNXOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_LYNXOS 0
#	define XIEITE_PLATFORM_TYPE_MACINTOSH 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_MACINTOSH 0
#	define XIEITE_PLATFORM_VERSION_MINOR_MACINTOSH 0
#	define XIEITE_PLATFORM_VERSION_PATCH_MACINTOSH 0
#	define XIEITE_PLATFORM_TYPE_MINIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_MINIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_MINIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_MINIX 0
#	define XIEITE_PLATFORM_TYPE_MORPHOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_MORPHOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_MORPHOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_MORPHOS 0
#	define XIEITE_PLATFORM_TYPE_MPE_IX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_MPE_IX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_MPE_IX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_MPE_IX 0
#	define XIEITE_PLATFORM_TYPE_MS_DOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_MS_DOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_MS_DOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_MS_DOS 0
#	define XIEITE_PLATFORM_TYPE_NETBSD 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_NETBSD 0
#	define XIEITE_PLATFORM_VERSION_MINOR_NETBSD 0
#	define XIEITE_PLATFORM_VERSION_PATCH_NETBSD 0
#	define XIEITE_PLATFORM_TYPE_NONSTOP 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_NONSTOP 0
#	define XIEITE_PLATFORM_VERSION_MINOR_NONSTOP 0
#	define XIEITE_PLATFORM_VERSION_PATCH_NONSTOP 0
#	define XIEITE_PLATFORM_TYPE_NUCLEUS_RTOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_NUCLEUS_RTOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_NUCLEUS_RTOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_NUCLEUS_RTOS 0
#	define XIEITE_PLATFORM_TYPE_OPENBSD 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_OPENBSD 0
#	define XIEITE_PLATFORM_VERSION_MINOR_OPENBSD 0
#	define XIEITE_PLATFORM_VERSION_PATCH_OPENBSD 0
#	define XIEITE_PLATFORM_TYPE_OPENSERVER 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_OPENSERVER 0
#	define XIEITE_PLATFORM_VERSION_MINOR_OPENSERVER 0
#	define XIEITE_PLATFORM_VERSION_PATCH_OPENSERVER 0
#	define XIEITE_PLATFORM_TYPE_OS_2 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_OS_2 0
#	define XIEITE_PLATFORM_VERSION_MINOR_OS_2 0
#	define XIEITE_PLATFORM_VERSION_PATCH_OS_2 0
#	define XIEITE_PLATFORM_TYPE_OS_400 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_OS_400 0
#	define XIEITE_PLATFORM_VERSION_MINOR_OS_400 0
#	define XIEITE_PLATFORM_VERSION_PATCH_OS_400 0
#	define XIEITE_PLATFORM_TYPE_OS_9 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_OS_9 0
#	define XIEITE_PLATFORM_VERSION_MINOR_OS_9 0
#	define XIEITE_PLATFORM_VERSION_PATCH_OS_9 0
#	define XIEITE_PLATFORM_TYPE_PALM_OS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_PALM_OS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_PALM_OS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_PALM_OS 0
#	define XIEITE_PLATFORM_TYPE_PLAN_9 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_PLAN_9 0
#	define XIEITE_PLATFORM_VERSION_MINOR_PLAN_9 0
#	define XIEITE_PLATFORM_VERSION_PATCH_PLAN_9 0
#	define XIEITE_PLATFORM_TYPE_QNX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_QNX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_QNX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_QNX 0
#	define XIEITE_PLATFORM_TYPE_SINIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_SINIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_SINIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_SINIX 0
#	define XIEITE_PLATFORM_TYPE_SOLARIS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_SOLARIS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_SOLARIS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_SOLARIS 0
#	define XIEITE_PLATFORM_TYPE_SYGWIN 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_SYGWIN 0
#	define XIEITE_PLATFORM_VERSION_MINOR_SYGWIN 0
#	define XIEITE_PLATFORM_VERSION_PATCH_SYGWIN 0
#	define XIEITE_PLATFORM_TYPE_SYLLABLE 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_SYLLABLE 0
#	define XIEITE_PLATFORM_VERSION_MINOR_SYLLABLE 0
#	define XIEITE_PLATFORM_VERSION_PATCH_SYLLABLE 0
#	define XIEITE_PLATFORM_TYPE_SYMBIAN 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_SYMBIAN 0
#	define XIEITE_PLATFORM_VERSION_MINOR_SYMBIAN 0
#	define XIEITE_PLATFORM_VERSION_PATCH_SYMBIAN 0
#	define XIEITE_PLATFORM_TYPE_SYSTEM_V 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_SYSTEM_V 0
#	define XIEITE_PLATFORM_VERSION_MINOR_SYSTEM_V 0
#	define XIEITE_PLATFORM_VERSION_PATCH_SYSTEM_V 0
#	define XIEITE_PLATFORM_TYPE_TRU64 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_TRU64 0
#	define XIEITE_PLATFORM_VERSION_MINOR_TRU64 0
#	define XIEITE_PLATFORM_VERSION_PATCH_TRU64 0
#	define XIEITE_PLATFORM_TYPE_ULTRIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_ULTRIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_ULTRIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_ULTRIX 0
#	define XIEITE_PLATFORM_TYPE_UNICOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_UNICOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_UNICOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_UNICOS 0
#	define XIEITE_PLATFORM_TYPE_UNICOS_MP 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_UNICOS_MP 0
#	define XIEITE_PLATFORM_VERSION_MINOR_UNICOS_MP 0
#	define XIEITE_PLATFORM_VERSION_PATCH_UNICOS_MP 0
#	define XIEITE_PLATFORM_TYPE_UNIX 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_UNIX 0
#	define XIEITE_PLATFORM_VERSION_MINOR_UNIX 0
#	define XIEITE_PLATFORM_VERSION_PATCH_UNIX 0
#	define XIEITE_PLATFORM_TYPE_UNIXWARE 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_UNIXWARE 0
#	define XIEITE_PLATFORM_VERSION_MINOR_UNIXWARE 0
#	define XIEITE_PLATFORM_VERSION_PATCH_UNIXWARE 0
#	define XIEITE_PLATFORM_TYPE_UTS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_UTS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_UTS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_UTS 0
#	define XIEITE_PLATFORM_TYPE_UWIN 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_UWIN 0
#	define XIEITE_PLATFORM_VERSION_MINOR_UWIN 0
#	define XIEITE_PLATFORM_VERSION_PATCH_UWIN 0
#	define XIEITE_PLATFORM_TYPE_VMS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_VMS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_VMS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_VMS 0
#	define XIEITE_PLATFORM_TYPE_VOS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_VOS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_VOS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_VOS 0
#	define XIEITE_PLATFORM_TYPE_VXWORKS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_VXWORKS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_VXWORKS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_VXWORKS 0
#	define XIEITE_PLATFORM_TYPE_WINDOWS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_WINDOWS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_WINDOWS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_WINDOWS 0
#	define XIEITE_PLATFORM_TYPE_WINDOWS_CE 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_WINDOWS_CE 0
#	define XIEITE_PLATFORM_VERSION_MINOR_WINDOWS_CE 0
#	define XIEITE_PLATFORM_VERSION_PATCH_WINDOWS_CE 0
#	define XIEITE_PLATFORM_TYPE_WIND_U 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_WIND_U 0
#	define XIEITE_PLATFORM_VERSION_MINOR_WIND_U 0
#	define XIEITE_PLATFORM_VERSION_PATCH_WIND_U 0
#	define XIEITE_PLATFORM_TYPE_Z_OS 0
#	define XIEITE_PLATFORM_VERSION_MAJOR_Z_OS 0
#	define XIEITE_PLATFORM_VERSION_MINOR_Z_OS 0
#	define XIEITE_PLATFORM_VERSION_PATCH_Z_OS 0

#	define XIEITE_PLATFORM_VERSION_LEAST(platform_, major_, minor_, patch_) (XIEITE_COMPILER_TYPE_##platform_ && ((XIEITE_PLATFORM_VERSION_MAJOR_##platform_ > (major_)) || (XIEITE_PLATFORM_VERSION_MAJOR_##platform_ == (major_)) && ((XIEITE_PLATFORM_VERSION_MINOR_##platform_ > (minor_)) || (XIEITE_PLATFORM_VERSION_MINOR_##platform_ == (minor_)) && (XIEITE_PLATFORM_VERSION_PATCH_##platform_ >= (patch_)))))
#	define XIEITE_PLATFORM_VERSION_MOST(platform_, major_, minor_, patch_) (XIEITE_COMPILER_TYPE_##platform_ && ((XIEITE_PLATFORM_VERSION_MAJOR_##platform_ < (major_)) || (XIEITE_PLATFORM_VERSION_MAJOR_##platform_ == (major_)) && ((XIEITE_PLATFORM_VERSION_MINOR_##platform_ < (minor_)) || (XIEITE_PLATFORM_VERSION_MINOR_##platform_ == (minor_)) && (XIEITE_PLATFORM_VERSION_PATCH_##platform_ <= (patch_)))))

#	ifdef aegis
#		undef XIEITE_PLATFORM_TYPE_AEGIS
#		define XIEITE_PLATFORM_TYPE_AEGIS 1
#	endif

#	ifdef _AIX
#		undef XIEITE_PLATFORM_TYPE_AIX
#		define XIEITE_PLATFORM_TYPE_AIX 1

#		if defined(_AIX3) || defined(_AIX32)
#			undef XIEITE_PLATFORM_VERSION_MAJOR_AIX
#			define XIEITE_PLATFORM_VERSION_MAJOR_AIX 3

#			undef XIEITE_PLATFORM_VERSION_MINOR_AIX
#			define XIEITE_PLATFORM_VERSION_MINOR_AIX 2
#		endif

#		ifdef _AIX41
#			undef XIEITE_PLATFORM_VERSION_MAJOR_AIX
#			define XIEITE_PLATFORM_VERSION_MAJOR_AIX 4

#			undef XIEITE_PLATFORM_VERSION_MINOR_AIX
#			define XIEITE_PLATFORM_VERSION_MINOR_AIX 1
#		endif

#		ifdef _AIX43
#			undef XIEITE_PLATFORM_VERSION_MAJOR_AIX
#			define XIEITE_PLATFORM_VERSION_MAJOR_AIX 4

#			undef XIEITE_PLATFORM_VERSION_MINOR_AIX
#			define XIEITE_PLATFORM_VERSION_MINOR_AIX 3
#		endif
#	endif

#	if defined(AMIGA) || defined(__amigaos__)
#		undef XIEITE_PLATFORM_TYPE_AMIGAOS
#		define XIEITE_PLATFORM_TYPE_AMIGAOS 1
#	endif

#	ifdef __ANDROID__
#		include <android/api-level.h>

#		undef XIEITE_PLATFORM_TYPE_ANDROID
#		define XIEITE_PLATFORM_TYPE_ANDROID 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_ANDROID
#		define XIEITE_PLATFORM_VERSION_MAJOR_ANDROID __ANDROID_API__
#	endif

#	ifdef __BEOS__
#		undef XIEITE_PLATFORM_TYPE_BEOS
#		define XIEITE_PLATFORM_TYPE_BEOS 1
#	endif

#	if defined(__bg__) || defined(__THW_BLUEGENE__)
#		undef XIEITE_PLATFORM_TYPE_BLUE_GENE
#		define XIEITE_PLATFORM_TYPE_BLUE_GENE 1
#	endif

#	if defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__) || defined(__bsdi__) || defined(__DragonFly__) || defined(_SYSTYPE_BSD)
#		include <sys/param.h>

#		undef XIEITE_PLATFORM_TYPE_BSD
#		define XIEITE_PLATFORM_TYPE_BSD 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_BSD
#		define XIEITE_PLATFORM_VERSION_MAJOR_BSD (BSD / 100)

#		undef XIEITE_PLATFORM_VERSION_MINOR_BSD
#		define XIEITE_PLATFORM_VERSION_MINOR_BSD (BSD % 100)
#	endif

#	ifdef __bsdi__
#		undef XIEITE_PLATFORM_TYPE_BSD_OS
#		define XIEITE_PLATFORM_TYPE_BSD_OS 1
#	endif

#	ifdef __convex__
#		undef XIEITE_PLATFORM_TYPE_CONVEXOS
#		define XIEITE_PLATFORM_TYPE_CONVEXOS 1
#	endif

#	ifdef pyr
#		undef XIEITE_PLATFORM_TYPE_DC_OSX
#		define XIEITE_PLATFORM_TYPE_DC_OSX 1
#	endif

#	if defined(DGUX) || defined(__DGUX__) || defined(__dgux__)
#		undef XIEITE_PLATFORM_TYPE_DG_UX
#		define XIEITE_PLATFORM_TYPE_DG_UX 1
#	endif

#	ifdef apollo
#		undef XIEITE_PLATFORM_TYPE_DOMAIN_OS
#		define XIEITE_PLATFORM_TYPE_DOMAIN_OS 1
#	endif

#	ifdef __DragonFly__
#		undef XIEITE_PLATFORM_TYPE_DRAGONFLY
#		define XIEITE_PLATFORM_TYPE_DRAGONFLY 1
#	endif

#	if defined(_SEQUENT_) || defined(sequent)
#		undef XIEITE_PLATFORM_TYPE_DYNIX
#		define XIEITE_PLATFORM_TYPE_DYNIX 1
#	endif

#	ifdef __ECOS
#		undef XIEITE_PLATFORM_TYPE_ECOS
#		define XIEITE_PLATFORM_TYPE_ECOS 1
#	endif

#	ifdef __EMX__
#		undef XIEITE_PLATFORM_TYPE_EMX
#		define XIEITE_PLATFORM_TYPE_EMX 1
#	endif

#	if defined(__FreeBSD__) || defined(__FreeBSD_kernel__)
#		include <sys/param.h>

#		undef XIEITE_PLATFORM_TYPE_FREEBSD
#		define XIEITE_PLATFORM_TYPE_FREEBSD 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_FREEBSD
#		define XIEITE_PLATFORM_VERSION_MAJOR_FREEBSD (__FreeBSD_version / 100000)

#		undef XIEITE_PLATFORM_VERSION_MINOR_FREEBSD
#		define XIEITE_PLATFORM_VERSION_MINOR_FREEBSD (__FreeBSD_version / 10000 % 10)

#		undef XIEITE_PLATFORM_VERSION_PATCH_FREEBSD
#		define XIEITE_PLATFORM_VERSION_PATCH_FREEBSD (__FreeBSD_version % 10000)
#	endif

#	if defined(__GNU__) || defined(__gnu_hurd__)
#		undef XIEITE_PLATFORM_TYPE_GNU_HURD
#		define XIEITE_PLATFORM_TYPE_GNU_HURD 1
#	endif

#	if defined(__FreeBSD_kernel__) && defined(__GLIBC__)
#		undef XIEITE_PLATFORM_TYPE_GNU_KFREEBSD
#		define XIEITE_PLATFORM_TYPE_GNU_KFREEBSD 1
#	endif

#	ifdef __gnu_linux__
#		undef XIEITE_PLATFORM_TYPE_GNU_LINUX
#		define XIEITE_PLATFORM_TYPE_GNU_LINUX 1
#	endif

#	ifdef __hiuxmpp
#		undef XIEITE_PLATFORM_TYPE_HI_UX_MPP
#		define XIEITE_PLATFORM_TYPE_HI_UX_MPP 1
#	endif

#	ifdef __INTEGRITY
#		undef XIEITE_PLATFORM_TYPE_INTEGRITY
#		define XIEITE_PLATFORM_TYPE_INTEGRITY 1
#	endif

#	ifdef __INTERIX
#		undef XIEITE_PLATFORM_TYPE_INTERIX
#		define XIEITE_PLATFORM_TYPE_INTERIX 1
#	endif

#	if defined(sgi) || defined(__sgi)
#		undef XIEITE_PLATFORM_TYPE_IRIX
#		define XIEITE_PLATFORM_TYPE_IRIX 1
#	endif

#	ifdef __linux__
#		undef XIEITE_PLATFORM_TYPE_LINUX
#		define XIEITE_PLATFORM_TYPE_LINUX 1
#	endif

#	ifdef __Lynx__
#		undef XIEITE_PLATFORM_TYPE_LYNXOS
#		define XIEITE_PLATFORM_TYPE_LYNXOS 1
#	endif

#	if defined(macintosh) || defined(Macintosh) || defined(__APPLE__) && defined(__MACH__)
#		undef XIEITE_PLATFORM_TYPE_MACINTOSH
#		define XIEITE_PLATFORM_TYPE_MACINTOSH 1
#	endif

#	ifdef __minix
#		undef XIEITE_PLATFORM_TYPE_MINIX
#		define XIEITE_PLATFORM_TYPE_MINIX 1
#	endif

#	ifdef __MORPHOS__
#		undef XIEITE_PLATFORM_TYPE_MORPHOS
#		define XIEITE_PLATFORM_TYPE_MORPHOS 1
#	endif

#	if defined(mpeix) || defined(__mpexl)
#		undef XIEITE_PLATFORM_TYPE_MPE_IX
#		define XIEITE_PLATFORM_TYPE_MPE_IX 1
#	endif

#	if defined(MSDOS) || defined(__MSDOS__) || defined(_MSDOS) || defined(__DOS__)
#		undef XIEITE_PLATFORM_TYPE_MS_DOS
#		define XIEITE_PLATFORM_TYPE_MS_DOS 1
#	endif

#	ifdef __NetBSD__
#		include <sys/param.h>

#		undef XIEITE_PLATFORM_TYPE_NETBSD
#		define XIEITE_PLATFORM_TYPE_NETBSD 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_NETBSD
#		define XIEITE_PLATFORM_VERSION_MAJOR_NETBSD (__NetBSD_version__ / 100000000)

#		undef XIEITE_PLATFORM_VERSION_MINOR_NETBSD
#		define XIEITE_PLATFORM_VERSION_MINOR_NETBSD (__NetBSD_version__ / 1000000 % 100)

#		undef XIEITE_PLATFORM_VERSION_PATCH_NETBSD
#		define XIEITE_PLATFORM_VERSION_PATCH_NETBSD (__NetBSD_version__ / 100 % 100)
#	endif

#	ifdef __TANDEM
#		undef XIEITE_PLATFORM_TYPE_NONSTOP
#		define XIEITE_PLATFORM_TYPE_NONSTOP 1
#	endif

#	ifdef __nucleus__
#		undef XIEITE_PLATFORM_TYPE_NUCLEUS_RTOS
#		define XIEITE_PLATFORM_TYPE_NUCLEUS_RTOS 1
#	endif

#	ifdef __OpenBSD__
#		undef XIEITE_PLATFORM_TYPE_OPENBSD
#		define XIEITE_PLATFORM_TYPE_OPENBSD 1
#	endif

#	if defined(M_I386) || defined(M_XENIX) || defined(_SCO_DS)
#		undef XIEITE_PLATFORM_TYPE_OPENSERVER
#		define XIEITE_PLATFORM_TYPE_OPENSERVER 1
#	endif

#	if defined(OS2) || defined(_OS2) || defined(__OS2__) || defined(__TOS_OS2__)
#		undef XIEITE_PLATFORM_TYPE_OS_2
#		define XIEITE_PLATFORM_TYPE_OS_2 1
#	endif

#	ifdef __OS400__
#		undef XIEITE_PLATFORM_TYPE_OS_400
#		define XIEITE_PLATFORM_TYPE_OS_400 1
#	endif

#	if defined(__OS9000) || defined(_OSK)
#		undef XIEITE_PLATFORM_TYPE_OS_9
#		define XIEITE_PLATFORM_TYPE_OS_9 1
#	endif

#	ifdef __palmos__
#		undef XIEITE_PLATFORM_TYPE_PALM_OS
#		define XIEITE_PLATFORM_TYPE_PALM_OS 1
#	endif

#	ifdef EPLAN9
#		undef XIEITE_PLATFORM_TYPE_PLAN_9
#		define XIEITE_PLATFORM_TYPE_PLAN_9 1
#	endif

#	if defined(__QNX__) || defined(__QNXNTO__)
#		include <sys/neutrino.h>

#		undef XIEITE_PLATFORM_TYPE_QNX
#		define XIEITE_PLATFORM_TYPE_QNX 1

#		ifdef __QNXNTO__
#			undef XIEITE_PLATFORM_VERSION_MAJOR_QNX
#			define XIEITE_PLATFORM_VERSION_MAJOR_QNX (_NTO_VERSION / 100)

#			undef XIEITE_PLATFORM_VERSION_MINOR_QNX
#			define XIEITE_PLATFORM_VERSION_MINOR_QNX (_NTO_VERSION / 10 % 10)

#			undef XIEITE_PLATFORM_VERSION_PATCH_QNX
#			define XIEITE_PLATFORM_VERSION_PATCH_QNX (_NTO_VERSION % 10)
#		endif
#	endif

#	ifdef sinux
#		undef XIEITE_PLATFORM_TYPE_SINIX
#		define XIEITE_PLATFORM_TYPE_SINIX 1
#	endif

#	if defined(sun) || defined(__sun)
#		undef XIEITE_PLATFORM_TYPE_SOLARIS
#		define XIEITE_PLATFORM_TYPE_SOLARIS 1
#	endif

#	ifdef __SYGWIN__
#		undef XIEITE_PLATFORM_TYPE_SYGWIN
#		define XIEITE_PLATFORM_TYPE_SYGWIN 1
#	endif

#	ifdef __SYLLABLE__
#		undef XIEITE_PLATFORM_TYPE_SYLLABLE
#		define XIEITE_PLATFORM_TYPE_SYLLABLE 1
#	endif

#	ifdef __SYMBIAN32__
#		undef XIEITE_PLATFORM_TYPE_SYMBIAN
#		define XIEITE_PLATFORM_TYPE_SYMBIAN 1
#	endif

#	if defined(__sysv__) || defined(__SVR4) || defined(__svr4__) || defined(_SYSTYPE_SVR4)
#		undef XIEITE_PLATFORM_TYPE_SYSTEM_V
#		define XIEITE_PLATFORM_TYPE_SYSTEM_V 1
#	endif

#	if defined(__osf__) || defined(__osf)
#		undef XIEITE_PLATFORM_TYPE_TRU64
#		define XIEITE_PLATFORM_TYPE_TRU64 1
#	endif

#	if defined(ultrix) || defined(__ultrix) || defined(__ultrix__) || defined(unix) && defined(vax)
#		undef XIEITE_PLATFORM_TYPE_ULTRIX
#		define XIEITE_PLATFORM_TYPE_ULTRIX 1
#	endif

#	ifdef _UNICOS
#		undef XIEITE_PLATFORM_TYPE_UNICOS
#		define XIEITE_PLATFORM_TYPE_UNICOS 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_UNICOS
#		define XIEITE_PLATFORM_VERSION_MAJOR_UNICOS _UNICOS
#	endif

#	if defined(_CRAY) || defined(__crayx1)
#		undef XIEITE_PLATFORM_TYPE_UNICOS_MP
#		define XIEITE_PLATFORM_TYPE_UNICOS_MP 1
#	endif

#	if defined(__unix__) || defined(__unix)
#		undef XIEITE_PLATFORM_TYPE_UNIX
#		define XIEITE_PLATFORM_TYPE_UNIX 1
#	endif

#	if defined(sco) || defined(_UNIXWARE7)
#		undef XIEITE_PLATFORM_TYPE_UNIXWARE
#		define XIEITE_PLATFORM_TYPE_UNIXWARE 1
#	endif

#	ifdef UTS
#		undef XIEITE_PLATFORM_TYPE_UTS
#		define XIEITE_PLATFORM_TYPE_UTS 1
#	endif

#	ifdef _UWIN
#		undef XIEITE_PLATFORM_TYPE_UWIN
#		define XIEITE_PLATFORM_TYPE_UWIN 1
#	endif

#	if defined(VMS) || defined(__VMS)
#		undef XIEITE_PLATFORM_TYPE_VMS
#		define XIEITE_PLATFORM_TYPE_VMS 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_VMS
#		define XIEITE_PLATFORM_VERSION_MAJOR_VMS (__VMS_VER / 10000000)

#		undef XIEITE_PLATFORM_VERSION_MINOR_VMS
#		define XIEITE_PLATFORM_VERSION_MINOR_VMS (__VMS_VER / 100000 % 100)

#		undef XIEITE_PLATFORM_VERSION_PATCH_VMS
#		define XIEITE_PLATFORM_VERSION_PATCH_VMS (__VMS_VER / 100 % 100)
#	endif

#	ifdef __VOS__
#		undef XIEITE_PLATFORM_TYPE_VOS
#		define XIEITE_PLATFORM_TYPE_VOS 1

#		undef XIEITE_PALTFORM_VERSION_MAJOR_VOS
#		define XIEITE_PLATFORM_VERSION_MAJOR_VOS __VOS__
#	endif

#	if defined(__VXWORKS__) || defined(__vxworks)
#		include <version.h>

#		undef XIEITE_PLATFORM_TYPE_VXWORKS
#		define XIEITE_PLATFORM_TYPE_VXWORKS 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_VXWORKS
#		define XIEITE_PLATFORM_VERSION_MAJOR_VXWORKS _WRS_VXWORKS_MAJOR

#		undef XIEITE_PLATFORM_VERSION_MINOR_VXWORKS
#		define XIEITE_PLATFORM_VERSION_MINOR_VXWORKS _WRS_VXWORKS_MINOR

#		undef XIEITE_PLATFORM_VERSION_PATCH_VXWORKS
#		define XIEITE_PLATFORM_VERSION_PATCH_VXWORKS _WRS_VXWORKS_MAINT
#	endif

#	if defined(_WIN16) || defined(_WIN32) || defined(_WIN64) || defined(__WIN32__) || defined(__TOS_WIN__) || defined(__WINDOWS__)
#		undef XIEITE_PLATFORM_TYPE_WINDOWS
#		define XIEITE_PLATFORM_TYPE_WINDOWS 1
#	endif

#	ifdef _WIN32_WCE
#		undef XIEITE_PLATFORM_TYPE_WINDOWS_CE
#		define XIEITE_PLATFORM_TYPE_WINDOWS_CE 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_WINDOWS_CE
#		define XIEITE_PLATFORM_VERSION_MAJOR_WINDOWS_CE (_WIN32_WCE / 100)

#		undef XIEITE_PLATFORM_VERSION_MINOR_WINDOWS_CE
#		define XIEITE_PLATFORM_VERSION_MINOR_WINDOWS_CE (_WIN32_WCE % 100)
#	endif

#	ifdef _WINDU_SOURCE
#		undef XIEITE_PLATFORM_TYPE_WIND_U
#		define XIEITE_PLATFORM_TYPE_WIND_U 1

#		undef XIEITE_PLATFORM_VERSION_MAJOR_WIND_U
#		define XIEITE_PLATFORM_VERSION_MAJOR_WIND_U (_WINDU_SOURCE / 0x10000)

#		undef XIEITE_PLATFORM_VERSION_MINOR_WIND_U
#		define XIEITE_PLATFORM_VERSION_MINOR_WIND_U (_WINDU_SOURCE / 0x100 % 0x100)

#		undef XIEITE_PLATFORM_VERSION_PATCH_WIND_U
#		define XIEITE_PLATFORM_VERSION_PATCH_WIND_U (_WINDU_SOURCE % 0x100)
#	endif

#	if defined(__MVS__) || defined(__HOS_MVS__) || defined(__TOS_MVS__)
#		undef XIEITE_PLATFORM_TYPE_Z_OS
#		define XIEITE_PLATFORM_TYPE_Z_OS 1
#	endif
#endif

// https://sourceforge.net/p/predef/wiki/OperatingSystems/
// TODO: Somehow complete `XIEITE_PLATFORM_VERSION_LEAST` and `XIEITE_PLATFORM_VERSION_MOST` to account for platforms of which it is unrealistic to list all possible versions
