#ifndef XIEITE_HEADER_MACROS_STANDARD_LANGUAGE
#	define XIEITE_HEADER_MACROS_STANDARD_LANGUAGE

#	define XIEITE_STANDARD_LANGUAGE_C_1989 false
#	define XIEITE_STANDARD_LANGUAGE_C_1990 false
#	define XIEITE_STANDARD_LANGUAGE_C_1994 false
#	define XIEITE_STANDARD_LANGUAGE_C_1999 false
#	define XIEITE_STANDARD_LANGUAGE_C_2011 false
#	define XIEITE_STANDARD_LANGUAGE_C_2018 false
#	define XIEITE_STANDARD_LAMGUAGE_C_2020 false
#	define XIEITE_STANDARD_LANGUAGE_CPP_1998 false
#	define XIEITE_STANDARD_LANGUAGE_CPP_2011 false
#	define XIEITE_STANDARD_LANGUAGE_CPP_2014 false
#	define XIEITE_STANDARD_LANGUAGE_CPP_2017 false
#	define XIEITE_STANDARD_LANGUAGE_CPP_2020 false
#	define XIEITE_STANDARD_LANGUAGE_CPP_2023 false
#	define XIEITE_STANDARD_LANGUAGE_CPP_CLI false
#	define XIEITE_STANDARD_LANGUAGE_CPP_EMBEDDED false

#	ifdef __STDC__
#		undef XIEITE_STANDARD_LANGUAGE_C_1989
#		define XIEITE_STANDARD_LANGUAGE_C_1989 true

#		undef XIEITE_STANDARD_LANGUAGE_C_1990
#		define XIEITE_STANDARD_LANGUAGE_C_1990 true
#	endif

#	ifdef __STDC_VERSION__
#		if (__STDC_VERSION__ >= 199409)
#			undef XIEITE_STANDARD_LANGUAGE_C_1994
#			define XIEITE_STANDARD_LANGUAGE_C_1994 true
#		endif

#		if (__STDC_VERSION__ >= 199901)
#			undef XIEITE_STANDARD_LANGUAGE_C_1999
#			define XIEITE_STANDARD_LANGUAGE_C_1999 true
#		endif

#		if (__STDC_VERSION__ >= 201112)
#			undef XIEITE_STANDARD_LANGUAGE_C_2011
#			define XIEITE_STANDARD_LANGUAGE_C_2011 true
#		endif

#		if (__STDC_VERSION__ >= 201710)
#			undef XIEITE_STANDARD_LANGUAGE_C_2018
#			define XIEITE_STANDARD_LANGUAGE_C_2018 true
#		endif

#		if (__STDC_VERSION__ >= 202000)
#			undef XIEITE_STANDARD_LANGUAGE_C_2020
#			define XIEITE_STANDARD_LANGUAGE_C_2020 true
#		endif
#	endif

#	ifdef __cplusplus
#		if (__cplusplus >= 199711)
#			undef XIEITE_STANDARD_LANGUAGE_CPP_1998
#			define XIEITE_STANDARD_LANGUAGE_CPP_1998 true
#		endif

#		if (__cplusplus >= 201103)
#			undef XIEITE_STANDARD_LANGUAGE_CPP_2011
#			define XIEITE_STANDARD_LANGUAGE_CPP_2011 true
#		endif

#		if (__cplusplus >= 201402)
#			undef XIEITE_STANDARD_LANGUAGE_CPP_2014
#			define XIEITE_STANDARD_LANGUAGE_CPP_2014 true
#		endif

#		if (__cplusplus >= 201703)
#			undef XIEITE_STANDARD_LANGUAGE_CPP_2017
#			define XIEITE_STANDARD_LANGUAGE_CPP_2017 true
#		endif

#		if (__cplusplus >= 202002)
#			undef XIEITE_STANDARD_LANGUAGE_CPP_2020
#			define XIEITE_STANDARD_LANGUAGE_CPP_2020 true
#		endif

#		if (__cplusplus >= 202100)
#			undef XIEITE_STANDARD_LANGUAGE_CPP_2023
#			define XIEITE_STANDARD_LANGUAGE_CPP_2023 true
#		endif
#	endif

#	if defined(__cplusplus_cli) && (__cplusplus_cli >= 200406)
#		undef XIEITE_STANDARD_LANGUAGE_CPP_CLI
#		define XIEITE_STANDARD_LANGUAGE_CPP_CLI true
#	endif

#	ifdef __embedded_cplusplus
#		undef XIEITE_STANDARD_LANGUAGE_CPP_EMBEDDED
#		define XIEITE_STANDARD_LANGUAGE_CPP_EMBEDDED true
#	endif

#endif
