#ifndef XIEITE_HEADER_MACROS_STRINGIFY
#	define XIEITE_HEADER_MACROS_STRINGIFY

#	define XIEITE_STRINGIFY(...) XIEITE_STRINGIFY_INTERNAL(__VA_ARGS__)

#	define XIEITE_STRINGIFY_INTERNAL(...) #__VA_ARGS__

#endif
