#ifndef XIEITE_HEADER_MACROS_STRINGIFY
#	define XIEITE_HEADER_MACROS_STRINGIFY

#	define XIEITE_STRINGIFY(...) XIEITE_INTERNAL_STRINGIFY(__VA_ARGS__)

#	define XIEITE_INTERNAL_STRINGIFY(...) #__VA_ARGS__

#endif
