#ifndef XIEITE_HEADER__MACROS__STRINGIFY
#	define XIEITE_HEADER__MACROS__STRINGIFY

#	define XIEITE__STRINGIFY(...) XIEITE_INTERNAL_STRINGIFY(__VA_ARGS__)

#	define XIEITE_INTERNAL_STRINGIFY(...) #__VA_ARGS__

#endif
