#ifndef XIEITE_HEADER__MACROS__UNIQUE_TOKEN
#	define XIEITE_HEADER__MACROS__UNIQUE_TOKEN

#	include "../macros/CONCATENATE.hpp"

#	define XIEITE__UNIQUE_TOKEN XIEITE__CONCATENATE(XIEITE_INTERNAL__UNIQUE_TOKEN_, __COUNTER__)

#endif
