#ifndef XIEITE_HEADER_MACROS_UNIQUE_TOKEN
#	define XIEITE_HEADER_MACROS_UNIQUE_TOKEN

#	include "../macros/CONCATENATE.hpp"

#	define XIEITE_UNIQUE_TOKEN XIEITE_CONCATENATE(XIEITE_INTERNAL_UNIQUE_TOKEN_, __COUNTER__)

#endif
