#ifndef XIEITE_HEADER_MACROS_UNIX_STANDARD
#	define XIEITE_HEADER_MACROS_UNIX_STANDARD

#	include "../macros/platform.hpp"

#	if !XIEITE_PLATFORM_UNIX
#		error "Platform not supported"
#	endif

#	undef XIEITE_UNIX_STANDARD_POSIX_1988
#	undef XIEITE_UNIX_STANDARD_POSIX_1990
#	undef XIEITE_UNIX_STANDARD_POSIX_1993
#	undef XIEITE_UNIX_STANDARD_POSIX_1996
#	undef XIEITE_UNIX_STANDARD_POSIX_2001
#	undef XIEITE_UNIX_STANDARD_POSIX_2008
#	undef XIEITE_UNIX_STANDARD_POSIX_1992
#	undef XIEITE_UNIX_STANDARD_XOPEN_1989
#	undef XIEITE_UNIX_STANDARD_XOPEN_1992
#	undef XIEITE_UNIX_STANDARD_XOPEN_1995
#	undef XIEITE_UNIX_STANDARD_XOPEN_1998
#	undef XIEITE_UNIX_STANDARD_XOPEN_2003
#	undef XIEITE_UNIX_STANDARD_XOPEN_2008
#	undef XIEITE_UNIX_STANDARD_LSB

#	include <unistd.h>

#	ifdef _POSIX_VERSION
#		if _POSIX_VERSION >= 198808
#			define XIEITE_UNIX_STANDARD_POSIX_1988 1
#		endif

#		if _POSIX_VERSION >= 199009
#			define XIEITE_UNIX_STANDARD_POSIX_1990 1
#		endif

#		if _POSIX_VERSION >= 199309
#			define XIEITE_UNIX_STANDARD_POSIX_1993 1
#		endif

#		if _POSIX_VERSION >= 199506
#			define XIEITE_UNIX_STANDARD_POSIX_1996 1
#		endif

#		if _POSIX_VERSION >= 200112
#			define XIEITE_UNIX_STANDARD_POSIX_2001 1
#		endif

#		if _POSIX_VERSION >= 200809
#			define XIEITE_UNIX_STANDARD_POSIX_2008 1
#		endif
#	endif

#	ifdef _POSIX2_C_VERSION
#		if _POSIX2_C_VERSION >= 199209
#			define XIEITE_UNIX_STANDARD_POSIX_1992 1
#		endif
#	endif

#	ifdef _XOPEN_VERSION
#		if _XOPEN_VERSION >= 3
#			define XIEITE_UNIX_STANDARD_XOPEN_1989 1
#		endif

#		if _XOPEN_VERSION >= 4
#			define XIEITE_UNIX_STANDARD_XOPEN_1992 1
#		endif

#		if (_XOPEN_VERSION >= 4) && defined(_XOPEN_UNIX)
#			define XIEITE_UNIX_STANDARD_XOPEN_1995 1
#		endif

#		if _XOPEN_VERSION >= 500
#			define XIEITE_UNIX_STANDARD_XOPEN_1998 1
#		endif

#		if _XOPEN_VERSION >= 600
#			define XIEITE_UNIX_STANDARD_XOPEN_2003 1
#		endif

#		if _XOPEN_VERSION >= 700
#			define XIEITE_UNIX_STANDARD_XOPEN_2008 1
#		endif
#	endif

#	ifdef __LSB_VERSION__
#		define XIEITE_UNIX_STANDARD_LSB 1
#	endif

#endif
