#ifndef DETAIL_XIEITE_HEADER_PP_CM
#	define DETAIL_XIEITE_HEADER_PP_CM
#
#	include "../pp/eat.hpp"
#	include "../pp/paren.hpp"
#	include "../pp/scan.hpp"
#
#	define XIEITE_CM(...) XIEITE_SCAN(XIEITE_EAT XIEITE_LPAREN() DETAIL_XIEITE_CM_NEXT_0(__VA_ARGS__))
#
#	define DETAIL_XIEITE_CM_NEXT_0(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_1(DETAIL_XIEITE_CM_PASS_1(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_1(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_2(DETAIL_XIEITE_CM_PASS_2(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_2(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_3(DETAIL_XIEITE_CM_PASS_3(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_3(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_4(DETAIL_XIEITE_CM_PASS_4(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_4(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_5(DETAIL_XIEITE_CM_PASS_5(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_5(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_6(DETAIL_XIEITE_CM_PASS_6(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_6(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_7(DETAIL_XIEITE_CM_PASS_7(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_7(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_8(DETAIL_XIEITE_CM_PASS_8(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_8(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_9(DETAIL_XIEITE_CM_PASS_9(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_9(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_A(DETAIL_XIEITE_CM_PASS_A(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_A(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_B(DETAIL_XIEITE_CM_PASS_B(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_B(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_C(DETAIL_XIEITE_CM_PASS_C(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_C(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_D(DETAIL_XIEITE_CM_PASS_D(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_D(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_E(DETAIL_XIEITE_CM_PASS_E(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_E(_P, _fn, ...) DETAIL_XIEITE_CM_PASS_F(DETAIL_XIEITE_CM_PASS_F(XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_F(_P, _fn, ...) XIEITE_CM_FN_##_fn(, _P##__VA_ARGS__)
#	define DETAIL_XIEITE_CM_PASS_1(_x) DETAIL_XIEITE_CM_NEXT_1 _x
#	define DETAIL_XIEITE_CM_PASS_2(_x) DETAIL_XIEITE_CM_NEXT_2 _x
#	define DETAIL_XIEITE_CM_PASS_3(_x) DETAIL_XIEITE_CM_NEXT_3 _x
#	define DETAIL_XIEITE_CM_PASS_4(_x) DETAIL_XIEITE_CM_NEXT_4 _x
#	define DETAIL_XIEITE_CM_PASS_5(_x) DETAIL_XIEITE_CM_NEXT_5 _x
#	define DETAIL_XIEITE_CM_PASS_6(_x) DETAIL_XIEITE_CM_NEXT_6 _x
#	define DETAIL_XIEITE_CM_PASS_7(_x) DETAIL_XIEITE_CM_NEXT_7 _x
#	define DETAIL_XIEITE_CM_PASS_8(_x) DETAIL_XIEITE_CM_NEXT_8 _x
#	define DETAIL_XIEITE_CM_PASS_9(_x) DETAIL_XIEITE_CM_NEXT_9 _x
#	define DETAIL_XIEITE_CM_PASS_A(_x) DETAIL_XIEITE_CM_NEXT_A _x
#	define DETAIL_XIEITE_CM_PASS_B(_x) DETAIL_XIEITE_CM_NEXT_B _x
#	define DETAIL_XIEITE_CM_PASS_C(_x) DETAIL_XIEITE_CM_NEXT_C _x
#	define DETAIL_XIEITE_CM_PASS_D(_x) DETAIL_XIEITE_CM_NEXT_D _x
#	define DETAIL_XIEITE_CM_PASS_E(_x) DETAIL_XIEITE_CM_NEXT_E _x
#	define DETAIL_XIEITE_CM_PASS_F(_x) DETAIL_XIEITE_CM_NEXT_F _x
#endif

// NOTE: I have no idea how to use this
