#ifndef DETAIL_XIEITE_HEADER_PP_CM
#	define DETAIL_XIEITE_HEADER_PP_CM
#
#	include "../pp/eat.hpp"
#	include "../pp/paren.hpp"
#	include "../pp/scan.hpp"
#
#	define XIEITE_CM(...) XIEITE_SCAN(XIEITE_EAT XIEITE_LPAREN() DETAIL_XIEITE_CM_NEXT_0(__VA_ARGS__))
#
#	define DETAIL_XIEITE_CM_NEXT_0(P, f, ...) DETAIL_XIEITE_CM_PASS_1(DETAIL_XIEITE_CM_PASS_1(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_1(P, f, ...) DETAIL_XIEITE_CM_PASS_2(DETAIL_XIEITE_CM_PASS_2(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_2(P, f, ...) DETAIL_XIEITE_CM_PASS_3(DETAIL_XIEITE_CM_PASS_3(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_3(P, f, ...) DETAIL_XIEITE_CM_PASS_4(DETAIL_XIEITE_CM_PASS_4(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_4(P, f, ...) DETAIL_XIEITE_CM_PASS_5(DETAIL_XIEITE_CM_PASS_5(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_5(P, f, ...) DETAIL_XIEITE_CM_PASS_6(DETAIL_XIEITE_CM_PASS_6(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_6(P, f, ...) DETAIL_XIEITE_CM_PASS_7(DETAIL_XIEITE_CM_PASS_7(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_7(P, f, ...) DETAIL_XIEITE_CM_PASS_8(DETAIL_XIEITE_CM_PASS_8(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_8(P, f, ...) DETAIL_XIEITE_CM_PASS_9(DETAIL_XIEITE_CM_PASS_9(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_9(P, f, ...) DETAIL_XIEITE_CM_PASS_A(DETAIL_XIEITE_CM_PASS_A(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_A(P, f, ...) DETAIL_XIEITE_CM_PASS_B(DETAIL_XIEITE_CM_PASS_B(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_B(P, f, ...) DETAIL_XIEITE_CM_PASS_C(DETAIL_XIEITE_CM_PASS_C(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_C(P, f, ...) DETAIL_XIEITE_CM_PASS_D(DETAIL_XIEITE_CM_PASS_D(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_D(P, f, ...) DETAIL_XIEITE_CM_PASS_E(DETAIL_XIEITE_CM_PASS_E(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_E(P, f, ...) DETAIL_XIEITE_CM_PASS_F(DETAIL_XIEITE_CM_PASS_F(XIEITE_CM_FN_##f(, P##__VA_ARGS__)))
#	define DETAIL_XIEITE_CM_NEXT_F(P, f, ...) XIEITE_CM_FN_##f(, P##__VA_ARGS__)
#	define DETAIL_XIEITE_CM_PASS_1(x) DETAIL_XIEITE_CM_NEXT_1 x
#	define DETAIL_XIEITE_CM_PASS_2(x) DETAIL_XIEITE_CM_NEXT_2 x
#	define DETAIL_XIEITE_CM_PASS_3(x) DETAIL_XIEITE_CM_NEXT_3 x
#	define DETAIL_XIEITE_CM_PASS_4(x) DETAIL_XIEITE_CM_NEXT_4 x
#	define DETAIL_XIEITE_CM_PASS_5(x) DETAIL_XIEITE_CM_NEXT_5 x
#	define DETAIL_XIEITE_CM_PASS_6(x) DETAIL_XIEITE_CM_NEXT_6 x
#	define DETAIL_XIEITE_CM_PASS_7(x) DETAIL_XIEITE_CM_NEXT_7 x
#	define DETAIL_XIEITE_CM_PASS_8(x) DETAIL_XIEITE_CM_NEXT_8 x
#	define DETAIL_XIEITE_CM_PASS_9(x) DETAIL_XIEITE_CM_NEXT_9 x
#	define DETAIL_XIEITE_CM_PASS_A(x) DETAIL_XIEITE_CM_NEXT_A x
#	define DETAIL_XIEITE_CM_PASS_B(x) DETAIL_XIEITE_CM_NEXT_B x
#	define DETAIL_XIEITE_CM_PASS_C(x) DETAIL_XIEITE_CM_NEXT_C x
#	define DETAIL_XIEITE_CM_PASS_D(x) DETAIL_XIEITE_CM_NEXT_D x
#	define DETAIL_XIEITE_CM_PASS_E(x) DETAIL_XIEITE_CM_NEXT_E x
#	define DETAIL_XIEITE_CM_PASS_F(x) DETAIL_XIEITE_CM_NEXT_F x
#endif

// NOTE: I have no idea how to use this
