#ifndef DETAIL_XIEITE_HEADER_PP_COMPL
#	define DETAIL_XIEITE_HEADER_PP_COMPL
#
#	include "../pp/cat.hpp"
#
#	define XIEITE_COMPL(_b) XIEITE_PCAT(DETAIL_XIEITE_COMPL_, _b)
#
#	define DETAIL_XIEITE_COMPL_0 1
#	define DETAIL_XIEITE_COMPL_1 0
#endif
