#if __has_include(<windows.h>)
#	define NOATOM
#	define NOCLIPBOARD
#	define NOCOLOR
#	define NOCOMM
#	define NOCRYPT
#	define NOCTLMGR
#	define NODEFERWINDOWPOS
#	define NODRAWTEXT
#	define NOGDI
#	define NOGDICAPMASKS
#	define NOHELP
#	define NOICONS
#	define NOIMAGE
#	define NOKANJI
#	define NOKERNEL
#	define NOKEYSTATES
#	define NOMB
#	define NOMCX
#	define NOMEMMGR
#	define NOMENUS
#	define NOMETAFILE
#	define NOMINMAX
#	define NOMSG
#	define NONLS
#	define NOOPENFILE
#	define NOPROFILER
#	define NOPROXYSTUB
#	define NORASTEROPS
#	define NORPC
#	define NOSCROLL
#	define NOSERVICE
#	define NOSHOWWINDOW
#	define NOSOUND
#	define NOSYSCOMMANDS
#	define NOSYSMETRICS
#	define NOTAPE
#	define NOTEXTMETRIC
#	define NOUSER
#	define NOVIRTUALKEYCODES
#	define NOWH
#	define NOWINMESSAGES
#	define NOWINOFFSETS
#	define NOWINSTYLES
#	define WIN32_LEAN_AND_MEAN
#
#	include <windows.h>
#
#	undef NOATOM
#	undef NOCLIPBOARD
#	undef NOCOLOR
#	undef NOCOMM
#	undef NOCRYPT
#	undef NOCTLMGR
#	undef NODEFERWINDOWPOS
#	undef NODRAWTEXT
#	undef NOGDI
#	undef NOGDICAPMASKS
#	undef NOHELP
#	undef NOICONS
#	undef NOIMAGE
#	undef NOKANJI
#	undef NOKERNEL
#	undef NOKEYSTATES
#	undef NOMB
#	undef NOMCX
#	undef NOMEMMGR
#	undef NOMENUS
#	undef NOMETAFILE
#	undef NOMINMAX
#	undef NOMSG
#	undef NONLS
#	undef NOOPENFILE
#	undef NOPROFILER
#	undef NOPROXYSTUB
#	undef NORASTEROPS
#	undef NORPC
#	undef NOSCROLL
#	undef NOSERVICE
#	undef NOSHOWWINDOW
#	undef NOSOUND
#	undef NOSYSCOMMANDS
#	undef NOSYSMETRICS
#	undef NOTAPE
#	undef NOTEXTMETRIC
#	undef NOUSER
#	undef NOVIRTUALKEYCODES
#	undef NOWH
#	undef NOWINMESSAGES
#	undef NOWINOFFSETS
#	undef NOWINSTYLES
#	undef WIN32_LEAN_AND_MEAN
#
#	undef APIENTRY
#	undef APIPRIVATE
#	undef CALLBACK
#	undef CDECL
#	undef CONST
#	undef FALSE
#	undef FAR
#	undef far
#	undef IN
#	undef NEAR
#	undef near
#	undef OPTIONAL
#	undef OUT
#	undef PASCAL
#	undef pascal
#	undef STRICT
#	undef TRUE
#	undef VOID
#	undef WINAPI
#endif

// Thanks to Veeloxfire (https://github.com/Veeloxfire) for original code
