#pragma once

#define XIEITE_PLATFORM_TYPE_AEGIS 0
#define XIEITE_PLATFORM_MAJOR_AEGIS 0
#define XIEITE_PLATFORM_MINOR_AEGIS 0
#define XIEITE_PLATFORM_PATCH_AEGIS 0
#define XIEITE_PLATFORM_TYPE_AIX 0
#define XIEITE_PLATFORM_MAJOR_AIX 0
#define XIEITE_PLATFORM_MINOR_AIX 0
#define XIEITE_PLATFORM_PATCH_AIX 0
#define XIEITE_PLATFORM_TYPE_AKAROS 0
#define XIEITE_PLATFORM_MAJOR_AKAROS 0
#define XIEITE_PLATFORM_MINOR_AKAROS 0
#define XIEITE_PLATFORM_PATCH_AKAROS 0
#define XIEITE_PLATFORM_TYPE_AMIGAOS 0
#define XIEITE_PLATFORM_MAJOR_AMIGAOS 0
#define XIEITE_PLATFORM_MINOR_AMIGAOS 0
#define XIEITE_PLATFORM_PATCH_AMIGAOS 0
#define XIEITE_PLATFORM_TYPE_ANDROID 0
#define XIEITE_PLATFORM_MAJOR_ANDROID 0
#define XIEITE_PLATFORM_MINOR_ANDROID 0
#define XIEITE_PLATFORM_PATCH_ANDROID 0
#define XIEITE_PLATFORM_TYPE_APPLE_II 0
#define XIEITE_PLATFORM_MAJOR_APPLE_II 0
#define XIEITE_PLATFORM_MINOR_APPLE_II 0
#define XIEITE_PLATFORM_PATCH_APPLE_II 0
#define XIEITE_PLATFORM_TYPE_APPLE_IIE 0
#define XIEITE_PLATFORM_MAJOR_APPLE_IIE 0
#define XIEITE_PLATFORM_MINOR_APPLE_IIE 0
#define XIEITE_PLATFORM_PATCH_APPLE_IIE 0
#define XIEITE_PLATFORM_TYPE_ASMJS 0
#define XIEITE_PLATFORM_MAJOR_ASMJS 0
#define XIEITE_PLATFORM_MINOR_ASMJS 0
#define XIEITE_PLATFORM_PATCH_ASMJS 0
#define XIEITE_PLATFORM_TYPE_ATARI 0
#define XIEITE_PLATFORM_MAJOR_ATARI 0
#define XIEITE_PLATFORM_MINOR_ATARI 0
#define XIEITE_PLATFORM_PATCH_ATARI 0
#define XIEITE_PLATFORM_TYPE_ATARI_2600 0
#define XIEITE_PLATFORM_MAJOR_ATARI_2600 0
#define XIEITE_PLATFORM_MINOR_ATARI_2600 0
#define XIEITE_PLATFORM_PATCH_ATARI_2600 0
#define XIEITE_PLATFORM_TYPE_ATARI_5200 0
#define XIEITE_PLATFORM_MAJOR_ATARI_5200 0
#define XIEITE_PLATFORM_MINOR_ATARI_5200 0
#define XIEITE_PLATFORM_PATCH_ATARI_5200 0
#define XIEITE_PLATFORM_TYPE_ATARI_LYNX 0
#define XIEITE_PLATFORM_MAJOR_ATARI_LYNX 0
#define XIEITE_PLATFORM_MINOR_ATARI_LYNX 0
#define XIEITE_PLATFORM_PATCH_ATARI_LYNX 0
#define XIEITE_PLATFORM_TYPE_ATARI_XL 0
#define XIEITE_PLATFORM_MAJOR_ATARI_XL 0
#define XIEITE_PLATFORM_MINOR_ATARI_XL 0
#define XIEITE_PLATFORM_PATCH_ATARI_XL 0
#define XIEITE_PLATFORM_TYPE_BEOS 0
#define XIEITE_PLATFORM_MAJOR_BEOS 0
#define XIEITE_PLATFORM_MINOR_BEOS 0
#define XIEITE_PLATFORM_PATCH_BEOS 0
#define XIEITE_PLATFORM_TYPE_BLUE_GENE 0
#define XIEITE_PLATFORM_MAJOR_BLUE_GENE 0
#define XIEITE_PLATFORM_MINOR_BLUE_GENE 0
#define XIEITE_PLATFORM_PATCH_BLUE_GENE 0
#define XIEITE_PLATFORM_TYPE_BSD 0
#define XIEITE_PLATFORM_MAJOR_BSD 0
#define XIEITE_PLATFORM_MINOR_BSD 0
#define XIEITE_PLATFORM_PATCH_BSD 0
#define XIEITE_PLATFORM_TYPE_BSD_BSDI 0
#define XIEITE_PLATFORM_MAJOR_BSD_BSDI 0
#define XIEITE_PLATFORM_MINOR_BSD_BSDI 0
#define XIEITE_PLATFORM_PATCH_BSD_BSDI 0
#define XIEITE_PLATFORM_TYPE_BSD_DRAGONFLY 0
#define XIEITE_PLATFORM_MAJOR_BSD_DRAGONFLY 0
#define XIEITE_PLATFORM_MINOR_BSD_DRAGONFLY 0
#define XIEITE_PLATFORM_PATCH_BSD_DRAGONFLY 0
#define XIEITE_PLATFORM_TYPE_BSD_FREE 0
#define XIEITE_PLATFORM_MAJOR_BSD_FREE 0
#define XIEITE_PLATFORM_MINOR_BSD_FREE 0
#define XIEITE_PLATFORM_PATCH_BSD_FREE 0
#define XIEITE_PLATFORM_TYPE_BSD_NET 0
#define XIEITE_PLATFORM_MAJOR_BSD_NET 0
#define XIEITE_PLATFORM_MINOR_BSD_NET 0
#define XIEITE_PLATFORM_PATCH_BSD_NET 0
#define XIEITE_PLATFORM_TYPE_BSD_OPEN 0
#define XIEITE_PLATFORM_MAJOR_BSD_OPEN 0
#define XIEITE_PLATFORM_MINOR_BSD_OPEN 0
#define XIEITE_PLATFORM_PATCH_BSD_OPEN 0
#define XIEITE_PLATFORM_TYPE_CLOUDABI 0
#define XIEITE_PLATFORM_MAJOR_CLOUDABI 0
#define XIEITE_PLATFORM_MINOR_CLOUDABI 0
#define XIEITE_PLATFORM_PATCH_CLOUDABI 0
#define XIEITE_PLATFORM_TYPE_CMB 0
#define XIEITE_PLATFORM_MAJOR_CMB 0
#define XIEITE_PLATFORM_MINOR_CMB 0
#define XIEITE_PLATFORM_PATCH_CMB 0
#define XIEITE_PLATFORM_TYPE_CMB_500 0
#define XIEITE_PLATFORM_MAJOR_CMB_500 0
#define XIEITE_PLATFORM_MINOR_CMB_500 0
#define XIEITE_PLATFORM_PATCH_CMB_500 0
#define XIEITE_PLATFORM_TYPE_CMB_600 0
#define XIEITE_PLATFORM_MAJOR_CMB_600 0
#define XIEITE_PLATFORM_MINOR_CMB_600 0
#define XIEITE_PLATFORM_PATCH_CMB_600 0
#define XIEITE_PLATFORM_TYPE_COMMANDER_X16 0
#define XIEITE_PLATFORM_MAJOR_COMMANDER_X16 0
#define XIEITE_PLATFORM_MINOR_COMMANDER_X16 0
#define XIEITE_PLATFORM_PATCH_COMMANDER_X16 0
#define XIEITE_PLATFORM_TYPE_COMMODORE_16 0
#define XIEITE_PLATFORM_MAJOR_COMMODORE_16 0
#define XIEITE_PLATFORM_MINOR_COMMODORE_16 0
#define XIEITE_PLATFORM_PATCH_COMMODORE_16 0
#define XIEITE_PLATFORM_TYPE_COMMODORE_64 0
#define XIEITE_PLATFORM_MAJOR_COMMODORE_64 0
#define XIEITE_PLATFORM_MINOR_COMMODORE_64 0
#define XIEITE_PLATFORM_PATCH_COMMODORE_64 0
#define XIEITE_PLATFORM_TYPE_COMMODORE_128 0
#define XIEITE_PLATFORM_MAJOR_COMMODORE_128 0
#define XIEITE_PLATFORM_MINOR_COMMODORE_128 0
#define XIEITE_PLATFORM_PATCH_COMMODORE_128 0
#define XIEITE_PLATFORM_TYPE_COMMODORE_PLUS_4 0
#define XIEITE_PLATFORM_MAJOR_COMMODORE_PLUS_4 0
#define XIEITE_PLATFORM_MINOR_COMMODORE_PLUS_4 0
#define XIEITE_PLATFORM_PATCH_COMMODORE_PLUS_4 0
#define XIEITE_PLATFORM_TYPE_COMMODORE_VIC20 0
#define XIEITE_PLATFORM_MAJOR_COMMODORE_VIC20 0
#define XIEITE_PLATFORM_MINOR_COMMODORE_VIC20 0
#define XIEITE_PLATFORM_PATCH_COMMODORE_VIC20 0
#define XIEITE_PLATFORM_TYPE_CONVEXOS 0
#define XIEITE_PLATFORM_MAJOR_CONVEXOS 0
#define XIEITE_PLATFORM_MINOR_CONVEXOS 0
#define XIEITE_PLATFORM_PATCH_CONVEXOS 0
#define XIEITE_PLATFORM_TYPE_CYGWIN 0
#define XIEITE_PLATFORM_MAJOR_CYGWIN 0
#define XIEITE_PLATFORM_MINOR_CYGWIN 0
#define XIEITE_PLATFORM_PATCH_CYGWIN 0
#define XIEITE_PLATFORM_TYPE_DC_OSX 0
#define XIEITE_PLATFORM_MAJOR_DC_OSX 0
#define XIEITE_PLATFORM_MINOR_DC_OSX 0
#define XIEITE_PLATFORM_PATCH_DC_OSX 0
#define XIEITE_PLATFORM_TYPE_DG_UX 0
#define XIEITE_PLATFORM_MAJOR_DG_UX 0
#define XIEITE_PLATFORM_MINOR_DG_UX 0
#define XIEITE_PLATFORM_PATCH_DG_UX 0
#define XIEITE_PLATFORM_TYPE_DOMAIN_OS 0
#define XIEITE_PLATFORM_MAJOR_DOMAIN_OS 0
#define XIEITE_PLATFORM_MINOR_DOMAIN_OS 0
#define XIEITE_PLATFORM_PATCH_DOMAIN_OS 0
#define XIEITE_PLATFORM_TYPE_DRAGONFLY 0
#define XIEITE_PLATFORM_MAJOR_DRAGONFLY 0
#define XIEITE_PLATFORM_MINOR_DRAGONFLY 0
#define XIEITE_PLATFORM_PATCH_DRAGONFLY 0
#define XIEITE_PLATFORM_TYPE_DYNIX 0
#define XIEITE_PLATFORM_MAJOR_DYNIX 0
#define XIEITE_PLATFORM_MINOR_DYNIX 0
#define XIEITE_PLATFORM_PATCH_DYNIX 0
#define XIEITE_PLATFORM_TYPE_ECOS 0
#define XIEITE_PLATFORM_MAJOR_ECOS 0
#define XIEITE_PLATFORM_MINOR_ECOS 0
#define XIEITE_PLATFORM_PATCH_ECOS 0
#define XIEITE_PLATFORM_TYPE_EMX 0
#define XIEITE_PLATFORM_MAJOR_EMX 0
#define XIEITE_PLATFORM_MINOR_EMX 0
#define XIEITE_PLATFORM_PATCH_EMX 0
#define XIEITE_PLATFORM_TYPE_FREEBSD 0
#define XIEITE_PLATFORM_MAJOR_FREEBSD 0
#define XIEITE_PLATFORM_MINOR_FREEBSD 0
#define XIEITE_PLATFORM_PATCH_FREEBSD 0
#define XIEITE_PLATFORM_TYPE_FUCHSIA 0
#define XIEITE_PLATFORM_MAJOR_FUCHSIA 0
#define XIEITE_PLATFORM_MINOR_FUCHSIA 0
#define XIEITE_PLATFORM_PATCH_FUCHSIA 0
#define XIEITE_PLATFORM_TYPE_GEOS 0
#define XIEITE_PLATFORM_MAJOR_GEOS 0
#define XIEITE_PLATFORM_MINOR_GEOS 0
#define XIEITE_PLATFORM_PATCH_GEOS 0
#define XIEITE_PLATFORM_TYPE_GEOS_APPLE 0
#define XIEITE_PLATFORM_MAJOR_GEOS_APPLE 0
#define XIEITE_PLATFORM_MINOR_GEOS_APPLE 0
#define XIEITE_PLATFORM_PATCH_GEOS_APPLE 0
#define XIEITE_PLATFORM_TYPE_GEOS_CMB 0
#define XIEITE_PLATFORM_MAJOR_GEOS_CMB 0
#define XIEITE_PLATFORM_MINOR_GEOS_CMB 0
#define XIEITE_PLATFORM_PATCH_GEOS_CMB 0
#define XIEITE_PLATFORM_TYPE_GNU_HURD 0
#define XIEITE_PLATFORM_MAJOR_GNU_HURD 0
#define XIEITE_PLATFORM_MINOR_GNU_HURD 0
#define XIEITE_PLATFORM_PATCH_GNU_HURD 0
#define XIEITE_PLATFORM_TYPE_GNU_KFREEBSD 0
#define XIEITE_PLATFORM_MAJOR_GNU_KFREEBSD 0
#define XIEITE_PLATFORM_MINOR_GNU_KFREEBSD 0
#define XIEITE_PLATFORM_PATCH_GNU_KFREEBSD 0
#define XIEITE_PLATFORM_TYPE_GNU_LINUX 0
#define XIEITE_PLATFORM_MAJOR_GNU_LINUX 0
#define XIEITE_PLATFORM_MINOR_GNU_LINUX 0
#define XIEITE_PLATFORM_PATCH_GNU_LINUX 0
#define XIEITE_PLATFORM_TYPE_HAIKU 0
#define XIEITE_PLATFORM_MAJOR_HAIKU 0
#define XIEITE_PLATFORM_MINOR_HAIKU 0
#define XIEITE_PLATFORM_PATCH_HAIKU 0
#define XIEITE_PLATFORM_TYPE_HI_UX_MPP 0
#define XIEITE_PLATFORM_MAJOR_HI_UX_MPP 0
#define XIEITE_PLATFORM_MINOR_HI_UX_MPP 0
#define XIEITE_PLATFORM_PATCH_HI_UX_MPP 0
#define XIEITE_PLATFORM_TYPE_HP_UX 0
#define XIEITE_PLATFORM_MAJOR_HP_UX 0
#define XIEITE_PLATFORM_MINOR_HP_UX 0
#define XIEITE_PLATFORM_PATCH_HP_UX 0
#define XIEITE_PLATFORM_TYPE_INTEGRITY 0
#define XIEITE_PLATFORM_MAJOR_INTEGRITY 0
#define XIEITE_PLATFORM_MINOR_INTEGRITY 0
#define XIEITE_PLATFORM_PATCH_INTEGRITY 0
#define XIEITE_PLATFORM_TYPE_INTERIX 0
#define XIEITE_PLATFORM_MAJOR_INTERIX 0
#define XIEITE_PLATFORM_MINOR_INTERIX 0
#define XIEITE_PLATFORM_PATCH_INTERIX 0
#define XIEITE_PLATFORM_TYPE_IOS_SIMULATOR 0
#define XIEITE_PLATFORM_MAJOR_IOS_SIMULATOR 0
#define XIEITE_PLATFORM_MINOR_IOS_SIMULATOR 0
#define XIEITE_PLATFORM_PATCH_IOS_SIMULATOR 0
#define XIEITE_PLATFORM_TYPE_IRIX 0
#define XIEITE_PLATFORM_MAJOR_IRIX 0
#define XIEITE_PLATFORM_MINOR_IRIX 0
#define XIEITE_PLATFORM_PATCH_IRIX 0
#define XIEITE_PLATFORM_TYPE_KALLISTI 0
#define XIEITE_PLATFORM_MAJOR_KALLISTI 0
#define XIEITE_PLATFORM_MINOR_KALLISTI 0
#define XIEITE_PLATFORM_PATCH_KALLISTI 0
#define XIEITE_PLATFORM_TYPE_LINUX 0
#define XIEITE_PLATFORM_MAJOR_LINUX 0
#define XIEITE_PLATFORM_MINOR_LINUX 0
#define XIEITE_PLATFORM_PATCH_LINUX 0
#define XIEITE_PLATFORM_TYPE_LUNIX 0
#define XIEITE_PLATFORM_MAJOR_LUNIX 0
#define XIEITE_PLATFORM_MINOR_LUNIX 0
#define XIEITE_PLATFORM_PATCH_LUNIX 0
#define XIEITE_PLATFORM_TYPE_LYNXOS 0
#define XIEITE_PLATFORM_MAJOR_LYNXOS 0
#define XIEITE_PLATFORM_MINOR_LYNXOS 0
#define XIEITE_PLATFORM_PATCH_LYNXOS 0
#define XIEITE_PLATFORM_TYPE_MACINTOSH 0
#define XIEITE_PLATFORM_MAJOR_MACINTOSH 0
#define XIEITE_PLATFORM_MINOR_MACINTOSH 0
#define XIEITE_PLATFORM_PATCH_MACINTOSH 0
#define XIEITE_PLATFORM_TYPE_MACINTOSH_DYLD 0
#define XIEITE_PLATFORM_MAJOR_MACINTOSH_DYLD 0
#define XIEITE_PLATFORM_MINOR_MACINTOSH_DYLD 0
#define XIEITE_PLATFORM_PATCH_MACINTOSH_DYLD 0
#define XIEITE_PLATFORM_TYPE_MINGW32 0
#define XIEITE_PLATFORM_MAJOR_MINGW32 0
#define XIEITE_PLATFORM_MINOR_MINGW32 0
#define XIEITE_PLATFORM_PATCH_MINGW32 0
#define XIEITE_PLATFORM_TYPE_MINGW64 0
#define XIEITE_PLATFORM_MAJOR_MINGW64 0
#define XIEITE_PLATFORM_MINOR_MINGW64 0
#define XIEITE_PLATFORM_PATCH_MINGW64 0
#define XIEITE_PLATFORM_TYPE_MINIX 0
#define XIEITE_PLATFORM_MAJOR_MINIX 0
#define XIEITE_PLATFORM_MINOR_MINIX 0
#define XIEITE_PLATFORM_PATCH_MINIX 0
#define XIEITE_PLATFORM_TYPE_MORPHOS 0
#define XIEITE_PLATFORM_MAJOR_MORPHOS 0
#define XIEITE_PLATFORM_MINOR_MORPHOS 0
#define XIEITE_PLATFORM_PATCH_MORPHOS 0
#define XIEITE_PLATFORM_TYPE_MPE_IX 0
#define XIEITE_PLATFORM_MAJOR_MPE_IX 0
#define XIEITE_PLATFORM_MINOR_MPE_IX 0
#define XIEITE_PLATFORM_PATCH_MPE_IX 0
#define XIEITE_PLATFORM_TYPE_MS_DOS 0
#define XIEITE_PLATFORM_MAJOR_MS_DOS 0
#define XIEITE_PLATFORM_MINOR_MS_DOS 0
#define XIEITE_PLATFORM_PATCH_MS_DOS 0
#define XIEITE_PLATFORM_TYPE_NACL 0
#define XIEITE_PLATFORM_MAJOR_NACL 0
#define XIEITE_PLATFORM_MINOR_NACL 0
#define XIEITE_PLATFORM_PATCH_NACL 0
#define XIEITE_PLATFORM_TYPE_NES 0
#define XIEITE_PLATFORM_MAJOR_NES 0
#define XIEITE_PLATFORM_MINOR_NES 0
#define XIEITE_PLATFORM_PATCH_NES 0
#define XIEITE_PLATFORM_TYPE_NEXT 0
#define XIEITE_PLATFORM_MAJOR_NEXT 0
#define XIEITE_PLATFORM_MINOR_NEXT 0
#define XIEITE_PLATFORM_PATCH_NEXT 0
#define XIEITE_PLATFORM_TYPE_NINTENDO_3DS 0
#define XIEITE_PLATFORM_MAJOR_NINTENDO_3DS 0
#define XIEITE_PLATFORM_MINOR_NINTENDO_3DS 0
#define XIEITE_PLATFORM_PATCH_NINTENDO_3DS 0
#define XIEITE_PLATFORM_TYPE_NINTENDO_GAMECUBE 0
#define XIEITE_PLATFORM_MAJOR_NINTENDO_GAMECUBE 0
#define XIEITE_PLATFORM_MINOR_NINTENDO_GAMECUBE 0
#define XIEITE_PLATFORM_PATCH_NINTENDO_GAMECUBE 0
#define XIEITE_PLATFORM_TYPE_NINTENDO_SWITCH 0
#define XIEITE_PLATFORM_MAJOR_NINTENDO_SWITCH 0
#define XIEITE_PLATFORM_MINOR_NINTENDO_SWITCH 0
#define XIEITE_PLATFORM_PATCH_NINTENDO_SWITCH 0
#define XIEITE_PLATFORM_TYPE_NONSTOP 0
#define XIEITE_PLATFORM_MAJOR_NONSTOP 0
#define XIEITE_PLATFORM_MINOR_NONSTOP 0
#define XIEITE_PLATFORM_PATCH_NONSTOP 0
#define XIEITE_PLATFORM_TYPE_NUCLEUS_RTOS 0
#define XIEITE_PLATFORM_MAJOR_NUCLEUS_RTOS 0
#define XIEITE_PLATFORM_MINOR_NUCLEUS_RTOS 0
#define XIEITE_PLATFORM_PATCH_NUCLEUS_RTOS 0
#define XIEITE_PLATFORM_TYPE_OHIO_SCIENTIFIC_CHALLENGER_1P 0
#define XIEITE_PLATFORM_MAJOR_OHIO_SCIENTIFIC_CHALLENGER_1P 0
#define XIEITE_PLATFORM_MINOR_OHIO_SCIENTIFIC_CHALLENGER_1P 0
#define XIEITE_PLATFORM_PATCH_OHIO_SCIENTIFIC_CHALLENGER_1P 0
#define XIEITE_PLATFORM_TYPE_OPENSERVER 0
#define XIEITE_PLATFORM_MAJOR_OPENSERVER 0
#define XIEITE_PLATFORM_MINOR_OPENSERVER 0
#define XIEITE_PLATFORM_PATCH_OPENSERVER 0
#define XIEITE_PLATFORM_TYPE_ORIC_ATMOS 0
#define XIEITE_PLATFORM_MAJOR_ORIC_ATMOS 0
#define XIEITE_PLATFORM_MINOR_ORIC_ATMOS 0
#define XIEITE_PLATFORM_PATCH_ORIC_ATMOS 0
#define XIEITE_PLATFORM_TYPE_OS_2 0
#define XIEITE_PLATFORM_MAJOR_OS_2 0
#define XIEITE_PLATFORM_MINOR_OS_2 0
#define XIEITE_PLATFORM_PATCH_OS_2 0
#define XIEITE_PLATFORM_TYPE_OS_400 0
#define XIEITE_PLATFORM_MAJOR_OS_400 0
#define XIEITE_PLATFORM_MINOR_OS_400 0
#define XIEITE_PLATFORM_PATCH_OS_400 0
#define XIEITE_PLATFORM_TYPE_OS_9 0
#define XIEITE_PLATFORM_MAJOR_OS_9 0
#define XIEITE_PLATFORM_MINOR_OS_9 0
#define XIEITE_PLATFORM_PATCH_OS_9 0
#define XIEITE_PLATFORM_TYPE_PALM_OS 0
#define XIEITE_PLATFORM_MAJOR_PALM_OS 0
#define XIEITE_PLATFORM_MINOR_PALM_OS 0
#define XIEITE_PLATFORM_PATCH_PALM_OS 0
#define XIEITE_PLATFORM_TYPE_PDOS 0
#define XIEITE_PLATFORM_MAJOR_PDOS 0
#define XIEITE_PLATFORM_MINOR_PDOS 0
#define XIEITE_PLATFORM_PATCH_PDOS 0
#define XIEITE_PLATFORM_TYPE_PET 0
#define XIEITE_PLATFORM_MAJOR_PET 0
#define XIEITE_PLATFORM_MINOR_PET 0
#define XIEITE_PLATFORM_PATCH_PET 0
#define XIEITE_PLATFORM_TYPE_PHOENIX 0
#define XIEITE_PLATFORM_MAJOR_PHOENIX 0
#define XIEITE_PLATFORM_MINOR_PHOENIX 0
#define XIEITE_PLATFORM_PATCH_PHOENIX 0
#define XIEITE_PLATFORM_TYPE_PLAN_9 0
#define XIEITE_PLATFORM_MAJOR_PLAN_9 0
#define XIEITE_PLATFORM_MINOR_PLAN_9 0
#define XIEITE_PLATFORM_PATCH_PLAN_9 0
#define XIEITE_PLATFORM_TYPE_PNACL 0
#define XIEITE_PLATFORM_MAJOR_PNACL 0
#define XIEITE_PLATFORM_MINOR_PNACL 0
#define XIEITE_PLATFORM_PATCH_PNACL 0
#define XIEITE_PLATFORM_TYPE_QNX 0
#define XIEITE_PLATFORM_MAJOR_QNX 0
#define XIEITE_PLATFORM_MINOR_QNX 0
#define XIEITE_PLATFORM_PATCH_QNX 0
#define XIEITE_PLATFORM_TYPE_SEGA_DREAMCAST 0
#define XIEITE_PLATFORM_MAJOR_SEGA_DREAMCAST 0
#define XIEITE_PLATFORM_MINOR_SEGA_DREAMCAST 0
#define XIEITE_PLATFORM_PATCH_SEGA_DREAMCAST 0
#define XIEITE_PLATFORM_TYPE_SIM6502 0
#define XIEITE_PLATFORM_MAJOR_SIM6502 0
#define XIEITE_PLATFORM_MINOR_SIM6502 0
#define XIEITE_PLATFORM_PATCH_SIM6502 0
#define XIEITE_PLATFORM_TYPE_SIM65C02 0
#define XIEITE_PLATFORM_MAJOR_SIM65C02 0
#define XIEITE_PLATFORM_MINOR_SIM65C02 0
#define XIEITE_PLATFORM_PATCH_SIM65C02 0
#define XIEITE_PLATFORM_TYPE_SINIX 0
#define XIEITE_PLATFORM_MAJOR_SINIX 0
#define XIEITE_PLATFORM_MINOR_SINIX 0
#define XIEITE_PLATFORM_PATCH_SINIX 0
#define XIEITE_PLATFORM_TYPE_SOLARIS 0
#define XIEITE_PLATFORM_MAJOR_SOLARIS 0
#define XIEITE_PLATFORM_MINOR_SOLARIS 0
#define XIEITE_PLATFORM_PATCH_SOLARIS 0
#define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION 0
#define XIEITE_PLATFORM_MAJOR_SONY_PLAYSTATION 0
#define XIEITE_PLATFORM_MINOR_SONY_PLAYSTATION 0
#define XIEITE_PLATFORM_PATCH_SONY_PLAYSTATION 0
#define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_2 0
#define XIEITE_PLATFORM_MAJOR_SONY_PLAYSTATION_2 0
#define XIEITE_PLATFORM_MINOR_SONY_PLAYSTATION_2 0
#define XIEITE_PLATFORM_PATCH_SONY_PLAYSTATION_2 0
#define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_3 0
#define XIEITE_PLATFORM_MAJOR_SONY_PLAYSTATION_3 0
#define XIEITE_PLATFORM_MINOR_SONY_PLAYSTATION_3 0
#define XIEITE_PLATFORM_PATCH_SONY_PLAYSTATION_3 0
#define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_4 0
#define XIEITE_PLATFORM_MAJOR_SONY_PLAYSTATION_4 0
#define XIEITE_PLATFORM_MINOR_SONY_PLAYSTATION_4 0
#define XIEITE_PLATFORM_PATCH_SONY_PLAYSTATION_4 0
#define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_5 0
#define XIEITE_PLATFORM_MAJOR_SONY_PLAYSTATION_5 0
#define XIEITE_PLATFORM_MINOR_SONY_PLAYSTATION_5 0
#define XIEITE_PLATFORM_PATCH_SONY_PLAYSTATION_5 0
#define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_P 0
#define XIEITE_PLATFORM_MAJOR_SONY_PLAYSTATION_P 0
#define XIEITE_PLATFORM_MINOR_SONY_PLAYSTATION_P 0
#define XIEITE_PLATFORM_PATCH_SONY_PLAYSTATION_P 0
#define XIEITE_PLATFORM_TYPE_SONY_VITA 0
#define XIEITE_PLATFORM_MAJOR_SONY_VITA 0
#define XIEITE_PLATFORM_MINOR_SONY_VITA 0
#define XIEITE_PLATFORM_PATCH_SONY_VITA 0
#define XIEITE_PLATFORM_TYPE_SUPERVISION 0
#define XIEITE_PLATFORM_MAJOR_SUPERVISION 0
#define XIEITE_PLATFORM_MINOR_SUPERVISION 0
#define XIEITE_PLATFORM_PATCH_SUPERVISION 0
#define XIEITE_PLATFORM_TYPE_SYGWIN 0
#define XIEITE_PLATFORM_MAJOR_SYGWIN 0
#define XIEITE_PLATFORM_MINOR_SYGWIN 0
#define XIEITE_PLATFORM_PATCH_SYGWIN 0
#define XIEITE_PLATFORM_TYPE_SYLLABLE 0
#define XIEITE_PLATFORM_MAJOR_SYLLABLE 0
#define XIEITE_PLATFORM_MINOR_SYLLABLE 0
#define XIEITE_PLATFORM_PATCH_SYLLABLE 0
#define XIEITE_PLATFORM_TYPE_SYM1 0
#define XIEITE_PLATFORM_MAJOR_SYM1 0
#define XIEITE_PLATFORM_MINOR_SYM1 0
#define XIEITE_PLATFORM_PATCH_SYM1 0
#define XIEITE_PLATFORM_TYPE_SYMBIAN 0
#define XIEITE_PLATFORM_MAJOR_SYMBIAN 0
#define XIEITE_PLATFORM_MINOR_SYMBIAN 0
#define XIEITE_PLATFORM_PATCH_SYMBIAN 0
#define XIEITE_PLATFORM_TYPE_SYSTEM_V 0
#define XIEITE_PLATFORM_MAJOR_SYSTEM_V 0
#define XIEITE_PLATFORM_MINOR_SYSTEM_V 0
#define XIEITE_PLATFORM_PATCH_SYSTEM_V 0
#define XIEITE_PLATFORM_TYPE_TELESTRAT 0
#define XIEITE_PLATFORM_MAJOR_TELESTRAT 0
#define XIEITE_PLATFORM_MINOR_TELESTRAT 0
#define XIEITE_PLATFORM_PATCH_TELESTRAT 0
#define XIEITE_PLATFORM_TYPE_TRU64 0
#define XIEITE_PLATFORM_MAJOR_TRU64 0
#define XIEITE_PLATFORM_MINOR_TRU64 0
#define XIEITE_PLATFORM_PATCH_TRU64 0
#define XIEITE_PLATFORM_TYPE_UCLINUX 0
#define XIEITE_PLATFORM_MAJOR_UCLINUX 0
#define XIEITE_PLATFORM_MINOR_UCLINUX 0
#define XIEITE_PLATFORM_PATCH_UCLINUX 0
#define XIEITE_PLATFORM_TYPE_ULTRIX 0
#define XIEITE_PLATFORM_MAJOR_ULTRIX 0
#define XIEITE_PLATFORM_MINOR_ULTRIX 0
#define XIEITE_PLATFORM_PATCH_ULTRIX 0
#define XIEITE_PLATFORM_TYPE_UNICOS 0
#define XIEITE_PLATFORM_MAJOR_UNICOS 0
#define XIEITE_PLATFORM_MINOR_UNICOS 0
#define XIEITE_PLATFORM_PATCH_UNICOS 0
#define XIEITE_PLATFORM_TYPE_UNICOS_MP 0
#define XIEITE_PLATFORM_MAJOR_UNICOS_MP 0
#define XIEITE_PLATFORM_MINOR_UNICOS_MP 0
#define XIEITE_PLATFORM_PATCH_UNICOS_MP 0
#define XIEITE_PLATFORM_TYPE_UNIX 0
#define XIEITE_PLATFORM_MAJOR_UNIX 0
#define XIEITE_PLATFORM_MINOR_UNIX 0
#define XIEITE_PLATFORM_PATCH_UNIX 0
#define XIEITE_PLATFORM_TYPE_UNIXWARE 0
#define XIEITE_PLATFORM_MAJOR_UNIXWARE 0
#define XIEITE_PLATFORM_MINOR_UNIXWARE 0
#define XIEITE_PLATFORM_PATCH_UNIXWARE 0
#define XIEITE_PLATFORM_TYPE_UTS 0
#define XIEITE_PLATFORM_MAJOR_UTS 0
#define XIEITE_PLATFORM_MINOR_UTS 0
#define XIEITE_PLATFORM_PATCH_UTS 0
#define XIEITE_PLATFORM_TYPE_UWIN 0
#define XIEITE_PLATFORM_MAJOR_UWIN 0
#define XIEITE_PLATFORM_MINOR_UWIN 0
#define XIEITE_PLATFORM_PATCH_UWIN 0
#define XIEITE_PLATFORM_TYPE_VMS 0
#define XIEITE_PLATFORM_MAJOR_VMS 0
#define XIEITE_PLATFORM_MINOR_VMS 0
#define XIEITE_PLATFORM_PATCH_VMS 0
#define XIEITE_PLATFORM_TYPE_VOS 0
#define XIEITE_PLATFORM_MAJOR_VOS 0
#define XIEITE_PLATFORM_MINOR_VOS 0
#define XIEITE_PLATFORM_PATCH_VOS 0
#define XIEITE_PLATFORM_TYPE_VXWORKS 0
#define XIEITE_PLATFORM_MAJOR_VXWORKS 0
#define XIEITE_PLATFORM_MINOR_VXWORKS 0
#define XIEITE_PLATFORM_PATCH_VXWORKS 0
#define XIEITE_PLATFORM_TYPE_WINDOWS 0
#define XIEITE_PLATFORM_MAJOR_WINDOWS 0
#define XIEITE_PLATFORM_MINOR_WINDOWS 0
#define XIEITE_PLATFORM_PATCH_WINDOWS 0
#define XIEITE_PLATFORM_TYPE_WINDOWS_CE 0
#define XIEITE_PLATFORM_MAJOR_WINDOWS_CE 0
#define XIEITE_PLATFORM_MINOR_WINDOWS_CE 0
#define XIEITE_PLATFORM_PATCH_WINDOWS_CE 0
#define XIEITE_PLATFORM_TYPE_WINDOWS_DESKTOP 0
#define XIEITE_PLATFORM_MAJOR_WINDOWS_DESKTOP 0
#define XIEITE_PLATFORM_MINOR_WINDOWS_DESKTOP 0
#define XIEITE_PLATFORM_PATCH_WINDOWS_DESKTOP 0
#define XIEITE_PLATFORM_TYPE_WINDOWS_GDK 0
#define XIEITE_PLATFORM_MAJOR_WINDOWS_GDK 0
#define XIEITE_PLATFORM_MINOR_WINDOWS_GDK 0
#define XIEITE_PLATFORM_PATCH_WINDOWS_GDK 0
#define XIEITE_PLATFORM_TYPE_WINDOWS_NT 0
#define XIEITE_PLATFORM_MAJOR_WINDOWS_NT 0
#define XIEITE_PLATFORM_MINOR_WINDOWS_NT 0
#define XIEITE_PLATFORM_PATCH_WINDOWS_NT 0
#define XIEITE_PLATFORM_TYPE_WIND_U 0
#define XIEITE_PLATFORM_MAJOR_WIND_U 0
#define XIEITE_PLATFORM_MINOR_WIND_U 0
#define XIEITE_PLATFORM_PATCH_WIND_U 0
#define XIEITE_PLATFORM_TYPE_XBOX 0
#define XIEITE_PLATFORM_MAJOR_XBOX 0
#define XIEITE_PLATFORM_MINOR_XBOX 0
#define XIEITE_PLATFORM_PATCH_XBOX 0
#define XIEITE_PLATFORM_TYPE_XBOX_360 0
#define XIEITE_PLATFORM_MAJOR_XBOX_360 0
#define XIEITE_PLATFORM_MINOR_XBOX_360 0
#define XIEITE_PLATFORM_PATCH_XBOX_360 0
#define XIEITE_PLATFORM_TYPE_XBOX_ONE 0
#define XIEITE_PLATFORM_MAJOR_XBOX_ONE 0
#define XIEITE_PLATFORM_MINOR_XBOX_ONE 0
#define XIEITE_PLATFORM_PATCH_XBOX_ONE 0
#define XIEITE_PLATFORM_TYPE_XBOX_SERIES 0
#define XIEITE_PLATFORM_MAJOR_XBOX_SERIES 0
#define XIEITE_PLATFORM_MINOR_XBOX_SERIES 0
#define XIEITE_PLATFORM_PATCH_XBOX_SERIES 0
#define XIEITE_PLATFORM_TYPE_Z 0
#define XIEITE_PLATFORM_MAJOR_Z 0
#define XIEITE_PLATFORM_MINOR_Z 0
#define XIEITE_PLATFORM_PATCH_Z 0

#define XIEITE_PLATFORM_EQ(type, major, ...) DETAIL_XIEITE_PLATFORM(__VA_ARGS__, DETAIL_XIEITE_PLATFORM_EQ(type, major, __VA_ARGS__), DETAIL_XIEITE_PLATFORM_EQ(type, major, __VA_ARGS__, 0), DETAIL_XIEITE_PLATFORM_EQ(type, major, 0, 0))
#define XIEITE_PLATFORM_LEAST(type, major, ...) DETAIL_XIEITE_PLATFORM(__VA_ARGS__, DETAIL_XIEITE_PLATFORM_LEAST(type, major, __VA_ARGS__), DETAIL_XIEITE_PLATFORM_LEAST(type, major, __VA_ARGS__, 0), DETAIL_XIEITE_PLATFORM_LEAST(type, major, 0, 0))
#define XIEITE_PLATFORM_MOST(type, major, ...) DETAIL_XIEITE_PLATFORM(__VA_ARGS__, DETAIL_XIEITE_PLATFORM_MOST(type, major, __VA_ARGS__), DETAIL_XIEITE_PLATFORM_MOST(type, major, __VA_ARGS__, 0), DETAIL_XIEITE_PLATFORM_MOST(type, major, 0, 0))
#define DETAIL_XIEITE_PLATFORM(_0, _1, _2, x, ...) x
#define DETAIL_XIEITE_PLATFORM_EQ(type, major, minor, patch) (XIEITE_PLATFORM_TYPE_##type && (XIEITE_PLATFORM_MAJOR_##type == (major)) && (XIEITE_PLATFORM_MINOR_##type == (minor)) && (XIEITE_PLATFORM_PATCH_##type == (patch)))
#define DETAIL_XIEITE_PLATFORM_LEAST(type, major, minor, patch) (XIEITE_PLATFORM_TYPE_##type && ((XIEITE_PLATFORM_MAJOR_##type > (major)) || (XIEITE_PLATFORM_MAJOR_##type == (major)) && ((XIEITE_PLATFORM_MINOR_##type > (minor)) || (XIEITE_PLATFORM_MINOR_##type == (minor)) && (XIEITE_PLATFORM_PATCH_##type >= (patch)))))
#define DETAIL_XIEITE_PLATFORM_MOST(type, major, minor, patch) (XIEITE_PLATFORM_TYPE_##type && ((XIEITE_PLATFORM_MAJOR_##type < (major)) || (XIEITE_PLATFORM_MAJOR_##type == (major)) && ((XIEITE_PLATFORM_MINOR_##type < (minor)) || (XIEITE_PLATFORM_MINOR_##type == (minor)) && (XIEITE_PLATFORM_PATCH_##type <= (patch)))))

#ifdef aegis
#	undef XIEITE_PLATFORM_TYPE_AEGIS
#	define XIEITE_PLATFORM_TYPE_AEGIS 1
#endif

#if defined(_AIX) || defined(__TOS_AIX__)
#	undef XIEITE_PLATFORM_TYPE_AIX
#	define XIEITE_PLATFORM_TYPE_AIX 1

#	ifdef _AIX3
#		undef XIEITE_PLATFORM_MAJOR_AIX
#		define XIEITE_PLATFORM_MAJOR_AIX 3
#	endif

#	ifdef _AIX32
#		undef XIEITE_PLATFORM_MAJOR_AIX
#		define XIEITE_PLATFORM_MAJOR_AIX 3

#		undef XIEITE_PLATFORM_MINOR_AIX
#		define XIEITE_PLATFORM_MINOR_AIX 2
#	endif

#	ifdef _AIX41
#		undef XIEITE_PLATFORM_MAJOR_AIX
#		define XIEITE_PLATFORM_MAJOR_AIX 4

#		undef XIEITE_PLATFORM_MINOR_AIX
#		define XIEITE_PLATFORM_MINOR_AIX 1
#	endif

#	ifdef _AIX43
#		undef XIEITE_PLATFORM_MAJOR_AIX
#		define XIEITE_PLATFORM_MAJOR_AIX 4

#		undef XIEITE_PLATFORM_MINOR_AIX
#		define XIEITE_PLATFORM_MINOR_AIX 3
#	endif
#endif

#ifdef __ros__
#	undef XIEITE_PLATFORM_TYPE_AKAROS
#	define XIEITE_PLATFORM_TYPE_AKAROS 1
#endif

#if defined(AMIGA) || defined(__amigaos__)
#	undef XIEITE_PLATFORM_TYPE_AMIGAOS
#	define XIEITE_PLATFORM_TYPE_AMIGAOS 1
#endif

#ifdef __ANDROID__
#	include <android/api-level.h>

#	undef XIEITE_PLATFORM_TYPE_ANDROID
#	define XIEITE_PLATFORM_TYPE_ANDROID 1

#	undef XIEITE_PLATFORM_MAJOR_ANDROID
#	define XIEITE_PLATFORM_MAJOR_ANDROID __ANDROID_API__
#endif

#ifdef __APPLE2__
#	undef XIEITE_PLATFORM_TYPE_APPLE_II
#	define XIEITE_PLATFORM_TYPE_APPLE_II 1
#endif

#ifdef __APPLE2ENH__
#	undef XIEITE_PLATFORM_TYPE_APPLE_IIE
#	define XIEITE_PLATFORM_TYPE_APPLE_IIE 1
#endif

#ifdef __asmjs__
#	undef XIEITE_PLATFORM_TYPE_ASMJS
#	define XIEITE_PLATFORM_TYPE_ASMJS 1
#endif

#ifdef __ATARI__
#	undef XIEITE_PLATFORM_TYPE_ATARI
#	define XIEITE_PLATfORM_TYPE_ATARI 1
#endif

#ifdef __ATARI2600__
#	undef XIEITE_PLATFORM_TYPE_ATARI_2600
#	define XIEITE_PLATfORM_TYPE_ATARI_2600 1
#endif

#ifdef __ATARI5200__
#	undef XIEITE_PLATFORM_TYPE_ATARI_5200
#	define XIEITE_PLATfORM_TYPE_ATARI_5200 1
#endif

#ifdef __LYNX__
#	undef XIEITE_PLATFORM_TYPE_ATARI_LYNX
#	define XIEITE_PLATfORM_TYPE_ATARI_LYNX 1
#endif

#ifdef __ATARIXL__
#	undef XIEITE_PLATFORM_TYPE_ATARI_XL
#	define XIEITE_PLATfORM_TYPE_ATARI_XL 1
#endif

#ifdef __BEOS__
#	undef XIEITE_PLATFORM_TYPE_BEOS
#	define XIEITE_PLATFORM_TYPE_BEOS 1
#endif

#if defined(__THW_BLUEGENE__) || defined(__bg__)
#	undef XIEITE_PLATFORM_TYPE_BLUE_GENE
#	define XIEITE_PLATFORM_TYPE_BLUE_GENE 1
#endif

#if defined(BSD) || defined(_SYSTYPE_BSD) || defined(__DragonFly__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__) || defined(__bsdi__)
#	include <sys/param.h>

#	undef XIEITE_PLATFORM_TYPE_BSD
#	define XIEITE_PLATFORM_TYPE_BSD 1

#	undef XIEITE_PLATFORM_MAJOR_BSD
#	define XIEITE_PLATFORM_MAJOR_BSD (BSD / 100)

#	undef XIEITE_PLATFORM_MINOR_BSD
#	define XIEITE_PLATFORM_MINOR_BSD (BSD % 100)
#endif

#ifdef __bsdi__
#	undef XIEITE_PLATFORM_TYPE_BSD_BSDI
#	define XIEITE_PLATFORM_TYPE_BSD_BSDI 1
#endif

#ifdef __DragonFly__
#	undef XIEITE_PLATFORM_TYPE_DRAGONFLY
#	define XIEITE_PLATFORM_TYPE_DRAGONFLY 1
#endif

#if defined(__FreeBSD__) || defined(__FreeBSD_kernel__)
#	include <sys/param.h>

#	undef XIEITE_PLATFORM_TYPE_BSD_FREE
#	define XIEITE_PLATFORM_TYPE_BSD_FREE 1

#	undef XIEITE_PLATFORM_MAJOR_BSD_FREE
#	define XIEITE_PLATFORM_MAJOR_BSD_FREE (__FreeBSD_version / 100000)

#	undef XIEITE_PLATFORM_MINOR_BSD_FREE
#	define XIEITE_PLATFORM_MINOR_BSD_FREE (__FreeBSD_version / 10000 % 10)

#	undef XIEITE_PLATFORM_PATCH_BSD_FREE
#	define XIEITE_PLATFORM_PATCH_BSD_FREE (__FreeBSD_version % 10000)
#endif

#ifdef __NetBSD__
#	include <sys/param.h>

#	undef XIEITE_PLATFORM_TYPE_BSD_NET
#	define XIEITE_PLATFORM_TYPE_BSD_NET 1

#	ifdef __NetBSD_Version
#		undef XIEITE_PLATFORM_MAJOR_BSD_NET
#		define XIEITE_PLATFORM_MAJOR_BSD_NET (__NetBSD_Version / 100000000)

#		undef XIEITE_PLATFORM_MINOR_BSD_NET
#		define XIEITE_PLATFORM_MINOR_BSD_NET (__NetBSD_Version / 1000000 % 100)

#		undef XIEITE_PLATFORM_PATCH_BSD_NET
#		define XIEITE_PLATFORM_PATCH_BSD_NET (__NetBSD_Version / 100 % 100)
#	elifdef __NetBSD_version
#		undef XIEITE_PLATFORM_MAJOR_BSD_NET
#		define XIEITE_PLATFORM_MAJOR_BSD_NET (__NetBSD_version / 100000000)

#		undef XIEITE_PLATFORM_MINOR_BSD_NET
#		define XIEITE_PLATFORM_MINOR_BSD_NET (__NetBSD_version / 1000000 % 100)

#		undef XIEITE_PLATFORM_PATCH_BSD_NET
#		define XIEITE_PLATFORM_PATCH_BSD_NET (__NetBSD_version / 100 % 100)
#	elifdef NetBSD1_0
#		undef XIEITE_PLATFORM_MAJOR_BSD_NET
#		define XIEITE_PLATFORM_MAJOR_BSD_NET 1
#	elifdef NetBSD0_9
#		undef XIEITE_PLATFORM_MINOR_BSD_NET
#		define XIEITE_PLATFORM_MINOR_BSD_NET 9
#	elifdef NetBSD0_8
#		undef XIEITE_PLATFORM_MINOR_BSD_NET
#		define XIEITE_PLATFORM_MINOR_BSD_NET 8
#	endif
#endif

#ifdef __OpenBSD__
#	undef XIEITE_PLATFORM_TYPE_BSD_OPEN
#	define XIEITE_PLATFORM_TYPE_BSD_OPEN 1

#	ifdef OpenBSD2_0
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2
#	elifdef OpenBSD2_1
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 1
#	elifdef OpenBSD2_2
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 2
#	elifdef OpenBSD2_3
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 3
#	elifdef OpenBSD2_4
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 4
#	elifdef OpenBSD2_5
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 5
#	elifdef OpenBSD2_6
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 6
#	elifdef OpenBSD2_7
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 7
#	elifdef OpenBSD2_8
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 8
#	elifdef OpenBSD2_9
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 9
#	elifdef OpenBSD3_0
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3
#	elifdef OpenBSD3_1
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 1
#	elifdef OpenBSD3_2
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 2
#	elifdef OpenBSD3_3
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 3
#	elifdef OpenBSD3_4
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 4
#	elifdef OpenBSD3_5
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 5
#	elifdef OpenBSD3_6
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 6
#	elifdef OpenBSD3_7
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 7
#	elifdef OpenBSD3_8
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 8
#	elifdef OpenBSD3_9
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 9
#	elifdef OpenBSD4_0
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4
#	elifdef OpenBSD4_1
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 1
#	elifdef OpenBSD4_2
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 2
#	elifdef OpenBSD4_3
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 3
#	elifdef OpenBSD4_4
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 4
#	elifdef OpenBSD4_5
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 5
#	elifdef OpenBSD4_6
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 6
#	elifdef OpenBSD4_7
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 7
#	elifdef OpenBSD4_8
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 8
#	elifdef OpenBSD4_9
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 9
#	elifdef OpenBSD5_0
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5
#	elifdef OpenBSD5_1
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 1
#	elifdef OpenBSD5_2
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 2
#	elifdef OpenBSD5_3
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 3
#	elifdef OpenBSD5_4
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 4
#	elifdef OpenBSD5_5
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 5
#	elifdef OpenBSD5_6
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 6
#	elifdef OpenBSD5_7
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 7
#	elifdef OpenBSD5_8
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 8
#	elifdef OpenBSD5_9
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 9
#	elifdef OpenBSD6_0
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6
#	elifdef OpenBSD6_1
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 1
#	elifdef OpenBSD6_2
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 2
#	elifdef OpenBSD6_3
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 3
#	elifdef OpenBSD6_4
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 4
#	elifdef OpenBSD6_5
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 5
#	elifdef OpenBSD6_6
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 6
#	elifdef OpenBSD6_7
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 7
#	elifdef OpenBSD6_8
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 8
#	elifdef OpenBSD6_9
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 9
#	elifdef OpenBSD7_0
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 7
#	elifdef OpenBSD7_1
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 1
#	elifdef OpenBSD7_2
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 2
#	elifdef OpenBSD7_3
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 3
#	elifdef OpenBSD7_4
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 4
#	elifdef OpenBSD7_5
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 5
#	elifdef OpenBSD7_6
#		undef XIEITE_PLATFORM_MAJOR_BSD_OPEN
#		define XIEITE_PLATFORM_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLATFORM_MINOR_BSD_OPEN
#		define XIEITE_PLATFORM_MINOR_BSD_OPEN 6
#	endif // TODO: Detect more versions
#endif

#ifdef __CloudABI__
#	undef XIEITE_PLATFORM_TYPE_CLOUDABI
#	define XIEITE_PLATFORM_TYPE_CLOUDABI 1
#endif

#ifdef __CMB__
#	undef XIEITE_PLATFORM_TYPE_CMB
#	define XIEITE_PLATFORM_TYPE_CMB 1
#endif

#ifdef __CMB510__
#	undef XIEITE_PLATFORM_TYPE_CMB_500
#	define XIEITE_PLATFORM_TYPE_CMB_500 1
#endif

#ifdef __CMB610__
#	undef XIEITE_PLATFORM_TYPE_CMB_600
#	define XIEITE_PLATFORM_TYPE_CMB_600 1
#endif

#ifdef __CX16__
#	undef XIEITE_PLATFORM_TYPE_COMMANDER_X16
#	define XIEITE_PLATFORM_TYPE_COMMANDER_X16 1
#endif

#ifdef __C16__
#	undef XIEITE_PLATFORM_TYPE_COMMODORE_16
#	define XIEITE_PLATFORM_TYPE_COMMODORE_16 1
#endif

#ifdef __C64__
#	undef XIEITE_PLATFORM_TYPE_COMMODORE_64
#	define XIEITE_PLATFORM_TYPE_COMMODORE_64 1
#endif

#ifdef __C128__
#	undef XIEITE_PLATFORM_TYPE_COMMODORE_128
#	define XIEITE_PLATFORM_TYPE_COMMODORE_128 1
#endif

#ifdef __PLUS4__
#	undef XIEITE_PLATFORM_TYPE_COMMODORE_PLUS_4
#	define XIEITE_PLATFORM_TYPE_COMMODORE_PLUS_4 1
#endif

#ifdef __VIC20__
#	undef XIEITE_PLATFORM_TYPE_COMMODORE_VIC20
#	define XIEITE_PLATFORM_TYPE_COMMODORE_VIC20 1
#endif

#ifdef __convex__
#	undef XIEITE_PLATFORM_TYPE_CONVEXOS
#	define XIEITE_PLATFORM_TYPE_CONVEXOS 1
#endif

#ifdef __CYGWIN__
#	undef XIEITE_PLATFORM_TYPE_CYGWIN
#	define XIEITE_PLATFORM_TYPE_CYGWIN 1

#	undef XIEITE_PLATFORM_MAJOR_CYGWIN
#	define XIEITE_PLATFORM_MAJOR_CYGWIN CYGWIN_VERSION_API_MAJOR

#	undef XIEITE_PLATFORM_MINOR_CYGWIN
#	define XIEITE_PLATFORM_MINOR_CYGWIN CYGWIN_VERSION_API_MINOR
#endif

#ifdef pyr
#	undef XIEITE_PLATFORM_TYPE_DC_OSX
#	define XIEITE_PLATFORM_TYPE_DC_OSX 1
#endif

#if defined(DGUX) || defined(__DGUX__) || defined(__dgux__)
#	undef XIEITE_PLATFORM_TYPE_DG_UX
#	define XIEITE_PLATFORM_TYPE_DG_UX 1
#endif

#ifdef apollo
#	undef XIEITE_PLATFORM_TYPE_DOMAIN_OS
#	define XIEITE_PLATFORM_TYPE_DOMAIN_OS 1
#endif

#ifdef __DragonFly__
#	undef XIEITE_PLATFORM_TYPE_DRAGONFLY
#	define XIEITE_PLATFORM_TYPE_DRAGONFLY 1
#endif

#if defined(_SEQUENT_) || defined(sequent)
#	undef XIEITE_PLATFORM_TYPE_DYNIX
#	define XIEITE_PLATFORM_TYPE_DYNIX 1
#endif

#ifdef __ECOS
#	undef XIEITE_PLATFORM_TYPE_ECOS
#	define XIEITE_PLATFORM_TYPE_ECOS 1
#endif

#ifdef __EMX__
#	undef XIEITE_PLATFORM_TYPE_EMX
#	define XIEITE_PLATFORM_TYPE_EMX 1
#endif

#ifdef __Fuchsia__
#	undef XIEITE_PLATFORM_TYPE_FUCHSIA
#	define XIEITE_PLATFORM_TYPE_FUCHSIA 1
#endif

#ifdef __GEOS__
#	undef XIEITE_PLATFORM_TYPE_GEOS
#	define XIEITE_PLATFORM_TYPE_GEOS 1
#endif

#ifdef __GEOS_APPLE__
#	undef XIEITE_PLATFORM_TYPE_GEOS_APPLE
#	define XIEITE_PLATFORM_TYPE_GEOS_APPLE 1
#endif

#ifdef __GEOS_CMB__
#	undef XIEITE_PLATFORM_TYPE_GEOS_CMB
#	define XIEITE_PLATFORM_TYPE_GEOS_CMB 1
#endif

#if defined(__GNU__) || defined(__gnu_hurd__)
#	undef XIEITE_PLATFORM_TYPE_GNU_HURD
#	define XIEITE_PLATFORM_TYPE_GNU_HURD 1
#endif

#if defined(__FreeBSD_kernel__) && defined(__GLIBC__)
#	undef XIEITE_PLATFORM_TYPE_GNU_KFREEBSD
#	define XIEITE_PLATFORM_TYPE_GNU_KFREEBSD 1
#endif

#ifdef __gnu_linux__
#	undef XIEITE_PLATFORM_TYPE_GNU_LINUX
#	define XIEITE_PLATFORM_TYPE_GNU_LINUX 1
#endif

#ifdef __HAIKU__
#	undef XIEITE_PLATFORM_TYPE_HAIKU
#	define XIEITE_PLATFORM_TYPE_HAIKU 1
#endif

#ifdef __hiuxmpp
#	undef XIEITE_PLATFORM_TYPE_HI_UX_MPP
#	define XIEITE_PLATFORM_TYPE_HI_UX_MPP 1
#endif

#if defined(__hpux) || defined(__hpux__) || defined(_hpux) || defined(hpux)
#	undef XIEITE_PLATFORM_TYPE_HP_UX
#	define XIEITE_PLATFORM_TYPE_HP_UX 1
#endif

#ifdef __INTEGRITY
#	undef XIEITE_PLATFORM_TYPE_INTEGRITY
#	define XIEITE_PLATFORM_TYPE_INTEGRITY 1
#endif

#if defined(TARGET_IPHONE_SIMULATOR) || defined(TARGET_OS_SIMULATOR)
#	undef XIEITE_PLATFORM_TYPE_IOS_SIMULATOR
#	define XIEITE_PLATFORM_TYPE_IOS_SIMULATOR 1
#endif

#ifdef __INTERIX
#	undef XIEITE_PLATFORM_TYPE_INTERIX
#	define XIEITE_PLATFORM_TYPE_INTERIX 1
#endif

#if defined(__sgi) || defined(sgi)
#	undef XIEITE_PLATFORM_TYPE_IRIX
#	define XIEITE_PLATFORM_TYPE_IRIX 1
#endif

#ifdef __KOS__
#	undef XIEITE_PLATFORM_TYPE_KALLISTI
#	define XIEITE_PLATFORM_TYPE_KALLISTI 1
#endif

#if defined(__gnu_linux__) || defined(__linux) || defined(__linux__) || defined(linux)
#	undef XIEITE_PLATFORM_TYPE_LINUX
#	define XIEITE_PLATFORM_TYPE_LINUX 1
#endif

#ifdef __LUNIX__
#	undef XIEITE_PLATFORM_TYPE_LUNIX
#	define XIEITE_PLATFORM_TYPE_LUNIX 1
#endif

#ifdef __Lynx__
#	undef XIEITE_PLATFORM_TYPE_LYNXOS
#	define XIEITE_PLATFORM_TYPE_LYNXOS 1
#endif

#if defined(Macintosh) || defined(__APPLE__) || defined(__MACH__) || defined(macintosh)
#	undef XIEITE_PLATFORM_TYPE_MACINTOSH
#	define XIEITE_PLATFORM_TYPE_MACINTOSH 1

#	undef XIEITE_PLATFORM_MAJOR_MACINTOSH
#	if defined(__APPLE__) && defined(__MACH__)
#		define XIEITE_PLATFORM_MAJOR_MACINTOSH 10
#	else
#		define XIEITE_PLATFORM_MAJOR_MACINTOSH 9
#	endif
#endif

#ifdef MACOSX_DYLD
#	undef XIEITE_PLATFORM_TYPE_MACINTOSH_DYLD
#	define XIEITE_PLATFORM_TYPE_MACINTOSH_DYLD 1
#endif

#ifdef __MINGW32__
#	undef XIEITE_PLATFORM_TYPE_MINGW32
#	define XIEITE_PLATFORM_TYPE_MINGW32 1

#	undef XIEITE_PLATFORM_MAJOR_MINGW32
#	define XIEITE_PLATFORM_MAJOR_MINGW32 __MING32_VERSION_MAJOR

#	undef XIEITE_PLATFORM_MINOR_MINGW32
#	define XIEITE_PLATFORM_MINOR_MINGW32 __MING32_VERSION_MINOR
#endif

#ifdef __MINGW64__
#	undef XIEITE_PLATFORM_TYPE_MINGW64
#	define XIEITE_PLATFORM_TYPE_MINGW64 1

#	undef XIEITE_PLATFORM_MAJOR_MINGW64
#	define XIEITE_PLATFORM_MAJOR_MINGW64 __MING64_VERSION_MAJOR

#	undef XIEITE_PLATFORM_MINOR_MINGW64
#	define XIEITE_PLATFORM_MINOR_MINGW64 __MING64_VERSION_MINOR
#endif

#if defined(_MINIX) || defined(__minix) || defined(__minix__)
#	undef XIEITE_PLATFORM_TYPE_MINIX
#	define XIEITE_PLATFORM_TYPE_MINIX 1
#endif

#ifdef __MORPHOS__
#	undef XIEITE_PLATFORM_TYPE_MORPHOS
#	define XIEITE_PLATFORM_TYPE_MORPHOS 1
#endif

#if defined(mpeix) || defined(__mpexl)
#	undef XIEITE_PLATFORM_TYPE_MPE_IX
#	define XIEITE_PLATFORM_TYPE_MPE_IX 1
#endif

#if defined(MSDOS) || defined(_MSDOS) || defined(__DOS__) || defined(__MSDOS) || defined(__MSDOS__)
#	undef XIEITE_PLATFORM_TYPE_MS_DOS
#	define XIEITE_PLATFORM_TYPE_MS_DOS 1
#endif

#ifdef __native_client__
#	undef XIEITE_PLATFORM_TYPE_NACL
#	define XIEITE_PLATFORM_TYPE_NACL 1
#endif

#ifdef __NES__
#	undef XIEITE_PLATFORM_TYPE_NES
#	define XIEITE_PLATFORM_TYPE_NES 1
#endif

#ifdef NeXT
#	undef XIEITE_PLATFORM_TYPE_NEXT
#	define XIEITE_PLATFORM_TYPE_NEXT 1
#endif

#ifdef __3DS__
#	undef XIEITE_PLATFORM_TYPE_NINTENDO_3DS
#	define XIEITE_PLATFORM_TYPE_NINTENDO_3DS 1
#endif

#if (defined(__PPC__) || defined(__ppc__)) && defined(_GC) || defined(__GAMECUBE__)
#	undef XIEITE_PLATFORM_TYPE_NINTENDO_GAMECUBE
#	define XIEITE_PLATFORM_TYPE_NINTENDO_GAMECUBE 1
#endif

#ifdef __NX__
#	undef XIEITE_PLATFORM_TYPE_NINTENDO_SWITCH
#	define XIEITE_PLATFORM_TYPE_NINTENDO_SWITCH 1
#endif

#ifdef __TANDEM
#	undef XIEITE_PLATFORM_TYPE_NONSTOP
#	define XIEITE_PLATFORM_TYPE_NONSTOP 1
#endif

#ifdef __nucleus__
#	undef XIEITE_PLATFORM_TYPE_NUCLEUS_RTOS
#	define XIEITE_PLATFORM_TYPE_NUCLEUS_RTOS 1
#endif

#ifdef __OSIC1P__
#	undef XIEITE_PLATFORM_TYPE_OHIO_SCIENTIFIC_COMPUTER_1P
#	define XIEITE_PLATFORM_TYPE_OHIO_SCIENTIFIC_COMPUTER_1P 1
#endif

#ifdef __OpenBSD__
#	undef XIEITE_PLATFORM_TYPE_OPENBSD
#	define XIEITE_PLATFORM_TYPE_OPENBSD 1
#endif

#if defined(M_I386) || defined(M_XENIX) || defined(_SCO_DS)
#	undef XIEITE_PLATFORM_TYPE_OPENSERVER
#	define XIEITE_PLATFORM_TYPE_OPENSERVER 1
#endif

#ifdef __ATMOS__
#	undef XIEITE_PLATFORM_TYPE_ORIC_ATMOS
#	define XIETIE_PLATFORM_TYPE_ORIC_ATMOS 1
#endif

#if defined(OS2) || defined(_OS2) || defined(__OS2__) || defined(__TOS_OS2__)
#	undef XIEITE_PLATFORM_TYPE_OS_2
#	define XIEITE_PLATFORM_TYPE_OS_2 1
#endif

#ifdef __OS400__
#	undef XIEITE_PLATFORM_TYPE_OS_400
#	define XIEITE_PLATFORM_TYPE_OS_400 1
#endif

#if defined(_OSK) || defined(__OS9000)
#	undef XIEITE_PLATFORM_TYPE_OS_9
#	define XIEITE_PLATFORM_TYPE_OS_9 1
#endif

#ifdef __palmos__
#	undef XIEITE_PLATFORM_TYPE_PALM_OS
#	define XIEITE_PLATFORM_TYPE_PALM_OS 1
#endif

#ifdef __PDOS386__
#	undef XIEITE_PLATFORM_TYPE_PDOS
#	define XIEITE_PLATFORM_TYPE_PDOS 1
#endif

#ifdef __PET__
#	undef XIEITE_PLATFORM_TYPE_PET
#	define XIEITE_PLATFORM_TYPE_PET 1
#endif

#if defined(__phoenix) || defined(__phoenix__) || defined(phoenix)
#	undef XIEITE_PLATFORM_TYPE_PHOENIX
#	define XIEITE_PLATFORM_TYPE_PHOENIX 1
#endif

#ifdef EPLAN9
#	undef XIEITE_PLATFORM_TYPE_PLAN_9
#	define XIEITE_PLATFORM_TYPE_PLAN_9 1
#endif

#ifdef __pnacl__
#	undef XIEITE_PLATFORM_TYPE_PNACL
#	define XIEITE_PLATFORM_TYPE_PNACL 1
#endif

#if defined(__QNXNTO__) || defined(__QNX__)
#	include <sys/neutrino.h>

#	undef XIEITE_PLATFORM_TYPE_QNX
#	define XIEITE_PLATFORM_TYPE_QNX 1

#	ifdef __QNXNTO__
#		undef XIEITE_PLATFORM_MAJOR_QNX
#		define XIEITE_PLATFORM_MAJOR_QNX (_NTO_VERSION / 100)

#		undef XIEITE_PLATFORM_MINOR_QNX
#		define XIEITE_PLATFORM_MINOR_QNX (_NTO_VERSION / 10 % 10)

#		undef XIEITE_PLATFORM_PATCH_QNX
#		define XIEITE_PLATFORM_PATCH_QNX (_NTO_VERSION % 10)
#	elifdef __QNX__
#		undef XIEITE_PLATFORM_MAJOR_QNX
#		define XIEITE_PLATFORM_MAJOR_QNX 4
#	endif
#endif

#if (defined(__GNUC__) && !defined(__SNC__) && defined(__SH4_SINGLE_ONLY__)) || defined(_arch_dreamcast)
#	undef XIEITE_PLATFORM_TYPE_SEGA_DREAMCAST
#	define XIEITE_PLATFORM_TYPE_SEGA_DREAMCAST 1
#endif

#ifdef __SIM6502__
#	undef XIEITE_PLATFORM_TYPE_SIM6502
#	define XIEITE_PLATFORM_TYPE_SIM6502 1
#endif

#ifdef __SIM65C02__
#	undef XIEITE_PLATFORM_TYPE_SIM65C02
#	define XIEITE_PLATFORM_TYPE_SIM65C02 1
#endif

#ifdef sinux
#	undef XIEITE_PLATFORM_TYPE_SINIX
#	define XIEITE_PLATFORM_TYPE_SINIX 1
#endif

#if defined(sun) || defined(__sun)
#	undef XIEITE_PLATFORM_TYPE_SOLARIS
#	define XIEITE_PLATFORM_TYPE_SOLARIS 1
#endif

#ifdef __SCE__
#	undef XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION
#	define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION 1
#endif

#if defined(PS2) || defined(__PS2__)
#	undef XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_2
#	define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_2 1
#endif

#ifdef __CELLOS_LV2__
#	undef XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_3
#	define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_3 1
#endif

#ifdef __ORBIS__
#	undef XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_4
#	define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_4 1
#endif

#ifdef __PROSPERO__
#	undef XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_5
#	define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_5 1
#endif

#if defined(__psp__) || defined(__PSP__)
#	undef XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_P
#	define XIEITE_PLATFORM_TYPE_SONY_PLAYSTATION_P 1
#endif

#if defined(__psp2__) || defined(__vita__)
#	undef XIEITE_PLATFORM_TYPE_SONY_VITA
#	define XIEITE_PLATFORM_TYPE_SONY_VITA 1
#endif

#ifdef __SUPERVISION__
#	undef XIEITE_PLATFORM_TYPE_SUPERVISION
#	define XIEITE_PLATFORM_TYPE_SUPERVISION 1
#endif

#ifdef __SYGWIN__
#	undef XIEITE_PLATFORM_TYPE_SYGWIN
#	define XIEITE_PLATFORM_TYPE_SYGWIN 1
#endif

#ifdef __SYLLABLE__
#	undef XIEITE_PLATFORM_TYPE_SYLLABLE
#	define XIEITE_PLATFORM_TYPE_SYLLABLE 1
#endif

#ifdef __SYM1__
#	undef XIEITE_PLATFORM_TYPE_SYM1
#	define XIEITE_PLATFORM_TYPE_SYM1 1
#endif

#ifdef __SYMBIAN32__
#	undef XIEITE_PLATFORM_TYPE_SYMBIAN
#	define XIEITE_PLATFORM_TYPE_SYMBIAN 1
#endif

#if defined(_SYSTYPE_SVR4) || defined(__SVR4) || defined(__svr4__) || defined(__sysv__)
#	undef XIEITE_PLATFORM_TYPE_SYSTEM_V
#	define XIEITE_PLATFORM_TYPE_SYSTEM_V 1
#endif

#ifdef __TELESTRAT__
#	undef XIEITE_PLATFORM_TYPE_TELESTRAT
#	define XIEITE_PLATFORM_TYPE_TELESTRAT 1
#endif

#if defined(__OSF__) || defined(__osf) || defined(__osf__)
#	undef XIEITE_PLATFORM_TYPE_TRU64
#	define XIEITE_PLATFORM_TYPE_TRU64 1
#endif

#ifdef __uClinux__
#	undef XIEITE_PLATFORM_TYPE_UCLINUX
#	define XIEITE_PLATFORM_TYPE_UCLINUX 1
#endif

#if defined(__ultrix) || defined(__ultrix__) || defined(ultrix) || (defined(unix) && defined(vax))
#	undef XIEITE_PLATFORM_TYPE_ULTRIX
#	define XIEITE_PLATFORM_TYPE_ULTRIX 1
#endif

#ifdef _UNICOS
#	undef XIEITE_PLATFORM_TYPE_UNICOS
#	define XIEITE_PLATFORM_TYPE_UNICOS 1

#	undef XIEITE_PLATFORM_MAJOR_UNICOS
#	define XIEITE_PLATFORM_MAJOR_UNICOS _UNICOS
#endif

#if defined(_CRAY) || defined(_UNICOSMP) || defined(__crayx1)
#	undef XIEITE_PLATFORM_TYPE_UNICOS_MP
#	define XIEITE_PLATFORM_TYPE_UNICOS_MP 1
#endif

#if defined(_POSIX_SOURCE) || defined(_XOPEN_SOURCE) || defined(__unix) || defined(__unix__) || defined(unix)
#	undef XIEITE_PLATFORM_TYPE_UNIX
#	define XIEITE_PLATFORM_TYPE_UNIX 1
#endif

#if defined(_UNIXWARE7) || defined(sco)
#	undef XIEITE_PLATFORM_TYPE_UNIXWARE
#	define XIEITE_PLATFORM_TYPE_UNIXWARE 1
#endif

#ifdef UTS
#	undef XIEITE_PLATFORM_TYPE_UTS
#	define XIEITE_PLATFORM_TYPE_UTS 1
#endif

#ifdef _UWIN
#	undef XIEITE_PLATFORM_TYPE_UWIN
#	define XIEITE_PLATFORM_TYPE_UWIN 1
#endif

#if defined(VMS) || defined(__VMS) || defined(__VMS__) || defined(__vms) || defined(__vms__)
#	undef XIEITE_PLATFORM_TYPE_VMS
#	define XIEITE_PLATFORM_TYPE_VMS 1

#	undef XIEITE_PLATFORM_MAJOR_VMS
#	define XIEITE_PLATFORM_MAJOR_VMS (__VMS_VER / 10000000)

#	undef XIEITE_PLATFORM_MINOR_VMS
#	define XIEITE_PLATFORM_MINOR_VMS (__VMS_VER / 100000 % 100)

#	undef XIEITE_PLATFORM_PATCH_VMS
#	define XIEITE_PLATFORM_PATCH_VMS (__VMS_VER / 100 % 100)
#endif

#ifdef __VOS__
#	undef XIEITE_PLATFORM_TYPE_VOS
#	define XIEITE_PLATFORM_TYPE_VOS 1

#	undef XIEITE_PALTFORM_VERSION_MAJOR_VOS
#	define XIEITE_PLATFORM_MAJOR_VOS __VOS__
#endif

#if defined(__VXWORKS__) || defined(__vxworks)
#	include <version.h>

#	undef XIEITE_PLATFORM_TYPE_VXWORKS
#	define XIEITE_PLATFORM_TYPE_VXWORKS 1

#	undef XIEITE_PLATFORM_MAJOR_VXWORKS
#	define XIEITE_PLATFORM_MAJOR_VXWORKS _WRS_VXWORKS_MAJOR

#	undef XIEITE_PLATFORM_MINOR_VXWORKS
#	define XIEITE_PLATFORM_MINOR_VXWORKS _WRS_VXWORKS_MINOR

#	undef XIEITE_PLATFORM_PATCH_VXWORKS
#	define XIEITE_PLATFORM_PATCH_VXWORKS _WRS_VXWORKS_MAINT
#endif

#if defined(WIN16) || defined(WIN32) || defined(WIN64) || defined(_WIN16) || defined(_WIN32) || defined(_WIN64) || defined(__TOS_WIN__) || defined(__WIN16) || defined(__WIN16__) || defined(__WIN32) || defined(__WIN32__) || defined(__WIN64) || defined(__WIN64__) || defined(__WINDOWS__)
#	undef XIEITE_PLATFORM_TYPE_WINDOWS
#	define XIEITE_PLATFORM_TYPE_WINDOWS 1
#endif

#ifdef _WIN32_WCE
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_CE
#	define XIEITE_PLATFORM_TYPE_WINDOWS_CE 1

#	undef XIEITE_PLATFORM_MAJOR_WINDOWS_CE
#	define XIEITE_PLATFORM_MAJOR_WINDOWS_CE (_WIN32_WCE / 100)

#	undef XIEITE_PLATFORM_MINOR_WINDOWS_CE
#	define XIEITE_PLATFORM_MINOR_WINDOWS_CE (_WIN32_WCE % 100)
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_DESKTOP_APP) && (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_DESKTOP
#	define XIEITE_PLATFORM_TYPE_WINDOWS_DESKTOP 1
#endif

#ifdef _GAMING_DESKTOP
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_GDK
#	define XIEITE_PLATFORM_TYPE_WINDOWS_GDK 1
#endif

#if defined(__WINNT__) || defined(__NT__)
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_NT
#	define XIEITE_PLATFORM_TYPE_WINDOWS_NT 1
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_PHONE_APP) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_PHONE
#	define XIEITE_PLATFORM_TYPE_WINDOWS_PHONE 1
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_SERVER) && (WINAPI_FAMILY == WINAPI_FAMILY_SERVER)
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_SERVER
#	define XIEITE_PLATFORM_TYPE_WINDOWS_SERVER 1
#endif

#if defined(WINAPI_FAMILY) && (defined(WINAPI_FAMILY_APP) || defined(WINAPI_FAMILY_PC_APP)) && ((WINAPI_FAMILY == WINAPI_FAMILY_APP) || (WINAPI_FAMILY == WINAPI_FAMILY_PC_APP))
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_STORE
#	define XIEITE_PLATFORM_TYPE_WINDOWS_STORE 1
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_SYSTEM) && (WINAPI_FAMILY == WINAPI_FAMILY_SYSTEM)
#	undef XIEITE_PLATFORM_TYPE_WINDOWS_SYSTEM
#	define XIEITE_PLATFORM_TYPE_WINDOWS_SYSTEM 1
#endif

#ifdef _WINDU_SOURCE
#	undef XIEITE_PLATFORM_TYPE_WIND_U
#	define XIEITE_PLATFORM_TYPE_WIND_U 1

#	undef XIEITE_PLATFORM_MAJOR_WIND_U
#	define XIEITE_PLATFORM_MAJOR_WIND_U (_WINDU_SOURCE / 0x10000)

#	undef XIEITE_PLATFORM_MINOR_WIND_U
#	define XIEITE_PLATFORM_MINOR_WIND_U (_WINDU_SOURCE / 0x100 % 0x100)

#	undef XIEITE_PLATFORM_PATCH_WIND_U
#	define XIEITE_PLATFORM_PATCH_WIND_U (_WINDU_SOURCE % 0x100)
#endif

#ifdef _XBOX_VER
#	undef XIEITE_PLATFORM_TYPE_XBOX
#	define XIEITE_PLATFORM_TYPE_XBOX 1
#endif

#if defined(_XBOX_VER) && (_XBOX_VER >= 200)
#	undef XIEITE_PLATFORM_TYPE_XBOX_360
#	define XIEITE_PLATFORM_TYPE_XBOX_360 1
#endif

#if defined(_DURANGO) || defined(_GAMING_XBOX_XBOXONE) || defined(_XBOX_ONE)
#	undef XIEITE_PLATFORM_TYPE_XBOX_ONE
#	define XIEITE_PLATFORM_TYPE_XBOX_ONE 1
#endif

#ifdef _GAMING_XBOX_SCARLETT
#	undef XIEITE_PLATFORM_TYPE_XBOX_SERIES
#	define XIEITE_PLATFORM_TYPE_XBOX_SERIES 1
#endif

#if defined(__HOS_MVS__) || defined(__MVS__) || defined(__TOS_MVS__)
#	undef XIEITE_PLATFORM_TYPE_Z
#	define XIEITE_PLATFORM_TYPE_Z 1
#endif

// https://github.com/cpredef/predef/blob/master/OperatingSystems.md
// https://cc65.github.io/doc/cc65.html#s6
// Thanks to Ian Pike (https://github.com/Rinzii) for some detection macros
