#pragma once

#define XIEITE_PLTF_TYPE_AEGIS 0
#define XIEITE_PLTF_MAJOR_AEGIS 0
#define XIEITE_PLTF_MINOR_AEGIS 0
#define XIEITE_PLTF_PATCH_AEGIS 0
#define XIEITE_PLTF_TYPE_AIX 0
#define XIEITE_PLTF_MAJOR_AIX 0
#define XIEITE_PLTF_MINOR_AIX 0
#define XIEITE_PLTF_PATCH_AIX 0
#define XIEITE_PLTF_TYPE_AKAROS 0
#define XIEITE_PLTF_MAJOR_AKAROS 0
#define XIEITE_PLTF_MINOR_AKAROS 0
#define XIEITE_PLTF_PATCH_AKAROS 0
#define XIEITE_PLTF_TYPE_AMIGAOS 0
#define XIEITE_PLTF_MAJOR_AMIGAOS 0
#define XIEITE_PLTF_MINOR_AMIGAOS 0
#define XIEITE_PLTF_PATCH_AMIGAOS 0
#define XIEITE_PLTF_TYPE_ANDROID 0
#define XIEITE_PLTF_MAJOR_ANDROID 0
#define XIEITE_PLTF_MINOR_ANDROID 0
#define XIEITE_PLTF_PATCH_ANDROID 0
#define XIEITE_PLTF_TYPE_ASMJS 0
#define XIEITE_PLTF_MAJOR_ASMJS 0
#define XIEITE_PLTF_MINOR_ASMJS 0
#define XIEITE_PLTF_PATCH_ASMJS 0
#define XIEITE_PLTF_TYPE_BEOS 0
#define XIEITE_PLTF_MAJOR_BEOS 0
#define XIEITE_PLTF_MINOR_BEOS 0
#define XIEITE_PLTF_PATCH_BEOS 0
#define XIEITE_PLTF_TYPE_BLUE_GENE 0
#define XIEITE_PLTF_MAJOR_BLUE_GENE 0
#define XIEITE_PLTF_MINOR_BLUE_GENE 0
#define XIEITE_PLTF_PATCH_BLUE_GENE 0
#define XIEITE_PLTF_TYPE_BSD 0
#define XIEITE_PLTF_MAJOR_BSD 0
#define XIEITE_PLTF_MINOR_BSD 0
#define XIEITE_PLTF_PATCH_BSD 0
#define XIEITE_PLTF_TYPE_BSD_BSDI 0
#define XIEITE_PLTF_MAJOR_BSD_BSDI 0
#define XIEITE_PLTF_MINOR_BSD_BSDI 0
#define XIEITE_PLTF_PATCH_BSD_BSDI 0
#define XIEITE_PLTF_TYPE_BSD_DRAGONFLY 0
#define XIEITE_PLTF_MAJOR_BSD_DRAGONFLY 0
#define XIEITE_PLTF_MINOR_BSD_DRAGONFLY 0
#define XIEITE_PLTF_PATCH_BSD_DRAGONFLY 0
#define XIEITE_PLTF_TYPE_BSD_FREE 0
#define XIEITE_PLTF_MAJOR_BSD_FREE 0
#define XIEITE_PLTF_MINOR_BSD_FREE 0
#define XIEITE_PLTF_PATCH_BSD_FREE 0
#define XIEITE_PLTF_TYPE_BSD_NET 0
#define XIEITE_PLTF_MAJOR_BSD_NET 0
#define XIEITE_PLTF_MINOR_BSD_NET 0
#define XIEITE_PLTF_PATCH_BSD_NET 0
#define XIEITE_PLTF_TYPE_BSD_OPEN 0
#define XIEITE_PLTF_MAJOR_BSD_OPEN 0
#define XIEITE_PLTF_MINOR_BSD_OPEN 0
#define XIEITE_PLTF_PATCH_BSD_OPEN 0
#define XIEITE_PLTF_TYPE_CLOUDABI 0
#define XIEITE_PLTF_MAJOR_CLOUDABI 0
#define XIEITE_PLTF_MINOR_CLOUDABI 0
#define XIEITE_PLTF_PATCH_CLOUDABI 0
#define XIEITE_PLTF_TYPE_CONVEXOS 0
#define XIEITE_PLTF_MAJOR_CONVEXOS 0
#define XIEITE_PLTF_MINOR_CONVEXOS 0
#define XIEITE_PLTF_PATCH_CONVEXOS 0
#define XIEITE_PLTF_TYPE_CYGWIN 0
#define XIEITE_PLTF_MAJOR_CYGWIN 0
#define XIEITE_PLTF_MINOR_CYGWIN 0
#define XIEITE_PLTF_PATCH_CYGWIN 0
#define XIEITE_PLTF_TYPE_DC_OSX 0
#define XIEITE_PLTF_MAJOR_DC_OSX 0
#define XIEITE_PLTF_MINOR_DC_OSX 0
#define XIEITE_PLTF_PATCH_DC_OSX 0
#define XIEITE_PLTF_TYPE_DG_UX 0
#define XIEITE_PLTF_MAJOR_DG_UX 0
#define XIEITE_PLTF_MINOR_DG_UX 0
#define XIEITE_PLTF_PATCH_DG_UX 0
#define XIEITE_PLTF_TYPE_DOMAIN_OS 0
#define XIEITE_PLTF_MAJOR_DOMAIN_OS 0
#define XIEITE_PLTF_MINOR_DOMAIN_OS 0
#define XIEITE_PLTF_PATCH_DOMAIN_OS 0
#define XIEITE_PLTF_TYPE_DRAGONFLY 0
#define XIEITE_PLTF_MAJOR_DRAGONFLY 0
#define XIEITE_PLTF_MINOR_DRAGONFLY 0
#define XIEITE_PLTF_PATCH_DRAGONFLY 0
#define XIEITE_PLTF_TYPE_DYNIX 0
#define XIEITE_PLTF_MAJOR_DYNIX 0
#define XIEITE_PLTF_MINOR_DYNIX 0
#define XIEITE_PLTF_PATCH_DYNIX 0
#define XIEITE_PLTF_TYPE_ECOS 0
#define XIEITE_PLTF_MAJOR_ECOS 0
#define XIEITE_PLTF_MINOR_ECOS 0
#define XIEITE_PLTF_PATCH_ECOS 0
#define XIEITE_PLTF_TYPE_EMX 0
#define XIEITE_PLTF_MAJOR_EMX 0
#define XIEITE_PLTF_MINOR_EMX 0
#define XIEITE_PLTF_PATCH_EMX 0
#define XIEITE_PLTF_TYPE_FREEBSD 0
#define XIEITE_PLTF_MAJOR_FREEBSD 0
#define XIEITE_PLTF_MINOR_FREEBSD 0
#define XIEITE_PLTF_PATCH_FREEBSD 0
#define XIEITE_PLTF_TYPE_FUCHSIA 0
#define XIEITE_PLTF_MAJOR_FUCHSIA 0
#define XIEITE_PLTF_MINOR_FUCHSIA 0
#define XIEITE_PLTF_PATCH_FUCHSIA 0
#define XIEITE_PLTF_TYPE_GNU_HURD 0
#define XIEITE_PLTF_MAJOR_GNU_HURD 0
#define XIEITE_PLTF_MINOR_GNU_HURD 0
#define XIEITE_PLTF_PATCH_GNU_HURD 0
#define XIEITE_PLTF_TYPE_GNU_KFREEBSD 0
#define XIEITE_PLTF_MAJOR_GNU_KFREEBSD 0
#define XIEITE_PLTF_MINOR_GNU_KFREEBSD 0
#define XIEITE_PLTF_PATCH_GNU_KFREEBSD 0
#define XIEITE_PLTF_TYPE_GNU_LINUX 0
#define XIEITE_PLTF_MAJOR_GNU_LINUX 0
#define XIEITE_PLTF_MINOR_GNU_LINUX 0
#define XIEITE_PLTF_PATCH_GNU_LINUX 0
#define XIEITE_PLTF_TYPE_HAIKU 0
#define XIEITE_PLTF_MAJOR_HAIKU 0
#define XIEITE_PLTF_MINOR_HAIKU 0
#define XIEITE_PLTF_PATCH_HAIKU 0
#define XIEITE_PLTF_TYPE_HI_UX_MPP 0
#define XIEITE_PLTF_MAJOR_HI_UX_MPP 0
#define XIEITE_PLTF_MINOR_HI_UX_MPP 0
#define XIEITE_PLTF_PATCH_HI_UX_MPP 0
#define XIEITE_PLTF_TYPE_HP_UX 0
#define XIEITE_PLTF_MAJOR_HP_UX 0
#define XIEITE_PLTF_MINOR_HP_UX 0
#define XIEITE_PLTF_PATCH_HP_UX 0
#define XIEITE_PLTF_TYPE_INTEGRITY 0
#define XIEITE_PLTF_MAJOR_INTEGRITY 0
#define XIEITE_PLTF_MINOR_INTEGRITY 0
#define XIEITE_PLTF_PATCH_INTEGRITY 0
#define XIEITE_PLTF_TYPE_INTERIX 0
#define XIEITE_PLTF_MAJOR_INTERIX 0
#define XIEITE_PLTF_MINOR_INTERIX 0
#define XIEITE_PLTF_PATCH_INTERIX 0
#define XIEITE_PLTF_TYPE_IOS_SIMULATOR 0
#define XIEITE_PLTF_MAJOR_IOS_SIMULATOR 0
#define XIEITE_PLTF_MINOR_IOS_SIMULATOR 0
#define XIEITE_PLTF_PATCH_IOS_SIMULATOR 0
#define XIEITE_PLTF_TYPE_IRIX 0
#define XIEITE_PLTF_MAJOR_IRIX 0
#define XIEITE_PLTF_MINOR_IRIX 0
#define XIEITE_PLTF_PATCH_IRIX 0
#define XIEITE_PLTF_TYPE_KALLISTI 0
#define XIEITE_PLTF_MAJOR_KALLISTI 0
#define XIEITE_PLTF_MINOR_KALLISTI 0
#define XIEITE_PLTF_PATCH_KALLISTI 0
#define XIEITE_PLTF_TYPE_LINUX 0
#define XIEITE_PLTF_MAJOR_LINUX 0
#define XIEITE_PLTF_MINOR_LINUX 0
#define XIEITE_PLTF_PATCH_LINUX 0
#define XIEITE_PLTF_TYPE_LYNXOS 0
#define XIEITE_PLTF_MAJOR_LYNXOS 0
#define XIEITE_PLTF_MINOR_LYNXOS 0
#define XIEITE_PLTF_PATCH_LYNXOS 0
#define XIEITE_PLTF_TYPE_MACINTOSH 0
#define XIEITE_PLTF_MAJOR_MACINTOSH 0
#define XIEITE_PLTF_MINOR_MACINTOSH 0
#define XIEITE_PLTF_PATCH_MACINTOSH 0
#define XIEITE_PLTF_TYPE_MACINTOSH_DYLD 0
#define XIEITE_PLTF_MAJOR_MACINTOSH_DYLD 0
#define XIEITE_PLTF_MINOR_MACINTOSH_DYLD 0
#define XIEITE_PLTF_PATCH_MACINTOSH_DYLD 0
#define XIEITE_PLTF_TYPE_MINGW32 0
#define XIEITE_PLTF_MAJOR_MINGW32 0
#define XIEITE_PLTF_MINOR_MINGW32 0
#define XIEITE_PLTF_PATCH_MINGW32 0
#define XIEITE_PLTF_TYPE_MINGW64 0
#define XIEITE_PLTF_MAJOR_MINGW64 0
#define XIEITE_PLTF_MINOR_MINGW64 0
#define XIEITE_PLTF_PATCH_MINGW64 0
#define XIEITE_PLTF_TYPE_MINIX 0
#define XIEITE_PLTF_MAJOR_MINIX 0
#define XIEITE_PLTF_MINOR_MINIX 0
#define XIEITE_PLTF_PATCH_MINIX 0
#define XIEITE_PLTF_TYPE_MORPHOS 0
#define XIEITE_PLTF_MAJOR_MORPHOS 0
#define XIEITE_PLTF_MINOR_MORPHOS 0
#define XIEITE_PLTF_PATCH_MORPHOS 0
#define XIEITE_PLTF_TYPE_MPE_IX 0
#define XIEITE_PLTF_MAJOR_MPE_IX 0
#define XIEITE_PLTF_MINOR_MPE_IX 0
#define XIEITE_PLTF_PATCH_MPE_IX 0
#define XIEITE_PLTF_TYPE_MS_DOS 0
#define XIEITE_PLTF_MAJOR_MS_DOS 0
#define XIEITE_PLTF_MINOR_MS_DOS 0
#define XIEITE_PLTF_PATCH_MS_DOS 0
#define XIEITE_PLTF_TYPE_NACL 0
#define XIEITE_PLTF_MAJOR_NACL 0
#define XIEITE_PLTF_MINOR_NACL 0
#define XIEITE_PLTF_PATCH_NACL 0
#define XIEITE_PLTF_TYPE_NEXT 0
#define XIEITE_PLTF_MAJOR_NEXT 0
#define XIEITE_PLTF_MINOR_NEXT 0
#define XIEITE_PLTF_PATCH_NEXT 0
#define XIEITE_PLTF_TYPE_NONSTOP 0
#define XIEITE_PLTF_MAJOR_NONSTOP 0
#define XIEITE_PLTF_MINOR_NONSTOP 0
#define XIEITE_PLTF_PATCH_NONSTOP 0
#define XIEITE_PLTF_TYPE_NUCLEUS_RTOS 0
#define XIEITE_PLTF_MAJOR_NUCLEUS_RTOS 0
#define XIEITE_PLTF_MINOR_NUCLEUS_RTOS 0
#define XIEITE_PLTF_PATCH_NUCLEUS_RTOS 0
#define XIEITE_PLTF_TYPE_OPENSERVER 0
#define XIEITE_PLTF_MAJOR_OPENSERVER 0
#define XIEITE_PLTF_MINOR_OPENSERVER 0
#define XIEITE_PLTF_PATCH_OPENSERVER 0
#define XIEITE_PLTF_TYPE_OS_2 0
#define XIEITE_PLTF_MAJOR_OS_2 0
#define XIEITE_PLTF_MINOR_OS_2 0
#define XIEITE_PLTF_PATCH_OS_2 0
#define XIEITE_PLTF_TYPE_OS_400 0
#define XIEITE_PLTF_MAJOR_OS_400 0
#define XIEITE_PLTF_MINOR_OS_400 0
#define XIEITE_PLTF_PATCH_OS_400 0
#define XIEITE_PLTF_TYPE_OS_9 0
#define XIEITE_PLTF_MAJOR_OS_9 0
#define XIEITE_PLTF_MINOR_OS_9 0
#define XIEITE_PLTF_PATCH_OS_9 0
#define XIEITE_PLTF_TYPE_PALM_OS 0
#define XIEITE_PLTF_MAJOR_PALM_OS 0
#define XIEITE_PLTF_MINOR_PALM_OS 0
#define XIEITE_PLTF_PATCH_PALM_OS 0
#define XIEITE_PLTF_TYPE_PDOS 0
#define XIEITE_PLTF_MAJOR_PDOS 0
#define XIEITE_PLTF_MINOR_PDOS 0
#define XIEITE_PLTF_PATCH_PDOS 0
#define XIEITE_PLTF_TYPE_PHOENIX 0
#define XIEITE_PLTF_MAJOR_PHOENIX 0
#define XIEITE_PLTF_MINOR_PHOENIX 0
#define XIEITE_PLTF_PATCH_PHOENIX 0
#define XIEITE_PLTF_TYPE_PLAN_9 0
#define XIEITE_PLTF_MAJOR_PLAN_9 0
#define XIEITE_PLTF_MINOR_PLAN_9 0
#define XIEITE_PLTF_PATCH_PLAN_9 0
#define XIEITE_PLTF_TYPE_PNACL 0
#define XIEITE_PLTF_MAJOR_PNACL 0
#define XIEITE_PLTF_MINOR_PNACL 0
#define XIEITE_PLTF_PATCH_PNACL 0
#define XIEITE_PLTF_TYPE_QNX 0
#define XIEITE_PLTF_MAJOR_QNX 0
#define XIEITE_PLTF_MINOR_QNX 0
#define XIEITE_PLTF_PATCH_QNX 0
#define XIEITE_PLTF_TYPE_SINIX 0
#define XIEITE_PLTF_MAJOR_SINIX 0
#define XIEITE_PLTF_MINOR_SINIX 0
#define XIEITE_PLTF_PATCH_SINIX 0
#define XIEITE_PLTF_TYPE_SOLARIS 0
#define XIEITE_PLTF_MAJOR_SOLARIS 0
#define XIEITE_PLTF_MINOR_SOLARIS 0
#define XIEITE_PLTF_PATCH_SOLARIS 0
#define XIEITE_PLTF_TYPE_SYGWIN 0
#define XIEITE_PLTF_MAJOR_SYGWIN 0
#define XIEITE_PLTF_MINOR_SYGWIN 0
#define XIEITE_PLTF_PATCH_SYGWIN 0
#define XIEITE_PLTF_TYPE_SYLLABLE 0
#define XIEITE_PLTF_MAJOR_SYLLABLE 0
#define XIEITE_PLTF_MINOR_SYLLABLE 0
#define XIEITE_PLTF_PATCH_SYLLABLE 0
#define XIEITE_PLTF_TYPE_SYMBIAN 0
#define XIEITE_PLTF_MAJOR_SYMBIAN 0
#define XIEITE_PLTF_MINOR_SYMBIAN 0
#define XIEITE_PLTF_PATCH_SYMBIAN 0
#define XIEITE_PLTF_TYPE_SYSTEM_V 0
#define XIEITE_PLTF_MAJOR_SYSTEM_V 0
#define XIEITE_PLTF_MINOR_SYSTEM_V 0
#define XIEITE_PLTF_PATCH_SYSTEM_V 0
#define XIEITE_PLTF_TYPE_TRU64 0
#define XIEITE_PLTF_MAJOR_TRU64 0
#define XIEITE_PLTF_MINOR_TRU64 0
#define XIEITE_PLTF_PATCH_TRU64 0
#define XIEITE_PLTF_TYPE_UCLINUX 0
#define XIEITE_PLTF_MAJOR_UCLINUX 0
#define XIEITE_PLTF_MINOR_UCLINUX 0
#define XIEITE_PLTF_PATCH_UCLINUX 0
#define XIEITE_PLTF_TYPE_ULTRIX 0
#define XIEITE_PLTF_MAJOR_ULTRIX 0
#define XIEITE_PLTF_MINOR_ULTRIX 0
#define XIEITE_PLTF_PATCH_ULTRIX 0
#define XIEITE_PLTF_TYPE_UNICOS 0
#define XIEITE_PLTF_MAJOR_UNICOS 0
#define XIEITE_PLTF_MINOR_UNICOS 0
#define XIEITE_PLTF_PATCH_UNICOS 0
#define XIEITE_PLTF_TYPE_UNICOS_MP 0
#define XIEITE_PLTF_MAJOR_UNICOS_MP 0
#define XIEITE_PLTF_MINOR_UNICOS_MP 0
#define XIEITE_PLTF_PATCH_UNICOS_MP 0
#define XIEITE_PLTF_TYPE_UNIX 0
#define XIEITE_PLTF_MAJOR_UNIX 0
#define XIEITE_PLTF_MINOR_UNIX 0
#define XIEITE_PLTF_PATCH_UNIX 0
#define XIEITE_PLTF_TYPE_UNIXWARE 0
#define XIEITE_PLTF_MAJOR_UNIXWARE 0
#define XIEITE_PLTF_MINOR_UNIXWARE 0
#define XIEITE_PLTF_PATCH_UNIXWARE 0
#define XIEITE_PLTF_TYPE_UTS 0
#define XIEITE_PLTF_MAJOR_UTS 0
#define XIEITE_PLTF_MINOR_UTS 0
#define XIEITE_PLTF_PATCH_UTS 0
#define XIEITE_PLTF_TYPE_UWIN 0
#define XIEITE_PLTF_MAJOR_UWIN 0
#define XIEITE_PLTF_MINOR_UWIN 0
#define XIEITE_PLTF_PATCH_UWIN 0
#define XIEITE_PLTF_TYPE_VMS 0
#define XIEITE_PLTF_MAJOR_VMS 0
#define XIEITE_PLTF_MINOR_VMS 0
#define XIEITE_PLTF_PATCH_VMS 0
#define XIEITE_PLTF_TYPE_VOS 0
#define XIEITE_PLTF_MAJOR_VOS 0
#define XIEITE_PLTF_MINOR_VOS 0
#define XIEITE_PLTF_PATCH_VOS 0
#define XIEITE_PLTF_TYPE_VXWORKS 0
#define XIEITE_PLTF_MAJOR_VXWORKS 0
#define XIEITE_PLTF_MINOR_VXWORKS 0
#define XIEITE_PLTF_PATCH_VXWORKS 0
#define XIEITE_PLTF_TYPE_WINDOWS 0
#define XIEITE_PLTF_MAJOR_WINDOWS 0
#define XIEITE_PLTF_MINOR_WINDOWS 0
#define XIEITE_PLTF_PATCH_WINDOWS 0
#define XIEITE_PLTF_TYPE_WINDOWS_CE 0
#define XIEITE_PLTF_MAJOR_WINDOWS_CE 0
#define XIEITE_PLTF_MINOR_WINDOWS_CE 0
#define XIEITE_PLTF_PATCH_WINDOWS_CE 0
#define XIEITE_PLTF_TYPE_WINDOWS_NT 0
#define XIEITE_PLTF_MAJOR_WINDOWS_NT 0
#define XIEITE_PLTF_MINOR_WINDOWS_NT 0
#define XIEITE_PLTF_PATCH_WINDOWS_NT 0
#define XIEITE_PLTF_TYPE_WIND_U 0
#define XIEITE_PLTF_MAJOR_WIND_U 0
#define XIEITE_PLTF_MINOR_WIND_U 0
#define XIEITE_PLTF_PATCH_WIND_U 0
#define XIEITE_PLTF_TYPE_Z 0
#define XIEITE_PLTF_MAJOR_Z 0
#define XIEITE_PLTF_MINOR_Z 0
#define XIEITE_PLTF_PATCH_Z 0

#define XIEITE_PLTF_EQ(type, major, ...) XIEITE_DETAIL_PLTF(__VA_ARGS__, XIEITE_DETAIL_PLTF_EQ(type, major, __VA_ARGS__), XIEITE_DETAIL_PLTF_EQ(type, major, __VA_ARGS__, 0), XIEITE_DETAIL_PLTF_EQ(type, major, 0, 0))
#define XIEITE_PLTF_LEAST(type, major, ...) XIEITE_DETAIL_PLTF(__VA_ARGS__, XIEITE_DETAIL_PLTF_LEAST(type, major, __VA_ARGS__), XIEITE_DETAIL_PLTF_LEAST(type, major, __VA_ARGS__, 0), XIEITE_DETAIL_PLTF_LEAST(type, major, 0, 0))
#define XIEITE_PLTF_MOST(type, major, ...) XIEITE_DETAIL_PLTF(__VA_ARGS__, XIEITE_DETAIL_PLTF_MOST(type, major, __VA_ARGS__), XIEITE_DETAIL_PLTF_MOST(type, major, __VA_ARGS__, 0), XIEITE_DETAIL_PLTF_MOST(type, major, 0, 0))
#define XIEITE_DETAIL_PLTF(_0, _1, _2, x, ...) x
#define XIEITE_DETAIL_PLTF_EQ(type, major, minor, patch) (XIEITE_PLTF_TYPE_##type && (XIEITE_PLTF_MAJOR_##type == (major)) && (XIEITE_PLTF_MINOR_##type == (minor)) && (XIEITE_PLTF_PATCH_##type == (patch)))
#define XIEITE_DETAIL_PLTF_LEAST(type, major, minor, patch) (XIEITE_PLTF_TYPE_##type && ((XIEITE_PLTF_MAJOR_##type > (major)) || (XIEITE_PLTF_MAJOR_##type == (major)) && ((XIEITE_PLTF_MINOR_##type > (minor)) || (XIEITE_PLTF_MINOR_##type == (minor)) && (XIEITE_PLTF_PATCH_##type >= (patch)))))
#define XIEITE_DETAIL_PLTF_MOST(type, major, minor, patch) (XIEITE_PLTF_TYPE_##type && ((XIEITE_PLTF_MAJOR_##type < (major)) || (XIEITE_PLTF_MAJOR_##type == (major)) && ((XIEITE_PLTF_MINOR_##type < (minor)) || (XIEITE_PLTF_MINOR_##type == (minor)) && (XIEITE_PLTF_PATCH_##type <= (patch)))))

#ifdef aegis
#	undef XIEITE_PLTF_TYPE_AEGIS
#	define XIEITE_PLTF_TYPE_AEGIS 1
#endif

#if defined(_AIX) || defined(__TOS_AIX__)
#	undef XIEITE_PLTF_TYPE_AIX
#	define XIEITE_PLTF_TYPE_AIX 1

#	ifdef _AIX3
#		undef XIEITE_PLTF_MAJOR_AIX
#		define XIEITE_PLTF_MAJOR_AIX 3
#	endif

#	ifdef _AIX32
#		undef XIEITE_PLTF_MAJOR_AIX
#		define XIEITE_PLTF_MAJOR_AIX 3

#		undef XIEITE_PLTF_MINOR_AIX
#		define XIEITE_PLTF_MINOR_AIX 2
#	endif

#	ifdef _AIX41
#		undef XIEITE_PLTF_MAJOR_AIX
#		define XIEITE_PLTF_MAJOR_AIX 4

#		undef XIEITE_PLTF_MINOR_AIX
#		define XIEITE_PLTF_MINOR_AIX 1
#	endif

#	ifdef _AIX43
#		undef XIEITE_PLTF_MAJOR_AIX
#		define XIEITE_PLTF_MAJOR_AIX 4

#		undef XIEITE_PLTF_MINOR_AIX
#		define XIEITE_PLTF_MINOR_AIX 3
#	endif
#endif

#ifdef __ros__
#	undef XIEITE_PLTF_TYPE_AKAROS
#	define XIEITE_PLTF_TYPE_AKAROS 1
#endif

#if defined(AMIGA) || defined(__amigaos__)
#	undef XIEITE_PLTF_TYPE_AMIGAOS
#	define XIEITE_PLTF_TYPE_AMIGAOS 1
#endif

#ifdef __ANDROID__
#	include <android/api-level.h>

#	undef XIEITE_PLTF_TYPE_ANDROID
#	define XIEITE_PLTF_TYPE_ANDROID 1

#	undef XIEITE_PLTF_MAJOR_ANDROID
#	define XIEITE_PLTF_MAJOR_ANDROID __ANDROID_API__
#endif

#ifdef __asmjs__
#	undef XIEITE_PLTF_TYPE_ASMJS
#	define XIEITE_PLTF_TYPE_ASMJS 1
#endif

#ifdef __BEOS__
#	undef XIEITE_PLTF_TYPE_BEOS
#	define XIEITE_PLTF_TYPE_BEOS 1
#endif

#if defined(__THW_BLUEGENE__) || defined(__bg__)
#	undef XIEITE_PLTF_TYPE_BLUE_GENE
#	define XIEITE_PLTF_TYPE_BLUE_GENE 1
#endif

#if defined(BSD) || defined(_SYSTYPE_BSD) || defined(__DragonFly__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__) || defined(__bsdi__)
#	include <sys/param.h>

#	undef XIEITE_PLTF_TYPE_BSD
#	define XIEITE_PLTF_TYPE_BSD 1

#	undef XIEITE_PLTF_MAJOR_BSD
#	define XIEITE_PLTF_MAJOR_BSD (BSD / 100)

#	undef XIEITE_PLTF_MINOR_BSD
#	define XIEITE_PLTF_MINOR_BSD (BSD % 100)
#endif

#ifdef __bsdi__
#	undef XIEITE_PLTF_TYPE_BSD_BSDI
#	define XIEITE_PLTF_TYPE_BSD_BSDI 1
#endif

#ifdef __DragonFly__
#	undef XIEITE_PLTF_TYPE_DRAGONFLY
#	define XIEITE_PLTF_TYPE_DRAGONFLY 1
#endif

#if defined(__FreeBSD__) || defined(__FreeBSD_kernel__)
#	include <sys/param.h>

#	undef XIEITE_PLTF_TYPE_BSD_FREE
#	define XIEITE_PLTF_TYPE_BSD_FREE 1

#	undef XIEITE_PLTF_MAJOR_BSD_FREE
#	define XIEITE_PLTF_MAJOR_BSD_FREE (__FreeBSD_version / 100000)

#	undef XIEITE_PLTF_MINOR_BSD_FREE
#	define XIEITE_PLTF_MINOR_BSD_FREE (__FreeBSD_version / 10000 % 10)

#	undef XIEITE_PLTF_PATCH_BSD_FREE
#	define XIEITE_PLTF_PATCH_BSD_FREE (__FreeBSD_version % 10000)
#endif

#ifdef __NetBSD__
#	include <sys/param.h>

#	undef XIEITE_PLTF_TYPE_BSD_NET
#	define XIEITE_PLTF_TYPE_BSD_NET 1

#	ifdef __NetBSD_Version
#		undef XIEITE_PLTF_MAJOR_BSD_NET
#		define XIEITE_PLTF_MAJOR_BSD_NET (__NetBSD_Version / 100000000)

#		undef XIEITE_PLTF_MINOR_BSD_NET
#		define XIEITE_PLTF_MINOR_BSD_NET (__NetBSD_Version / 1000000 % 100)

#		undef XIEITE_PLTF_PATCH_BSD_NET
#		define XIEITE_PLTF_PATCH_BSD_NET (__NetBSD_Version / 100 % 100)
#	elifdef __NetBSD_version
#		undef XIEITE_PLTF_MAJOR_BSD_NET
#		define XIEITE_PLTF_MAJOR_BSD_NET (__NetBSD_version / 100000000)

#		undef XIEITE_PLTF_MINOR_BSD_NET
#		define XIEITE_PLTF_MINOR_BSD_NET (__NetBSD_version / 1000000 % 100)

#		undef XIEITE_PLTF_PATCH_BSD_NET
#		define XIEITE_PLTF_PATCH_BSD_NET (__NetBSD_version / 100 % 100)
#	elifdef NetBSD1_0
#		undef XIEITE_PLTF_MAJOR_BSD_NET
#		define XIEITE_PLTF_MAJOR_BSD_NET 1
#	elifdef NetBSD0_9
#		undef XIEITE_PLTF_MINOR_BSD_NET
#		define XIEITE_PLTF_MINOR_BSD_NET 9
#	elifdef NetBSD0_8
#		undef XIEITE_PLTF_MINOR_BSD_NET
#		define XIEITE_PLTF_MINOR_BSD_NET 8
#	endif
#endif

#ifdef __OpenBSD__
#	undef XIEITE_PLTF_TYPE_BSD_OPEN
#	define XIEITE_PLTF_TYPE_BSD_OPEN 1

#	ifdef OpenBSD2_0
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2
#	elifdef OpenBSD2_1
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 1
#	elifdef OpenBSD2_2
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 2
#	elifdef OpenBSD2_3
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 3
#	elifdef OpenBSD2_4
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 4
#	elifdef OpenBSD2_5
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 5
#	elifdef OpenBSD2_6
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 6
#	elifdef OpenBSD2_7
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 7
#	elifdef OpenBSD2_8
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 8
#	elifdef OpenBSD2_9
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 2

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 9
#	elifdef OpenBSD3_0
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3
#	elifdef OpenBSD3_1
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 1
#	elifdef OpenBSD3_2
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 2
#	elifdef OpenBSD3_3
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 3
#	elifdef OpenBSD3_4
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 4
#	elifdef OpenBSD3_5
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 5
#	elifdef OpenBSD3_6
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 6
#	elifdef OpenBSD3_7
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 7
#	elifdef OpenBSD3_8
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 8
#	elifdef OpenBSD3_9
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 3

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 9
#	elifdef OpenBSD4_0
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4
#	elifdef OpenBSD4_1
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 1
#	elifdef OpenBSD4_2
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 2
#	elifdef OpenBSD4_3
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 3
#	elifdef OpenBSD4_4
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 4
#	elifdef OpenBSD4_5
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 5
#	elifdef OpenBSD4_6
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 6
#	elifdef OpenBSD4_7
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 7
#	elifdef OpenBSD4_8
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 8
#	elifdef OpenBSD4_9
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 4

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 9
#	elifdef OpenBSD5_0
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5
#	elifdef OpenBSD5_1
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 1
#	elifdef OpenBSD5_2
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 2
#	elifdef OpenBSD5_3
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 3
#	elifdef OpenBSD5_4
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 4
#	elifdef OpenBSD5_5
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 5
#	elifdef OpenBSD5_6
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 6
#	elifdef OpenBSD5_7
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 7
#	elifdef OpenBSD5_8
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 8
#	elifdef OpenBSD5_9
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 5

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 9
#	elifdef OpenBSD6_0
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6
#	elifdef OpenBSD6_1
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 1
#	elifdef OpenBSD6_2
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 2
#	elifdef OpenBSD6_3
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 3
#	elifdef OpenBSD6_4
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 4
#	elifdef OpenBSD6_5
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 5
#	elifdef OpenBSD6_6
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 6
#	elifdef OpenBSD6_7
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 7
#	elifdef OpenBSD6_8
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 8
#	elifdef OpenBSD6_9
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 6

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 9
#	elifdef OpenBSD7_0
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 7
#	elifdef OpenBSD7_1
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 1
#	elifdef OpenBSD7_2
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 2
#	elifdef OpenBSD7_3
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 3
#	elifdef OpenBSD7_4
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 4
#	elifdef OpenBSD7_5
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 5
#	elifdef OpenBSD7_6
#		undef XIEITE_PLTF_MAJOR_BSD_OPEN
#		define XIEITE_PLTF_MAJOR_BSD_OPEN 7

#		undef XIEITE_PLTF_MINOR_BSD_OPEN
#		define XIEITE_PLTF_MINOR_BSD_OPEN 6
#	endif // TODO: Add recent versions (seems to update frequently)
#endif

#ifdef __CloudABI__
#	undef XIEITE_PLTF_TYPE_CLOUDABI
#	define XIEITE_PLTF_TYPE_CLOUDABI 1
#endif

#ifdef __convex__
#	undef XIEITE_PLTF_TYPE_CONVEXOS
#	define XIEITE_PLTF_TYPE_CONVEXOS 1
#endif

#ifdef __CYGWIN__
#	undef XIEITE_PLTF_TYPE_CYGWIN
#	define XIEITE_PLTF_TYPE_CYGWIN 1

#	undef XIEITE_PLTF_MAJOR_CYGWIN
#	define XIEITE_PLTF_MAJOR_CYGWIN CYGWIN_VERSION_API_MAJOR

#	undef XIEITE_PLTF_MINOR_CYGWIN
#	define XIEITE_PLTF_MINOR_CYGWIN CYGWIN_VERSION_API_MINOR
#endif

#ifdef pyr
#	undef XIEITE_PLTF_TYPE_DC_OSX
#	define XIEITE_PLTF_TYPE_DC_OSX 1
#endif

#if defined(DGUX) || defined(__DGUX__) || defined(__dgux__)
#	undef XIEITE_PLTF_TYPE_DG_UX
#	define XIEITE_PLTF_TYPE_DG_UX 1
#endif

#ifdef apollo
#	undef XIEITE_PLTF_TYPE_DOMAIN_OS
#	define XIEITE_PLTF_TYPE_DOMAIN_OS 1
#endif

#ifdef __DragonFly__
#	undef XIEITE_PLTF_TYPE_DRAGONFLY
#	define XIEITE_PLTF_TYPE_DRAGONFLY 1
#endif

#if defined(_SEQUENT_) || defined(sequent)
#	undef XIEITE_PLTF_TYPE_DYNIX
#	define XIEITE_PLTF_TYPE_DYNIX 1
#endif

#ifdef __ECOS
#	undef XIEITE_PLTF_TYPE_ECOS
#	define XIEITE_PLTF_TYPE_ECOS 1
#endif

#ifdef __EMX__
#	undef XIEITE_PLTF_TYPE_EMX
#	define XIEITE_PLTF_TYPE_EMX 1
#endif

#ifdef __Fuchsia__
#	undef XIEITE_PLTF_TYPE_FUCHSIA
#	define XIEITE_PLTF_TYPE_FUCHSIA 1
#endif

#if defined(__GNU__) || defined(__gnu_hurd__)
#	undef XIEITE_PLTF_TYPE_GNU_HURD
#	define XIEITE_PLTF_TYPE_GNU_HURD 1
#endif

#if defined(__FreeBSD_kernel__) && defined(__GLIBC__)
#	undef XIEITE_PLTF_TYPE_GNU_KFREEBSD
#	define XIEITE_PLTF_TYPE_GNU_KFREEBSD 1
#endif

#ifdef __gnu_linux__
#	undef XIEITE_PLTF_TYPE_GNU_LINUX
#	define XIEITE_PLTF_TYPE_GNU_LINUX 1
#endif

#ifdef __HAIKU__
#	undef XIEITE_PLTF_TYPE_HAIKU
#	define XIEITE_PLTF_TYPE_HAIKU 1
#endif

#ifdef __hiuxmpp
#	undef XIEITE_PLTF_TYPE_HI_UX_MPP
#	define XIEITE_PLTF_TYPE_HI_UX_MPP 1
#endif

#if defined(__hpux) || defined(__hpux__) || defined(_hpux) || defined(hpux)
#	undef XIEITE_PLTF_TYPE_HP_UX
#	define XIEITE_PLTF_TYPE_HP_UX 1
#endif

#ifdef __INTEGRITY
#	undef XIEITE_PLTF_TYPE_INTEGRITY
#	define XIEITE_PLTF_TYPE_INTEGRITY 1
#endif

#if defined(TARGET_IPHONE_SIMULATOR) || defined(TARGET_OS_SIMULATOR)
#	undef XIEITE_PLTF_TYPE_IOS_SIMULATOR
#	define XIEITE_PLTF_TYPE_IOS_SIMULATOR 1
#endif

#ifdef __INTERIX
#	undef XIEITE_PLTF_TYPE_INTERIX
#	define XIEITE_PLTF_TYPE_INTERIX 1
#endif

#if defined(__sgi) || defined(sgi)
#	undef XIEITE_PLTF_TYPE_IRIX
#	define XIEITE_PLTF_TYPE_IRIX 1
#endif

#ifdef __KOS__
#	undef XIEITE_PLTF_TYPE_KALLISTI
#	define XIEITE_PLTF_TYPE_KALLISTI 1
#endif

#if defined(__gnu_linux__) || defined(__linux) || defined(__linux__) || defined(linux)
#	undef XIEITE_PLTF_TYPE_LINUX
#	define XIEITE_PLTF_TYPE_LINUX 1
#endif

#ifdef __Lynx__
#	undef XIEITE_PLTF_TYPE_LYNXOS
#	define XIEITE_PLTF_TYPE_LYNXOS 1
#endif

#if defined(Macintosh) || defined(__APPLE__) || defined(__MACH__) || defined(macintosh)
#	undef XIEITE_PLTF_TYPE_MACINTOSH
#	define XIEITE_PLTF_TYPE_MACINTOSH 1

#	undef XIEITE_PLTF_MAJOR_MACINTOSH
#	if defined(__APPLE__) && defined(__MACH__)
#		define XIEITE_PLTF_MAJOR_MACINTOSH 10
#	else
#		define XIEITE_PLTF_MAJOR_MACINTOSH 9
#	endif
#endif

#ifdef MACOSX_DYLD
#	undef XIEITE_PLTF_TYPE_MACINTOSH_DYLD
#	define XIEITE_PLTF_TYPE_MACINTOSH_DYLD 1
#endif

#ifdef __MINGW32__
#	undef XIEITE_PLTF_TYPE_MINGW32
#	define XIEITE_PLTF_TYPE_MINGW32 1

#	undef XIEITE_PLTF_MAJOR_MINGW32
#	define XIEITE_PLTF_MAJOR_MINGW32 __MING32_VERSION_MAJOR

#	undef XIEITE_PLTF_MINOR_MINGW32
#	define XIEITE_PLTF_MINOR_MINGW32 __MING32_VERSION_MINOR
#endif

#ifdef __MINGW64__
#	undef XIEITE_PLTF_TYPE_MINGW64
#	define XIEITE_PLTF_TYPE_MINGW64 1

#	undef XIEITE_PLTF_MAJOR_MINGW64
#	define XIEITE_PLTF_MAJOR_MINGW64 __MING64_VERSION_MAJOR

#	undef XIEITE_PLTF_MINOR_MINGW64
#	define XIEITE_PLTF_MINOR_MINGW64 __MING64_VERSION_MINOR
#endif

#if defined(_MINIX) || defined(__minix) || defined(__minix__)
#	undef XIEITE_PLTF_TYPE_MINIX
#	define XIEITE_PLTF_TYPE_MINIX 1
#endif

#ifdef __MORPHOS__
#	undef XIEITE_PLTF_TYPE_MORPHOS
#	define XIEITE_PLTF_TYPE_MORPHOS 1
#endif

#if defined(mpeix) || defined(__mpexl)
#	undef XIEITE_PLTF_TYPE_MPE_IX
#	define XIEITE_PLTF_TYPE_MPE_IX 1
#endif

#if defined(MSDOS) || defined(_MSDOS) || defined(__DOS__) || defined(__MSDOS) || defined(__MSDOS__)
#	undef XIEITE_PLTF_TYPE_MS_DOS
#	define XIEITE_PLTF_TYPE_MS_DOS 1
#endif

#ifdef __native_client__
#	undef XIEITE_PLTF_TYPE_NACL
#	define XIEITE_PLTF_TYPE_NACL 1
#endif

#ifdef NeXT
#	undef XIEITE_PLTF_TYPE_NEXT
#	define XIEITE_PLTF_TYPE_NEXT 1
#endif

#ifdef __TANDEM
#	undef XIEITE_PLTF_TYPE_NONSTOP
#	define XIEITE_PLTF_TYPE_NONSTOP 1
#endif

#ifdef __nucleus__
#	undef XIEITE_PLTF_TYPE_NUCLEUS_RTOS
#	define XIEITE_PLTF_TYPE_NUCLEUS_RTOS 1
#endif

#ifdef __OpenBSD__
#	undef XIEITE_PLTF_TYPE_OPENBSD
#	define XIEITE_PLTF_TYPE_OPENBSD 1
#endif

#if defined(M_I386) || defined(M_XENIX) || defined(_SCO_DS)
#	undef XIEITE_PLTF_TYPE_OPENSERVER
#	define XIEITE_PLTF_TYPE_OPENSERVER 1
#endif

#if defined(OS2) || defined(_OS2) || defined(__OS2__) || defined(__TOS_OS2__)
#	undef XIEITE_PLTF_TYPE_OS_2
#	define XIEITE_PLTF_TYPE_OS_2 1
#endif

#ifdef __OS400__
#	undef XIEITE_PLTF_TYPE_OS_400
#	define XIEITE_PLTF_TYPE_OS_400 1
#endif

#if defined(_OSK) || defined(__OS9000)
#	undef XIEITE_PLTF_TYPE_OS_9
#	define XIEITE_PLTF_TYPE_OS_9 1
#endif

#ifdef __palmos__
#	undef XIEITE_PLTF_TYPE_PALM_OS
#	define XIEITE_PLTF_TYPE_PALM_OS 1
#endif

#ifdef __PDOS386__
#	undef XIEITE_PLTF_TYPE_PDOS
#	define XIEITE_PLTF_TYPE_PDOS 1
#endif

#if defined(__phoenix) || defined(__phoenix__) || defined(phoenix)
#	undef XIEITE_PLTF_TYPE_PHOENIX
#	define XIEITE_PLTF_TYPE_PHOENIX 1
#endif

#ifdef EPLAN9
#	undef XIEITE_PLTF_TYPE_PLAN_9
#	define XIEITE_PLTF_TYPE_PLAN_9 1
#endif

#ifdef __pnacl__
#	undef XIEITE_PLTF_TYPE_PNACL
#	define XIEITE_PLTF_TYPE_PNACL 1
#endif

#if defined(__QNXNTO__) || defined(__QNX__)
#	include <sys/neutrino.h>

#	undef XIEITE_PLTF_TYPE_QNX
#	define XIEITE_PLTF_TYPE_QNX 1

#	ifdef __QNXNTO__
#		undef XIEITE_PLTF_MAJOR_QNX
#		define XIEITE_PLTF_MAJOR_QNX (_NTO_VERSION / 100)

#		undef XIEITE_PLTF_MINOR_QNX
#		define XIEITE_PLTF_MINOR_QNX (_NTO_VERSION / 10 % 10)

#		undef XIEITE_PLTF_PATCH_QNX
#		define XIEITE_PLTF_PATCH_QNX (_NTO_VERSION % 10)
#	elifdef __QNX__
#		undef XIEITE_PLTF_MAJOR_QNX
#		define XIEITE_PLTF_MAJOR_QNX 4
#	endif
#endif

#ifdef sinux
#	undef XIEITE_PLTF_TYPE_SINIX
#	define XIEITE_PLTF_TYPE_SINIX 1
#endif

#if defined(__sun) || defined(sun)
#	undef XIEITE_PLTF_TYPE_SOLARIS
#	define XIEITE_PLTF_TYPE_SOLARIS 1
#endif

#ifdef __SYGWIN__
#	undef XIEITE_PLTF_TYPE_SYGWIN
#	define XIEITE_PLTF_TYPE_SYGWIN 1
#endif

#ifdef __SYLLABLE__
#	undef XIEITE_PLTF_TYPE_SYLLABLE
#	define XIEITE_PLTF_TYPE_SYLLABLE 1
#endif

#ifdef __SYMBIAN32__
#	undef XIEITE_PLTF_TYPE_SYMBIAN
#	define XIEITE_PLTF_TYPE_SYMBIAN 1
#endif

#if defined(_SYSTYPE_SVR4) || defined(__SVR4) || defined(__svr4__) || defined(__sysv__)
#	undef XIEITE_PLTF_TYPE_SYSTEM_V
#	define XIEITE_PLTF_TYPE_SYSTEM_V 1
#endif

#if defined(__OSF__) || defined(__osf) || defined(__osf__)
#	undef XIEITE_PLTF_TYPE_TRU64
#	define XIEITE_PLTF_TYPE_TRU64 1
#endif

#ifdef __uClinux__
#	undef XIEITE_PLTF_TYPE_UCLINUX
#	define XIEITE_PLTF_TYPE_UCLINUX 1
#endif

#if defined(__ultrix) || defined(__ultrix__) || defined(ultrix) || (defined(unix) && defined(vax))
#	undef XIEITE_PLTF_TYPE_ULTRIX
#	define XIEITE_PLTF_TYPE_ULTRIX 1
#endif

#ifdef _UNICOS
#	undef XIEITE_PLTF_TYPE_UNICOS
#	define XIEITE_PLTF_TYPE_UNICOS 1

#	undef XIEITE_PLTF_MAJOR_UNICOS
#	define XIEITE_PLTF_MAJOR_UNICOS _UNICOS
#endif

#if defined(_CRAY) || defined(_UNICOSMP) || defined(__crayx1)
#	undef XIEITE_PLTF_TYPE_UNICOS_MP
#	define XIEITE_PLTF_TYPE_UNICOS_MP 1
#endif

#if defined(_POSIX_SOURCE) || defined(_XOPEN_SOURCE) || defined(__unix) || defined(__unix__) || defined(unix)
#	undef XIEITE_PLTF_TYPE_UNIX
#	define XIEITE_PLTF_TYPE_UNIX 1
#endif

#if defined(_UNIXWARE7) || defined(sco)
#	undef XIEITE_PLTF_TYPE_UNIXWARE
#	define XIEITE_PLTF_TYPE_UNIXWARE 1
#endif

#ifdef UTS
#	undef XIEITE_PLTF_TYPE_UTS
#	define XIEITE_PLTF_TYPE_UTS 1
#endif

#ifdef _UWIN
#	undef XIEITE_PLTF_TYPE_UWIN
#	define XIEITE_PLTF_TYPE_UWIN 1
#endif

#if defined(VMS) || defined(__VMS) || defined(__VMS__) || defined(__vms) || defined(__vms__)
#	undef XIEITE_PLTF_TYPE_VMS
#	define XIEITE_PLTF_TYPE_VMS 1

#	undef XIEITE_PLTF_MAJOR_VMS
#	define XIEITE_PLTF_MAJOR_VMS (__VMS_VER / 10000000)

#	undef XIEITE_PLTF_MINOR_VMS
#	define XIEITE_PLTF_MINOR_VMS (__VMS_VER / 100000 % 100)

#	undef XIEITE_PLTF_PATCH_VMS
#	define XIEITE_PLTF_PATCH_VMS (__VMS_VER / 100 % 100)
#endif

#ifdef __VOS__
#	undef XIEITE_PLTF_TYPE_VOS
#	define XIEITE_PLTF_TYPE_VOS 1

#	undef XIEITE_PALTFORM_VERSION_MAJOR_VOS
#	define XIEITE_PLTF_MAJOR_VOS __VOS__
#endif

#if defined(__VXWORKS__) || defined(__vxworks)
#	include <version.h>

#	undef XIEITE_PLTF_TYPE_VXWORKS
#	define XIEITE_PLTF_TYPE_VXWORKS 1

#	undef XIEITE_PLTF_MAJOR_VXWORKS
#	define XIEITE_PLTF_MAJOR_VXWORKS _WRS_VXWORKS_MAJOR

#	undef XIEITE_PLTF_MINOR_VXWORKS
#	define XIEITE_PLTF_MINOR_VXWORKS _WRS_VXWORKS_MINOR

#	undef XIEITE_PLTF_PATCH_VXWORKS
#	define XIEITE_PLTF_PATCH_VXWORKS _WRS_VXWORKS_MAINT
#endif

#if defined(WIN16) || defined(WIN32) || defined(WIN64) || defined(_WIN16) || defined(_WIN32) || defined(_WIN64) || defined(__TOS_WIN__) || defined(__WIN16) || defined(__WIN16__) || defined(__WIN32) || defined(__WIN32__) || defined(__WIN64) || defined(__WIN64__) || defined(__WINDOWS__)
#	undef XIEITE_PLTF_TYPE_WINDOWS
#	define XIEITE_PLTF_TYPE_WINDOWS 1
#endif

#ifdef _WIN32_WCE
#	undef XIEITE_PLTF_TYPE_WINDOWS_CE
#	define XIEITE_PLTF_TYPE_WINDOWS_CE 1

#	undef XIEITE_PLTF_MAJOR_WINDOWS_CE
#	define XIEITE_PLTF_MAJOR_WINDOWS_CE (_WIN32_WCE / 100)

#	undef XIEITE_PLTF_MINOR_WINDOWS_CE
#	define XIEITE_PLTF_MINOR_WINDOWS_CE (_WIN32_WCE % 100)
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_DESKTOP_APP) && (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)
#	undef XIEITE_PLTF_TYPE_WINDOWS_DESKTOP
#	define XIEITE_PLTF_TYPE_WINDOWS_DESKTOP 1
#endif

#if defined(__WINNT__) || defined(__NT__)
#	undef XIEITE_PLTF_TYPE_WINDOWS_NT
#	define XIEITE_PLTF_TYPE_WINDOWS_NT 1
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_PHONE_APP) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)
#	undef XIEITE_PLTF_TYPE_WINDOWS_PHONE
#	define XIEITE_PLTF_TYPE_WINDOWS_PHONE 1
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_SERVER) && (WINAPI_FAMILY == WINAPI_FAMILY_SERVER)
#	undef XIEITE_PLTF_TYPE_WINDOWS_SERVER
#	define XIEITE_PLTF_TYPE_WINDOWS_SERVER 1
#endif

#if defined(WINAPI_FAMILY) && (defined(WINAPI_FAMILY_APP) || defined(WINAPI_FAMILY_PC_APP)) && ((WINAPI_FAMILY == WINAPI_FAMILY_APP) || (WINAPI_FAMILY == WINAPI_FAMILY_PC_APP))
#	undef XIEITE_PLTF_TYPE_WINDOWS_STORE
#	define XIEITE_PLTF_TYPE_WINDOWS_STORE 1
#endif

#if defined(WINAPI_FAMILY) && defined(WINAPI_FAMILY_SYSTEM) && (WINAPI_FAMILY == WINAPI_FAMILY_SYSTEM)
#	undef XIEITE_PLTF_TYPE_WINDOWS_SYSTEM
#	define XIEITE_PLTF_TYPE_WINDOWS_SYSTEM 1
#endif

#ifdef _WINDU_SOURCE
#	undef XIEITE_PLTF_TYPE_WIND_U
#	define XIEITE_PLTF_TYPE_WIND_U 1

#	undef XIEITE_PLTF_MAJOR_WIND_U
#	define XIEITE_PLTF_MAJOR_WIND_U (_WINDU_SOURCE / 0x10000)

#	undef XIEITE_PLTF_MINOR_WIND_U
#	define XIEITE_PLTF_MINOR_WIND_U (_WINDU_SOURCE / 0x100 % 0x100)

#	undef XIEITE_PLTF_PATCH_WIND_U
#	define XIEITE_PLTF_PATCH_WIND_U (_WINDU_SOURCE % 0x100)
#endif

#if defined(__HOS_MVS__) || defined(__MVS__) || defined(__TOS_MVS__)
#	undef XIEITE_PLTF_TYPE_Z
#	define XIEITE_PLTF_TYPE_Z 1
#endif

// https://github.com/cpredef/predef/blob/master/OperatingSystems.md
