#ifndef DETAIL_XIEITE_HEADER_PP_SIGNATURE
#	define DETAIL_XIEITE_HEADER_PP_SIGNATURE
#
#	include "../pp/compiler.hpp"
#
#	if XIEITE_COMPILER_TYPE_GCC || XIEITE_COMPILER_TYPE_CLANG
#		define XIEITE_SIGNATURE __PRETTY_FUNCTION__
#	elif XIEITE_COMPILER_TYPE_MSVC
#		define XIEITE_SIGNATURE __FUNCSIG__
#	else
#		define XIEITE_SIGNATURE __func__
#	endif
#endif
