#ifndef DETAIL_XIEITE_HEADER_PP_UNWRAP
#	define DETAIL_XIEITE_HEADER_PP_UNWRAP
#
#	include "../pp/cat.hpp"
#
#	define XIEITE_UNWRAP(x) XIEITE_CAT(DETAIL_XIEITE_UNWRAP_, DETAIL_XIEITE_UNWRAP x)
#
#	define DETAIL_XIEITE_UNWRAP(...) DETAIL_XIEITE_UNWRAP __VA_ARGS__
#	define DETAIL_XIEITE_UNWRAP_DETAIL_XIEITE_UNWRAP
#endif
