#ifndef DETAIL_XIEITE_HEADER_PP_WORD
#	define DETAIL_XIEITE_HEADER_PP_WORD
#
#	include <stdint.h>
#	include "../pp/arch.hpp"
#
#	if XIEITE_ARCH_TYPE_AARCH64 || XIEITE_ARCH_TYPE_ALPHA || XIEITE_ARCH_TYPE_CONVEX || XIEITE_ARCH_TYPE_EPIPHANY || XIEITE_ARCH_TYPE_IBM_Z || XIEITE_ARCH_TYPE_ITANIUM || XIEITE_ARCH_VER(POWERPC, >=, 620) || XIEITE_ARCH_VER(SPARC, >=, 9) || XIEITE_ARCH_TYPE_X86_64 || (UINTPTR_MAX >= 18446744073709551615ull)
#		define XIEITE_WORD 64
#	elif XIEITE_ARCH_TYPE_ARM || XIEITE_ARCH_TYPE_MIPS || XIEITE_ARCH_TYPE_MOTOROLA_68000 || XIEITE_ARCH_TYPE_PA_RISC || XIEITE_ARCH_TYPE_PYRAMID_9810 || XIEITE_ARCH_TYPE_RS_6000 || XIEITE_ARCH_VER(SPARC, <=, 8) || XIEITE_ARCH_TYPE_SUPERH || XIEITE_ARCH_VER(TMS320, >=, 5400) || XIEITE_ARCH_TYPE_TMS470 || XIEITE_ARCH_TYPE_X86_32 || (UINTPTR_MAX >= 4294967295ull)
#		define XIEITE_WORD 32
#	elif XIEITE_ARCH_TYPE_BLACKFIN || XIEITE_ARCH_VER(TMS320, <=, 2800) || (UINTPTR_MAX >= 65535ull)
#		define XIEITE_WORD 16
#	else
#		define XIEITE_WORD 8
#	endif
#endif
