#ifndef DETAIL_XIEITE_HEADER_PP_WRAPPED
#	define DETAIL_XIEITE_HEADER_PP_WRAPPED
#
#	include "../pp/cat.hpp"
#	include "../pp/eat.hpp"
#
#	define XIEITE_WRAPPED(...) XIEITE_CAT(DETAIL_XIEITE_WRAPPED_, DETAIL_XIEITE_WRAPPED __VA_ARGS__))
#
#	define DETAIL_XIEITE_WRAPPED(...) DETAIL_XIEITE_WRAPPED_1
#	define DETAIL_XIEITE_WRAPPED_DETAIL_XIEITE_WRAPPED 0 XIEITE_EAT(
#	define DETAIL_XIEITE_WRAPPED_DETAIL_XIEITE_WRAPPED_1 1 XIEITE_EAT(
#endif
