#pragma once

#define XIEITE_ARCHITECTURE_TYPE_ALPHA 0
#define XIEITE_ARCHITECTURE_MAJOR_ALPHA 0
#define XIEITE_ARCHITECTURE_MINOR_ALPHA 0
#define XIEITE_ARCHITECTURE_PATCH_ALPHA 0
#define XIEITE_ARCHITECTURE_TYPE_ARM 0
#define XIEITE_ARCHITECTURE_MAJOR_ARM 0
#define XIEITE_ARCHITECTURE_MINOR_ARM 0
#define XIEITE_ARCHITECTURE_PATCH_ARM 0
#define XIEITE_ARCHITECTURE_TYPE_BLACKFIN 0
#define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 0
#define XIEITE_ARCHITECTURE_MINOR_BLACKFIN 0
#define XIEITE_ARCHITECTURE_PATCH_BLACKFIN 0
#define XIEITE_ARCHITECTURE_TYPE_CONVEX 0
#define XIEITE_ARCHITECTURE_MAJOR_CONVEX 0
#define XIEITE_ARCHITECTURE_MINOR_CONVEX 0
#define XIEITE_ARCHITECTURE_PATCH_CONVEX 0
#define XIEITE_ARCHITECTURE_TYPE_CRAY 0
#define XIEITE_ARCHITECTURE_MAJOR_CRAY 0
#define XIEITE_ARCHITECTURE_MINOR_CRAY 0
#define XIEITE_ARCHITECTURE_PATCH_CRAY 0
#define XIEITE_ARCHITECTURE_TYPE_CSKY 0
#define XIEITE_ARCHITECTURE_MAJOR_CSKY 0
#define XIEITE_ARCHITECTURE_MINOR_CSKY 0
#define XIEITE_ARCHITECTURE_PATCH_CSKY 0
#define XIEITE_ARCHITECTURE_TYPE_EPIPHANY 0
#define XIEITE_ARCHITECTURE_MAJOR_EPIPHANY 0
#define XIEITE_ARCHITECTURE_MINOR_EPIPHANY 0
#define XIEITE_ARCHITECTURE_PATCH_EPIPHANY 0
#define XIEITE_ARCHITECTURE_TYPE_ELBRUS_2000 0
#define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 0
#define XIEITE_ARCHITECTURE_MINOR_ELBRUS_2000 0
#define XIEITE_ARCHITECTURE_PATCH_ELBRUS_2000 0
#define XIEITE_ARCHITECTURE_TYPE_FR30 0
#define XIEITE_ARCHITECTURE_MAJOR_FR30 0
#define XIEITE_ARCHITECTURE_MINOR_FR30 0
#define XIEITE_ARCHITECTURE_PATCH_FR30 0
#define XIEITE_ARCHITECTURE_TYPE_HEXAGON 0
#define XIEITE_ARCHITECTURE_MAJOR_HEXAGON 0
#define XIEITE_ARCHITECTURE_MINOR_HEXAGON 0
#define XIEITE_ARCHITECTURE_PATCH_HEXAGON 0
#define XIEITE_ARCHITECTURE_TYPE_HP_800 0
#define XIEITE_ARCHITECTURE_MAJOR_HP_800 0
#define XIEITE_ARCHITECTURE_MINOR_HP_800 0
#define XIEITE_ARCHITECTURE_PATCH_HP_800 0
#define XIEITE_ARCHITECTURE_TYPE_HP_9000 0
#define XIEITE_ARCHITECTURE_MAJOR_HP_9000 0
#define XIEITE_ARCHITECTURE_MINOR_HP_9000 0
#define XIEITE_ARCHITECTURE_PATCH_HP_9000 0
#define XIEITE_ARCHITECTURE_TYPE_IA64 0
#define XIEITE_ARCHITECTURE_MAJOR_IA64 0
#define XIEITE_ARCHITECTURE_MINOR_IA64 0
#define XIEITE_ARCHITECTURE_PATCH_IA64 0
#define XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_32 0
#define XIEITE_ARCHITECTURE_MAJOR_IBM_SYSTEM_32 0
#define XIEITE_ARCHITECTURE_MINOR_IBM_SYSTEM_32 0
#define XIEITE_ARCHITECTURE_PATCH_IBM_SYSTEM_32 0
#define XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_370 0
#define XIEITE_ARCHITECTURE_MAJOR_IBM_SYSTEM_370 0
#define XIEITE_ARCHITECTURE_MINOR_IBM_SYSTEM_370 0
#define XIEITE_ARCHITECTURE_PATCH_IBM_SYSTEM_370 0
#define XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_390 0
#define XIEITE_ARCHITECTURE_MAJOR_IBM_SYSTEM_390 0
#define XIEITE_ARCHITECTURE_MINOR_IBM_SYSTEM_390 0
#define XIEITE_ARCHITECTURE_PATCH_IBM_SYSTEM_390 0
#define XIEITE_ARCHITECTURE_TYPE_IBM_Z 0
#define XIEITE_ARCHITECTURE_MAJOR_IBM_Z 0
#define XIEITE_ARCHITECTURE_MINOR_IBM_Z 0
#define XIEITE_ARCHITECTURE_PATCH_IBM_Z 0
#define XIEITE_ARCHITECTURE_TYPE_LOONGARCH 0
#define XIEITE_ARCHITECTURE_MAJOR_LOONGARCH 0
#define XIEITE_ARCHITECTURE_MINOR_LOONGARCH 0
#define XIEITE_ARCHITECTURE_PATCH_LOONGARCH 0
#define XIEITE_ARCHITECTURE_TYPE_M_CORE 0
#define XIEITE_ARCHITECTURE_MAJOR_M_CORE 0
#define XIEITE_ARCHITECTURE_MINOR_M_CORE 0
#define XIEITE_ARCHITECTURE_PATCH_M_CORE 0
#define XIEITE_ARCHITECTURE_TYPE_M32R 0
#define XIEITE_ARCHITECTURE_MAJOR_M32R 0
#define XIEITE_ARCHITECTURE_MINOR_M32R 0
#define XIEITE_ARCHITECTURE_PATCH_M32R 0
#define XIEITE_ARCHITECTURE_TYPE_MIPS 0
#define XIEITE_ARCHITECTURE_MAJOR_MIPS 0
#define XIEITE_ARCHITECTURE_MINOR_MIPS 0
#define XIEITE_ARCHITECTURE_PATCH_MIPS 0
#define XIEITE_ARCHITECTURE_TYPE_MMIX 0
#define XIEITE_ARCHITECTURE_MAJOR_MMIX 0
#define XIEITE_ARCHITECTURE_MINOR_MMIX 0
#define XIEITE_ARCHITECTURE_PATCH_MMIX 0
#define XIEITE_ARCHITECTURE_TYPE_MN103 0
#define XIEITE_ARCHITECTURE_MAJOR_MN103 0
#define XIEITE_ARCHITECTURE_MINOR_MN103 0
#define XIEITE_ARCHITECTURE_PATCH_MN103 0
#define XIEITE_ARCHITECTURE_TYPE_MOTOROLA_68000 0
#define XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000 0
#define XIEITE_ARCHITECTURE_MINOR_MOTOROLA_68000 0
#define XIEITE_ARCHITECTURE_PATCH_MOTOROLA_68000 0
#define XIEITE_ARCHITECTURE_TYPE_MOXIE 0
#define XIEITE_ARCHITECTURE_MAJOR_MOXIE 0
#define XIEITE_ARCHITECTURE_MINOR_MOXIE 0
#define XIEITE_ARCHITECTURE_PATCH_MOXIE 0
#define XIEITE_ARCHITECTURE_TYPE_NDS32 0
#define XIEITE_ARCHITECTURE_MAJOR_NDS32 0
#define XIEITE_ARCHITECTURE_MINOR_NDS32 0
#define XIEITE_ARCHITECTURE_PATCH_NDS32 0
#define XIEITE_ARCHITECTURE_TYPE_NEC_SX_AURORA_TSUBASA 0
#define XIEITE_ARCHITECTURE_MAJOR_NEC_SX_AURORA_TSUBASA 0
#define XIEITE_ARCHITECTURE_MINOR_NEC_SX_AURORA_TSUBASA 0
#define XIEITE_ARCHITECTURE_PATCH_NEC_SX_AURORA_TSUBASA 0
#define XIEITE_ARCHITECTURE_TYPE_NIOS_II 0
#define XIEITE_ARCHITECTURE_MAJOR_NIOS_II 0
#define XIEITE_ARCHITECTURE_MINOR_NIOS_II 0
#define XIEITE_ARCHITECTURE_PATCH_NIOS_II 0
#define XIEITE_ARCHITECTURE_TYPE_OR1K 0
#define XIEITE_ARCHITECTURE_MAJOR_OR1K 0
#define XIEITE_ARCHITECTURE_MINOR_OR1K 0
#define XIEITE_ARCHITECTURE_PATCH_OR1K 0
#define XIEITE_ARCHITECTURE_TYPE_PA_RISC 0
#define XIEITE_ARCHITECTURE_MAJOR_PA_RISC 0
#define XIEITE_ARCHITECTURE_MINOR_PA_RISC 0
#define XIEITE_ARCHITECTURE_PATCH_PA_RISC 0
#define XIEITE_ARCHITECTURE_TYPE_PDP_11 0
#define XIEITE_ARCHITECTURE_MAJOR_PDP_11 0
#define XIEITE_ARCHITECTURE_MINOR_PDP_11 0
#define XIEITE_ARCHITECTURE_PATCH_PDP_11 0
#define XIEITE_ARCHITECTURE_TYPE_PNACL 0
#define XIEITE_ARCHITECTURE_MAJOR_PNACL 0
#define XIEITE_ARCHITECTURE_MINOR_PNACL 0
#define XIEITE_ARCHITECTURE_PATCH_PNACL 0
#define XIEITE_ARCHITECTURE_TYPE_POWERPC 0
#define XIEITE_ARCHITECTURE_MAJOR_POWERPC 0
#define XIEITE_ARCHITECTURE_MINOR_POWERPC 0
#define XIEITE_ARCHITECTURE_PATCH_POWERPC 0
#define XIEITE_ARCHITECTURE_TYPE_PTX 0
#define XIEITE_ARCHITECTURE_MAJOR_PTX 0
#define XIEITE_ARCHITECTURE_MINOR_PTX 0
#define XIEITE_ARCHITECTURE_PATCH_PTX 0
#define XIEITE_ARCHITECTURE_TYPE_PYRAMID_9810 0
#define XIEITE_ARCHITECTURE_MAJOR_PYRAMID_9810 0
#define XIEITE_ARCHITECTURE_MINOR_PYRAMID_9810 0
#define XIEITE_ARCHITECTURE_PATCH_PYRAMID_9810 0
#define XIEITE_ARCHITECTURE_TYPE_RISC_V 0
#define XIEITE_ARCHITECTURE_MAJOR_RISC_V 0
#define XIEITE_ARCHITECTURE_MINOR_RISC_V 0
#define XIEITE_ARCHITECTURE_PATCH_RISC_V 0
#define XIEITE_ARCHITECTURE_TYPE_RS_6000 0
#define XIEITE_ARCHITECTURE_MAJOR_RS_6000 0
#define XIEITE_ARCHITECTURE_MINOR_RS_6000 0
#define XIEITE_ARCHITECTURE_PATCH_RS_6000 0
#define XIEITE_ARCHITECTURE_TYPE_SPARC 0
#define XIEITE_ARCHITECTURE_MAJOR_SPARC 0
#define XIEITE_ARCHITECTURE_MINOR_SPARC 0
#define XIEITE_ARCHITECTURE_PATCH_SPARC 0
#define XIEITE_ARCHITECTURE_TYPE_SUPERH 0
#define XIEITE_ARCHITECTURE_MAJOR_SUPERH 0
#define XIEITE_ARCHITECTURE_MINOR_SUPERH 0
#define XIEITE_ARCHITECTURE_PATCH_SUPERH 0
#define XIEITE_ARCHITECTURE_TYPE_TAHOE 0
#define XIEITE_ARCHITECTURE_MAJOR_TAHOE 0
#define XIEITE_ARCHITECTURE_MINOR_TAHOE 0
#define XIEITE_ARCHITECTURE_PATCH_TAHOE 0
#define XIEITE_ARCHITECTURE_TYPE_TMS320 0
#define XIEITE_ARCHITECTURE_MAJOR_TMS320 0
#define XIEITE_ARCHITECTURE_MINOR_TMS320 0
#define XIEITE_ARCHITECTURE_PATCH_TMS320 0
#define XIEITE_ARCHITECTURE_TYPE_TMS470 0
#define XIEITE_ARCHITECTURE_MAJOR_TMS470 0
#define XIEITE_ARCHITECTURE_MINOR_TMS470 0
#define XIEITE_ARCHITECTURE_PATCH_TMS470 0
#define XIEITE_ARCHITECTURE_TYPE_V850 0
#define XIEITE_ARCHITECTURE_MAJOR_V850 0
#define XIEITE_ARCHITECTURE_MINOR_V850 0
#define XIEITE_ARCHITECTURE_PATCH_V850 0
#define XIEITE_ARCHITECTURE_TYPE_VAX 0
#define XIEITE_ARCHITECTURE_MAJOR_VAX 0
#define XIEITE_ARCHITECTURE_MINOR_VAX 0
#define XIEITE_ARCHITECTURE_PATCH_VAX 0
#define XIEITE_ARCHITECTURE_TYPE_X80 0
#define XIEITE_ARCHITECTURE_MAJOR_X80 0
#define XIEITE_ARCHITECTURE_MINOR_X80 0
#define XIEITE_ARCHITECTURE_PATCH_X80 0
#define XIEITE_ARCHITECTURE_TYPE_X86_32 0
#define XIEITE_ARCHITECTURE_MAJOR_X86_32 0
#define XIEITE_ARCHITECTURE_MINOR_X86_32 0
#define XIEITE_ARCHITECTURE_PATCH_X86_32 0
#define XIEITE_ARCHITECTURE_TYPE_X86_64 0
#define XIEITE_ARCHITECTURE_MAJOR_X86_64 0
#define XIEITE_ARCHITECTURE_MINOR_X86_64 0
#define XIEITE_ARCHITECTURE_PATCH_X86_64 0
#define XIEITE_ARCHITECTURE_TYPE_XSTORMY16 0
#define XIEITE_ARCHITECTURE_MAJOR_XSTORMY16 0
#define XIEITE_ARCHITECTURE_MINOR_XSTORMY16 0
#define XIEITE_ARCHITECTURE_PATCH_XSTORMY16 0
#define XIEITE_ARCHITECTURE_TYPE_XTENSA 0
#define XIEITE_ARCHITECTURE_MAJOR_XTENSA 0
#define XIEITE_ARCHITECTURE_MINOR_XTENSA 0
#define XIEITE_ARCHITECTURE_PATCH_XTENSA 0

#define XIEITE_ARCHITECTURE_EQUAL(architecture_, major_, minor_, patch_) (XIEITE_ARCHITECTURE_TYPE_##architecture_ && (XIEITE_ARCHITECTURE_MAJOR_##architecture_ == (major_)) && (XIEITE_ARCHITECTURE_MINOR_##architecture_ == (minor_)) && (XIEITE_ARCHITECTURE_PATCH_##architecture_ == (patch_)))
#define XIEITE_ARCHITECTURE_LEAST(architecture_, major_, minor_, patch_) (XIEITE_ARCHITECTURE_TYPE_##architecture_ && ((XIEITE_ARCHITECTURE_MAJOR_##architecture_ > (major_)) || (XIEITE_ARCHITECTURE_MAJOR_##architecture_ == (major_)) && ((XIEITE_ARCHITECTURE_MINOR_##architecture_ > (minor_)) || (XIEITE_ARCHITECTURE_MINOR_##architecture_ == (minor_)) && (XIEITE_ARCHITECTURE_PATCH_##architecture_ >= (patch_)))))
#define XIEITE_ARCHITECTURE_MOST(architecture_, major_, minor_, patch_) (XIEITE_ARCHITECTURE_TYPE_##architecture_ && ((XIEITE_ARCHITECTURE_MAJOR_##architecture_ < (major_)) || (XIEITE_ARCHITECTURE_MAJOR_##architecture_ == (major_)) && ((XIEITE_ARCHITECTURE_MINOR_##architecture_ < (minor_)) || (XIEITE_ARCHITECTURE_MINOR_##architecture_ == (minor_)) && (XIEITE_ARCHITECTURE_PATCH_##architecture_ <= (patch_)))))

#if defined(_M_ALPHA) || defined(__ALPHA) || defined(__alpha) || defined(__alpha__)
#	undef XIEITE_ARCHITECTURE_TYPE_ALPHA
#	define XIEITE_ARCHITECTURE_TYPE_ALPHA 1

#	ifdef __alpha_ev4__
#		undef XIEITE_ARCHITECTURE_MAJOR_ALPHA
#		define XIEITE_ARCHITECTURE_MAJOR_ALPHA 4
#	endif

#	ifdef __alpha_ev5__
#		undef XIEITE_ARCHITECTURE_MAJOR_ALPHA
#		define XIEITE_ARCHITECTURE_MAJOR_ALPHA 5
#	endif

#	ifdef __alpha_ev6__
#		undef XIEITE_ARCHITECTURE_MAJOR_ALPHA
#		define XIEITE_ARCHITECTURE_MAJOR_ALPHA 6
#	endif

#	ifdef __alpha_ev7__
#		undef XIEITE_ARCHITECTURE_MAJOR_ALPHA
#		define XIEITE_ARCHITECTURE_MAJOR_ALPHA 7
#	endif
#endif

#if defined(_ARM) || defined(_ARMT) || defined(_M_ARM) || defined(_M_ARMT) || defined(_M_ARM_NT) || defined(__AARCH64EB__) || defined(__AARCH64EL__) || defined(__ARM_ARCH) || defined(__ARM_ARCH__) || defined(__CC_ARM) || defined(__TARGET_ARCH_ARM) || defined(__TARGET_ARCH_THUMB) || defined(__arm) || defined(__arm64) || defined(__arm__) || defined(__thumb__)
#	undef XIEITE_ARCHITECTURE_TYPE_ARM
#	define XIEITE_ARCHITECTURE_TYPE_ARM 1

#	if defined(_M_ARM) && (_M_ARM > 0)
#		undef XIEITE_ARCHITECTURE_MAJOR_ARM
#		define XIEITE_ARCHITECTURE_MAJOR_ARM _M_ARM
#	elif defined(__ARM_ARCH) && (__ARM_ARCH > 0)
#		undef XIEITE_ARCHITECTURE_MAJOR_ARM
#		define XIEITE_ARCHITECTURE_MAJOR_ARM __ARM_ARCH
#	elif defined(__TARGET_ARCH_ARM) && (__TARGET_ARCH_ARM > 0)
#		undef XIEITE_ARCHITECTURE_MAJOR_ARM
#		define XIEITE_ARCHITECTURE_MAJOR_ARM __TARGET_ARCH_ARM
#	elif defined(__TARGET_ARCH_THUMB) && (__TARGET_ARCH_THUMB > 0)
#		undef XIEITE_ARCHITECTURE_MAJOR_ARM
#		define XIEITE_ARCHITECTURE_MAJOR_ARM __TARGET_ARCH_THUMB
#	else
#		ifdef __ARM_ARCH_2__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 2
#		endif

#		if defined(__ARM_ARCH_3M__) || defined(__ARM_ARCH_3__)
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 3
#		endif

#		if defined(__ARM_ARCH_4T__) || defined(__TARGET_ARM_4T)
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 4
#		endif

#		if defined(__ARM_ARCH_5E__) || defined(__ARM_ARCH_5TEJ__) || defined(__ARM_ARCH_5TE__) || defined(__ARM_ARCH_5T__) || defined(__ARM_ARCH_5__)
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 5
#		endif

#		if defined(__ARM_ARCH_6J__) || defined(__ARM_ARCH_6K__) || defined(__ARM_ARCH_6M__) || defined(__ARM_ARCH_6T2__) || defined(__ARM_ARCH_6ZK__) || defined(__ARM_ARCH_6Z__) || defined(__ARM_ARCH_6__)
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 6
#		endif

#		if defined(__ARM_ARCH_7A__) || defined(__ARM_ARCH_7EM__) || defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7R__) || defined(__ARM_ARCH_7S__) || defined(__ARM_ARCH_7__)
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 7
#		endif

#		if defined(_M_ARM64) || defined(__AARCH64EB__) || defined(__AARCH64EL__) || defined(__ARM_ARCH_8A__) || defined(__ARM_ARCH_8__) || defined(__ARMv8_A__) || defined(__ARMv8__) || defined(__CORE_CORTEXAV8__) || defined(__aarch64__) || defined(__arch64) || defined(__arm64)
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8
#		endif

#		ifdef __ARM_ARCH_8_1A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 1
#		endif

#		ifdef __ARM_ARCH_8_2A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 2
#		endif

#		ifdef __ARM_ARCH_8_3A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 3
#		endif

#		ifdef __ARM_ARCH_8_4A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 4
#		endif

#		ifdef __ARM_ARCH_8_5A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 5
#		endif

#		ifdef __ARM_ARCH_8_6A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 6
#		endif

#		ifdef __ARM_ARCH_8_7A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 7
#		endif

#		ifdef __ARM_ARCH_8_8A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 8
#		endif

#		ifdef __ARM_ARCH_8_9A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 8

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 9
#		endif

#		ifdef __ARM_ARCH_9A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 9
#		endif

#		ifdef __ARM_ARCH_9_1A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 9

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 1
#		endif

#		ifdef __ARM_ARCH_9_2A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 9

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 2
#		endif

#		ifdef __ARM_ARCH_9_3A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 9

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 3
#		endif

#		ifdef __ARM_ARCH_9_4A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 9

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 4
#		endif

#		ifdef __ARM_ARCH_9_5A__
#			undef XIEITE_ARCHITECTURE_MAJOR_ARM
#			define XIEITE_ARCHITECTURE_MAJOR_ARM 9

#			undef XIEITE_ARCHITECTURE_MINOR_ARM
#			define XIEITE_ARCHITECTURE_MINOR_ARM 5
#		endif
#	endif
#endif

#if defined(BFIN) || defined(__ADSPBLACKFIN__) || defined(__BFIN) || defined(__BFIN__) || defined(__bfin) || defined(__bfin__) || defined(bfin)
#	undef XIEITE_ARCHITECTURE_TYPE_BLACKFIN
#	define XIEITE_ARCHITECTURE_TYPE_BLACKFIN 1

#	ifdef __ADSPBF504__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 504
#	endif

#	ifdef __ADSPBF512__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 512
#	endif

#	ifdef __ADSPBF514__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 514
#	endif

#	ifdef __ADSPBF516__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 516
#	endif

#	ifdef __ADSPBF518__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 518
#	endif

#	if defined(__ADSPBF522__) || defined(__ADSPBF522C__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 522
#	endif

#	if defined(__ADSPBF523__) || defined(__ADSPBF523C__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 523
#	endif

#	if defined(__ADSPBF524__) || defined(__ADSPBF524C__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 524
#	endif

#	if defined(__ADSPBF525__) || defined(__ADSPBF525C__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 525
#	endif

#	if defined(__ADSPBF526__) || defined(__ADSPBF526C__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 526
#	endif

#	if defined(__ADSPBF527__) || defined(__ADSPBF527C__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 527
#	endif

#	ifdef __ADSPBF531__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 531
#	endif

#	ifdef __ADSPBF532__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 532
#	endif

#	ifdef __ADSPBF533__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 533
#	endif

#	ifdef __ADSPBF534__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 534
#	endif

#	ifdef __ADSPBF536__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 536
#	endif

#	ifdef __ADSPBF537__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 537
#	endif

#	if defined(__ADSPBF538__) || defined(__ADSPBF538F__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 538
#	endif

#	if defined(__ADSPBF539__) || defined(__ADSPBF539F__)
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 539
#	endif

#	ifdef __ADSPBF542__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 542
#	endif

#	ifdef __ADSPBF544__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 544
#	endif

#	ifdef __ADSPBF547__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 547
#	endif

#	ifdef __ADSPBF548__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 548
#	endif

#	ifdef __ADSPBF549__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 549
#	endif

#	ifdef __ADSPBF561__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 561
#	endif

#	ifdef __ADSPBF606__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 606
#	endif

#	ifdef __ADSPBF607__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 607
#	endif

#	ifdef __ADSPBF608__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 608
#	endif

#	ifdef __ADSPBF609__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 609
#	endif

#	ifdef __ADSPBF700__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 700
#	endif

#	ifdef __ADSPBF701__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 701
#	endif

#	ifdef __ADSPBF702__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 702
#	endif

#	ifdef __ADSPBF703__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 703
#	endif

#	ifdef __ADSPBF704__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 704
#	endif

#	ifdef __ADSPBF705__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 705
#	endif

#	ifdef __ADSPBF706__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 706
#	endif

#	ifdef __ADSPBF707__
#		undef XIEITE_ARCHITECTURE_MAJOR_BLACKFIN
#		define XIEITE_ARCHITECTURE_MAJOR_BLACKFIN 707
#	endif
#endif

#ifdef __convex__
#	undef XIEITE_ARCHITECTURE_TYPE_CONVEX
#	define XIEITE_ARCHITECTURE_TYPE_CONVEX 1

#	ifdef __convex_c1__
#		undef XIEITE_ARCHITECTURE_MAJOR_CONVEX
#		define XIEITE_ARCHITECTURE_MAJOR_CONVEX 1
#	endif

#	ifdef __convex_c2__
#		undef XIEITE_ARCHITECTURE_MAJOR_CONVEX
#		define XIEITE_ARCHITECTURE_MAJOR_CONVEX 2
#	endif

#	ifdef __convex_c32__
#		undef XIEITE_ARCHITECTURE_MAJOR_CONVEX
#		define XIEITE_ARCHITECTURE_MAJOR_CONVEX 32
#	endif

#	ifdef __convex_c34__
#		undef XIEITE_ARCHITECTURE_MAJOR_CONVEX
#		define XIEITE_ARCHITECTURE_MAJOR_CONVEX 34
#	endif

#	ifdef __convex_c38__
#		undef XIEITE_ARCHITECTURE_MAJOR_CONVEX
#		define XIEITE_ARCHITECTURE_MAJOR_CONVEX 38
#	endif
#endif

#ifdef _CRAY
#	undef XIEITE_ARCHITECTURE_TYPE_CRAY
#	define XIEITE_ARCHITECTURE_TYPE_CRAY 1
#endif

#if defined(__CSKY__) || defined(__csky__)
#	undef XIEITE_ARCHITECTURE_TYPE_CSKY
#	define XIEITE_ARCHITECTURE_TYPE_CSKY 1
#endif

#ifdef __epiphany__
#	undef XIEITE_ARCHITECTURE_TYPE_EPIPHANY
#	define XIEITE_ARCHITECTURE_TYPE_EPIPHANY 1
#endif

#if defined(__e2k__) || defined(__elbrus__)
#	undef XIEITE_ARCHITECTURE_TYPE_ELBRUS_2000
#	define XIEITE_ARCHITECTURE_TYPE_ELBRUS_2000 1

#	if defined(__elbrus__) || (defined(__iset__) && (__iset__ == 1))
#		undef XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000
#		define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 1
#	endif

#	if defined(__elbrus_2cplus__) || defined(__elbrus_s__) || (defined(__iset__) && (__iset__ == 2))
#		undef XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000
#		define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 2
#	endif

#	if defined(__elbrus_4c__) || (defined(__iset__) && (__iset__ == 3))
#		undef XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000
#		define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 3
#	endif

#	if defined(__elbrus_1ck__) || defined(__elbrus_1cplus__) || defined(__elbrus_8c__) || defined(__elbrus_8c1__) || (defined(__iset__) && (__iset__ == 4))
#		undef XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000
#		define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 4
#	endif

#	if defined(__elbrus_8cb__) || (defined(__iset__) && (__iset__ == 5))
#		undef XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000
#		define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 5
#	endif

#	if defined(__elbrus_12c__) || defined(__elbrus_2c3__) || (defined(__iset__) && (__iset__ == 6))
#		undef XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000
#		define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 6
#	endif

#	if defined(__elbrus_32c__) || (defined(__iset__) && (__iset__ == 7))
#		undef XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000
#		define XIEITE_ARCHITECTURE_MAJOR_ELBRUS_2000 7
#	endif
#endif

#if defined(__fr30) || defined(__fr30__) || defined(fr30)
#	undef XIEITE_ARCHITECTURE_TYPE_FR30
#	define XIEITE_ARCHITECTURE_TYPE_FR30 1
#endif

#ifdef __hexagon__
#	undef XIEITE_ARCHITECTURE_TYPE_HEXAGON
#	define XIEITE_ARCHITECTURE_TYPE_HEXAGON 1

#	ifdef __HVX_ARCH__
#		undef XIEITE_ARCHITECTURE_MAJOR_HEXAGON
#		define XIEITE_ARCHITECTURE_MAJOR_HEXAGON __HVX_ARCH__
#	endif
#endif

#if defined(__hp800) || defined(__hp800__) || defined(hp800)
#	undef XIEITE_ARCHITECTURE_TYPE_HP_800
#	define XIEITE_ARCHITECTURE_TYPE_HP_800 1
#endif

#ifdef __hp9000
#	undef XIEITE_ARCHITECTURE_TYPE_HP_9000
#	define XIEITE_ARCHITECTURE_TYPE_HP_9000 1

#	if defined(__hp9000s200) || defined(__hp9000s200__) || defined(hp9000s200)
#		undef XIEITE_ARCHITECTURE_MAJOR_HP_9000
#		define XIEITE_ARCHITECTURE_MAJOR_HP_9000 200
#	endif

#	if defined(__hp9000s300) || defined(__hp9000s300__) || defined(hp9000s300)
#		undef XIEITE_ARCHITECTURE_MAJOR_HP_9000
#		define XIEITE_ARCHITECTURE_MAJOR_HP_9000 300
#	endif

#	if defined(__hp9000s400) || defined(__hp9000s400__) || defined(hp9000s400)
#		undef XIEITE_ARCHITECTURE_MAJOR_HP_9000
#		define XIEITE_ARCHITECTURE_MAJOR_HP_9000 400
#	endif

#	if defined(__hp9000s500) || defined(__hp9000s400__) || defined(hp9000s500)
#		undef XIEITE_ARCHITECTURE_MAJOR_HP_9000
#		define XIEITE_ARCHITECTURE_MAJOR_HP_9000 500
#	endif

#	if defined(__hp9000s700) || defined(__hp9000s700__) || defined(hp9000s700)
#		undef XIEITE_ARCHITECTURE_MAJOR_HP_9000
#		define XIEITE_ARCHITECTURE_MAJOR_HP_9000 700
#	endif

#	if defined(__hp9000s800) || defined(__hp9000s800__) || defined(__hp9k8) || defined(__hp9k8__) || defined(hp9000s800) || defined(hp9k8)
#		undef XIEITE_ARCHITECTURE_MAJOR_HP_9000
#		define XIEITE_ARCHITECTURE_MAJOR_HP_9000 800
#	endif
#endif

#if defined(_IA64) || defined(_M_IA64) || defined(__IA64__) || defined(__ia64) || defined(__ia64__) || defined(__itanium__) || defined(ia64)
#	undef XIEITE_ARCHITECTURE_TYPE_IA64
#	define XIEITE_ARCHITECTURE_TYPE_IA64 1

#	undef XIEITE_ARCHITECTURE_MAJOR_IA64
#	define XIEITE_ARCHITECTURE_MAJOR_IA64 (_M_IA64 % 64000 / 100)

#	undef XIEITE_ARCHITECTURE_MINOR_IA64
#	define XIEITE_ARCHITECTURE_MINOR_IA64 (_M_IA64 % 100)
#endif

#ifdef ibm032
#	undef XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_32
#	define XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_32 1
#endif

#if defined(__370__) || defined(__THW_370__) || defined(ibm370)
#	undef XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_370
#	define XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_370 1
#endif

#if defined(__s390__) || defined(__s390x__)
#	undef XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_390
#	define XIEITE_ARCHITECTURE_TYPE_IBM_SYSTEM_390 1
#endif

#if defined(__SYSC_ZARCH__) || defined(__zarch__)
#	undef XIEITE_ARCHITECTURE_TYPE_IBM_Z
#	define XIEITE_ARCHITECTURE_TYPE_IBM_Z 1
#endif

#ifdef __loongarch__
#	undef XIEITE_ARCHITECTURE_TYPE_LOONGARCH
#	define XIEITE_ARCHITECTURE_TYPE_LOONGARCH 1

#	undef XIEITE_ARCHITECTURE_MAJOR_LOONGARCH
#	define XIEITE_ARCHITECTURE_MAJOR_LOONGARCH 32

#	if defined(__loongarch_grlen) || (defined(__loongarch64) && (__loongarchgrlen == 64))
#		undef XIEITE_ARCHITECTURE_MAJOR_LOONGARCH
#		define XIEITE_ARCHITECTURE_MAJOR_LOONGARCH 64
#	endif
#endif

#if defined(__MCORE__) || defined(__mcore__)
#	undef XIEITE_ARCHITECTURE_TYPE_M_CORE
#	define XIEITE_ARCHITECTURE_TYPE_M_CORE 1
#endif

#if defined(__M32R__) || defined(__m32r__)
#	undef XIEITE_ARCHITECTURE_TYPE_M32R
#	define XIEITE_ARCHITECTURE_TYPE_M32R 1
#endif

#if defined(__MMIX__) || defined(__mmix__)
#	undef XIEITE_ARCHITECTURE_TYPE_MMIX
#	define XIEITE_ARCHITECTURE_TYPE_MMIX 1
#endif

#if defined(__MN10300__) || defined(__mn10300__)
#	undef XIEITE_ARCHITECTURE_TYPE_MN103
#	define XIEITE_ARCHITECTURE_TYPE_MN103
#endif

#if defined(MIPS) || defined(_M_MRX000) || defined(__MIPS) || defined(__MIPS__) || defined(__mips) || defined(__mips__) || defined(mips)
#	undef XIEITE_ARCHITECTURE_TYPE_MIPS
#	define XIEITE_ARCHITECTURE_TYPE_MIPS 1

#	ifdef __mips
#		undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#		define XIEITE_ARCHITECTURE_MAJOR_MIPS __mips
#	else
#		if defined(_MIPS_ARCH_MIPS1) || (defined(_MIPS_ISA) && (_MIPS_ISA == _MIPS_ISA_MIPS1))
#			undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#			define XIEITE_ARCHITECTURE_MAJOR_MIPS 1
#		endif

#		if  defined(_MIPS_ARCH_MIPS2) || (defined(_MIPS_ISA) && (_MIPS_ISA == _MIPS_ISA_MIPS2)) || defined(_R3000) || defined(__MIPS_ISA2__)
#			undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#			define XIEITE_ARCHITECTURE_MAJOR_MIPS 2
#		endif

#		if defined(_MIPS_ARCH_MIPS3) || (defined(_MIPS_ISA) && (_MIPS_ISA == _MIPS_ISA_MIPS3)) || (defined(_M_MRX000) && (_M_MRX000 < 10000)) || defined(_R4000) || defined(__MIPS_ISA3__)
#			undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#			define XIEITE_ARCHITECTURE_MAJOR_MIPS 3
#		endif

#		if defined(_MIPS_ARCH_MIPS4) || (defined(_MIPS_ISA) && (_MIPS_ISA == _MIPS_ISA_MIPS4)) || (defined(_M_MRX000) && (_M_MRX000 >= 10000)) || defined(__MIPS_ISA4__)
#			undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#			define XIEITE_ARCHITECTURE_MAJOR_MIPS 4
#		endif

#		if defined(_MIPS_ARCH_MIPS5) || (defined(_MIPS_ISA) && (_MIPS_ISA == _MIPS_ISA_MIPS5)) || defined(__MIPS_ISA5__)
#			undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#			define XIEITE_ARCHITECTURE_MAJOR_MIPS 5
#		endif

#		if defined(_MIPS_ARCH_MIPS32) || (defined(_MIPS_ISA) && (_MIPS_ISA == _MIPS_ISA_MIPS32)) || defined(__mips32)
#			undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#			define XIEITE_ARCHITECTURE_MAJOR_MIPS 32
#		endif

#		if defined(_MIPS_ARCH_MIPS64) || (defined(_MIPS_ISA) && (_MIPS_ISA == _MIPS_ISA_MIPS64)) || defined(__mips64)
#			undef XIEITE_ARCHITECTURE_MAJOR_MIPS
#			define XIEITE_ARCHITECTURE_MAJOR_MIPS 64
#		endif
#	endif
#endif

#if defined(M68000) || defined(_M_M68K) || defined(__MC68K__) || defined(__m68k__) || defined(__mc68000) || defined(__mc68000__) || defined(is68k) || defined(mc68000)
#	undef XIEITE_ARCHITECTURE_TYPE_MOTOROLA_68000
#	define XIEITE_ARCHITECTURE_TYPE_MOTOROLA_68000 1

#	if defined(__MC68000__) || defined(__MC68010__) || defined(__mc68000) || defined(__mc68000__) || defined(__mc68010) || defined(__mc68010__) || defined(mc68000) || defined(mc68010)
#		undef XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000
#		define XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000 1
#	endif

#	if defined(__MC68020__) || defined(__MC68030__) || defined(__mc68020) || defined(__mc68020__) || defined(__mc68030) || defined(__mc68030__) || defined(mc68020) || defined(mc68030)
#		undef XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000
#		define XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000 2
#	endif

#	if defined(__MC68040__) || defined(__mc68040) || defined(__mc68040__) || defined(mc68040)
#		undef XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000
#		define XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000 3
#	endif

#	if defined(__MC68060__) || defined(__mc68060) || defined(__mc68060__) || defined(mc68060)
#		undef XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000
#		define XIEITE_ARCHITECTURE_MAJOR_MOTOROLA_68000 4
#	endif
#endif

#if defined(MOXIE) || defined(__MOXIE) || defined(__MOXIE__) || defined(__moxie) || defined(__moxie__) || defined(moxie)
#	undef XIEITE_ARCHITECTURE_TYPE_MOXIE
#	define XIEITE_ARCHITECTURE_TYPE_MOXIE 1
#endif

#if defined(__NDS32__) || defined(__nds32__)
#	undef XIEITE_ARCHITECTURE_TYPE_NDS32
#	define XIEITE_ARCHITECTURE_TYPE_NDS32 1
#endif

#if defined(__NEC__) || defined(__ve) || defined(__ve__)
#	undef XIEITE_ARCHITECTURE_TYPE_NEC_SX_AURORA_TSUBASA
#	define XIEITE_ARCHITECTURE_TYPE_NEC_SX_AURORA_TSUBASA 1
#endif

#if defined(NIOS2) || defined(__NIOS2) || defined(__NIOS2__) || defined(__nios2) || defined(__nios2__) || defined(nios2)
#	undef XIEITE_ARCHITECTURE_TYPE_NIOS_II
#	define XIEITE_ARCHITECTURE_TYPE_NIOS_II 1
#endif

#if defined(__OR1K__) || defined(__or1k__)
#	undef XIEITE_ARCHITECTURE_TYPE_OR1K
#	define XIEITE_ARCHITECTURE_TYPE_OR1K 1
#endif

#if defined(__HPPA__) || defined(__hppa) || defined(__hppa__)
#	undef XIEITE_ARCHITECTURE_TYPE_PA_RISC
#	define XIEITE_ARCHITECTURE_TYPE_PA_RISC 1

#	ifdef _PA_RISC1_0
#		undef XIEITE_ARCHITECTURE_MAJOR_PA_RISC
#		define XIEITE_ARCHITECTURE_MAJOR_PA_RISC 1
#	endif

#	if defined(_PA_RISC1_1) || defined(__HPPA11__) || defined(__PA7100__)
#		undef XIEITE_ARCHITECTURE_MAJOR_PA_RISC
#		define XIEITE_ARCHITECTURE_MAJOR_PA_RISC 1

#		undef XIEITE_ARCHITECTURE_MINOR_PA_RISC
#		define XIEITE_ARCHITECTURE_MINOR_PA_RISC 1
#	endif

#	if defined(_PA_RISC2_0) || defined(__HPPA20__) || defined(__PA8000__) || defined(__RISC2_0__)
#		undef XIEITE_ARCHITECTURE_MAJOR_PA_RISC
#		define XIEITE_ARCHITECTURE_MAJOR_PA_RISC 2
#	endif
#endif

#if defined(__pdp11) || defined(__pdp11__) || defined(pdp11)
#	undef XIEITE_ARCHITECTURE_TYPE_PDP_11
#	define XIEITE_ARCHITECTURE_TYPE_PDP_11 1
#endif

#if defined(PPC) || defined(_ARCH_COM) || defined(_ARCH_PPC) || defined(_ARCH_PPC64) || defined(_ARCH_PRW) || defined(_LP64) || defined(_M_MPPC) || defined(_M_PPC) || defined(_M_PPC) || defined(__64BIT__) || defined(__LP64__) || defined(__POWERPC__) || defined(__PPC) || defined(__PPC64__) || defined(__PPC__) || defined(__powerpc) || defined(__powerpc64__) || defined(__powerpc__) || defined(__ppc) || defined(__ppc64) || defined(__ppc64__) || defined(__ppc__) || defined(powerpc)
#	undef XIEITE_ARCHITECTURE_TYPE_POWERPC
#	define XIEITE_ARCHITECTURE_TYPE_POWERPC 1

#	ifdef _ARCH_PWR4
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 400
#	endif

#	if defined(_ARCH_440) || defined(__ppc440__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 440
#	endif

#	if defined(_ARCH_450) || defined(__ppc450__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 450
#	endif

#	ifdef _ARCH_PWR5
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 500
#	endif

#	ifdef _ARCH_PWR6
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 600
#	endif

#	if defined(_ARCH_601) || defined(__ppc601__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 601
#	endif

#	if defined(_ARCH_602) || defined(__ppc602__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 602
#	endif

#	if defined(_ARCH_603) || defined(__ppc603__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 603
#	endif

#	if defined(_ARCH_604) || defined(__ppc604__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 604
#	endif

#	if defined(_ARCH_605) || defined(__ppc605__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 605
#	endif

#	if defined(_ARCH_620) || defined(__ppc620__)
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 620
#	endif

#	ifdef _ARCH_PWR7
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 700
#	endif

#	ifdef _ARCH_PWR8
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 800
#	endif

#	ifdef _ARCH_PWR9
#		undef XIEITE_ARCHITECTURE_MAJOR_POWERPC
#		define XIEITE_ARCHITECTURE_MAJOR_POWERPC 900
#	endif
#endif

#ifdef __CUDA_ARCH__
#	undef XIEITE_ARCHITECTURE_TYPE_PTX
#	define XIEITE_ARCHITECTURE_TYPE_PTX 1
#endif

#ifdef pyr
#	undef XIEITE_ARCHITECTURE_TYPE_PYRAMID_9810
#	define XIEITE_ARCHITECTURE_TYPE_PYRAMID_9810 1
#endif

#if defined(__riscv) || defined(__riscv64) || defined(__riscv__) || defined(__riscv_xlen)
#	undef XIEITE_ARCHITECTURE_TYPE_RISC_V
#	define XIEITE_ARCHITECTURE_TYPE_RISC_V 1
#endif

#if defined(_ARCH_PWR) || defined(_ARCH_PWR2) || defined(_ARCH_PWR3) || defined(_ARCH_PWR4) || defined(_IBMR2) || defined(_POWER) || defined(__THW_RS6000)
#	undef XIEITE_ARCHITECTURE_TYPE_RS_6000
#	define XIEITE_ARCHITECTURE_TYPE_RS_6000 1
#endif

#if defined(__sparc) || defined(__sparc__) || defined(sparc)
#	undef XIEITE_ARCHITECTURE_TYPE_SPARC
#	define XIEITE_ARCHITECTURE_TYPE_SPARC 1

#	if defined(__sparc_v1__) || defined(__sparcv1)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 1
#	endif

#	if defined(__sparc_v2__) || defined(__sparcv2)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 2
#	endif

#	if defined(__sparc_v3__) || defined(__sparcv3)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 3
#	endif

#	if defined(__sparc_v4__) || defined(__sparcv4)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 4
#	endif

#	if defined(__sparc_v5__) || defined(__sparcv5)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 5
#	endif

#	if defined(__sparc_v6__) || defined(__sparcv6)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 6
#	endif

#	if defined(__sparc_v7__) || defined(__sparcv7)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 7
#	endif

#	if defined(__sparc_v8__) || defined(__sparcv8)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 8
#	endif

#	if defined(__sparc_v9__) || defined(__sparcv9)
#		undef XIEITE_ARCHITECTURE_MAJOR_SPARC
#		define XIEITE_ARCHITECTURE_MAJOR_SPARC 9
#	endif
#endif

#ifdef __sh__
#	undef XIEITE_ARCHITECTURE_TYPE_SUPERH
#	define XIEITE_ARCHITECTURE_TYPE_SUPERH 1

#	if defined(__SH1__) || defined(__sh1__)
#		undef XIEITE_ARCHITECTURE_MAJOR_SUPERH
#		define XIEITE_ARCHITECTURE_MAJOR_SUPERH 1
#	endif

#	if defined(__SH2__) || defined(__sh2__)
#		undef XIEITE_ARCHITECTURE_MAJOR_SUPERH
#		define XIEITE_ARCHITECTURE_MAJOR_SUPERH 2
#	endif

#	if defined(__SH3__) || defined(__sh3__)
#		undef XIEITE_ARCHITECTURE_MAJOR_SUPERH
#		define XIEITE_ARCHITECTURE_MAJOR_SUPERH 3
#	endif

#	if defined(__SH4__) || defined(__sh4__)
#		undef XIEITE_ARCHITECTURE_MAJOR_SUPERH
#		define XIEITE_ARCHITECTURE_MAJOR_SUPERH 4
#	endif

#	if defined(__SH5__) || defined(__sh5__)
#		undef XIEITE_ARCHITECTURE_MAJOR_SUPERH
#		define XIEITE_ARCHITECTURE_MAJOR_SUPERH 5
#	endif
#endif

#ifdef tahoe
#	undef XIEITE_ARCHITECTURE_TYPE_TAHOE
#	define XIEITE_ARCHITECTURE_TYPE_TAHOE 1
#endif

#if defined(_TMS320C2XX) || defined(_TMS320C5X) || defined(_TMS320C6X) || defined(__TMS320C2000__) || defined(__TMS320C55X__) || defined(__TMS320C6X__)
#	undef XIEITE_ARCHITECTURE_TYPE_TMS320
#	define XIEITE_ARCHITECTURE_TYPE_TMS320 1

#	ifdef _TMS320C28X
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 2800
#	endif

#	ifdef _TMS320C5XX
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 5400
#	endif

#	ifdef __TMS320C55X__
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 5500
#	endif

#	ifdef _TMS320C6200
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 6200
#	endif

#	ifdef _TMS320C6400
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 6400
#	endif

#	ifdef _TMS320C6400_PLUS
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 6400

#		undef XIEITE_ARCHITECTURE_MINOR_TMS320
#		define XIEITE_ARCHITECTURE_MINOR_TMS320 1
#	endif

#	ifdef _TMS320C6600
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 6600
#	endif

#	ifdef _TMS320C6700
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 6700
#	endif

#	ifdef _TMS320C6700_PLUS
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 6700

#		undef XIEITE_ARCHITECTURE_MINOR_TMS320
#		define XIEITE_ARCHITECTURE_MINOR_TMS320 1
#	endif

#	ifdef _TMS320C6740
#		undef XIEITE_ARCHITECTURE_MAJOR_TMS320
#		define XIEITE_ARCHITECTURE_MAJOR_TMS320 6740
#	endif

#endif

#ifdef __TMS470__
#	undef XIEITE_ARCHITECTURE_TYPE_TMS470
#	define XIEITE_ARCHITECTURE_TYPE_TMS470 1
#endif

#if defined(__v850) || defined(__v850__)
#	undef XIEITE_ARCHITECTURE_TYPE_V850
#	define XIEITE_ARCHITECTURE_TYPE_V850 1
#endif

#if defined(VAX) || defined(__VAX) || defined(__vax) || defined(vax)
#	undef XIEITE_ARCHITECTURE_TYPE_VAX
#	define XIEITE_ARCHITECTURE_TYPE_VAX 1
#endif

#if defined(__8080__) || defined(__8085__) || defined(__Z180) || defined(__Z80)
#	undef XIEITE_ARCHITECTURE_TYPE_X80
#	define XIEITE_ARCHITECTURE_TYPE_X80 1
#endif

#if defined(_M_I86) || defined(_M_IX86) || defined(_X86_) || defined(__386) || defined(__80486__) || defined(__I86__) || defined(__IA32__) || defined(__INTEL__) || defined(__SSE__) || defined(__THW_INTEL__) || defined(__X86__) || defined(__athlon__) || defined(__i386) || defined(__i386__) || defined(__k6__) || defined(__pentium__) || defined(i386)
#	undef XIEITE_ARCHITECTURE_TYPE_X86_32
#	define XIEITE_ARCHITECTURE_TYPE_X86_32 1

#	ifdef _M_IX86
#		undef XIEITE_ARCHITECTURE_MAJOR_X86_32
#		define XIEITE_ARCHITECTURE_MAJOR_X86_32 (_M_IX86 / 100)
#	elifdef __I86__
#		undef XIEITE_ARCHITECTURE_MAJOR_X86_32
#		define XIEITE_ARCHITECTURE_MAJOR_X86_32 __I86__
#	else
#		ifdef __i386__
#			undef XIEITE_ARCHITECTURE_MAJOR_X86_32
#			define XIEITE_ARCHITECTURE_MAJOR_X86_32 3
#		endif

#		if defined(__80486__) || defined(__i486__)
#			undef XIEITE_ARCHITECTURE_MAJOR_X86_32
#			define XIEITE_ARCHITECTURE_MAJOR_X86_32 4
#		endif

#		if defined(__i586__) || defined(__k6__) || defined(__pentium__)
#			undef XIEITE_ARCHITECTURE_MAJOR_X86_32
#			define XIEITE_ARCHITECTURE_MAJOR_X86_32 5
#		endif

#		if defined(__SSE__) || defined(__athlon__) || defined(__i686__) || defined(__pentiumpro__)
#			undef XIEITE_ARCHITECTURE_MAJOR_X86_32
#			define XIEITE_ARCHITECTURE_MAJOR_X86_32 6
#		endif
#	endif
#endif

#if defined(_M_AMD64) || defined(_M_X64) || defined(__amd64) || defined(__amd64__) || defined(__amd_64__amd64__) || defined(__k8) || defined(__k8__) || defined(__x86_64) || defined(__x86_64__)
#	undef XIEITE_ARCHITECTURE_TYPE_X86_64
#	define XIEITE_ARCHITECTURE_TYPE_X86_64 1
#endif

#if defined(__xstormy16) || defined(__xstormy16__) || defined(xstormy16)
#	undef XIEITE_ARCHITECTURE_TYPE_XSTORMY16
#	define XIEITE_ARCHITECTURE_TYPE_XSTORMY16 1
#endif

#if defined(__XTENSA__) || defined(__xtensa__)
#	undef XIEITE_ARCHITECTURE_TYPE_XTENSA
#	define XIEITE_ARCHITECTURE_TYPE_XTENSA 1
#endif

// https://github.com/cpredef/predef/blob/master/Architectures.md
// https://web.archive.org/web/20240613155632/https://www.analog.com/en/parametricsearch/11130#/
// https://github.com/saprykin/plibsys/blob/0e7ecc43f005abc88ff76811e4ec403e1975fa0a/src/pmacroscpu.h
// https://github.com/GrieferAtWork/KOSmk4/blob/63a9764f79ab2d9734ff2fec26a04b3ed5fa3131/kos/include/hybrid/host.h
