#pragma once

#define XIEITE_CAT(x, ...) XIEITE_CAT_PRIM(x, __VA_ARGS__)
#define XIEITE_CAT_REVERSE(x, ...) XIEITE_CAT_PRIM_REVERSE(x, __VA_ARGS__)
#define XIEITE_CAT_PRIM(x, ...) x##__VA_ARGS__
#define XIEITE_CAT_PRIM_REVERSE(x, ...) __VA_ARGS__##x
#define XIEITE_CAT_FIRST(x) XIEITE_CAT_PRIM(x,
#define XIEITE_CAT_SECOND(x) XIEITE_CAT_PRIM_REVERSE(x,
