#pragma once

#include <xieite/eat.hpp>
#include <xieite/paren.hpp>
#include <xieite/scan.hpp>

#define XIEITE_CM(...) XIEITE_SCAN(XIEITE_EAT XIEITE_LPAREN() XIEITE_DETAIL_CM_NEXT_0(__VA_ARGS__))

#define XIEITE_DETAIL_CM_NEXT_0(P, m, ...) XIEITE_DETAIL_CM_PASS_1(XIEITE_DETAIL_CM_PASS_1(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_1(P, m, ...) XIEITE_DETAIL_CM_PASS_2(XIEITE_DETAIL_CM_PASS_2(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_2(P, m, ...) XIEITE_DETAIL_CM_PASS_3(XIEITE_DETAIL_CM_PASS_3(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_3(P, m, ...) XIEITE_DETAIL_CM_PASS_4(XIEITE_DETAIL_CM_PASS_4(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_4(P, m, ...) XIEITE_DETAIL_CM_PASS_5(XIEITE_DETAIL_CM_PASS_5(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_5(P, m, ...) XIEITE_DETAIL_CM_PASS_6(XIEITE_DETAIL_CM_PASS_6(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_6(P, m, ...) XIEITE_DETAIL_CM_PASS_7(XIEITE_DETAIL_CM_PASS_7(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_7(P, m, ...) XIEITE_DETAIL_CM_PASS_8(XIEITE_DETAIL_CM_PASS_8(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_8(P, m, ...) XIEITE_DETAIL_CM_PASS_9(XIEITE_DETAIL_CM_PASS_9(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_9(P, m, ...) XIEITE_DETAIL_CM_PASS_A(XIEITE_DETAIL_CM_PASS_A(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_A(P, m, ...) XIEITE_DETAIL_CM_PASS_B(XIEITE_DETAIL_CM_PASS_B(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_B(P, m, ...) XIEITE_DETAIL_CM_PASS_C(XIEITE_DETAIL_CM_PASS_C(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_C(P, m, ...) XIEITE_DETAIL_CM_PASS_D(XIEITE_DETAIL_CM_PASS_D(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_D(P, m, ...) XIEITE_DETAIL_CM_PASS_E(XIEITE_DETAIL_CM_PASS_E(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_E(P, m, ...) XIEITE_DETAIL_CM_PASS_F(XIEITE_DETAIL_CM_PASS_F(XIEITE_CM_FN_##m(, P##__VA_ARGS__)))
#define XIEITE_DETAIL_CM_NEXT_F(P, m, ...) XIEITE_CM_FN_##m(, P##__VA_ARGS__)
#define XIEITE_DETAIL_CM_PASS_1(x) XIEITE_DETAIL_CM_NEXT_1 x
#define XIEITE_DETAIL_CM_PASS_2(x) XIEITE_DETAIL_CM_NEXT_2 x
#define XIEITE_DETAIL_CM_PASS_3(x) XIEITE_DETAIL_CM_NEXT_3 x
#define XIEITE_DETAIL_CM_PASS_4(x) XIEITE_DETAIL_CM_NEXT_4 x
#define XIEITE_DETAIL_CM_PASS_5(x) XIEITE_DETAIL_CM_NEXT_5 x
#define XIEITE_DETAIL_CM_PASS_6(x) XIEITE_DETAIL_CM_NEXT_6 x
#define XIEITE_DETAIL_CM_PASS_7(x) XIEITE_DETAIL_CM_NEXT_7 x
#define XIEITE_DETAIL_CM_PASS_8(x) XIEITE_DETAIL_CM_NEXT_8 x
#define XIEITE_DETAIL_CM_PASS_9(x) XIEITE_DETAIL_CM_NEXT_9 x
#define XIEITE_DETAIL_CM_PASS_A(x) XIEITE_DETAIL_CM_NEXT_A x
#define XIEITE_DETAIL_CM_PASS_B(x) XIEITE_DETAIL_CM_NEXT_B x
#define XIEITE_DETAIL_CM_PASS_C(x) XIEITE_DETAIL_CM_NEXT_C x
#define XIEITE_DETAIL_CM_PASS_D(x) XIEITE_DETAIL_CM_NEXT_D x
#define XIEITE_DETAIL_CM_PASS_E(x) XIEITE_DETAIL_CM_NEXT_E x
#define XIEITE_DETAIL_CM_PASS_F(x) XIEITE_DETAIL_CM_NEXT_F x

// Note: I have no idea how to use this
