#pragma once

#define XIEITE_CONCATENATE(first_, ...) XIEITE_CONCATENATE_PRIMITIVE(first_, __VA_ARGS__)
#define XIEITE_CONCATENATE_REVERSE(first_, ...) XIEITE_CONCATENATE_PRIMITIVE_REVERSE(first_, __VA_ARGS__)
#define XIEITE_CONCATENATE_PRIMITIVE(first_, ...) first_##__VA_ARGS__
#define XIEITE_CONCATENATE_PRIMITIVE_REVERSE(first_, ...) __VA_ARGS__##first_
#define XIEITE_CONCATENATE_FIRST(first_) XIEITE_CONCATENATE_PRIMITIVE(first_,
#define XIEITE_CONCATENATE_SECOND(second_) XIEITE_CONCATENATE_PRIMITIVE_REVERSE(second_,
