#ifndef XIEITE_HEADER__CONCEPTS
#	define XIEITE_HEADER__CONCEPTS

#	include "./concepts/aggregate.hpp"
#	include "./concepts/all_of.hpp"
#	include "./concepts/any_of.hpp"
#	include "./concepts/arithmetic.hpp"
#	include "./concepts/bitset_reference.hpp"
#	include "./concepts/character.hpp"
#	include "./concepts/constant.hpp"
#	include "./concepts/convertible_to_all_of.hpp"
#	include "./concepts/convertible_to_any_of.hpp"
#	include "./concepts/copy_assignable.hpp"
#	include "./concepts/decayed.hpp"
#	include "./concepts/derivable.hpp"
#	include "./concepts/derived_from_all_of.hpp"
#	include "./concepts/derived_from_any_of.hpp"
#	include "./concepts/enumeration.hpp"
#	include "./concepts/functable.hpp"
#	include "./concepts/hashable.hpp"
#	include "./concepts/hasher.hpp"
#	include "./concepts/integer.hpp"
#	include "./concepts/linear_shape.hpp"
#	include "./concepts/narrow_character.hpp"
#	include "./concepts/no_throw_convertible_to.hpp"
#	include "./concepts/no_throw_convertible_to_all_of.hpp"
#	include "./concepts/no_throw_convertible_to_any_of.hpp"
#	include "./concepts/numeric.hpp"
#	include "./concepts/ordinary_character.hpp"
#	include "./concepts/polymorphic.hpp"
#	include "./concepts/range_of.hpp"
#	include "./concepts/same_as_all_of.hpp"
#	include "./concepts/same_as_any_of.hpp"
#	include "./concepts/streamable_in.hpp"
#	include "./concepts/streamable_out.hpp"
#	include "./concepts/temporal_duration.hpp"
#	include "./concepts/trivial.hpp"
#	include "./concepts/uniform_random_bit_generator.hpp"
#	include "./concepts/unsigned_integer.hpp"
#	include "./concepts/wide_character.hpp"

#endif
