#pragma once

#define XIEITE_CONCATENATE($first, $second) XIEITE_CONCATENATE_PRIMITIVE($first, $second)
#define XIEITE_CONCATENATE_REVERSE($first, $second) XIEITE_CONCATENATE_PRIMITIVE_REVERSE($first, $second)
#define XIEITE_CONCATENATE_PRIMITIVE($first, $second) $first##$second
#define XIEITE_CONCATENATE_PRIMITIVE_REVERSE($first, $second) $second##$first
#define XIEITE_CONCATENATE_FIRST($first) XIEITE_CONCATENATE_PRIMITIVE($first,
#define XIEITE_CONCATENATE_SECOND($second) XIEITE_CONCATENATE_PRIMITIVE_REVERSE($second,
