#pragma once

#include <xieite/concepts/Aggregate.hpp>
#include <xieite/concepts/Arithmetic.hpp>
#include <xieite/concepts/CallbackComparator.hpp>
#include <xieite/concepts/CallbackSelector.hpp>
#include <xieite/concepts/ConvertibleToOneOf.hpp>
#include <xieite/concepts/CopyAssignable.hpp>
#include <xieite/concepts/Decayed.hpp>
#include <xieite/concepts/Enumerator.hpp>
#include <xieite/concepts/Hashable.hpp>
#include <xieite/concepts/LinearShape.hpp>
#include <xieite/concepts/NoThrowConvertibleTo.hpp>
#include <xieite/concepts/NoThrowConvertibleToOneOf.hpp>
#include <xieite/concepts/SameAsOneOf.hpp>
#include <xieite/concepts/StreamableInto.hpp>
#include <xieite/concepts/StreamableOutOf.hpp>
#include <xieite/concepts/TemporalDuration.hpp>
#include <xieite/concepts/Trivial.hpp>
#include <xieite/concepts/UniformRandomBitGenerator.hpp>
