#ifndef XIEITE_HEADER__CONCEPTS
#	define XIEITE_HEADER__CONCEPTS

#	include "./concepts/Aggregate.hpp"
#	include "./concepts/AllOf.hpp"
#	include "./concepts/AnyOf.hpp"
#	include "./concepts/Arithmetic.hpp"
#	include "./concepts/BitsetReference.hpp"
#	include "./concepts/Character.hpp"
#	include "./concepts/ChronoDuration.hpp"
#	include "./concepts/Constant.hpp"
#	include "./concepts/ConvertibleToAllOf.hpp"
#	include "./concepts/ConvertibleToAnyOf.hpp"
#	include "./concepts/CopyAssignable.hpp"
#	include "./concepts/Decayed.hpp"
#	include "./concepts/Derivable.hpp"
#	include "./concepts/DerivedFromAllOf.hpp"
#	include "./concepts/DerivedFromAnyOf.hpp"
#	include "./concepts/Enumerator.hpp"
#	include "./concepts/Functable.hpp"
#	include "./concepts/Hashable.hpp"
#	include "./concepts/Hasher.hpp"
#	include "./concepts/LinearShape.hpp"
#	include "./concepts/NarrowCharacter.hpp"
#	include "./concepts/NoThrowConvertibleTo.hpp"
#	include "./concepts/NoThrowConvertibleToAllOf.hpp"
#	include "./concepts/NoThrowConvertibleToAnyOf.hpp"
#	include "./concepts/OrdinaryCharacter.hpp"
#	include "./concepts/Polymorphic.hpp"
#	include "./concepts/RangeOf.hpp"
#	include "./concepts/SameAsAllOf.hpp"
#	include "./concepts/SameAsAnyOf.hpp"
#	include "./concepts/StreamableIn.hpp"
#	include "./concepts/StreamableOut.hpp"
#	include "./concepts/Trivial.hpp"
#	include "./concepts/UniformRandomBitGenerator.hpp"
#	include "./concepts/WideCharacter.hpp"

#endif
