#pragma once

#include <xieite/console/ModeLock.hpp>
#include <xieite/console/Position.hpp>
#include <xieite/console/clearLine.hpp>
#include <xieite/console/clearScreen.hpp>
#include <xieite/console/getArrowKey.hpp>
#include <xieite/console/getArrowKeyOrCharacter.hpp>
#include <xieite/console/getCharacter.hpp>
#include <xieite/console/getCursorPosition.hpp>
#include <xieite/console/getString.hpp>
#include <xieite/console/getWindowSize.hpp>
#include <xieite/console/putBackString.hpp>
#include <xieite/console/resetStyle.hpp>
#include <xieite/console/setCursorAlternative.hpp>
#include <xieite/console/setScreenAlternative.hpp>
#include <xieite/console/setColorBackground.hpp>
#include <xieite/console/setColorDim.hpp>
#include <xieite/console/setColorForeground.hpp>
#include <xieite/console/setColorInversion.hpp>
#include <xieite/console/setCursorPosition.hpp>
#include <xieite/console/setCursorVisibility.hpp>
#include <xieite/console/setTextBlink.hpp>
#include <xieite/console/setTextBold.hpp>
#include <xieite/console/setTextItalic.hpp>
#include <xieite/console/setTextStrikethrough.hpp>
#include <xieite/console/setTextUnderline.hpp>
#include <xieite/console/setTextVisibility.hpp>
