#pragma once

#include <xieite/eat.hpp>
#include <xieite/parenthesis.hpp>
#include <xieite/scan.hpp>

#define XIEITE_CONTINUATION_MACHINE(...) XIEITE_SCAN(XIEITE_EAT XIEITE_PARENTHESIS_LEFT() XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_0(__VA_ARGS__))

#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_0(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_1(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_1(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_1(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_2(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_2(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_2(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_3(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_3(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_3(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_4(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_4(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_4(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_5(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_5(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_5(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_6(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_6(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_6(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_7(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_7(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_7(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_8(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_8(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_8(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_9(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_9(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_9(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_A(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_A(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_A(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_B(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_B(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_B(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_C(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_C(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_C(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_D(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_D(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_D(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_E(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_E(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_E(lazy_, macro_, ...) XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_F(XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_F(XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)))
#define XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_F(lazy_, macro_, ...) XIEITE_CONTINUATION_MACHINE_CALLBACK_##macro_(, lazy_##__VA_ARGS__)
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_1(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_1 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_2(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_2 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_3(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_3 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_4(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_4 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_5(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_5 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_6(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_6 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_7(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_7 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_8(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_8 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_9(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_9 result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_A(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_A result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_B(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_B result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_C(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_C result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_D(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_D result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_E(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_E result_
#define XIEITE_DETAIL_CONTINUATION_MACHINE_PASS_F(result_) XIEITE_DETAIL_CONTINUATION_MACHINE_NEXT_F result_

// Note: I have no idea how to use this
