#pragma once

#include <xieite/compiler.hpp>
#include <xieite/pragma.hpp>
#include <xieite/stringify.hpp>

#define XIEITE_DIAGNOSTIC_PUSH()
#define XIEITE_DIAGNOSTIC_POP()
#define XIEITE_DIAGNOSTIC_WARN_GCC(...)
#define XIEITE_DIAGNOSTIC_WARN_CLANG(...)
#define XIEITE_DIAGNOSTIC_WARN_MSVC(...)
#define XIEITE_DIAGNOSTIC_ERROR_GCC(...)
#define XIEITE_DIAGNOSTIC_ERROR_CLANG(...)
#define XIEITE_DIAGNOSTIC_ERROR_MSVC(...)
#define XIEITE_DIAGNOSTIC_IGNORE_GCC(...)
#define XIEITE_DIAGNOSTIC_IGNORE_CLANG(...)
#define XIEITE_DIAGNOSTIC_IGNORE_MSVC(...)

#if XIEITE_COMPILER_TYPE_GCC
#	undef XIEITE_DIAGNOSTIC_PUSH
#	define XIEITE_DIAGNOSTIC_PUSH() XIEITE_PRAGMA(GCC diagnostic push)

#	undef XIEITE_DIAGNOSTIC_POP
#	define XIEITE_DIAGNOSTIC_POP() XIEITE_PRAGMA(GCC diagnostic pop)

#	undef XIEITE_DIAGNOSTIC_WARN_GCC
#	define XIEITE_DIAGNOSTIC_WARN_GCC(...) XIEITE_PRAGMA(GCC diagnostic warning XIEITE_STRINGIFY(__VA_ARGS__))

#	undef XIEITE_DIAGNOSTIC_ERROR_GCC
#	define XIEITE_DIAGNOSTIC_ERROR_GCC(...) XIEITE_PRAGMA(GCC diagnostic error XIEITE_STRINGIFY(__VA_ARGS__))

#	undef XIEITE_DIAGNOSTIC_IGNORE_GCC
#	define XIEITE_DIAGNOSTIC_IGNORE_GCC(...) XIEITE_PRAGMA(GCC diagnostic ignored XIEITE_STRINGIFY(__VA_ARGS__))
#elif XIEITE_COMPILER_TYPE_CLANG
#	undef XIEITE_DIAGNOSTIC_PUSH
#	define XIEITE_DIAGNOSTIC_PUSH() XIEITE_PRAGMA(clang diagnostic push)

#	undef XIEITE_DIAGNOSTIC_POP
#	define XIEITE_DIAGNOSTIC_POP() XIEITE_PRAGMA(clang diagnostic pop)

#	undef XIEITE_DIAGNOSTIC_WARN_CLANG
#	define XIEITE_DIAGNOSTIC_WARN_CLANG(...) XIEITE_PRAGMA(clang diagnostic warning XIEITE_STRINGIFY(__VA_ARGS__))

#	undef XIEITE_DIAGNOSTIC_ERROR_CLANG
#	define XIEITE_DIAGNOSTIC_ERROR_CLANG(...) XIEITE_PRAGMA(clang diagnostic error XIEITE_STRINGIFY(__VA_ARGS__))

#	undef XIEITE_DIAGNOSTIC_IGNORE_CLANG
#	define XIEITE_DIAGNOSTIC_IGNORE_CLANG(...) XIEITE_PRAGMA(clang diagnostic ignored XIEITE_STRINGIFY(__VA_ARGS__))
#elif XIEITE_COMPILER_TYPE_MSVC
#	undef XIEITE_DIAGNOSTIC_PUSH
#	define XIEITE_DIAGNOSTIC_PUSH() XIEITE_PRAGMA(warning(push))

#	undef XIEITE_DIAGNOSTIC_POP
#	define XIEITE_DIAGNOSTIC_POP() XIEITE_PRAGMA(warning(pop))

#	undef XIEITE_DIAGNOSTIC_WARN_MSVC
#	define XIEITE_DIAGNOSTIC_WARN_MSVC(...) XIEITE_PRAGMA(warning(default: __VA_ARGS__))

#	undef XIEITE_DIAGNOSTIC_ERROR_MSVC
#	define XIEITE_DIAGNOSTIC_ERROR_MSVC(...) XIEITE_PRAGMA(warning(error: __VA_ARGS__))

#	undef XIEITE_DIAGNOSTIC_IGNORE_MSVC
#	define XIEITE_DIAGNOSTIC_IGNORE_MSVC(...) XIEITE_PRAGMA(warning(disable: __VA_ARGS__))
#endif

// https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4000-c5999
