#pragma once

#define XIEITE_EVALUATE(...) XIEITE_DETAIL_EVALUATE_0(XIEITE_DETAIL_EVALUATE_0(XIEITE_DETAIL_EVALUATE_0(XIEITE_DETAIL_EVALUATE_0(__VA_ARGS__))))

#define XIEITE_DETAIL_EVALUATE_0(...) XIEITE_DETAIL_EVALUATE_1(XIEITE_DETAIL_EVALUATE_1(XIEITE_DETAIL_EVALUATE_1(XIEITE_DETAIL_EVALUATE_1(__VA_ARGS__))))
#define XIEITE_DETAIL_EVALUATE_1(...) XIEITE_DETAIL_EVALUATE_2(XIEITE_DETAIL_EVALUATE_2(XIEITE_DETAIL_EVALUATE_2(XIEITE_DETAIL_EVALUATE_2(__VA_ARGS__))))
#define XIEITE_DETAIL_EVALUATE_2(...) XIEITE_DETAIL_EVALUATE_3(XIEITE_DETAIL_EVALUATE_3(XIEITE_DETAIL_EVALUATE_3(XIEITE_DETAIL_EVALUATE_3(__VA_ARGS__))))
#define XIEITE_DETAIL_EVALUATE_3(...) XIEITE_DETAIL_EVALUATE_4(XIEITE_DETAIL_EVALUATE_4(XIEITE_DETAIL_EVALUATE_4(XIEITE_DETAIL_EVALUATE_4(__VA_ARGS__))))
#define XIEITE_DETAIL_EVALUATE_4(...) __VA_ARGS__
