#pragma once

#define XIEITE_EXTENSION_ADD_WITH_CARRY 0
#define XIEITE_EXTENSION_ADVANCED_ENCRYPTION_STANDARD 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_BYTE_WORD 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_CONFLICT_DETECTION 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_DOUBLEWORD_QUADWORD 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_EXPONENTIAL_RECIPROCAL 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_FOUNDATION 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_PREFETCH 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_BIT_MANIPULATION 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_LENGTH 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_2 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_10 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_10_1 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_10_1_256 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_10_1_512 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_10_2 0
#define XIEITE_EXTENSION_ATOMIC 0
#define XIEITE_EXTENSION_BYTE_MATRIX_MULTIPLICATION 0
#define XIEITE_EXTENSION_CACHE_LINE_DEMOTE 0
#define XIEITE_EXTENSION_CRYPTOGRAPHY
#define XIEITE_EXTENSION_CYCLIC_REDUNDANCY_CHECK 0
#define XIEITE_EXTENSION_DOT_PRODUCT 0
#define XIEITE_EXTENSION_ENCHANCED_VECTOR_256 0
#define XIEITE_EXTENSION_ENCHANCED_VECTOR_512 0
#define XIEITE_EXTENSION_FAST_FLOAT_STATE_RESTORE 0
#define XIEITE_EXTENSION_FLOAT_16_FUSED_MULTIPLY_ADD 0
#define XIEITE_EXTENSION_FLOAT_16_SCALAR_ARITHMETIC 0
#define XIEITE_EXTENSION_FLOAT_16_VECTOR_ARITHMETIC 0
#define XIEITE_EXTENSION_FLOAT_BRAIN_SCALAR_ARITHMETIC 0
#define XIEITE_EXTENSION_FLOAT_BRAIN_VECTOR_ARITHMETIC 0
#define XIEITE_EXTENSION_FLOAT_FUSED_MULTIPLY_ADD 0
#define XIEITE_EXTENSION_FLOAT_ROUND_TO_INTEGER 0
#define XIEITE_EXTENSION_HARD_FLOAT 0
#define XIEITE_EXTENSION_HIGH_PERFORMANCE_VECTOR 0
#define XIEITE_EXTENSION_INTEGER_DIVISION 0
#define XIEITE_EXTENSION_JOINT_CONVERT 0
#define XIEITE_EXTENSION_MEMORY_TAGGING 0
#define XIEITE_EXTENSION_MOVE_64_BYTES_AS_DIRECT_STORE 0
#define XIEITE_EXTENSION_MOVE_DOUBLEWORD_AS_DIRECT_STORE 0
#define XIEITE_EXTENSION_MULTIMEDIA 0
#define XIEITE_EXTENSION_NEON 0
#define XIEITE_EXTENSION_POP_COUNT 0
#define XIEITE_EXTENSION_QUANTIZED_ROUNDING_DOUBLING_MULTIPLY 0
#define XIEITE_EXTENSION_RANDOM_NUMBER_GENERATION 0
#define XIEITE_EXTENSION_READ_RANDOM_SEED 0
#define XIEITE_EXTENSION_RESTRICTED_TRANSACTIONAL_MEMORY 0
#define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE 0
#define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_COMPACT 0
#define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_OPTIMIZED 0
#define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_SUPERVISOR 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_BYTE_MATRIX_MULTIPLICATION 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_FLOAT_32_MATRIX_MULTIPLICATION 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_FLOAT_64_MATRIX_MULTIPLICATION 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_2 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_2_ADVANCED_ENCRYPTION_STANDARD 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_2_BIT_PERMUTATION 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_2_SECURE_HASH_ALGORITHM_3 0
#define XIEITE_EXTENSION_SCALABLE_VECTOR_2_SHANGMI_4 0
#define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM 0
#define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_2 0
#define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_3 0
#define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_512 0
#define XIEITE_EXTENSION_SHADOW_STACK 0
#define XIEITE_EXTENSION_SHANGMI_3 0
#define XIEITE_EXTENSION_SHANGMI_4 0
#define XIEITE_EXTENSION_STREAMING 0
#define XIEITE_EXTENSION_STREAMING_2 0
#define XIEITE_EXTENSION_STREAMING_3 0
#define XIEITE_EXTENSION_SUPPLEMENTAL_STREAMING_3 0
#define XIEITE_EXTENSION_STREAMING_4_1 0
#define XIEITE_EXTENSION_STREAMING_4_2 0
#define XIEITE_EXTENSION_TRACED_MEMORY_EXECUTION 0
#define XIEITE_EXTENSION_USER_LEVEL_MONITOR_WAIT 0
#define XIEITE_EXTENSION_WRITE_BACK_NO_INVALIDATE 0

#ifdef __ADX__
#	undef XIEITE_EXTENSION_ADD_WITH_CARRY
#	define XIEITE_EXTENSION_ADD_WITH_CARRY 1
#endif

#ifdef __ARM_FEATURE_AES
#	undef XIEITE_EXTENSION_ADVANCED_ENCRYPTION_STANDARD
#	define XIEITE_EXTENSION_ADVANCED_ENCRYPTION_STANDARD 1
#endif

#ifdef __AVX__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR
#	define XIEITE_EXTENSION_ADVANCED_VECTOR 1
#endif

#ifdef __AVX512BW__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_BYTE_WORD
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_BYTE_WORD 1
#endif

#ifdef __AVX512CD__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_CONFLICT_DETECTION
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_CONFLICT_DETECTION 1
#endif

#ifdef __AVX512DQ__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_DOUBLEWORD_QUADWORD
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_DOUBLEWORD_QUADWORD 1
#endif

#ifdef __AVX512ER__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_EXPONENTIAL_RECIPROCAL
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_EXPONENTIAL_RECIPROCAL 1
#endif

#ifdef __AVX512F__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_FOUNDATION
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_FOUNDATION 1
#endif

#ifdef __AVX512PF__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_PREFETCH
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_PREFETCH 1
#endif

#ifdef __AVX512VBMI__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_BIT_MANIPULATION
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_BIT_MANIPULATION
#endif

#ifdef __AVX512VL__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_LENGTH
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_LENGTH 1
#endif

#ifdef __AVX2__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_2
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_2 1
#endif

#ifdef __AVX10__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_10
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_10 1
#endif

#ifdef __AVX10_1__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_10_1
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_10_1 1
#endif

#ifdef __AVX10_1_256__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_10_1_256
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_10_1_256 1
#endif

#ifdef __AVX10_1_512__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_10_1_512
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_10_1_512 1
#endif

#ifdef __AVX10_2__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_10_2
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_10_2 1
#endif

#ifdef __ARM_FEATURE_ATOMICS
#	undef XIEITE_EXTENSION_ATOMIC
#	define XIEITE_EXTENSION_ATOMIC
#endif

#ifdef __ARM_FEATURE_MATMUL_INT8
#	undef XIEITE_EXTENSION_BYTE_MATRIX_MULTIPLICATION
#	define XIEITE_EXTENSION_BYTE_MATRIX_MULTIPLICATION 1
#endif

#ifdef __CLDEMOTE__
#	undef XIEITE_EXTENSION_CACHE_LINE_DEMOTE
#	define XIEITE_EXTENSION_CACHE_LINE_DEMOTE 1
#endif

#ifdef __ARM_FEATURE_CRYPTO
#	undef XIEITE_EXTENSION_CRYPTOGRAPHY
#	define XIEITE_EXTENSION_CRYPTOGRAPHY 1
#endif

#ifdef __ARM_FEATURE_CRC32
#	undef XIEITE_EXTENSION_CYCLIC_REDUNDANCY_CHECK
#	define XIEITE_EXTENSION_CYCLIC_REDUNDANCY_CHECK 1
#endif

#ifdef __ARM_FEATURE_DOTPROD
#	undef XIEITE_EXTENSION_DOT_PRODUCT
#	define XIEITE_EXTENSION_DOT_PRODUCT 1
#endif

#ifdef __EVEX256__
#	undef XIEITE_EXTENSION_ENCHANCED_VECTOR_256
#	define XIEITE_EXTENSION_ENCHANCED_VECTOR_256 1
#endif

#ifdef __EVEX512__
#	undef XIEITE_EXTENSION_ENCHANCED_VECTOR_512
#	define XIEITE_EXTENSION_ENCHANCED_VECTOR_512 1
#endif

#ifdef __FXSR__
#	undef XIEITE_EXTENSION_FAST_FLOAT_STATE_RESTORE
#	define XIEITE_EXTENSION_FAST_FLOAT_STATE_RESTORE 1
#endif

#if defined(__ARM_FEATURE_FP16FML) || defined(__ARM_FEATURE_FP16_FML)
#	undef XIEITE_EXTENSION_FLOAT_16_FUSED_MULTIPLY_ADD
#	define XIEITE_EXTENSION_FLOAT_16_FUSED_MULTIPLY_ADD 1
#endif

#ifdef __ARM_FEATURE_FP16_SCALAR_ARITHMETIC
#	undef XIEITE_EXTENSION_FLOAT_16_SCALAR_ARITHMETIC
#	define XIEITE_EXTENSION_FLOAT_16_SCALAR_ARITHMETIC 1
#endif

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
#	undef XIEITE_EXTENSION_FLOAT_16_VECTOR_ARITHMETIC
#	define XIEITE_EXTENSION_FLOAT_16_VECTOR_ARITHMETIC 1
#endif

#ifdef __ARM_FEATURE_BF16_SCALAR_ARITHMETIC
#	undef XIEITE_EXTENSION_FLOAT_BRAIN_SCALAR_ARITHMETIC
#	define XIEITE_EXTENSION_FLOAT_BRAIN_SCALAR_ARITHMETIC 1
#endif

#ifdef __ARM_FEATURE_BF16_VECTOR_ARITHMETIC
#	undef XIEITE_EXTENSION_FLOAT_BRAIN_VECTOR_ARITHMETIC
#	define XIEITE_EXTENSION_FLOAT_BRAIN_VECTOR_ARITHMETIC 1
#endif

#ifdef __FMA__
#	undef XIEITE_EXTENSION_FLOAT_FUSED_MULTIPLY_ADD
#	define XIEITE_EXTENSION_FLOAT_FUSED_MULTIPLY_ADD 1
#endif

#ifdef __ARM_FEATURE_FRINT
#	undef XIEITE_EXTENSION_FLOAT_ROUND_TO_INTEGER
#	define XIEITE_EXTENSION_FLOAT_ROUND_TO_INTEGER 1
#endif

#if defined(__ARM_PCS_VFP) || defined(__mips_hard_float) || defined(UNDER_RT) || defined(DART_RUN_IN_QEMU_ARMv7) || defined(XP_IOS)
#	undef XIEITE_EXTENSION_HARD_FLOAT
#	define XIEITE_EXTENSION_HARD_FLOAT 1
#endif

#ifdef __HVX__
#	undef XIEITE_EXTENSION_HIGH_PERFORMANCE_VECTOR
#	define XIEITE_EXTENSION_HIGH_PERFORMANCE_VECTOR 1
#endif

#ifdef __ARM_FEATURE_IDIV
#	undef XIEITE_EXTENSION_INTEGER_DIVISION
#	define XIEITE_EXTENSION_INTEGER_DIVISION 1
#endif

#ifdef __ARM_FEATURE_JCVT
#	undef XIEITE_EXTENSION_JOINT_CONVERT
#	define XIEITE_EXTENSION_JOINT_CONVERT 1
#endif

#ifdef __ARM_FEATURE_MEMORY_TAGGING
#	undef XIEITE_EXTENSION_MEMORY_TAGGING
#	define XIEITE_EXTENSION_MEMORY_TAGGING 1
#endif

#ifdef __MOVDIR64B__
#	undef XIEITE_EXTENSION_MOVE_64_BYTES_AS_DIRECT_STORE
#	define XIEITE_EXTENSION_MOVE_64_BYTES_AS_DIRECT_STORE 1
#endif

#ifdef __MOVDIRI__
#	undef XIEITE_EXTENSION_MOVE_DOUBLEWORD_AS_DIRECT_STORE
#	define XIEITE_EXTENSION_MOVE_DOUBLEWORD_AS_DIRECT_STORE 1
#endif

#ifdef __MMX__
#	undef XIEITE_EXTENSION_MULTIMEDIA
#	define XIEITE_EXTENSION_MULTIMEDIA 1
#endif

#if defined(__ARM_NEON) || defined(__ARM_NEON__)
#	undef XIEITE_EXTENSION_NEON
#	define XIEITE_EXTENSION_NEON 1
#endif

#ifdef __POPCNT__
#	undef XIEITE_EXTENSION_POP_COUNT
#	define XIEITE_EXTENSION_POP_COUNT 1
#endif

#ifdef __ARM_FEATURE_QRDMX
#	undef XIEITE_EXTENSION_QUANTIZED_ROUNDING_DOUBLING_MULTIPLY
#	define XIEITE_EXTENSION_QUANTIZED_ROUNDING_DOUBLING_MULTIPLY 1
#endif

#ifdef __ARM_FEATURE_RNG
#	undef XIEITE_EXTENSION_RANDOM_NUMBER_GENERATION
#	define XIEITE_EXTENSION_RANDOM_NUMBER_GENERATION 1
#endif

#ifdef __RDSEED__
#	undef XIEITE_EXTENSION_READ_RANDOM_SEED
#	define XIEITE_EXTENSION_READ_RANDOM_SEED 1
#endif

#ifdef __RTM__
#	undef XIEITE_EXTENSION_RESTRICTED_TRANSACTIONAL_MEMORY
#	define XIEITE_EXTENSION_RESTRICTED_TRANSACTIONAL_MEMORY 1
#endif

#ifdef __XSAVE__
#	undef XIEITE_EXTENSION_SAVE_PROCESSOR_STATE
#	define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE 1
#endif

#ifdef __XSAVEC__
#	undef XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_COMPACT
#	define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_COMPACT 1
#endif

#ifdef __XSAVEOPT__
#	undef XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_OPTIMIZED
#	define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_OPTIMIZED 1
#endif

#ifdef __XSAVES__
#	undef XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_SUPERVISOR
#	define XIEITE_EXTENSION_SAVE_PROCESSOR_STATE_SUPERVISOR 1
#endif

#if defined(__ARM_FEATURE_SVE) || defined(__ARM_FEATURE_SVE_VECTOR_OPERATORS)
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR
#	define XIEITE_EXTENSION_SCALABLE_VECTOR 1
#endif

#ifdef __ARM_FEATURE_SVE_MATMUL_INT8
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_BYTE_MATRIX_MULTIPLICATION
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_BYTE_MATRIX_MULTIPLICATION 1
#endif

#ifdef __ARM_FEATURE_SVE_MATMUL_FP32
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_FLOAT_32_MATRIX_MULTIPLICATION
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_FLOAT_32_MATRIX_MULTIPLICATION 1
#endif

#ifdef __ARM_FEATURE_SVE_MATMUL_FP64
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_FLOAT_64_MATRIX_MULTIPLICATION
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_FLOAT_64_MATRIX_MULTIPLICATION 1
#endif

#ifdef __ARM_FEATURE_SVE2
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_2
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_2 1
#endif

#ifdef __ARM_FEATURE_SVE2_AES
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_2_ADVANCED_ENCRYPTION_STANDARD
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_2_ADVANCED_ENCRYPTION_STANDARD 1
#endif

#ifdef __ARM_FEATURE_SVE2_BITPERM
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_2_BIT_PERMUTATION
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_2_BIT_PERMUTATION 1
#endif

#ifdef __ARM_FEATURE_SVE2_SHA3
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_2_SECURE_HASH_ALGORITHM_3
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_2_SECURE_HASH_ALGORITHM_3 1
#endif

#ifdef __ARM_FEATURE_SVE2_SM4
#	undef XIEITE_EXTENSION_SCALABLE_VECTOR_2_SHANGMI_4
#	define XIEITE_EXTENSION_SCALABLE_VECTOR_2_SHANGMI_4 1
#endif

#ifdef __SHA__
#	undef XIEITE_EXTENSION_SECURE_HASH_ALGORITHM
#	define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM 1
#endif

#ifdef __ARM_FEATURE_SHA2
#	undef XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_2
#	define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_2 1
#endif

#ifdef __ARM_FEATURE_SHA3
#	undef XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_3
#	define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_3 1
#endif

#ifdef __ARM_FEATURE_SHA512
#	undef XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_512
#	define XIEITE_EXTENSION_SECURE_HASH_ALGORITHM_512 1
#endif

#ifdef __SHSTK__
#	undef XIEITE_EXTENSION_SHADOW_STACK
#	define XIEITE_EXTENSION_SHADOW_STACK 1
#endif

#ifdef __ARM_FEATURE_SM3
#	undef XIEITE_EXTENSION_SHANGMI_3
#	define XIEITE_EXTENSION_SHANGMI_3 1
#endif

#ifdef __ARM_FEATURE_SM4
#	undef XIEITE_EXTENSION_SHANGMI_4
#	define XIEITE_EXTENSION_SHANGMI_4 1
#endif

#if defined(__SSE__) || defined(_M_IX86_FP) && (_M_IX86_FP >= 1)
#	undef XIEITE_EXTENSION_STREAMING
#	define XIEITE_EXTENSION_STREAMING 1
#endif

#if defined(__SSE2__) || defined(_M_IX86_FP) && (_M_IX86_FP >= 2)
#	undef XIEITE_EXTENSION_STREAMING_2
#	define XIEITE_EXTENSION_STREAMING_2 1
#endif

#ifdef __SSE3__
#	undef XIEITE_EXTENSION_STREAMING_3
#	define XIEITE_EXTENSION_STREAMING_3 1
#endif

#ifdef __SSSE3__
#	undef XIEITE_EXTENSION_SUPPLEMENTAL_STREAMING_3
#	define XIEITE_EXTENSION_SUPPLEMENTAL_STREAMING_3 1
#endif

#ifdef __SSE4_1__
#	undef XIEITE_EXTENSION_STREAMING_4_1
#	define XIEITE_EXTENSION_STREAMING_4_1 1
#endif

#ifdef __SSE4_2__
#	undef XIEITE_EXTENSION_STREAMING_4_2
#	define XIEITE_EXTENSION_STREAMING_4_2 1
#endif

#ifdef __ARM_FEATURE_TME
#	undef XIEITE_EXTENSION_TRACED_MEMORY_EXECUTION
#	define XIEITE_EXTENSION_TRACED_MEMORY_EXECUTION 1
#endif

#ifdef __WAITPKG__
#	undef XIEITE_EXTENSION_USER_LEVEL_MONITOR_WAIT
#	define XIEITE_EXTENSION_USER_LEVEL_MONITOR_WAIT 1
#endif

#ifdef __WBNOINVD__
#	undef XIEITE_EXTENSION_WRITE_BACK_NO_INVALIDATE
#	define XIEITE_EXTENSION_WRITE_BACK_NO_INVALIDATE 1
#endif

// https://www.felixcloutier.com/x86/
// https://docs.kernel.org/next/x86/shstk.html
// https://github.com/GPUOpen-Drivers/llvm-project/blob/bbf7626bacd5f4f420008876864d02bf87fe323a/clang/lib/Headers/immintrin.h
