#pragma once

#define XIEITE_EXTENSION_ADVANCED_VECTOR 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_2 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_BYTE_WORD 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_CONFLICT_DETECTION 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_DOUBLEWORD_QUADWORD 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_EXPONENTIAL_RECIPROCAL 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_FOUNDATION 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_PREFETCH 0
#define XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_LENGTH 0
#define XIEITE_EXTENSION_HARD_FLOAT 0
#define XIEITE_EXTENSION_NEON 0
#define XIEITE_EXTENSION_STREAMING 0
#define XIEITE_EXTENSION_STREAMING_2 0
#define XIEITE_EXTENSION_STREAMING_3 0
#define XIEITE_EXTENSION_SUPPLEMENTAL_STREAMING_3 0
#define XIEITE_EXTENSION_STREAMING_4_1 0
#define XIEITE_EXTENSION_STREAMING_4_2 0

#ifdef __AVX__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR
#	define XIEITE_EXTENSION_ADVANCED_VECTOR 1
#endif

#ifdef __AVX2__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_2
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_2 1
#endif

#ifdef __AVX512BW__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_BYTE_WORD
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_BYTE_WORD 1
#endif

#ifdef __AVX512CD__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_CONFLICT_DETECTION
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_CONFLICT_DETECTION 1
#endif

#ifdef __AVX512DQ__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_DOUBLEWORD_QUADWORD
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_DOUBLEWORD_QUADWORD 1
#endif

#ifdef __AVX512ER__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_EXPONENTIAL_RECIPROCAL
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_EXPONENTIAL_RECIPROCAL 1
#endif

#ifdef __AVX512F__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_FOUNDATION
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_FOUNDATION 1
#endif

#ifdef __AVX512PF__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_PREFETCH
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_PREFETCH 1
#endif

#ifdef __AVX512VL__
#	undef XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_LENGTH
#	define XIEITE_EXTENSION_ADVANCED_VECTOR_512_VECTOR_LENGTH 1
#endif

#if defined(__ARM_PCS_VFP) || defined(__mips_hard_float) || defined(UNDER_RT) || defined(DART_RUN_IN_QEMU_ARMv7) || defined(XP_IOS)
#	undef XIEITE_EXTENSION_HARD_FLOAT
#	define XIEITE_EXTENSION_HARD_FLOAT 1
#endif

#if defined(__ARM_NEON) || defined(__ARM_NEON__)
#	undef XIEITE_EXTENSION_NEON
#	define XIEITE_EXTENSION_NEON 1
#endif

#if defined(__SSE__) || defined(_M_IX86_FP) && (_M_IX86_FP >= 1)
#	undef XIEITE_EXTENSION_STREAMING
#	define XIEITE_EXTENSION_STREAMING 1
#endif

#if defined(__SSE2__) || defined(_M_IX86_FP) && (_M_IX86_FP >= 2)
#	undef XIEITE_EXTENSION_STREAMING_2
#	define XIEITE_EXTENSION_STREAMING_2 1
#endif

#ifdef __SSE3__
#	undef XIEITE_EXTENSION_STREAMING_3
#	define XIEITE_EXTENSION_STREAMING_3 1
#endif

#ifdef __SSSE3__
#	undef XIEITE_EXTENSION_SUPPLEMENTAL_STREAMING_3
#	define XIEITE_EXTENSION_SUPPLEMENTAL_STREAMING_3 1
#endif

#ifdef __SSE4_1__
#	undef XIEITE_EXTENSION_STREAMING_4_1
#	define XIEITE_EXTENSION_STREAMING_4_1 1
#endif

#ifdef __SSE4_2__
#	undef XIEITE_EXTENSION_STREAMING_4_2
#	define XIEITE_EXTENSION_STREAMING_4_2 1
#endif

// Mostly stolen from Ian (https://github.com/Rinzii)
