#pragma once

#include <xieite/compiler.hpp>
#include <xieite/language_standard.hpp>

#if XIEITE_LANGUAGE_STANDARD_CPP_2011
#	include <cstdint>
#else
#	include <stdint.h>
#endif

#define XIEITE_FEATURE_SIGNED_8 0
#define XIEITE_FEATURE_UNSIGNED_8 0
#define XIEITE_FEATURE_SIGNED_16 0
#define XIEITE_FEATURE_UNSIGNED_16 0
#define XIEITE_FEATURE_SIGNED_32 0
#define XIEITE_FEATURE_UNSIGNED_32 0
#define XIEITE_FEATURE_SIGNED_64 0
#define XIEITE_FEATURE_UNSIGNED_64 0
#define XIEITE_FEATURE_SIGNED_128 0
#define XIEITE_FEATURE_UNSIGNED_128 0
#define XIEITE_FEATURE_FLOAT_16 0
#define XIEITE_FEATURE_FLOAT_32 0
#define XIEITE_FEATURE_FLOAT_64 0
#define XIEITE_FEATURE_FLOAT_128 0
#define XIEITE_FEATURE_FLOAT_BRAIN 0
#define XIEITE_FEATURE_BASED_POINTER 0

#ifdef UINT8_MAX
#	undef XIEITE_FEATURE_UNSIGNED_8
#	define XIEITE_FEATURE_UNSIGNED_8 1
#endif

#ifdef INT8_MAX
#	undef XIEITE_FEATURE_SIGNED_8
#	define XIEITE_FEATURE_SIGNED_8 1
#endif

#ifdef UINT16_MAX
#	undef XIEITE_FEATURE_UNSIGNED_16
#	define XIEITE_FEATURE_UNSIGNED_16 1
#endif

#ifdef INT16_MAX
#	undef XIEITE_FEATURE_SIGNED_16
#	define XIEITE_FEATURE_SIGNED_16 1
#endif

#ifdef UINT32_MAX
#	undef XIEITE_FEATURE_UNSIGNED_32
#	define XIEITE_FEATURE_UNSIGNED_32 1
#endif

#ifdef INT32_MAX
#	undef XIEITE_FEATURE_SIGNED_32
#	define XIEITE_FEATURE_SIGNED_32 1
#endif

#ifdef UINT64_MAX
#	undef XIEITE_FEATURE_UNSIGNED_64
#	define XIEITE_FEATURE_UNSIGNED_64 1
#endif

#ifdef INT64_MAX
#	undef XIEITE_FEATURE_SIGNED_64
#	define XIEITE_FEATURE_SIGNED_64 1
#endif

#if defined(__SIZEOF_INT128__) || __has_include(<__msvc_int128.hpp>)
#	undef XIEITE_FEATURE_UNSIGNED_128
#	define XIEITE_FEATURE_UNSIGNED_128 1
#	undef XIEITE_FEATURE_SIGNED_128
#	define XIEITE_FEATURE_SIGNED_128 1
#endif

#ifdef __STDCPP_FLOAT16_T__
#	undef XIEITE_FEATURE_FLOAT_16
#	define XIEITE_FEATURE_FLOAT_16 1
#endif

#ifdef __STDCPP_FLOAT32_T__
#	undef XIEITE_FEATURE_FLOAT_32
#	define XIEITE_FEATURE_FLOAT_32 1
#endif

#ifdef __STDCPP_FLOAT64_T__
#	undef XIEITE_FEATURE_FLOAT_64
#	define XIEITE_FEATURE_FLOAT_64 1
#endif

#ifdef __STDCPP_FLOAT128_T__
#	undef XIEITE_FEATURE_FLOAT_128
#	define XIEITE_FEATURE_FLOAT_128 1
#endif

#ifdef __STDCPP_BFLOAT16_T__
#	undef XIEITE_FEATURE_FLOAT_BRAIN
#	define XIEITE_FEATURE_FLOAT_BRAIN 1
#endif

#if XIEITE_COMPILER_TYPE_MSVC
#	undef XIEITE_FEATURE_BASED_POINTER
#	define XIEITE_FEATURE_BASED_POINTER 1
#endif
