#pragma once
#include <xieite/geometry/Circle.hpp>
#include <xieite/geometry/Ellipse.hpp>
#include <xieite/geometry/Line.hpp>
#include <xieite/geometry/Point.hpp>
#include <xieite/geometry/Polygon.hpp>
#include <xieite/geometry/Ray.hpp>
#include <xieite/geometry/Segment.hpp>
#include <xieite/geometry/containsPoint.hpp>
#include <xieite/geometry/getAngle.hpp>
#include <xieite/geometry/getArea.hpp>
#include <xieite/geometry/getBoundingBox.hpp>
#include <xieite/geometry/getCircumference.hpp>
#include <xieite/geometry/getDistance.hpp>
#include <xieite/geometry/getInterceptX.hpp>
#include <xieite/geometry/getInterceptY.hpp>
#include <xieite/geometry/getIntersection.hpp>
#include <xieite/geometry/getIntersections.hpp>
#include <xieite/geometry/getLength.hpp>
#include <xieite/geometry/getPerimeter.hpp>
#include <xieite/geometry/getSides.hpp>
#include <xieite/geometry/getSlope.hpp>
#include <xieite/geometry/rotate.hpp>
