#pragma once
#include <xieite/gometry/Circle.hpp>
#include <xieite/gometry/Ellipse.hpp>
#include <xieite/gometry/Line.hpp>
#include <xieite/gometry/Point.hpp>
#include <xieite/gometry/Polygon.hpp>
#include <xieite/gometry/Ray.hpp>
#include <xieite/gometry/Segment.hpp>
#include <xieite/gometry/containsPoint.hpp>
#include <xieite/gometry/getAngle.hpp>
#include <xieite/gometry/getArea.hpp>
#include <xieite/gometry/getBoundingBox.hpp>
#include <xieite/gometry/getCircumference.hpp>
#include <xieite/gometry/getDistance.hpp>
#include <xieite/gometry/getIntersection.hpp>
#include <xieite/gometry/getLength.hpp>
#include <xieite/gometry/getPerimeter.hpp>
#include <xieite/gometry/getSides.hpp>
#include <xieite/gometry/getSlope.hpp>
#include <xieite/gometry/rotate.hpp>
