#pragma once

#include <xieite/macros/ARCHITECTURE_TYPE.hpp>
#include <xieite/macros/ASSERT.hpp>
#include <xieite/macros/COMPILER_TYPE.hpp>
#include <xieite/macros/COMPILER_VERSION.hpp>
#include <xieite/macros/CONCATENATE.hpp>
#include <xieite/macros/DEFER.hpp>
#include <xieite/macros/EMPTY.hpp>
#include <xieite/macros/LOOP.hpp>
#include <xieite/macros/MATRIX.hpp>
#include <xieite/macros/OBSTRUCT.hpp>
#include <xieite/macros/REPEAT_CONCATENATE.hpp>
#include <xieite/macros/REPEAT.hpp>
#include <xieite/macros/SCAN.hpp>
#include <xieite/macros/STANDARD_LANGUAGE.hpp>
#include <xieite/macros/STANDARD_UNIX.hpp>
#include <xieite/macros/STRINGIFY.hpp>
#include <xieite/macros/SYSTEM_TYPE.hpp>
#include <xieite/macros/THIEF.hpp>
#include <xieite/macros/UNIQUE_TOKEN.hpp>
#include <xieite/macros/VANISH.hpp>
#include <xieite/macros/VERSION.hpp>
