#ifndef XIEITE_HEADER__MACROS
#	define XIEITE_HEADER__MACROS

#	include "./macros/ARCHITECTURE_TYPE.hpp"
#	include "./macros/ASCII_SUPPORT.hpp"
#	include "./macros/COMPILER_TYPE.hpp"
#	include "./macros/COMPILER_VERSION.hpp"
#	include "./macros/CONCATENATE.hpp"
#	include "./macros/CONSUME.hpp"
#	include "./macros/DEFER.hpp"
#	include "./macros/EMPTY.hpp"
#	include "./macros/FORCE_INLINE.hpp"
#	include "./macros/FUNCTION_SIGNATURE.hpp"
#	include "./macros/LOOP.hpp"
#	include "./macros/MATRIX.hpp"
#	include "./macros/NO_RETURN.hpp"
#	include "./macros/OBSTRUCT.hpp"
#	include "./macros/PACKED.hpp"
#	include "./macros/REPEAT.hpp"
#	include "./macros/REPEAT_CONCATENATE.hpp"
#	include "./macros/RESTRICT.hpp"
#	include "./macros/SCAN.hpp"
#	include "./macros/STANDARD_LANGUAGE.hpp"
#	include "./macros/STANDARD_UNIX.hpp"
#	include "./macros/STRINGIFY.hpp"
#	include "./macros/STRUCTURE_UUID.hpp"
#	include "./macros/SYSTEM_TYPE.hpp"
#	include "./macros/UNIQUE_TOKEN.hpp"
#	include "./macros/UNREACHABLE.hpp"
#	include "./macros/VANISH.hpp"
#	include "./macros/VERSION.hpp"

#endif
