#ifndef XIEITE_HEADER__MATH
#	define XIEITE_HEADER__MATH

#	include "./math/AttemptSign.hpp"
#	include "./math/AttemptUnsign.hpp"
#	include "./math/BigInteger.hpp"
#	include "./math/ConditionalSign.hpp"
#	include "./math/Interval.hpp"
#	include "./math/MinimalInteger.hpp"
#	include "./math/Result.hpp"
#	include "./math/absolute.hpp"
#	include "./math/almostEqual.hpp"
#	include "./math/almostEqualSlope.hpp"
#	include "./math/alternatingBits.hpp"
#	include "./math/baseFrom.hpp"
#	include "./math/baseTo.hpp"
#	include "./math/closestTo.hpp"
#	include "./math/cosecant.hpp"
#	include "./math/cotangent.hpp"
#	include "./math/difference.hpp"
#	include "./math/digits.hpp"
#	include "./math/farthestFrom.hpp"
#	include "./math/generatePi.hpp"
#	include "./math/isPowerOf2.hpp"
#	include "./math/isPrime.hpp"
#	include "./math/logarithm.hpp"
#	include "./math/mergeIntervals.hpp"
#	include "./math/pi.hpp"
#	include "./math/reverse.hpp"
#	include "./math/robert.hpp"
#	include "./math/secant.hpp"
#	include "./math/tau.hpp"
#	include "./math/toDegrees.hpp"
#	include "./math/toRadians.hpp"
#	include "./math/wrap.hpp"
#	include "./math/xorShift.hpp"

#endif
