#pragma once

#include <xieite/terminal/ModeLock.hpp>
#include <xieite/terminal/Position.hpp>
#include <xieite/terminal/clearLine.hpp>
#include <xieite/terminal/clearScreen.hpp>
#include <xieite/terminal/getCharacter.hpp>
#include <xieite/terminal/getCursorPosition.hpp>
#include <xieite/terminal/getString.hpp>
#include <xieite/terminal/getWindowSize.hpp>
#include <xieite/terminal/putBackString.hpp>
#include <xieite/terminal/resetStyle.hpp>
#include <xieite/terminal/setCursorAlternative.hpp>
#include <xieite/terminal/setScreenAlternative.hpp>
#include <xieite/terminal/setColorBackground.hpp>
#include <xieite/terminal/setColorDim.hpp>
#include <xieite/terminal/setColorForeground.hpp>
#include <xieite/terminal/setColorInversion.hpp>
#include <xieite/terminal/setCursorPosition.hpp>
#include <xieite/terminal/setCursorVisibility.hpp>
#include <xieite/terminal/setTextBlink.hpp>
#include <xieite/terminal/setTextBold.hpp>
#include <xieite/terminal/setTextItalic.hpp>
#include <xieite/terminal/setTextStrikethrough.hpp>
#include <xieite/terminal/setTextUnderline.hpp>
#include <xieite/terminal/setTextVisibility.hpp>
