#ifndef XIEITE_HEADER__TRAITS
#	define XIEITE_HEADER__TRAITS

#	include "./traits/is_all_of.hpp"
#	include "./traits/is_any_of.hpp"
#	include "./traits/is_bitset_reference.hpp"
#	include "./traits/is_character.hpp"
#	include "./traits/is_convertible_to_all_of.hpp"
#	include "./traits/is_convertible_to_any_of.hpp"
#	include "./traits/is_decayed.hpp"
#	include "./traits/is_derivable.hpp"
#	include "./traits/is_derived_from_all_of.hpp"
#	include "./traits/is_derived_from_any_of.hpp"
#	include "./traits/is_functable.hpp"
#	include "./traits/is_hashable.hpp"
#	include "./traits/is_hasher.hpp"
#	include "./traits/is_integer.hpp"
#	include "./traits/is_linear_shape.hpp"
#	include "./traits/is_narrow_character.hpp"
#	include "./traits/is_no_throw_convertible_to_all_of.hpp"
#	include "./traits/is_no_throw_convertible_to_any_of.hpp"
#	include "./traits/is_numeric.hpp"
#	include "./traits/is_ordinary_character.hpp"
#	include "./traits/is_range_of.hpp"
#	include "./traits/is_same_as_all_of.hpp"
#	include "./traits/is_same_as_any_of.hpp"
#	include "./traits/is_streamable_in.hpp"
#	include "./traits/is_streamable_out.hpp"
#	include "./traits/is_temporal_duration.hpp"
#	include "./traits/is_uniform_random_bit_generator.hpp"
#	include "./traits/is_unsigned_integer.hpp"
#	include "./traits/is_wide_character.hpp"

#endif
