#pragma once

#include <xieite/cat.hpp>

#define XIEITE_UNWRAP(x) XIEITE_CAT(XIEITE_DETAIL_UNWRAP_, XIEITE_DETAIL_UNWRAP x)

#define XIEITE_DETAIL_UNWRAP(...) XIEITE_DETAIL_UNWRAP __VA_ARGS__
#define XIEITE_DETAIL_UNWRAP_XIEITE_DETAIL_UNWRAP
