#pragma once

#include <xieite/architecture.hpp>

#if XIEITE_ARCHITECTURE_TYPE_AARCH64 || XIEITE_ARCHITECTURE_TYPE_ALPHA || XIEITE_ARCHITECTURE_TYPE_CONVEX || XIEITE_ARCHITECTURE_TYPE_EPIPHANY || XIEITE_ARCHITECTURE_TYPE_IBM_Z || XIEITE_ARCHITECTURE_TYPE_ITANIUM || XIEITE_ARCHITECTURE_LEAST(POWERPC, 620, 0, 0) || XIEITE_ARCHITECTURE_LEAST(SPARC, 9, 0, 0) || XIEITE_ARCHITECTURE_TYPE_X86_64
#	define XIEITE_WORD_BITS 64
#elif XIEITE_ARCHITECTURE_TYPE_ARM || XIEITE_ARCHITECTURE_TYPE_MIPS || XIEITE_ARCHITECTURE_TYPE_MOTOROLA_68000 || XIEITE_ARCHITECTURE_TYPE_PA_RISC || XIEITE_ARCHITECTURE_TYPE_PYRAMID_9810 || XIEITE_ARCHITECTURE_TYPE_RS_6000 || XIEITE_ARCHITECTURE_MOST(SPARC, 8, 0, 0) || XIEITE_ARCHITECTURE_TYPE_SUPERH || XIEITE_ARCHITECTURE_LEAST(TMS320, 5400, 0, 0) || XIEITE_ARCHITECTURE_TYPE_TMS470 || XIEITE_ARCHITECTURE_TYPE_X86_32
#	define XIEITE_WORD_BITS 32
#elif XIEITE_ARCHITECTURE_TYPE_BLACKFIN || XIEITE_ARCHITECTURE_MOST(TMS320, 2800, 0, 0)
#	define XIEITE_WORD_BITS 16
#else
#	define XIEITE_WORD_BITS 8
#endif
