#pragma once

#include "../pp/eat.hpp"
#include "../pp/paren.hpp"
#include "../pp/scan.hpp"

#define X4CM(...) X4SCAN(X4EAT X4LPAREN() DETAIL_X4CMNEXT0(__VA_ARGS__))

#define DETAIL_X4CMNEXT0(P, m, ...) DETAIL_X4CMPASS1(DETAIL_X4CMPASS1(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT1(P, m, ...) DETAIL_X4CMPASS2(DETAIL_X4CMPASS2(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT2(P, m, ...) DETAIL_X4CMPASS3(DETAIL_X4CMPASS3(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT3(P, m, ...) DETAIL_X4CMPASS4(DETAIL_X4CMPASS4(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT4(P, m, ...) DETAIL_X4CMPASS5(DETAIL_X4CMPASS5(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT5(P, m, ...) DETAIL_X4CMPASS6(DETAIL_X4CMPASS6(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT6(P, m, ...) DETAIL_X4CMPASS7(DETAIL_X4CMPASS7(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT7(P, m, ...) DETAIL_X4CMPASS8(DETAIL_X4CMPASS8(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT8(P, m, ...) DETAIL_X4CMPASS9(DETAIL_X4CMPASS9(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXT9(P, m, ...) DETAIL_X4CMPASSA(DETAIL_X4CMPASSA(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXTA(P, m, ...) DETAIL_X4CMPASSB(DETAIL_X4CMPASSB(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXTB(P, m, ...) DETAIL_X4CMPASSC(DETAIL_X4CMPASSC(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXTC(P, m, ...) DETAIL_X4CMPASSD(DETAIL_X4CMPASSD(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXTD(P, m, ...) DETAIL_X4CMPASSE(DETAIL_X4CMPASSE(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXTE(P, m, ...) DETAIL_X4CMPASSF(DETAIL_X4CMPASSF(X4CMFN_##m(, P##__VA_ARGS__)))
#define DETAIL_X4CMNEXTF(P, m, ...) X4CMFN_##m(, P##__VA_ARGS__)
#define DETAIL_X4CMPASS1(x) DETAIL_X4CMNEXT1 x
#define DETAIL_X4CMPASS2(x) DETAIL_X4CMNEXT2 x
#define DETAIL_X4CMPASS3(x) DETAIL_X4CMNEXT3 x
#define DETAIL_X4CMPASS4(x) DETAIL_X4CMNEXT4 x
#define DETAIL_X4CMPASS5(x) DETAIL_X4CMNEXT5 x
#define DETAIL_X4CMPASS6(x) DETAIL_X4CMNEXT6 x
#define DETAIL_X4CMPASS7(x) DETAIL_X4CMNEXT7 x
#define DETAIL_X4CMPASS8(x) DETAIL_X4CMNEXT8 x
#define DETAIL_X4CMPASS9(x) DETAIL_X4CMNEXT9 x
#define DETAIL_X4CMPASSA(x) DETAIL_X4CMNEXTA x
#define DETAIL_X4CMPASSB(x) DETAIL_X4CMNEXTB x
#define DETAIL_X4CMPASSC(x) DETAIL_X4CMNEXTC x
#define DETAIL_X4CMPASSD(x) DETAIL_X4CMNEXTD x
#define DETAIL_X4CMPASSE(x) DETAIL_X4CMNEXTE x
#define DETAIL_X4CMPASSF(x) DETAIL_X4CMNEXTF x
