#pragma once

#define X4CPLR_ACC 0
#define X4CPLRMAJOR_ACC 0
#define X4CPLRMINOR_ACC 0
#define X4CPLRPATCH_ACC 0
#define X4CPLR_ACK 0
#define X4CPLRMAJOR_ACK 0
#define X4CPLRMINOR_ACK 0
#define X4CPLRPATCH_ACK 0
#define X4CPLR_ALTIUM_C_TO_HARDWARE 0
#define X4CPLRMAJOR_ALTIUM_C_TO_HARDWARE 0
#define X4CPLRMINOR_ALTIUM_C_TO_HARDWARE 0
#define X4CPLRPATCH_ALTIUM_C_TO_HARDWARE 0
#define X4CPLR_ALTIUM_MICROBLAZE_C 0
#define X4CPLRMAJOR_ALTIUM_MICROBLAZE_C 0
#define X4CPLRMINOR_ALTIUM_MICROBLAZE_C 0
#define X4CPLRPATCH_ALTIUM_MICROBLAZE_C 0
#define X4CPLR_AOCC 0
#define X4CPLRMAJOR_AOCC 0
#define X4CPLRMINOR_AOCC 0
#define X4CPLRPATCH_AOCC 0
#define X4CPLR_ARMCC 0
#define X4CPLRMAJOR_ARMCC 0
#define X4CPLRMINOR_ARMCC 0
#define X4CPLRPATCH_ARMCC 0
#define X4CPLR_AZTEC_C 0
#define X4CPLRMAJOR_AZTEC_C 0
#define X4CPLRMINOR_AZTEC_C 0
#define X4CPLRPATCH_AZTEC_C 0
#define X4CPLR_BORLAND 0
#define X4CPLRMAJOR_BORLAND 0
#define X4CPLRMINOR_BORLAND 0
#define X4CPLRPATCH_BORLAND 0
#define X4CPLR_CC65 0
#define X4CPLRMAJOR_CC65 0
#define X4CPLRMINOR_CC65 0
#define X4CPLRPATCH_CC65 0
#define X4CPLR_CIRCLE 0
#define X4CPLRMAJOR_CIRCLE 0
#define X4CPLRMINOR_CIRCLE 0
#define X4CPLRPATCH_CIRCLE 0
#define X4CPLR_CLANG 0
#define X4CPLRMAJOR_CLANG 0
#define X4CPLRMINOR_CLANG 0
#define X4CPLRPATCH_CLANG 0
#define X4CPLR_COMEAU 0
#define X4CPLRMAJOR_COMEAU 0
#define X4CPLRMINOR_COMEAU 0
#define X4CPLRPATCH_COMEAU 0
#define X4CPLR_COMPAQ_C 0
#define X4CPLRMAJOR_COMPAQ_C 0
#define X4CPLRMINOR_COMPAQ_C 0
#define X4CPLRPATCH_COMPAQ_C 0
#define X4CPLR_COMPAQ_CPP 0
#define X4CPLRMAJOR_COMPAQ_CPP 0
#define X4CPLRMINOR_COMPAQ_CPP 0
#define X4CPLRPATCH_COMPAQ_CPP 0
#define X4CPLR_COMPCERT 0
#define X4CPLRMAJOR_COMPCERT 0
#define X4CPLRMINOR_COMPCERT 0
#define X4CPLRPATCH_COMPCERT 0
#define X4CPLR_CONVEX_C 0
#define X4CPLRMAJOR_CONVEX_C 0
#define X4CPLRMINOR_CONVEX_C 0
#define X4CPLRPATCH_CONVEX_C 0
#define X4CPLR_COVERITY_STATIC_ANALYZER 0
#define X4CPLRMAJOR_COVERITY_STATIC_ANALYZER 0
#define X4CPLRMINOR_COVERITY_STATIC_ANALYZER 0
#define X4CPLRPATCH_COVERITY_STATIC_ANALYZER 0
#define X4CPLR_CRAY 0
#define X4CPLRMAJOR_CRAY 0
#define X4CPLRMINOR_CRAY 0
#define X4CPLRPATCH_CRAY 0
#define X4CPLR_DIGITAL_MARS 0
#define X4CPLRMAJOR_DIGITAL_MARS 0
#define X4CPLRMINOR_DIGITAL_MARS 0
#define X4CPLRPATCH_DIGITAL_MARS 0
#define X4CPLR_DICE_C 0
#define X4CPLRMAJOR_DICE_C 0
#define X4CPLRMINOR_DICE_C 0
#define X4CPLRPATCH_DICE_C 0
#define X4CPLR_DIGNUS_SYSTEMS_CPP 0
#define X4CPLRMAJOR_DIGNUS_SYSTEMS_CPP 0
#define X4CPLRMINOR_DIGNUS_SYSTEMS_CPP 0
#define X4CPLRPATCH_DIGNUS_SYSTEMS_CPP 0
#define X4CPLR_DJGPP 0
#define X4CPLRMAJOR_DJGPP 0
#define X4CPLRMINOR_DJGPP 0
#define X4CPLRPATCH_DJGPP 0
#define X4CPLR_EDG 0
#define X4CPLRMAJOR_EDG 0
#define X4CPLRMINOR_EDG 0
#define X4CPLRPATCH_EDG 0
#define X4CPLR_EKOPATH 0
#define X4CPLRMAJOR_EKOPATH 0
#define X4CPLRMINOR_EKOPATH 0
#define X4CPLRPATCH_EKOPATH 0
#define X4CPLR_ELLCC 0
#define X4CPLRMAJOR_ELLCC 0
#define X4CPLRMINOR_ELLCC 0
#define X4CPLRPATCH_ELLCC 0
#define X4CPLR_EMSCRIPTEN 0
#define X4CPLRMAJOR_EMSCRIPTEN 0
#define X4CPLRMINOR_EMSCRIPTEN 0
#define X4CPLRPATCH_EMSCRIPTEN 0
#define X4CPLR_FUJITSU_CPP 0
#define X4CPLRMAJOR_FUJITSU_CPP 0
#define X4CPLRMINOR_FUJITSU_CPP 0
#define X4CPLRPATCH_FUJITSU_CPP 0
#define X4CPLR_GCC 0
#define X4CPLRMAJOR_GCC 0
#define X4CPLRMINOR_GCC 0
#define X4CPLRPATCH_GCC 0
#define X4CPLR_GCC_XML 0
#define X4CPLRMAJOR_GCC_XML 0
#define X4CPLRMINOR_GCC_XML 0
#define X4CPLRPATCH_GCC_XML 0
#define X4CPLR_GREEN_HILLS 0
#define X4CPLRMAJOR_GREEN_HILLS 0
#define X4CPLRMINOR_GREEN_HILLS 0
#define X4CPLRPATCH_GREEN_HILLS 0
#define X4CPLR_HEXAGON 0
#define X4CPLRMAJOR_HEXAGON 0
#define X4CPLRMINOR_HEXAGON 0
#define X4CPLRPATCH_HEXAGON 0
#define X4CPLR_HIPCC 0
#define X4CPLRMAJOR_HIPCC 0
#define X4CPLRMINOR_HIPCC 0
#define X4CPLRPATCH_HIPCC 0
#define X4CPLR_HP_ACC 0
#define X4CPLRMAJOR_HP_ACC 0
#define X4CPLRMINOR_HP_ACC 0
#define X4CPLRPATCH_HP_ACC 0
#define X4CPLR_HP_ANSI_C 0
#define X4CPLRMAJOR_HP_ANSI_C 0
#define X4CPLRMINOR_HP_ANSI_C 0
#define X4CPLRPATCH_HP_ANSI_C 0
#define X4CPLR_IAR 0
#define X4CPLRMAJOR_IAR 0
#define X4CPLRMINOR_IAR 0
#define X4CPLRPATCH_IAR 0
#define X4CPLR_ICC 0
#define X4CPLRMAJOR_ICC 0
#define X4CPLRMINOR_ICC 0
#define X4CPLRPATCH_ICC 0
#define X4CPLR_ICX 0
#define X4CPLRMAJOR_ICX 0
#define X4CPLRMINOR_ICX 0
#define X4CPLRPATCH_ICX 0
#define X4CPLR_IMAGECRAFT_C 0
#define X4CPLRMAJOR_IMAGECRAFT_C 0
#define X4CPLRMINOR_IMAGECRAFT_C 0
#define X4CPLRPATCH_IMAGECRAFT_C 0
#define X4CPLR_KCC 0
#define X4CPLRMAJOR_KCC 0
#define X4CPLRMINOR_KCC 0
#define X4CPLRPATCH_KCC 0
#define X4CPLR_KEIL_C166 0
#define X4CPLRMAJOR_KEIL_C166 0
#define X4CPLRMINOR_KEIL_C166 0
#define X4CPLRPATCH_KEIL_C166 0
#define X4CPLR_KEIL_C51 0
#define X4CPLRMAJOR_KEIL_C51 0
#define X4CPLRMINOR_KEIL_C51 0
#define X4CPLRPATCH_KEIL_C51 0
#define X4CPLR_KEIL_CARM 0
#define X4CPLRMAJOR_KEIL_CARM 0
#define X4CPLRMINOR_KEIL_CARM 0
#define X4CPLRPATCH_KEIL_CARM 0
#define X4CPLR_LATTICE_C 0
#define X4CPLRMAJOR_LATTICE_C 0
#define X4CPLRMINOR_LATTICE_C 0
#define X4CPLRPATCH_LATTICE_C 0
#define X4CPLR_LCC 0
#define X4CPLRMAJOR_LCC 0
#define X4CPLRMINOR_LCC 0
#define X4CPLRPATCH_LCC 0
#define X4CPLR_LIGHTSPEED_C 0
#define X4CPLRMAJOR_LIGHTSPEED_C 0
#define X4CPLRMINOR_LIGHTSPEED_C 0
#define X4CPLRPATCH_LIGHTSPEED_C 0
#define X4CPLR_LLVM 0
#define X4CPLRMAJOR_LLVM 0
#define X4CPLRMINOR_LLVM 0
#define X4CPLRPATCH_LLVM 0
#define X4CPLR_METAWARE_HIGH 0
#define X4CPLRMAJOR_METAWARE_HIGH 0
#define X4CPLRMINOR_METAWARE_HIGH 0
#define X4CPLRPATCH_METAWARE_HIGH 0
#define X4CPLR_METROWERKS_CODEWARRIOR 0
#define X4CPLRMAJOR_METROWERKS_CODEWARRIOR 0
#define X4CPLRMINOR_METROWERKS_CODEWARRIOR 0
#define X4CPLRPATCH_METROWERKS_CODEWARRIOR 0
#define X4CPLR_MICROTEC 0
#define X4CPLRMAJOR_MICROTEC 0
#define X4CPLRMINOR_MICROTEC 0
#define X4CPLRPATCH_MICROTEC 0
#define X4CPLR_MICROWAY_NDP_C 0
#define X4CPLRMAJOR_MICROWAY_NDP_C 0
#define X4CPLRMINOR_MICROWAY_NDP_C 0
#define X4CPLRPATCH_MICROWAY_NDP_C 0
#define X4CPLR_MINGW32 0
#define X4CPLRMAJOR_MINGW32 0
#define X4CPLRMINOR_MINGW32 0
#define X4CPLRPATCH_MINGW32 0
#define X4CPLR_MINGW_W64 0
#define X4CPLRMAJOR_MINGW_W64 0
#define X4CPLRMINOR_MINGW_W64 0
#define X4CPLRPATCH_MINGW_W64 0
#define X4CPLR_MIPSPRO 0
#define X4CPLRMAJOR_MIPSPRO 0
#define X4CPLRMINOR_MIPSPRO 0
#define X4CPLRPATCH_MIPSPRO 0
#define X4CPLR_MIRACLE_C 0
#define X4CPLRMAJOR_MIRACLE_C 0
#define X4CPLRMINOR_MIRACLE_C 0
#define X4CPLRPATCH_MIRACLE_C 0
#define X4CPLR_MPW 0
#define X4CPLRMAJOR_MPW 0
#define X4CPLRMINOR_MPW 0
#define X4CPLRPATCH_MPW 0
#define X4CPLR_MSVC 0
#define X4CPLRMAJOR_MSVC 0
#define X4CPLRMINOR_MSVC 0
#define X4CPLRPATCH_MSVC 0
#define X4CPLR_NORCROFT_C 0
#define X4CPLRMAJOR_NORCROFT_C 0
#define X4CPLRMINOR_NORCROFT_C 0
#define X4CPLRPATCH_NORCROFT_C 0
#define X4CPLR_NVIDIA_HPC 0
#define X4CPLRMAJOR_NVIDIA_HPC 0
#define X4CPLRMINOR_NVIDIA_HPC 0
#define X4CPLRPATCH_NVIDIA_HPC 0
#define X4CPLR_NVCC 0
#define X4CPLRMAJOR_NVCC 0
#define X4CPLRMINOR_NVCC 0
#define X4CPLRPATCH_NVCC 0
#define X4CPLR_NWCC 0
#define X4CPLRMAJOR_NWCC 0
#define X4CPLRMINOR_NWCC 0
#define X4CPLRPATCH_NWCC 0
#define X4CPLR_OPEN64 0
#define X4CPLRMAJOR_OPEN64 0
#define X4CPLRMINOR_OPEN64 0
#define X4CPLRPATCH_OPEN64 0
#define X4CPLR_OPENACC 0
#define X4CPLRMAJOR_OPENACC 0
#define X4CPLRMINOR_OPENACC 0
#define X4CPLRPATCH_OPENACC 0
#define X4CPLR_OPENSERVER 0
#define X4CPLRMAJOR_OPENSERVER 0
#define X4CPLRMINOR_OPENSERVER 0
#define X4CPLRPATCH_OPENSERVER 0
#define X4CPLR_PACIFIC_C 0
#define X4CPLRMAJOR_PACIFIC_C 0
#define X4CPLRMINOR_PACIFIC_C 0
#define X4CPLRPATCH_PACIFIC_C 0
#define X4CPLR_PALM 0
#define X4CPLRMAJOR_PALM 0
#define X4CPLRMINOR_PALM 0
#define X4CPLRPATCH_PALM 0
#define X4CPLR_PELLES_C 0
#define X4CPLRMAJOR_PELLES_C 0
#define X4CPLRMINOR_PELLES_C 0
#define X4CPLRPATCH_PELLES_C 0
#define X4CPLR_PGI 0
#define X4CPLRMAJOR_PGI 0
#define X4CPLRMINOR_PGI 0
#define X4CPLRPATCH_PGI 0
#define X4CPLR_PRO_C 0
#define X4CPLRMAJOR_PRO_C 0
#define X4CPLRMINOR_PRO_C 0
#define X4CPLRPATCH_PRO_C 0
#define X4CPLR_RENESAS 0
#define X4CPLRMAJOR_RENESAS 0
#define X4CPLRMINOR_RENESAS 0
#define X4CPLRPATCH_RENESAS 0
#define X4CPLR_SDCC 0
#define X4CPLRMAJOR_SDCC 0
#define X4CPLRMINOR_SDCC 0
#define X4CPLRPATCH_SDCC 0
#define X4CPLR_SNC 0
#define X4CPLRMAJOR_SNC 0
#define X4CPLRMINOR_SNC 0
#define X4CPLRPATCH_SNC 0
#define X4CPLR_STRATUS_VOS_C 0
#define X4CPLRMAJOR_STRATUS_VOS_C 0
#define X4CPLRMINOR_STRATUS_VOS_C 0
#define X4CPLRPATCH_STRATUS_VOS_C 0
#define X4CPLR_SUNPRO_C 0
#define X4CPLRMAJOR_SUNPRO_C 0
#define X4CPLRMINOR_SUNPRO_C 0
#define X4CPLRPATCH_SUNPRO_C 0
#define X4CPLR_SUNPRO_CPP 0
#define X4CPLRMAJOR_SUNPRO_CPP 0
#define X4CPLRMINOR_SUNPRO_CPP 0
#define X4CPLRPATCH_SUNPRO_CPP 0
#define X4CPLR_SYMANTEC_CPP 0
#define X4CPLRMAJOR_SYMANTEC_CPP 0
#define X4CPLRMINOR_SYMANTEC_CPP 0
#define X4CPLRPATCH_SYMANTEC_CPP 0
#define X4CPLR_TCC 0
#define X4CPLRMAJOR_TCC 0
#define X4CPLRMINOR_TCC 0
#define X4CPLRPATCH_TCC 0
#define X4CPLR_TENDRA 0
#define X4CPLRMAJOR_TENDRA 0
#define X4CPLRMINOR_TENDRA 0
#define X4CPLRPATCH_TENDRA 0
#define X4CPLR_TI_CGT 0
#define X4CPLRMAJOR_TI_CGT 0
#define X4CPLRMINOR_TI_CGT 0
#define X4CPLRPATCH_TI_CGT 0
#define X4CPLR_TI_CL430 0
#define X4CPLRMAJOR_TI_CL430 0
#define X4CPLRMINOR_TI_CL430 0
#define X4CPLRPATCH_TI_CL430 0
#define X4CPLR_TURBO 0
#define X4CPLRMAJOR_TURBO 0
#define X4CPLRMINOR_TURBO 0
#define X4CPLRPATCH_TURBO 0
#define X4CPLR_ULTIMATE 0
#define X4CPLRMAJOR_ULTIMATE 0
#define X4CPLRMINOR_ULTIMATE 0
#define X4CPLRPATCH_ULTIMATE 0
#define X4CPLR_USL_C 0
#define X4CPLRMAJOR_USL_C 0
#define X4CPLRMINOR_USL_C 0
#define X4CPLRPATCH_USL_C 0
#define X4CPLR_VBCC 0
#define X4CPLRMAJOR_VBCC 0
#define X4CPLRMINOR_VBCC 0
#define X4CPLRPATCH_VBCC 0
#define X4CPLR_WATCOM 0
#define X4CPLRMAJOR_WATCOM 0
#define X4CPLRMINOR_WATCOM 0
#define X4CPLRPATCH_WATCOM 0
#define X4CPLR_WIND_RIVER_DIAB 0
#define X4CPLRMAJOR_WIND_RIVER_DIAB 0
#define X4CPLRMINOR_WIND_RIVER_DIAB 0
#define X4CPLRPATCH_WIND_RIVER_DIAB 0
#define X4CPLR_XC8 0
#define X4CPLRMAJOR_XC8 0
#define X4CPLRMINOR_XC8 0
#define X4CPLRPATCH_XC8 0
#define X4CPLR_XC16 0
#define X4CPLRMAJOR_XC16 0
#define X4CPLRMINOR_XC16 0
#define X4CPLRPATCH_XC16 0
#define X4CPLR_XC32 0
#define X4CPLRMAJOR_XC32 0
#define X4CPLRMINOR_XC32 0
#define X4CPLRPATCH_XC32 0
#define X4CPLR_XC_DSC 0
#define X4CPLRMAJOR_XC_DSC 0
#define X4CPLRMINOR_XC_DSC 0
#define X4CPLRPATCH_XC_DSC 0
#define X4CPLR_XL 0
#define X4CPLRMAJOR_XL 0
#define X4CPLRMINOR_XL 0
#define X4CPLRPATCH_XL 0
#define X4CPLR_ZORTECH_CPP 0
#define X4CPLRMAJOR_ZORTECH_CPP 0
#define X4CPLRMINOR_ZORTECH_CPP 0
#define X4CPLRPATCH_ZORTECH_CPP 0
#define X4CPLR_Z88DK 0
#define X4CPLRMAJOR_Z88DK 0
#define X4CPLRMINOR_Z88DK 0
#define X4CPLRPATCH_Z88DK 0

#define X4CPLREQ(type, major, ...) DETAIL_X4CPLR(__VA_ARGS__, DETAIL_X4CPLREQ(type, major, __VA_ARGS__), DETAIL_X4CPLREQ(type, major, __VA_ARGS__, 0), DETAIL_X4CPLREQ(type, major, 0, 0))
#define X4CPLRLEAST(type, major, ...) DETAIL_X4CPLR(__VA_ARGS__, DETAIL_X4CPLRLEAST(type, major, __VA_ARGS__), DETAIL_X4CPLRLEAST(type, major, __VA_ARGS__, 0), DETAIL_X4CPLRLEAST(type, major, 0, 0))
#define X4CPLRMOST(type, major, ...) DETAIL_X4CPLR(__VA_ARGS__, DETAIL_X4CPLRMOST(type, major, __VA_ARGS__), DETAIL_X4CPLRMOST(type, major, __VA_ARGS__, 0), DETAIL_X4CPLRMOST(type, major, 0, 0))
#define DETAIL_X4CPLR(_0, _1, _2, x, ...) x
#define DETAIL_X4CPLREQ(type, major, minor, patch) (X4CPLR_##type && (X4CPLRMAJOR_##type == (major)) && (X4CPLRMINOR_##type == (minor)) && (X4CPLRPATCH_##type == (patch)))
#define DETAIL_X4CPLRLEAST(type, major, minor, patch) (X4CPLR_##type && ((X4CPLRMAJOR_##type > (major)) || (X4CPLRMAJOR_##type == (major)) && ((X4CPLRMINOR_##type > (minor)) || (X4CPLRMINOR_##type == (minor)) && (X4CPLRPATCH_##type >= (patch)))))
#define DETAIL_X4CPLRMOST(type, major, minor, patch) (X4CPLR_##type && ((X4CPLRMAJOR_##type < (major)) || (X4CPLRMAJOR_##type == (major)) && ((X4CPLRMINOR_##type < (minor)) || (X4CPLRMINOR_##type == (minor)) && (X4CPLRPATCH_##type <= (patch)))))

#ifdef _ACC_
#	undef X4CPLR_ACC
#	define X4CPLR_ACC 1

#	undef X4CPLRMAJOR_ACC
#	define X4CPLRMAJOR_ACC (__HP_aCC / 10000)

#	undef X4CPLRMINOR_ACC
#	define X4CPLRMINOR_ACC (__HP_aCC % 10000 / 100)

#	undef X4CPLRPATCH_ACC
#	define X4CPLRPATCH_ACC (__HP_aCC % 100)
#endif

#ifdef __ACK__
#	undef X4CPLR_ACK
#	define X4CPLR_ACK 1
#endif

#ifdef __CHC__
#	undef X4CPLR_ALTIUM_C_TO_HARDWARE
#	define X4CPLR_ALTIUM_C_TO_HARDWARE 1

#	undef X4CPLRMAJOR_ALTIUM_C_TO_HARDWARE
#	define X4CPLRMAJOR_ALTIUM_C_TO_HARDWARE (__VERSION___ / 1000)

#	undef X4CPLRMINOR_ALTIUM_C_TO_HARDWARE
#	define X4CPLRMINOR_ALTIUM_C_TO_HARDWARE (__VERSION___ % 1000)

#	undef X4CPLRPATCH_ALTIUM_C_TO_HARDWARE
#	define X4CPLRPATCH_ALTIUM_C_TO_HARDWARE __REVISION__
#endif

#ifdef __CMB__
#	undef X4CPLR_ALTIUM_MICROBLAZE_C
#	define X4CPLR_ALTIUM_MICROBLAZE_C 1

#	undef X4CPLRMAJOR_ALTIUM_MICROBLAZE_C
#	define X4CPLRMAJOR_ALTIUM_MICROBLAZE_C (__VERSION___ / 1000)

#	undef X4CPLRMINOR_ALTIUM_MICROBLAZE_C
#	define X4CPLRMINOR_ALTIUM_MICROBLAZE_C (__VERSION___ % 1000)

#	undef X4CPLRPATCH_ALTIUM_MICROBLAZE_C
#	define X4CPLRPATCH_ALTIUM_MICROBLAZE_C __REVISION__
#endif

#ifdef __aocc__
#	undef X4CPLR_AOCC
#	define X4CPLR_AOCC 1

#	ifdef __aocc_major__
#		undef X4CPLRMAJOR_AOCC
#		define X4CPLRMAJOR_AOCC __aocc_major__

#		undef X4CPLRMAJOR_AOCC
#		define X4CPLRMAJOR_AOCC __aocc_minor__

#		undef X4CPLRMAJOR_AOCC
#		define X4CPLRMAJOR_AOCC __aocc_patchlevel__
#	endif
#endif

#ifdef __CC_ARM
#	undef X4CPLR_ARMCC
#	define X4CPLR_ARMCC 1

#	undef X4CPLRMAJOR_ARMCC
#	define X4CPLRMAJOR_ARMCC (__ARMCC_VERSION / 100000)

#	undef X4CPLRMINOR_ARMCC
#	define X4CPLRMINOR_ARMCC (__ARMCC_VERSION % 100000 / 10000)

#	undef X4CPLRPATCH_ARMCC
#	define X4CPLRPATCH_ARMCC (__ARMCC_VERSION % 10000 / 1000)
#endif

#ifdef AZTEC_C
#	undef X4CPLR_AZTEC_C
#	define X4CPLR_AZTEC_C 1

#	undef X4CPLRMAJOR_AZTEC_C
#	define X4CPLRMAJOR_AZTEC_C (__VERSION / 100)

#	undef X4CPLRMINOR_AZTEC_C
#	define X4CPLRMINOR_AZTEC_C (__VERSION % 100)
#endif

#if defined(__BORLANDC__) || defined(__CODEGEARC__)
#	undef X4CPLR_BORLAND
#	define X4CPLR_BORLAND 1
#endif

#ifdef __CC65__
#	undef X4CPLR_CC65
#	define X4CPLR_CC65 1

#	undef X4CPLRMAJOR_CC65
#	define X4CPLRMAJOR_CC65 (__CC65__ / 0x100)

#	undef X4CPLRMINOR_CC65
#	define X4CPLRMINOR_CC65 (__CC65__ % 0x100 / 0x10)

#	undef X4CPLRPATCH_CC65
#	define X4CPLRPATCH_CC65 (__CC65__ % 0x10)
#endif

#if defined(__circle__) || defined(__circle_lang__) || defined(__circle_build__)
#	undef X4CPLR_CIRCLE
#	define X4CPLR_CIRCLE 1

#	undef X4CPLRMAJOR_CIRCLE
#	define X4CPLRMAJOR_CIRCLE (__circle__ / 10000)

#	undef X4CPLRMINOR_CIRCLE
#	define X4CPLRMINOR_CIRCLE (__circle__ % 10000 / 100)

#	undef X4CPLRPATCH_CIRCLE
#	define X4CPLRPATCH_CIRCLE (__circle__ % 100)
#endif

#ifdef __clang__
#	undef X4CPLR_CLANG
#	define X4CPLR_CLANG 1

#	undef X4CPLRMAJOR_CLANG
#	define X4CPLRMAJOR_CLANG __clang_major___

#	undef X4CPLRMINOR_CLANG
#	define X4CPLRMINOR_CLANG __clang_minor___

#	undef X4CPLRPATCH_CLANG
#	define X4CPLRPATCH_CLANG __clang_patchlevel__
#endif

#if defined(__CWCC__) || defined(__MWERKS__)
#	undef X4CPLR_METROWERKS_CODEWARRIOR
#	define X4CPLR_METROWERKS_CODEWARRIOR 1

#	undef X4CPLRMAJOR_METROWERKS_CODEWARRIOR
#	undef X4CPLRMINOR_METROWERKS_CODEWARRIOR
#	undef X4CPLRPATCH_METROWERKS_CODEWARRIOR
#	ifdef __CWCC__
#		define X4CPLRMAJOR_METROWERKS_CODEWARRIOR (__CWCC__ / 0x1000)
#		define X4CPLRMINOR_METROWERKS_CODEWARRIOR (__CWCC__ % 0x1000 / 0x100)
#		define X4CPLRPATCH_METROWERKS_CODEWARRIOR (__CWCC__ % 0x100)
#	else
#		define X4CPLRMAJOR_METROWERKS_CODEWARRIOR (__MWERKS__ / 0x1000)
#		define X4CPLRMINOR_METROWERKS_CODEWARRIOR (__MWERKS__ % 0x1000 / 0x100)
#		define X4CPLRPATCH_METROWERKS_CODEWARRIOR (__MWERKS__ % 0x100)
#	endif
#endif

#ifdef __COMO__
#	undef X4CPLR_COMEAU
#	define X4CPLR_COMEAU 1

#	undef X4CPLRMAJOR_COMEAU
#	define X4CPLRMAJOR_COMEAU (__COMO_VERSION___ / 0x100)

#	undef X4CPLRMINOR_COMEAU
#	define X4CPLRMINOR_COMEAU (__COMO_VERSION___ % 0x100 / 0x10)

#	undef X4CPLRPATCH_COMEAU
#	define X4CPLRPATCH_COMEAU (__COMO_VERSION__ % 0x10)
#endif

#ifdef __DECC
#	undef X4CPLR_COMPAQ_C
#	define X4CPLR_COMPAQ_C 1

#	undef X4CPLRMAJOR_COMPAQ_C
#	define X4CPLRMAJOR_COMPAQ_C (__DECC_VER / 10000000)

#	undef X4CPLRMINOR_COMPAQ_C
#	define X4CPLRMINOR_COMPAQ_C (__DECC_VER % 10000000 / 100000)

#	undef X4CPLRPATCH_COMPAQ_C
#	define X4CPLRPATCH_COMPAQ_C (__DECC_VER % 10000)
#endif

#ifdef __DECCXX
#	undef X4CPLR_COMPAQ_CPP
#	define X4CPLR_COMPAQ_CPP 1

#	undef X4CPLRMAJOR_COMPAQ_CPP
#	define X4CPLRMAJOR_COMPAQ_CPP (__DECCXX_VER / 10000000)

#	undef X4CPLRMINOR_COMPAQ_CPP
#	define X4CPLRMINOR_COMPAQ_CPP (__DECCXX_VER % 10000000 / 100000)

#	undef X4CPLRPATCH_COMPAQ_CPP
#	define X4CPLRPATCH_COMPAQ_CPP (__DECCXX_VER % 10000)
#endif

#ifdef __COMPCERT__
#	undef X4CPLR_COMPCERT
#	define X4CPLR_COMPCERT 1
#endif

#ifdef __convexc__
#	undef X4CPLR_CONVEX_C
#	define X4CPLR_CONVEX_C 1
#endif

#ifdef __COVERITY__
#	undef X4CPLR_COVERITY_STATIC_ANALYZER
#	define X4CPLR_COVERITY_STATIC_ANALYZER 1
#endif

#ifdef _CRAYC
#	undef X4CPLR_CRAY
#	define X4CPLR_CRAY 1

#	undef X4CPLRMAJOR_CRAY
#	define X4CPLRMAJOR_CRAY _RELEASE

#	undef X4CPLRMINOR_CRAY
#	define X4CPLRMINOR_CRAY _RELEASE_MINOR
#endif

#ifdef __DMC__
#	undef X4CPLR_DIGITAL_MARS
#	define X4CPLR_DIGITAL_MARS 1

#	undef X4CPLRMAJOR_DIGITAL_MARS
#	define X4CPLRMAJOR_DIGITAL_MARS (__DMC__ / 0x100)

#	undef X4CPLRMINOR_DIGITAL_MARS
#	define X4CPLRMINOR_DIGITAL_MARS (__DMC__ % 0x100 / 0x10)

#	undef X4CPLRPATCH_DIGITAL_MARS
#	define X4CPLRPATCH_DIGITAL_MARS (__DMC__ % 0x10)
#endif

#ifdef _DICE
#	undef X4CPLR_DICE_C
#	define X4CPLR_DICE_C 1
#endif

#ifdef __SYSC__
#	undef X4CPLR_DIGNUS_SYSTEMS_CPP
#	define X4CPLR_DIGNUS_SYSTEMS_CPP 1

#	undef X4CPLRMAJOR_DIGNUS_SYSTEMS_CPP
#	define X4CPLRMAJOR_DIGNUS_SYSTEMS_CPP (__SYSC_VER__ / 10000)

#	undef X4CPLRMINOR_DIGNUS_SYSTEMS_CPP
#	define X4CPLRMINOR_DIGNUS_SYSTEMS_CPP (__SYSC_VER__ % 10000 / 100)

#	undef X4CPLRPATCH_DIGNUS_SYSTEMS_CPP
#	define X4CPLRPATCH_DIGNUS_SYSTEMS_CPP (__SYSC_VER__ % 100)
#endif

#if defined(DJGPP) || defined(__DJGPP) || defined(__DJGPP__)
#	undef X4CPLR_DJGPP
#	define X4CPLR_DJGPP 1

#	undef X4CPLRMAJOR_DJGPP
#	define X4CPLRMAJOR_DJGPP __DJGPP__

#	undef X4CPLRMINOR_DJGPP
#	define X4CPLRMINOR_DJGPP __DJGPP_MINOR__
#endif

#ifdef __EDG__
#	undef X4CPLR_EDG
#	define X4CPLR_EDG 1

#	undef X4CPLRMAJOR_EDG
#	define X4CPLRMAJOR_EDG (__EDG_VERSION___ / 100)

#	undef X4CPLRMINOR_EDG
#	define X4CPLRMINOR_EDG (__EDG_VERSION___ % 100)
#endif

#ifdef __PATHCC__
#	undef X4CPLR_EKOPATH
#	define X4CPLR_EKOPATH 1

#	undef X4CPLRMAJOR_EKOPATH
#	define X4CPLRMAJOR_EKOPATH __PATHCC__

#	undef X4CPLRMINOR_EKOPATH
#	define X4CPLRMINOR_EKOPATH __PATHCC_MINOR__

#	undef X4CPLRPATCH_EKOPATH
#	define X4CPLRPATCH_EKOPATH __PATHCC_PATCHLEVEL__
#endif

#ifdef __ELLCC__
#	undef X4CPLR_ELLCC
#	define X4CPLR_ELLCC 1
#endif

#ifdef __EMSCRIPTEN__
#	undef X4CPLR_EMSCRIPTEN
#	define X4CPLR_EMSCRIPTEN 1
#endif

#ifdef __FCC_VERSION
#	undef X4CPLR_FUJITSU_CPP
#	define X4CPLR_FUJITSU_CPP 1
#endif

#if defined(__GNUC) || defined(__GNUC__) || defined(__gnuc)
#	undef X4CPLR_GCC
#	define X4CPLR_GCC 1

#	undef X4CPLRMAJOR_GCC
#	define X4CPLRMAJOR_GCC __GNUC__

#	undef X4CPLRMINOR_GCC
#	define X4CPLRMINOR_GCC __GNUC_MINOR__

#	undef X4CPLRPATCH_GCC
#	define X4CPLRPATCH_GCC __GNUC_PATCHLEVEL__
#endif

#ifdef __GCCXML__
#	undef X4CPLR_GCC_XML
#	define X4CPLR_GCC_XML 1
#endif

#if defined(__ghs) || defined(__ghs__)
#	undef X4CPLR_GREEN_HILLS
#	define X4CPLR_GREEN_HILLS 1

#	ifdef __ghs
#		undef X4CPLRMAJOR_GREEN_HILLS
#		define X4CPLRMAJOR_GREEN_HILLS (__ghs / 100)

#		undef X4CPLRMINOR_GREEN_HILLS
#		define X4CPLRMINOR_GREEN_HILLS (__ghs % 100 / 10)

#		undef X4CPLRPATCH_GREEN_HILLS
#		define X4CPLRPATCH_GREEN_HILLS (__ghs % 10)
#	elifdef __GHS_VERSION_NUMBER__
#		undef X4CPLRMAJOR_GREEN_HILLS
#		define X4CPLRMAJOR_GREEN_HILLS (__GHS_VERSION_NUMBER__ / 100)

#		undef X4CPLRMINOR_GREEN_HILLS
#		define X4CPLRMINOR_GREEN_HILLS (__GHS_VERSION_NUMBER__ % 100 / 10)

#		undef X4CPLRPATCH_GREEN_HILLS
#		define X4CPLRPATCH_GREEN_HILLS (__GHS_VERSION_NUMBER__ % 10)
#	endif
#endif

#ifdef __hexagon__
#	undef X4CPLR_HEXAGON
#	define X4CPLR_HEXAGON 1

#	ifdef __HEXAGON_V65__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 65
#	endif

#	ifdef __HEXAGON_V66__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 66
#	endif

#	ifdef __HEXAGON_V67__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 67
#	endif

#	ifdef __HEXAGON_V68__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 68
#	endif

#	ifdef __HEXAGON_V69__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 69
#	endif

#	ifdef __HEXAGON_V70__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 70
#	endif

#	ifdef __HEXAGON_V71__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 71
#	endif

#	ifdef __HEXAGON_V73__
#		undef X4CPLRMAJOR_HEXAGON
#		define X4CPLRMAJOR_HEXAGON 73
#	endif
#endif

#if defined(__HIPCC__) || defined(__HIP__)
#	undef X4CPLR_HIPCC
#	define X4CPLR_HIPCC 1
#endif

#ifdef __HP_aCC
#	undef X4CPLR_HP_ACC
#	define X4CPLR_HP_ACC 1

#	undef X4CPLRMAJOR_HP_ACC
#	define X4CPLRMAJOR_HP_ACC (__HP_aCC / 10000)

#	undef X4CPLRMINOR_HP_ACC
#	define X4CPLRMINOR_HP_ACC (__HP_aCC % 10000 / 100)

#	undef X4CPLRPATCH_HP_ACC
#	define X4CPLRPATCH_HP_ACC (__HP_aCC % 100)
#endif

#ifdef __HP_cc
#	undef X4CPLR_HP_ANSI_C
#	define X4CPLR_HP_ANSI_C 1
#endif

#ifdef __IAR_SYSTEMS_ICC__
#	undef X4CPLR_IAR
#	define X4CPLR_IAR 1

#	undef X4CPLRMAJOR_IAR
#	define X4CPLRMAJOR_IAR (__VER__ / 100)

#	undef X4CPLRMINOR_IAR
#	define X4CPLRMINOR_IAR (__VER__ % 100)
#endif

#if defined(__ECC) || defined(__ICC) || defined(__ICL) || defined(__INTEL_COMPILER)
#	undef X4CPLR_ICC
#	define X4CPLR_ICC 1

#	ifdef __INTEL_COMPILER
#		undef X4CPLRMAJOR_ICC
#		undef X4CPLRMINOR_ICC
#		undef X4CPLRPATCH_ICC

#		if __INTEL_COMPILER == 9999
#			define X4CPLRMAJOR_ICC 12
#			define X4CPLRMINOR_ICC 1
#		else
#			define X4CPLRMAJOR_ICC (__INTEL_COMPILER / 100)
#			define X4CPLRMINOR_ICC (__INTEL_COMPILER % 100 / 10)

#			ifdef __INTEL_COMPILER_UPDATE
#				define X4CPLRPATCH_ICC __INTEL_COMPILER_UPDATE
#			else
#				define X4CPLRPATCH_ICC (__INTEL_COMPILER % 10)
#			endif
#		endif
#	endif
#endif

#ifdef __INTEL_CLANG_COMPILER
#	undef X4CPLR_ICX
#	define X4CPLR_ICX 1

#	undef X4CPLRMAJOR_ICX
#	define X4CPLRMAJOR_ICX (__INTEL_CLANG_COMPILER / 100)

#	undef X4CPLRMINOR_ICX
#	define X4CPLRMINOR_ICX (__INTEL_CLANG_COMPILER % 100 / 10)

#	undef X4CPLRPATCH_ICX
#	define X4CPLRPATCH_ICX (__INTEL_CLANG_COMPILER % 10)
#endif

#ifdef __IMAGECRAFT__
#	undef X4CPLR_IMAGECRAFT_C
#	define X4CPLR_IMAGECRAFT_C 1
#endif

#ifdef __KCC
#	undef X4CPLR_KCC
#	define X4CPLR_KCC 1

#	undef X4CPLRMAJOR_KCC
#	define X4CPLRMAJOR_KCC (__KCC_VERSION / 0x1000)

#	undef X4CPLRMINOR_KCC
#	define X4CPLRMINOR_KCC (__KCC_VERSION % 0x1000 / 0x100)

#	undef X4CPLRPATCH_KCC
#	define X4CPLRPATCH_KCC (__KCC_VERSION % 0x100)
#endif

#ifdef __C166__
#	undef X4CPLR_KEIL_C166
#	define X4CPLR_KEIL_C166 1

#	undef X4CPLRMAJOR_KEIL_C166
#	define X4CPLRMAJOR_KEIL_C166 (__C166__ / 100)

#	undef X4CPLRMINOR_KEIL_C166
#	define X4CPLRMINOR_KEIL_C166 (__C166__ % 100)
#endif

#ifdef __C51__
#	undef X4CPLR_KEIL_C51
#	define X4CPLR_KEIL_C51 1

#	undef X4CPLRMAJOR_KEIL_C51
#	define X4CPLRMAJOR_KEIL_C51 (__C51__ / 100)

#	undef X4CPLRMINOR_KEIL_C51
#	define X4CPLRMINOR_KEIL_C51 (__C51__ % 100)
#endif

#if defined(__CA__) || defined(__KEIL__)
#	undef X4CPLR_KEIL_CARM
#	define X4CPLR_KEIL_CARM 1

#	undef X4CPLRMAJOR_KEIL_CARM
#	define X4CPLRMAJOR_KEIL_CARM (__CA__ / 100)

#	undef X4CPLRMINOR_KEIL_CARM
#	define X4CPLRMINOR_KEIL_CARM (__CA__ % 100)
#endif

#if defined(SASC) || defined(__SASC) || defined(__SASC__)
#	undef X4CPLR_LATTICE_C
#	define X4CPLR_LATTICE_C 1

#	undef X4CPLRMAJOR_LATTICE_C
#	define X4CPLRMAJOR_LATTICE_C (__SASC__ / 100)

#	undef X4CPLRMINOR_LATTICE_C
#	define X4CPLRMINOR_LATTICE_C (__SASC__ % 100)
#endif

#ifdef __LCC__
#	undef X4CPLR_LCC
#	define X4CPLR_LCC 1

#	undef X4CPLRMAJOR_LCC
#	define X4CPLRMAJOR_LCC __LCC__

#	undef X4CPLRMINOR_LCC
#	define X4CPLRMINOR_LCC __LCC_MINOR__
#endif

#if defined(THINKC3) || defined(THINKC4)
#	undef X4CPLR_LIGHTSPEED_C
#	define X4CPLR_LIGHTSPEED_C 1
#endif

#ifdef __llvm__
#	undef X4CPLR_LLVM
#	define X4CPLR_LLVM 1
#endif

#ifdef __HIGHC__
#	undef X4CPLR_METAWARE_HIGH
#	define X4CPLR_METAWARE_HIGH 1
#endif

#ifdef _MRI
#	undef X4CPLR_MICROTEC
#	define X4CPLR_MICROTEC 1
#endif

#if defined(__NDPC__) || defined(__NDPX__)
#	undef X4CPLR_MICROWAY_NDP_C
#	define X4CPLR_MICROWAY_NDP_C 1
#endif

#ifdef __MINGW32__
#	include <windows.h>

#	undef X4CPLR_MINGW32
#	define X4CPLR_MINGW32 1

#	undef X4CPLRMAJOR_MINGW32
#	define X4CPLRMAJOR_MINGW32 __MINGW32_MAJOR_VERSION

#	undef X4CPLRMINOR_MINGW32
#	define X4CPLRMINOR_MINGW32 __MINGW32_MINOR_VERSION
#endif

#ifdef __MINGW64__
#	include <windows.h>

#	undef X4CPLR_MINGW_W64
#	define X4CPLR_MINGW_W64 1

#	undef X4CPLRMAJOR_MINGW_W64
#	define X4CPLRMAJOR_MINGW_W64 __MINGW64_VERSION_MAJOR

#	undef X4CPLRMINOR_MINGW_W64
#	define X4CPLRMINOR_MINGW_W64 __MINGW64_VERSION_MINOR

#	undef X4CPLRPATCH_MINGW_W64
#	define X4CPLRPATCH_MINGW_W64
#endif

#if defined(sgi) || defined(__sgi)
#	undef X4CPLR_MIPSPRO
#	define X4CPLR_MIPSPRO 1

#	ifdef _SGI_COMPILER_VERSION
#		undef X4CPLRMAJOR_MIPSPRO
#		define X4CPLRMAJOR_MIPSPRO (_SGI_COMPILER_VERSION / 100)

#		undef X4CPLRMINOR_MIPSPRO
#		define X4CPLRMINOR_MIPSPRO (_SGI_COMPILER_VERSION % 100 / 10)

#		undef X4CPLRPATCH_MIPSPRO
#		define X4CPLRPATCH_MIPSPRO (_SGI_COMPILER_VERSION % 10)
#	elifdef _COMPILER_VERSION
#		undef X4CPLRMAJOR_MIPSPRO
#		define X4CPLRMAJOR_MIPSPRO (_COMPILER_VERSION / 100)

#		undef X4CPLRMINOR_MIPSPRO
#		define X4CPLRMINOR_MIPSPRO (_COMPILER_VERSION % 100 / 10)

#		undef X4CPLRPATCH_MIPSPRO
#		define X4CPLRPATCH_MIPSPRO (_COMPILER_VERSION % 10)
#	endif
#endif

#ifdef MIRACLE
#	undef X4CPLR_MIRACLE_C
#	define X4CPLR_MIRACLE_C 1
#endif

#if defined(MPW_C) || defined(MPW_CPLUS) || defined(__MRC__)
#	undef X4CPLR_MPW
#	define X4CPLR_MPW 1

#	undef X4CPLRMAJOR_MPW
#	define X4CPLRMAJOR_MPW (__MRC__ / 0x100)

#	undef X4CPLRMINOR_MPW
#	define X4CPLRMINOR_MPW (__MRC__ % 0x100)
#endif

#ifdef _MSC_VER
#	undef X4CPLR_MSVC
#	define X4CPLR_MSVC 1

#	undef X4CPLRMAJOR_MSVC
#	define X4CPLRMAJOR_MSVC (_MSC_FULL_VER / 10000000)

#	undef X4CPLRMINOR_MSVC
#	define X4CPLRMINOR_MSVC (_MSC_FULL_VER % 10000000 / 100000)

#	undef X4CPLRPATCH_MSVC
#	define X4CPLRPATCH_MSVC (_MSC_FULL_VER % 100000)
#endif

#ifdef __CC_NORCROFT
#	undef X4CPLR_NORCROFT_C
#	define X4CPLR_NORCROFT_C 1
#endif

#ifdef __NVCOMPILER
#	undef X4CPLR_NVIDIA_HPC
#	define X4CPLR_NVIDIA_HPC 1

#	undef X4CPLRMAJOR_NVIDIA_HPC
#	define X4CPLRMAJOR_NVIDIA_HPC __NVCOMPILER_MAJOR__

#	undef X4CPLRMINOR_NVIDIA_HPC
#	define X4CPLRMINOR_NVIDIA_HPC __NVCOMPILER_MINOR__
#endif

#ifdef __NVCC__
#	undef X4CPLR_NVCC
#	define X4CPLR_NVCC 1

#	undef X4CPLRMAJOR_NVCC
#	define X4CPLRMAJOR_NVCC __CUDACC_VER_MAJOR__

#	undef X4CPLRMINOR_NVCC
#	define X4CPLRMINOR_NVCC __CUDACC_VER_MINOR__

#	undef X4CPLRPATCH_NVCC
#	define X4CPLRPATCH_NVCC __CUDACC_VER_BUILD__
#endif

#ifdef __NWCC__
#	undef X4CPLR_NWCC
#	define X4CPLR_NWCC 1
#endif

#if defined(__OPEN64__) || defined(__OPENCC__)
#	undef X4CPLR_OPEN64
#	define X4CPLR_OPEN64 1

#	undef X4CPLRMAJOR_OPEN64
#	define X4CPLRMAJOR_OPEN64 __OPENCC__

#	undef X4CPLRMINOR_OPEN64
#	define X4CPLRMINOR_OPEN64 __OPENCC_MINOR__

#	undef X4CPLRPATCH_OPEN64
#	define X4CPLRPATCH_OPEN64 __OPENCC_PATCHLEVEL__
#endif

#ifdef _OPENACC
#	undef X4CPLR_OPENACC
#	define X4CPLR_OPENACC 1
#endif

#ifdef _SCO_DS
#	undef X4CPLR_OPENSERVER
#	define X4CPLR_OPENSERVER 1
#endif

#ifdef __PACIFIC__
#	undef X4CPLR_PACIFIC_C
#	define X4CPLR_PACIFIC_C 1
#endif

#ifdef _PACC_VER
#	undef X4CPLR_PALM
#	define X4CPLR_PALM 1

#	undef X4CPLRMAJOR_PALM
#	define X4CPLRMAJOR_PALM (_PACC_VER / 0x10000000)

#	undef X4CPLRMINOR_PALM
#	define X4CPLRMINOR_PALM (_PACC_VER % 0x10000000 / 0x100000)

#	undef X4CPLRPATCH_PALM
#	define X4CPLRPATCH_PALM (_PACC_VER % 0x100000 / 0x1000)
#endif

#ifdef __POCC__
#	undef X4CPLR_PELLES_C
#	define X4CPLR_PELLES_C 1

#	undef X4CPLRMAJOR_PELLES_C
#	define X4CPLRMAJOR_PELLES_C (__POCC__ / 100)

#	undef X4CPLRMINOR_PELLES_C
#	define X4CPLRMINOR_PELLES_C (__POCC__ % 100)
#endif

#ifdef __PGI
#	undef X4CPLR_PGI
#	define X4CPLR_PGI 1

#	undef X4CPLRMAJOR_PGI
#	define X4CPLRMAJOR_PGI __PGIC__

#	undef X4CPLRMINOR_PGI
#	define X4CPLRMINOR_PGI __PGIC_MINOR__

#	undef X4CPLRPATCH_PGI
#	define X4CPLRPATCH_PGI __PGIC_PATCHLEVEL__
#endif

#ifdef ORA_PROC
#	undef X4CPLR_PRO_C
#	define X4CPLR_PRO_C 1
#endif

#if defined(__HITACHI__) || defined(__RENESAS__)
#	undef X4CPLR_RENESAS
#	define X4CPLR_RENESAS 1

#	undef X4CPLRMAJOR_RENESAS
#	define X4CPLRMAJOR_RENESAS (__RENESAS_VERSION___ / 0x1000000)

#	undef X4CPLRMINOR_RENESAS
#	define X4CPLRMINOR_RENESAS (__RENESAS_VERSION___ % 0x1000000 / 0x10000)

#	undef X4CPLRPATCH_RENESAS
#	define X4CPLRPATCH_RENESAS (__RENESAS_VERSION___ % 0x10000 / 0x100)
#endif

#if defined(SDCC) || defined(__SDCC)
#	undef X4CPLR_SDCC
#	define X4CPLR_SDCC 1

#	undef X4CPLRMAJOR_SDCC
#	undef X4CPLRMINOR_SDCC
#	undef X4CPLRPATCH_SDCC
#	ifdef SDCC
#		define X4CPLRMAJOR_SDCC (SDCC / 100)
#		define X4CPLRMINOR_SDCC (SDCC % 100 / 10)
#		define X4CPLRPATCH_SDCC (SDCC % 10)
#	elifdef __SDCC
#		define X4CPLRMAJOR_SDCC (__SDCC / 100)
#		define X4CPLRMINOR_SDCC (__SDCC % 100 / 10)
#		define X4CPLRPATCH_SDCC (__SDCC % 10)
#	else
#		define X4CPLRMAJOR_SDCC __SDCC_VERSION_MAJOR
#		define X4CPLRMINOR_SDCC __SDCC_VERSION_MINOR
#		define X4CPLRMINOR_SDCC __SDCC_VERSION_PATCH
#	endif
#endif

#ifdef __SNC__
#	undef X4CPLR_SNC
#	define X4CPLR_SNC 1
#endif

#ifdef __VOSC__
#	undef X4CPLR_STRATUS_VOS_C
#	define X4CPLR_STRATUS_VOS_C 1
#endif

#ifdef __SUNPRO_C
#	undef X4CPLR_SUNPRO_C
#	define X4CPLR_SUNPRO_C 1

#	undef X4CPLRMAJOR_SUNPRO_C
#	define X4CPLRMAJOR_SUNPRO_C (__SUNPRO_C / 0x1000)

#	undef X4CPLRMINOR_SUNPRO_C
#	define X4CPLRMINOR_SUNPRO_C (__SUNPRO_C % 0x1000 / 0x10)

#	undef X4CPLRPATCH_SUNPRO_C
#	define X4CPLRPATCH_SUNPRO_C (__SUNPRO_C % 0x10)
#endif

#ifdef __SUNPRO_CC
#	undef X4CPLR_SUNPRO_CPP
#	define X4CPLR_SUNPRO_CPP 1

#	undef X4CPLRMAJOR_SUNPRO_CPP
#	define X4CPLRMAJOR_SUNPRO_CPP (__SUNPRO_CC / 0x1000)

#	undef X4CPLRMINOR_SUNPRO_CPP
#	define X4CPLRMINOR_SUNPRO_CPP (__SUNPRO_CC % 0x1000 / 0x10)

#	undef X4CPLRPATCH_SUNPRO_CPP
#	define X4CPLRPATCH_SUNPRO_CPP (__SUNPRO_CC % 0x10)
#endif

#ifdef __SC__
#	undef X4CPLR_SYMANTEC_CPP
#	define X4CPLR_SYMANTEC_CPP 1

#	undef X4CPLRMAJOR_SYMANTEC_CPP
#	define X4CPLRMAJOR_SYMANTEC_CPP (__SC__ / 0x100)

#	undef X4CPLRMINOR_SYMANTEC_CPP
#	define X4CPLRMINOR_SYMANTEC_CPP (__SC__ % 0x100)
#endif

#ifdef __TINYC__
#	undef X4CPLR_TCC
#	define X4CPLR_TCC 1
#endif

#ifdef __TenDRA__
#	undef X4CPLR_TENDRA
#	define X4CPLR_TENDRA 1
#endif

#ifdef _TMS320C6X
#	undef X4CPLR_TI_CGT
#	define X4CPLR_TI_CGT 1

#	undef X4CPLRMAJOR_TI_CGT
#	define X4CPLRMAJOR_TI_CGT (__TI_COMPILER_VERSION___ / 1000000)

#	undef X4CPLRMINOR_TI_CGT
#	define X4CPLRMINOR_TI_CGT (__TI_COMPILER_VERSION___ % 1000000 / 1000)

#	undef X4CPLRPATCH_TI_CGT
#	define X4CPLRPATCH_TI_CGT (__TI_COMPILER_VERSION___ % 1000)
#endif

#ifdef __MSP430__
#	undef X4CPLR_TI_CL430
#	define X4CPLR_TI_CL430 1

#	undef X4CPLRMAJOR_TI_CL430
#	define X4CPLRMAJOR_TI_CL430 (__TI_COMPILER_VERSION___ / 1000000)

#	undef X4CPLRMINOR_TI_CL430
#	define X4CPLRMINOR_TI_CL430 (__TI_COMPILER_VERSION___ % 1000000 / 1000)

#	undef X4CPLRPATCH_TI_CL430
#	define X4CPLRPATCH_TI_CL430 (__TI_COMPILER_VERSION___ % 1000)
#endif

#ifdef __TURBOC__
#	undef X4CPLR_TURBO
#	define X4CPLR_TURBO 1

#	undef X4CPLRMAJOR_TURBO
#	define X4CPLRMAJOR_TURBO (__TURBOC__ / 0x100)

#	undef X4CPLRMINOR_TURBO
#	define X4CPLRMINOR_TURBO (__TURBOC__ % 0x100)
#endif

#ifdef _UCC
#	undef X4CPLR_ULTIMATE
#	define X4CPLR_ULTIMATE 1

#	undef X4CPLRMAJOR_ULTIMATE
#	define X4CPLRMAJOR_ULTIMATE _MAJOR_REV

#	undef X4CPLRMINOR_ULTIMATE
#	define X4CPLRMINOR_ULTIMATE _MINOR_REV
#endif

#ifdef __USLC__
#	undef X4CPLR_USL_C
#	define X4CPLR_USL_C 1

#	undef X4CPLRMAJOR_USL_C
#	define X4CPLRMAJOR_USL_C (__SCO_VERSION___ / 100000000)

#	undef X4CPLRMINOR_USL_C
#	define X4CPLRMINOR_USL_C (__SCO_VERSION___ % 100000000 / 1000000)
#endif

#ifdef __VBCC__
#	undef X4CPLR_VBCC
#	define X4CPLR_VBCC 1
#endif

#ifdef __WATCOMC__
#	undef X4CPLR_WATCOM
#	define X4CPLR_WATCOM 1

#	undef X4CPLRMAJOR_WATCOM
#	define X4CPLRMAJOR_WATCOM (__WATCOMC__ / 100)

#	undef X4CPLRMINOR_WATCOM
#	define X4CPLRMINOR_WATCOM (__WATCOMC__ % 100)
#endif

#ifdef __XC8
#	undef X4CPLR_XC8
#	define X4CPLR_XC8 1

#	ifdef __XC8_VERSION
#		undef X4CPLRMAJOR_XC8
#		define X4CPLRMAJOR_XC8 (__XC8_VERSION / 1000)

#		undef X4CPLRMINOR_XC8
#		define X4CPLRMINOR_XC8 (__XC8_VERSION % 1000 / 10)

#		undef X4CPLRMAJOR_XC8
#		define X4CPLRMAJOR_XC8 (__XC8_VERSION % 10)
#	endif
#endif

#if defined(C30) || defined(XC16) || defined(__C30) || defined(__C30__) || defined(__XC16) || defined(__XC16__) || defined(__dsPIC30__) || defined(__dsPICC30) || defined(dsPIC30)
#	undef X4CPLR_XC16
#	define X4CPLR_XC16 1

#	ifdef __XC32_VERSION
#		undef X4CPLRMAJOR_XC32
#		define X4CPLRMAJOR_XC32 (__XC32_VERSION / 1000)

#		undef X4CPLRMINOR_XC32
#		define X4CPLRMINOR_XC32 (__XC32_VERSION % 1000 / 10)

#		undef X4CPLRMAJOR_XC32
#		define X4CPLRMAJOR_XC32 (__XC32_VERSION % 10)
#	elifdef __C32_VERSION__
#		undef X4CPLRPATCH_XC32
#		define X4CPLRPATCH_XC32 (__C32_VERSION__ / 1000)

#		undef X4CPLRMINOR_XC32
#		define X4CPLRMINOR_XC32 (__C32_VERSION__ % 1000 / 10)

#		undef X4CPLRPATCH_XC32
#		define X4CPLRPATCH_XC32 (__C32_VERSION__ % 10)
#	endif
#endif

#ifdef __XC32
#	undef X4CPLR_XC32
#	define X4CPLR_XC32 1

#	ifdef __XC32_VERSION
#		undef X4CPLRMAJOR_XC32
#		define X4CPLRMAJOR_XC32 (__XC32_VERSION / 1000)

#		undef X4CPLRMINOR_XC32
#		define X4CPLRMINOR_XC32 (__XC32_VERSION % 1000 / 10)

#		undef X4CPLRMAJOR_XC32
#		define X4CPLRMAJOR_XC32 (__XC32_VERSION % 10)
#	elifdef __C32_VERSION__
#		undef X4CPLRPATCH_XC32
#		define X4CPLRPATCH_XC32 (__C32_VERSION__ / 1000)

#		undef X4CPLRMINOR_XC32
#		define X4CPLRMINOR_XC32 (__C32_VERSION__ % 1000 / 10)

#		undef X4CPLRPATCH_XC32
#		define X4CPLRPATCH_XC32 (__C32_VERSION__ % 10)
#	endif
#endif

#ifdef __DCC__
#	undef X4CPLR_WIND_RIVER_DIAB
#	define X4CPLR_WIND_RIVER_DIAB 1

#	undef X4CPLRMAJOR_WIND_RIVER_DIAB
#	define X4CPLRMAJOR_WIND_RIVER_DIAB (__VERSION_NUMBER__ / 1000)

#	undef X4CPLRMINOR_WIND_RIVER_DIAB
#	define X4CPLRMINOR_WIND_RIVER_DIAB (__VERSION_NUMBER__ % 1000 / 100)

#	undef X4CPLRPATCH_WIND_RIVER_DIAB
#	define X4CPLRPATCH_WIND_RIVER_DIAB (__VERSION_NUMBER__ % 100)
#endif

#if defined(__IBMCPP__) || defined(__IBMC__) || defined(__ibmxl__) || defined(__xlC__) || defined(__xlc__)
#	undef X4CPLR_XL
#	define X4CPLR_XL 1

#	ifdef __COMPILER_VER__
#		undef X4CPLRMAJOR_XL
#		define X4CPLRMAJOR_XL (__COMPILER_VER__ / 0x1000000)

#		undef X4CPLRMINOR_XL
#		define X4CPLRMINOR_XL (__COMPILER_VER__ % 0x1000000 / 0x1000)

#		undef X4CPLRPATCH_XL
#		define X4CPLRPATCH_XL (__COMPILER_VER__ % 0x1000)
#	elifdef __IBMCPP__
#		undef X4CPLRMAJOR_XL
#		define X4CPLRMAJOR_XL (__IBMCPP__ / 100)

#		undef X4CPLRMINOR_XL
#		define X4CPLRMINOR_XL (__IBMCPP__ % 10 / 10)

#		undef X4CPLRPATCH_XL
#		define X4CPLRPATCH_XL (__IBMCPP__ % 10)
#	elifdef __xlC__
#		undef X4CPLRMAJOR_XL
#		define X4CPLRMAJOR_XL (__xlC__ / 0x100)

#		undef X4CPLRMINOR_XL
#		define X4CPLRMINOR_XL (__xlC__ % 0x100)
#	elifdef __xlc__
#		undef X4CPLRMAJOR_XL
#		define X4CPLRMAJOR_XL (__xlc__ / 0x100)

#		undef X4CPLRMINOR_XL
#		define X4CPLRMINOR_XL (__xlc__ % 0x100)
#	else
#		undef X4CPLRMAJOR_XL
#		define X4CPLRMAJOR_XL __ibmxl_version__

#		undef X4CPLRMINOR_XL
#		define X4CPLRMINOR_XL __ibmxl_release__

#		undef X4CPLRPATCH_XL
#		define X4CPLRPATCH_XL __ibmxl_modification__
#	endif
#endif

#ifdef __ZTC__
#	undef X4CPLR_ZORTECH_CPP
#	define X4CPLR_ZORTECH_CPP 1

#	undef X4CPLRMAJOR_ZORTECH_CPP
#	define X4CPLRMAJOR_ZORTECH_CPP (__ZTC__ / 0x100)

#	undef X4CPLRMINOR_ZORTECH_CPP
#	define X4CPLRMINOR_ZORTECH_CPP (__ZTC__ % 0x100 / 0x10)

#	undef X4CPLRPATCH_ZORTECH_CPP
#	define X4CPLRPATCH_ZORTECH_CPP (__ZTC__ % 0x10)
#endif

#if defined(SCCZ80) || defined(__SCCZ80)
#	undef X4CPLR_Z88DK
#	define X4CPLR_Z88DK 1
#endif
