#pragma once

#define X4STDLIB_CLOUDABI_C 0
#define X4STDLIBMAJOR_CLOUDABI_C 0
#define X4STDLIBMINOR_CLOUDABI_C 0
#define X4STDLIBPATCH_CLOUDABI_C 0
#define X4STDLIB_COMO_CPP 0
#define X4STDLIBMAJOR_COMO_CPP 0
#define X4STDLIBMINOR_COMO_CPP 0
#define X4STDLIBPATCH_COMO_CPP 0
#define X4STDLIB_DINKUMWARE_CPP 0
#define X4STDLIBMAJOR_DINKUMWARE_CPP 0
#define X4STDLIBMINOR_DINKUMWARE_CPP 0
#define X4STDLIBPATCH_DINKUMWARE_CPP 0
#define X4STDLIB_GNU_C 0
#define X4STDLIBMAJOR_GNU_C 0
#define X4STDLIBMINOR_GNU_C 0
#define X4STDLIBPATCH_GNU_C 0
#define X4STDLIB_GNU_CPP 0
#define X4STDLIBMAJOR_GNU_CPP 0
#define X4STDLIBMINOR_GNU_CPP 0
#define X4STDLIBPATCH_GNU_CPP 0
#define X4STDLIB_IBM_VA_CPP 0
#define X4STDLIBMAJOR_IBM_VA_CPP 0
#define X4STDLIBMINOR_IBM_VA_CPP 0
#define X4STDLIBPATCH_IBM_VA_CPP 0
#define X4STDLIB_LLVM_CPP 0
#define X4STDLIBMAJOR_LLVM_CPP 0
#define X4STDLIBMINOR_LLVM_CPP 0
#define X4STDLIBPATCH_LLVM_CPP 0
#define X4STDLIB_METROWERKS_CPP 0
#define X4STDLIBMAJOR_METROWERKS_CPP 0
#define X4STDLIBMINOR_METROWERKS_CPP 0
#define X4STDLIBPATCH_METROWERKS_CPP 0
#define X4STDLIB_MODENA_CPP 0
#define X4STDLIBMAJOR_MODENA_CPP 0
#define X4STDLIBMINOR_MODENA_CPP 0
#define X4STDLIBPATCH_MODENA_CPP 0
#define X4STDLIB_PDP_C 0
#define X4STDLIBMAJOR_PDP_C 0
#define X4STDLIBMINOR_PDP_C 0
#define X4STDLIBPATCH_PDP_C 0
#define X4STDLIB_ROGUEWAVE_CPP 0
#define X4STDLIBMAJOR_ROGUEWAVE_CPP 0
#define X4STDLIBMINOR_ROGUEWAVE_CPP 0
#define X4STDLIBPATCH_ROGUEWAVE_CPP 0
#define X4STDLIB_SGI_CPP 0
#define X4STDLIBMAJOR_SGI_CPP 0
#define X4STDLIBMINOR_SGI_CPP 0
#define X4STDLIBPATCH_SGI_CPP 0
#define X4STDLIB_UC_C 0
#define X4STDLIBMAJOR_UC_C 0
#define X4STDLIBMINOR_UC_C 0
#define X4STDLIBPATCH_UC_C 0
#define X4STDLIB_VMS_C 0
#define X4STDLIBMAJOR_VMS_C 0
#define X4STDLIBMINOR_VMS_C 0
#define X4STDLIBPATCH_VMS_C 0
#define X4STDLIB_Z_C 0
#define X4STDLIBMAJOR_Z_C 0
#define X4STDLIBMINOR_Z_C 0
#define X4STDLIBPATCH_Z_C 0

#define X4STDLIBEQ(type, major, ...) DETAIL_X4STDLIB(__VA_ARGS__, DETAIL_X4STDLIBEQ(type, major, __VA_ARGS__), DETAIL_X4STDLIBEQ(type, major, __VA_ARGS__, 0), DETAIL_X4STDLIBEQ(type, major, 0, 0))
#define X4STDLIBLEAST(type, major, ...) DETAIL_X4STDLIB(__VA_ARGS__, DETAIL_X4STDLIBLEAST(type, major, __VA_ARGS__), DETAIL_X4STDLIBLEAST(type, major, __VA_ARGS__, 0), DETAIL_X4STDLIBLEAST(type, major, 0, 0))
#define X4STDLIBMOST(type, major, ...) DETAIL_X4STDLIB(__VA_ARGS__, DETAIL_X4STDLIBMOST(type, major, __VA_ARGS__), DETAIL_X4STDLIBMOST(type, major, __VA_ARGS__, 0), DETAIL_X4STDLIBMOST(type, major, 0, 0))
#define DETAIL_X4STDLIB(_0, _1, _2, x, ...) x
#define DETAIL_X4STDLIBEQ(type, major, minor, patch) (X4STDLIB_##type && (X4STDLIBMAJOR_##type == (major)) && (X4STDLIBMINOR_##type == (minor)) && (X4STDLIBPATCH_##type == (patch)))
#define DETAIL_X4STDLIBLEAST(type, major, minor, patch) (X4STDLIB_##type && ((X4STDLIBMAJOR_##type > (major)) || (X4STDLIBMAJOR_##type == (major)) && ((X4STDLIBMINOR_##type > (minor)) || (X4STDLIBMINOR_##type == (minor)) && (X4STDLIBPATCH_##type >= (patch)))))
#define DETAIL_X4STDLIBMOST(type, major, minor, patch) (X4STDLIB_##type && ((X4STDLIBMAJOR_##type < (major)) || (X4STDLIBMAJOR_##type == (major)) && ((X4STDLIBMINOR_##type < (minor)) || (X4STDLIBMINOR_##type == (minor)) && (X4STDLIBPATCH_##type <= (patch)))))

#ifdef __cloudlibc__
#	undef X4STDLIB_CLOUDABI_C
#	define X4STDLIB_CLOUDABI_C 1

#	undef X4STDLIBMAJOR_CLOUDABI_C
#	define X4STDLIBMAJOR_CLOUDABI_C __cloudlibc_major__

#	undef X4STDLIBMINOR_CLOUDABI_C
#	define X4STDLIBMINOR_CLOUDABI_C __cloudlibc_minor__
#endif

#ifdef __LIBCOMO__
#	undef X4STDLIB_COMO_CPP
#	define X4STDLIB_COMO_CPP 1

#	undef X4STDLIBMAJOR_COMO_CPP
#	define X4STDLIBMAJOR_COMO_CPP __LIBCOMO_VERSION__
#endif

#if defined(_CPPLIB_VER) || (defined(_YVALS) && !defined(__IBMCPP__))
#	undef X4STDLIB_DINKUMWARE_CPP
#	define X4STDLIB_DINKUMWARE_CPP 1

#	ifdef _CPPLIB_VER
#		undef X4STDLIBMAJOR_DINKUMWARE_CPP
#		define X4STDLIBMAJOR_DINKUMWARE_CPP (_CPPLIB_VER / 100)

#		undef X4STDLIBMINOR_DINKUMWARE_CPP
#		define X4STDLIBMINOR_DINKUMWARE_CPP (_CPPLIB_VER % 100)
#	endif
#endif

#if defined(__GLIBC__) || defined(__GNU_LIBRARY__)
#	undef X4STDLIB_GNU_C
#	define X4STDLIB_GNU_C 1

#	undef X4STDLIBMAJOR_GNU_C
#	undef X4STDLIBMINOR_GNU_C
#	ifdef __GLIBC__
#		define X4STDLIBMAJOR_GNU_C __GLIBC__
#		define XIIETE_LIBRARY_MINOR_GNU_C __GLIBC_MINOR__
#	else
#		define X4STDLIBMAJOR_GNU_C __GNU_LIBRARY__
#		define X4STDLIBMINOR_GNU_C __GNU_LIBRARY_MINOR__
#	endif
#endif

#ifdef __GLIBCXX__
#	undef X4STDLIB_GNU_CPP
#	define X4STDLIB_GNU_CPP 1

#	ifdef _GLIBCXX_RELEASE
#		undef X4STDLIBMAJOR_GNU_CPP
#		define X4STDLIBMAJOR_GNU_CPP _GLIBCXX_RELEASE
#	else
#		undef X4STDLIBMINOR_GNU_CPP
#		define X4STDLIBMINOR_GNU_CPP __GLIBCXX__
#	endif
#endif

#ifdef __IBMCPP__
#	undef X4STDLIB_IBM_VA_CPP
#	define X4STDLIB_IBM_VA_CPP 1
#endif

#ifdef _LIBCPP_VERSION
#	undef X4STDLIB_LLVM_CPP
#	define X4STDLIB_LLVM_CPP 1

#	undef X4STDLIBMAJOR_LLVM_CPP
#	define X4STDLIBMAJOR_LLVM_CPP (_LIBCPP_VERSION / 10000)

#	undef X4STDLIBMINOR_LLVM_CPP
#	define X4STDLIBMINOR_LLVM_CPP (_LIBCPP_VERSION % 10000 / 100)

#	undef X4STDLIBPATCH_LLVM_CPP
#	define X4STDLIBPATCH_LLVM_CPP (_LIBCPP_VERSION % 100)
#endif

#if defined(__MSL_CPP__) || defined(__MSL__)
#	undef X4STDLIB_METROWERKS_CPP
#	define X4STDLIB_METROWERKS_CPP 1

#	undef X4STDLIBMAJOR_METROWERKS_CPP
#	undef X4STDLIBMINOR_METROWERKS_CPP
#	undef X4STDLIBPATCH_METROWERKS_CPP
#	ifdef __MSL_CPP__
#		define X4STDLIBMAJOR_METROWERKS_CPP (__MSL_CPP__ / 0x1000)
#		define X4STDLIBMINOR_METROWERKS_CPP (__MSL_CPP__ / 0x1000 / 100)
#		define X4STDLIBPATCH_METROWERKS_CPP (__MSL_CPP__ / 0x100)
#	else
#		define X4STDLIBMAJOR_METROWERKS_CPP (__MSL__ / 0x1000)
#		define X4STDLIBMINOR_METROWERKS_CPP (__MSL__ / 0x1000 / 100)
#		define X4STDLIBPATCH_METROWERKS_CPP (__MSL__ / 0x100)
#	endif
#endif

#if defined(MSIPL_COMPILE_H) || defined(__MSIPL_COMPILE_H)
#	undef X4STDLIB_MODENA_CPP
#	define X4STDLIB_MODENA_CPP 1
#endif

#ifdef __PDOSGEN__
#	undef X4STDLIB_PDP_C
#	define X4STDLIB_PDP_C 1
#endif

#if defined(_RWSTD_VER) || defined(__STD_RWCOMPILER_H__)
#	undef X4STDLIB_ROGUEWAVE_CPP
#	define X4STDLIB_ROGUEWAVE_CPP 1

#	ifdef _RWSTD_VER
#		undef X4STDLIBMAJOR_ROGUEWAVE_CPP
#		undef X4STDLIBMINOR_ROGUEWAVE_CPP
#		undef X4STDLIBMINOR_ROGUEWAVE_CPP
#		if _RWSTD_VER < 0x10000
#			define X4STDLIBMAJOR_ROGUEWAVE_CPP (_RWSTD_VER % 0x1000)
#			define X4STDLIBMINOR_ROGUEWAVE_CPP (_RWSTD_VER % 0x1000 / 10)
#			define X4STDLIBPATCH_ROGUEWAVE_CPP (_RWSTD_VER % 0x10)
#		else
#			define X4STDLIBMAJOR_ROGUEWAVE_CPP (_RWSTD_VER % 0x10000)
#			define X4STDLIBMINOR_ROGUEWAVE_CPP (_RWSTD_VER % 0x10000 / 100)
#			define X4STDLIBPATCH_ROGUEWAVE_CPP (_RWSTD_VER % 0x100)
#		endif
#	endif
#endif

#ifdef __SGI_STL
#	undef X4STDLIB_SGI_CPP
#	define X4STDLIB_SGI_CPP 1

#	undef X4STDLIBMAJOR_SGI_CPP
#	define X4STDLIBMAJOR_SGI_CPP (__SGI_STL / 100)

#	undef X4STDLIBMINOR_SGI_CPP
#	define X4STDLIBMINOR_SGI_CPP (__SGI_STL % 100 / 10)

#	undef X4STDLIBPATCH_SGI_CPP
#	define X4STDLIBPATCH_SGI_CPP (__SGI_STL % 10)
#endif

#ifdef __UCLIBC__
#	undef X4STDLIB_UC_C
#	define X4STDLIB_UC_C 1

#	undef X4STDLIBMAJOR_UC_C
#	define X4STDLIBMAJOR_UC_C __UCLIBC_MAJOR__

#	undef X4STDLIBMINOR_UC_C
#	define X4STDLIBMINOR_UC_C __UCLIBC_MINOR__

#	undef X4STDLIBPATCH_UC_C
#	define X4STDLIBPATCH_UC_C __UCLIBC_SUBLEVEL__
#endif

#ifdef __CTRL_VER
#	undef X4STDLIB_VMS_C
#	define X4STDLIB_VMS_C 1

#	undef X4STDLIBMAJOR_VMS_C
#	define X4STDLIBMAJOR_VMS_C (__CTRL_VER / 10000000)

#	undef X4STDLIBMINOR_VMS_C
#	define X4STDLIBMINOR_VMS_C (__CTRL_VER % 10000000 / 100000)

#	undef X4STDLIBPATCH_VMS_C
#	define X4STDLIBPATCH_VMS_C (__CTRL_VER % 100000)
#endif

#ifdef __LIBREL__
#	undef X4STDLIB_Z_C
#	define X4STDLIB_Z_C 1

#	ifdef __TARGET_LIB__
#		undef X4STDLIBMAJOR_Z_C
#		define X4STDLIBMAJOR_Z_C (__TARGET_LIB__ / 1000000)

#		undef X4STDLIBMINOR_Z_C
#		define X4STDLIBMINOR_Z_C (__TARGET_LIB__ % 1000000 / 10000)

#		undef X4STDLIBPATCH_Z_C
#		define X4STDLIBPATCH_Z_C (__TARGET_LIB__ % 10000)
#	else
#		undef X4STDLIBMAJOR_Z_C
#		define X4STDLIBMAJOR_Z_C (__LIBREL__ / 1000000)

#		undef X4STDLIBMINOR_Z_C
#		define X4STDLIBMINOR_Z_C (__LIBREL__ % 1000000 / 10000)

#		undef X4STDLIBPATCH_Z_C
#		define X4STDLIBPATCH_Z_C (__LIBREL__ % 10000)
#	endif
#endif
