#include <xte/aliases.hpp>
#include <xte/approx_equal.hpp>
#include <xte/detect/feature.hpp>
#include <xte/math/serialize.hpp>
#include <numbers>
#include <limits>

static_assert(xte::stringify_number(123) == "123");
static_assert(xte::stringify_number(-123) == "-123");
static_assert(xte::stringify_number(0) == "0");
static_assert(xte::stringify_number(1) == "1");
static_assert(xte::stringify_number(-1) == "-1");
static_assert(xte::stringify_number(0xFF, 16) == "FF");
static_assert(xte::stringify_number(0b1101, 2) == "1101");
static_assert(xte::stringify_number(0765, 8) == "765");
static_assert(xte::stringify_number(255, 16) == "FF");
static_assert(xte::stringify_number(10, 16) == "A");
static_assert(xte::stringify_number(3, 1) == "111");
static_assert(xte::stringify_number(5, 1) == "11111");
static_assert(xte::stringify_number(-3, 1) == "-111");
static_assert(xte::stringify_number(3, -1) == "10101");
static_assert(xte::stringify_number(1, -1) == "1");
static_assert(xte::stringify_number(2, -1) == "101");
static_assert(xte::stringify_number(-3, -1) == "-10101");
static_assert(xte::stringify_number(10, -10) == "190");
static_assert(xte::stringify_number(-10, -10) == "10");
static_assert(xte::stringify_number(8, -10) == "8");
static_assert(xte::stringify_number(-8, -10) == "12");
static_assert(xte::stringify_number(0) == "0");
static_assert(xte::stringify_number(0, 2) == "0");
static_assert(xte::stringify_number(0, 16) == "0");
static_assert(xte::stringify_number(123, 0) == "0");
static_assert(xte::stringify_number(123.456, 0.0) == "0.0");
static_assert(xte::stringify_number(123.456) == "123.456");
static_assert(xte::stringify_number(0.5) == "0.5");
static_assert(xte::stringify_number(1.0) == "1.0");
static_assert(xte::stringify_number(-123.456) == "-123.456");
static_assert(xte::stringify_number(255.5, 16.0) == "FF.8");
static_assert(xte::stringify_number(16.0625, 16.0) == "10.1");
static_assert(xte::stringify_number(5.5, 2.0) == "101.1");
static_assert(xte::stringify_number(2.75, 2.0) == "10.11");
static_assert(xte::stringify_number(10.5, -10.0) == "191.5");
static_assert(xte::stringify_number(-10.5, -10.0) == "10.5");
static_assert(xte::stringify_number(8.25, -10.0) == "9.85");
static_assert(xte::stringify_number(5.0, -2.0) == "101.0");
static_assert(xte::stringify_number(-5.0, -2.0) == "1111.0");
static_assert(xte::stringify_number(6.5, -2.0) == "11011.1");
static_assert(xte::stringify_number(0.5, 0.5) == "10.0");
static_assert(xte::stringify_number(1.0, std::numbers::phi) == "1.0");
static_assert(xte::stringify_number(42.0, std::numbers::phi) == "10100010.00100001");
static_assert(xte::stringify_number(123.456, 10.0, {}, 0) == "123.");
static_assert(xte::parse_number<int>(xte::stringify_number(123)) == 123);
static_assert(xte::parse_number<int>(xte::stringify_number(-123)) == -123);
static_assert(xte::parse_number<int>(xte::stringify_number(0)) == 0);
static_assert(xte::parse_number<int>(xte::stringify_number(255, 16), 16) == 255);
static_assert(xte::parse_number<int>(xte::stringify_number(13, 2), 2) == 13);
static_assert(xte::parse_number<int>(xte::stringify_number(63, 8), 8) == 63);
static_assert(xte::parse_number<int>(xte::stringify_number(3, 1), 1) == 3);
static_assert(xte::parse_number<int>(xte::stringify_number(5, 1), 1) == 5);
static_assert(xte::parse_number<int>(xte::stringify_number(3, -1), -1) == 3);
static_assert(xte::parse_number<int>(xte::stringify_number(1, -1), -1) == 1);
static_assert(xte::parse_number<int>(xte::stringify_number(2, -1), -1) == 2);
static_assert(xte::parse_number<int>(xte::stringify_number(10, -10), -10) == 10);
static_assert(xte::parse_number<int>(xte::stringify_number(-10, -10), -10) == -10);
static_assert(xte::parse_number<int>(xte::stringify_number(8, -10), -10) == 8);
static_assert(xte::parse_number<int>(xte::stringify_number(-8, -10), -10) == -8);
static_assert(xte::parse_number<unsigned>(xte::stringify_number(0xDEADBEEF, 16u), 16u) == 0xDEADBEEF);
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(123.456)), 123.456));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(0.5)), 0.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-123.456)), -123.456));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(255.5, 16.0), 16.0), 255.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(5.5, 2.0), 2.0), 5.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(2.5, 2.5), 2.5), 2.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(3.5, 3.5), 3.5), 3.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(7.0, 3.5), 3.5), 7.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.0, 3.5), 3.5), 10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(100.0, 7.5), 7.5), 100.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.5, 1.5), 1.5), 1.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.0, 0.5), 0.5), 1.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(123.0, 0.5), 0.5), 123.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.0, -0.5), -0.5), 1.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(123.0, -0.5), -0.5), 123.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-2.0, -0.5), -0.5), -2.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-5.0, -0.5), -0.5), -5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.5, -0.5), -0.5), 1.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-1.5, -0.5), -0.5), -1.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(0.1, -0.5), -0.5), 0.1));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(5.0, -2.5), -2.5), 5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.0, -3.5), -3.5), 10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-5.0, -2.5), -2.5), -5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-10.0, -3.5), -3.5), -10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(100.0, -10.0), -10.0), 100.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-100.0, -10.0), -10.0), -100.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(15.5, -2.0), -2.0), 15.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-15.5, -2.0), -2.0), -15.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.0, -10.0), -10.0), 10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-10.0, -10.0), -10.0), -10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(8.0, -10.0), -10.0), 8.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-8.0, -10.0), -10.0), -8.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.5, -10.0), -10.0), 10.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-10.5, -10.0), -10.0), -10.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(8.25, -10.0), -10.0), 8.25));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(5.0, -2.0), -2.0), 5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-5.0, -2.0), -2.0), -5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(6.5, -2.0), -2.0), 6.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-6.5, -2.0), -2.0), -6.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(374.0, std::numbers::pi), std::numbers::pi), 374.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(42.0, std::numbers::phi), std::numbers::phi), 42.0));
static_assert(xte::stringify_number(std::numeric_limits<double>::infinity()) == "inf");
static_assert(xte::stringify_number(-std::numeric_limits<double>::infinity()) == "-inf");
static_assert(xte::stringify_number(std::numeric_limits<double>::quiet_NaN()) == "NaN");
static_assert(xte::stringify_number(-std::numeric_limits<double>::quiet_NaN()) == "NaN");



static_assert(xte::parse_number<int>("123") == 123);
static_assert(xte::parse_number<int>("+123") == 123);
static_assert(xte::parse_number<int>("-123") == -123);
static_assert(xte::parse_number<int>("FF", 16) == 0xFF);
static_assert(xte::parse_number<int>("1101", 2) == 0b1101);
static_assert(xte::parse_number<int>("765", 8) == 0765);
static_assert(xte::parse_number<int>("111", 1) == 3);
static_assert(xte::parse_number<int>("10101", -1) == 3);
static_assert(xte::parse_number<int>("101010", -1) == -3);
static_assert(xte::parse_number<int>("-10101", -1) == -3);
static_assert(xte::parse_number<int>("12", -10) == -8);
static_assert(xte::parse_number<int>("10", -10) == -10);
static_assert(xte::parse_number<int>("0") == 0);
static_assert(xte::parse_number<int>("") == 0);
static_assert(xte::parse_number<int>("123", 0) == 0);
static_assert(xte::parse_number<int>("+") == 0);
static_assert(xte::parse_number<int>("-") == 0);
static_assert(xte::parse_number<int>("123.456") == 123);
static_assert(xte::parse_number<int>("123abc") == 123);
#if XTE_HAS_INT_8
static_assert(xte::parse_number<xte::u8>("256") == 0);
static_assert(xte::parse_number<xte::u8>("256", 10, {}, false) == 25);
static_assert(xte::parse_number<xte::i8>("128") == -128);
static_assert(xte::parse_number<xte::i8>("-128") == -128);
static_assert(xte::parse_number<xte::i8>("-129", 10, {}, false) == -12);
#endif
static_assert(xte::parse_number<unsigned>("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", 16) == -1u);
static_assert(xte::parse_number<int>("190", -10) == 10);
static_assert(xte::parse_number<int>("101", -2) == 5);
static_assert(xte::parse_number<int>("1111", -2) == -5);
static_assert(xte::approx_equal(xte::parse_number<double>("123.456"), 123.456));
static_assert(xte::approx_equal(xte::parse_number<double>(".5"), 0.5));
static_assert(xte::approx_equal(xte::parse_number<double>("1."), 1.0));
static_assert(xte::approx_equal(xte::parse_number<double>("123.456e78"), 123.456e78));
static_assert(xte::approx_equal(xte::parse_number<double>("123.456e+78"), 123.456e78));
static_assert(xte::approx_equal(xte::parse_number<double>("123.456e-78"), 123.456e-78));
static_assert(xte::approx_equal(xte::parse_number<double>("123.456e"), 123.456));
static_assert(xte::approx_equal(xte::parse_number<double>("FF.FF", 16), 255.0 + 255.0 / 256.0));
static_assert(xte::approx_equal(xte::parse_number<double>("10", 2.5), 2.5));
static_assert(xte::approx_equal(xte::parse_number<double>("11", 2.5), 3.5));
static_assert(xte::approx_equal(xte::parse_number<double>("123.456.789"), 123.456));
static_assert(xte::approx_equal(xte::parse_number<double>("1e2e3"), 1e2));
static_assert(xte::approx_equal(xte::parse_number<double>("1e"), 1));
static_assert(xte::approx_equal(xte::parse_number<double>("1e+"), 1));
static_assert(xte::approx_equal(xte::parse_number<double>("1e-"), 1));
static_assert(xte::approx_equal(xte::parse_number<double>("20", 3.5), 7.0));
static_assert(xte::approx_equal(xte::parse_number<double>("23", 3.5), 10.0));
static_assert(xte::approx_equal(xte::parse_number<double>("32", 3.5), 12.5));
static_assert(xte::approx_equal(xte::parse_number<double>("0.1", 0.5), 2.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.01", 0.5), 4.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.11", 0.5), 6.0));
static_assert(xte::approx_equal(xte::parse_number<double>("1", 0.5), 1.0));
static_assert(xte::approx_equal(xte::parse_number<double>("1.1", 0.5), 3.0));
static_assert(xte::approx_equal(xte::parse_number<double>("1.101111", 0.5), 123.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.1", -0.5), 2.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.01", -0.5), 4.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.11", -0.5), 6.0));
static_assert(xte::approx_equal(xte::parse_number<double>("-0.1", -0.5), -2.0));
static_assert(xte::approx_equal(xte::parse_number<double>("1.1", -0.5), 3.0));
static_assert(xte::approx_equal(xte::parse_number<double>("-1.1", -0.5), -3.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.001", -0.5), 8.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.111", -0.5), 14.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.0001", -0.5), 16.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0", -0.5), 0.0));
static_assert(xte::approx_equal(xte::parse_number<double>("1", -0.5), 1.0));
static_assert(xte::approx_equal(xte::parse_number<double>("-1", -0.5), -1.0));
static_assert(xte::approx_equal(xte::parse_number<double>("0.0101", -0.5), 20.0));
static_assert(xte::approx_equal(xte::parse_number<double>("191.5", -10.0), 10.5));
static_assert(xte::approx_equal(xte::parse_number<double>("10.5", -10.0), -10.5));
static_assert(xte::approx_equal(xte::parse_number<double>("9.85", -10.0), 8.25));
static_assert(xte::approx_equal(xte::parse_number<double>("11011.1", -2.0), 6.5));
static_assert(xte::approx_equal(xte::parse_number<double>("1110.1", -2.0), -6.5));
static_assert(xte::approx_equal(xte::parse_number<double>("20", -2.5), 5.0));
static_assert(xte::approx_equal(xte::parse_number<double>("-20", -2.5), -5.0));
static_assert(xte::parse_number<int>.with_index("123").index == 3);
static_assert(xte::parse_number<int>.with_index("-").index == 0);
static_assert(xte::parse_number<double>.with_index("+123.456e-78").index == 12);
