#include <xte/math/approx_equal.hpp>
#include <xte/math/parse_number.hpp>
#include <xte/math/stringify_number.hpp>
#include <numbers>

static_assert(xte::stringify_number(123) == "123");
static_assert(xte::stringify_number(-123) == "-123");
static_assert(xte::stringify_number(0) == "0");
static_assert(xte::stringify_number(1) == "1");
static_assert(xte::stringify_number(-1) == "-1");
static_assert(xte::stringify_number(0xFF, 16) == "FF");
static_assert(xte::stringify_number(0b1101, 2) == "1101");
static_assert(xte::stringify_number(0765, 8) == "765");
static_assert(xte::stringify_number(255, 16) == "FF");
static_assert(xte::stringify_number(10, 16) == "A");
static_assert(xte::stringify_number(3, 1) == "111");
static_assert(xte::stringify_number(5, 1) == "11111");
static_assert(xte::stringify_number(-3, 1) == "-111");
static_assert(xte::stringify_number(3, -1) == "10101");
static_assert(xte::stringify_number(1, -1) == "1");
static_assert(xte::stringify_number(2, -1) == "101");
static_assert(xte::stringify_number(-3, -1) == "-10101");
static_assert(xte::stringify_number(10, -10) == "190");
static_assert(xte::stringify_number(-10, -10) == "10");
static_assert(xte::stringify_number(8, -10) == "8");
static_assert(xte::stringify_number(-8, -10) == "12");
static_assert(xte::stringify_number(0) == "0");
static_assert(xte::stringify_number(0, 2) == "0");
static_assert(xte::stringify_number(0, 16) == "0");
static_assert(xte::stringify_number(123, 0) == "0");
static_assert(xte::stringify_number(123.456, 0.0) == "0.0");
static_assert(xte::stringify_number(123.456) == "123.456");
static_assert(xte::stringify_number(0.5) == "0.5");
static_assert(xte::stringify_number(1.0) == "1.0");
static_assert(xte::stringify_number(-123.456) == "-123.456");
static_assert(xte::stringify_number(255.5, 16.0) == "FF.8");
static_assert(xte::stringify_number(16.0625, 16.0) == "10.1");
static_assert(xte::stringify_number(5.5, 2.0) == "101.1");
static_assert(xte::stringify_number(2.75, 2.0) == "10.11");
static_assert(xte::stringify_number(10.5, -10.0) == "191.5");
static_assert(xte::stringify_number(-10.5, -10.0) == "10.5");
static_assert(xte::stringify_number(8.25, -10.0) == "9.85");
static_assert(xte::stringify_number(5.0, -2.0) == "101.0");
static_assert(xte::stringify_number(-5.0, -2.0) == "1111.0");
static_assert(xte::stringify_number(6.5, -2.0) == "11011.1");
static_assert(xte::stringify_number(0.5, 0.5) == "10.0");
static_assert(xte::stringify_number(1.0, std::numbers::phi) == "1.0");
static_assert(xte::stringify_number(42.0, std::numbers::phi) == "10100010.00100001");
static_assert(xte::stringify_number(123.456, 10.0, {}, 0) == "123.");
static_assert(xte::parse_number<int>(xte::stringify_number(123)) == 123);
static_assert(xte::parse_number<int>(xte::stringify_number(-123)) == -123);
static_assert(xte::parse_number<int>(xte::stringify_number(0)) == 0);
static_assert(xte::parse_number<int>(xte::stringify_number(255, 16), 16) == 255);
static_assert(xte::parse_number<int>(xte::stringify_number(13, 2), 2) == 13);
static_assert(xte::parse_number<int>(xte::stringify_number(63, 8), 8) == 63);
static_assert(xte::parse_number<int>(xte::stringify_number(3, 1), 1) == 3);
static_assert(xte::parse_number<int>(xte::stringify_number(5, 1), 1) == 5);
static_assert(xte::parse_number<int>(xte::stringify_number(3, -1), -1) == 3);
static_assert(xte::parse_number<int>(xte::stringify_number(1, -1), -1) == 1);
static_assert(xte::parse_number<int>(xte::stringify_number(2, -1), -1) == 2);
static_assert(xte::parse_number<int>(xte::stringify_number(10, -10), -10) == 10);
static_assert(xte::parse_number<int>(xte::stringify_number(-10, -10), -10) == -10);
static_assert(xte::parse_number<int>(xte::stringify_number(8, -10), -10) == 8);
static_assert(xte::parse_number<int>(xte::stringify_number(-8, -10), -10) == -8);
static_assert(xte::parse_number<unsigned>(xte::stringify_number(0xDEADBEEF, 16u), 16u) == 0xDEADBEEF);
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(123.456)), 123.456));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(0.5)), 0.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-123.456)), -123.456));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(255.5, 16.0), 16.0), 255.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(5.5, 2.0), 2.0), 5.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(2.5, 2.5), 2.5), 2.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(3.5, 3.5), 3.5), 3.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(7.0, 3.5), 3.5), 7.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.0, 3.5), 3.5), 10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(100.0, 7.5), 7.5), 100.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.5, 1.5), 1.5), 1.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.0, 0.5), 0.5), 1.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(123.0, 0.5), 0.5), 123.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.0, -0.5), -0.5), 1.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(123.0, -0.5), -0.5), 123.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-2.0, -0.5), -0.5), -2.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-5.0, -0.5), -0.5), -5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(1.5, -0.5), -0.5), 1.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-1.5, -0.5), -0.5), -1.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(0.1, -0.5), -0.5), 0.1));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(5.0, -2.5), -2.5), 5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.0, -3.5), -3.5), 10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-5.0, -2.5), -2.5), -5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-10.0, -3.5), -3.5), -10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(100.0, -10.0), -10.0), 100.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-100.0, -10.0), -10.0), -100.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(15.5, -2.0), -2.0), 15.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-15.5, -2.0), -2.0), -15.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.0, -10.0), -10.0), 10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-10.0, -10.0), -10.0), -10.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(8.0, -10.0), -10.0), 8.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-8.0, -10.0), -10.0), -8.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(10.5, -10.0), -10.0), 10.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-10.5, -10.0), -10.0), -10.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(8.25, -10.0), -10.0), 8.25));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(5.0, -2.0), -2.0), 5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-5.0, -2.0), -2.0), -5.0));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(6.5, -2.0), -2.0), 6.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(-6.5, -2.0), -2.0), -6.5));
static_assert(xte::approx_equal(xte::parse_number<double>(xte::stringify_number(42.0, std::numbers::phi), std::numbers::phi), 42.0));
