export module xieite:units.length;

import :units.Unit;

export namespace xieite::units {
	using Quectometre = xieite::units::Unit<"length", [](auto x) { return x / 1e30; }, [](auto x) { return x * 1e30; }>;
	using Rontometre = xieite::units::Unit<"length", [](auto x) { return x / 1e27; }, [](auto x) { return x * 1e27; }>;
	using Yoctometre = xieite::units::Unit<"length", [](auto x) { return x / 1e24; }, [](auto x) { return x * 1e24; }>;
	using Zeptometre = xieite::units::Unit<"length", [](auto x) { return x / 1e21; }, [](auto x) { return x * 1e21; }>;
	using Attometre = xieite::units::Unit<"length", [](auto x) { return x / 1e18; }, [](auto x) { return x * 1e18; }>;
	using Femtometre = xieite::units::Unit<"length", [](auto x) { return x / 1e15; }, [](auto x) { return x * 1e15; }>;
	using Picometre = xieite::units::Unit<"length", [](auto x) { return x / 1e12; }, [](auto x) { return x * 1e12; }>;
	using Nanometre = xieite::units::Unit<"length", [](auto x) { return x / 1e9; }, [](auto x) { return x * 1e9; }>;
	using Micrometre = xieite::units::Unit<"length", [](auto x) { return x / 1e6; }, [](auto x) { return x * 1e6; }>;
	using Millimetre = xieite::units::Unit<"length", [](auto x) { return x / 1e3; }, [](auto x) { return x * 1e3; }>;
	using Centimetre = xieite::units::Unit<"length", [](auto x) { return x / 1e2; }, [](auto x) { return x * 1e2; }>;
	using Decimetre = xieite::units::Unit<"length", [](auto x) { return x / 1e1; }, [](auto x) { return x * 1e1; }>;
	using Metre = xieite::units::Unit<"length">;
	using Decametre = xieite::units::Unit<"length", [](auto x) { return x * 1e1; }, [](auto x) { return x / 1e1; }>;
	using Hectometre = xieite::units::Unit<"length", [](auto x) { return x * 1e2; }, [](auto x) { return x / 1e2; }>;
	using Kilometre = xieite::units::Unit<"length", [](auto x) { return x * 1e3; }, [](auto x) { return x / 1e3; }>;
	using Megametre = xieite::units::Unit<"length", [](auto x) { return x * 1e6; }, [](auto x) { return x / 1e6; }>;
	using Gigametre = xieite::units::Unit<"length", [](auto x) { return x * 1e9; }, [](auto x) { return x / 1e9; }>;
	using Terametre = xieite::units::Unit<"length", [](auto x) { return x * 1e12; }, [](auto x) { return x / 1e12; }>;
	using Petametre = xieite::units::Unit<"length", [](auto x) { return x * 1e15; }, [](auto x) { return x / 1e15; }>;
	using Exametre = xieite::units::Unit<"length", [](auto x) { return x * 1e18; }, [](auto x) { return x / 1e18; }>;
	using Zettametre = xieite::units::Unit<"length", [](auto x) { return x * 1e21; }, [](auto x) { return x / 1e21; }>;
	using Yottametre = xieite::units::Unit<"length", [](auto x) { return x * 1e24; }, [](auto x) { return x / 1e24; }>;
	using Ronnametre = xieite::units::Unit<"length", [](auto x) { return x * 1e27; }, [](auto x) { return x / 1e27; }>;
	using Quettametre = xieite::units::Unit<"length", [](auto x) { return x * 1e30; }, [](auto x) { return x / 1e30; }>;
	using Twip = xieite::units::Unit<"length", [](auto x) { return x * 0.0254 / 1440.0; }, [](auto x) { return x * 1440.0 / 0.0254; }>;
	using Thou = xieite::units::Unit<"length", [](auto x) { return x * 0.0000254; }, [](auto x) { return x / 0.0000254; }>;
	using Barleycorn = xieite::units::Unit<"length", [](auto x) { return x * 0.0254 / 3.0; }, [](auto x) { return x * 3.0 / 0.0254; }>;
	using Inch = xieite::units::Unit<"length", [](auto x) { return x * 0.0254; }, [](auto x) { return x / 0.0254; }>;
	using Foot = xieite::units::Unit<"length", [](auto x) { return x / 0.3048; }, [](auto x) { return x * 0.3048; }>;
	using Yard = xieite::units::Unit<"length", [](auto x) { return x * 0.9144; }, [](auto x) { return x / 0.9144; }>;
	using Chain = xieite::units::Unit<"length", [](auto x) { return x * 20.1168; }, [](auto x) { return x / 20.1168; }>;
	using Furlong = xieite::units::Unit<"length", [](auto x) { return x * 201.168; }, [](auto x) { return x / 201.168; }>;
	using Mile = xieite::units::Unit<"length", [](auto x) { return x * 1609.344; }, [](auto x) { return x / 1609.344; }>;
	using League = xieite::units::Unit<"length", [](auto x) { return x * 4828.032; }, [](auto x) { return x / 4828.032; }>;
	using Fathom = xieite::units::Unit<"length", [](auto x) { return x * 1.8288; }, [](auto x) { return x / 1.8288; }>;
	using Cable = xieite::units::Unit<"length", [](auto x) { return x * 185.2; }, [](auto x) { return x / 185.2; }>;
	using NauticalMile = xieite::units::Unit<"length", [](auto x) { return x * 1852.0; }, [](auto x) { return x / 1852.0; }>;
	using NauticalLeague = xieite::units::Unit<"length", [](auto x) { return x * 5556.0; }, [](auto x) { return x / 5556.0; }>;
	using Link = xieite::units::Unit<"length", [](auto x) { return x * 0.201168; }, [](auto x) { return x / 0.201168; }>;
	using Rod = xieite::units::Unit<"length", [](auto x) { return x * 5.0292; }, [](auto x) { return x / 5.0292; }>;
	using Perch = xieite::units::Rod;
	using Pole = xieite::units::Rod;
	using Lug = xieite::units::Rod;
}
