export module xieite:units.volume;

import :units.Unit;

export namespace xieite::units {
	using CubicQuectometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e90; }, [](auto x) { return x * 1e90; }>;
	using CubicRontometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e81; }, [](auto x) { return x * 1e81; }>;
	using CubicYoctometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e72; }, [](auto x) { return x * 1e72; }>;
	using CubicZeptometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e63; }, [](auto x) { return x * 1e63; }>;
	using CubicAttometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e54; }, [](auto x) { return x * 1e54; }>;
	using CubicFemtometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e45; }, [](auto x) { return x * 1e45; }>;
	using CubicPicometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e36; }, [](auto x) { return x * 1e36; }>;
	using CubicNanometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e27; }, [](auto x) { return x * 1e27; }>;
	using CubicMicrometre = xieite::units::Unit<"volume", [](auto x) { return x / 1e18; }, [](auto x) { return x * 1e18; }>;
	using CubicMillimetre = xieite::units::Unit<"volume", [](auto x) { return x / 1e9; }, [](auto x) { return x * 1e9; }>;
	using CubicCentimetre = xieite::units::Unit<"volume", [](auto x) { return x / 1e6; }, [](auto x) { return x * 1e6; }>;
	using CubicDecimetre = xieite::units::Unit<"volume", [](auto x) { return x / 1e3; }, [](auto x) { return x * 1e3; }>;
	using CubicMetre = xieite::units::Unit<"volume">;
	using CubicDecametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e3; }, [](auto x) { return x / 1e3; }>;
	using CubicHectometre = xieite::units::Unit<"volume", [](auto x) { return x * 1e6; }, [](auto x) { return x / 1e6; }>;
	using CubicKilometre = xieite::units::Unit<"volume", [](auto x) { return x * 1e9; }, [](auto x) { return x / 1e9; }>;
	using CubicMegametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e18; }, [](auto x) { return x / 1e18; }>;
	using CubicGigametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e27; }, [](auto x) { return x / 1e27; }>;
	using CubicTerametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e36; }, [](auto x) { return x / 1e36; }>;
	using CubicPetametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e45; }, [](auto x) { return x / 1e45; }>;
	using CubicExametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e54; }, [](auto x) { return x / 1e54; }>;
	using CubicZettametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e63; }, [](auto x) { return x / 1e63; }>;
	using CubicYottametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e72; }, [](auto x) { return x / 1e72; }>;
	using CubicRonnametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e81; }, [](auto x) { return x / 1e81; }>;
	using CubicQuettametre = xieite::units::Unit<"volume", [](auto x) { return x * 1e90; }, [](auto x) { return x / 1e90; }>;
	using CubicInch = xieite::units::Unit<"volume", [](auto x) { return x / 61023.744095; }, [](auto x) { return x * 61023.744095; }>;
	using CubicFoot = xieite::units::Unit<"volume", [](auto x) { return x / 35.314666721; }, [](auto x) { return x * 35.314666721; }>;
	using CubicYard = xieite::units::Unit<"volume", [](auto x) { return x / 1.3079506193; }, [](auto x) { return x * 1.3079506193; }>;
	using CubicMile = xieite::units::Unit<"volume", [](auto x) { return x / 4168181825.440579584; }, [](auto x) { return x * 4168181825.440579584; }>;
	using Quectolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e33; }, [](auto x) { return x * 1e33; }>;
	using Rontolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e30; }, [](auto x) { return x * 1e30; }>;
	using Yoctolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e27; }, [](auto x) { return x * 1e27; }>;
	using Zeptolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e24; }, [](auto x) { return x * 1e24; }>;
	using Attolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e21; }, [](auto x) { return x * 1e21; }>;
	using Femtolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e18; }, [](auto x) { return x * 1e18; }>;
	using Picolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e15; }, [](auto x) { return x * 1e15; }>;
	using Nanolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e12; }, [](auto x) { return x * 1e12; }>;
	using Microlitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e9; }, [](auto x) { return x * 1e9; }>;
	using Millilitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e6; }, [](auto x) { return x * 1e6; }>;
	using Centilitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e5; }, [](auto x) { return x * 1e5; }>;
	using Decilitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e4; }, [](auto x) { return x * 1e4; }>;
	using Litre = xieite::units::Unit<"volume", [](auto x) { return x / 1e3; }, [](auto x) { return x * 1e3; }>;
	using Decalitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e2; }, [](auto x) { return x * 1e2; }>;
	using Hectolitre = xieite::units::Unit<"volume", [](auto x) { return x / 1e1; }, [](auto x) { return x * 1e1; }>;
	using Kilolitre = xieite::units::CubicMetre;
	using Megalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e3; }, [](auto x) { return x / 1e3; }>;
	using Gigalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e6; }, [](auto x) { return x / 1e6; }>;
	using Teralitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e9; }, [](auto x) { return x / 1e9; }>;
	using Petalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e12; }, [](auto x) { return x / 1e12; }>;
	using Exalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e15; }, [](auto x) { return x / 1e15; }>;
	using Zettalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e18; }, [](auto x) { return x / 1e18; }>;
	using Yottalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e21; }, [](auto x) { return x / 1e21; }>;
	using Ronnalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e24; }, [](auto x) { return x / 1e24; }>;
	using Quettalitre = xieite::units::Unit<"volume", [](auto x) { return x * 1e27; }, [](auto x) { return x / 1e27; }>;
	using FluidOunce = xieite::units::Unit<"volume", [](auto x) { return x / 33814.022702; }, [](auto x) { return x * 33814.022702; }>;
	using Gill = xieite::units::Unit<"volume", [](auto x) { return x / 7039.0159455708; }, [](auto x) { return x * 7039.0159455708; }>;
	using Cup = xieite::units::Unit<"volume", [](auto x) { return x / 3519.5079727854; }, [](auto x) { return x * 3519.5079727854; }>;
	using Pint = xieite::units::Unit<"volume", [](auto x) { return x / 1759.7539863927; }, [](auto x) { return x * 1759.7539863927; }>;
	using Quart = xieite::units::Unit<"volume", [](auto x) { return x / 879.87699319635; }, [](auto x) { return x * 879.87699319635; }>;
	using Gallon = xieite::units::Unit<"volume", [](auto x) { return x / 219.9691574; }, [](auto x) { return x * 219.9691574; }>;
}
