#ifndef DETAIL_XTE_XTE_HEADER_DIAGNOSTIC
#	define DETAIL_XTE_XTE_HEADER_DIAGNOSTIC
#
#	include "./detect/compiler.hpp"
#	include "./detect/feature.hpp"
#
#	if !XTE_HAS_SEQ_ITER
#		warning unsupported preprocessor
#	endif
#
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_INFO(MESSAGE) XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE)
#	elif XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_INFO(MESSAGE) XTE_DIAGNOSTIC_INFO_CLANG(MESSAGE)
#	elif XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_INFO(MESSAGE) XTE_DIAGNOSTIC_INFO_GCC(MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_INFO(MESSAGE)
#	endif
#	if XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_INFO_GCC(MESSAGE) DETAIL_XTE_DIAGNOSTIC_PRAGMA(message MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_INFO_GCC(MESSAGE)
#	endif
#	if XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_INFO_CLANG(MESSAGE) DETAIL_XTE_DIAGNOSTIC_PRAGMA(message MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_INFO_CLANG(MESSAGE)
#	endif
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE) DETAIL_XTE_DIAGNOSTIC_PRAGMA(message(MESSAGE))
#	else
#		define XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE)
#	endif
#
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_WARN(MESSAGE) XTE_DIAGNOSTIC_WARN_MSVC(MESSAGE)
#	elif XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_WARN(MESSAGE) XTE_DIAGNOSTIC_WARN_CLANG(MESSAGE)
#	elif XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_WARN(MESSAGE) XTE_DIAGNOSTIC_WARN_GCC(MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_WARN(MESSAGE)
#	endif
#	if XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_WARN_GCC(MESSAGE) DETAIL_XTE_DIAGNOSTIC_PRAGMA(GCC warning MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_WARN_GCC(MESSAGE)
#	endif
#	if XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_WARN_CLANG(MESSAGE) DETAIL_XTE_DIAGNOSTIC_PRAGMA(GCC warning MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_WARN_CLANG(MESSAGE)
#	endif
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_WARN_MSVC(MESSAGE) XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_WARN_MSVC(MESSAGE)
#	endif
#
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_ERROR(MESSAGE) XTE_DIAGNOSTIC_ERROR_MSVC(MESSAGE)
#	elif XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_ERROR(MESSAGE) XTE_DIAGNOSTIC_ERROR_CLANG(MESSAGE)
#	elif XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_ERROR(MESSAGE) XTE_DIAGNOSTIC_ERROR_GCC(MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_ERROR(MESSAGE)
#	endif
#	if XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_ERROR_GCC(MESSAGE) DETAIL_XTE_DIAGNOSTIC_PRAGMA(GCC error MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_ERROR_GCC(MESSAGE)
#	endif
#	if XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_ERROR_CLANG(MESSAGE) DETAIL_XTE_DIAGNOSTIC_PRAGMA(GCC error MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_ERROR_CLANG(MESSAGE)
#	endif
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_ERROR_MSVC(MESSAGE) XTE_DIAGNOSTIC_INFO_MSVC(MESSAGE)
#	else
#		define XTE_DIAGNOSTIC_ERROR_MSVC(MESSAGE)
#	endif
#
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_PUSH(ID_SEQ, ...) XTE_DIAGNOSTIC_PUSH_MSVC(ID_SEQ##__VA_ARGS__)
#	elif XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_PUSH(ID_SEQ, ...) XTE_DIAGNOSTIC_PUSH_CLANG(ID_SEQ##__VA_ARGS__)
#	elif XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_PUSH(ID_SEQ, ...) XTE_DIAGNOSTIC_PUSH_GCC(ID_SEQ##__VA_ARGS__)
#	else
#		define XTE_DIAGNOSTIC_PUSH(ID_SEQ)
#	endif
#	if XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_PUSH_GCC(ID_SEQ, ...) _Pragma("GCC diagnostic push")DETAIL_XTE_DIAGNOSTIC_SET ID_SEQ##__VA_ARGS__()
#	else
#		define XTE_DIAGNOSTIC_PUSH_GCC(ID_SEQ)
#	endif
#	if XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_PUSH_CLANG(ID_SEQ, ...) _Pragma("clang diagnostic push")DETAIL_XTE_DIAGNOSTIC_SET ID_SEQ##__VA_ARGS__()
#	else
#		define XTE_DIAGNOSTIC_PUSH_CLANG(ID_SEQ)
#	endif
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_PUSH_MSVC(ID_SEQ, ...) _Pragma("warning(push)")DETAIL_XTE_DIAGNOSTIC_SET ID_SEQ##__VA_ARGS__()
#	else
#		define XTE_DIAGNOSTIC_PUSH_MSVC(ID_SEQ)
#	endif
#
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_POP() XTE_DIAGNOSTIC_POP_MSVC()
#	elif XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_POP() XTE_DIAGNOSTIC_POP_CLANG()
#	elif XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_POP() XTE_DIAGNOSTIC_POP_GCC()
#	else
#		define XTE_DIAGNOSTIC_POP()
#	endif
#	if XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_POP_GCC() _Pragma("GCC diagnostic pop")
#	else
#		define XTE_DIAGNOSTIC_POP_GCC()
#	endif
#	if XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_POP_CLANG() _Pragma("clang diagnostic pop")
#	else
#		define XTE_DIAGNOSTIC_POP_CLANG()
#	endif
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_POP_MSVC() _Pragma("warning(pop)")
#	else
#		define XTE_DIAGNOSTIC_POP_MSVC()
#	endif
#
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_SET(ID_SEQ, ...) XTE_DIAGNOSTIC_SET_MSVC(ID_SEQ##__VA_ARGS__)
#	elif XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_SET(ID_SEQ, ...) XTE_DIAGNOSTIC_SET_CLANG(ID_SEQ##__VA_ARGS__)
#	elif XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_SET(ID_SEQ, ...) XTE_DIAGNOSTIC_SET_GCC(ID_SEQ##__VA_ARGS__)
#	else
#		define XTE_DIAGNOSTIC_SET(ID_SEQ)
#	endif
#	if XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_SET_GCC(ID_SEQ, ...) DETAIL_XTE_DIAGNOSTIC_SET ID_SEQ##__VA_ARGS__()
#	else
#		define XTE_DIAGNOSTIC_SET_GCC(ID_SEQ)
#	endif
#	if XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_SET_CLANG(ID_SEQ, ...) DETAIL_XTE_DIAGNOSTIC_SET ID_SEQ##__VA_ARGS__()
#	else
#		define XTE_DIAGNOSTIC_SET_CLANG(ID_SEQ)
#	endif
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_SET_MSVC(ID_SEQ, ...) DETAIL_XTE_DIAGNOSTIC_SET ID_SEQ##__VA_ARGS__()
#	else
#		define XTE_DIAGNOSTIC_SET_MSVC(ID_SEQ)
#	endif
#
#	if XTE_COMPILER_MSVC
#		define XTE_DIAGNOSTIC_ID_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_ENABLE(5030)
#		define XTE_DIAGNOSTIC_ID_ERROR_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_ENFORCE(5030)
#		define XTE_DIAGNOSTIC_ID_NO_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_IGNORE(5030)
#
#		define XTE_DIAGNOSTIC_ID_CONVERSION DETAIL_XTE_DIAGNOSTIC_ENABLE(4244 4245 4267 4305 4365 4389 4800 4804 4805 4806)
#		define XTE_DIAGNOSTIC_ID_ERROR_CONVERSION DETAIL_XTE_DIAGNOSTIC_ENFORCE(4244 4245 4267 4305 4365 4389 4800 4804 4805 4806)
#		define XTE_DIAGNOSTIC_ID_NO_CONVERSION DETAIL_XTE_DIAGNOSTIC_IGNORE(4244 4245 4267 4305 4365 4389 4800 4804 4805 4806)
#
#		define XTE_DIAGNOSTIC_ID_DEPRECATED DETAIL_XTE_DIAGNOSTIC_ENABLE(4996)
#		define XTE_DIAGNOSTIC_ID_ERROR_DEPRECATED DETAIL_XTE_DIAGNOSTIC_ENFORCE(4996)
#		define XTE_DIAGNOSTIC_ID_NO_DEPRECATED DETAIL_XTE_DIAGNOSTIC_IGNORE(4996)
#
#		define XTE_DIAGNOSTIC_ID_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_ENABLE(4180 5266)
#		define XTE_DIAGNOSTIC_ID_ERROR_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_ENFORCE(4180 5266)
#		define XTE_DIAGNOSTIC_ID_NO_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_IGNORE(4180 5266)
#
#		define XTE_DIAGNOSTIC_ID_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_ENABLE(5262)
#		define XTE_DIAGNOSTIC_ID_ERROR_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_ENFORCE(5262)
#		define XTE_DIAGNOSTIC_ID_NO_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_IGNORE(5262)
#
#		define XTE_DIAGNOSTIC_ID_INTERFERENCE_SIZE
#		define XTE_DIAGNOSTIC_ID_ERROR_INTERFERENCE_SIZE
#		define XTE_DIAGNOSTIC_ID_NO_INTERFERENCE_SIZE
#
#		define XTE_DIAGNOSTIC_ID_MISSING_FIELD_INITIALIZERS
#		define XTE_DIAGNOSTIC_ID_ERROR_MISSING_FIELD_INITIALIZERS
#		define XTE_DIAGNOSTIC_ID_NO_MISSING_FIELD_INITIALIZERS
#
#		define XTE_DIAGNOSTIC_ID_NON_TEMPLATE_FRIEND
#		define XTE_DIAGNOSTIC_ID_ERROR_NON_TEMPLATE_FRIEND
#		define XTE_DIAGNOSTIC_ID_NO_NON_TEMPLATE_FRIEND
#
#		define XTE_DIAGNOSTIC_ID_OBJECT_SIZE
#		define XTE_DIAGNOSTIC_ID_ERROR_OBJECT_SIZE
#		define XTE_DIAGNOSTIC_ID_NO_OBJECT_SIZE
#
#		define XTE_DIAGNOSTIC_ID_PARENTHESES DETAIL_XTE_DIAGNOSTIC_ENABLE(4706)
#		define XTE_DIAGNOSTIC_ID_ERROR_PARENTHESES DETAIL_XTE_DIAGNOSTIC_ENFORCE(4706)
#		define XTE_DIAGNOSTIC_ID_NO_PARENTHESES DETAIL_XTE_DIAGNOSTIC_IGNORE(4706)
#
#		define XTE_DIAGNOSTIC_ID_SFINAE_INCOMPLETE
#		define XTE_DIAGNOSTIC_ID_ERROR_SFINAE_INCOMPLETE
#		define XTE_DIAGNOSTIC_ID_NO_SFINAE_INCOMPLETE
#
#		define XTE_DIAGNOSTIC_ID_SHADOW DETAIL_XTE_DIAGNOSTIC_ENABLE(4456 4457 4458 4459)
#		define XTE_DIAGNOSTIC_ID_ERROR_SHADOW DETAIL_XTE_DIAGNOSTIC_ENFORCE(4456 4457 4458 4459)
#		define XTE_DIAGNOSTIC_ID_NO_SHADOW DETAIL_XTE_DIAGNOSTIC_IGNORE(4456 4457 4458 4459)
#
#		define XTE_DIAGNOSTIC_ID_SWITCH DETAIL_XTE_DIAGNOSTIC_ENABLE(4062)
#		define XTE_DIAGNOSTIC_ID_ERROR_SWITCH DETAIL_XTE_DIAGNOSTIC_ENFORCE(4062)
#		define XTE_DIAGNOSTIC_ID_NO_SWITCH DETAIL_XTE_DIAGNOSTIC_IGNORE(4062)
#
#		define XTE_DIAGNOSTIC_ID_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_ENABLE(4806 4807)
#		define XTE_DIAGNOSTIC_ID_ERROR_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_ENFORCE(4806 4807)
#		define XTE_DIAGNOSTIC_ID_NO_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_IGNORE(4806 4807)
#
#		define XTE_DIAGNOSTIC_ID_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_ENABLE(4700 4701 4703)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_ENFORCE(4700 4701 4703)
#		define XTE_DIAGNOSTIC_ID_NO_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_IGNORE(4700 4701 4703)
#
#		define XTE_DIAGNOSTIC_ID_UNREACHABLE DETAIL_XTE_DIAGNOSTIC_ENABLE(4702)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNREACHABLE DETAIL_XTE_DIAGNOSTIC_ENFORCE(4702)
#		define XTE_DIAGNOSTIC_ID_NO_UNREACHABLE DETAIL_XTE_DIAGNOSTIC_IGNORE(4702)
#
#		define XTE_DIAGNOSTIC_ID_UNUSED DETAIL_XTE_DIAGNOSTIC_ENABLE(4100 4101 4102 4189 4834 4505 4555)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNUSED DETAIL_XTE_DIAGNOSTIC_ENFORCE(4100 4101 4102 4189 4834 4505 4555)
#		define XTE_DIAGNOSTIC_ID_NO_UNUSED DETAIL_XTE_DIAGNOSTIC_IGNORE(4100 4101 4102 4189 4834 4505 4555)
#
#	elif XTE_COMPILER_CLANG
#		define XTE_DIAGNOSTIC_ID_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wattributes)
#		define XTE_DIAGNOSTIC_ID_ERROR_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wattributes)
#		define XTE_DIAGNOSTIC_ID_NO_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wattributes)
#
#		define XTE_DIAGNOSTIC_ID_CONVERSION DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wconversion)
#		define XTE_DIAGNOSTIC_ID_ERROR_CONVERSION DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wconversion)
#		define XTE_DIAGNOSTIC_ID_NO_CONVERSION DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wconversion)
#
#		define XTE_DIAGNOSTIC_ID_DEPRECATED DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wdeprecated)
#		define XTE_DIAGNOSTIC_ID_ERROR_DEPRECATED DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wdeprecated)
#		define XTE_DIAGNOSTIC_ID_NO_DEPRECATED DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wdeprecated)
#
#		define XTE_DIAGNOSTIC_ID_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wignored-qualifiers)
#		define XTE_DIAGNOSTIC_ID_ERROR_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wignored-qualifiers)
#		define XTE_DIAGNOSTIC_ID_NO_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wignored-qualifiers)
#
#		define XTE_DIAGNOSTIC_ID_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wimplicit-fallthrough)
#		define XTE_DIAGNOSTIC_ID_ERROR_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wimplicit-fallthrough)
#		define XTE_DIAGNOSTIC_ID_NO_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wimplicit-fallthrough)
#
#		define XTE_DIAGNOSTIC_ID_INTERFERENCE_SIZE
#		define XTE_DIAGNOSTIC_ID_ERROR_INTERFERENCE_SIZE
#		define XTE_DIAGNOSTIC_ID_NO_INTERFERENCE_SIZE
#
#		define XTE_DIAGNOSTIC_ID_MISSING_FIELD_INITIALIZERS DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wmissing-field-initializers)
#		define XTE_DIAGNOSTIC_ID_ERROR_MISSING_FIELD_INITIALIZERS DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wmissing-field-initializers)
#		define XTE_DIAGNOSTIC_ID_NO_MISSING_FIELD_INITIALIZERS DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wmissing-field-initializers)
#
#		define XTE_DIAGNOSTIC_ID_NON_TEMPLATE_FRIEND
#		define XTE_DIAGNOSTIC_ID_ERROR_NON_TEMPLATE_FRIEND
#		define XTE_DIAGNOSTIC_ID_NO_NON_TEMPLATE_FRIEND
#
#		define XTE_DIAGNOSTIC_ID_OBJECT_SIZE DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wframe-larger-than)
#		define XTE_DIAGNOSTIC_ID_ERROR_OBJECT_SIZE DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wframe-larger-than)
#		define XTE_DIAGNOSTIC_ID_NO_OBJECT_SIZE DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wframe-larger-than)
#
#		define XTE_DIAGNOSTIC_ID_PARENTHESES DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wparentheses)
#		define XTE_DIAGNOSTIC_ID_ERROR_PARENTHESES DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wparentheses)
#		define XTE_DIAGNOSTIC_ID_NO_PARENTHESES DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wparentheses)
#
#		define XTE_DIAGNOSTIC_ID_SFINAE_INCOMPLETE
#		define XTE_DIAGNOSTIC_ID_ERROR_SFINAE_INCOMPLETE
#		define XTE_DIAGNOSTIC_ID_NO_SFINAE_INCOMPLETE
#
#		define XTE_DIAGNOSTIC_ID_SHADOW DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wshadow)
#		define XTE_DIAGNOSTIC_ID_ERROR_SHADOW DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wshadow)
#		define XTE_DIAGNOSTIC_ID_NO_SHADOW DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wshadow)
#
#		define XTE_DIAGNOSTIC_ID_SWITCH DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wswitch)
#		define XTE_DIAGNOSTIC_ID_ERROR_SWITCH DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wswitch)
#		define XTE_DIAGNOSTIC_ID_NO_SWITCH DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wswitch)
#
#		define XTE_DIAGNOSTIC_ID_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wtype-limits)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wtautological-constant-out-of-range-compare)
#		define XTE_DIAGNOSTIC_ID_ERROR_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wtype-limits)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wtautological-constant-out-of-range-compare)
#		define XTE_DIAGNOSTIC_ID_NO_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wtype-limits)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wtautological-constant-out-of-range-compare)
#
#		define XTE_DIAGNOSTIC_ID_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wuninitialized)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wuninitialized)
#		define XTE_DIAGNOSTIC_ID_NO_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wuninitialized)
#
#		define XTE_DIAGNOSTIC_ID_UNREACHABLE DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wunreachable-code)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNREACHABLE DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wunreachable-code)
#		define XTE_DIAGNOSTIC_ID_NO_UNREACHABLE DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wunreachable-code)
#
#		define XTE_DIAGNOSTIC_ID_UNUSED DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wunused)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNUSED DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wunused)
#		define XTE_DIAGNOSTIC_ID_NO_UNUSED DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wunused)
#
#	elif XTE_COMPILER_GCC
#		define XTE_DIAGNOSTIC_ID_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wattributes)
#		define XTE_DIAGNOSTIC_ID_ERROR_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wattributes)
#		define XTE_DIAGNOSTIC_ID_NO_ATTRIBUTES DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wattributes)
#
#		define XTE_DIAGNOSTIC_ID_CONVERSION DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wconversion)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wsign-conversion)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wfloat-conversion)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wint-to-pointer-cast)
#		define XTE_DIAGNOSTIC_ID_ERROR_CONVERSION DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wconversion)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wsign-conversion)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wfloat-conversion)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wint-to-pointer-cast)
#		define XTE_DIAGNOSTIC_ID_NO_CONVERSION DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wconversion)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wsign-conversion)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wfloat-conversion)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wint-to-pointer-cast)
#
#		define XTE_DIAGNOSTIC_ID_DEPRECATED DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wdeprecated)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wdeprecated-declarations)
#		define XTE_DIAGNOSTIC_ID_ERROR_DEPRECATED DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wdeprecated)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wdeprecated-declarations)
#		define XTE_DIAGNOSTIC_ID_NO_DEPRECATED DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wdeprecated)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wdeprecated-declarations)
#
#		define XTE_DIAGNOSTIC_ID_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wignored-qualifiers)
#		define XTE_DIAGNOSTIC_ID_ERROR_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wignored-qualifiers)
#		define XTE_DIAGNOSTIC_ID_NO_IGNORED_QUALIFIERS DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wignored-qualifiers)
#
#		define XTE_DIAGNOSTIC_ID_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wimplicit-fallthrough)
#		define XTE_DIAGNOSTIC_ID_ERROR_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wimplicit-fallthrough)
#		define XTE_DIAGNOSTIC_ID_NO_FALLTHROUGH DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wimplicit-fallthrough)
#
#		define XTE_DIAGNOSTIC_ID_INTERFERENCE_SIZE DETAIL_XTE_DIAGNOSTIC_ENABLE(-Winterference-size)
#		define XTE_DIAGNOSTIC_ID_ERROR_INTERFERENCE_SIZE DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Winterference-size)
#		define XTE_DIAGNOSTIC_ID_NO_INTERFERENCE_SIZE DETAIL_XTE_DIAGNOSTIC_IGNORE(-Winterference-size)
#
#		define XTE_DIAGNOSTIC_ID_MISSING_FIELD_INITIALIZERS DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wmissing-field-initializers)
#		define XTE_DIAGNOSTIC_ID_ERROR_MISSING_FIELD_INITIALIZERS DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wmissing-field-initializers)
#		define XTE_DIAGNOSTIC_ID_NO_MISSING_FIELD_INITIALIZERS DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wmissing-field-initializers)
#
#		define XTE_DIAGNOSTIC_ID_NON_TEMPLATE_FRIEND DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wnon-template-friend)
#		define XTE_DIAGNOSTIC_ID_ERROR_NON_TEMPLATE_FRIEND DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wnon-template-friend)
#		define XTE_DIAGNOSTIC_ID_NO_NON_TEMPLATE_FRIEND DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wnon-template-friend)
#
#		define XTE_DIAGNOSTIC_ID_OBJECT_SIZE DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wlarger-than=1EB)
#		define XTE_DIAGNOSTIC_ID_ERROR_OBJECT_SIZE DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wlarger-than=1EB)
#		define XTE_DIAGNOSTIC_ID_NO_OBJECT_SIZE DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wno-larger-than)
#
#		define XTE_DIAGNOSTIC_ID_PARENTHESES DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wparentheses)
#		define XTE_DIAGNOSTIC_ID_ERROR_PARENTHESES DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wparentheses)
#		define XTE_DIAGNOSTIC_ID_NO_PARENTHESES DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wparentheses)
#
#		define XTE_DIAGNOSTIC_ID_SHADOW DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wshadow)
#		define XTE_DIAGNOSTIC_ID_ERROR_SHADOW DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wshadow)
#		define XTE_DIAGNOSTIC_ID_NO_SHADOW DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wshadow)
#
#		define XTE_DIAGNOSTIC_ID_SFINAE_INCOMPLETE DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wsfinae-incomplete)
#		define XTE_DIAGNOSTIC_ID_ERROR_SFINAE_INCOMPLETE DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wsfinae-incomplete)
#		define XTE_DIAGNOSTIC_ID_NO_SFINAE_INCOMPLETE DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wsfinae-incomplete)
#
#		define XTE_DIAGNOSTIC_ID_SWITCH DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wswitch)
#		define XTE_DIAGNOSTIC_ID_ERROR_SWITCH DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wswitch)
#		define XTE_DIAGNOSTIC_ID_NO_SWITCH DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wswitch)
#
#		define XTE_DIAGNOSTIC_ID_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wtype-limits)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wbool-compare)
#		define XTE_DIAGNOSTIC_ID_ERROR_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wtype-limits)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wbool-compare)
#		define XTE_DIAGNOSTIC_ID_NO_TYPE_LIMITS DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wtype-limits)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wbool-compare)
#
#		define XTE_DIAGNOSTIC_ID_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wuninitialized)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wuninitialized)
#		define XTE_DIAGNOSTIC_ID_NO_UNINITIALIZED DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wuninitialized)
#
#		define XTE_DIAGNOSTIC_ID_UNREACHABLE
#		define XTE_DIAGNOSTIC_ID_ERROR_UNREACHABLE
#		define XTE_DIAGNOSTIC_ID_NO_UNREACHABLE
#
#		define XTE_DIAGNOSTIC_ID_UNUSED DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wunused-function)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wunused-value)DETAIL_XTE_DIAGNOSTIC_ENABLE(-Wunused-variable)
#		define XTE_DIAGNOSTIC_ID_ERROR_UNUSED DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wunused-function)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wunused-value)DETAIL_XTE_DIAGNOSTIC_ENFORCE(-Wunused-variable)
#		define XTE_DIAGNOSTIC_ID_NO_UNUSED DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wunused-function)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wunused-value)DETAIL_XTE_DIAGNOSTIC_IGNORE(-Wunused-variable)
#	endif
#
#	define DETAIL_XTE_DIAGNOSTIC_PRAGMA(...) _Pragma(#__VA_ARGS__)
#	define DETAIL_XTE_DIAGNOSTIC_SET(...) __VA_OPT__(XTE_DIAGNOSTIC_ID_##__VA_ARGS__ DETAIL_XTE_DIAGNOSTIC_SET_)
#	define DETAIL_XTE_DIAGNOSTIC_SET_(...) __VA_OPT__(XTE_DIAGNOSTIC_ID_##__VA_ARGS__ DETAIL_XTE_DIAGNOSTIC_SET)
#	if XTE_COMPILER_MSVC
#		define DETAIL_XTE_DIAGNOSTIC_ENABLE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(warning(default:__VA_ARGS__))
#	elif XTE_COMPILER_CLANG
#		define DETAIL_XTE_DIAGNOSTIC_ENABLE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(clang diagnostic warning#__VA_ARGS__)
#	elif XTE_COMPILER_GCC
#		define DETAIL_XTE_DIAGNOSTIC_ENABLE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(GCC diagnostic warning#__VA_ARGS__)
#	endif
#	if XTE_COMPILER_MSVC
#		define DETAIL_XTE_DIAGNOSTIC_ENFORCE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(warning(error:__VA_ARGS__))
#	elif XTE_COMPILER_CLANG
#		define DETAIL_XTE_DIAGNOSTIC_ENFORCE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(clang diagnostic error#__VA_ARGS__)
#	elif XTE_COMPILER_GCC
#		define DETAIL_XTE_DIAGNOSTIC_ENFORCE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(GCC diagnostic error#__VA_ARGS__)
#	endif
#	if XTE_COMPILER_MSVC
#		define DETAIL_XTE_DIAGNOSTIC_IGNORE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(warning(disable:__VA_ARGS__))
#	elif XTE_COMPILER_CLANG
#		define DETAIL_XTE_DIAGNOSTIC_IGNORE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(clang diagnostic ignored#__VA_ARGS__)
#	elif XTE_COMPILER_GCC
#		define DETAIL_XTE_DIAGNOSTIC_IGNORE(...) DETAIL_XTE_DIAGNOSTIC_PRAGMA(GCC diagnostic ignored#__VA_ARGS__)
#	endif
#endif
